### ISSUE TITLE
[ MLflow Roadmap ] Environment Variable consolidation and migration

### ISSUE THREAD

**Issue by BenWilson2** [mlflow/mlflow#10039]
### Summary

There are a number of legacy references to directly defined environment variable keys within modules in MLflow. We would like to continue the effort of relocating all of these references to an easily referenced, clearly documented, and centralized location: mlflow.environment_variables.py. 

In the process of doing the relocation of each of these, please adhere to the existing documentation standards within the target destination environment_variables.py, being as verbose as necessary in order to clearly communicate what the environment variable is for and how it should be used, what the available options are (if applicable), and what core MLflow functionality is affected by setting this environment variable. 

If the environment variable declaration is already present in environment_variables.py, then simply replace the reference to the key in the declared file below with the environment variable handler reference (the getter). 

Note: Internal environment variables, such as those defined here: https://github.com/mlflow/mlflow/blob/27f62b02ce7246363d95dcd1b224569efe680f4e/mlflow/server/__init__.py#L21-L27 ***do not to be included*** in this migration of variable definitions. These are set and retrieved by internal MLflow processes and should not be exposed as part of the environment_variables.py. 

- [ ] mlflow.projects.backend.local MLFLOW_S3_ENDPOINT_URL, MLFLOW_S3_IGNORE_TLS
- [ ] mlflow.store.artifact.azure_blob_artifact_repo AZURE_STORAGE_CONNECTION_STRING
- [ ] mlflow.metrics.metrics_definition TIKTOKEN_CACHE_DIR
- [ ] mlflow.store.artifact.s3_artifact_repo MLFLOW_EXPERIMENTAL_S3_SIGNATURE_VERSION
- [ ] mlflow.utils._capture_transformers_modules USE_TORCH, USE_TF
- [ ] mlflow.utils.credentials DATABRICKS_CONFIG_FILE, DATABRICKS_CONFIG_PROFILE
- [ ] mlflow.projects.kubernetes KUBE_MLFLOW_TRACKING_URI
- [ ] mlflow.utils.databricks_utils DATABRICKS_RUNTIME_VERSION
- [ ] mlflow.pyfunc.backend, mlflow.pyfunc.__init__ MLFLOW_HOME
- [ ] mlflow.utils._spark_utils SPARK_DIST_CLASSPATH, PYSPARK_GATEWAY_PORT, PYSPARK_GATEWAY_SECRET

### Notes

- Make sure to open a PR from a **non-master** branch.
- Sign off the commit using the `-s` flag when making a commit:

  ```sh
  git commit -s -m "..."
           # ^^ make sure to use this
  ```

- Include `#{issue_number}` (e.g. `#123`) in the PR description when opening a PR.

**Comment by mkrdip** [comment]
@BenWilson2, may I get this one please? Thanks!

**Comment by BenWilson2** [comment]
@mkrdip You sure can! Thank you for volunteering!

**Comment by sh4x2** [comment]
Hey @mkrdip, could you please let me know if you are still willing to work on this? I would like to take it up if you haven't already made some progress.

**Comment by mkrdip** [comment]
@sh4x2, I am working on this during this holiday period. Thanks for checking in. I'll be done this week and submit my PR.

**Comment by JMLizano** [comment]
Hi @mkrdip, what's the status of this, were you able to make any progress?

**Comment by rahuja23** [comment]
Is there any progress in this? I would like to contribute

**Comment by bmerkle** [comment]
Hi  @JMLizano @BenWilson2 
there seemt to be not much progress, so I would contribute a PR for this issue, ok ?

**Comment by StanleyTuz** [comment]
Hi @JMLizano @BenWilson2, could I be assigned to this? It seems there's not any recent progress and I think I can get this done fairly quickly (first-time contributor).

**Comment by StanleyTuz** [comment]
@BenWilson2 

I notice that all of the environment variables in `mlflow/environment_variables.py` have the identifier prefix `MLFLOW_`, but several (most) in the list for this PR do not have this prefix. Should we 
1. maintain this standard internally, via something like 
```python
MLFLOW_USE_TF = _EnvironmentVariable(
    "USE_TF", str, None
)
```
or
2. keep the internal representation aligned with the exposed env var name, like
```python
USE_TF = _EnvironmentVariable(
    "USE_TF", str, None
)
```

**Comment by StanleyTuz** [comment]
Another question: while working on migrating the env vars in the list provided in this issue, I found some variables that were not listed but may fit the bill for the migration (e.g., `AZURE_STORAGE_ACCESS_KEY`); should I go ahead and migrate these as well?

Similarly, I have found at least one of the listed variables in another module _in addition_ to the one it was listed in above. I am guessing it would be fine to migrate this same variable in that file as well (i.e., use the getter there)?
