### ISSUE TITLE
[ MLflow Roadmap ] Simplify and standardize Spark Session fixture usage

### ISSUE THREAD

**Issue by BenWilson2** [mlflow/mlflow#10045]
### Summary

There are a number of redundant definitions of a `spark_session` constructor sprinkled throughout the test suites within MLflow. Refactoring these to consolidate all references for the creation of a local spark context for use in test suites would be a good step in reducing the complexity of test configuration fixtures. 
The final location for the module-level test suite fixture should be within `tests.utils.test_file_utils`. 

Locations of redundant definitions: 
- [ ] tests.spark.autologging.ml.test_pyspark_ml_autologging
- [ ] tests.evaluate.test_evaluation
- [ ] tests.tensorflow.test_keras_pyfunc_model_works_with_all_input_types

Note that other locations that require distinct configuration changes to the spark session builder should not be refactored as the configuration options defined within them may introduce incompatibilities with the expected default behavior of a spark session. 

### Notes

- Make sure to open a PR from a **non-master** branch.
- Sign off the commit using the `-s` flag when making a commit:

  ```sh
  git commit -s -m "..."
           # ^^ make sure to use this
  ```

- Include `#{issue_number}` (e.g. `#123`) in the PR description when opening a PR.

**Comment by Gekko0114** [comment]
Hi @BenWilson2 ,
Can I work on this issue?

**Comment by BenWilson2** [comment]
@Gekko0114 it's all yours! :D

**Comment by Gekko0114** [comment]
Hi @BenWilson2 ,

I want to clarify what I should do.

Should I simply move this code to `tests.utils.test_file_utils` ?
```python
@pytest.fixture(scope="module")
def spark_session():
    with SparkSession.builder.master("local[*]").getOrCreate() as session:
        yield session
```
Or should I work on other functions as well, like get_iris? Seems that all three files you mentioned use iris dataset.
```python
def get_iris():
    iris = sklearn.datasets.load_iris()
    return iris.data, iris.target
```

**Comment by BenWilson2** [comment]
Hi @Gekko0114 I'd split that up into two different PRs :) But anything that you notice that is a 'generic' test fixture (used by multiple modules), is a candidate for consolidating as a utility fixture.

**Comment by Cokral** [comment]
Hey! Is there still work happening on this? If not, i'd be happy to give it a go :)

**Comment by Gekko0114** [comment]
Please take it. Thanks
