### ISSUE TITLE
[ MLflow Roadmap ] Refactor OS validation checks

### ISSUE THREAD

**Issue by BenWilson2** [mlflow/mlflow#10044]
### Summary

Currently, there are many locations spread through the MLflow code base that perform validations based on the operating system type that MLflow is running within. Nearly all of them have identical logic (although varying implementations), all doing one thing: checking to see if the current OS is Windows-based or not. 

This issue is looking to address this redundant code by remove all references of "os.name != 'nt'" or "os.name == 'nt'" in favor of using the utility function 'mlflow.utils.is_windows()'

These entries typically take the form of a conditional logic check like this:
https://github.com/mlflow/mlflow/blob/4e2c9b08b0632553b3193e76016480abe60714f8/mlflow/utils/string_utils.py#L130-L131

The list of locations that explicitly declare logic for determining if the code is executing within Windows or not:

- [ ] confest.py
- [ ] mlflow.utils.string_utils
- [ ] mlflow.utils.process
- [ ] mlflow.pyfunc.backend
- [ ] mlflow.mleap.__init__
- [ ] mlflow.utils.environment
- [ ] mlflow.projects.backend.local
- [ ] mlflow.utils.conda
- [ ] mlflow.utils.file_utils
- [ ] mlflow.recipes.utils.step
- [ ] mlflow.tracking.artifact_utils
- [ ] mlflow.pyspark.ml.__init__
- [ ] tests.test_import
- [ ] tests.test_cli
- [ ] tests.helper_functions
- [ ] tests.utils.test_process_utils
- [ ] tests_conftest
- [ ] tests.utils.test_requirements_utils
- [ ] tests.tracking.test_mlflow_artifacts

If you would like to tackle one of these, feel free to respond to this issue with the instance that you'd like to refactor and we'll mark that instance with your handle. 

### Notes

- Make sure to open a PR from a **non-master** branch.
- Sign off the commit using the `-s` flag when making a commit:

  ```sh
  git commit -s -m "..."
           # ^^ make sure to use this
  ```

- Include `#{issue_number}` (e.g. `#123`) in the PR description when opening a PR.

**Comment by mkrdip** [comment]
May I take this one, please? @BenWilson2, thanks!

**Comment by manhtaile** [comment]
Hi @BenWilson2. Can I take this ticket? I'm willing to handle this entire checklist
