### ISSUE TITLE
[BUG] Model lineage tracking - missing "MLmodel/registered_model_meta" file

### ISSUE THREAD

**Issue by MajerMartin** [mlflow/mlflow#10230]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Other

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 2.8.0
- Tracking server: 2.3.1

### System information

- Ubuntu 20.04 LTS
- Python 3.8

### Describe the problem

It seems that latest release of MLflow breaks compatibility between client and server when it runs on older version of MLflow.

https://github.com/mlflow/mlflow/commit/85037652d6caf4a78d8ac73ca734e433e86b1fd9

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```
import mlflow
from mlflow.store.artifact.artifact_repository_registry import get_artifact_repository

# server 2.3.1 + client 2.7.1 -> works
# server 2.3.1 + client 2.8.0 -> throws

mlflow.set_tracking_uri('FILL IN')

model_name = 'FILL IN'
model_version = 'FILL IN'
model_uri = f'models:/{model_name}/{model_version}'

artifact_repository = get_artifact_repository(model_uri)
mlmodel_path = artifact_repository.download_artifacts('MLmodel')
```

### Stack trace

```
Traceback (most recent call last):
  File "/app/miniconda/envs/engine/bin/setup-image", line 33, in <module>
    sys.exit(load_entry_point('engine', 'console_scripts', 'setup-image')())
  File "/app/engine/assembly/scripts.py", line 53, in setup_image
    mlmodel_path = artifact_repository.download_artifacts('MLmodel')
  File "/app/miniconda/envs/engine/lib/python3.8/site-packages/mlflow/store/artifact/models_artifact_repo.py", line 173, in download_artifacts
    self._add_registered_model_meta_file(model_path)
  File "/app/miniconda/envs/engine/lib/python3.8/site-packages/mlflow/store/artifact/models_artifact_repo.py", line 143, in _add_registered_model_meta_file
    write_yaml(
  File "/app/miniconda/envs/engine/lib/python3.8/site-packages/mlflow/utils/file_utils.py", line 250, in write_yaml
    raise e
  File "/app/miniconda/envs/engine/lib/python3.8/site-packages/mlflow/utils/file_utils.py", line 240, in write_yaml
    with codecs.open(yaml_file_name, mode="w", encoding=ENCODING) as yaml_file:
  File "/app/miniconda/envs/engine/lib/python3.8/codecs.py", line 905, in open
    file = builtins.open(filename, mode, buffering)
NotADirectoryError: [Errno 20] Not a directory: '/tmp/tmpv6q_d0ps/MLmodel/registered_model_meta'
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/gateway`: AI Gateway service, Gateway client APIs, third-party Gateway integrations
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [X] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@MajerMartin Thanks for reporting the issue. Here's a minimum repro:

```python
import mlflow
from mlflow.store.artifact.artifact_repository_registry import get_artifact_repository

mlflow.set_tracking_uri("sqlite:///:memory:")

with mlflow.start_run():
    mlflow.sklearn.log_model("I am a model", "model", registered_model_name="foo")

model_uri = f"models:/foo/1"

artifact_repository = get_artifact_repository(model_uri)
mlmodel_path = artifact_repository.download_artifacts("MLmodel")

```

**Comment by harupy** [comment]
It looks like the error occurs on the line added in https://github.com/mlflow/mlflow/pull/9402.
