### ISSUE TITLE
[BUG] Anyone can create users without credentials even with basic authentication enabled

### ISSUE THREAD

**Issue by pinarkaymaz6** [mlflow/mlflow#10250]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Other

### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### MLflow version

- Client: 2.7.1
- Tracking server: 2.7.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
NAME="Amazon Linux"
VERSION="2023"
ID="amzn"
ID_LIKE="fedora"
VERSION_ID="2023"
PLATFORM_ID="platform:al2023"
PRETTY_NAME="Amazon Linux 2023"
Kernel: Linux 6.1.49-70.116.amzn2023.x86_64
Architecture: x86-64
- **Python version**:
Python 3.9.16
- **yarn version, if running the dev UI**:
-

### Describe the problem

We have a remote MLFlow server running on AWS EC2. We enabled basic authentication as it is publicly accessible. The problem is that anyone can create a user without any credentials even though we have basic authentication enabled. The created user is able to view the UI dashboard and able to create/remove their own experimentations on our remote server. Creating user should not be allowed without credentials if the basic authentication enabled and even then only users with admin rights should be able to do so.

### Tracking information

**MLFLow Server:**
```shell
mlflow server --host 0.0.0.0 --port 5000 --app-name basic-auth --default-artifact-root s3://{artifact_bucket.bucket_name}
```
>>> mlflow.doctor()
System information: Linux #1 SMP PREEMPT_DYNAMIC Wed Sep  6 22:13:07 UTC 2023
Python version: 3.9.16
MLflow version: 2.7.1
MLflow module location: /mlflow/.venv/lib64/python3.9/site-packages/mlflow/__init__.py
Tracking URI: file:///mlflow/mlruns
Registry URI: file:///mlflow/mlruns
MLflow dependencies:
  Flask: 2.3.3
  Jinja2: 3.1.2
  alembic: 1.12.0
  boto3: 1.28.49
  click: 8.1.7
  cloudpickle: 2.2.1
  databricks-cli: 0.17.8
  docker: 6.1.3
  entrypoints: 0.4
  gitpython: 3.1.37
  gunicorn: 21.2.0
  importlib-metadata: 6.8.0
  markdown: 3.4.4
  matplotlib: 3.8.0
  numpy: 1.26.0
  packaging: 23.1
  pandas: 2.1.1
  protobuf: 4.24.3
  pyarrow: 13.0.0
  pytz: 2023.3.post1
  pyyaml: 6.0.1
  querystring-parser: 1.2.4
  requests: 2.31.0
  scikit-learn: 1.3.1
  scipy: 1.11.2
  sqlalchemy: 2.0.21
  sqlparse: 0.4.4

**MLFLow Client:**
>>> mlflow.doctor()
System information: Darwin Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:43 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6000
Python version: 3.11.5
MLflow version: 2.7.1
MLflow module location: <PATH>/.venv/lib/python3.11/site-packages/mlflow/__init__.py
Tracking URI: <TRACKING_URL>:5000
Registry URI: <TRACKING_URL>:5000
MLflow dependencies: 
  Flask: 2.3.3
  Jinja2: 3.1.2
  alembic: 1.12.0
  boto3: 1.28.49
  click: 8.1.7
  cloudpickle: 2.2.1
  databricks-cli: 0.17.8
  docker: 6.1.3
  entrypoints: 0.4
  fastapi: 0.103.2
  gitpython: 3.1.37
  gunicorn: 21.2.0
  importlib-metadata: 6.8.0
  markdown: 3.4.4
  matplotlib: 3.8.0
  numpy: 1.25.2
  packaging: 23.1
  pandas: 2.1.1
  protobuf: 4.24.3
  psutil: 5.9.6
  pyarrow: 13.0.0
  pydantic: 2.3.0
  pytz: 2023.3.post1
  pyyaml: 6.0.1
  querystring-parser: 1.2.4
  requests: 2.31.0
  scikit-learn: 1.3.1
  scipy: 1.11.3
  sqlalchemy: 2.0.21
  sqlparse: 0.4.4
  uvicorn: 0.23.2
  watchfiles: 0.20.0

### Code to reproduce issue

```
import mlflow
from mlflow.server import get_app_client


mlflow.set_tracking_uri(<TRACKING_URL>)
auth_client = get_app_client("basic-auth", tracking_uri=tracking_url)
auth_client.create_user(username="user12", password="pass12")
```

### Stack trace

```
No warnings or errors. It creates the user.
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/gateway`: AI Gateway service, Gateway client APIs, third-party Gateway integrations
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [X] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [X] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@pinarkaymaz6 can you try 2.8? In 2.8, only admin should be able to add users.

**Comment by pinarkaymaz6** [comment]
Thank you, using the version 2.8 resolved our issue.

**Comment by pinarkaymaz6** [comment]
Upgrading the version to 2.0 resolved our issue. Thank you!
