### ISSUE TITLE
[BUG] Unable to fetch model version for a given alias in Databricks

### ISSUE THREAD

**Issue by g-malamud** [mlflow/mlflow#10269]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Databricks

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

- Client: 2.7.0
- Registry URI: 'databricks-uc'

### System information

- Databricks runtime: 13.3 ML LTS
- Python version: 3.10.12

### Describe the problem

I am unable to fetch the model version using a specified alias. The model is registered to Databricks Unity Catalog. When using the MLFlowClient, I was able to get a list of model versions for a given model name but the list of aliases were empty. 

### Tracking information

```shell
System information: Linux #56~20.04.1-Ubuntu SMP Thu Sep 21 13:01:28 UTC 2023
Python version: 3.10.12
MLflow version: 2.7.0
MLflow module location: /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/mlflow/__init__.py
Tracking URI: databricks
Registry URI: databricks
Databricks runtime version: 13.3.x-cpu-ml-scala2.12
MLflow environment variables: 
  MLFLOW_CONDA_HOME: /databricks/conda
  MLFLOW_GATEWAY_URI: databricks
  MLFLOW_PYTHON_EXECUTABLE: /databricks/spark/scripts/mlflow_python.sh
  MLFLOW_TRACKING_URI: databricks
MLflow dependencies: 
  Flask: 1.1.2+db1
  Jinja2: 2.11.3
  aiohttp: 3.8.5
  alembic: 1.12.1
  azure-storage-file-datalake: 12.12.0
  boto3: 1.24.28
  click: 8.0.4
  cloudpickle: 2.0.0
  databricks-cli: 0.17.7
  docker: 6.1.3
  entrypoints: 0.4
  fastapi: 0.98.0
  gitpython: 3.1.27
  google-cloud-storage: 2.10.0
  gunicorn: 20.1.0
  importlib-metadata: 4.11.3
  markdown: 3.3.4
  matplotlib: 3.5.2
  numpy: 1.21.5
  packaging: 21.3
  pandas: 1.4.4
  protobuf: 3.19.4
  psutil: 5.9.0
  pyarrow: 8.0.0
  pydantic: 1.10.6
  pytz: 2022.1
  pyyaml: 6.0
  querystring-parser: 1.2.4
  requests: 2.28.1
  scikit-learn: 1.1.1
  scipy: 1.9.1
  sqlalchemy: 1.4.39
  sqlparse: 0.4.2
  uvicorn: 0.23.2
  virtualenv: 20.16.3
  watchfiles: 0.19.0
```

### Code to reproduce issue

```
from mlflow.tracking import MlflowClient
client = MlflowClient()
model_version_infos = client.search_model_versions("name = '%s'" % model_name)
```

### Stack trace

```
[<ModelVersion: aliases=[], creation_timestamp=1698862889464, current_stage=None, description='', last_updated_timestamp=1698862892589, name=MODEL_NAME, run_id=RUN_ID, run_link=None, source=SOURCE, status='READY', status_message='', tags={}, user_id=USER', version='8'>,
 <ModelVersion: aliases=[], creation_timestamp=1698824052230, current_stage=None, description='', last_updated_timestamp=1698824054121, name=MODEL_NAME, run_id=RUN_ID, run_link=None, source=SOURCE, status='READY', status_message='', tags={}, user_id=USER, version='7'>, ...]
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/gateway`: AI Gateway service, Gateway client APIs, third-party Gateway integrations
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [X] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment]
@jerrylian-db could you shed some insight here? Thanks!

**Comment by jerrylian-db** [comment]
@g-malamud thanks for filing this! This is a known limitation of the Unity Catalog model registry in Databricks. Due to performance constraints, we don't currently return aliases in model version search responses. We hope to implement this in the future.

**Comment by jerrylian-db** [comment]
Closing this issue since the reported issue is a known limitation.
