### ISSUE TITLE
[FR] Add PolarsDataset

### ISSUE THREAD

**Issue by elenavolkova93** [mlflow/mlflow#10292]
### Willingness to contribute

Yes. I would be willing to contribute this feature with guidance from the MLflow community.

### Proposal Summary

Add `PolarsDataset` class for logging datasets based on [polars](https://www.pola.rs/) dataframes, and a corresponding `.from_polars()` method.

### Motivation

> #### What is the use case for this feature?

To log a Dataset based on a polars dataframe with `mlflow.log_input`.

> #### Why is this use case valuable to support for MLflow users in general?

Polars is a library that's been gaining popularity in data science, as it can be a lot faster and more memory-efficient than pandas, and for some projects it's not an option to convert to pandas or numpy just to create an MLFlow dataset.

> #### Why is this use case valuable to support for your project(s) or organization?

We use polars for faster data loading and preprocessing and would like to use `mlflow.data` to log the datasets.

> #### Why is it currently difficult to achieve this use case?

Not implemented.

### Details

As far as I can see, the implementation is just:
 - adding `PolarsDataset(Dataset)`
 - adding `.from_polars()` function
 - although not strictly required for a minimal working implementation, would be nice to have this as well https://github.com/mlflow/mlflow/issues/7642, which would allow to infer schema of a polars dataset.

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/gateway`: AI Gateway service, Gateway client APIs, third-party Gateway integrations
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by mbignotti** [comment]
Any news on this?

**Comment by nrccua-timr** [comment]
Would be nice to have 💯

**Comment by AlpAribal** [comment]
I would be happy to provide an implementation for this. Which would be the better way forward:
1. adding this implementation to under `mlflow.data`, and hence adding a [possibly-optional] `polars` dependency
2. implementing this as a plugin

**Comment by nrccua-timr** [comment]
@AlpAribal I'd say option 1. adding this implementation to under mlflow.data, and hence adding a [possibly-optional] polars dependency

**Comment by Turkish-coffee** [comment]
hi guys, is there any news about the feature ?

**Comment by obiii** [comment]
Hi, is there any update on this`?

**Comment by ilukibanovaxs** [comment]
Hi, any news on the implementation?

**Comment by IreneYangClari** [comment]
Hi folks, any update on this?

**Comment by pietroppeter** [comment]
I guess this might be another interesting use case for https://github.com/narwhals-dev/narwhals ? :)

**Comment by FBruzzesi** [comment]
Hey there! I know there is already a PR open to support polars, nevertheless I am taking a stab at solving it via Narwhals as suggested by @pietroppeter.

In the first iteration, I will be focusing to add support for eager dataframes (pandas, polars and pyarrow). Possibly in the future it could be used to support other lazy dataframes and not only pyspark.

#13006 was a great head start 🚀

**Comment by FBruzzesi** [comment]
Is there someone we can ping to speed up _any_ feedback for this feature? 😁

**Comment by MarcoGorelli** [comment]
Hi @harupy @B-Step62 - sorry for the direct ping, just wanted to ask if there's any way to get this feature and the active PR #15072 looked at, given the great community interest, thanks 🙏

**Comment by edgBR** [comment]
Please lets get this in!

**Comment by B-Step62** [comment]
Sorry for the late response. We were very occupied for MLflow 3.0 launch and finally get chance to revisit important requests like this...

First of all, thank you so much for the great pull request @FBruzzesi! I have one request to push this effort forward: Is it possible to separate the PR for (1) lazy dataframe support  (2) Polars dataset (3) Arrow dataset? 

I love the idea of supporting lazy evaluation and believe it brings much benefits to users. However, we *cannot* make it a core dependency of dataset feature right now, even I totally understand the effort of making the library very lightweight and stable. MLflow is used as a foundation of managed MLOps platforms such as AzureML, SagMaker, Databricks, and also used by many enterprise users. Therefore, we need a strict stance for introducing any new core dependency.

The way we would like to proceed is:
1. Introduce Polars/Arrow dataset on top of the existing stack.
2. Add lazy dataframe support as an **opt-in** feature. This could be implemented with Narwhals.
3. Once the lazy dataframe feature is adopted widely, we possibly make it default.

**Comment by FBruzzesi** [comment]
Hey @B-Step62 thanks for your reply - I am very excited to see you onboard with the idea of supporting a larger set of both eager and lazy dataframe types.

Let me address your comment step by step (tried my best to keep it in the same sequential order 😊).

---

> Sorry for the late response. We were very occupied for MLflow 3.0 launch and finally get chance to revisit important requests like this...

No need to be sorry - we were a little concerned on the MLFlow interest to support Polars at all.

> First of all, thank you so much for the great pull request [@FBruzzesi](https://github.com/FBruzzesi)! I have one request to push this effort forward: Is it possible to separate the PR for (1) lazy dataframe support (2) Polars dataset (3) Arrow dataset?

For context #15072 deals with (2) and (3) through Narwhals (and it would also already enable cuDF and Modin).

(1) is not addressed _at all_ for now - I would have a few design questions for how to proceed, and I didn't want to invest too much effort ahead of time without discussing some of the details.

> The way we would like to proceed is:
> 
> 1. Introduce Polars/Arrow dataset on top of the existing stack.

Sure, that's what #15072 enables with a unified (generic and parent) class. I would suggest to move the conversation there if it's a likable approach.

On the other hand, if you prefer to have single classes, one for each dataframe library, then you might start with #13006 for Polars support, and Narwhals might not be what you need/want.

> 2. Add lazy dataframe support as an **opt-in** feature. This could be implemented with Narwhals.
> 3. Once the lazy dataframe feature is adopted widely, we possibly make it default.

In my opinion, these require discussion, we could move it to another issue to have better tracking. Just FYI, with Narwhals it might be possible to find a _single_ solution for a few lazy dataframe libraries such as duckdb, dask, ibis (and eventually daft/others). For PySpark, I can see a very tailored solution already, and I would not touch it 😂

> However, we _cannot_ make it a core dependency of dataset feature right now, even I totally understand the effort of making the library very lightweight and stable. MLflow is used as a foundation of managed MLOps platforms such as AzureML, SagMaker, Databricks, and also used by many enterprise users. Therefore, we need a strict stance for introducing any new core dependency.

I perfectly understand wanting to be conservative with the introduction of new dependencies. May I ask if there is an evaluation process from your side, and how would that look like? We can have a call if that helps.

Also FYI, Databricks images already have Narwhals as a dependency through Plotly.
I am not a AzureML nor SageMaker user, so I cannot tell on top on my head.

---

Looking forward to this collaboration 🤗

**Comment by B-Step62** [comment]
> In my opinion, these require discussion, we could move it to another issue to have better tracking. Just FYI, with Narwhals it might be possible to find a single solution for a few lazy dataframe libraries such as duckdb, dask, ibis (and eventually daft/others). For PySpark, I can see a very tailored solution already, and I would not touch it 😂

@FBruzzesi Sure, would you mind filing a separate FR for Narwhals introduction? I totally agree it's beneficial to have a single solution to support wide range of dataframe libraries. We just need to evaluate the blast radius carefully and make sure things are fully backward copmatible.

> Just FYI, with Narwhals it might be possible to find a single solution for a few lazy dataframe libraries such as duckdb, dask, ibis (and eventually daft/others). For PySpark, I can see a very tailored solution already, and I would not touch it 😂

I'm also curious if Narwhals allows us to fix the current "convert everything to Pandas" design. If it provides unified interface while not doing extra data copy and conversion, it sounds very nice to us🙂

> Also FYI, Databricks images already have Narwhals as a dependency through Plotly.

This is great info, thanks for sharing!

**Comment by B-Step62** [comment]
Meanwhile I've merged https://github.com/mlflow/mlflow/pull/13006 to answer the big demand for Polars Dataset support. It will be released in version 3.2.0 mid July.

cc: @mbignotti @nrccua-timr @AlpAribal @Turkish-coffee @obiii @ilukibanovaxs @IreneYangClari @edgBR

**Comment by FBruzzesi** [comment]
Lovely to hear this @B-Step62 - I opened https://github.com/mlflow/mlflow/issues/16518 to move the discussion about Narwhals there. I tried to summarize some of the key features 🤗

**Comment by MarcoGorelli** [comment]
Thanks all for discussion!

> I'm also curious if Narwhals allows us to fix the current "convert everything to Pandas" design. If it provides unified interface while not doing extra data copy and conversion, it sounds very nice to us🙂

Yup, that's exactly the use-case that Narwhals aims to address

When Plotly started using Narwhals, then plotting Polars dataframes often became 10x faster compared with when they converted everything to pandas (source: Plotly's v6.0 blog post https://plotly.com/blog/chart-smarter-not-harder-universal-dataframe-support/)
