### ISSUE TITLE
[BUG] Bump upper bound on pyarrow for `CVE-2023-47248`

### ISSUE THREAD

**Issue by jmahlik** [mlflow/mlflow#10356]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Other

### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### MLflow version

- Client: 2.8.0
- Tracking server: 2.8.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Debian Bookworm
- **Python version**: 3.11
- **yarn version, if running the dev UI**: n/a

### Describe the problem

The upper bound on pyarrow is set at 14 [CVE-2023-47248](https://www.cve.org/CVERecord?id=CVE-2023-47248) applies to <14.  Currently users are unable to upgrade to a fixed version due to [the upper bound](https://github.com/mlflow/mlflow/blob/9648fed26c6193eb504974c367c9ef944ddf0350/requirements/core-requirements.txt#L16) without some hacking around the installation process.

There's some occurrences of `read_parquet` in the source code. I'd imagine most users are reading trusted data, but there's a chance some may be dealing with untrusted parquet data being serialized/de-serialized via datasets.

```shell
git grep -e 'read_parquet' ./mlflow
mlflow/models/evaluation/artifacts.py:        self._content = pd.read_parquet(local_artifact_path)
mlflow/recipes/artifacts.py:            return pd.read_parquet(self._path)
mlflow/recipes/steps/evaluate.py:            test_df = pd.read_parquet(test_df_path)
mlflow/recipes/steps/evaluate.py:            validation_df = pd.read_parquet(validation_df_path)
mlflow/recipes/steps/ingest/__init__.py:from mlflow.utils.file_utils import read_parquet_as_pandas_df
mlflow/recipes/steps/ingest/__init__.py:        ingested_df = read_parquet_as_pandas_df(data_parquet_path=dataset_dst_path)
mlflow/recipes/steps/ingest/datasets.py:    read_parquet_as_pandas_df,
mlflow/recipes/steps/ingest/datasets.py:        return read_parquet_as_pandas_df(data_parquet_path=local_data_file_path)
mlflow/recipes/steps/predict.py:        input_pdf = pd.read_parquet(ingested_data_path)
mlflow/recipes/steps/split.py:        input_df = pd.read_parquet(ingested_data_path)
mlflow/recipes/steps/train.py:            train_df = pd.read_parquet(transformed_training_data_path)
mlflow/recipes/steps/train.py:            validation_df = pd.read_parquet(transformed_validation_data_path)
mlflow/recipes/steps/train.py:            raw_train_df = pd.read_parquet(raw_training_data_path)
mlflow/recipes/steps/train.py:            raw_validation_df = pd.read_parquet(raw_validation_data_path)
mlflow/recipes/steps/transform.py:        train_df = pd.read_parquet(train_data_path)
mlflow/recipes/steps/transform.py:        validation_df = pd.read_parquet(validation_data_path)
mlflow/utils/file_utils.py:def read_parquet_as_pandas_df(data_parquet_path: str):
mlflow/utils/file_utils.py:    return pd.read_parquet(data_parquet_path, engine="pyarrow")
```

### Tracking information

```shell
```

### Code to reproduce issue

```
```

### Stack trace

```
```

### Other info / logs

```
```

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/gateway`: AI Gateway service, Gateway client APIs, third-party Gateway integrations
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [X] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by LourencoVazPato** [comment]
Solved by https://github.com/mlflow/mlflow/pull/10359

**Comment by harupy** [comment]
Yes, #10359 solved it.

**Comment by jmahlik** [comment]
Just noticed this appears to be the last major blocker to installing on python 3.12.
