### ISSUE TITLE
[FR] [MLFLOW ROADMAP] Implement Metric Sampling API

### ISSUE THREAD

**Issue by BenWilson2** [mlflow/mlflow#10455]
### Willingness to contribute

No. I cannot contribute this feature at this time.

### Proposal Summary

A new feature for the MLflow UI (metric sampling for Deep Learning metric volumes during training) has been implemented and is available for use. 

In order to enable this UI functionality for MLflow backends, we would like a contributor to work on the implementation for: 
- FileStore
- SQLAlchemyStore 

and provide the functionality for handling within the MLflow tracking server. 

The RPC message definition for this API is as follows:

```python
# Returns metrics for the provided list of runs for the given step interval.
# If the number of steps exceed the max_results to return, then the resulting
# data is sampled. For example, if max_results is 5, start_step = 0, and 
# end_step = 8, then steps [0, 2, 4, 6, 8] are returned. The start_step and 
# end_step (if available) should be included in the response.
message GetMetricHistoryBulkInterval {

  # List of runs
  repeated string run_id = 1;

  # Metric key
  optional string metric_key = 2 [(validate_required) = true];

  # Number of results to return, e.g. 25k by default
  optional int32 max_results = 3;

  # Step to start returning metrics from, e.g. 0 by default
  optional int32 start_step = 4;

  # Step to stop returning metrics from, e.g. None by default (max)
  optional int32 end_step = 5;

  # Timestamp to start querying metrics for
  # - should not be set if start_step or end_step is set
  optional int64 start_timestamp = 6;

  # Timestamp to stop querying metrics for
  # - should not be set if start_step or end_step is set
  # - should be set if start_timestamp is set
  optional int64 end_timestamp = 7;

  message Response {

    # Returned metrics data
    repeated MetricWithRunId metrics = 1;

    # If the returned data was sampled
    optional bool sampled = 2;
  }
}
```

If you are interested in implementing this feature, an excellent reference point is this PR: #8739 , which shows the scope of the implementation and tests that would be required for this to be merged. 

If you are interested, please respond to this issue and we'll be sure to assign it to you. 

Note that we are interested in getting this introduced to MLflow in the 2.10.0 release (tentatively scheduled for the 2nd or 3rd week of January, 2024). If you are unable to make this delivery window due to other responsibilities, we would appreciate it if you didn't volunteer. However, if you feel like you can get this done, please let us know as we would love for this to be an external contribution! 

### Motivation

> #### What is the use case for this feature?

To support large volume metric sampling to allow for DL training workloads data to be displayed in MLflow UI charts, as well as establishing the required pre-existing work to allow for a client metric sampling API to be created.

> #### Why is this use case valuable to support for MLflow users in general?
Analyzing and evaluating extremely high volume metrics data is critical for DL training workloads (particularly for larger and more complex models that train for very long epoch iterations). 

> #### Why is this use case valuable to support for your project(s) or organization?
(see above on DL training analysis)

> #### Why is it currently difficult to achieve this use case?
The volume of data for many DL training runs is too great to load into UI visualizations with the existing APIs and is far too voluminous to be of a useful visualization data set. Deterministic statistical sampling is an effective way of visualizing extremely large metric populations.

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/gateway`: AI Gateway service, Gateway client APIs, third-party Gateway integrations
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [X] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by jeffreyjgong** [comment]
@BenWilson2 Is it too late to get started on this?  Read through most of the relevant code and think I'm at a good place to make a solid attempt at it

**Comment by BenWilson2** [comment]
@jeffreyjgong It's all yours! :) Thanks!

**Comment by harupy** [comment]
@jeffreyjgong Are you still interested in working on this?

**Comment by jeffreyjgong** [comment]
@harupy Yes! Sorry for the delay, would it be possible to have some guidance over a quick meeting?
