### ISSUE TITLE
User control `run_id`

### ISSUE THREAD

**Issue by bhack** [mlflow/mlflow#10510]
### Willingness to contribute

Yes. I would be willing to contribute this feature with guidance from the MLflow community.

### Proposal Summary

I need to let user control the runid for an experiment.

### Motivation

> #### What is the use case for this feature?
When using spot instances on the cloud pod are  going to restart and so the runs are going to proliferate on MLFLOW tracking when instead we are still conceptually inside the same run.
> #### Why is this use case valuable to support for MLflow users in general?
Cause we could define runid in env/config maps so that when a pod restart we are still inside the same run specially when we the run is going to rescue the last checkpoint 
> #### Why is this use case valuable to support for your project(s) or organization?

> #### Why is it currently difficult to achieve this use case?
Cause the in new runid are only generated server side.

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/gateway`: AI Gateway service, Gateway client APIs, third-party Gateway integrations
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by B-Step62** [comment]
@bhack, thank you for contacting us about this issue!

MLflow does support starting or resuming a run with a run_id of your choice. You can pass the desired run_id to [mlflow.start_run()](https://mlflow.org/docs/latest/python_api/mlflow.html#mlflow.start_run). To fetch the paused run id, you can use [mlflow.last_active_run()](https://mlflow.org/docs/latest/python_api/mlflow.html#mlflow.start_run), or you can search for a specific run using various filters with [MLflowClient](https://mlflow.org/docs/latest/python_api/mlflow.client.html#mlflow.client.MlflowClient.search_runs).

For example:
```
run_id = mlflow.last_active_run().info.run_id

with mlflow.start_run(run_id=run_id):
    # Resume your training
```

Would this resolve your issue?

**Comment by bhack** [comment]
> MLflow does support starting or resuming 

Are you sure that is working for starting? I think it doesn't work for starting as it will work only in the resuming case.

**Comment by B-Step62** [comment]
@bhack Sorry for the confusion, you're right it only works when run exists. But wouldn't it be sufficient for your use case?

**Comment by bhack** [comment]
With spot  instances (as "these days" it is hard to find GPI availability) the pod is going to terminate and restart automatically e.g. scheduled by a job.
An external controlled env for the pod could let to maintain the same run id also if the pod is restarting without runs proliferating on the MLFLOW tracking server/UI for the same semantic run.

How a restarting pod can  retrieve its own runid if it is generated only server side and you have many spot experiments with restarting pods?

You need to store it somewhere else or on a persistent storage but then you need to add other redundancy to store this info and so the advantage of using the MLflow tracking server is going to be impacted by this logistic overhead.

**Comment by B-Step62** [comment]
Ok, let me clarify your current set up a bit. So you're running both your training code and tracking server on spot instance(s), without connecting to any persistent database/storage for tracking backend? If my understanding is correct, how you keep other tracking data such as metrics from banishing on random termination?

> You need to store it somewhere else or on a persistent storage but then you need to add other redundancy to store this info and so the advantage of using the MLflow tracking server is going to be impacted by this logistic overhead.

This is actually recommended setup for such fluid environment. As for overhead, MLflow supports [async logging](https://mlflow.org/docs/latest/python_api/mlflow.html#mlflow.log_metric) for logging metrics.

**Comment by bhack** [comment]
No the MFflow tracking server is not spot and it is using persistent postgres backend.

Of course the spot instead are the training jobs/runs where the pod could be restarted/rescheduled by the governing job.

Every time the pod is automatically restarted/rescheduled on resource availability by its governing job we are going to generate another runid but this is not ok as e.g. we are resuming the last checkpoint so we are really just inside the same experiment run and we don't want to generate a new one.

So what is wrong is that the server is going to assign a new runid every time on each spot instances that it is going down and restarting.

**Comment by B-Step62** [comment]
Thanks for the further explanation! In that case, let me dig into what I suggested here:

> you can search for a specific run using various filters with [MLflowClient](https://mlflow.org/docs/latest/python_api/mlflow.client.html#mlflow.client.MlflowClient.search_runs).

This approach should work across multiple (spot) instances, because [MLflowClient](https://mlflow.org/docs/latest/python_api/mlflow.client.html#mlflow.client.MlflowClient.search_runs) queries runs **from the tracking server**, meaning that you can fetch your previous run on terminated spot instance, and resume it with `mlflow.start_run(run_id="foo")`. For example, you can simply get uncompleted job with some identifier indicates "same experiment" as a tag like this:

```
client = MLflowClient()
mlflow.search_runs(
    experiment_ids=[experiment_id], 
    filter_string=""tags.YOUR_TAG_KEY = 'YOUR_TAG_VALUE' and attributes.status != 'FINISHED'"
   order_by=["attributes.end_time desc"]
)
```

One caveat is that mlflow doesn't update the status from "RUNNING" to "FAILED" when the instance get terminated. Also it doesn't prevent two instances from starting runs under same run id at the same time. This means that you may need to have some control mechanism for managing which run id should be restarted or not. That being said, this should be rare occasion when the cluster scale is small, and the same thing is required if you manage run id by yourself, as you mentioned as *"An external controlled env for the pod"*.

**Comment by bhack** [comment]
Are you suggesting to use the pod env as an extra tag (like a fake runid) to recover the real runid with a query?

So I need to manage an extra id just cause I cannot assign an id client side (this is exactly the point of this issue)

> One caveat is that mlflow doesn't update the status from "RUNNING" to "FAILED" when the instance get terminated

This was not an issue as spots have a grace period termination.

**Comment by B-Step62** [comment]
Yes! Tags have more freedom with safety than managing run id by yourself, for example, run id is used as a primary key in tracking database, hence has certain restriction and pitfalls ([example](https://github.com/mlflow/mlflow/blame/f34364aeb36d8f1a5bf9861a6d7a25c9603ab214/mlflow/store/tracking/sqlalchemy_store.py#L465-L468)).

**Comment by bhack** [comment]
I will try to experiment a bit with this workaround to understand the logistic overhead of this approach

**Comment by B-Step62** [comment]
Thank you! I will close this issue for now but please open this or file a new issue for your further feedback. Supporting the fluid cloud environment is definitely an important path as a platform, so any feedbacks is really appreciated.
