### ISSUE TITLE
[FR] Add timestamp parameter to mlflow.log_metric

### ISSUE THREAD

**Issue by mbenoit29** [mlflow/mlflow#10535]
### Willingness to contribute

Yes. I would be willing to contribute this feature with guidance from the MLflow community.

### Proposal Summary

The `log_metric` [method](https://github.com/mlflow/mlflow/blob/0deea32675d0c49df3276bcb10efd4a6ed8075b1/mlflow/tracking/client.py#L702) of the python `MlflowClient` class takes a `timestamp` parameter as input which can then be used for visualisations in the UI instead of step.

However, this parameter doesn't exist in the fluent `log_metric` [method](https://github.com/mlflow/mlflow/blob/0deea32675d0c49df3276bcb10efd4a6ed8075b1/mlflow/tracking/fluent.py#L732). It is set by default to be the current timestamp.

It would be an optional parameter, defaulting to the current timestamp to keep the default behaviour similar to the current one.

### Motivation

> #### What is the use case for this feature?
This can be useful in runs where you make predictions over multiple timestamps. For example for time series problems where the model predicts multiple steps.
> #### Why is this use case valuable to support for MLflow users in general?
Monitoring metrics over time is common use case of data science.
> #### Why is this use case valuable to support for your project(s) or organization?
We are working with time series model which make predictions over multiple steps and we want to easily monitor metrics for each of these steps and be able to clearly identify the step by its timestamp (in our case date).
> #### Why is it currently difficult to achieve this use case?
It can currently only be done by creating an MlflowClient, which is of course manageable but we lose the advantage of having the fluent `log_metric` method.

### Details

The method could look like this:

```python
def log_metric(
    key: str, value: float, step: Optional[int] = None, synchronous: bool = True, timestamp: Optional[int] = None,
) -> Optional[RunOperations]:
    run_id = _get_or_start_run().info.run_id
    return MlflowClient().log_metric(
        run_id, key, value, timestamp or get_current_time_millis(), step or 0, synchronous=synchronous
    )
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/gateway`: AI Gateway service, Gateway client APIs, third-party Gateway integrations
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [X] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by B-Step62** [comment]
@mbenoit29 Awesome, thank you so much for your contribution!
