### ISSUE TITLE
[BUG]MlflowException: failed to save spark model via mlflowdbfs

### ISSUE THREAD

**Issue by codekcg23** [mlflow/mlflow#10587]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Databricks

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 2.3.2

### System information

-**Databricks Runtime**: 10.4 ML LTS

### Describe the problem

We have a requirement to log an MLflow experiment to a central Databricks workspace from another workspace (dev). The setup worked perfectly for logging and registering Scikit-learn models using MLflow.

However, we cannot log a Spark model to a central Databricks workspace (different databricks workspace form current one) using set_tracking_uri and set_registry_uri.

The mentioned code base works perfectly in the current workspace when attempting to log a Spark model. Additionally, when trying to log Scikit-learn models, they get logged in the central workspace (different workspace) as well.

The issue only occurs when attempting to log a Spark model to a different workspace. Metrics of the model get logged in this target workspace, but the model itself doesn't get saved in the Artifacts and throws this mentioned error.

![image](https://github.com/mlflow/mlflow/assets/43032723/81ca68ef-1fde-471c-98a0-1f2d118102e0)
![image](https://github.com/mlflow/mlflow/assets/43032723/fdaef94f-b077-4129-b6d6-b5cdc0832d81)

Reference material for the sample codebase

[Binary classification sample code](https://docs.databricks.com/en/_extras/notebooks/source/binary-classification.html)
[Remote Model Registry](https://learn.microsoft.com/en-us/azure/databricks/_static/notebooks/mlflow/mlflow-model-registry-multi-workspace.html)

### Tracking information

```shell
MLflow version: 2.3.2
MLflow module location: /databricks/python/lib/python3.8/site-packages/mlflow/__init__.py
Tracking URI: databricks://:testing_mlflow_central
Registry URI: databricks://:testing_mlflow_central
Databricks runtime version: 10.4.x-cpu-ml-scala2.12
MLflow environment variables: 
  MLFLOW_CONDA_HOME: /databricks/conda
  MLFLOW_PYTHON_EXECUTABLE: /databricks/spark/scripts/mlflow_python.sh
  MLFLOW_TRACKING_URI: databricks
MLflow dependencies: 
  Flask: 1.1.2+db1
  Jinja2: 2.11.3
  alembic: 1.13.0
  click: 7.1.2
  cloudpickle: 1.6.0
  databricks-cli: 0.16.3
  docker: 6.1.3
  entrypoints: 0.3
  gitpython: 3.1.12
  gunicorn: 20.0.4
  importlib-metadata: 3.10.0
  markdown: 3.3.3
  matplotlib: 3.4.2
  numpy: 1.22.4
  packaging: 21.3
  pandas: 1.5.3
  protobuf: 3.20.3
  pyarrow: 11.0.0
  pytz: 2020.5
  pyyaml: 5.4.1
  querystring-parser: 1.2.4
  requests: 2.31.0
  scikit-learn: 0.24.1
  scipy: 1.6.2
  sqlalchemy: 1.4.29
  sqlparse: 0.4.1
```

### Code to reproduce issue

```
from pyspark.sql.types import DoubleType, StringType, StructField, StructType
import pyspark
from pyspark.ml import Pipeline
from pyspark.ml.feature import StringIndexer, VectorAssembler
from distutils.version import LooseVersion

import mlflow
from mlflow.tracking.artifact_utils import get_artifact_uri
from mlflow.tracking.client import MlflowClient
from pyspark.ml.classification import RandomForestClassifier
from pyspark.ml.tuning import ParamGridBuilder, CrossValidator

#scope and key ,have set up using databricks secret scope. workspace id, token, host url has been set up for central workspace
registry_uri = 'databricks://' + scope + ':' + key
mlflow.set_registry_uri(registry_uri)
mlflow.set_tracking_uri(registry_uri)

experiment_name = "/mlflow_experiments/diabetes/debug_spark_1"
client = MlflowClient(tracking_uri=REGISTRY_URI, registry_uri=REGISTRY_URI)
mlflow.set_experiment(experiment_name)

schema = StructType([
  StructField("age", DoubleType(), False),
  StructField("workclass", StringType(), False),
  StructField("fnlwgt", DoubleType(), False),
  StructField("education", StringType(), False),
  StructField("education_num", DoubleType(), False),
  StructField("marital_status", StringType(), False),
  StructField("occupation", StringType(), False),
  StructField("relationship", StringType(), False),
  StructField("race", StringType(), False),
  StructField("sex", StringType(), False),
  StructField("capital_gain", DoubleType(), False),
  StructField("capital_loss", DoubleType(), False),
  StructField("hours_per_week", DoubleType(), False),
  StructField("native_country", StringType(), False),
  StructField("income", StringType(), False)
])
 
dataset = spark.read.format("csv").schema(schema).load("/databricks-datasets/adult/adult.data")
cols = dataset.columns

 
categoricalColumns = ["workclass", "education", "marital_status", "occupation", "relationship", "race", "sex", "native_country"]
stages = [] # stages in Pipeline
for categoricalCol in categoricalColumns:
    # Category Indexing with StringIndexer
    stringIndexer = StringIndexer(inputCol=categoricalCol, outputCol=categoricalCol + "Index")
    # Use OneHotEncoder to convert categorical variables into binary SparseVectors
    if LooseVersion(pyspark.__version__) < LooseVersion("3.0"):
        from pyspark.ml.feature import OneHotEncoderEstimator
        encoder = OneHotEncoderEstimator(inputCols=[stringIndexer.getOutputCol()], outputCols=[categoricalCol + "classVec"])
    else:
        from pyspark.ml.feature import OneHotEncoder
        encoder = OneHotEncoder(inputCols=[stringIndexer.getOutputCol()], outputCols=[categoricalCol + "classVec"])
    # Add stages.  These are not run here, but will run all at once later on.
    stages += [stringIndexer, encoder]

# Convert label into label indices using the StringIndexer
label_stringIdx = StringIndexer(inputCol="income", outputCol="label")
stages += [label_stringIdx]

# Transform all features into a vector using VectorAssembler
numericCols = ["age", "fnlwgt", "education_num", "capital_gain", "capital_loss", "hours_per_week"]
assemblerInputs = [c + "classVec" for c in categoricalColumns] + numericCols
assembler = VectorAssembler(inputCols=assemblerInputs, outputCol="features")
stages += [assembler]

partialPipeline = Pipeline().setStages(stages)
pipelineModel = partialPipeline.fit(dataset)
preppedDataDF = pipelineModel.transform(dataset)

# Keep relevant columns
selectedcols = ["label", "features"] + cols
dataset = preppedDataDF.select(selectedcols)

### Randomly split data into training and test sets. set seed for reproducibility
(trainingData, testData) = dataset.randomSplit([0.7, 0.3], seed=100)


# Create an initial RandomForest model.
rf = RandomForestClassifier(labelCol="label", featuresCol="features")
evaluator = BinaryClassificationEvaluator() 


param_grid = (
    ParamGridBuilder()
    .addGrid(rf.numTrees, conf["model_params"]["rf_params"]["numTrees"])
    .addGrid(rf.maxDepth, conf["model_params"]["rf_params"]["maxDepth"])
    .addGrid(
        rf.minInstancesPerNode,
        conf["model_params"]["rf_params"]["minInstancesPerNode"],
    )
    .build()
)

cv = CrossValidator(
    estimator=rf,
    estimatorParamMaps=param_grid,
    evaluator=BinaryClassificationEvaluator(metricName="areaUnderROC"),
    numFolds=5,
)
cv_model = cv.fit(trainingData)

# best model
model = cv_model.bestModel


model_params_best = {
    "numTrees": cv_model.getEstimatorParamMaps()[np.argmax(cv_model.avgMetrics)][
        cv_model.bestModel.numTrees
    ],
    "maxDepth": cv_model.getEstimatorParamMaps()[np.argmax(cv_model.avgMetrics)][
        cv_model.bestModel.maxDepth
    ],
    "minInstancesPerNode": cv_model.getEstimatorParamMaps()[
        np.argmax(cv_model.avgMetrics)
    ][cv_model.bestModel.minInstancesPerNode],
}

prediction = model.transform(testData)
#evaluate
AUC = evaluator.evaluate(prediction)
artifact_path = "best-model"
model_name = "debug_spark_model_1"

#experiment run should log in different workspace, not in the running workspace
with mlflow.start_run(run_name="debug_run_1"):
    run1_id = mlflow.active_run().info.run_id
    mlflow.log_params(model_params_best)
    mlflow.log_metric("test_auc",AUC)
  
    artifact_path = "best-model"
    
    mlflow.spark.log_model(spark_model = model, artifact_path = artifact_path) 
    source = get_artifact_uri(run_id=run1_id, artifact_path=artifact_path)
    
#registering model in different workspace - central  

registered_model = client.create_registered_model(model_name)
```

### Stack trace

```
com.databricks.mlflowdbfs.MlflowHttpException: statusCode=404 reasonPhrase=[Not Found] bodyMessage=
[{&#34;error_code&#34;:&#34;RESOURCE_DOES_NOT_EXIST&#34;,&#34;message&#34;:&#34;
Run &#39;35afe99c3d3c434cb75a51bc2eb1b08f&#39; not found.&#34;}]
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
/databricks/python/lib/python3.8/site-packages/mlflow/spark.py in log_model(spark_model, artifact_path, conda_env, code_paths, dfs_tmpdir, sample_input, registered_model_name, signature, input_example, await_registration_for, pip_requirements, extra_pip_requirements, metadata)
    241             try:
--> 242                 spark_model.save(mlflowdbfs_path)
    243             except Exception as e:

/databricks/spark/python/pyspark/ml/util.py in save(self, path)
    356         """Save this ML instance to the given path, a shortcut of 'write().save(path)'."""
--> 357         self.write().save(path)
    358 

/databricks/spark/python/pyspark/ml/util.py in save(self, path)
    307             raise TypeError("path should be a string, got type %s" % type(path))
--> 308         self._jwrite.save(path)
    309 

/databricks/spark/python/lib/py4j-0.10.9.1-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1303         answer = self.gateway_client.send_command(command)
-> 1304         return_value = get_return_value(
1305             answer, self.gateway_client, self.target_id, self.name)

/databricks/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
    116         try:
--> 117             return f(*a, **kw)
    118         except py4j.protocol.Py4JJavaError as e:

/databricks/spark/python/lib/py4j-0.10.9.1-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    325             if answer[1] == REFERENCE_TYPE:
--> 326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".

Py4JJavaError: An error occurred while calling o22614.save.
: com.databricks.mlflowdbfs.MlflowHttpException: statusCode=404 reasonPhrase=[Not Found] bodyMessage=[{"error_code":"RESOURCE_DOES_NOT_EXIST","message":"Run '35afe99c3d3c434cb75a51bc2eb1b08f' not found."}]
at com.databricks.mlflowdbfs.MlflowHttpCaller.checkError(MlflowHttpCaller.java:165)
	at com.databricks.mlflowdbfs.MlflowHttpCaller.executeRequestWithRateLimitRetries(MlflowHttpCaller.java:115)
	at com.databricks.mlflowdbfs.MlflowHttpCaller.executeRequest(MlflowHttpCaller.java:125)
	at com.databricks.mlflowdbfs.MlflowHttpCaller.send(MlflowHttpCaller.java:150)
	at com.databricks.mlflowdbfs.MlflowdbfsClient.getWithEntity(MlflowdbfsClient.scala:246)
	at com.databricks.mlflowdbfs.MlflowdbfsClient.listArtifacts(MlflowdbfsClient.scala:194)
	at com.databricks.mlflowdbfs.MlflowdbfsClient.com$databricks$mlflowdbfs$MlflowdbfsClient$$getFilesFromMlflowService(MlflowdbfsClient.scala:92)
	at com.databricks.mlflowdbfs.MlflowdbfsClient$$anon$1.load(MlflowdbfsClient.scala:146)
	at com.databricks.mlflowdbfs.MlflowdbfsClient$$anon$1.load(MlflowdbfsClient.scala:143)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3522)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2315)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2193)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3932)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3936)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4806)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4812)
	at com.databricks.mlflowdbfs.MlflowdbfsClient.getFiles(MlflowdbfsClient.scala:74)
	at com.databricks.mlflowdbfs.MlflowdbfsFileSystem.getFileStatus(MlflowdbfsFileSystem.scala:221)
	at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1760)
	at org.apache.spark.ml.util.FileSystemOverwrite.handleOverwrite(ReadWrite.scala:675)
	at org.apache.spark.ml.util.MLWriter.save(ReadWrite.scala:167)
	at org.apache.spark.ml.PipelineModel$PipelineModelWriter.super$save(Pipeline.scala:344)
	at org.apache.spark.ml.PipelineModel$PipelineModelWriter.$anonfun$save$4(Pipeline.scala:344)
	at org.apache.spark.ml.MLEvents.withSaveInstanceEvent(events.scala:175)
	at org.apache.spark.ml.MLEvents.withSaveInstanceEvent$(events.scala:170)
	at org.apache.spark.ml.util.Instrumentation.withSaveInstanceEvent(Instrumentation.scala:43)
	at org.apache.spark.ml.PipelineModel$PipelineModelWriter.$anonfun$save$3(Pipeline.scala:344)
	at org.apache.spark.ml.PipelineModel$PipelineModelWriter.$anonfun$save$3$adapted(Pipeline.scala:344)
	at org.apache.spark.ml.util.Instrumentation$.$anonfun$instrumented$1(Instrumentation.scala:284)
	at scala.util.Try$.apply(Try.scala:213)
	at org.apache.spark.ml.util.Instrumentation$.instrumented(Instrumentation.scala:284)
	at org.apache.spark.ml.PipelineModel$PipelineModelWriter.save(Pipeline.scala:344)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:295)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:251)
	at java.lang.Thread.run(Thread.java:750)


The above exception was the direct cause of the following exception:

MlflowException                           Traceback (most recent call last)
<command-442679019551010> in <module>
     82     artifact_path = "best-model"
---> 83     mlflow_spark.log_model(spark_model = model, artifact_path = artifact_path) #gives error


/databricks/python/lib/python3.8/site-packages/mlflow/spark.py in log_model(spark_model, artifact_path, conda_env, code_paths, dfs_tmpdir, sample_input, registered_model_name, signature, input_example, await_registration_for, pip_requirements, extra_pip_requirements, metadata)
    242                 spark_model.save(mlflowdbfs_path)
    243             except Exception as e:
--> 244                 raise MlflowException("failed to save spark model via mlflowdbfs") from e
    245 
    246     # If the artifact URI is a local filesystem path, defer to Model.log() to persist the model,

MlflowException: failed to save spark model via mlflowdbfs
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/gateway`: AI Gateway service, Gateway client APIs, third-party Gateway integrations
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [X] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment]
Hi @codekcg23, I'm fairly certain that this isn't possible due to the mechanism of saving SparkML models to a temp DFS location before copying back to the local file system to initiate the transfer. 
Something to potentially think about is using unity catalog, which I think will greatly simplify your workflow. Is it possible for you to try that?

**Comment by codekcg23** [comment]
Hi @BenWilson2 , I  will look into using Unity Catalog.

I used below code to disable mlflowdbfs and was able to log the spark model to a different workspace. Will there be any issues if I use this workaround?

```
import os
os.environ["DISABLE_MLFLOWDBFS"] = "true
```"
