### ISSUE TITLE
[FR] in mlflow viewer, add markdown file artifacts viewer

### ISSUE THREAD

**Issue by Edouard59** [mlflow/mlflow#10671]
### Willingness to contribute

No I cannot contribute to this feature.

### Proposal Summary

When logging a markdown file (.md) as an artifact in a run, add in the mlflow ui viewer a capability to parse the markdown language and show the file in a formatted way instead of the raw markdown text in the file preview pane.

### Motivation

> #### What is the use case for this feature?
Nice formatting preview of markdown files logged as artifacts. For instance I log in a folder some data and add to it a readme.md file to explain what the folder contains, and so on.

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [X] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by serena-ruan** [comment]
Sounds like a great idea! Contributions are welcome!

**Comment by geetptl** [comment]
@serena-ruan I'd like to get my hands dirty on this!

**Comment by pietrodantuono** [comment]
@mlflow/mlflow-team are there any news in this regard?

**Comment by mprahl** [comment]
I'll take a look at this one!
