### ISSUE TITLE
comparison chart is no longer interactive

### ISSUE THREAD

**Issue by osama-ammar** [mlflow/mlflow#10987]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

- Client: 2.10.0
- Tracking server: [http://127.0.0.1:5000]

### System information

- **OS Platform and Distribution **: Windows 11
- **Python version**:   3.10.11

### Describe the problem

when you click on a line on comparison chart it doesn't go to the experiment related to this line.

### Tracking information

System information: Windows 10.0.22621
Python version: 3.10.11
MLflow version: 2.10.0
MLflow module location: C:\Users\Osama Ammar\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\mlflow\__init__.py
Tracking URI: file:///C:/Atomica_CV_source_code/cycle30/cvml/roi-detection-to-segmentation/mlruns
Registry URI: file:///C:/Atomica_CV_source_code/cycle30/cvml/roi-detection-to-segmentation/mlruns
Active experiment ID: 401650045079793612
Active run ID: c283fcfcd8704b71a71dd069a31a496d
Active run artifact URI: file:///C:/Atomica_CV_source_code/cycle30/cvml/roi-detection-to-segmentation/mlruns/401650045079793612/c283fcfcd8704b71a71dd069a31a496d/artifacts
MLflow dependencies:
  Flask: 2.3.2
  Jinja2: 3.1.2
  aiohttp: 3.8.5
  alembic: 1.11.2
  boto3: 1.33.13
  botocore: 1.33.13
  click: 8.1.3
  cloudpickle: 2.2.1
  databricks-cli: 0.17.7
  docker: 6.1.3
  entrypoints: 0.4
  fastapi: 0.95.0
  gitpython: 3.1.32
  importlib-metadata: 6.8.0
  markdown: 3.4.1
  matplotlib: 3.6.0
  numpy: 1.23.3
  packaging: 23.2
  pandas: 1.5.0
  protobuf: 3.19.6
  pyarrow: 12.0.1
  pydantic: 1.10.12
  pytz: 2022.1
  pyyaml: 6.0
  querystring-parser: 1.2.4
  requests: 2.28.2
  scikit-learn: 1.1.2
  scipy: 1.9.1
  sqlalchemy: 2.0.19
  sqlparse: 0.4.2
  uvicorn: 0.21.1
  waitress: 2.1.2

### Code to reproduce issue

```
REPLACE_ME
```

### Stack trace

```
REPLACE_ME
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [X] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by osama-ammar** [comment]
yes , may be I didn't clear out enough , but I mean when you select many models and press compare button , a window with parallel view figure opens , this figure is not interactive as the figure you showed in the video.

**Comment by harupy** [comment]
@osama-ammar We currently don't have a plan to update the legacy comparison chart.
