### ISSUE TITLE
[FR] Logging csv files directly to mlflow without having to save locally first

### ISSUE THREAD

**Issue by SiddharthSingi** [mlflow/mlflow#11052]
### Willingness to contribute

Yes. I would be willing to contribute this feature with guidance from the MLflow community.

### Proposal Summary

Ability to save a csv file directly as an artifact instead of saving as a csv file locally first and then passing the filename

### Motivation

> #### What is the use case for this feature?
So that users do not have to save multiple csv files locally 
> #### Why is this use case valuable to support for MLflow users in general?
It will make it easier to save multiple csv artifacts  with less code and less space used in multiple locations
> #### Why is this use case valuable to support for your project(s) or organization?
I would like to save multiple csv files every epoch so I can view them and understand hwo they are changing
> #### Why is it currently difficult to achieve this use case?
Takes up too much space and is annoying to save multiple copies of the same file

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [X] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [X] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@SiddharthSingi Have you tried `mlflow.log_text`?

```python
import mlflow

with mlflow.start_run():
    csv_text = "a,b,c\n1,2,3\n4,5,6\n"
    mlflow.log_text(csv_text, "data.csv")
```

**Comment by harupy** [comment]
@SiddharthSingi Feel free to reopen the issue if the code above doesn't work
