### ISSUE TITLE
[BUG] `mlflow.tracking._model_registry.utils.get_default_host_creds` ignores configuration file

### ISSUE THREAD

**Issue by badge** [mlflow/mlflow#11214]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Other

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 2.10.2
- Tracking server: 2.10.2

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS
- **Python version**: 3.11.7
- **yarn version, if running the dev UI**: n/a

### Describe the problem

I've been trying out mlflow with basic auth using a credentials file at `~/.mlflow/credentials`, [per the docs](https://mlflow.org/docs/latest/auth/index.html#using-credentials-file). This works great for model tracking, however when I tried following the section of the docs to [retrieve my model artifacts](https://mlflow.org/docs/latest/auth/index.html#using-credentials-file), I got an `MlfowException` resulting from a 401 unauthorized error code.

I've tracked the problem down to the [`get_default_host_creds`](https://github.com/mlflow/mlflow/blob/master/mlflow/tracking/_model_registry/utils.py#L148) function which is partialed by `mlflow.store.model_registry.rest_store.RestStore`, at `MlflowClient._registry_client_lazy.store` after the first call to the registry.

The problem occurs because the `get_default_host_creds` function only loads the `MLFLOW_TRACKING_USERNAME` and `MLFLOW_TRACKING_PASSWORD` environment variables, and doesn't look in the config file at all.

### Code to reproduce issue

Setup as follows:

- Running mlflow with `mlflow server --app-name basic-auth`
- Add credentials to `~/.mlflow/credentials`

```
import mlflow.client

client = mlflow.client.MlflowClient(tracking_uri="[tracking URI with basic auth]")
client.search_experiments()                          # Shows that the client is correctly using the config file auth
client.get_model_version("tracking-quickstart", "1") # Raises `MlflowException`
```

### Stack trace

```
---------------------------------------------------------------------------
MlflowException                           Traceback (most recent call last)
Cell In[56], line 1
----> 1 client.get_model_version_download_uri("LightGBM Test", "2")

File ~/.pyenv/versions/3.11.7/envs/mlflow-test-3.11.7/lib/python3.11/site-packages/mlflow/tracking/client.py:3166, in MlflowClient.get_model_version_download_uri(self, name, version)
   3122 def get_model_version_download_uri(self, name: str, version: str) -> str:
   3123     """
   3124     Get the download location in Model Registry for this model version.
   3125 
   (...)
   3164         Download URI: runs:/027d7bbe81924c5a82b3e4ce979fcab7/sklearn-model
   3165     """
-> 3166     return self._get_registry_client().get_model_version_download_uri(name, version)

File ~/.pyenv/versions/3.11.7/envs/mlflow-test-3.11.7/lib/python3.11/site-packages/mlflow/tracking/_model_registry/client.py:278, in ModelRegistryClient.get_model_version_download_uri(self, name, version)
    270 def get_model_version_download_uri(self, name, version):
    271     """
    272     Get the download location in Model Registry for this model version.
    273 
   (...)
    276     :return: A single URI location that allows reads for downloading.
    277     """
--> 278     return self.store.get_model_version_download_uri(name, version)

File ~/.pyenv/versions/3.11.7/envs/mlflow-test-3.11.7/lib/python3.11/site-packages/mlflow/store/model_registry/rest_store.py:309, in RestStore.get_model_version_download_uri(self, name, version)
    299 """
    300 Get the download location in Model Registry for this model version.
    301 NOTE: For first version of Model Registry, since the models are not copied over to another
   (...)
    306 :return: A single URI location that allows reads for downloading.
    307 """
    308 req_body = message_to_json(GetModelVersionDownloadUri(name=name, version=str(version)))
--> 309 response_proto = self._call_endpoint(GetModelVersionDownloadUri, req_body)
    310 return response_proto.artifact_uri

File ~/.pyenv/versions/3.11.7/envs/mlflow-test-3.11.7/lib/python3.11/site-packages/mlflow/store/model_registry/base_rest_store.py:44, in BaseRestStore._call_endpoint(self, api, json_body, call_all_endpoints, extra_headers)
     42 else:
     43     endpoint, method = self._get_endpoint_from_method(api)
---> 44     return call_endpoint(
     45         self.get_host_creds(), endpoint, method, json_body, response_proto, extra_headers
     46     )

File ~/.pyenv/versions/3.11.7/envs/mlflow-test-3.11.7/lib/python3.11/site-packages/mlflow/utils/rest_utils.py:220, in call_endpoint(host_creds, endpoint, method, json_body, response_proto, extra_headers)
    218     call_kwargs["json"] = json_body
    219     response = http_request(**call_kwargs)
--> 220 response = verify_rest_response(response, endpoint)
    221 js_dict = json.loads(response.text)
    222 parse_dict(js_dict=js_dict, message=response_proto)

File ~/.pyenv/versions/3.11.7/envs/mlflow-test-3.11.7/lib/python3.11/site-packages/mlflow/utils/rest_utils.py:158, in verify_rest_response(response, endpoint)
    153     else:
    154         base_msg = (
    155             f"API request to endpoint {endpoint} "
    156             f"failed with error code {response.status_code} != 200"
    157         )
--> 158         raise MlflowException(
    159             f"{base_msg}. Response body: '{response.text}'",
    160             error_code=get_error_code(response.status_code),
    161         )
    163 # Skip validation for endpoints (e.g. DBFS file-download API) which may return a non-JSON
    164 # response
    165 if endpoint.startswith(_REST_API_PATH_PREFIX) and not _can_parse_as_json_object(response.text):

MlflowException: API request to endpoint /api/2.0/mlflow/model-versions/get-download-uri failed with error code 401 != 200. Response body: 'You are not authenticated. Please see https://www.mlflow.org/docs/latest/auth/index.html#authenticating-to-mlflow on how to authenticate.'
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by B-Step62** [comment]
Thank you for bringing this issue to our attention, @badge!
I could reproduce the issue and we will patch the fix to read credential info from the file.
