### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by GhaithDek** [mlflow/mlflow#11400]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- mlflow, version 2.11.1

### System information

- **WSL2 : Ubuntu-20.04)**:
- **Python 3.12.2**:

### Describe the problem

ValueError: Loading azure-openai-chat LLM not supported when using AzureChatOpenAI for retieval when following this tutorial:
https://github.com/mlflow/mlflow/blob/master/examples/langchain/retrieval_qa_chain_azure_openai.py

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```
import os
import tempfile
import json

from langchain.chains import RetrievalQA
from langchain.document_loaders import TextLoader
from langchain.text_splitter import CharacterTextSplitter
from langchain.vectorstores import FAISS
#from langchain_openai import AzureOpenAI, AzureChatOpenAI, AzureOpenAIEmbeddings
from langchain_openai import  OpenAI, OpenAIEmbeddings
from langchain_openai import AzureOpenAI, AzureChatOpenAI, OpenAI
from langchain_openai.embeddings.azure import AzureOpenAIEmbeddings

import mlflow

# set your api keys here

assert (
    "AZURE_OPENAI_ENDPOINT" in os.environ
), "Please set the AZURE_OPENAI_ENDPOINT environment variable. It is the base URL for your Azure OpenAI resource. You can find this in the Azure portal under your Azure OpenAI resource."
assert (
    "OPENAI_API_KEY" in os.environ
), "Please set the OPENAI_API_KEY environment variable. It is the API key for your Azure OpenAI resource. You can find this in the Azure portal under your Azure OpenAI resource."

remote_server_uri = ""
mlflow.set_tracking_uri(uri=remote_server_uri)

with tempfile.TemporaryDirectory() as temp_dir:
    persist_dir = os.path.join(temp_dir, "faiss_index")
    # Create the vector db, persist the db to a local fs folder
    loader = TextLoader("mlflow_/tests/langchain/state_of_the_union.txt")
    documents = loader.load()
    text_splitter = CharacterTextSplitter(chunk_size=1000, chunk_overlap=0)
    docs = text_splitter.split_documents(documents)
    
    embeddings = AzureOpenAIEmbeddings(
        #deployment_name="<your-deployment-name>",
    )
    db = FAISS.from_documents(docs, embeddings)
    db.save_local(persist_dir)
    llm = AzureChatOpenAI(
        deployment_name="<your-deployment-name>",
        model_name="gpt-35-turbo-instruct",
    )
    # Create the RetrievalQA chain
    retrievalQA = RetrievalQA.from_llm(llm=llm, retriever=db.as_retriever())

    # Log the retrievalQA chain
    def load_retriever(persist_directory):  
        embeddings = AzureOpenAIEmbeddings(
            #deployment_name="<your-deployment-name>",
        )
        vectorstore = FAISS.load_local(persist_directory, embeddings)
        return vectorstore.as_retriever()

    with mlflow.start_run() as run:
        logged_model = mlflow.langchain.log_model(
            retrievalQA,
            artifact_path="retrieval_qa",
            loader_fn=load_retriever,
            persist_dir=persist_dir,
        )

# Load the retrievalQA chain
loaded_model = mlflow.pyfunc.load_model(logged_model.model_uri)
print(loaded_model.predict([{"query": "What did the president say about Ketanji Brown Jackson"}]))
```

### Stack trace

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/mlflow_/retrieval.py", line 96, in <module>
    loaded_model = mlflow.pyfunc.load_model(logged_model.model_uri)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/anaconda3/envs/mlflow/lib/python3.12/site-packages/mlflow/pyfunc/__init__.py", line 681, in load_model
    model_impl = importlib.import_module(conf[MAIN])._load_pyfunc(data_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/anaconda3/envs/mlflow/lib/python3.12/site-packages/mlflow/langchain/__init__.py", line 674, in _load_pyfunc
    return wrapper_cls(_load_model_from_local_fs(path))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/anaconda3/envs/mlflow/lib/python3.12/site-packages/mlflow/langchain/__init__.py", line 680, in _load_model_from_local_fs
    return _load_model(local_model_path, flavor_conf)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/anaconda3/envs/mlflow/lib/python3.12/site-packages/mlflow/langchain/__init__.py", line 492, in _load_model
    model = _load_base_lcs(local_model_path, flavor_conf)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/anaconda3/envs/mlflow/lib/python3.12/site-packages/mlflow/langchain/utils.py", line 458, in _load_base_lcs
    model = load_chain(lc_model_path, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/anaconda3/envs/mlflow/lib/python3.12/site-packages/langchain/chains/loading.py", line 596, in load_chain
    return _load_chain_from_file(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/anaconda3/envs/mlflow/lib/python3.12/site-packages/langchain/chains/loading.py", line 623, in _load_chain_from_file
    return load_chain_from_config(config, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/anaconda3/envs/mlflow/lib/python3.12/site-packages/langchain/chains/loading.py", line 586, in load_chain_from_config
    return chain_loader(config, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/anaconda3/envs/mlflow/lib/python3.12/site-packages/langchain/chains/loading.py", line 419, in _load_retrieval_qa
    combine_documents_chain = load_chain_from_config(combine_documents_chain_config)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/anaconda3/envs/mlflow/lib/python3.12/site-packages/langchain/chains/loading.py", line 586, in load_chain_from_config
    return chain_loader(config, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/anaconda3/envs/mlflow/lib/python3.12/site-packages/langchain/chains/loading.py", line 79, in _load_stuff_documents_chain
    llm_chain = load_chain_from_config(llm_chain_config)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/anaconda3/envs/mlflow/lib/python3.12/site-packages/langchain/chains/loading.py", line 586, in load_chain_from_config
    return chain_loader(config, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/anaconda3/envs/mlflow/lib/python3.12/site-packages/langchain/chains/loading.py", line 40, in _load_llm_chain
    llm = load_llm_from_config(llm_config)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/anaconda3/envs/mlflow/lib/python3.12/site-packages/langchain_community/llms/loading.py", line 21, in load_llm_from_config
    raise ValueError(f"Loading {config_type} LLM not supported")
ValueError: Loading azure-openai-chat LLM not supported
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [X] `area/docs`: MLflow documentation pages
- [X] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [X] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by serena-ruan** [comment]
@GhaithDek This is a bug in Langchain. Filed https://github.com/langchain-ai/langchain/pull/19017
