### ISSUE TITLE
[BUG] Rag Demo unable to create endpoint - "File {load_path} must exist and must be a directory in order to load runnable with steps."

### ISSUE THREAD

**Issue by CarlosLabrado** [mlflow/mlflow#11405]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Databricks

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

mlflow==2.11.1 and mlflow==2.10.1

### System information

- **Databricks**:
- **Python version 3.10**:

### Describe the problem

I was following your RAG demo [link](https://notebooks.databricks.com/demos/llm-rag-chatbot/index.html#) sucessfully up to the point of "04-Deploy-Model-as-Endpoint" but when I am trying to serve the model as an enpoint it fails at the last step when is trying to start the server with this error:

```
An error occurred while loading the model. Folder /model/model/steps/0/model/steps/question_is_relevant/model/steps/0/model/steps/chat_history/model/steps must exist and must be a directory in order to load runnable with steps..
```

Now I am not using the unity catalog for logging the model, I am using classic "databricks" like `mlflow.set_registry_uri('databricks')`

### I am able to **successfully** load the model from mlflow like this:

```python
model = mlflow.langchain.load_model(model_info.model_uri)
model.invoke(dialog)
```

### Tracking information

```shell
REPLACE_ME
```

### Here is the code for logging to MLflow:

```python
import cloudpickle
import langchain
from mlflow.models import infer_signature
import mlflow

mlflow.set_registry_uri("databricks")
model_name = "rag_model"

with mlflow.start_run(run_name="rag_run") as run:
    #Get our model signature from input/output
    output = full_chain.invoke(dialog)
    signature = infer_signature(dialog, output)

    model_info = mlflow.langchain.log_model(
        full_chain,
        loader_fn=get_retriever,  # Load the retriever with DATABRICKS_TOKEN env as secret (for authentication).
        artifact_path="model", # this used to be "chain" but I changed it to try and fix the error, didn't worked either
        registered_model_name=model_name,
        pip_requirements=[
            "mlflow==" + mlflow.__version__,
            "langchain==" + langchain.__version__,
            "databricks-vectorsearch",
            "pydantic==2.6.4 --no-binary pydantic", # updated this from 2.5.2 , but still failing 
            "cloudpickle=="+ cloudpickle.__version__,
        ],
        input_example=dialog,
        signature=signature,
        example_no_conversion=True,
    )
```

### Code to try and create the endpoint

```python
import urllib
import json
import mlflow
from mlflow import MlflowClient

mlflow.set_registry_uri('databricks')
client = MlflowClient()
serving_endpoint_name = "vyguide-poc-classic-test"

#TODO: use the sdk once model serving is available.
serving_client = EndpointApiClient()

environment_vars={"DATABRICKS_TOKEN": "{{secrets/my-secret/my-key}}"}

# create_endpoint_if_not_exists is the code already in the init of the demo notebook
serving_client.create_endpoint_if_not_exists(serving_endpoint_name, model_name="rag_model", model_version=5, workload_size="Small", scale_to_zero_enabled=True, wait_start = True, environment_vars=environment_vars)
```

### Stack trace

I get this error from the "Service Logs" in the "Serving Endpoints" UI
```
[787c9zrzl4] An error occurred while loading the model. Folder /model/model/steps/0/model/steps/question_is_relevant/model/steps/0/model/steps/chat_history/model/steps must exist and must be a directory in order to load runnable with steps..
[787c9zrzl4] [2024-03-11 21:31:48 +0000] [68] [INFO] Worker exiting (pid: 68)
[787c9zrzl4] [2024-03-11 21:31:48 +0000] [7] [ERROR] Worker (pid:68) exited with code 1
[787c9zrzl4] [2024-03-11 21:31:48 +0000] [7] [ERROR] Worker (pid:68) exited with code 1.
[787c9zrzl4] [2024-03-11 21:31:48 +0000] [72] [INFO] Booting worker with pid: 72
[787c9zrzl4] An error occurred while loading the model. Folder /model/model/steps/0/model/steps/question_is_relevant/model/steps/0/model/steps/chat_history/model/steps must exist and must be a directory in order to load runnable with steps..
[787c9zrzl4] [2024-03-11 21:31:58 +0000] [48] [INFO] Worker exiting (pid: 48)
[787c9zrzl4] [2024-03-11 21:31:58 +0000] [7] [ERROR] Worker (pid:48) exited with code 1
[787c9zrzl4] [2024-03-11 21:31:58 +0000] [7] [ERROR] Worker (pid:48) exited with code 1.
[787c9zrzl4] [2024-03-11 21:31:58 +0000] [76] [INFO] Booting worker with pid: 76
[787c9zrzl4] An error occurred while loading the model. Folder /model/model/steps/0/model/steps/question_is_relevant/model/steps/0/model/steps/chat_history/model/steps must exist and must be a directory in order to load runnable with steps..
[787c9zrzl4] [2024-03-11 21:32:08 +0000] [72] [INFO] Worker exiting (pid: 72)
[787c9zrzl4] [2024-03-11 21:32:08 +0000] [7] [ERROR] Worker (pid:72) exited with code 1
[787c9zrzl4] [2024-03-11 21:32:08 +0000] [7] [ERROR] Worker (pid:72) exited with code 1.
[787c9zrzl4] [2024-03-11 21:32:08 +0000] [80] [INFO] Booting worker with pid: 80
[787c9zrzl4] An error occurred while loading the model. Folder /model/model/steps/0/model/steps/question_is_relevant/model/steps/0/model/steps/chat_history/model/steps must exist and must be a directory in order to load runnable with steps..
[787c9zrzl4] [2024-03-11 21:32:18 +0000] [80] [INFO] Worker exiting (pid: 80)
[787c9zrzl4] [2024-03-11 21:32:18 +0000] [7] [ERROR] Worker (pid:80) exited with code 1
[787c9zrzl4] [2024-03-11 21:32:18 +0000] [7] [ERROR] Worker (pid:80) exited with code 1.
[787c9zrzl4] [2024-03-11 21:32:18 +0000] [84] [INFO] Booting worker with pid: 84
[787c9zrzl4] An error occurred while loading the model. Folder /model/model/steps/0/model/steps/question_is_relevant/model/steps/0/model/steps/chat_history/model/steps must exist and must be a directory in order to load runnable with steps..
[787c9zrzl4] [2024-03-11 21:32:28 +0000] [60] [INFO] Worker exiting (pid: 60)
[787c9zrzl4] [2024-03-11 21:32:28 +0000] [7] [ERROR] Worker (pid:60) exited with code 1
[787c9zrzl4] [2024-03-11 21:32:28 +0000] [7] [ERROR] Worker (pid:60) exited with code 1.
[787c9zrzl4] [2024-03-11 21:32:28 +0000] [88] [INFO] Booting worker with pid: 88
[787c9zrzl4] An error occurred while loading the model. Folder /model/model/steps/0/model/steps/question_is_relevant/model/steps/0/model/steps/chat_history/model/steps must exist and must be a directory in order to load runnable with steps..
[787c9zrzl4] [2024-03-11 21:32:38 +0000] [52] [INFO] Worker exiting (pid: 52)
[787c9zrzl4] [2024-03-11 21:32:38 +0000] [7] [ERROR] Worker (pid:52) exited with code 1
[787c9zrzl4] [2024-03-11 21:32:38 +0000] [7] [ERROR] Worker (pid:52) exited with code 1.
[787c9zrzl4] [2024-03-11 21:32:38 +0000] [92] [INFO] Booting worker with pid: 92
[787c9zrzl4] An error occurred while loading the model. Folder /model/model/steps/0/model/steps/question_is_relevant/model/steps/0/model/steps/chat_history/model/steps must exist and must be a directory in order to load runnable with steps..
[787c9zrzl4] [2024-03-11 21:32:48 +0000] [92] [INFO] Worker exiting (pid: 92)
[787c9zrzl4] [2024-03-11 21:32:48 +0000] [7] [ERROR] Worker (pid:92) exited with code 1
[787c9zrzl4] [2024-03-11 21:32:48 +0000] [7] [ERROR] Worker (pid:92) exited with code 1.
[787c9zrzl4] [2024-03-11 21:32:48 +0000] [96] [INFO] Booting worker with pid: 96
[787c9zrzl4] An error occurred while loading the model. Folder /model/model/steps/0/model/steps/question_is_relevant/model/steps/0/model/steps/chat_history/model/steps must exist and must be a directory in order to load runnable with steps..
[787c9zrzl4] [2024-03-11 21:32:58 +0000] [88] [INFO] Worker exiting (pid: 88)
[787c9zrzl4] An error occurred while loading the model. Folder /model/model/steps/0/model/steps/question_is_relevant/model/steps/0/model/steps/chat_history/model/steps must exist and must be a directory in order to load runnable with steps..
[787c9zrzl4] [2024-03-11 21:32:58 +0000] [76] [INFO] Worker exiting (pid: 76)
[787c9zrzl4] [2024-03-11 21:32:58 +0000] [7] [ERROR] Worker (pid:88) exited with code 1
[787c9zrzl4] [2024-03-11 21:32:58 +0000] [7] [ERROR] Worker (pid:88) exited with code 1.
[787c9zrzl4] [2024-03-11 21:32:58 +0000] [108] [INFO] Booting worker with pid: 108
[787c9zrzl4] [2024-03-11 21:32:58 +0000] [7] [ERROR] Worker (pid:76) exited with code 1
[787c9zrzl4] [2024-03-11 21:32:58 +0000] [7] [ERROR] Worker (pid:76) exited with code 1.
[787c9zrzl4] [2024-03-11 21:32:58 +0000] [109] [INFO] Booting worker with pid: 109
[787c9zrzl4] An error occurred while loading the model. Folder /model/model/steps/0/model/steps/question_is_relevant/model/steps/0/model/steps/chat_history/model/steps must exist and must be a directory in order to load runnable with steps..
[787c9zrzl4] [2024-03-11 21:32:59 +0000] [96] [INFO] Worker exiting (pid: 96)
[787c9zrzl4] [2024-03-11 21:32:59 +0000] [7] [ERROR] Worker (pid:96) exited with code 1
[787c9zrzl4] [2024-03-11 21:32:59 +0000] [7] [ERROR] Worker (pid:96) exited with code 1.
[787c9zrzl4] [2024-03-11 21:32:59 +0000] [116] [INFO] Booting worker with pid: 116
[787c9zrzl4] An error occurred while loading the model. Folder /model/model/steps/0/model/steps/question_is_relevant/model/steps/0/model/steps/chat_history/model/steps must exist and must be a directory in order to load runnable with steps..
[787c9zrzl4] [2024-03-11 21:33:01 +0000] [109] [INFO] Worker exiting (pid: 109)
[787c9zrzl4] [2024-03-11 21:33:01 +0000] [7] [ERROR] Worker (pid:109) exited with code 1
[787c9zrzl4] [2024-03-11 21:33:01 +0000] [7] [ERROR] Worker (pid:109) exited with code 1.
[787c9zrzl4] [2024-03-11 21:33:01 +0000] [120] [INFO] Booting worker with pid: 120
[787c9zrzl4] An error occurred while loading the model. Folder /model/model/steps/0/model/steps/question_is_relevant/model/steps/0/model/steps/chat_history/model/steps must exist and must be a directory in order to load runnable with steps..
[787c9zrzl4] [2024-03-11 21:33:04 +0000] [108] [INFO] Worker exiting (pid: 108)
[787c9zrzl4] [2024-03-11 21:33:04 +0000] [7] [ERROR] Worker (pid:108) exited with code 1
[787c9zrzl4] [2024-03-11 21:33:04 +0000] [7] [ERROR] Worker (pid:108) exited with code 1.
[787c9zrzl4] [2024-03-11 21:33:04 +0000] [124] [INFO] Booting worker with pid: 124
[787c9zrzl4] An error occurred while loading the model. Folder /model/model/steps/0/model/steps/question_is_relevant/model/steps/0/model/steps/chat_history/model/steps must exist and must be a directory in order to load runnable with steps..
[787c9zrzl4] [2024-03-11 21:33:08 +0000] [120] [INFO] Worker exiting (pid: 120)
[787c9zrzl4] An error occurred while loading the model. Folder /model/model/steps/0/model/steps/question_is_relevant/model/steps/0/model/steps/chat_history/model/steps must exist and must be a directory in order to load runnable with steps..
[787c9zrzl4] [2024-03-11 21:33:08 +0000] [84] [INFO] Worker exiting (pid: 84)
[787c9zrzl4] [2024-03-11 21:33:08 +0000] [7] [ERROR] Worker (pid:120) exited with code 1
[787c9zrzl4] [2024-03-11 21:33:08 +0000] [7] [ERROR] Worker (pid:120) exited with code 1.
[787c9zrzl4] [2024-03-11 21:33:08 +0000] [128] [INFO] Booting worker with pid: 128
[787c9zrzl4] [2024-03-11 21:33:08 +0000] [7] [ERROR] Worker (pid:84) exited with code 1
[787c9zrzl4] [2024-03-11 21:33:08 +0000] [7] [ERROR] Worker (pid:84) exited with code 1.
[787c9zrzl4] [2024-03-11 21:33:08 +0000] [129] [INFO] Booting worker with pid: 129
[787c9zrzl4] An error occurred while loading the model. Folder /model/model/steps/0/model/steps/question_is_relevant/model/steps/0/model/steps/chat_history/model/steps must exist and must be a directory in order to load runnable with steps..
[787c9zrzl4] [2024-03-11 21:33:13 +0000] [128] [INFO] Worker exiting (pid: 128)
[787c9zrzl4] [2024-03-11 21:33:13 +0000] [7] [ERROR] Worker (pid:128) exited with code 1
[787c9zrzl4] [2024-03-11 21:33:13 +0000] [7] [ERROR] Worker (pid:128) exited with code 1.
[787c9zrzl4] [2024-03-11 21:33:13 +0000] [136] [INFO] Booting worker with pid: 136
[787c9zrzl4] An error occurred while loading the model. Folder /model/model/steps/0/model/steps/question_is_relevant/model/steps/0/model/steps/chat_history/model/steps must exist and must be a directory in order to load runnable with steps..
[787c9zrzl4] [2024-03-11 21:33:18 +0000] [129] [INFO] Worker exiting (pid: 129)
[787c9zrzl4] [2024-03-11 21:33:18 +0000] [7] [ERROR] Worker (pid:129) exited with code 1
[787c9zrzl4] [2024-03-11 21:33:18 +0000] [7] [ERROR] Worker (pid:129) exited with code 1.
[787c9zrzl4] [2024-03-11 21:33:18 +0000] [140] [INFO] Booting worker with pid: 140
[787c9zrzl4] An error occurred while loading the model. Folder /model/model/steps/0/model/steps/question_is_relevant/model/steps/0/model/steps/chat_history/model/steps must exist and must be a directory in order to load runnable with steps..
[787c9zrzl4] [2024-03-11 21:33:19 +0000] [116] [INFO] Worker exiting (pid: 116)
[787c9zrzl4] [2024-03-11 21:33:19 +0000] [7] [ERROR] Worker (pid:116) exited with code 1
[787c9zrzl4] [2024-03-11 21:33:19 +0000] [7] [ERROR] Worker (pid:116) exited with code 1.
[787c9zrzl4] [2024-03-11 21:33:19 +0000] [144] [INFO] Booting worker with pid: 144
[787c9zrzl4] An error occurred while loading the model. Folder /model/model/steps/0/model/steps/question_is_relevant/model/steps/0
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [X] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [X] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [X] `integrations/databricks`: Databricks integrations

**Comment by serena-ruan** [comment]
@CarlosLabrado So this only happens when you use the workspace registry right? Could you provide the screenshot of your model artifacts folder? From the log we should load your model from model/model folder

**Comment by CarlosLabrado** [comment]
I don't know if it "only" happens with workspace registry because when I try to use the "databricks-uc" I get a firewall error (already contacted support about it), but I assume it should work with workspace registry right?

Meanwhile, screenshots of the model artifacts folders:

![image](https://github.com/mlflow/mlflow/assets/4044758/50b7aa2b-bed7-41f5-81a3-0d0dd2b2faa9)


![image](https://github.com/mlflow/mlflow/assets/4044758/5c26f475-a75d-4481-81da-7ccd52e9e55a)

**Comment by CarlosLabrado** [comment]
I can get past a bit further by not using a RunnableBranch:

```python
branch_node = RunnableBranch(
    (lambda x: "yes" in x["question_is_relevant"].lower(), relevant_question_chain),
    (lambda x: "no" in x["question_is_relevant"].lower(), irrelevant_question_chain),
    irrelevant_question_chain
)

full_chain = (
        {
            "question_is_relevant": is_about_databricks_chain,
            "question": itemgetter("messages") | RunnableLambda(extract_question),
            "chat_history": itemgetter("messages") | RunnableLambda(extract_history),
        }
        | branch_node 
)
```

to use a function instead:
```python
def route(info):
    if "yes" in info["question_is_relevant"].lower():
        return relevant_question_chain
    elif "no" in info["question_is_relevant"].lower():
        return irrelevant_question_chain
    else:
        return irrelevant_question_chain


full_chain = (
        {
            "question_is_relevant": is_about_databricks_chain,
            "question": itemgetter("messages") | RunnableLambda(extract_question),
            "chat_history": itemgetter("messages") | RunnableLambda(extract_history),
        }
        | RunnableLambda(route)
)

```

The endpoint is now created successfully, but when you make a call you get:
`{"error_code": "BAD_REQUEST", "message": "1 tasks failed. Errors: {0: 'error: InvalidConfigurationError(\"You haven\\'t configured the CLI yet! Please configure by entering `/opt/conda/envs/mlflow-env/bin/gunicorn configure`\") Traceback (most recent call last):\\n  File \"/opt/conda/envs/mlflow-env/lib/python3.10/site-packages/mlflow/langchain/api_request_parallel_processor.py\", line 206, in call_api\\n    response = self.lc_model.invoke(\\n  File \"/opt/conda/envs/mlflow-env/lib/python3.10/site-packages/langchain_core/runnables/base.py\", line 2053, in invoke\\n    input = step.invoke(\\n  File \"/opt/conda/envs/mlflow-env/lib/python3.10/site-packages/langchain_core/runnables/base.py\", line 2692, in invoke\\n    output = {key: future.result() for key, future in zip(steps, futures)}\\n  File \"/opt/conda/envs/mlflow-env/lib/python3.10/site-packages/langchain_core/runnables/base.py\", line 2692, in <dictcomp>\\n    output = {key: future.result() for key, future in zip(steps, futures)}\\n  File \"/opt/conda/envs/mlflow-env/lib/python3.10/concurrent/futures/_base.py\", line 458, in result\\n    return self.__get_result()\\n  File \"/opt/conda/envs/mlflow-env/lib/python3.10/concurrent/futures/_base.py\", line 403, in __get_result\\n    raise self._exception\\n  File \"/opt/conda/envs/mlflow-env/lib/python3.10/concurrent/futures/thread.py\", line 58, in run\\n    result = self.fn(*self.args, **self.kwargs)\\n  File \"/opt/conda/envs/mlflow-env/lib/python3.10/site-packages/langchain_core/runnables/base.py\", line 2053, in invoke\\n    input = step.invoke(\\n  File \"/opt/conda/envs/mlflow-env/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py\", line 166, in invoke\\n    self.generate_prompt(\\n  File \"/opt/conda/envs/mlflow-env/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py\", line 544, in generate_prompt\\n    return self.generate(prompt_messages, stop=stop, callbacks=callbacks, **kwargs)\\n  File \"/opt/conda/envs/mlflow-env/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py\", line 408, in generate\\n    raise e\\n  File \"/opt/conda/envs/mlflow-env/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py\", line 398, in generate\\n    self._generate_with_cache(\\n  File \"/opt/conda/envs/mlflow-env/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py\", line 577, in _generate_with_cache\\n    return self._generate(\\n  File \"/opt/conda/envs/mlflow-env/lib/python3.10/site-packages/langchain_community/chat_models/mlflow.py\", line 122, in _generate\\n    resp = self._client.predict(endpoint=self.endpoint, inputs=data)\\n  File \"/opt/conda/envs/mlflow-env/lib/python3.10/site-packages/mlflow/deployments/databricks/__init__.py\", line 201, in predict\\n    return self._call_endpoint(\\n  File \"/opt/conda/envs/mlflow-env/lib/python3.10/site-packages/mlflow/deployments/databricks/__init__.py\", line 138, in _call_endpoint\\n    host_creds=get_databricks_host_creds(self.target_uri),\\n  File \"/opt/conda/envs/mlflow-env/lib/python3.10/site-packages/mlflow/utils/databricks_utils.py\", line 445, in get_databricks_host_creds\\n    config = provider.get_config()\\n  File \"/opt/conda/envs/mlflow-env/lib/python3.10/site-packages/databricks_cli/configure/provider.py\", line 134, in get_config\\n    raise InvalidConfigurationError.for_profile(None)\\ndatabricks_cli.utils.InvalidConfigurationError: You haven\\'t configured the CLI yet! Please configure by entering `/opt/conda/envs/mlflow-env/bin/gunicorn configure`\\n\\n request payload: {\\'messages\\': [{\\'role\\': \\'user\\', \\'content\\': \\'What is Apache Spark?\\'}, {\\'role\\': \\'assistant\\', \\'content\\': \\'Apache Spark is an open-source data processing engine that is widely used in big data analytics.\\'}, {\\'role\\': \\'user\\', \\'content\\': \\'Does it support streaming?\\'}]}'}"}`

**Comment by CarlosLabrado** [comment]
I was able to bypass this last error by modifying the get_retriever function based on[ this post](https://community.databricks.com/t5/machine-learning/problem-when-serving-a-langchain-model-on-databricks/td-p/59506/page/2) from "DataWrangler" 

```python
def get_retriever(persist_dir: str = None):
    import gunicorn

    import logging

    import traceback
    logging.basicConfig(filename='error.log', level=logging.DEBUG)

    os.environ["DATABRICKS_HOST"] = host
    # Get the vector search index
    vsc = VectorSearchClient(workspace_url=os.environ["DATABRICKS_HOST"],
                             personal_access_token=os.environ["DATABRICKS_TOKEN"],
                             disable_notice=True)

    print('initialized VectorSearchClient')

    vs_index = vsc.get_index(
        endpoint_name=VECTOR_SEARCH_ENDPOINT_NAME,
        index_name=index_name
    )

    # Create the retriever
    try:
        print('trying to initialize vectorstore')
        vectorstore = DatabricksVectorSearch(
            vs_index, text_column="content", embedding=embedding_model, columns=["url"]
        )

        retriever = vectorstore.as_retriever(search_kwargs={'k': 4})

        print('initialized vectorstore')

        return retriever
    except BaseException as e:
        print("An error occurred:", str(e))
        traceback.print_exc()


retriever = get_retriever()
```

**Comment by serena-ruan** [comment]
@CarlosLabrado Sorry for the late reply. `invalidConfigurationError(\"You haven\\'t configured the CLI yet!` usually happens when there're environment variables missing during endpoint creation.

The original problem looks weird... because you definitely have that folder. If you load the model locally does it work?

**Comment by CarlosLabrado** [comment]
@serena-ruan  No worries. 

Yes I had to add the environment variable for that CLI error.

For the original problem, yes if I just locally load the model from MLflow it works.
