### ISSUE TITLE
[BUG] importing mlflow fails in an environment where os.cpu_count() returns None

### ISSUE THREAD

**Issue by HiromuHota** [mlflow/mlflow#11810]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Other

### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### MLflow version

- Client: 2.12.1
- Tracking server: N/A

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Snowpark (Python environment provided from SnowFlake)
- **Python version**: 3.8
- **yarn version, if running the dev UI**: N/A

### Describe the problem

importing mlflow fails in an environment where os.cpu_count() returns None.
`os.cpu_count()` could return None if undermined (https://docs.python.org/3/library/os.html#os.cpu_count). For example, in SnowPark, it returns None (see this another issue at SnowPark https://community.snowflake.com/s/question/0D5Do000004rLAtKAM/running-shap-with-snowpark-model).

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```
>>> import os
>>> os.cpu_count = lambda: None  # replicate an environment where `os.cpu_count()` returns None
>>> import mlflow
```

### Stack trace

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.pyenv/versions/base/lib/python3.8/site-packages/mlflow/__init__.py", line 34, in <module>
    from mlflow import (
  File "/home/ubuntu/.pyenv/versions/base/lib/python3.8/site-packages/mlflow/artifacts/__init__.py", line 11, in <module>
    from mlflow.tracking import _get_store
  File "/home/ubuntu/.pyenv/versions/base/lib/python3.8/site-packages/mlflow/tracking/__init__.py", line 8, in <module>
    from mlflow.tracking._model_registry.utils import (
  File "/home/ubuntu/.pyenv/versions/base/lib/python3.8/site-packages/mlflow/tracking/_model_registry/utils.py", line 4, in <module>
    from mlflow.store.db.db_types import DATABASE_ENGINES
  File "/home/ubuntu/.pyenv/versions/base/lib/python3.8/site-packages/mlflow/store/__init__.py", line 1, in <module>
    from mlflow.store import _unity_catalog  # noqa: F401
  File "/home/ubuntu/.pyenv/versions/base/lib/python3.8/site-packages/mlflow/store/_unity_catalog/__init__.py", line 1, in <module>
    from mlflow.store._unity_catalog import registry  # noqa: F401
  File "/home/ubuntu/.pyenv/versions/base/lib/python3.8/site-packages/mlflow/store/_unity_catalog/registry/__init__.py", line 1, in <module>
    from mlflow.store._unity_catalog.registry import rest_store  # noqa: F401
  File "/home/ubuntu/.pyenv/versions/base/lib/python3.8/site-packages/mlflow/store/_unity_catalog/registry/rest_store.py", line 66, in <module>
    from mlflow.store.artifact.presigned_url_artifact_repo import PresignedUrlArtifactRepository
  File "/home/ubuntu/.pyenv/versions/base/lib/python3.8/site-packages/mlflow/store/artifact/presigned_url_artifact_repo.py", line 15, in <module>
    from mlflow.store.artifact.cloud_artifact_repo import CloudArtifactRepository
  File "/home/ubuntu/.pyenv/versions/base/lib/python3.8/site-packages/mlflow/store/artifact/cloud_artifact_repo.py", line 17, in <module>
    from mlflow.store.artifact.artifact_repo import ArtifactRepository
  File "/home/ubuntu/.pyenv/versions/base/lib/python3.8/site-packages/mlflow/store/artifact/artifact_repo.py", line 14, in <module>
    from mlflow.utils.file_utils import ArtifactProgressBar, create_tmp_dir
  File "/home/ubuntu/.pyenv/versions/base/lib/python3.8/site-packages/mlflow/utils/file_utils.py", line 58, in <module>
    MAX_PARALLEL_DOWNLOAD_WORKERS = os.cpu_count() * 2
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [X] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [X] `area/projects`: MLproject format, project running backends
- [X] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [X] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by daniellok-db** [comment]
Thanks for reporting this! I've filed #11812 to fix it.
