### ISSUE TITLE
[FR] Add regex comparator `~` to search functions for string attributes and tags

### ISSUE THREAD

**Issue by sydneyw-spotify** [mlflow/mlflow#11898]
### Willingness to contribute

Yes. I can contribute this feature independently.

### Proposal Summary

Currently the only string comparators available to [Search Experiments](https://mlflow.org/docs/latest/search-experiments.html) and [Search Runs](https://www.mlflow.org/docs/2.2.1/search-runs.html#comparator) are `=, !=, LIKE, ILIKE`. While these comparators are sufficient for many use cases, they only allow for relatively simple queries, especially considering MLflow only allows you to chain together expressions with the `AND` operator and is missing the `OR` operator (see: https://github.com/mlflow/mlflow/issues/6075).  While `LIKE` and `ILIKE` allow you to do some string matching they both lack the complexity of full regex expressions. 

In addition, the FileStore already substitutes `LIKE` for the [regex operator](https://github.com/mlflow/mlflow/blob/master/mlflow/utils/search_utils.py#L43) causing operations that worked in the FileStore to error out in a SqlAlchemyStore.

### Motivation

> #### What is the use case for this feature?

Users can make more complex queries of their experiments and runs. 

> #### Why is this use case valuable to support for MLflow users in general?

String querying is limited to relatively simple operations, this unlocks a much deeper querying ability. Additionally, regex supports an [OR operator](https://stackoverflow.com/questions/15986187/or-condition-in-regex) which at least partially unblocks user in need of that operation, while being much simpler to implement.  

> #### Why is this use case valuable to support for your project(s) or organization?

We need to query tags in a way that is outside the scope of `LIKE` 

> #### Why is it currently difficult to achieve this use case?

MLflow string querying is limited.

### Details

Modify [this function](https://github.com/mlflow/mlflow/blob/master/mlflow/utils/search_utils.py#L194-L206) to be this:

```python
@staticmethod
def get_sql_comparison_func(comparator, dialect):
    import sqlalchemy as sa

    def comparison_func(column, value):
        if comparator == "LIKE":
            return column.like(value)
        elif comparator == "ILIKE":
            return column.ilike(value)
        elif comparator == "IN":
            return column.in_(value)
        elif comparator == "NOT IN":
            return ~column.in_(value)
        elif comparator == "~":
            return column.regexp_match(value)
        return SearchUtils.get_comparison_func(comparator)(column, value)
```
And update all comparator checks to include the `~` operator such as [here](https://github.com/mlflow/mlflow/blob/master/mlflow/utils/search_utils.py#L115-L117) and [here](https://github.com/mlflow/mlflow/blob/master/mlflow/store/tracking/sqlalchemy_store.py#L1936):
```python
  VALID_PARAM_COMPARATORS = {"!=", "=", "~", LIKE_OPERATOR, ILIKE_OPERATOR}
  VALID_TAG_COMPARATORS = {"!=", "=", "~", LIKE_OPERATOR, ILIKE_OPERATOR}
  VALID_STRING_ATTRIBUTE_COMPARATORS = {"!=", "=", "~", LIKE_OPERATOR, ILIKE_OPERATOR, "IN", "NOT IN"}
```
and

```python
if comparator not in ("=", "!=", "LIKE", "ILIKE", "~"):
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [X] `area/server-infra`: MLflow Tracking server backend
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by sydneyw-spotify** [comment]
@harupy I opened this issue, happy to take it on myself

**Comment by yoginlangalia** [comment]
I have opened a PR to address this: #21183

The implementation extends the existing `RLIKE` comparator (already supported in `SearchTraceUtils`) to run and experiment search for params, tags, string attributes, and datasets. The SQL layer already handled `RLIKE` for all 4 dialects, so the main changes are adding `RLIKE` to the `SearchUtils` comparator sets and the in-memory `get_comparison_func()` dispatch.
