### ISSUE TITLE
[BUG] Tracking URI and experiment name are set wrong in some multiprocessing start methods

### ISSUE THREAD

**Issue by elenavolkova93** [mlflow/mlflow#12315]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 2.13.2

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.04.6 LTS
- **Python version**: Python 3.9.19
- **yarn version, if running the dev UI**: -

### Describe the problem

According to the [docs](https://mlflow.org/docs/latest/tracking/tracking-api.html), MLFlow supports starting runs in parallel processes:
```python
import mlflow
import multiprocessing as mp

def train_model(params):
    with mlflow.start_run():
        mlflow.log_param("p", params)
        ...

if __name__ == "__main__":
    params = [0.01, 0.02, ...]
    pool = mp.Pool(processes=4)
    pool.map(train_model, params)
```

However, that only works with multiprocessing start method `fork`. If you use other start methods (`spawn` or `forkserver`), then the run can get logged to the wrong place.

### Tracking information

```shell
System information: Linux #202-Ubuntu SMP Fri Apr 26 12:29:36 UTC 2024
Python version: 3.9.19
MLflow version: 2.13.2
MLflow module location: /home/elenav/noi-processing/venv/lib/python3.9/site-packages/mlflow/__init__.py
Tracking URI: prod-mlruns
Registry URI: prod-mlruns
MLflow environment variables: 
  MLFLOW_TRACKING_URI: prod-mlruns
MLflow dependencies: 
  Flask: 3.0.3
  Jinja2: 3.1.3
  alembic: 1.13.1
  boto3: 1.34.93
  botocore: 1.34.93
  cachetools: 5.3.3
  click: 8.1.7
  cloudpickle: 3.0.0
  docker: 7.0.0
  entrypoints: 0.4
  gitpython: 3.1.43
  google-cloud-storage: 2.16.0
  graphene: 3.3
  gunicorn: 21.2.0
  importlib-metadata: 7.1.0
  markdown: 3.6
  matplotlib: 3.8.3
  numpy: 1.26.4
  opentelemetry-api: 1.25.0
  opentelemetry-sdk: 1.25.0
  packaging: 24.0
  pandas: 2.2.1
  protobuf: 3.19.6
  pyarrow: 15.0.2
  pytz: 2024.1
  pyyaml: 6.0.1
  querystring-parser: 1.2.4
  requests: 2.31.0
  scikit-learn: 1.4.1.post1
  scipy: 1.13.0
  sqlalchemy: 2.0.29
  sqlparse: 0.5.0
```

### Code to reproduce issue

1. Set the tracking URI to the production MLFlow server:

```shell
MLFLOW_TRACKING_URI="prod-mlruns"
```

2. Run the multiprocessing example from the docs, but with multiprocessing start method `spawn`:

```python
import mlflow
import multiprocessing as mp

def train_model(param):
    with mlflow.start_run():
        mlflow.log_param("p", param)

if __name__ == "__main__":
    params = [0.01, 0.02, 0.03, 0.04]

    # Update the tracking URI to something other than 'prod-mlflow'
    mlflow.set_tracking_uri("")

    mlflow.set_experiment("mptest")

    mp.set_start_method("spawn")
    # If the line above is replaced by the line below, everything works correctly: 
    # mp.set_start_method("fork")

    pool = mp.Pool(processes=4)
    pool.map(train_model, params)
```

### Stack trace

There is no error raised, but the run is logged to the wrong place.

I expect the runs to be logged to `./mlruns`, under experiment `mptest`, but the runs are instead logged to `prod-mlflow` under experiment `Default`.

If not supporting non-fork start methods is a deliberate choice, I would expect to be notified about it in the docs.

### Other info / logs

This is because a child process started with `spawn` method doesn't get access to the global variables that MLFlow uses to keep track of the experiment ID and the tracking URI. The same problem with the `loky` backend using `joblib`:

```python
import mlflow
from joblib import Parallel, delayed

def train_model(param):
    with mlflow.start_run():
        mlflow.log_param("p", param)

if __name__ == "__main__":
    params = [0.01, 0.02, 0.03, 0.04]

    mlflow.set_tracking_uri("")
    mlflow.set_experiment("mptest")

    Parallel(n_jobs=4, verbose=1)(delayed(train_model)(x) for x in params)
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [X] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by B-Step62** [comment]
@elenavolkova93 Thank you for bringing this issue to our attention!

You're right, the current experiment and tracking URI are stored in global variables. Since these global variables are not automatically propagated to the child processes created with `spawn` mode, the default values are used instead.

As the limitation resides in language design, automatically propagating these settings between processes created with spawn would require large design changes. Therefore, I would suggest a practical workaround for now - setting these variables explicitly within each process:

```
import mlflow
import multiprocessing as mp

def train_model(param):
    mlflow.set_tracking_uri("")
    mlflow.set_experiment("mptest")

    with mlflow.start_run():
        mlflow.log_param("p", param)

if __name__ == "__main__":
    params = [0.01, 0.02, 0.03, 0.04]
    mp.set_start_method("spawn")

    pool = mp.Pool(processes=4)
    pool.map(train_model, params)
```

In the meantime, I will also update the documentation for the information. I hope this answer helps clarify the issue and provides a viable solution for your use case!

**Comment by elenavolkova93** [comment]
@B-Step62 ok, thanks, that's what I've tried. I have a little class MLFlowState, that can get the active run, the tracking URI, and the experiment ID in the main process, and reset/resume them in the child process, and it's passed to all the worker functions.
