### ISSUE TITLE
[FR] Support uv package installer when inferring requirements (i.e. when logging model)

### ISSUE THREAD

**Issue by robmcd** [mlflow/mlflow#12478]
### Willingness to contribute

No. I cannot contribute this feature at this time.

### Proposal Summary

When using the **uv** package manager to create virtual environments and install packages mlflow is unable to infer requirements.txt when auto-logging a model.

I guess this is caused by uv behaviour being slightly different to pip.

### Motivation

> #### What is the use case for this feature?
ability to auto-log models (with inferred dependencies) based on environments managed by the uv package manager

> #### Why is this use case valuable to support for MLflow users in general?
usage of uv is increasing. It's faster than pip.

> #### Why is this use case valuable to support for your project(s) or organization?

> #### Why is it currently difficult to achieve this use case?
errors encountered unless we manually log the model with explicitly specified dependencies in the argument.

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment]
Hi @robmcd we'll take a look at this. No promises on an integration (that's a very sizable effort), but we'll keep this in mind. Thanks for the request!

**Comment by alexeyshockov** [comment]
Hey folks, with the latest additions uv looks more and more usable in MLflow context.

What I mean is that it can replace both pyenv/Conda and PIP. uv is able to automatically install a Python interpreter and the required packages.

I'm actually willing to contribute, if you can guide me.

**Comment by timvink** [comment]
+1 for this!

A potential route might to have `mlflow.models.infer_pip_requirements()` detect the presence of a `uv.lock` file. If present, it can determine the pip requirements by using a subprocess that runs `uv export --no-dev --no-hashes --no-editable --frozen --locked`

Likewise, `mlflow.sklearn.get_default_conda_env()` could create a conda file by looking for the presence of a `.python-version` file (which `uv` will add to projects)

**Comment by harupy** [comment]
We started looking into this. Do you want to log `pyproject.toml` and `uv.lock` file.

**Comment by timvink** [comment]
I'm not sure how it works exactly, but things like databricks serving endpoints seems to build the environment from the conda specification.

The way we work now is to export the uv.lock file to a requirements.txt file (`uv export --frozen --no-dev --no-header --no-editable --no-hashes --output-file {requirements_file}`), read that in, and log it to mlflow. Something like this:

```python
conda_env = {
    "name": "mlflow-env",
    "channels": ["conda-forge"],
    "dependencies": [f"python={python_version}", {"pip": requirements}],
}
mlflow.pyfunc.log_model(
    conda_env=conda_env,
    ...
)
```

So having a `uv.lock` file logged with the model is a nice-to-have. In the future mlflow might want to use `uv` to create environments, and then it's a must-have. Might as well start including it now already.

**Comment by harupy** [comment]
@timvink Thanks for the reply! What I had in my mind was something like this:

```python
mlflow.pyfunc.log_model(
    uv_lock="/path/to/uv.lock",  # do we need both pyproject.toml and uv.lock?
    ...
)

# When mlflow or model serving needs to restore the model environment,
# just run `uv run` (to let uv sync the environment and serve the model in that environment)
```

I'm not familiar with uv at all, to be honest.

**Comment by timvink** [comment]
project_root parameter makes a lot of sense, good abstraction because it can be extended to any python environment system. But it does make it harder to test, as you'll have to create temporary directories with the required files. 

Maybe instead of `conda_env` and `pip_requirements` we could use `python_version` and `requirements: path | list[str]`. Then you can pass a uv.lock file, a requirements.txt file, or a list with requirements.

Btw, it's worth the time to read the docs for `uv` start to finish. The concepts look very familiar to older tools like `rye` and `poetry`.

**Comment by wpdonders** [comment]
Just dropping by to +1 this feature. Especially because in terms of speed, `uv` >> `pip` > `conda` (in my experience); and functionally, `uv` allows specification of the Python version (like `conda`,  but unlike  `pip`). 

I saw mention of `rye` in the comments --- `uv` is the successor to it and maintained by the same people at astral.sh.

**Comment by harupy** [comment]
@wpdonders Thanks for the comment! Would you mind sharing how you use uv in your projects? We're investigating how people use uv for ML/AI projects.

**Comment by simonamtoft** [comment]
Found this since I'm also interested in this addition.

@harupy  I believe you should include `pyproject.toml`, `uv.lock` and `.python-version` as part of the model logging.

The `uv sync` command will update your virtual environment `.venv` with the appropriate python version and packages.

**Comment by marcocamilo** [comment]
Also just dropping by to +1 this feature. uv seems to be more agnostic than conda. With uv, you can simply abstract the dependencies of your project not only at lightning speed, but also in a manager-agnostic way via `pyproject.toml`, `requirements.txt`, and even the `uv.lock` file, which ensures environment reproducibility and dependency tracking. It would be a huge upgrade to replace the current conda implementation with uv (given more and more developers are adopting it, seems to be a future-proof decision MLflow should definitely adopt).

**Comment by auggie246** [comment]
agreed that this feature will be very useful and these 3 files `pyproject.toml`, `uv.lock` and `.python-version` will be more than sufficient

**Comment by j-adamczyk** [comment]
+1, we evaluated using MLFlow and resigned due to lack of Poetry and uv support, since we manage everything with them.

**Comment by atinary-rdaod** [comment]
+1

**Comment by peyerroger** [comment]
+1

**Comment by sadelcarpio** [comment]
+1

**Comment by Mberga14** [comment]
+1

**Comment by jpm2617** [comment]
+1

**Comment by debu-sinha** [comment]
## Design Document: UV Package Manager Support

I've drafted a detailed design document for implementing UV support in MLflow:

**Design Doc:** https://github.com/debu-sinha/design-docs/blob/main/mlflow/mlflow-uv-support-design-doc-v1.md

### Summary

**Phase 1 (MVP):** Automatic UV detection and dependency export
- Detect `uv.lock` in project directory during `log_model()`
- Export to pip-compatible `requirements.txt` via `uv export`
- Graceful fallback to existing pip inference
- 100% backwards compatible - no API changes required

**Key Features:**
- Monorepo support (walks up parent directories)
- UV version checking (requires 0.5.0+)
- Observability tags (`mlflow.requirements.source`)
- Comprehensive error handling with fallbacks

**Phase 2 (Future):**
- Store `uv.lock` alongside model artifacts
- Add `env_manager="uv"` for faster environment restoration
- UV workspace support

### Requesting Feedback

@BenWilson2 Would appreciate your architectural review of this approach. Happy to address any concerns or iterate on the design.

The design prioritizes backwards compatibility and "just works" behavior for UV users while maintaining all existing pip functionality.

**Comment by debu-sinha** [comment]
**Update: Implementation Ready for Testing (PR #20344)**

I've implemented native UV support for MLflow's automatic dependency inference. The PR is ready for community testing and feedback.

**What's implemented:**

- Automatic UV project detection (`uv.lock` + `pyproject.toml` in CWD)
- Dependency export via `uv export` -> `requirements.txt`
- UV artifacts logged with model (`uv.lock`, `pyproject.toml`, `.python-version`)
- Monorepo support via explicit `uv_lock` parameter
- Dependency groups support (`MLFLOW_UV_GROUPS`, `MLFLOW_UV_ONLY_GROUPS`, `MLFLOW_UV_EXTRAS`)
- UV-based environment restoration functions

**Basic usage (just works):**
```python
# If you have uv.lock + pyproject.toml in your project directory
mlflow.sklearn.log_model(model, "model")  # UV detected automatically
```

**Monorepo support:**
```python
mlflow.sklearn.log_model(model, "model", uv_lock="/path/to/monorepo/uv.lock")
```

**Configuration:**
```bash
MLFLOW_LOG_UV_FILES=false python train.py  # Disable UV file logging
MLFLOW_UV_ONLY_GROUPS="serving" python train.py  # Export only serving deps
```

**To test:**
```bash
pip install git+https://github.com/mlflow/mlflow.git@refs/pull/20344/head
```

PR: #20344
Design doc: https://github.com/debu-sinha/design-docs/blob/main/mlflow/uv-support-design-doc-v2.md

Would appreciate feedback on the API design and any edge cases I should handle.

Thankyou @WeichenXu123 and @harupy  for reviewing design and providing valuable feedback!

**Comment by B-Step62** [comment]
This shipped in **MLflow 3.11.1**. MLflow now supports `uv` for model dependency management: when you log a model from a uv project it detects `uv.lock` / `pyproject.toml` and can restore the environment with uv. Docs: https://mlflow.org/docs/latest/ml/model/dependencies

Thanks for all the input and interest here, please give it a try and let us know how it works for your uv workflows! @robmcd @timvink @wpdonders @hellmrf @simonamtoft @marcocamilo @auggie246 @j-adamczyk @atinary-rdaod @peyerroger @sadelcarpio @Mberga14 @jpm2617
