### ISSUE TITLE
[BUG] SHAP evaluation fails due to mlflow.exceptions.MlflowException: Incompatible input types for column columnname. Can not safely convert float64 to int32.

### ISSUE THREAD

**Issue by robmcd** [mlflow/mlflow#12516]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

mlflow, version 2.14.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **Python version**: 3.10

### Describe the problem

During evaluation I am getting an error:
mlflow.exceptions.MlflowException: Incompatible input types for column columnname. Can not safely convert float64 to int32.

There are columns in my dataframe with numpy types int8, int16, int32. However it seems inside the SHAP evaluation process they are converted to float64, then back in mlflow code it tries to compare them to the schema but the schema expects ints hence the error.

It's not clear to me if I am doing something wrong, or this is an issue with the mlflow code, or an issue in the SHAP code. I would appreciate any guidance.

### Code to reproduce issue

```
from pathlib import Path

import pandas as pd
from sklearn.model_selection import train_test_split

import mlflow
import xgboost as xgb
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

mlflow.set_tracking_uri("http://localhost:5000")
logging.getLogger('mlflow').setLevel(logging.DEBUG)
df = pd.read_parquet(Path(__file__).parent / 'df_preprocessed.parquet')
target_col = 'target'
X = df.copy()
y = X.pop(target_col)

logger.info('Splitting %d rows of data into train, validation, test datasets.', len(X))
rand = 42  # random number seed.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=rand)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=rand)
X_train, X_debug, y_train, y_debug = train_test_split(X_train, y_train, test_size=0.1, random_state=rand)

# setup experiment tracking if it hasn't already been setup
experiment_name = 'expname'
tags = dict(project_name='proj', team='myteam')
existing_experiments = mlflow.search_experiments(filter_string=f"name = '{experiment_name}'")
if not existing_experiments:
	print("Experiment doesn't exist so we will create it")
	mlflow.create_experiment(name=experiment_name, tags=tags)
mlflow.set_experiment(experiment_name)
mlflow.autolog(log_input_examples=True)

import warnings

warnings.filterwarnings(
	action='ignore', message='.*Failed to determine whether UCVolumeDatasetSource can resolve source information.*'
)

input_data_url = 's3://bucketname/folder/folder'
train_dataset = mlflow.data.from_pandas(
	pd.concat([y_train, X_train], axis='columns'),
	source=input_data_url,
	name='dataset name',
	targets=target_col,
)

xgb_model = xgb.XGBClassifier(tree_method='hist', objective='binary:logistic', random_state=42)

active_run = mlflow.start_run()
mlflow.log_input(train_dataset, context="train")
xgb_model.fit(X_train, y_train)

datas = [
	y_val,
	X_val,
]
val_dataset = mlflow.data.from_pandas(
	pd.concat(datas, axis='columns'),
	source=input_data_url,
	name='dataset - validation data',
	targets=target_col,
)

# evaluate
model_uri = mlflow.get_artifact_uri("model")
result = mlflow.evaluate(model=model_uri, data=val_dataset, model_type="classifier")
print('Result: !!!\n' + str(result))
mlflow.end_run()
```

### Stack trace

```
2024/06/28 15:28:54 DEBUG mlflow.models.evaluation.default_evaluator: 
Traceback (most recent call last):
  File "C:\dev\ws\proj\.venv\lib\site-packages\mlflow\pyfunc\__init__.py", line 698, in _validate_prediction_input
    data = _enforce_schema(data, input_schema, flavor)
  File "C:\dev\ws\proj\.venv\lib\site-packages\mlflow\models\utils.py", line 1028, in _enforce_schema
    _enforce_named_col_schema(pf_input, input_schema)
  File "C:\dev\ws\proj\.venv\lib\site-packages\mlflow\models\utils.py", line 735, in _enforce_named_col_schema
    new_pf_input[name] = _enforce_mlflow_datatype(name, pf_input[name], input_type)
  File "C:\dev\ws\proj\.venv\lib\site-packages\mlflow\models\utils.py", line 695, in _enforce_mlflow_datatype
    raise MlflowException(
mlflow.exceptions.MlflowException: Incompatible input types for column columnname. Can not safely convert float64 to int32.
```

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [X] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by daniellok-db** [comment]
Thank you for the report! We'll look into this.
