### ISSUE TITLE
[BUG] LangChain tracing does not work for abatch with config field

### ISSUE THREAD

**Issue by Peilun-Li** [mlflow/mlflow#12636]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Databricks

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

- Client: 2.14.2
- Tracking server: Databricks MLflow (can't find a version reported through UI easily. Happy to follow-up if there's instructions)

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: amzn2 Linux
- **Python version**: 3.9
- **yarn version, if running the dev UI**:

### Describe the problem

MLflow LangChain tracing works for simple `abatch` call (with only one input field). However, when providing with additional `config` field, tracing does not work anymore.

Example:
```
import mlflow
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate
from langchain_openai import OpenAI
mlflow.set_experiment(<experiment_path>)
mlflow.langchain.autolog()


llm = OpenAI(temperature=0.7, max_tokens=1000)

prompt_template = ChatPromptTemplate.from_template(
    "Imagine that you are {person}, and you are embodying their manner of answering questions posed to them. "
    "While answering, attempt to mirror their conversational style, their wit, and the habits of their speech "
    "and prose. You will emulate them as best that you can, attempting to distill their quirks, personality, "
    "and habits of engagement to the best of your ability. Feel free to fully embrace their personality, whether "
    "aspects of it are not guaranteed to be productive or entirely constructive or inoffensive."
    "The question you are asked, to which you will reply as that person, is: {question}"
)
output_parser = StrOutputParser()

chain = prompt_template | llm | output_parser

with mlflow.start_run(run_name=<run_name>):
    res = await chain.abatch(
        [{
            "person": "Richard Feynman",
            "question": "Why should we colonize Mars instead of Venus?",
        },
        {
            "person": "Linus Torvalds",
            "question": "Can I just set everyone's access to sudo to make things easier?",
        }],
    )
    print(res)
```
Running the above would have traces rendered as expected
<img width="1247" alt="image" src="https://github.com/mlflow/mlflow/assets/11920339/d67091d3-e766-4c3d-ad9d-82da37f7fd4c">

However, when providing an additional `config` field to the `abatch` method, tracing does not work anymore. (one example usage of the `config` field is to [define max_concurrency](https://github.com/langchain-ai/langchain/blob/dc131ac42a5956e354df6a58bfc5376df458d500/libs/core/langchain_core/language_models/llms.py#L439), this is documented [for batch method](https://python.langchain.com/v0.1/docs/expression_language/interface/#batch) and seems to apply the same to `abatch`)

```
import mlflow
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate
from langchain_openai import OpenAI
mlflow.set_experiment(<experiment_path>)
mlflow.langchain.autolog()


llm = OpenAI(temperature=0.7, max_tokens=1000)

prompt_template = ChatPromptTemplate.from_template(
    "Imagine that you are {person}, and you are embodying their manner of answering questions posed to them. "
    "While answering, attempt to mirror their conversational style, their wit, and the habits of their speech "
    "and prose. You will emulate them as best that you can, attempting to distill their quirks, personality, "
    "and habits of engagement to the best of your ability. Feel free to fully embrace their personality, whether "
    "aspects of it are not guaranteed to be productive or entirely constructive or inoffensive."
    "The question you are asked, to which you will reply as that person, is: {question}"
)
output_parser = StrOutputParser()

chain = prompt_template | llm | output_parser

with mlflow.start_run(run_name=<run_name>):
    res = await chain.abatch(
        [{
            "person": "Richard Feynman",
            "question": "Why should we colonize Mars instead of Venus?",
        },
        {
            "person": "Linus Torvalds",
            "question": "Can I just set everyone's access to sudo to make things easier?",
        }],
        config={"max_concurrency": 10}
    )
    print(res)
```

<img width="1006" alt="image" src="https://github.com/mlflow/mlflow/assets/11920339/8ceebe7b-1669-4f00-a1a3-31ef7207f9a4">

The same also applies to passing an empty `config` field, e.g., even if only set`config={}`, the `abatch` tracing still doesn't work.

In comparison, the tracing for `batch` is working as expected, even with the `config` field passed in.

### Tracking information

```shell
System information: Linux #1 SMP Tue Apr 23 20:32:19 UTC 2024
Python version: 3.9.13
MLflow version: 2.14.2
MLflow module location: <masked>
Tracking URI: databricks
Registry URI: databricks
MLflow environment variables: 
  MLFLOW_TRACKING_URI: databricks
MLflow dependencies: 
  Flask: 2.2.3
  Jinja2: 3.1.2
  aiohttp: 3.8.4
  alembic: 1.13.2
  boto3: 1.24.59
  botocore: 1.27.59
  cachetools: 5.3.3
  click: 8.0.4
  cloudpickle: 2.2.1
  docker: 7.1.0
  entrypoints: 0.4
  gitpython: 3.1.31
  google-cloud-storage: 1.44.0
  graphene: 3.3
  gunicorn: 22.0.0
  importlib-metadata: 6.1.0
  kubernetes: 24.2.0
  langchain: 0.2.1
  markdown: 3.4.3
  matplotlib: 3.7.1
  numpy: 1.23.5
  opentelemetry-api: 1.25.0
  opentelemetry-sdk: 1.25.0
  packaging: 24.1
  pandas: 1.5.3
  protobuf: 3.20.3
  pyarrow: 11.0.0
  pydantic: 2.8.2
  pytz: 2022.7.1
  pyyaml: 5.4.1
  querystring-parser: 1.2.4
  requests: 2.28.2
  scikit-learn: 1.5.1
  scipy: 1.10.1
  sqlalchemy: 2.0.31
  sqlparse: 0.5.0
  tiktoken: 0.7.0
```

### Code to reproduce issue

```
import mlflow
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate
from langchain_openai import OpenAI
mlflow.set_experiment(<experiment_path>)
mlflow.langchain.autolog()


llm = OpenAI(temperature=0.7, max_tokens=1000)

prompt_template = ChatPromptTemplate.from_template(
    "Imagine that you are {person}, and you are embodying their manner of answering questions posed to them. "
    "While answering, attempt to mirror their conversational style, their wit, and the habits of their speech "
    "and prose. You will emulate them as best that you can, attempting to distill their quirks, personality, "
    "and habits of engagement to the best of your ability. Feel free to fully embrace their personality, whether "
    "aspects of it are not guaranteed to be productive or entirely constructive or inoffensive."
    "The question you are asked, to which you will reply as that person, is: {question}"
)
output_parser = StrOutputParser()

chain = prompt_template | llm | output_parser

with mlflow.start_run(run_name=<run_name>):
    res = await chain.abatch(
        [{
            "person": "Richard Feynman",
            "question": "Why should we colonize Mars instead of Venus?",
        },
        {
            "person": "Linus Torvalds",
            "question": "Can I just set everyone's access to sudo to make things easier?",
        }],
        config={"max_concurrency": 10}
    )
    print(res)
```

### Stack trace

```
No error stack trace from client side
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [X] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [X] `integrations/databricks`: Databricks integrations

**Comment by B-Step62** [comment]
@Peilun-Li Thank you for reporting the issue!

This is a thread safety bug of the MLflow tracer. I've filed a fix https://github.com/mlflow/mlflow/pull/12701 and validated all traces are completed properly. You can install the patch with the following command:
```
%pip install git+https://github.com/mlflow/mlflow.git@refs/pull/12701/head -qU
```

**Comment by B-Step62** [comment]
@Peilun-Li Thank you for reporting the issue! I could reproduce the bug and it appears to be a bug in our callback injection logic. We will investigate further and implement a fix soon.

(Please ignore the above PR and label, I accidentally mixed up this issue and the other one😅)

**Comment by B-Step62** [comment]
@Peilun-Li The fix is merged in and will be released next week. You can validate the fix by installing the latest patch by `pip install git+https://github.com/mlflow/mlflow.git@master -U`.
