### ISSUE TITLE
[BUG] LangChain tracing occasionally has traces stuck in "In Progress" during chain.batch calls

### ISSUE THREAD

**Issue by Peilun-Li** [mlflow/mlflow#12669]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Databricks

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

- Client: 2.14.2
- Tracking server: Databricks MLflow (can't find a version reported through UI easily. Happy to follow-up if there's instructions)

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: amzn2 Linux
- **Python version**: 3.9
- **yarn version, if running the dev UI**:

### Describe the problem

For MLflow langchain tracing, when instrumenting through chain.batch calls (which would result in multiple traces each for a different request), occasionally we see some traces stuck in `In progress` forever, while other traces work as expected. This happens especially quite frequently when using the langchain integration provided by RAGAS (using ragas==0.1.10 here)

Example chain.batch call
```
from ragas.integrations.langchain import EvaluatorChain
from ragas.metrics import faithfulness
faithfulness_chain = EvaluatorChain(metric=faithfulness)

sample= {
    "question": "What is the capital of France?",
    "answer": "The capital of France is Paris.",
    "contexts": [
        "France, in Western Europe, encompasses medieval cities, alpine villages and Mediterranean beaches. Paris, its capital, is famed for its fashion houses, classical art museums including the Louvre and monuments like the Eiffel Tower.",
        "Paris is the capital and most populous city of France. It has an area of 105 square kilometers and a population of over 2 million residents."
    ],
    "ground_truth": "Paris"
}

import mlflow
mlflow.langchain.autolog()
mlflow.set_experiment({experiment_path})

with mlflow.start_run():
    ret = faithfulness_chain.batch([sample] * 10, config={"max_concurrency": 10})
    print(ret)
```

The above example would result in 10 traces/records/requests as we send a batch size of 10. The batch call would pass and `res` would be expected, though frequently some of the traces (as shown in Databricks UI) would stuck in `In progress` forever (see example screenshot below). I.e., we lost one trace unexpectedly. 

<img width="1351" alt="image" src="https://github.com/user-attachments/assets/9fec9668-a050-4dc2-8391-55465193f1ab">

### Tracking information

```shell
System information: Linux #1 SMP Tue Apr 23 20:32:19 UTC 2024
Python version: 3.9.13
MLflow version: 2.14.2
MLflow module location: <masked>
Tracking URI: databricks
Registry URI: databricks
MLflow environment variables: 
  MLFLOW_TRACKING_URI: databricks
MLflow dependencies: 
  Flask: 2.2.3
  Jinja2: 3.1.2
  aiohttp: 3.8.4
  alembic: 1.13.2
  boto3: 1.24.59
  botocore: 1.27.59
  cachetools: 5.3.3
  click: 8.0.4
  cloudpickle: 2.2.1
  docker: 7.1.0
  entrypoints: 0.4
  gitpython: 3.1.31
  google-cloud-storage: 1.44.0
  graphene: 3.3
  gunicorn: 22.0.0
  importlib-metadata: 6.1.0
  kubernetes: 24.2.0
  langchain: 0.2.1
  markdown: 3.4.3
  matplotlib: 3.7.1
  numpy: 1.23.5
  opentelemetry-api: 1.25.0
  opentelemetry-sdk: 1.25.0
  packaging: 24.1
  pandas: 1.5.3
  protobuf: 3.20.3
  pyarrow: 15.0.2
  pydantic: 2.8.2
  pytz: 2022.7.1
  pyyaml: 5.4.1
  querystring-parser: 1.2.4
  requests: 2.32.3
  scikit-learn: 1.5.1
  scipy: 1.10.1
  sqlalchemy: 2.0.31
  sqlparse: 0.5.0
  tiktoken: 0.7.0
```

### Code to reproduce issue

```
See example above
```

### Stack trace

```
No stack trace
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [X] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [X] `integrations/databricks`: Databricks integrations

**Comment by B-Step62** [comment]
@Peilun-Li Thank you for reporting the issue!

This is a thread safety bug of the MLflow tracer. I've filed a fix https://github.com/mlflow/mlflow/pull/12701 and validated all traces are completed properly. You can install the patch with the following command:
```
%pip install git+https://github.com/mlflow/mlflow.git@refs/pull/12701/head -qU
```
