### ISSUE TITLE
[FR] - MLFlow Tracking Server Default Columns in UI

### ISSUE THREAD

**Issue by vinceli1004** [mlflow/mlflow#12764]
### Willingness to contribute

No. I cannot contribute this feature at this time.

### Proposal Summary

We would like a way to set a different default for the columns shown when viewing an experiment in the MLFlow Tracking UI. The table view defaults to dataset, duration, source, and model - but there's a few tags/attributes that would be useful for our team to display by default without needing to manually choose them each time we open a new experiment. If possible, I'd like anyone navigating to our UI to have these by default across any experiment(s).

### Motivation

> #### What is the use case for this feature?
Giving users customization over the default columns shown when viewing tables of runs in mlflow experiments.

> #### Why is this use case valuable to support for MLflow users in general?
Depending on the organization and how users populate tags, it's possible that there are more useful columns than dataset, duration, source, and models to show on a page by default - for example user.

> #### Why is this use case valuable to support for your project(s) or organization?
My organization has an internal tagging system which we would like to display by default to quickly understand which runs in an experiment are relevant. Additionally, it would also be very helpful for us to have user be a default column as much of the value we get out of MLFlow is from tracking who ran what.

> #### Why is it currently difficult to achieve this use case?
Each time we navigate to a new experiment or combination of experiments, our selected attributes/tags that make up the columns are deselected. Furthermore, even within an experiment, this behavior is only shared within the same browser, so other users viewing an experiment would have to manually select these columns. Given we almost always are looking for the same few tags mentioned above, it would help immensely if this was something we could configure at the server level.

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by CamilleLHuillier** [comment]
I agree supporting configurable views in MLflow Tracking portal could be a very nice enhancement from an efficiency and a collaboration perspectives.

In my organization we rely on MLflow for experiment tracking and automated training tracking. Configuring the view (column selection, row sorting / filtering/ grouping) is often key to provide the right perspective when analyzing the experiment data and taking decisions. Right now this configuration operation needs to be done by any user and often it's hard for someone to do it without in-depth knowledge of the experiment. It quite hard to analyze and understand autonomously experiments from other teams.

Experiments can be quite heterogeneous and get quite complex, for instance because of:

- different run structures, sometimes using nested runs or grouped runs when training multiple models, performing hyperparameter search, etc.
- many parameters, metrics, artifacts
- etc.

It would be great to be able to save such tailored views and having them available under a self-explanatory name for anyone browsing the UI. Jira offers such a configurable view feature illustrated in https://support.atlassian.com/jira-software-cloud/docs/preconfigured-views-in-advanced-roadmaps/.

If you think that this feature could make sense I would be happy to propose a design.

**Comment by A-Telfer** [comment]
I would also appreciate this feature. Stumbled on this issue while searching if there was a better way to set default columns. Sometimes the mlflow ui needs to be restarted, or maybe I'm switching through experiments which resets the columns.

It would be nice if it could be stored globally, or in the experiment meta data.

**Comment by B-Step62** [comment]
@CamilleLHuillier The configurable view feature sounds fruitful🙂 However, it seems beyond the scope of this feature request. To keep the scope clear, would you mind creating a new feature request with that proposal?

**Comment by davy-blavette** [comment]
I've created a plugin, I'm looking for a feature like: 

`client.set_columns(run_id, ‘total/Anomaly,total/F1,epochs,model_backbone,model_pretrained,model_type’), `

I've created a plugin too so I can use the source code if I need to, any ideas for code?

**Comment by nikospap0** [comment]
This feature feels like a must-have in my mind. How come not so many people have requested this before? Do you not track your experiments with custom metrics? Does everyone organize their view each time they open up mlflow? :(

**Comment by LukasDb** [comment]
I wrote a browser plugin for firefox to import/export the chart view configuration. This at least saves me from clicking all the buttons again on a new experiment, or on a different machine.

https://github.com/LukasDb/mlflow-viewport

**Comment by nikospap0** [comment]
> I wrote a browser plugin for firefox to import/export the chart view configuration. This at least saves me from clicking all the buttons again on a new experiment, or on a different machine.
> 
> https://github.com/LukasDb/mlflow-viewport

Haven't tried it but major kudos to you!

**Comment by iaverypadberg** [comment]
Another request for configurable columns or saved views! That plugin is a cool idea but I don't need it badly enough to set it up.

**Comment by ebnertom** [comment]
I would also appreciate that!

**Comment by akashjainn** [comment]
I looked into implementing this and hit a design question that needs a maintainer call, so leaving notes here for whoever picks it up.

**Where the current defaults live** — `mlflow/server/js/src/experiment-tracking/components/experiment-page/models/ExperimentPageUIState.tsx`:

```ts
export const getDefaultSelectedColumns = () => [
  makeCanonicalSortKey(COLUMN_TYPES.ATTRIBUTES, ATTRIBUTE_COLUMN_LABELS.SOURCE),
  makeCanonicalSortKey(COLUMN_TYPES.ATTRIBUTES, ATTRIBUTE_COLUMN_LABELS.MODELS),
  makeCanonicalSortKey(COLUMN_TYPES.ATTRIBUTES, ATTRIBUTE_COLUMN_LABELS.DATASET),
];
```

That is the hardcoded set this issue is asking to make configurable.

**The complication:** `getDefaultSelectedColumns()` is synchronous, and it feeds `createExperimentPageUIState()`, which is consumed from several non-hook call sites (`persistSearchFacets.ts`, `ExperimentGetShareLinkModal.tsx`, `useInitializeUIState.ts`, `ExperimentViewRuns.tsx`). So server-provided defaults cannot simply be awaited at the point of use — the value has to be available synchronously by the time those run.

**Three ways to square that**, with fairly different blast radius:

1. **Config endpoint + module-level cache.** Serve the defaults from a small endpoint (the MLflow Assistant already does this pattern — `ajax-api/3.0/mlflow/assistant/config` backed by `mlflow/server/assistant/api.py`), fetch once at app boot, and have `getDefaultSelectedColumns()` read the cached value. Keeps all existing call sites synchronous. Supports runtime server config, which is what the original request asks for.
2. **Build-time environment variable.** Much smaller change, but the defaults are then baked into the bundle rather than configurable on a running tracking server, which I think misses the point of the request.
3. **Per-experiment tag/metadata.** Would give per-experiment control, but the request is explicitly for a setting that applies "across any experiment(s)" at the server level.

Option 1 looks like the right fit and follows an existing in-repo pattern, but it does add a server config surface, so it seems worth a maintainer's opinion before someone writes it.

@B-Step62 — you scoped saved views out of this one earlier; is a server-level config endpoint for the default column set the direction you'd want here, or would you rather this stay client-side?

**Comment by B-Step62** [comment]
Hi everyone — shareable saved views shipped in [MLflow 3.15.0](https://mlflow.org/releases/3.15.0/#3-shareable-table-views) 🎉

From the Runs page, select **Views → Save as new view**. A named view captures the selected columns, column order and widths, filters, and sorting configuration. Saved views can also be shared by URL, giving collaborators a consistent starting view.

![Creating and switching between saved views](https://mlflow.org/img/releases/3.15.0/3-15-new-switching-saved-view.gif)

While this does not add a server-wide default column setting, it addresses the underlying workflow of preserving and sharing a preferred table configuration. If centrally enforced defaults across all experiments are still needed, please open a focused follow-up request.

Please upgrade to MLflow 3.15.0 or later and try it out!

Thanks to everyone who commented or reacted with 👍 for helping us prioritize this:

@camlhui @A-Telfer @davy-blavette @nikospap0 @LukasDb @iaverypadberg @ebnertom @akashjainn @zx220325 @HamdiYakoota @stijnvermeeren-swisstopo @joann-alvarez @Saya47 @laurelisdunn @stn @RomanN27 @mayorblock @cecilianakamura @daviddwlee84 @andreped @kklein @JulianJvn @stefan-olli

Closing this as completed.
