### ISSUE TITLE
[FR] Tracing for Langchain's Runnable.astream_events() and Langgraph's CompiledGraph.invoke()

### ISSUE THREAD

**Issue by lragnarsson** [mlflow/mlflow#12798]
### Willingness to contribute

Yes. I would be willing to contribute this feature with guidance from the MLflow community.

### Proposal Summary

At the moment, using MLServer autologging for Langchain does not appear to support Runnable.astream_events(), nor the LangGraph CompiledGraph.invoke() calls. I can see sub-chains being traced such as contextual compression in retrievers, or each individual node in a LangGraph if those nodes are simple chain-invocations for example.

But since the top level traces are not being logged at the moment it is not very useful.

I am guessing this is about playing catch-up with a rapidly evolving Langchain API, and I am willing to help out and contribute if someone could point me in the right direction. I found this : [line of code](https://github.com/mlflow/mlflow/blob/49403432b48942a612f9e801003239855f578309/mlflow/langchain/_langchain_autolog.py#L112) Where the callbacks are added, but where e.g. astream_events is not handled.

As for why the CompiledGraph.invoke() does not get picked up I don't know, as it does inherit the langchain Runnable class. 

### Motivation

> #### What is the use case for this feature?
Make MLFlow LLM Tracing work for newest Langchain APIs

> #### Why is this use case valuable to support for MLflow users in general?
Langchain is one of the most widely used libraries for LLM applications, and being able to trace them is very useful.

> #### Why is this use case valuable to support for your project(s) or organization?
This feature would enable us to switch over to MLFlow for agent tracing and evaluation.

> #### Why is it currently difficult to achieve this use case?
Newest LangChain features appear to be unsupported at the moment.

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [X] `integrations/databricks`: Databricks integrations

**Comment by serena-ruan** [comment]
@lragnarsson Thanks for raising this. To patch CompiledGraph you can use `mlflow.langchain.autolog(extra_model_classes=[CompiledGraph])` to add it to the patching list, as currently we only atuo-patch classes in langchain and langchain_community. 

For `astream_events` support, please feel free to raise a PR!
