### ISSUE TITLE
[BUG] Regression connecting to MLFlow tracking server on other Databricks workspace

### ISSUE THREAD

**Issue by nathan-az** [mlflow/mlflow#12837]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Databricks

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 2.15.0

### System information

Databricks DBR 15.3 ML - appears to be present across runtimes though.

### Describe the problem

Connecting to an MLFlow tracking server from one Databricks workspace into another no longer works correctly in the [method described in the documentation](https://docs.databricks.com/en/machine-learning/manage-model-lifecycle/multiple-workspaces.html#specify-a-remote-registry). 

`mlflow.doctor()` shows a change in the tracking URI, but the actual experiments accessible do not change, and instead still only reflex the current workspace.

### Tracking information

```
System information: Linux #70~20.04.1-Ubuntu SMP Fri Jun 14 15:42:13 UTC 2024
Python version: 3.11.0rc1
MLflow version: 2.15.0
MLflow module location: /local_disk0/.ephemeral_nfs/envs/pythonEnv-739661f2-56fd-47a0-97e3-aa9a4da6b01a/lib/python3.11/site-packages/mlflow/__init__.py
Tracking URI: databricks://<scope>:<prefix>
Registry URI: databricks://<scope>:<prefix>
Databricks runtime version: 15.3
MLflow environment variables: 
  MLFLOW_CONDA_HOME: /databricks/conda
  MLFLOW_DEPLOYMENTS_TARGET: databricks
  MLFLOW_GATEWAY_URI: databricks
  MLFLOW_PYTHON_EXECUTABLE: /databricks/spark/scripts/mlflow_python.sh
  MLFLOW_TRACKING_URI: databricks
MLflow dependencies: 
  Flask: 2.2.5
  Jinja2: 3.1.2
  aiohttp: 3.8.5
  alembic: 1.13.2
  azure-storage-file-datalake: 12.14.0
  boto3: 1.34.39
  botocore: 1.34.39
  docker: 7.1.0
  google-cloud-storage: 2.10.0
  graphene: 3.3
  gunicorn: 20.1.0
  langchain: 0.1.20
  markdown: 3.4.1
  matplotlib: 3.7.2
  mlflow-skinny: 2.15.0
  numpy: 1.23.5
  pandas: 1.5.3
  pyarrow: 14.0.1
  pydantic: 1.10.6
  querystring-parser: 1.2.4
  scikit-learn: 1.3.0
  scipy: 1.11.1
  sqlalchemy: 1.4.39
  tiktoken: 0.5.2
  virtualenv: 20.24.2
```

### Code to reproduce issue

```py
import mlflow
import os


# insert scope and prefix from other workspace
scope = ...
prefix = ...
uri = f"databricks://{scope}/{prefix}"
mlflow.set_tracking_uri(uri)
mlflow.set_registry_uri(uri)

# get number of experiments
num_exps = len(mlflow.search_experiments())

# will reflect the number of experiments in the current workspace's mlflow instance, not the other
print(f"Number of experiments in env: {num_exps}")
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [X] `integrations/databricks`: Databricks integrations

**Comment by serena-ruan** [comment]
@nathan-az Does it work if you use `MlflowClient(tracking_uri="...").search_experiments()`? Is there any warnings when you switch the tracking uri, just want to make sure you have the access

**Comment by nathan-az** [comment]
Hey @serena-ruan - same outcome. The client version runs without warning, but the experiments returned are from the current workspace, not the other. It works correctly after downgrading to 2.14.3.

**Comment by serena-ruan** [comment]
Thanks for the confirmation! I'll investigate on this.

**Comment by serena-ruan** [comment]
Seems https://github.com/mlflow/mlflow/pull/12313 is the root cause. @WeichenXu123 Could you take a look and fix it? We need a patch release for this bug

**Comment by WeichenXu123** [comment]
@nathan-az I filed a fix, could you test it ?

You can test it by `pip install git+https://github.com/mlflow/mlflow.git@refs/pull/12861/merge`

**Comment by nathan-az** [comment]
Confirmed working on `1c20e8ae49fa2fcd5383b9301d0ac364d907c35e`, thanks @WeichenXu123 !
