### ISSUE TITLE
[BUG] Can not do tracing when use evaluation with openai model

### ISSUE THREAD

**Issue by Impvest** [mlflow/mlflow#12952]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Other

### Willingness to contribute

I'm willing to fix this.

### MLflow version

- Client: 2.15.0
- Tracking server: 2.15.0

### System information

- **OS Platform and Distribution: Ubuntu
- **Python version**: 3.8
- **yarn version, if running the dev UI**:

### Describe the problem

With this code . I cant see any traces if I run this code with openai model. But if I change to langchain it worked.

`with mlflow.start_run(
        run_name=RUN_NAME,
        tags={
            "mlflow.source.git.commit": RUN_VERSION,
        }
    ) as started_run:
        prompt_tokens = count_tokens([PROMPT])
        email_tokens = count_tokens(dataset["email"])
        avg_tokens = count_tokens([PROMPT])

        model_info = mlflow.openai.log_model(
            model = MODEL_NAME,
            task= openai.chat.completions,
            artifact_path="model",
            messages = create_message(PROMPT),
            signature = SIGNATURE
        )

        try:
            results = mlflow.evaluate(
                    predict(model_info.model_uri),
                    dataset,
                    targets=GROUND_TRUTH_COLUMN,
                    evaluators="default",
                    model_type="classifier",
                    validation_thresholds = {
                            "precision_score": MetricThreshold(
                                threshold=PRECISION_THRESHOLD,
                                greater_is_better=True,
                            ),
                        },
                    extra_metrics=[ token_count(), latency(), precision_metric, coverage_metric]
            )

            params ={
            "temperature": TEMPERATURE,
            "top_p": TOP_P}

            mlflow.log_metrics(results.metrics)
            mlflow.log_metrics({"avg_request_tokens": avg_tokens})
            mlflow.log_metrics({"max_request_tokens":int(2*avg_tokens)})
            mlflow.log_params(params)

            log_only_mistakes_table(started_run.info.run_id)
            print_links(started_run, model_info)
        except Exception as e:
            print("Run failed, see the logs for details")
            print(e)`

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```
REPLACE_ME
```

### Stack trace

```
REPLACE_ME
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [X] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by B-Step62** [comment]
@Impvest Thank you for raising this issue. Supporting OpenAI tracing for evaluation makes sense, we will work on the addition soon!

**Comment by Impvest** [comment]
After looking on code I think the problem is related to openai flavor. Can we change it to use openai client instead of directly call api? Anyway I tried to change it in my local and it works.

**Comment by Impvest** [comment]
Inside api_request_parallel_processor.py

**Comment by heyitsaamir** [comment]
A workaround that worked for me was setting `mlflow.utils.autologging_utils._AUTOLOGGING_GLOBALLY_DISABLED = False` inside your evaluation function. Bit hacky, but it gets me past the issue for now.
