### ISSUE TITLE
[FR]Ability to choose colour of the runs in UI

### ISSUE THREAD

**Issue by mbenoit29** [mlflow/mlflow#12992]
### Willingness to contribute

Yes. I would be willing to contribute this feature with guidance from the MLflow community.

### Proposal Summary

Proposal would be to allow users to choose the colour they want to assign to the run, ideally both programmatically and in the UI.

### Motivation

> #### What is the use case for this feature?
Currently the colour of runs are chosen automatically by MLFlow and it can easily happen that 2 runs have the same or very similar colours.
This is quite problematic when looking at metrics in the chart because it makes it almost impossible to know which line is from which run.

> #### Why is this use case valuable to support for MLflow users in general?
Make the MLFlow chart more user-friendly.

> #### Why is this use case valuable to support for your project(s) or organization?
Possibility to present charts coming from MLflow to colleagues and ease of comparing run performances.

> #### Why is it currently difficult to achieve this use case?
Color coding is random and there are no way to affect it for the user (or at least not documented).

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [X] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by B-Step62** [comment]
@mbenoit29 Thank you for bringing this issue to our attention. The proposal makes sense to me, WDYT @daniellok-db?

Also tagging @chenmoneygithub as I heard there was some change in color selection recently, which might not be imported to OSS UI. Will it solve or mitigate this issue?

**Comment by daniellok-db** [comment]
Yes there was a change recently that assigns the colors via rotating 16-color palette rather than randomly, so this should mitigate the issue the next time we update the UI 🙂

**Comment by daniellok-db** [comment]
oh wait, it looks like this is already available by clicking the run color:

https://github.com/user-attachments/assets/25fdea90-2218-4bb3-a3d8-92ad4a3a1f34

cc @mbenoit29

**Comment by mbenoit29** [comment]
That would be already very nice! @daniellok-db do you happen to know in which version this was released?
Because we are running 2.15.1 and nothing happens for me when I click the run color

**Comment by daniellok-db** [comment]
Looks like it was released in 2.13.0! 

https://github.com/user-attachments/assets/e7d06058-cd6a-483e-b098-4cf8ec0d7e36

What browser are you using? Maybe that makes a difference. You could also try to do a hard refresh (shift + cmd + r on mac) in case maybe the browser is caching old assets.

**Comment by mbenoit29** [comment]
Ah indeed, working in chrome but not safari!
Maybe one last question: how much effort would it be to also be able to set the color when starting the run programatically (especially in python in my case)?

**Comment by daniellok-db** [comment]
Hi @mbenoit29, sorry for the late reply! Unfortunately I believe the run color is set by the UI, and so it isn't possible to set it from the python client.

**Comment by mbenoit29** [comment]
Great thanks a lot Daniel, I'm closing the issue then!
