### ISSUE TITLE
[FR] Add a `py.typed` to the mlflow package

### ISSUE THREAD

**Issue by tanguylefloch-veesion** [mlflow/mlflow#13137]
### Willingness to contribute

Yes. I can contribute this feature independently.

### Proposal Summary

Currently when adding `mlflow` to an existing codebase using `mypy` or other type checkers following [PEP-561](https://peps.python.org/pep-0561/) it is impossible to leverage `mlflow`'s internal type annotations.

Mypy errors with:
```
veesion_data_core/lib/training/get_training_stats.py:8: error: Skipping analyzing "mlflow": module is installed, but missing library stubs or py.typed marker  [import-untyped]
```
I couldn't seem to find a serious separate stub package so I assume it doesn't exist. The only related content seems to be https://github.com/mlflow/mlflow/issues/1756 which indicates that the `mlflow` team has been using type annotations, it would be nice that others can benefit from it.

To do so, we simply need to add an empty `py.typed` file to the root of the package to indicate that internal type annotations can be used.

### Motivation

> #### What is the use case for this feature?
Leveraging MLFlow's type annotation in projects using it with a type checker.

> #### Why is this use case valuable to support for MLflow users in general?
It reinforces and help developing applications built on top or using mlflow.

> #### Why is this use case valuable to support for your project(s) or organization?
I extensively use mlflow in company applications that are fully type-annotated and this would help
me detect bugs and work in a more efficient manner.

> #### Why is it currently difficult to achieve this use case?
It's impossible without that file or extensive workarounds.

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [X] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [X] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [X] `area/projects`: MLproject format, project running backends
- [X] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations
