### ISSUE TITLE
[BUG] mlflow-llamaindex-qdrant issue with the latest mlflow 12.18.0

### ISSUE THREAD

**Issue by pavanjava** [mlflow/mlflow#13930]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### MLflow version

- Client: 12.18.0
- Tracking server: 12.8.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: OSX 15.1.1
- **Python version**: 3.12.4
- **yarn version, if running the dev UI**: NA

### Describe the problem

When I run the mlflow tracking I get the local mlruns folder and when I load the model back it says below error
`mlflow.exceptions.MissingConfigException: Yaml file '/Users/pavanmantha/Pavans/PracticeExamples/DataScience_Practice/mlflow-tutorials/mlflow-llamaindex-playground/mlruns/1/0c1d0d78add74008b3d21da00f12a650/meta.yaml' does not exist.
`

### Tracking information

```
MLflow dependencies: 
  Flask: 3.0.3
  Jinja2: 3.1.4
  aiohttp: 3.10.10
  alembic: 1.13.3
  docker: 7.1.0
  fastapi: 0.115.5
  graphene: 3.4.1
  gunicorn: 23.0.0
  markdown: 3.7
  matplotlib: 3.9.2
  mlflow-skinny: 2.18.0
  numpy: 1.26.4
  pandas: 2.2.3
  pyarrow: 17.0.0
  pydantic: 2.9.2
  scikit-learn: 1.5.2
  scipy: 1.14.1
  sqlalchemy: 2.0.36
  tiktoken: 0.8.0
  uvicorn: 0.32.1
```

```
MLflow version: 2.18.0
Tracking URI: http://127.0.0.1:3000
Artifact URI: /Users/pavanmantha/Pavans/PracticeExamples/DataScience_Practice/mlflow-tutorials/mlflow-llamaindex-playground/mlruns/1/3ab0769e066a460e95649da601d3d552/artifacts
```

### Code to reproduce issue

model_indexing.py
```
from llama_index.core import Settings, SimpleDirectoryReader, StorageContext, VectorStoreIndex
from llama_index.embeddings.ollama import OllamaEmbedding
from llama_index.llms.ollama import Ollama
from llama_index.vector_stores.qdrant import QdrantVectorStore
from dotenv import load_dotenv, find_dotenv
import qdrant_client
import mlflow
import os

load_dotenv(find_dotenv())

Settings.llm = Ollama(model=os.environ.get('LANGUAGE_MODEL'), base_url=os.environ.get('OLLAMA_URL'))
Settings.embed_model = OllamaEmbedding(model_name=os.environ.get('EMBED_MODEL'), base_url=os.environ.get('OLLAMA_URL'))

documents = SimpleDirectoryReader(input_dir='data', required_exts=['.pdf']).load_data(show_progress=True)

client = qdrant_client.QdrantClient(url=os.environ.get('QDRANT_URL'), api_key=os.environ.get('QDRANT_API_KEY'))

vector_store = QdrantVectorStore(client=client, collection_name=os.environ.get('COLLECTION_NAME'))

storage_context = StorageContext.from_defaults(vector_store=vector_store)
index = VectorStoreIndex.from_documents(documents=documents, storage_context=storage_context, show_progress=True)

mlflow.models.set_model(index)

```

model_logging.py

```
import mlflow

mlflow.set_tracking_uri('http://127.0.0.1:3000')
mlflow.set_experiment(experiment_name='llamaindex-qdrant-rag-89')

mlflow.llama_index.autolog()

with mlflow.start_run():
    model_info = mlflow.llama_index.log_model(
        "model_indexing.py",
        artifact_path="index",
        engine_type="chat",  # chat, query & retrieve
    )

    print(f"model_uri = {model_info.model_uri}")

    print("MLflow version:", mlflow.__version__)
    print("Tracking URI:", mlflow.get_tracking_uri())
    print("Artifact URI:", mlflow.get_artifact_uri())

```

model_loading.py

```
import mlflow
from llama_index.core import VectorStoreIndex

model_uri: str = 'runs:/0c1d0d78add74008b3d21da00f12a650/index'
index: VectorStoreIndex = mlflow.llama_index.load_model(model_uri)

print(index)

response = index.as_query_engine().query("What are challenges of mlops?")

print(response)

```

### Stack trace

```
/Users/pavanmantha/Pavans/PracticeExamples/DataScience_Practice/mlflow-tutorials/mlflow-llamaindex-playground/venv/bin/python /Users/pavanmantha/Pavans/PracticeExamples/DataScience_Practice/mlflow-tutorials/mlflow-llamaindex-playground/model_loading.py 
Traceback (most recent call last):
  File "/Users/pavanmantha/Pavans/PracticeExamples/DataScience_Practice/mlflow-tutorials/mlflow-llamaindex-playground/model_loading.py", line 5, in <module>
    index: VectorStoreIndex = mlflow.llama_index.load_model(model_uri)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavanmantha/Pavans/PracticeExamples/DataScience_Practice/mlflow-tutorials/mlflow-llamaindex-playground/venv/lib/python3.12/site-packages/mlflow/tracing/provider.py", line 268, in wrapper
    is_func_called, result = True, f(*args, **kwargs)
                                   ^^^^^^^^^^^^^^^^^^
  File "/Users/pavanmantha/Pavans/PracticeExamples/DataScience_Practice/mlflow-tutorials/mlflow-llamaindex-playground/venv/lib/python3.12/site-packages/mlflow/llama_index/__init__.py", line 533, in load_model
    local_model_path = _download_artifact_from_uri(artifact_uri=model_uri, output_path=dst_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavanmantha/Pavans/PracticeExamples/DataScience_Practice/mlflow-tutorials/mlflow-llamaindex-playground/venv/lib/python3.12/site-packages/mlflow/tracking/artifact_utils.py", line 108, in _download_artifact_from_uri
    repo = get_artifact_repository(artifact_uri=root_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavanmantha/Pavans/PracticeExamples/DataScience_Practice/mlflow-tutorials/mlflow-llamaindex-playground/venv/lib/python3.12/site-packages/mlflow/store/artifact/artifact_repository_registry.py", line 131, in get_artifact_repository
    return _artifact_repository_registry.get_artifact_repository(artifact_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavanmantha/Pavans/PracticeExamples/DataScience_Practice/mlflow-tutorials/mlflow-llamaindex-playground/venv/lib/python3.12/site-packages/mlflow/store/artifact/artifact_repository_registry.py", line 76, in get_artifact_repository
    return repository(artifact_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavanmantha/Pavans/PracticeExamples/DataScience_Practice/mlflow-tutorials/mlflow-llamaindex-playground/venv/lib/python3.12/site-packages/mlflow/store/artifact/runs_artifact_repo.py", line 26, in __init__
    uri = RunsArtifactRepository.get_underlying_uri(artifact_uri)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavanmantha/Pavans/PracticeExamples/DataScience_Practice/mlflow-tutorials/mlflow-llamaindex-playground/venv/lib/python3.12/site-packages/mlflow/store/artifact/runs_artifact_repo.py", line 39, in get_underlying_uri
    uri = get_artifact_uri(run_id, artifact_path, tracking_uri)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavanmantha/Pavans/PracticeExamples/DataScience_Practice/mlflow-tutorials/mlflow-llamaindex-playground/venv/lib/python3.12/site-packages/mlflow/tracking/artifact_utils.py", line 52, in get_artifact_uri
    run = store.get_run(run_id)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavanmantha/Pavans/PracticeExamples/DataScience_Practice/mlflow-tutorials/mlflow-llamaindex-playground/venv/lib/python3.12/site-packages/mlflow/store/tracking/file_store.py", line 694, in get_run
    run_info = self._get_run_info(run_id)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavanmantha/Pavans/PracticeExamples/DataScience_Practice/mlflow-tutorials/mlflow-llamaindex-playground/venv/lib/python3.12/site-packages/mlflow/store/tracking/file_store.py", line 722, in _get_run_info
    run_info = self._get_run_info_from_dir(run_dir)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavanmantha/Pavans/PracticeExamples/DataScience_Practice/mlflow-tutorials/mlflow-llamaindex-playground/venv/lib/python3.12/site-packages/mlflow/store/tracking/file_store.py", line 731, in _get_run_info_from_dir
    meta = FileStore._read_yaml(run_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavanmantha/Pavans/PracticeExamples/DataScience_Practice/mlflow-tutorials/mlflow-llamaindex-playground/venv/lib/python3.12/site-packages/mlflow/store/tracking/file_store.py", line 1368, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavanmantha/Pavans/PracticeExamples/DataScience_Practice/mlflow-tutorials/mlflow-llamaindex-playground/venv/lib/python3.12/site-packages/mlflow/store/tracking/file_store.py", line 1361, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavanmantha/Pavans/PracticeExamples/DataScience_Practice/mlflow-tutorials/mlflow-llamaindex-playground/venv/lib/python3.12/site-packages/mlflow/utils/file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '/Users/pavanmantha/Pavans/PracticeExamples/DataScience_Practice/mlflow-tutorials/mlflow-llamaindex-playground/mlruns/1/0c1d0d78add74008b3d21da00f12a650/meta.yaml' does not exist.

Process finished with exit code 1

```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [X] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [X] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [X] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by pavanjava** [comment]
my requirements.txt is as below
```
mlflow==2.18.0
psycopg2-binary==2.9.10
psycopg2==2.9.10
llama-index==0.11.20
llama-index-llms-ollama==0.3.4
llama-index-embeddings-ollama==0.3.1
llama-index-vector-stores-qdrant==0.3.2
qdrant-client==1.12.0
python-dotenv==1.0.1
fastapi
uvicorn
confluent-kafka
```

**Comment by B-Step62** [comment]
@pavanjava This doesn't seem to be an issue of LlamaIndex flavor.

You are setting tracking URI here in `model_logging.py`

```
mlflow.set_tracking_uri('http://127.0.0.1:3000')
```

However, you don't set it in `model_loading.py`. Could you set it and try again? Also you can set `MLFLOW_TRACKING_URI` env variable in the environment so you don't need to set in each script.

**Comment by pavanjava** [comment]
Thanks @B-Step62 i am able to run it, but the wearied thing that I observed is when I run `model_indexing.py` my qdrant collection point count is 33 and when i run `model_logging.py` my qdrant collection point count is 66 and when i run the `model_loading.py` the qdrant collection point count is 99. Now my question is why the data is getting indexed for every run. To my knowledge it should only happen only once.

**Comment by pavanjava** [comment]
I fixed this issue; we can close this bug now.
