### ISSUE TITLE
[FR] Add PDF files to Preview

### ISSUE THREAD

**Issue by RMeli** [mlflow/mlflow#2790]
## Willingness to contribute
The MLflow Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature (either as an MLflow Plugin or an enhancement to the MLflow code base)?

- [ ] Yes. I can contribute this feature independently.
- [ ] Yes. I would be willing to contribute this feature with guidance from the MLflow community.
- [x] No. I cannot contribute this feature at this time.

## Proposal Summary

Graphs are often exported as PDF files. It would be great to support PDF files as supported format for file preview when they are logged as artifacts.

## Motivation
- What is the use case for this feature? 
  - Look at PDF images directly in the UI.
- Why is this use case valuable to support for MLflow users in general? 
  - It is helpful to look at PDF images directly in the UI as it is for other file formats.
- Why is this use case valuable to support for your project(s) or organization?
- Why is it currently difficult to achieve this use case? (please be as specific as possible about why related MLflow features and components are insufficient)
  - PDF are not supported by the UI.

## Which MLflow component(s) does this feature affect?

- [x] UI
- [ ] Command Line Interface
- [ ] API
- [ ] Examples
- [ ] Docs
- [ ] Tracking
- [ ] Projects
- [x] Artifacts
- [ ] Models
- [ ] Model Registry
- [ ] Scoring
- [ ] R
- [ ] Java
- [ ] Python

## Details

I don't know how difficult it would be to support PDF images, but it would be extremely helpful.

**Comment by dmatrix** [comment]
Thank you for filling this feature request. We hope that a community member can take this task.
Short of it, you can save the artifact, download it, and view it in a pdf reader.

**Comment by ankmathur96** [comment]
@pogil a PR for this is up here: #2859

**Comment by ankitmathur-db** [comment]
@RMeli this has now been merged, so if you'd like it immediately, you can upgrade to master. Otherwise, it should be in the next release!

**Comment by RMeli** [comment]
Amazing! Thank you very much for this great feature @ankitmathur-db !
