### ISSUE TITLE
[BUG] Run name not set when using start_run inside a MLproject execution

### ISSUE THREAD

**Issue by cthacker** [mlflow/mlflow#2804]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)
for additional information about bug reports. For help with debugging your code, please refer to [Stack Overflow](https://stackoverflow.com/questions/tagged/mlflow).

**Please fill in this bug report template to ensure a timely and thorough response.**

### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix
for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [x] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: Yes, but this issue can be recreated from stock example by running via cmd line and trying to set run_name in script.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**: 1.8.0
- **Python version**: 3.8
- **npm version, if running the dev UI**:
- **Exact command to reproduce**:

- modify any mlflow example  as follow:
```
with mlflow.start_run("run_name") as run:
```
- then run via command line `mlflow run .`

### Describe the problem
The run_name will not be added since the run has already been kicked off from the command line. Additionally, there is no way to set run names via command line as the command never sets an `MLFLOW_RUN_NAME` tag

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [x] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for
Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [x] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

This is related to https://github.com/mlflow/mlflow/issues/2735, but unlike that one, run_name cannot even be passed in.

**Comment by dbczumar** [comment]
Hi @cthacker! This seems like a good feature to add. We should be able to thread the run name through to the `mlflow.projects._run()` method and set the `MLFLOW_RUN_NAME` tag by adding additional calls to `tracking.MlflowClient.set_tag()` in the following locations:

- https://github.com/mlflow/mlflow/blob/a9af2182505d4047c2d065e3f23c79f7ca6cf879/mlflow/projects/__init__.py#L99-L100

- https://github.com/mlflow/mlflow/blob/a9af2182505d4047c2d065e3f23c79f7ca6cf879/mlflow/projects/__init__.py#L114-L115

- https://github.com/mlflow/mlflow/blob/a9af2182505d4047c2d065e3f23c79f7ca6cf879/mlflow/projects/__init__.py#L123

- https://github.com/mlflow/mlflow/blob/a9af2182505d4047c2d065e3f23c79f7ca6cf879/mlflow/projects/__init__.py#L164-L165

Please let me know if you have any questions about accomplishing this!

**Comment by dbczumar** [comment]
@cthacker Just checking in! Is this still something you'd be willing to contribute towards? Let me know if you have any questions about the proposed strategy.

**Comment by AgrawalAmey** [comment]
@dbczumar I am creating a PR for this one.

**Comment by roboticsbrian** [comment]
As a workaround, instead of 
```with mlflow.start_run("run_name") as run:```
 use the [system tag](https://mlflow.org/docs/latest/tracking.html#system-tags) directly:
```mlflow.set_tag("mlflow.runName", "run_name")```

**Comment by jkthompson** [comment]
Alternative workaround if you are outside the scope of the target run:
```python
mlflow.tracking.MlflowClient().set_tag(run_id, "mlflow.runName", "run_name")
```

**Comment by dbczumar** [comment]
We have merged https://github.com/mlflow/mlflow/pull/5187 to address this issue. Thank you for using MLflow!
