### ISSUE TITLE
[BUG] Cannot import data ERROR 1406 (22001): Data too long for column 'value' at row 1

### ISSUE THREAD

**Issue by weldpua2008** [mlflow/mlflow#2814]
### Willingness to contribute
- [X ] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No 
- **OS Platform and Distribution**: Debian GNU/Linux 10 (buster)
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**: mlflow, version 1.0.0
- **Python version**:  Python 3.6.10
- **Exact command to reproduce**:
```sql
MySQL [db]> INSERT INTO `params` (`key`, `value`, `run_uuid`) VALUES ( 'preprocessor', 'HtmlStrip >> EmailTitleCleaner >> SuperImportantTokenizer >> DateTokenizer >> MonthTokenizer >> TimeTokenizer >> EmailTokenizer >> MoneyTokenizer >> YARNTokenizer >> SecureUrlTokenizer >> SomeDnsTokenizer >> UrlTokenizer >> TicketIdTokenizer >> IpTokenizer >> PhoneTokenizer >> NumberTokenizer >> RegexTokenizer >> RegexTokenizer >> SurplusSpacesCleaner', 'd4459fec14dd4e5a8655e69cefe9ae74' );
ERROR 1406 (22001): Data too long for column 'value' at row 1
```
### Describe the problem
I am using the following code https://gist.github.com/bnekolny/8ec96faa0d57913eea6bb7848c06b912 to import from file-based backend store to mysql database 

I found that default schema creates all string fields as [varchar(250) (latest_schema.sql#L104)](https://github.com/mlflow/mlflow/blob/master/tests/resources/db/latest_schema.sql#L104) while **YAML has no such restriction, or I am wrong?**
Also, I can't find any mentioning that there is such restriction (250 max characters) at https://www.mlflow.org/docs/latest/tracking.html#concepts

I can perform the schema change:
```sql 
ALTER TABLE `params` MODIFY value VARCHAR(512) NOT NULL;
```
But what will be the side effect?

### Code to reproduce issue
value field has `varchar(250)`

```sql
MySQL [db]> SHOW CREATE TABLE params\G
*************************** 1. row ***************************
       Table: params
Create Table: CREATE TABLE `params` (
  `key` varchar(250) NOT NULL,
  `value` varchar(250) NOT NULL,
  `run_uuid` varchar(32) NOT NULL,
  PRIMARY KEY (`key`,`run_uuid`),
  KEY `run_uuid` (`run_uuid`),
  CONSTRAINT `params_ibfk_1` FOREIGN KEY (`run_uuid`) REFERENCES `runs` (`run_uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1
1 row in set (0.001 sec)
```

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [X] `area/artifacts`: Artifact stores and artifact logging
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for
Model Registry
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging
- [X] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry

**Comment by dbczumar** [comment]
@weldpua2008 Thank you for raising this issue. There is, indeed, a 250-character limit imposed on parameters and parameter values in the MLflow Service API. It is documented here: https://mlflow.org/docs/latest/rest-api.html#request-limits. Accordingly, all backend stores (SQLAlchemy, FileStore, custom implementations, etc) are expected to conform to this limit. 

It looks like our File Store does not currently enforce this limit. I will discuss limit enforcement with other committers. In the meantime, if you want to modify your particular database configuration to support larger parameters, altering the tables as you've described seems like a reasonable approach.

Please let me know if this addresses your concerns!

**Comment by smurching** [comment]
Closing for now, thanks @dbczumar for clarifying!

**Comment by ahirner** [comment]
Hi, we are depending on parameter values longer than 250 chars. We can and did log them on 0.11 with `log_param` in contrast to `log_batch` and `sqlite` backend.  Are there any reasons to constrain single parameter values in PostgreSQL?
