### ISSUE TITLE
[FR] Support for built-in SageMaker algorithms

### ISSUE THREAD

**Issue by IdoNisso** [mlflow/mlflow#2815]
## Willingness to contribute
- [ ] Yes. I can contribute this feature independently.
- [x] Yes. I would be willing to contribute this feature with guidance from the MLflow community.
- [ ] No. I cannot contribute this feature at this time.

## Proposal Summary
Add native support for the built-in algorithms (training jobs) in SageMaker.

## Motivation
I work with an AWS partner and many of our ML projects use the built-in algorithms for quick iteration and creation of baseline models. On top of that, we use SageMaker to 

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [x] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for
Model Registry
- [x] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [x] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [x] `integrations/sagemaker`: SageMaker integrations

## Details
There might be several challenges to this, especially in serialization/deserialization for other platforms. The AWS formats are, on occasion, not very user friendly and internals are poorly documented.
However, my company is looking to use MLFlow with all of our ML clients and this feature would be a great selling point.
I'd love to contribute this feature on my free time with some guidance.

**Comment by sueann** [comment]
> Add native support for the built-in algorithms (training jobs) in SageMaker.

Would you mind describing your desired features in a bit more detail? What would be the ideal workflow for working with SageMaker built-in algorithms and MLflow? For example, would you want auto-logging of metrics and params for SageMaker built-in algorithms (like we have for keras and Spark MLlib)? Or just being able to log metrics for each (internal) iteration for training? Or being able to save the built-in SageMaker models into the MLflow artifact repository?

**Comment by IdoNisso** [comment]
Saving the model to the artifact repository for deployment via mlflow will be the most useful feature right now, but pretty much all of the above, eventually. Where do you think is the best place to start?

**Comment by sueann** [comment]
I think to accomplish that, you'll want to add support for logging the artifact. I'm not super familiar with the SageMaker workflow in detail, so it'd be useful to understand yours:
- Do your SageMaker models already get saved to S3 automatically? If so, is the location known? 
- Is there an explicit function call to save the models to a specific location? 
- Do you plan to deploy the model to SageMaker serving (batch or REST)? It seems like if you're doing this for built-in SageMaker algorithms, it'd be easier to just do that flow entirely in SageMaker. Deploying via mlflow currently requires building a docker image and making it available in ECR and creating the sagemaker endpoint. 
  - One thing I could imagine here would be to wrap the SageMaker deployment code underneath the mlflow deployment abstraction, if you really want to have a "consistent" API across ML frameworks, but I am not sure how much that will buy you.
