### ISSUE TITLE
[BUG] Unable to delete experiments with long names from UI

### ISSUE THREAD

**Issue by jlangballe-miovision** [mlflow/mlflow#2818]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md) for additional information about bug reports. For help with debugging your code, please refer to [Stack Overflow](https://stackoverflow.com/questions/tagged/mlflow).

**Please fill in this bug report template to ensure a timely and thorough response.**

### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [x] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS 10.15.4, Google Chrome
- **MLflow installed from (source or binary)**: Source
- **MLflow version (run ``mlflow --version``)**: 1.8.0
- **Python version**: 3.7
- **npm version, if running the dev UI**:
- **Exact command to reproduce**: mlflow ui

### Describe the problem
Experiments with long names in the sidebar are missing the delete icon. There is no way of deleting them from within the web interface.

<img width="566" alt="mlflow-experiment-list-ui" src="https://user-images.githubusercontent.com/64787634/81737548-41d0cf00-9466-11ea-99a6-7d3ca181ef41.png">

### Code to reproduce issue
Create an experiment with a long name (using the UI or through any means).

### Other info / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for
Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [x] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations

**Comment by harupy** [comment]
https://github.com/mlflow/mlflow/pull/2827 might fix this issue.

**Comment by smurching** [comment]
Looks like this was fixed in #2827 , thanks @harupy! Closing
