### ISSUE TITLE
[BUG]: parameter passing integers when expecting floats to mLflow run throws an Exception

### ISSUE THREAD

**Issue by malanb5** [mlflow/mlflow#2820]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md) for additional information about bug reports. For help with debugging your code, please refer to [Stack Overflow](https://stackoverflow.com/questions/tagged/mlflow).

**Please fill in this bug report template to ensure a timely and thorough response.**

### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [X] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **MLflow installed from (source or binary)**:
- **MLflow version (run ``mlflow --version``)**:
- **Python version**:
- **npm version, if running the dev UI**:
- **Exact command to reproduce**:

### Describe the problem
Describe the problem clearly here. Include descriptions of the expected behavior and the actual behavior.

The command:
```
mlflow run https://github.com/mlflow/mlflow-example.git -P alpha=5
```
Throws an exception

### Code to reproduce issue
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
```
mlflow run https://github.com/mlflow/mlflow-example.git -P alpha=5
```

### Other info / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

```
Traceback (most recent call last):
  File "train.py", line 60, in <module>
    mlflow.log_param("alpha", alpha)
  File "/opt/anaconda3/envs/mlflow-3eee9bd7a0713cf80a17bc0a4d659bc9c549efac/lib/python3.6/site-packages/mlflow/tracking/fluent.py", line 214, in log_param
    MlflowClient().log_param(run_id, key, value)
  File "/opt/anaconda3/envs/mlflow-3eee9bd7a0713cf80a17bc0a4d659bc9c549efac/lib/python3.6/site-packages/mlflow/tracking/client.py", line 206, in log_param
    self._tracking_client.log_param(run_id, key, value)
  File "/opt/anaconda3/envs/mlflow-3eee9bd7a0713cf80a17bc0a4d659bc9c549efac/lib/python3.6/site-packages/mlflow/tracking/_tracking_service/client.py", line 179, in log_param
    self.store.log_param(run_id, param)
  File "/opt/anaconda3/envs/mlflow-3eee9bd7a0713cf80a17bc0a4d659bc9c549efac/lib/python3.6/site-packages/mlflow/store/tracking/file_store.py", line 663, in log_param
    self._log_run_param(run_info, param)
  File "/opt/anaconda3/envs/mlflow-3eee9bd7a0713cf80a17bc0a4d659bc9c549efac/lib/python3.6/site-packages/mlflow/store/tracking/file_store.py", line 671, in _log_run_param
    run_id=run_info.run_id, new_value=writeable_param_value)
  File "/opt/anaconda3/envs/mlflow-3eee9bd7a0713cf80a17bc0a4d659bc9c549efac/lib/python3.6/site-packages/mlflow/store/tracking/file_store.py", line 690, in _validate_new_param_value
    databricks_pb2.INVALID_PARAMETER_VALUE)
mlflow.exceptions.MlflowException: Changing param values is not allowed. Param with key='alpha' was already logged with value='5' for run ID='f829e9d818904139968a4b39baadab5a'. Attempted logging new value '5.0'.
2020/05/12 20:39:38 ERROR mlflow.cli: === Run (ID 'f829e9d818904139968a4b39baadab5a') failed ===                     /4.1s
```

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for
Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations

**Comment by malanb5** [comment]
I was able to solve this by changing in parameter from a integer to a float by adding a 5.0
```
mlflow run https://github.com/mlflow/mlflow-example.git -P alpha=5.0
```
In fact any integer will trigger this exception.
Suggest that this is handled a little more gracefully, and automatic casting from an integer to a float internally.

**Comment by harupy** [comment]
@malanb5 Thanks for reporting. I investigated how this error occurs.

1. Run `mlflow run https://github.com/mlflow/mlflow-example.git -P alpha=5`.
2. A new run is created with given parameters **before running an entrypoint script** (which is ` train.py` in this git example). It should look like:

- <img width="205" alt="Screen Shot 2020-05-13 at 15 09 07" src="https://user-images.githubusercontent.com/17039389/81777429-bfaade00-952b-11ea-924e-76771b881aa1.png">

- <img width="113" alt="Screen Shot 2020-05-13 at 15 11 19" src="https://user-images.githubusercontent.com/17039389/81777542-08629700-952c-11ea-8d84-f5d294079bcb.png">


3. Then, `train.py` is executed.
4. `train.py` casts `alpha` to float (which is `5.0`) at line 44.
5. `mlflow.log_param("alpha", alpha)` at line 60 tries to overwrite `alpha` with `5.0`, but it fails because `alpha` is already logged with `5` when the new run is created.

**Comment by malanb5** [comment]
@harupy thanks for explaining this.  I see we have state in two different places that we need to coordinate.  Looks like we modify the logged value as we run the program noting the casting, which seems a little messy or we take away the casting and leave it to ElasticNet's constructor.  Taking a look at ElasticNet's Constructor it does specify a float, however will have to do a little digging to see the repercussions of using an integer instead.

[ElasticNetConstructor](https://github.com/scikit-learn/scikit-learn/blob/483cd3eaa3c636a57ebb0dc4765531183b274df0/sklearn/linear_model/_coordinate_descent.py#L555)

**Comment by malanb5** [comment]
Specifying types beforehand using a schema?  Dynamically modifying the log file at runtime seems a little messy. @harupy what do you think?
