### ISSUE TITLE
[FR] allow to filter runs by entry point

### ISSUE THREAD

**Issue by Drtuna** [mlflow/mlflow#2841]
Thank you for submitting a feature request. **Before proceeding, please review MLflow's [Issue Policy for feature requests](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md#feature-requests) and the [MLflow Contributing Guide](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst)**.

**Please fill in this feature request template to ensure a timely and thorough response.**

## Willingness to contribute
The MLflow Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature (either as an MLflow Plugin or an enhancement to the MLflow code base)?

- [ ] Yes. I can contribute this feature independently.
- [x] Yes. I would be willing to contribute this feature with guidance from the MLflow community.
- [ ] No. I cannot contribute this feature at this time.

## Proposal Summary
The filter string in ` mlflow.search_runs(filter_string="")` allows to filter for ['metric', 'parameter', 'tag', 'attribute'] however I would like to filter by entrypoint

## Motivation
I run a lot of different experiments all logged in the same tracking server. 
To generate meaningful dashboards I would like to filter by entrypoint. On the tracking ui I see also many other fields besides "status" and "artifact_uri" like "user' and "source" which would generate meaningful filters

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for
Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations

## Details

(this seems to be so obvious that I probably don't see how I can do this already today)

**Comment by sueann** [comment]
I believe you can filter by entry point using the tag `mlflow.project.entryPoint` (https://www.mlflow.org/docs/latest/tracking.html#system-tags). Does that work for you?

**Comment by Drtuna** [comment]
@sueann Thank you for your reply. `mlflow.project.entryPoint` looks perfect. However, the tag is not accessible from `mlflow.search_runs(filter_string="")`. I assume it would be `mlflow.search_runs(filter_string="project.entryPoint='ep'")`

**Comment by AveshCSingh** [comment]
I think you may want `mlflow.search_runs(filter_string="tags.project.entryPoint='ep'")`. I'm closing this issue, but feel free to re-open if this does not work.
