### ISSUE TITLE
[FR] - changing the default value of artifact_location to try reading it from the environment variable

### ISSUE THREAD

**Issue by sunny1401** [mlflow/mlflow#2861]
Thank you for submitting a feature request. **Before proceeding, please review MLflow's [Issue Policy for feature requests](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md#feature-requests) and the [MLflow Contributing Guide](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst)**.

**Please fill in this feature request template to ensure a timely and thorough response.**

## Willingness to contribute
The MLflow Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature (either as an MLflow Plugin or an enhancement to the MLflow code base)?

- [x] Yes. I can contribute this feature independently.
- [ ] Yes. I would be willing to contribute this feature with guidance from the MLflow community.
- [ ] No. I cannot contribute this feature at this time.

## Proposal Summary
Currently, the create_experiment method uses artifact_location=None as a default argument. It would be better if by default the system tried to read the value for MLFLOW_ARTIFACT_URI from the environment and uses none if that is not found.

basically just replace :
def create_experiment(name, artifact_location=os.environ['MLFLOW_ARTIFACT_URI']):

by this
def create_experiment(name, artifact_location=os.getenv('MLFLOW_ARTIFACT_URI', None)):

(In a few sentences, provide a clear, high-level description of the feature request)

## Motivation
- What is the use case for this feature? - Instead of having None as the default value for artifact URI, and then user having to remember where they want their data to be saved and pass it in - it would be easier if the value was read from the environment and None only be used if the corresponding var is not found.

- Why is this use case valuable to support for MLflow users in general?
We might have a default artifact uri - where all your final artifacts should be saved. In this case, we either set the environment variable or can pass it in. By default, the variable is None right now, in which case it doesn't read from the environment but creates an artifact folder in the current working direction/mlruns. However, many-a-times, especially if the artifact uri is an s3 bucket - its hard to remember the exact path. If the value is read by default, it will be one less thing to worry about the boilerplate - especially for new users. 

- Why is this use case valuable to support for your project(s) or organization? We have set out artifact_uri to be s3 bucket. It is hard to pass or remember to pass the artifact_uri every time an experiment is created, especially by users not familiar to mlflow

- Why is it currently difficult to achieve this use case? (please be as specific as possible about why related MLflow features and components are insufficient) - It is not difficult to fix it. Currently, we have patches for this. But would be more convenient if it was there in mlflow - since it would remove the need for unnecessary patches.

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for
Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations

## Details

(Use this section to include any additional information about the feature. If you have a proposal for how to implement this feature, please include it here. For implementation guidelines, please refer to the [Contributing Guide](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst#contribution-guidelines).)

**Comment by smurching** [comment]
@sunny1401 thanks for filing! Note that you can specify the default artifact URI to use for experiments created under an MLflow server via the `--default-artifact-root` argument to `mlflow server`, e.g. by running your server via a command like `mlflow server --default-artifact-root s3://your-s3-bucket`. Given that the default artifact URI can be specified in this manner, would you be able to clarify why your workflow involves passing an artifact URI explicitly to `create_experiment`? It seems you could avoid the need for this by setting the default artifact URI when you run the server.

**Comment by sunny1401** [comment]
Hi - Thanks for replying. Yes, I can do that. But in case you are working on multiple projects - each having its own artifact location - as different s3 buckets and different locations on s3 - this approach would not work. In my case, I  have an s3 bucket where data should generally go once the code is finalized. This is set in os.environ['MLFLOW_ARTIFACT_URI']. Our tracking URI is rds database

However, simultaneously we have experiments running - for these - if the user passes in the artifact_location - that is where the experiment will be created.  In case the user passes in the artifact_location for their experiment - artifacts will be stored there. These can be set to os.environ['MLFLOW_ARTIFACT_URI']

For simultaneous access/availability - we don't start the server before logging. 

Let me know if there is a better way to it - currently, we applying a patch to create_experiments setting the default value of artifact_path = os.environ['MLFLOW_ARTIFACT_URI']

**Comment by smurching** [comment]
@sunny1401 thanks for clarifying! Sorry to ask for more details, just want to make sure I understand the use case - what's the motivation behind having separate artifact locations across different projects (i.e. why not use a single S3 bucket & rely on per-experiment subdirectories within the S3 bucket)?

> For simultaneous access/availability - we don't start the server before logging.

Would you be able to detail what you mean by "simultaneous access/availability"?

**Comment by sunny1401** [comment]
Hello @smurching - by simultaneous access I meant - while running multiple experiments on Jupyter notebooks, where locations can be different. Yeah - projects which are completely different can be in separate s3 buckets - but individuals working on the same project can have multiple folders in the same bucket - simply to allow clarity of organization and independence and privacy amongst things. Having a patch also allows the user to not have to worry too much about the boilerplate functions. Thank you for replying.

**Comment by sunny1401** [comment]
I was able to complete my requirement by building a wrapper around the function.

**Comment by leobenkel** [comment]
I am trying to set where the model artifact should be written to so that the MLFlow server can find them but it seems that `MLFLOW_ARTIFACT_URI` does not do anything. 

Is there a way so that not each Data scientist have to write the same `artifact_location` over and over ? 

It seems that this issue talk about the issue but I dont see a resolution.

**Comment by leobenkel** [comment]
> @sunny1401 thanks for filing! Note that you can specify the default artifact URI to use for experiments created under an MLflow server via the `--default-artifact-root` argument to `mlflow server`, e.g. by running your server via a command like `mlflow server --default-artifact-root s3://your-s3-bucket`. Given that the default artifact URI can be specified in this manner, would you be able to clarify why your workflow involves passing an artifact URI explicitly to `create_experiment`? It seems you could avoid the need for this by setting the default artifact URI when you run the server.
> 
> Thanks again!

It seems that does not work if the path is a local path. I am building a POC with `docker-compose` and both the client and server will write to their path in their own container but it is the same local folder on the host machine. 
Just so i dont have to set up S3 connection and permission etc... for a POC.

**Comment by sunny1401** [comment]
I could be wrong but I think if you have a custom location you need to add MLFLOW_ARTIFACT_URI as a environment variable in bash profile. So in my case every person logging has this location set in their bash profile- and mlflow reads it from there.. also if your location is different from the set location at MLFLOW_ARTIFACT_ URI then u can pass artifact location while creating experiment. But for this your should have the server running.

**Comment by leobenkel** [comment]
So I have the server running on container1 , and the client with jupyter on container2 . Both are sharing a volume when i start the docker images.

The metrics are being submitted correctly, I see them in the UI of MLFlow. 

But the `mlflow.sklearn.log_model` write to `./tmp/mlflow` .

On container2 `MLFLOW_ARTIFACT_URI` is set to the local folder attached to the same volume on the host.
But it doesn't seem to read it at all :/

**Comment by leobenkel** [comment]
<img width="576" alt="Screen Shot 2020-07-07 at 19 31 55" src="https://user-images.githubusercontent.com/4960573/86867931-91a7cd00-c088-11ea-969a-0d1340485f16.png">

This is a screenshot of the terminal from within Jupyter on container2

**Comment by leobenkel** [comment]
But when I call `mlflow.sklearn.log_model`

it goes to the wrong place:

<img width="824" alt="Screen Shot 2020-07-07 at 19 33 19" src="https://user-images.githubusercontent.com/4960573/86868040-c4ea5c00-c088-11ea-86a4-4bfc803309a2.png">

**Comment by sunny1401** [comment]
Did you try logging files using log_artifact and check if other artifacts are getting logged correctly.?

**Comment by leobenkel** [comment]
I am using the examples from the mlflow repo. 
What should I change ?

**Comment by leobenkel** [comment]
<img width="1166" alt="Screen Shot 2020-07-07 at 19 36 50" src="https://user-images.githubusercontent.com/4960573/86868257-3a562c80-c089-11ea-8969-bcd7e32bd369.png">

this is what is inside the output folders

**Comment by sunny1401** [comment]
What I meant was like probably confirming if the artifact location is being read by both containers- so I would try running the experiment from both containers and also try logging the wine.csv file as an artifact using mlflow.log_artifact(<file_path>). This is probably a stupid question - but could it be because your artifact location is a hidden folder? I concur that its not reading the artifact location

**Comment by leobenkel** [comment]
Nothing is ever written into `MLFLOW_ARTIFACT_URI=/home/jovyan/.mlflow/artifacts` but container2. 
So container1 where MLFlow server is running is never seeing any artifact

**Comment by sunny1401** [comment]
Also metrics can be seen cause they are set using tracking uri - so they work..

**Comment by sunny1401** [comment]
Okay - let me check on my system by changing mlflow artifact uri to hidden location

**Comment by leobenkel** [comment]
with `mlflow.log_artifact("wine-quality.csv")`, it saves in the same location: 

<img width="1158" alt="Screen Shot 2020-07-07 at 19 46 26" src="https://user-images.githubusercontent.com/4960573/86868993-9d948e80-c08a-11ea-8018-2db1a21d028d.png">

in the `tmp` folder

**Comment by leobenkel** [comment]
I use to have a different path earlier that was without the `.` folder and the result was the same

**Comment by sunny1401** [comment]
Can container1 access different files in container2. And does it have write access on the second container?

**Comment by leobenkel** [comment]
they cant write into each other folders , they share the same network, containe2 is able to send packets to container1 since the metrics are being recorded.

The `--default-artifact-root` point to `container1/folder` 
and on container2 `MLFLOW_ARTIFACT_URI` point to `conainer2/folder` 
but both containers have a `-v localFolder:container1/folder` and `-v localFolder:container2/folder` so they are essentially sharing a folder
When I manually add a file in this folder, I am able to read it from both container so this works.

**Comment by leobenkel** [comment]
Oh ! I might have found something: 

<img width="601" alt="Screen Shot 2020-07-07 at 19 59 16" src="https://user-images.githubusercontent.com/4960573/86869967-60310080-c08c-11ea-9006-ad7a616825c4.png">

it looks like the path value is coming from here !

**Comment by leobenkel** [comment]
this is a screenshot taken from the MLFlow UI

**Comment by sunny1401** [comment]
So this os the default location where mlflow would save the artifact if you dont provide anything - So I am assuming you are setting the volume using docker-compose -? Also if you manually add the files - can they be read by mlflow or you see then interactively? Sorry for being confused. I just dont understand why is it not reading

**Comment by leobenkel** [comment]
Reading is not the problem. the problem is the writing.

**Comment by leobenkel** [comment]
yes i am using docker-compose

**Comment by leobenkel** [comment]
I figured out a way.

If I make the `container1/folder` and the `container2/folder` path the exact same identical one. Even tho they are on two different images. Then it works

**Comment by sunny1401** [comment]
Neat - congrats! Also thanks for explaining - quite interesting. Makes sense I guess since in the end its the shared location path that mlflow is getting.

**Comment by leobenkel** [comment]
hmm yeah i guess. It's not very convenient. 
Also there are A LOT of issues with `experiment-id` vs `experiment-name` , and in the code vs through `cli`. I could go on and on about it but this thread is not about it
