### ISSUE TITLE
[FR] Add Scikit-Learn API support XGBoost auto-logging

### ISSUE THREAD

**Issue by pogil** [mlflow/mlflow#2870]
## Willingness to contribute
The MLflow Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature (either as an MLflow Plugin or an enhancement to the MLflow code base)?

- [ ] Yes. I can contribute this feature independently.
- [ ] Yes. I would be willing to contribute this feature with guidance from the MLflow community.
- [x] No. I cannot contribute this feature at this time.

## Proposal Summary

Add autologging support for [XGBoost's Scikit-Learn API](https://xgboost.readthedocs.io/en/latest/python/python_api.html#module-xgboost.sklearn)

## Motivation
- What is the use case for this feature?

Make it easy to use MLflow with the Scikit-Learn API for XGBoost.

- Why is this use case valuable to support for MLflow users in general?

The Scikit-Learn API for XGBoost is a popular interface for training models with XGBoost. 

- Why is it currently difficult to achieve this use case? (please be as specific as possible about why related MLflow features and components are insufficient)

Users of the Scikit-Learn API for XGBoost must instrument their own logging code. The auto-logging for `xgboost.train` has extensive support for parameters, metrics, feature importance, and the logging the model. 

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for
Model Registry
- [x] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations

## Details

Barring technical challenges, a good contribution would have feature parity with the existing autologging support for XGBoost's `xgboost.train`. This should include all regressors and classifiers in the Scikit-Learn APIs. This may require extending the XGBoost flavor for models to also support the Scikit-Learn APIs.

**Comment by jwyyy** [comment]
Hi @pogil, has this features been added to mlflow? Is anyone currently working on this issue? If not, I am willing to take this challenge and work on the implementation.

**Comment by dbczumar** [comment]
This feature has been added to MLflow! https://mlflow.org/docs/latest/python_api/mlflow.xgboost.html#mlflow.xgboost.autolog
