### ISSUE TITLE
[FR] Use all the width of screen to display feature importance artifacts

### ISSUE THREAD

**Issue by castorfou** [mlflow/mlflow#2901]
Thank you for submitting a feature request. **Before proceeding, please review MLflow's [Issue Policy for feature requests](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md#feature-requests) and the [MLflow Contributing Guide](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst)**.

**Please fill in this feature request template to ensure a timely and thorough response.**

## Willingness to contribute
The MLflow Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature (either as an MLflow Plugin or an enhancement to the MLflow code base)?

- [ ] Yes. I can contribute this feature independently.
- [ ] Yes. I would be willing to contribute this feature with guidance from the MLflow community.
- [x] No. I cannot contribute this feature at this time.

## Proposal Summary

(In a few sentences, provide a clear, high-level description of the feature request)

I have a xgboost model with 100+ features. I keep track of feature importance (gain and weight).
I use mlflow in a standalone (localhost) mode with local storage (file).
I have made a minor modification in mlflow/xgboost.py to create higher resolutions pictures.
They are stored nicely in mlruns/*/artifacts directories.
However in mlflow ui, the display is tiny. It would be nice to have it using all the width of my screen. 

## Motivation
- What is the use case for this feature?
ergonomics mainly
- Why is this use case valuable to support for MLflow users in general?
- Why is this use case valuable to support for your project(s) or organization?
- Why is it currently difficult to achieve this use case? (please be as specific as possible about why related MLflow features and components are insufficient)

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [x] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for
Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [x] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations

## Details

(Use this section to include any additional information about the feature. If you have a proposal for how to implement this feature, please include it here. For implementation guidelines, please refer to the [Contributing Guide](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst#contribution-guidelines).)

Here is a screenshot to explain the need
![artifact feature](https://user-images.githubusercontent.com/2387408/83736030-624d0d00-a651-11ea-9286-ccc5b92be25b.jpg)

**Comment by andychow-db** [comment]
Agreed. It looks pretty small and not as friendly as it could be. I think we should wait for more community feedback before we go and implement this. Perhaps there's a common use case we could solve here.

**Comment by mirekphd** [comment]
I can share a snipped of code tested over thousands of models, but in the interest of discoverability I can do it only on StackOverflow ;)

**Comment by peterdhansen** [comment]
same issue here.
![image](https://user-images.githubusercontent.com/19173854/122136880-05119d00-ce09-11eb-8bbc-dd1c3b2ed36f.png)

The plotly container really messes things up. There is no way to zoom in the plot because it keeps the original aspect ratio.

![image](https://user-images.githubusercontent.com/19173854/122137088-77827d00-ce09-11eb-8c1b-ded802d2f227.png)

I'd normally just right click and view in new tab. But its in a plotly container so I can't?

What benefit do you get from putting pngs into a plotly container for this tracking page?

**Comment by hipoglucido** [comment]
<img width="319" alt="small_image_mlflow" src="https://user-images.githubusercontent.com/13640946/149126430-38902247-fe51-40b3-ab6e-5dbe5ec69d09.png">
It also appears extremely narrow in my case. After trying to zoom the image crops itself so it is impossible to expand it horizontally. It makes it really user unfriendly to explore my vertical plots :(
