### ISSUE TITLE
[BUG] SqlAlchemyStore.record_logged_model tries to save a tag which exceeds character limit

### ISSUE THREAD

**Issue by LorianColtof** [mlflow/mlflow#2902]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md) for additional information about bug reports. For help with debugging your code, please refer to [Stack Overflow](https://stackoverflow.com/questions/tagged/mlflow).

**Please fill in this bug report template to ensure a timely and thorough response.**

### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [X] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: n
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Alpine 3.11 inside Docker
- **MLflow installed from (source or binary)**: binary (pip)
- **MLflow version (run ``mlflow --version``)**: 1.8.0
- **Python version**: 3.8.3
- **npm version, if running the dev UI**: N/A
- **Exact command to reproduce**: `mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri <PostgreSQL URI> --default-artifact-root <SFTP URI>`

### Describe the problem
I run the MLflow tracking server on a separate host than the host that I use to train my models. The code that trains my models calls `mlflow.pytorch.log_model` every once in a while. This makes a request to `/api/2.0/mlflow/runs/log-model` which eventually calls `SqlAlchemyStore.record_logged_model` inside `mlflow/tracking/sqlalchemy_store.py`. 
This tries to save a tag with the key of the constant `MLFLOW_LOGGED_MODELS` which has a value with both the previous tag value as the current `model_dict` (if a previous one exists), encoded as JSON. However, the resulting string exceeds the tag value limit of 5000, and this is caught by the `_validate_tag` call inside the function, which in turn raises an exception.

### Code to reproduce issue
(Will add this when I have time. I might be due to the naming of some of my things that it reaches the 5000 limit)

### Other info / logs

Error message shown at the client side:
```
2020/06/03 22:35:23 ERROR mlflow.utils.rest_utils: API request to https://my-remote-tracking-server.com/api/2.0/mlflow/runs/log-model failed with code 500 != 200, retrying up to 1 more times. API response body: {"error_code": "INTERNAL_ERROR", "message": "Tag value '[{\"run_id\": \"a1cbdd41e3e14a6789011ab4397698ee\", \"artifact_path\": \"models/generator_step_50_epoch_0/\", \"utc_time_created\": \"2020-06-03 20:25:03.553633\", \"flavors\": {\"pytorch\": {\"model_data\": \"data\", \"pytorch_version\": \"1.4.0\"}, \"python_function\": {\"pi' had length 5279, which exceeded length limit of 5000"}
```

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [x] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for
Model Registry
- [x] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [x] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [x] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations

**Comment by andychow-db** [comment]
What is your use case for such large tags values?

**Comment by LorianColtof** [comment]
No I'm not creating any tags myself. I am referring to this function: https://github.com/mlflow/mlflow/blob/master/mlflow/store/tracking/sqlalchemy_store.py#L680
This uses the result of `mlflow_modwl.to_dict()`, together with decoded JSON string from the previous value if it exists, and encodes it as a new JSON string to use as the tag value, which exceeds the 5000 character limit.

**Comment by andychow-db** [comment]
Ah ~ ! That is definitely a problem.

**Comment by andychow-db** [comment]
@tomasatdatabricks Perhaps we should revisit this and make this field in the tags optional or perhaps remove it all together for right now?

**Comment by dbczumar** [comment]
This seems to have been addressed in the MLflow 1.9.0 release via logic inserted here: https://github.com/mlflow/mlflow/blob/efda4ca59ec1c37dd92fb6d70a88018783c0082b/mlflow/models/model.py#L189-L194.
