### ISSUE TITLE
[BUG] mlflow after update calls for db migration when no data has changed

### ISSUE THREAD

**Issue by mirekphd** [mlflow/mlflow#2923]
### Willingness to contribute
- [x] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: ubuntu:bionic, ubuntu:focal
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**: 1.3.0, 1.8.0
- **Python version**: 3.6.4, 3.8.2
- **Exact command to reproduce**: -

### Describe the problem
I upgraded mlflow server version in our `mirekphd/ml-mlflow` docker container from 1.3.0 (container tag 20191024) to 1.8.0 (tag 20200611). The new mlflow version fails to start due to apparent need for db schema migration, even though nothing has changed and rollback of mlflow to previous version 1.3.0 restores normal operation

### Code to reproduce issue
buggy:
`docker pull mirekphd/ml-mlflow:20200611`
vs. normal:
`docker pull mirekphd/ml-mlflow:20191024`

### Other info / logs
```
2020/06/11 11:26:28 ERROR mlflow.cli: Error initializing backend store
2020/06/11 11:26:28 ERROR mlflow.cli: Detected out-of-date database schema (found version 89d4b8295536, but expected 0a8213491aaa). Take a backup of your database, then run 'mlflow db upgrade <database_uri>' to migrate your database to the latest schema. NOTE: schema migration may result in database downtime - please consult your database's documentation for more detail.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/mlflow/cli.py", line 286, in server
    initialize_backend_stores(backend_store_uri, default_artifact_root)
  File "/usr/local/lib/python3.8/dist-packages/mlflow/server/handlers.py", line 101, in initialize_backend_stores
    _get_tracking_store(backend_store_uri, default_artifact_root)
  File "/usr/local/lib/python3.8/dist-packages/mlflow/server/handlers.py", line 87, in _get_tracking_store
    _tracking_store = _tracking_store_registry.get_store(store_uri, artifact_root)
  File "/usr/local/lib/python3.8/dist-packages/mlflow/tracking/_tracking_service/registry.py", line 37, in get_store
    return builder(store_uri=store_uri, artifact_uri=artifact_uri)
  File "/usr/local/lib/python3.8/dist-packages/mlflow/server/handlers.py", line 60, in _get_sqlalchemy_store
    return SqlAlchemyStore(store_uri, artifact_uri)
  File "/usr/local/lib/python3.8/dist-packages/mlflow/store/tracking/sqlalchemy_store.py", line 103, in __init__
    mlflow.store.db.utils._verify_schema(self.engine)
  File "/usr/local/lib/python3.8/dist-packages/mlflow/store/db/utils.py", line 50, in _verify_schema
    raise MlflowException(
mlflow.exceptions.MlflowException: Detected out-of-date database schema (found version 89d4b8295536, but expected 0a8213491aaa). Take a backup of your database, then run 'mlflow db upgrade <database_uri>' to migrate your database to the latest schema. NOTE: schema migration may result in database downtime - please consult your database's documentation for more detail.
```

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [x] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry

**Comment by mirekphd** [comment]
Update: have been ignoring this issue for some time thanks to containers that make it easy to rollback to a last working version. 

But now after upgrading MariaDB database used by MLflow Tracking from v10.3 (via v10.4) to v10.5 (using its dedicated tool `mysql_upgrade`) I've found that only the original container with `mlflow==1.3` (`mirekphd/ml-mlflow:20191024`) and `SQLalchemy==1.3.10` works correctly with the upgraded database. Newer containers with newer SQLAlchemy and mlflow versions do not, still raising "Detected out-of-date database schema" error:

```
2020/08/24 19:25:53 ERROR mlflow.cli: Error initializing backend store
2020/08/24 19:25:53 ERROR mlflow.cli: Detected out-of-date database schema (found version 89d4b8295536, but expected 27a6a02d2cf1). Take a backup of your database, then run 'mlflow db upgrade <database_uri>' to migrate your database to the latest schema. NOTE: schema migration may result in database downtime - please consult your database's documentation for more detail.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/mlflow/cli.py", line 291, in server
    initialize_backend_stores(backend_store_uri, default_artifact_root)
  File "/usr/local/lib/python3.8/dist-packages/mlflow/server/handlers.py", line 105, in initialize_backend_stores
    _get_tracking_store(backend_store_uri, default_artifact_root)
  File "/usr/local/lib/python3.8/dist-packages/mlflow/server/handlers.py", line 91, in _get_tracking_store
    _tracking_store = _tracking_store_registry.get_store(store_uri, artifact_root)
  File "/usr/local/lib/python3.8/dist-packages/mlflow/tracking/_tracking_service/registry.py", line 37, in get_store
    return builder(store_uri=store_uri, artifact_uri=artifact_uri)
  File "/usr/local/lib/python3.8/dist-packages/mlflow/server/handlers.py", line 64, in _get_sqlalchemy_store
    return SqlAlchemyStore(store_uri, artifact_uri)
  File "/usr/local/lib/python3.8/dist-packages/mlflow/store/tracking/sqlalchemy_store.py", line 104, in __init__
    mlflow.store.db.utils._verify_schema(self.engine)
  File "/usr/local/lib/python3.8/dist-packages/mlflow/store/db/utils.py", line 51, in _verify_schema
    raise MlflowException(
mlflow.exceptions.MlflowException: Detected out-of-date database schema (found version 89d4b8295536, but expected 27a6a02d2cf1). Take a backup of your database, then run 'mlflow db upgrade <database_uri>' to migrate your database to the latest schema. NOTE: schema migration may result in database downtime - please consult your database's documentation for more detail.
```

This problem is not restricted to mlflow, but extends to other packages using SQLAlchemy - such as Optuna - it too cannot access this particular MariaDB database that MLflow has still problems with, giving me the following error:
```
RuntimeError: The runtime optuna version 2.0.0 is no longer compatible with the table schema (set up by optuna 2.0.0). Please try updating optuna to the latest version by `$ pip install -U optuna`.
```

It is not even due to a versions mismatch, because precisely the same database version (10.5.5) works when created from scratch (rather than going through a database migration process from v10.3 used by MLflow), i.e. it can be correctly accessed by Optuna through the latest SQLAlchemy (1.3.19). 

So most likely it is an SQLAlchemy bug introduced after version its 1.3.10, but it manifests itself only after database version upgrade.

**Comment by mirekphd** [comment]
I've gone through the docker build logs of the errorring container (`mirekphd:ml-mlflow:20200824`) and found this strange condition in `pip install` output (notice the inequality in the incorrect direction!) that sets back SQLAlchemy by 7 months from its latest version `1.3.19` (and I do not pin anything apart from `mlflow==1.10.0` in this container):
```
Collecting sqlalchemy<=1.3.13
  Downloading SQLAlchemy-1.3.13.tar.gz (6.0 MB)
```

**Comment by mirekphd** [comment]
Let us find the newest working version of mlflow then. 

I rebuilt the `mirekphd/ml-mlflow` container using the code from the last working version (container tag 20191024), where mlflow was pinned at 1.3.0. It works OK (recognizes MariaDB database upgrade from 1.3 via 1.4 to 1.5). Now for other versions.

**Comment by mirekphd** [comment]
So even a minor version upgrade of mlflow causes the "out-of-date database schema" error, and in the error message the "expected version" stays the same, while the "found version" changes with each mlflow version. The hashes corresponding to mlflow versions that are displayed in the error message (instead of mlflow versions for example...) are hard-coded in mflow [here](https://github.com/mlflow/mlflow/tree/master/mlflow/store/db_migrations/versions).

So as long as you keep mlflow version constant (pinned), it would continue to work through any database upgrade (at least by two series / minor versions). The need to "migrate database schema" using `mlflow db upgrade` is completely independent from the need to migrate the database itself (upgrade it using its dedicated tool such as `mysql_upgrade`).

**Comment by mirekphd** [comment]
So I finally modified the container template to replace the entrypoint so as to run `mlflow db upgrade <sqlalchemy_db_conn_str>` instead of `mlflow server <params>`, using the desired new version of `mlflow==1.10.0`, 

It printed this message (which is [apparently](https://docs.openstack.org/networking-sfc/ocata/alembic_migration.html) normal): 
```
2020/08/25 10:07:33 INFO mlflow.store.db.utils: Updating database tables
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
```

... and then I was eventually able to run the standard MLflow container (`mirekphd/ml-mlflow:20200825`), and display all previously archived metrics and params data (served by MariaDB migrated earlier independently to 10.5) in this new mlflow version.

**Comment by mirekphd** [comment]
I've also found the reason why optuna clashes with mlflow, raising this error (in its latest stable version of 2.0.0):
```
RuntimeError: The runtime optuna version 2.0.0 is no longer compatible with the table schema (set up by optuna 2.0.0). Please try updating optuna to the latest version by `$ pip install -U optuna`.
```

The reason is that both mlflow and optuna store their database schema versions (courtesy of Alembic) in the same database table named `alembic_version`, overwriting each other's versions and making it impossible to use them together (at least in the same database).

Here's the database "claimed" by MLflow (where Optuna won't work - raising the avove error - and won't permit a db schema upgrade - raising the below error - with MLflow db upgrade causing data loss for most Optuna users unless they can manually patch the version to one of the versions recognized by Optuna, e.g. v1.3.0.a):

```
MariaDB [mariadb]> select * from alembic_version;
+--------------+
| version_num  |
+--------------+
| 27a6a02d2cf1 |
+--------------+
```

Running `get_all_versions()` from Optuna's [_StorageUpgrade class](https://github.com/optuna/optuna/blob/master/optuna/cli.py#L318) reveals versions expected by Optuna:
```
known_versions: ['v1.3.0.a', 'v1.2.0.a', 'v0.9.0.a']
```

And indeed the identical version of MariaDB database (10.5.5) where Optuna does work, has this value of the `version_num` in `alembic_version` table:
```
MariaDB [mariadb]> select * from alembic_version;
+-------------+
| version_num |
+-------------+
| v1.3.0.a    |
+-------------+
```

So a warning for all MLflow users that store their numerical data in an SQL database (which is recommended for performance reasons): you should **create a separate database (e.g. mlflow) to avoid overwriting Alembic version data for other applications** such as Optuna. I think this recommendation should find its way to MLflow docs (or become more prominent if it is already there).

**Comment by mirekphd** [comment]
@[tanlin2013](https://github.com/tanlin2013) are you sure you want to run an auto-upgrade of db schema [here](https://github.com/tanlin2013/mbl/commit/654d76e96b2d62a7fcd9cc87e2290bed99c09b60#diff-b80bfcff5418fdc7e455376e9269d3741cc6cf7860940222b799b5107c19c214R81)? Unconditionally, without any backups or checks? Overwriting an identifier value like this is a destructive operation, and will cause data loss for other that use `version_num` from the `alembic_version` table... as show for Optuna [above ](https://github.com/mlflow/mlflow/issues/2923#issuecomment-684808578). I would instead raise a warning that using a dedicated database e.g. named `mlflow` is strongly recommended. And only if such a "characteristically" named database was being used, I would try to auto-update the schema, of course asking the user first if the version_number already exists and if granted permission by the user, backing it up e.g. to a `version_num_copy`.

**Comment by mirekphd** [comment]
@[tanlin2013](https://github.com/tanlin2013) an example of a slightly safer MariaDB auto-migration (with a backup), i.e. preceded by a check if it is needed and a backup of system tables (but not completely save since it would be attempted even with a major DB version change), can be found in the [docker_mariadb_upgrade](https://github.com/MariaDB/mariadb-docker/blob/master/docker-entrypoint.sh#L392) function in the official MariaDB container.
