### ISSUE TITLE
[FR] Add/Expose tags for registered models

### ISSUE THREAD

**Issue by gtadamson** [mlflow/mlflow#2997]
## Willingness to contribute
The MLflow Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature (either as an MLflow Plugin or an enhancement to the MLflow code base)?

- [ ] Yes. I can contribute this feature independently.
- [ ] Yes. I would be willing to contribute this feature with guidance from the MLflow community.
- [X] No. I cannot contribute this feature at this time.

## Proposal Summary

In version 1.9.0's documentation, it appeared the ability to add tags to registered models was added: https://www.mlflow.org/docs/latest/rest-api.html#mlflowregisteredmodel and https://www.mlflow.org/docs/latest/rest-api.html#mlflowregisteredmodeltag. We were excited to use the new functionality and upgraded immediately. However, they don't seem to be exposed in the GUI (unsure if they exist in the code). Request they be added to the code/GUI as required.

## Motivation
- What is the use case for this feature? Currently we tag all versions that are registered with a model with the same tag in order to simulate a registered model tag. Trying to parse the registered model description's free text field was determined to be an anti-pattern and we didn't go that route.
- Why is this use case valuable to support for MLflow users in general? Anyone who has classes of registered models and who uses the API to query for certain types would benefit from tags at the registered model level. I'm sure there are many other use cases. Having it exposed in the GUI is critical for non-developers to be able to see and modify the tags.
- Why is this use case valuable to support for your project(s) or organization? Keeping consistent tags at the version level is error prone and errors will almost inevitably occur. We're using MLflow to drive model deployment to our operational system, so missing tags at the version level could cause incorrect models to be automatically deployed.
- Why is it currently difficult to achieve this use case? This is repetitive, but storing duplicate tags on every version is not a best practice for data management. It is also more error prone. Finally, querying the tags for each version through the API requires a separate API call for each, adding unnecessary code/queries.

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for
Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [X] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations

## Details

I think I've provided enough detail above but please contact me if more is required.

**Comment by ludaavics** [comment]
@gtadamson are you still able to tag model versions in 1.9.0 ? I get 404's just trying to figure out if i'm missing something.

**Comment by gtadamson** [comment]
I can tag active runs. If I try to tag "deleted" ones I get an error message. Is that what you're talking about?

This ticket is in reference to adding tags on the registered models so those tags would be associated with that family of versions that are associated with a registered model.

**Comment by ludaavics** [comment]
> I can tag active runs. If I try to tag "deleted" ones I get an error message. Is that what you're talking about?

No -- I think we're on the same page, talking about tagging registered models and/or versions within a registered model.

Your ticket made it sounds like you were able to tag a registered model's specific versions, presumably using [this endpoint](https://www.mlflow.org/docs/latest/rest-api.html#set-model-version-tag), and you were using it as a workaround for the inability to tag the registered model directly. However, when I try POSTing to that endpoint, I get a 404. I am just wondering if that's a regression from whatever modelfow version you upgraded from, if you're going about it some other way, or if I'm missing something else. In case it's not clear, I'm new to modelflow.

**Comment by gtadamson** [comment]
I have not tried to programmatically add the tags, my portion of the team is using mlflow in a read-only capacity to drive another system. Adding them programmatically and then not being able to view them in the GUI would not be viable with our current workflow (even if it worked). I had seen in the documentation (like you have) that it seemed to indicate that you could add tags, however in the GUI it appears you can't. I think your experience is similar to mine although we're trying to access it in different ways (GUI vs. API).

I didn't mean to imply that I had had success, only that the documentation implied the capability existed.

**Comment by ludaavics** [comment]
Gotcha, that clarifies things, thanks.

FWIW, looking more closely, it looks like the deployed html doc we have been looking at might be out of sync with the [generating markup](https://github.com/mlflow/mlflow/blob/master/docs/source/rest-api.rst), let alone with the code. I am not a react guy, but from what i can tell these api routes don't exist in the [code](https://github.com/mlflow/mlflow/blob/master/mlflow/server/js/src/model-registry/actions.js). I guess we should take all the warnings about experimental features seriously! 

@dbczumar Taking a cursory look at the history, it's not clear to me that this feature ever existed? If it did, would love to know which version -- if it's not too far back i would probably consider downgrading.

**Comment by dbczumar** [comment]
Hi @ludaavics @gtadamson , this feature is currently under development. Unfortunately, it looks like our docs for model registry tags were published prior to completion of the feature. We're aiming to introduce this functionality within the next month or so.

**Comment by gtadamson** [comment]
@dbczumar that's great news. Feel free to close this ticket or leave it open, whatever is most useful for you.

**Comment by sueann** [comment]
@dbczumar can this issue be closed now? :-)

**Comment by dbczumar** [comment]
Closing this since the feature has been released and is available in the latest version of MLflow.
