### ISSUE TITLE
[FR] Create Log Artifacts Handler/Endpoint for REST API server

### ISSUE THREAD

**Issue by lqdev** [mlflow/mlflow#3034]
Thank you for submitting a feature request. **Before proceeding, please review MLflow's [Issue Policy for feature requests](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md#feature-requests) and the [MLflow Contributing Guide](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst)**.

**Please fill in this feature request template to ensure a timely and thorough response.**

## Willingness to contribute
The MLflow Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature (either as an MLflow Plugin or an enhancement to the MLflow code base)?

- [ ] Yes. I can contribute this feature independently.
- [x] Yes. I would be willing to contribute this feature with guidance from the MLflow community.
- [ ] No. I cannot contribute this feature at this time.

## Proposal Summary

Currently, only the `artifacts/list` endpoint is exposed through the REST API. Therefore users can't log artifacts associated with their runs / experiments using the REST API. Expose `runs/log-artifacts` so users working in languages not natively supported can log artifacts to the server. 

## Motivation
- What is the use case for this feature?
- Why is this use case valuable to support for MLflow users in general?
- Why is this use case valuable to support for your project(s) or organization?
- Why is it currently difficult to achieve this use case? (please be as specific as possible about why related MLflow features and components are insufficient)

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [x] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [x] `area/docs`: MLflow documentation pages
- [x] `area/examples`: Example code
- [x] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for
Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [x] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations

## Details

(Use this section to include any additional information about the feature. If you have a proposal for how to implement this feature, please include it here. For implementation guidelines, please refer to the [Contributing Guide](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst#contribution-guidelines).)

**Comment by dmatrix** [comment]
@lqdev 

Can you elaborate a little more on the use case where you want to log artifacts? For example, what languages, in particular, you want to issue REST calls from, and are you using MLflow to create runs and experiments for?

**Comment by lqdev** [comment]
Hi @dmatrix,

I'm looking to use MLFlow with .NET. With the REST API, I can log metadata on runs / experiments. However, for model and artifact management, I'm limited.

**Comment by dmatrix** [comment]
@lqdev 

Thanks for the response. @arjundc-db @smurching Any reason not to expose `runs/log_artifacts` REST API?

**Comment by smurching** [comment]
We probably don't want to introduce `LogArtifacts` as a standard MLflow REST API for the reasons described in https://github.com/mlflow/mlflow/issues/629#issuecomment-587959112. However, as described in that issue, we'd welcome a design proposal to enable logging artifacts via the tracking server. Let's continue discussion on https://github.com/mlflow/mlflow/issues/629 :)

**Comment by smurching** [comment]
In particular, the idea would be to in fact introduce a handler for logging artifacts to the Python MLflow server and introduce a generic HTTP artifact URI scheme that clients interact with by POSTing artifacts to the specified URI, but not introduce a standard LogArtifacts REST API. Will close for now as a duplicate of #629 , but feel free to reopen!

**Comment by dbczumar** [comment]
@smurching I think it may be worth clarifying what we mean by standard vs nonstandard artifacts REST API. I absolutely agree that the MLflow Service API is not the right place to define LogArtifact / DownloadArtifact APIs, but I think it makes a lot of sense to produce a well-defined artifacts REST API in the form of a new proto service (e.g., `MlflowArtifactsService`) that can be implemented within `mlflow server` or an adjacent backend; this will also enable other developers to implement `MlflowArtifactsService` in backends of their choosing.
