### ISSUE TITLE
[FR] Reorder Runs table columns, including parameters and metrics

### ISSUE THREAD

**Issue by AveshCSingh** [mlflow/mlflow#3101]
Thank you for submitting a feature request. **Before proceeding, please review MLflow's [Issue Policy for feature requests](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md#feature-requests) and the [MLflow Contributing Guide](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst)**.

**Please fill in this feature request template to ensure a timely and thorough response.**

## Willingness to contribute
The MLflow Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature (either as an MLflow Plugin or an enhancement to the MLflow code base)?

- [ ] Yes. I can contribute this feature independently.
- [ ] Yes. I would be willing to contribute this feature with guidance from the MLflow community.
- [x] No. I cannot contribute this feature at this time.

## Proposal Summary

We should add support to reorder the columns by selecting and dragging columns on the runs table. We will also need to persist these settings in the browser.

This was initially implemented in #2251, but we decided to not include reordering since the orders would not persist.

The proposal here is to add back custom column orderings & persist the order.

## Motivation
Runs often have many associated parameters, only some of which are useful in viewing the Runs table. This is especially true when using autologging, and also sometimes occurs with metrics.

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for
Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [x] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations

**Comment by evabalini** [comment]
Hi there! Is there an estimate for when this will be implemented? 
Many thanks in advance, 
Eva

**Comment by entron** [comment]
For the moment I add prefix 1, 2, 3 to metric names as the UI seems to order metrics alphanumerically.

**Comment by lorinczszabolcs** [comment]
For me they don't even seem to be ordered alphanumerically. If at least that would be the case, that would be quite ok.

**Comment by B-Step62** [comment]
Hi everyone — reorderable, shareable saved views shipped in [MLflow 3.15.0](https://mlflow.org/releases/3.15.0/#3-shareable-table-views) 🎉

Columns in the Runs table—including parameters and metrics—can now be reordered. From the Runs page, select **Views → Save as new view** to persist the selected columns, their order and widths, filters, and sorting configuration. Saved views can also be shared by URL.

![Creating and switching between saved views](https://mlflow.org/img/releases/3.15.0/3-15-new-switching-saved-view.gif)

Please upgrade to MLflow 3.15.0 or later and try it out!

Thanks to everyone who commented or reacted with 👍 for helping us prioritize this:

@evabalini @entron @lorinczszabolcs @psarka @peper0 @jhagege @florianblume @nosound2 @honnorat @mmeendez8 @JarnoRFB @lucacampanella @xbelonogov @slimneotech @MauritsDescamps @makcfd

Closing this as completed.
