### ISSUE TITLE
[DOC-FIX] Does the mlflow server include mlflow tracking AND mlflow model registry

### ISSUE THREAD

**Issue by raman-nbg** [mlflow/mlflow#3116]
### Willingness to contribute
The MLflow Community encourages documentation fix contributions. Would you or another member of your organization be willing to contribute a fix for this documentation issue to the MLflow code base?

- [ ] Yes. I can contribute a documentation fix independently.
- [x] Yes. I would be willing to contribute a document fix with guidance from the MLflow community.
- [ ] No. I cannot contribute a documentation fix at this time.

### URL(s) with the issue:

https://mlflow.org/docs/latest/concepts.html

### Description of proposal (what needs changing):
It is not clear whether the `mlflow server` includes only mlflow tracking or both (mlflow tracking and model registry). In the docs (https://mlflow.org/docs/latest/tracking.html#mlflow-tracking-servers) the server is only listed in the tracking section. But from the UI perspective it seems that the server also includes the model registry.

I think it would be better to document the server as a own component in the Mlflow concepts section and list all features (such as tracking) of the server.

**Comment by dmatrix** [comment]
This is all going to be addressed and explained in #3108

**Comment by dmatrix** [comment]
@raman-nbg #3108 will address all these issues. Can you close this issue, if you don't mind?

**Comment by raman-nbg** [comment]
@dmatrix yes, please. You can close the issue. :)
