### ISSUE TITLE
[BUG]Cannot parse "Order by a metric" if it contains a space

### ISSUE THREAD

**Issue by jdlesage** [mlflow/mlflow#3117]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md) for additional information about bug reports. For help with debugging your code, please refer to [Stack Overflow](https://stackoverflow.com/questions/tagged/mlflow).

**Please fill in this bug report template to ensure a timely and thorough response.**

### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [X] Yes. I can contribute a fix for this bug independently.
- [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: centos 7
- **MLflow installed from (source or binary)**: source
- **MLflow version (run ``mlflow --version``)**: master branch
- **Python version**: 3.6
- **npm version, if running the dev UI**: 
- **Exact command to reproduce**:

### Describe the problem + how to reproduce the issue
Create a run with a metric that contains a space in name. Such as "Mean Square Error". 
Order following this column from the UI
Got the following error: `Invalid order_by clause 'metrics.`Mean Square Error` DESC'. Could not be parsed.`

### Other info / logs
Error seems to be on backend (sqlalchemy store in my case) . The POST search request has the correct order_by attribute in payload but response code from backend is 400 + INVALID_PARAMETER_VALUE

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for
Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [x] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations

**Comment by dmatrix** [comment]
@jdlesage thanks for filing this. I tried with the following code examples, and I could order the column in ascending and descending order. Note that the metric has spaces in them. 

```
import mlflow
from random import random, randint

if __name__ == '__main__':
   local_registry = "sqlite:///mlruns.db"
   print(f"Running local model registry={local_registry}")
   mlflow.set_tracking_uri(local_registry)
   for i in range(3):
      with mlflow.start_run():
         mlflow.log_metric("MEAN SQUARE ERROR", 0.25 * random())
```

`mlflow ui -backend-store-uri sqlite:///mlruns.db`

Ascedingind and descending order of the columns:

![Screen Shot 2020-07-16 at 10 41 34 AM](https://user-images.githubusercontent.com/1117597/87704487-52950e00-c751-11ea-811c-c491133be521.png)

![Screen Shot 2020-07-16 at 10 41 51 AM](https://user-images.githubusercontent.com/1117597/87704505-5a54b280-c751-11ea-865c-7c0e0a27153e.png)

How did you attempt to reorder it?

cc: @mparkhe

**Comment by harupy** [comment]
@dmatrix I was able to reproduce the issue.

**Comment by dmatrix** [comment]
> @dmatrix I was able to reproduce the issue with your code.

@harupy Can you specify what [search expression](https://mlflow.org/docs/latest/search-syntax.html#search) did you use to reproduce this error?

For example, you can type in `DESC metric.` or `ORDER BY metric.` as search filter, and both will result in the `Invalid clause(s) in filter string: 'DESC', 'metric.'` and `Invalid clause(s) in filter string: ORDER BY', 'metric.'` error. The question is are those expressions fully supported?

**Comment by harupy** [comment]
@dmatrix I just ran the code you attached, launched the UI, and clicked the `MEAN SQUARE ERROR` column in the table to apply sorting.

**Comment by dmatrix** [comment]
> @dmatrix I just ran the code you attached, launched the UI and clicked the `MEAN SQUARE ERROR` column in the table to apply sorting.

And I did exactly the same, hence those two attachment images that show up arrow and down arrow. Weird?

**Comment by mparkhe** [comment]
This seems like a legitimate issue. We handle [spaces and other special characters](https://mlflow.org/docs/latest/search-syntax.html#entity-names-containing-special-characters) in parsing of search `filter_string` but they are unprotected in `order_by`.

Using @dmatrix 's example above this works:

```
>>> print([r.data.metrics for r in client.search_runs(experiment_ids=[0], filter_string='metrics."MEAN SQUARE ERROR" > .2')])
[{'MEAN SQUARE ERROR': 0.22512868815177145}, {'MEAN SQUARE ERROR': 0.2240787858744757}]
```

or 

```
>>> print([r.data.metrics for r in client.search_runs(experiment_ids=[0], filter_string="metrics.`MEAN SQUARE ERROR` > .2")])
[{'MEAN SQUARE ERROR': 0.22512868815177145}, {'MEAN SQUARE ERROR': 0.2240787858744757}]
```

This would be a great first issue.

**Comment by mparkhe** [comment]
Removing tags `area/sqlalchemy`

**Comment by jdlesage** [comment]
Indeed could be a good first issue... but when I wrote the ticket, I started the investigation and saw the line to change in the SearchUtils python file. So I proposed a fix here: https://github.com/mlflow/mlflow/pull/3118

**Comment by harupy** [comment]
Fixed by #3118
