### ISSUE TITLE
[FR] Allow specifying mlflow server configurations as environment variables

### ISSUE THREAD

**Issue by larribas** [mlflow/mlflow#3122]
## MLflow Roadmap Item

This is an MLflow Roadmap item that has been prioritized by the MLflow maintainers. We’ve identified this feature as a highly requested addition to the MLflow package based on community feedback. 
We're seeking a community contribution for the implementation of this feature and will enthusiastically support the development and review of a submitted PR for this.

## Feature scope

This roadmap feature’s complexity is classified as:

- [X] `good-first-issue`: This feature is limited in complexity and effort required to implement.

## Proposal Summary

When running an MLFlow server, I would like to propose having the ability to specify flags as environment variable, such as `MLFLOW_BACKEND_STORE_URI`, `MLFLOW_DEFAULT_ARTIFACT_ROOT`,  `MLFLOW_SERVE_ARTIFACTS`, `MLFLOW_ARTIFACTS_DESTINATION`, `MLFLOW_HOST`, ...

## Motivation

The `backend-store-uri` will oftentimes contain sensitive information like database passwords. Some deployment options, like AWS ECS, won't allow you to interpolate secrets in CLI arguments at runtime.

Workarounds to this limitation of ECS include creating a custom docker image with an entrypoint that interpolates said secret, or overriding the entrypoint to use a shell.

Although this limitation is not the responsibility of MLFlow, I would argue that giving people the option to specify values that contain secret information in multiple ways (env vars, files, ...) provides a better UX for systems engineers.

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for
Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

## Details

Leverage [Click's `envvar` argument for the `.option()` decorator](https://click.palletsprojects.com/en/7.x/options/#values-from-environment-variables).

**Comment by larribas** [comment]
A bit more specifically, this is how MLFlow on top of ECS looks like for me right now:

```hcl
entryPoint = ["sh", "-c"]
command = [
  "/bin/sh -c \"mlflow server --host=0.0.0.0 --port=80 --default-artifact-root=s3://${bucket_id} --backend-store-uri=mysql+pymysql://${db_username}:`echo -n $DB_PASSWORD`@${db_address}:${db_port}/${db_name}\""
]
secrets = [
  {
    name      = "DB_PASSWORD"
    valueFrom = secret
  },
]
```

Which breaks the encapsulation of the docker image's API and forces it to provide a shell.

And this is how this proposal would allow it to look:

```hcl
command = [
  "--host=0.0.0.0",
  "--port=80",
  "--default-artifact-root=s3://${bucket_id}",
]
secrets = [
  {
    name      = "BACKEND_STORE_URI"
    valueFrom = secret
  },
]
```

Allowing me to use any image which provides `mlflow` or `mlflow server` as an entrypoint.

**Comment by zanthorn** [comment]
I would love to see this added. Same for the `default_artifact_root` flag.

**Comment by pbarker** [comment]
All the flags should also be env vars, flags aren't always friendly

**Comment by cnphil** [comment]
Working on a PR for this...
