### ISSUE TITLE
[FR] Viewing deleted experiments in the MLflow UI [UI]

### ISSUE THREAD

**Issue by vivianjiang18** [mlflow/mlflow#3127]
## Willingness to contribute
The MLflow Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature (either as an MLflow Plugin or an enhancement to the MLflow code base)?

- [ ] Yes. I can contribute this feature independently.
- [X] Yes. I would be willing to contribute this feature with guidance from the MLflow community.
- [ ] No. I cannot contribute this feature at this time.

## Proposal Summary
Ability to view deleted experiments in the MLflow UI. Similar to how runs are viewed, the ability to view deleted experiments, rename them, and restore them in the UI (potentially by adding an option to change the view) might be a useful feature.

## Motivation
- What is the use case for this feature?
For current MLflow UI users, experiments can be deleted but once deleted, they can not be seen/restore/renamed. Adding this feature would allow these actions to be done from within the MLflow UI.

- Why is this use case valuable to support for MLflow users in general?
This will allow all MLflow users to maintain/organize experiments from within the UI, and recover old/archived experiments. It will also make the overall experiment lifecycle more visible.

- Why is this use case valuable to support for your project(s) or organization?
My project involves Azure ML integration with Mlflow, including the UI - in Azure, only deleted/archived experiments can be renamed, and they can also be viewed/restored, so this feature would allow for greater parity between the two.

- Why is it currently difficult to achieve this use case? (please be as specific as possible about why related MLflow features and components are insufficient)
I believe MLflow is just missing UI components to view deleted experiments by changing a view type, and restore and rename said deleted experiments

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for
Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [X] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients

Integrations
- [X] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations

## Details
I think those are the main general details for the feature!

**Comment by AveshCSingh** [comment]
Hi @vivianjiang18,

Thank you for filing this issue. 

Viewing deleted runs makes sense because it's common to quickly delete invalid runs or parameter sweeps, and also common to want to undo that operation on realizing that a deleted run actually contains useful information.

But I don't think deleting experiments is as common, so I'm not convinced that viewing deleted experiments deserves UI support. Note that you can use the `restore_experiment` API call to restore a deleted experiment.

But if you or other contributors feel that it does and can provide some example user journeys that involve frequently viewing deleted experiments, feel free to re-open this Issue.
