### ISSUE TITLE
[FR] Add spacy and fastai built-in models links on three model-related documentation pages

### ISSUE THREAD

**Issue by dmatrix** [mlflow/mlflow#3137]
Thank you for submitting a feature request. **Before proceeding, please review MLflow's [Issue Policy for feature requests](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md#feature-requests) and the [MLflow Contributing Guide](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst)**.

**Please fill in this feature request template to ensure a timely and thorough response.**

## Willingness to contribute
The MLflow Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature (either as an MLflow Plugin or an enhancement to the MLflow code base)?

- [x ] Yes. I can contribute this feature independently.
- [ ] Yes. I would be willing to contribute this feature with guidance from the MLflow community.
- [ ] No. I cannot contribute this feature at this time.

## Proposal Summary

Add spacy and fastai as part of the documentation on relevamt pages

- Add to the list of [built-in model flavors ](https://mlflow.org/docs/latest/models.html#built-in-model-flavors)

- Add to the list of [model-apis 
](https://mlflow.org/docs/latest/models.html#model-api)

- Add to the fastai to Auto Logging [tracking page](https://mlflow.org/docs/latest/tracking.html#automatic-logging)

- Add to the list of [Python Model APIs
](https://mlflow.org/docs/latest/python_api/mlflow.models.html)
## Motivation
- What is the use case for this feature?
It is beneficial to the developer to find all built-in models well documented and searchable 

- Why is this use case valuable to support for MLflow users in general?
Developer who wants to use spacy or fastai can find out what Python fluent APIs to use for tracking

Missing documentation betrays the scope of built-in model flavors. You don't want a developer to accidentally
find out that MLflow supports fastai and spacy model flavors. Any new model flavor added should be added and where appropriate links are prominent and searchable.

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [x ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for
Model Registry
- [x ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations

## Details

(Use this section to include any additional information about the feature. If you have a proposal for how to implement this feature, please include it here. For implementation guidelines, please refer to the [Contributing Guide](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst#contribution-guidelines).)

**Comment by dmatrix** [comment]
Issue fixed and as part of  https://github.com/mlflow/mlflow/pull/3194
