### ISSUE TITLE
[DOC-FIX] SFTP Documentation

### ISSUE THREAD

**Issue by synchronizing** [mlflow/mlflow#3182]
### Willingness to contribute
- [x] Yes. I can contribute a documentation fix independently.
- [ ] Yes. I would be willing to contribute a document fix with guidance from the MLflow community.
- [ ] No. I cannot contribute a documentation fix at this time.

### URL(s) with the issue:

- https://www.mlflow.org/docs/latest/tracking.html#sftp-server

### Description of Proposal

The `SFTP` artifact stores section of the documentation lacks proper instruction on setting up the configurations to get the client up and running. Perhaps it's lack of sleep from my end, but I still have not been able to get it all working (more on this issue after documentation pointers).

#### File Structure

Inform the user of what files he/she would need to set-up. The current description is not helpful: 

> To store artifacts in an SFTP server, specify a URI of the form sftp://user@host/path/to/directory. You should configure the client to be able to log in to the SFTP server without a password over SSH **(e.g. public key, identity file in ssh_config, etc.)**.

Since `pysftp` does not work out of the box with Windows regarding default paths (at least within MLFlow's implementation), the documentation should, at the very least, include information on setting up the Unix-based clients. 

#### Host Name

Mention that the host name inside the `~/.ssh/config` file requires to be the same as the `hostname` set by the `--default-artifact-root` flag. This might seem obvious at first, but when contextualizing shared networks/containerized environments things become a bit more hairy and the more detail the better.

https://github.com/mlflow/mlflow/blob/bde9c044f7b883723b3255e3c39eeb49a3c81fc2/mlflow/store/artifact/sftp_artifact_repo.py#L40

#### `known_hosts`

Specify where Specify `pysftp` looks for `known_hosts` files. Currently facing an issue on this myself. According to the `pysftp` documentation [here](https://pysftp.readthedocs.io/en/release_0.2.9/cookbook.html#pysftp-cnopts):

> Host Key checking is enabled by default. It will use `~/.ssh/known_hosts` by default.

Again, might seem obvious to some, but not all (specially folks who haven't messed with SSL in a while -- 🤚🏼).

----

## Issue

I'll use this opportunity to ask for help in this problem. I currently have the following structure inside of my `~/.ssh/` folder:

```
.
├── authorized_keys
├── config
└── known_hosts
```

All of these files are configured appropriately with the details mentioned above figured out. When trying to run `mlflow run`, the following issue is spit out by `pysftp` (as part of `mlflow run` crashing, of course):

```
raise HostKeysException('No Host Keys Found')
pysftp.exceptions.HostKeysException: No Host Keys Found
```

Any help would be awesome. I'll contribute back and push updated documentation on how to setup `SFTP`. 😄

**Comment by dmatrix** [comment]
@synchronizing thanks for filling this issue. Yes, we would love to get clarification on the documentation. Please do file a PR
and follow the guidelines in [CONTRIBUTIONS.rst](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst#building-a-distributable-artifact)

**Comment by synchronizing** [comment]
> @synchronizing thanks for filling this issue. Yes, we would love to get clarification on the documentation. Please do file a PR
> and follow the guidelines in [CONTRIBUTIONS.rst](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst#building-a-distributable-artifact)

Hey @dmatrix. I'm willing to help-out, but currently there are some issues with `SFTP`. I've added them to the bottom of my post. 😄

**Comment by synchronizing** [comment]
I figured out the issue. It's directly inside [`/mlflow/store/artifact/sftp_artifact_repo.py`](https://github.com/mlflow/mlflow/blob/bde9c044f7b883723b3255e3c39eeb49a3c81fc2/mlflow/store/artifact/sftp_artifact_repo.py). I'll fix the issue and create a PR.

**Comment by harupy** [comment]
@synchronizing Can you try running the code below and see what it prints out?

```python
import os

from pysftp.helpers import known_hosts
from paramiko.hostkeys import HostKeys

h = HostKeys()

try:
    kh = known_hosts()
    print("known_hosts:", kh)
    h.load(os.path.expanduser(kh))
except Exception as e:
    print(e)

print(len(h.items()))
```

This code is almost the same as what `pysftp` executes internally ([link](https://bitbucket.org/dundeemt/pysftp-dev/src/2d015d8e2e62e1486578489037c8e0cf4935b4af/pysftp/__init__.py?at=default#lines-74))

**Comment by hududed** [comment]
Hi I am wondering if there is a follow up to this issue:

running the quoted codes gave me a 0, which is spewing out the No Host Keys Found error ..

> @synchronizing Can you try running the code below and see what it prints out?
> 
> ```python
> import os
> 
> from pysftp.helpers import known_hosts
> from paramiko.hostkeys import HostKeys
> 
> h = HostKeys()
> 
> try:
>     kh = known_hosts()
>     print("known_hosts:", kh)
>     h.load(os.path.expanduser(kh))
> except Exception as e:
>     print(e)
> 
> print(len(h.items()))
> ```
> 
> This code is almost the same as what `pysftp` executes internally ([link](https://bitbucket.org/dundeemt/pysftp-dev/src/2d015d8e2e62e1486578489037c8e0cf4935b4af/pysftp/__init__.py?at=default#lines-74))

**Comment by synchronizing** [comment]
Hey, I'm no longer using `MLFlow` as I've since left the position for another. Closing this issue for now.
