### ISSUE TITLE
[BUG] Resuming runs with mlflow.start_run(run_id=) does not set state properly.

### ISSUE THREAD

**Issue by mgermain** [mlflow/mlflow#3228]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md) for additional information about bug reports. For help with debugging your code, please refer to [Stack Overflow](https://stackoverflow.com/questions/tagged/mlflow).

**Please fill in this bug report template to ensure a timely and thorough response.**

### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [X] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 20.04.1 LTS
- **MLflow installed from (source or binary)**: binary `pip install mlflow` in conda env
- **MLflow version (run ``mlflow --version``)**: mlflow, version 1.10.0
- **Python version**: Python 3.8.3
- **Exact command to reproduce**: See code to reproduce section.

### Describe the problem
Setting `run_id` in `mlflow.start_run(run_id=)` doe no behave as advertised.
According to the [start_run documentation](https://mlflow.org/docs/latest/python_api/mlflow.html#mlflow.start_run), setting the `run_id` should set the status to running and it does not.

Relevant line from the doc:
"run_id – If specified, get the run with the specified UUID and log parameters and metrics under that run. The run’s end time is unset and its status is set to running"

### Code to reproduce issue
```python
import mlflow

# Start run and print status (should be Running)
run = mlflow.start_run()
run_id = run.info.run_id
print(f"Should be RUNNING = {run.info.status}")

# Simulate failure and print status (should be FAILED)
mlflow.end_run(status="FAILED")
print(f"Should be FAILED = {mlflow.get_run(run_id).info.status}")

# Resume failed run from id
resumed_run = mlflow.start_run(run_id)
# Print status of resumed run (should be RUNNING)
print(f"Should be RUNNING = {resumed_run.info.status}")
```

### Other info / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [X] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by apurva-koti** [comment]
Thank you for filing this issue @mgermain ! A fix for this is tracked in #3329.

**Comment by Maarten-s1991** [comment]
Hi,

Issue still doesn't seem to be fixed. I used @mgermain exact code snippet and gives me following error:

RestException: BAD_REQUEST: Response: {'Error': {'Code': 'UserError', 'Severity': None, 'Message': 'Start time for run id e5f0f370-f7f2-472e-a758-35475d60e011 is already set.', 'MessageFormat': None, 'MessageParameters': None, 'ReferenceCode': None, 'DetailsUri': None, 'Target': None, 'Details': [], 'InnerError': None, 'DebugInfo': None}, 'Correlation': {'operation': '92fb8816f8a77c409b6c394de70d72a9', 'request': '38abc5973b845641'}, 'Environment': 'westeurope', 'Location': 'westeurope', 'Time': '2021-05-19T10:35:55.8724767+00:00', 'ComponentName': 'mlflow', 'error_code': 'BAD_REQUEST'}
