### ISSUE TITLE
[BUG] mlflow_get_experiment() in R API does not work.

### ISSUE THREAD

**Issue by jerrylian-db** [mlflow/mlflow#3234]
### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [x] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: N/A
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: N/A
- **MLflow version: `mlflow_1.10.0` in R on Databricks MLR.
- **Exact command to reproduce**: `mlflow_get_experiment()`

### Describe the problem

I ran the [Databricks MLflow R quikstart notebook](https://docs.databricks.com/applications/mlflow/quick-start-r.html), which loads MLflow, runs the install script, and executes an MLflow run. After that, I called `mlfow_get_experiment()`, expecting to see the active experiment metadata and associate runs. Instead, I got the following error

```
Error : `experiment_id` must be specified when there is no active experiment. Error : `experiment_id` must be specified when there is no active experiment.
```

See https://www.mlflow.org/docs/latest/R-api.html#mlflow-get-experiment for the official documentation for this function.

### Code to reproduce issue
The steps above should be able to reproduce the error.

### Other info / logs
There is no traceback in Databricks.

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Language 
- [x] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

**Comment by jerrylian-db** [comment]
### How to reproduce outside of Databricks.

I installed a fresh version of Rstudio on my computer. Then I ran:
```r
install.packages("mlflow")
mlflow::install_mlflow()
```
which installed `mlflow_1.10.0`.

Then I ran:
```r
library(mlflow)
install_mlflow()
run <- mlflow_start_run()
mlflow_log_param("param1", 5)
```
Here is the error:
```
Error: `experiment_id` must be specified when there is no active experiment.
```

**Comment by dmatrix** [comment]
@jerrylian-db Thanks for filing this. @javierluraschi any comments on this?

**Comment by lorenzwalthert** [comment]
There is a typo in your reprex (`mlfow_get_experiment()`), but otherwise I agree. I think the problem is that the the active run is set on `mlflow::mlflow_start_run()`, but the experiment not, so we need to add a call to `mlflow::mlflow_set_experiment()`. I did so in https://github.com/mlflow/mlflow/pull/3276.
