### ISSUE TITLE
[BUG] Something went wrong

### ISSUE THREAD

**Issue by kkendzia** [mlflow/mlflow#3273]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md) for additional information about bug reports. For help with debugging your code, please refer to [Stack Overflow](https://stackoverflow.com/questions/tagged/mlflow).

**Please fill in this bug report template to ensure a timely and thorough response.**

### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [x ] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:  no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Debian 9 (in Docker / K8s)
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**:  1.10.0
- **Python version**: 3.7.8
- **npm version, if running the dev UI**: ?
- **Exact command to reproduce**: mlflow server --host 0.0.0.0 --backend-store-uri sqlite:////backend.sqlite --default-artifact-root ftp://anonymous@${SFTPD_BASE_NAME}:${SFTPD_BASE_PORT}/upload

### Describe the problem
**This problem is located in the tracking server**
When clicking on an artifact in a run, the whole page crashes. This only happens with FTP, sFTP worked fine!

### Code to reproduce issue
Added just a simple model (adding a number to an input), but this shouldn't be a problem.

### Other info / logs
Response when I click on an artifact (Status 200) 
```
{,…}
files: [,…]
0: {path: "/upload/1/0df141c5b76348f89ae059c18e66c1da/artifacts/add_number_model2/model", is_dir: true}
is_dir: true
path: "/upload/1/0df141c5b76348f89ae059c18e66c1da/artifacts/add_number_model2/model"
root_uri: "ftp://anonymous@mlflow-artifacts-store.technologies.solactive.com:32021/upload/1/0df141c5b76348f89ae059c18e66c1da/artifacts"
```

JavaScript log:

```
react-dom.production.min.js:3282 Error: Can't find child.
    at ArtifactUtils.js:50
    at Array.forEach (<anonymous>)
    at Function.value (ArtifactUtils.js:46)
    at t.value (ArtifactView.js:213)
    at t.value (ArtifactView.js:105)
    at t.value (ArtifactView.js:244)
    at d (react-dom.production.min.js:2740)
    at beginWork (react-dom.production.min.js:2916)
    at o (react-dom.production.min.js:4051)
    at i (react-dom.production.min.js:4068)
_r @ react-dom.production.min.js:3282
commitErrorLogging @ react-dom.production.min.js:3619
C @ react-dom.production.min.js:4395
w @ react-dom.production.min.js:4296
_ @ react-dom.production.min.js:4263
b @ react-dom.production.min.js:4254
interactiveUpdates @ react-dom.production.min.js:4563
wn @ react-dom.production.min.js:1684
AppErrorBoundary.js:19 Error: Can't find child.
    at ArtifactUtils.js:50
    at Array.forEach (<anonymous>)
    at Function.value (ArtifactUtils.js:46)
    at t.value (ArtifactView.js:213)
    at t.value (ArtifactView.js:105)
    at t.value (ArtifactView.js:244)
    at d (react-dom.production.min.js:2740)
    at beginWork (react-dom.production.min.js:2916)
    at o (react-dom.production.min.js:4051)
    at i (react-dom.production.min.js:4068)
value @ AppErrorBoundary.js:19
commitErrorLogging @ react-dom.production.min.js:3620
C @ react-dom.production.min.js:4395
w @ react-dom.production.min.js:4296
_ @ react-dom.production.min.js:4263
b @ react-dom.production.min.js:4254
interactiveUpdates @ react-dom.production.min.js:4563
wn @ react-dom.production.min.js:1684
Reducers.js:292 Uncaught (in promise) TypeError: Cannot read property 'children' of undefined
    at Reducers.js:292
    at Array.forEach (<anonymous>)
    at artifactsByRunUuid (Reducers.js:291)
    at combineReducers.js:129
    at combineReducers.js:129
    at g (createStore.js:166)
    at index.js:114
    at index.js:11
    at dispatch (applyMiddleware.js:46)
    at index.js:202
(anonymous) @ Reducers.js:292
artifactsByRunUuid @ Reducers.js:291
(anonymous) @ combineReducers.js:129
(anonymous) @ combineReducers.js:129
g @ createStore.js:166
(anonymous) @ index.js:114
(anonymous) @ index.js:11
dispatch @ applyMiddleware.js:46
(anonymous) @ index.js:202
Promise.then (async)
(anonymous) @ index.js:228
(anonymous) @ index.js:11
(anonymous) @ bindActionCreators.js:3
a.onToggleTreebeard @ ArtifactView.js:126
value @ node.js:80
(anonymous) @ react-dom.production.min.js:41
invokeGuardedCallback @ react-dom.production.min.js:53
invokeGuardedCallbackAndCatchFirstError @ react-dom.production.min.js:56
A @ react-dom.production.min.js:174
R @ react-dom.production.min.js:203
I @ react-dom.production.min.js:215
M @ react-dom.production.min.js:192
F @ react-dom.production.min.js:258
z @ react-dom.production.min.js:267
vn @ react-dom.production.min.js:1661
batchedUpdates @ react-dom.production.min.js:4503
Ve @ react-dom.production.min.js:772
Cn @ react-dom.production.min.js:1707
interactiveUpdates @ react-dom.production.min.js:4561
wn @ react-dom.production.min.js:1684
```

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [x] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by kkendzia** [comment]
So the page crashes and just displays "Something went wrong", and I have to reload the page completly before I can interact with any button again.

**Comment by harupy** [comment]
https://github.com/mlflow/mlflow/pull/3210 fixed this issue.

**Comment by harupy** [comment]
@kkendzia 

You can install the latest dev version by running:

```
pip install git+https://github.com/mlflow/mlflow.git
```

**Comment by harupy** [comment]
@kkendzia Feel free to reopen this issue if the error still persists.

**Comment by kkendzia** [comment]
Thank you! We'll wait for the next release.
