### ISSUE TITLE
[BUG] Unclear exception upon incorrectly configuring DATABRICKS_HOST

### ISSUE THREAD

**Issue by bramrodenburg** [mlflow/mlflow#3301]
### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [X] Yes. I can contribute a fix for this bug independently.
- [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS Catelina 10.15.4
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**: 1.10.0
- **Python version**: 3.7.3
- **npm version, if running the dev UI**: -
- **Exact command to reproduce**: 
```bash
MLFLOW_TRACKING_URI=databricks
DATABRICKS_HOST="https://westus2.azuredatabricks.net/a"  # <- note the invalid 'a' at the end 
DATABRICKS_TOKEN="<secret-token>"

mlflow experiments create -n /path/to/somewhere
```

### Describe the problem
Incorrectly configuring the `DATABRICKS_HOST` variable can lead in certain cases to error messages that are unclear to the user. In the provided example, `mlflow` crashes with the following error message:

```
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

This is caused by the `verify_rest_response` function in `mlflow/utils/rest_utils.py` which only checks whether the returned status code is OK, regardless of whether the response is in JSON format or not. A simple fix would be to check the format as well, and notify the user if the returned format is not in JSON.

### Code to reproduce issue

```bash
export MLFLOW_TRACKING_URI=databricks
export DATABRICKS_HOST="https://westus2.azuredatabricks.net/a"  # <- note the invalid 'a' at the end 
export DATABRICKS_TOKEN="<secret-token>"

mlflow experiments create -n /path/to/somewhere
```

### Other info / logs
Error message:
```text
 "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [X] `integrations/databricks`: Databricks integrations

**Comment by dmatrix** [comment]
@bramrodenburg Thanks for filing this bug. If I read you correctly, in some cases when the `DATABRICKS_HOST` is misconfigured with an invalid path (as stated above), the status code returned is 200 yet mlflow crashes. Do you mean that `examples/rest_api/mlflow_tracking_rest_api.py` fails with an exception?

This is more on the [client-side checking ](https://github.com/mlflow/mlflow/blob/master/mlflow/utils/rest_utils.py#L113). Perhaps the `endpoint` should be verified if it's valid or not. For invalid endpoint, it returns not a 200.

cc: @avesh-db

**Comment by bramrodenburg** [comment]
In this case I was using `mlflow experiments create`, which I believe refers to `mlflow/experiments.py` -> `create`.

An exception is indeed thrown, which I think is correct given that the endpoint is not configured correctly, however I think the type of error and its message are not clear, and could be handled in a better way.

**Comment by amesar** [comment]
The server is incorrectly returning HTML instead of JSON. 
https://github.com/mlflow/mlflow/blob/master/mlflow/utils/rest_utils.py#L156

```
<html>
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="Content-Language" content="en"/>
    <title>Databricks - Sign In</title>
    <meta name="viewport" content="width=960">
    <link rel="stylesheet" href="/login/bootstrap.min.css">
    <link rel="icon" type="image/png" href="login/favicon.ico" />

    <meta http-equiv="content-type" content="text/html; charset=UTF8">
<link rel="shortcut icon" href="favicon.ico"><link href="login/login.81bd9e94.css" rel="stylesheet"></head>
<body>
<div id="login-page"></div>
<script type="text/javascript" src="login/login.8c534997.js"></script></body>
</html>
```

**Comment by AveshCSingh** [comment]
Thanks for fixing this in #3302 , @bramrodenburg !
