### ISSUE TITLE
[BUG] http.client.RemoteDisconnected for get_metric_history

### ISSUE THREAD

**Issue by mberr** [mlflow/mlflow#3334]
### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [x] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: yes (cf. below)
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.04.1 LTS
- **MLflow installed from (source or binary)**: binary (via pip)
- **MLflow version (run ``mlflow --version``)**: mlflow, version 1.10.0
- **Python version**: Python 3.8.2
- **npm version, if running the dev UI**: n/a
- **Exact command to reproduce**: cf. code to reproduce

### Describe the problem
I use Mlflow to track results throughout the training of a model.

The Mlflow server uses a Postgres backend and is started via
```console
$ mlflow server --backend-store-uri postgresql://mlflow_user:mlflow@localhost/mlflow_db --default-artifact-root /path/to/artifacts --host HOSTNAME
```
on a separate machine only used for tracking results. The actual training happens on workers which log to Mlflow via `http://HOSTNAME:5000`.

To analyse the training progress, I want to use `get_metric_history` to get the values of a metric of interest throughout the training. However, the number of tracked metrics (`32k`) seems to be large enough to cause a timeout during the HTTP request. This error also occurs when running the `get_metric_history` request directly on the tracking server. 

In the web frontend I can view the metrics, although it takes a long time until the page finishes loading (`~80 sec`, Mozilla Firefox 79.0).

When I directly issue the HTTP request taken from the browser's debug tools, the result comes back quickly

```console
$ time curl 'http://HOSTNAME:5000/ajax-api/2.0/preview/mlflow/metrics/get-history?run_uuid=bc82535154804601a1e1dcb91e9048b5&metric_key=eval.test.hits_at_1' -o /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 90681  100 90681    0     0   147k      0 --:--:-- --:--:-- --:--:--  146k

real	0m0,770s
user	0m0,004s
sys	0m0,011s
```

### Code to reproduce issue
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```python-console
>>> from mlflow.tracking import MlflowClient
>>> client = MlflowClient(tracking_uri='http://HOSTNAME:5000')
>>> history = client.get_metric_history(run_id='bc82535154804601a1e1dcb91e9048b5', key='eval.train.hits_at_1')
```

<details>
<summary>Full traceback</summary>

```python-traceback
Traceback (most recent call last):
  File "/path/to/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/path/to/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/path/to/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1332, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 272, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/path/to/venv/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/path/to/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 724, in urlopen
    retries = retries.increment(
  File "/path/to/venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/path/to/venv/lib/python3.8/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/path/to/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/path/to/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/path/to/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1332, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 272, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/to/venv/lib/python3.8/site-packages/mlflow/tracking/client.py", line 110, in get_metric_history
    return self._tracking_client.get_metric_history(run_id, key)
  File "/path/to/venv/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py", line 60, in get_metric_history
    return self.store.get_metric_history(run_id=run_id, metric_key=key)
  File "/path/to/venv/lib/python3.8/site-packages/mlflow/store/tracking/rest_store.py", line 187, in get_metric_history
    response_proto = self._call_endpoint(GetMetricHistory, req_body)
  File "/path/to/venv/lib/python3.8/site-packages/mlflow/store/tracking/rest_store.py", line 32, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "/path/to/venv/lib/python3.8/site-packages/mlflow/utils/rest_utils.py", line 139, in call_endpoint
    response = http_request(
  File "/path/to/venv/lib/python3.8/site-packages/mlflow/utils/rest_utils.py", line 76, in http_request
    response = request_with_ratelimit_retries(max_rate_limit_interval,
  File "/path/to/venv/lib/python3.8/site-packages/mlflow/utils/rest_utils.py", line 58, in request_with_ratelimit_retries
    response = requests.request(**kwargs)
  File "/path/to/venv/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/path/to/venv/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/path/to/venv/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/path/to/venv/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

</details>

### Other info / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

<details>
  <summary>Full list of installed packages in venv</summary>
  
  ```console
Package                   Version
------------------------- ---------
alembic                   1.4.2
azure-core                1.7.0
azure-storage-blob        12.3.2
certifi                   2020.6.20
cffi                      1.14.0
chardet                   3.0.4
click                     7.1.2
cloudpickle               1.5.0
cryptography              2.9.2
databricks-cli            0.11.0
docker                    4.2.2
entrypoints               0.3
Flask                     1.1.2
gitdb                     4.0.5
GitPython                 3.1.3
gorilla                   0.3.0
gunicorn                  20.0.4
idna                      2.10
isodate                   0.6.0
itsdangerous              1.1.0
Jinja2                    2.11.2
Mako                      1.1.3
MarkupSafe                1.1.1
mlflow                    1.10.0
msrest                    0.6.17
numpy                     1.19.0
oauthlib                  3.1.0
pandas                    1.0.5
pip                       20.2.2
pkg-resources             0.0.0
prometheus-client         0.8.0
prometheus-flask-exporter 0.14.1
protobuf                  3.12.2
psycopg2                  2.8.5
pycparser                 2.20
python-dateutil           2.8.1
python-editor             1.0.4
pytz                      2020.1
PyYAML                    5.3.1
querystring-parser        1.2.4
requests                  2.24.0
requests-oauthlib         1.3.0
setuptools                49.6.0
six                       1.15.0
smmap                     3.0.4
SQLAlchemy                1.3.13
sqlparse                  0.3.1
tabulate                  0.8.7
urllib3                   1.25.9
websocket-client          0.57.0
Werkzeug                  1.0.1
wheel                     0.35.1
```
</details>

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by mberr** [comment]
The problem seems to be caused by gunicorn workers timing out:
```
...
Aug 26 14:34:03 HOST start-mlflow[24625]: [2020-08-26 14:34:02 +0200] [24625] [CRITICAL] WORKER TIMEOUT (pid:24648)
Aug 26 14:34:04 HOST start-mlflow[25136]: [2020-08-26 14:34:04 +0200] [25136] [INFO] Booting worker with pid: 25136
Aug 26 14:34:05 HOST start-mlflow[24625]: [2020-08-26 14:34:05 +0200] [24625] [CRITICAL] WORKER TIMEOUT (pid:24649)
Aug 26 14:34:06 HOST start-mlflow[25137]: [2020-08-26 14:34:06 +0200] [25137] [INFO] Booting worker with pid: 25137
...
```

Increasing the worker timeout by adding
```console
--gunicorn-opts --timeout 300
```
to the server start script does not (reliably) solve the issue.

Also the behaviour is not always reproducible: In some cases the server returns an answer in short time. 


Further investigating via `htop` shows that the database operation is running too slow (top is showing `postgres: ... SELECT` as a long running process with high CPU utilization). I suspect this is caused by not having / not using an appropriate index to select the metrics corresponding to a certain `run_uuid` from the `metrics` table.

**Comment by mberr** [comment]
I could resolve the problem by adding an index on the `run_uuid` column of the metrics table:

```sql
CREATE INDEX ON metrics (run_uuid);
```

Afterwards, also the web frontend got notably faster.

For reference, the `metrics` table currently contains `51,945,952` rows.

**Comment by harupy** [comment]
Fixed by https://github.com/mlflow/mlflow/pull/5443.
