### ISSUE TITLE
[BUG] 550 Failed to open file when using FTP as backend

### ISSUE THREAD

**Issue by kkendzia** [mlflow/mlflow#3351]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md) for additional information about bug reports. For help with debugging your code, please refer to [Stack Overflow](https://stackoverflow.com/questions/tagged/mlflow).

**Please fill in this bug report template to ensure a timely and thorough response.**

### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [x] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Arch / Linux Debian / inside docker / outside docker
- **MLflow installed from (source or binary)**: pip
- **MLflow version (run ``mlflow --version``)**: 1.10.0 and current master
- **Python version**: 3.8.3
- **npm version, if running the dev UI**:
- **Exact command to reproduce**: `mlflow models serve --no-conda --host=0.0.0.0 --model-uri=${MODEL_OF_INTEREST_URI}`

### Describe the problem
When using FTP, I can't serve models - "550 Failed to open file". When using sftp everything works fine.

### Code to reproduce issue
Create an experiment / run. Try to serve model from ftp backend.

### Other info / logs
`Try to serve model from URI 'ftp://anonymous@<URI>/upload/3/612d0add4b5845169153413556dddc42/artifacts/add_number_model2'...
Traceback (most recent call last):
  File "/usr/local/bin/mlflow", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/mlflow/models/cli.py", line 55, in serve
    return _get_flavor_backend(model_uri,
  File "/usr/local/lib/python3.8/site-packages/mlflow/models/cli.py", line 164, in _get_flavor_backend
    local_path = _download_artifact_from_uri(
  File "/usr/local/lib/python3.8/site-packages/mlflow/tracking/artifact_utils.py", line 73, in _download_artifact_from_uri
    return get_artifact_repository(artifact_uri=root_uri).download_artifacts(
  File "/usr/local/lib/python3.8/site-packages/mlflow/store/artifact/artifact_repo.py", line 130, in download_artifacts
    return download_file(artifact_path)
  File "/usr/local/lib/python3.8/site-packages/mlflow/store/artifact/artifact_repo.py", line 90, in download_file
    self._download_file(remote_file_path=fullpath, local_path=local_file_path)
  File "/usr/local/lib/python3.8/site-packages/mlflow/store/artifact/ftp_artifact_repo.py", line 132, in _download_file
    ftp.retrbinary('RETR ' + remote_full_path, f.write)
  File "/usr/local/lib/python3.8/ftplib.py", line 425, in retrbinary
    with self.transfercmd(cmd, rest) as conn:
  File "/usr/local/lib/python3.8/ftplib.py", line 382, in transfercmd
    return self.ntransfercmd(cmd, rest)[0]
  File "/usr/local/lib/python3.8/ftplib.py", line 348, in ntransfercmd
    resp = self.sendcmd(cmd)
  File "/usr/local/lib/python3.8/ftplib.py", line 275, in sendcmd
    return self.getresp()
  File "/usr/local/lib/python3.8/ftplib.py", line 248, in getresp
    raise error_perm(resp)
ftplib.error_perm: 550 Failed to open file.
`

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [x] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
looks similar to this error: https://serverfault.com/questions/294250/ftp-failed-to-open-file#:~:text=2%20Answers&text=The%20550%20error%20code%20should,sure%20how%20likely%20that%20is.

**Comment by kkendzia** [comment]
Writing works fine, file permissions are 
`-rw-rw-rw-    1 ftp      ftp            300 Aug 28 08:16 MLmodel
-rw-rw-rw-    1 ftp      ftp            128 Aug 28 08:16 conda.yaml
-rw-rw-rw-    1 ftp      ftp            103 Aug 28 08:16 python_model.pkl`

`ftp> ls -la
227 Entering Passive Mode (10,19,10,23,125,24).
150 Here comes the directory listing.
drwxrwxr-x    2 ftp      ftp          4096 Aug 28 08:16 .
drwxrwxr-x    3 ftp      ftp          4096 Aug 28 08:16 ..
-rw-rw-rw-    1 ftp      ftp           300 Aug 28 08:16 MLmodel
-rw-rw-rw-    1 ftp      ftp           128 Aug 28 08:16 conda.yaml
-rw-rw-rw-    1 ftp      ftp           103 Aug 28 08:16 python_model.pkl
226 Directory send OK.
ftp> get conda.yaml
227 Entering Passive Mode (10,19,10,23,125,27).
150 Opening BINARY mode data connection for conda.yaml (128 bytes).
226 Transfer complete.
128 bytes received in 0.000135 seconds (926 kbytes/s)
ftp> 
`

So this works, but not with mlflow. Even in the browser I can access and download.

**Comment by kkendzia** [comment]
Any ideas here? Or does it have something to do with my vsftpd config?

    anonymous_enable=YES
    local_enable=NO
    write_enable=YES
    local_umask=000
    anon_upload_enable=YES
    anon_world_readable_only=YES
    hide_ids=YES
    anon_mkdir_write_enable=YES
    anon_other_write_enable=YES
    dirmessage_enable=YES
    xferlog_enable=YES
    connect_from_port_20=YES
    chown_uploads=YES
    chown_username=ftp
    chown_upload_mode=0666
    anon_umask=000
    xferlog_file=/var/log/vsftpd.log
    xferlog_std_format=YES
    nopriv_user=ftp
    banner_file=/etc/vsftpd/vsftpd.banner
    listen=YES
    secure_email_list_enable=NO
    pasv_min_port={{ .Values.ftp.passive.portMin }}
    pasv_max_port={{ .Values.ftp.passive.portMax }}
    pasv_addr_resolve=YES
    pasv_address=<URL>
    seccomp_sandbox=NO
    no_anon_password=YES
    allow_writeable_chroot=YES
    pasv_promiscuous=YES

**Comment by kkendzia** [comment]
Ok I found the problem. 

SFTP puts the MLmodel file to a different folder:

   sftp> ls -la
   drwxr-xr-x    2 1000     100          4096 Aug 25 13:55 .
   drwxr-xr-x    3 1000     100          4096 Aug 25 13:55 ..
   -rw-r--r--    1 1000     100           300 Aug 25 13:55 MLmodel
   -rw-r--r--    1 1000     100           128 Aug 25 13:55 conda.yaml
   -rw-r--r--    1 1000     100           103 Aug 25 13:55 python_model.pkl
   sftp> pwd
   Remote working directory: /upload/24/40b42167793743ceb62f1593f6add137/artifacts/add_number_model2
   sftp> 

In FTP its ftp://<URL>/upload/3/57c146e168294441ad173c1577f79675/artifacts/add_number_model2/model/

So this is inconsistent! But what should be the correct path?

**Comment by kkendzia** [comment]
I'll close this down and rename it.
