### ISSUE TITLE
[FR] Cloud storages as remote tracking URIs

### ISSUE THREAD

**Issue by Matts966** [mlflow/mlflow#3428]
## Willingness to contribute
The MLflow Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature (either as an MLflow Plugin or an enhancement to the MLflow code base)?

- [ ] Yes. I can contribute this feature independently.
- [x] Yes. I would be willing to contribute this feature with guidance from the MLflow community.
- [ ] No. I cannot contribute this feature at this time.

## Proposal Summary

Currently, runs can not be stored on cloud storage such as Google Cloud Storage and S3.
https://www.mlflow.org/docs/latest/tracking.html#where-runs-are-recorded

We can start using MLFlow more quickly with support for such stores.

## Motivation
- What is the use case for this feature?
When we want to have API or DB server, but share experiment results, we can use this.

- Why is this use case valuable to support for MLflow users in general?

Easier setup

- Why is this use case valuable to support for your project(s) or organization?

We currently use GCS to store information but do not want to maintain another server.

- Why is it currently difficult to achieve this use case? (please be as specific as possible about why related MLflow features and components are insufficient)

Currently, runs can not be stored on cloud storage such as Google Cloud Storage and S3.
https://www.mlflow.org/docs/latest/tracking.html#where-runs-are-recorded

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

## Details

We can use naively GCSFuse to mount the GCS contents on our local files, but it can cause conflicts.

**Comment by AveshCSingh** [comment]
Hi @Matts966 , thanks for filing this feature request. The file store is quite limited in functionality compared to the database backends. For example, it does not support the model registry. It is also generally not as performant.

For this reason, I would expect that most users who need runs to be stored on a cloud service would be best served by using a database backend. And as you point out, running the FileStore from a file system accessed by multiple users (eg GCS) can cause conflicts.  Avoiding these conflicts involves a non-trivial amount of work.

I'm closing this issue for now, but please feel free to re-open it if I'm overlooking something.
