### ISSUE TITLE
[BUG] MLflow UI doesn't update artifacts, that were reuploaded

### ISSUE THREAD

**Issue by maxim1317** [mlflow/mlflow#3441]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md) for additional information about bug reports. For help with debugging your code, please refer to [Stack Overflow](https://stackoverflow.com/questions/tagged/mlflow).

**Please fill in this bug report template to ensure a timely and thorough response.**

### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [x] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **MLflow installed from (source or binary)**: source
- **MLflow version (run ``mlflow --version``)**: 1.11.0
- **Python version**: 3.7
- **npm version, if running the dev UI**:
- **Exact command to reproduce**:

### Describe the problem

I am training a pytorch model, so I want to save last and best checkpoints (saving every checkpoint is too space costly). I save checkpoints with `mlflow.log_model("<local_path>/best.pth", "checkpoints/best")`. So, idea was to rewrite an existing artifact with new one to save space, but MLflow UI shows the first version of artifact. I'm using minio s3 as an artifact storage. And through minio I can receive the last version.   

### Code to reproduce issue

```python
with open('test.txt', 'w') as test_file:
  test_file.write('1')
mlflow.log_artifact('test.txt', 'test')
with open('test.txt', 'w') as test_file:
  test_file.write('2')
mlflow.log_artifact('test.txt', 'test')
```

### Other info / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [x] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [x] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dmatrix** [comment]
@maxim1317 Thanks for filling this issue.

I tried using [your example](https://github.com/dmatrix/mlflow-tests/blob/master/py/mlflow/mlflow_issues/issue_3441.py), with additional parameters,  on my localhost, and the MLflow shows the last version logged.

![Screen Shot 2020-09-21 at 9 35 11 AM](https://user-images.githubusercontent.com/1117597/93795239-f4bbf100-fbed-11ea-8a0b-d307df608ac8.png)

**Comment by maxim1317** [comment]
@dmatrix

Yeah, I should correct myself

I ran more tests today and the problem seems due to the caching in the browser.

After I look once at the file in mlflow ui, the file in ui doesn't update anymore.

It helps if I reset the cache, though

**Comment by dmatrix** [comment]
@maxim1317 Thanks for the clarification. Do you still think this is an MLflow UI problem than the browser not updating the cache?
If so can we close this issue?

**Comment by maxim1317** [comment]
@dmatrix I think you can

But maybe, when user clicks "download" button in UI, MLflow should send the file from storage, not a cached version

**Comment by dmatrix** [comment]
Okay, will close it with a note to the UI/UX engineer of this anomaly.

cc: @Zangr
