### ISSUE TITLE
[FR] tracking event callbacks for external observers in R interface of mlflow

### ISSUE THREAD

**Issue by yitao-li** [mlflow/mlflow#3494]
## Willingness to contribute
The MLflow Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature (either as an MLflow Plugin or an enhancement to the MLflow code base)?

- [x] Yes. I can contribute this feature independently.
- [ ] Yes. I would be willing to contribute this feature with guidance from the MLflow community.
- [ ] No. I cannot contribute this feature at this time.

## Proposal Summary

It would be great if the R interface of `mlflow` can provide optional generic callbacks for informing an external observer of tracking events such as setting active run ID, setting active experiment ID, logging metric, etc. If there is no external observer present, then no additional callback will be run.

## Motivation
- What is the use case for this feature?
IDE extensions can act as external observers receiving those callbacks. Users will be able to see current and past experiments and metric associated with them from an external IDE, which will be helpful during development.

- Why is this use case valuable to support for MLflow users in general?
It will be useful for users who run non-trivial number of experiments to have a hierarchical view of runs and experiments in an integrated development environment via an IDE extension.
  
- Why is this use case valuable to support for your project(s) or organization?
Having an integrated view of ongoing and past MLFlow experiments would greatly improve user experience for IDE users.

- Why is it currently difficult to achieve this use case? (please be as specific as possible about why related MLflow features and components are insufficient)
I don't think there is any existing construct in the R code base of MLflow that can be customized to optionally keep an external observer up-to-date with tracking events such as `set_active_run_id` or `set_active_experiment_id`, so, a small amount of code change is needed for this to happen.

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [x] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

## Details

It can be as simple as the following (I shall use `mlflow_set_active_experiment_id()` as an example):

```
mlflow_set_active_experiment_id <- function(experiment_id) {
  <code for updating active experiment ID globally>

  on_active_experiment_id(experiment_id)
}

on_active_experiment_id <- function(experiment_id) {
  observer <- getOption("MLFlowExternalObserver")
  if (!is.null(observer)) {
    # inform an external observer of the experiment id
    tryCatch({
      observer$set_active_experiment_id(experiment_id)
    }, error = function(e) {
      # we can log the error in some way, but there is not much else we can do here
    })
  } # otherwise there is no external observer, and no callback is run
}
```

Any such callback should return instantaneously, and if there is any operation that could be blocking or taking non-trivial amount of time, then such operation will need to be completed asynchronously rather than being executed inline within the callback.

Also, the user has complete control over whether such callbacks are run or not (by enabling or disabling IDE extensions that will act as observers).

**Comment by yitao-li** [comment]
cc @javierluraschi

**Comment by yitao-li** [comment]
@smurching @lorenzwalthert Please let me know what you think of this proposal. This is my first time creating a feature request for mlflow btw :slightly_smiling_face: 

I plan to work on this soon assuming the proposal makes sense. It should be fairly small coding-wise.

**Comment by lorenzwalthert** [comment]
Looks interesting, but I am not sure I fully understand the end goal of it. I also wonder if something similar should be implemented for Python and ergo if a native R implementation is desirable.

**Comment by yitao-li** [comment]
@lorenzwalthert One goal at the moment is to eventually have a plugin for RStudio IDE that can at least help people visualize all the MLflow experiments they are running, and possibly more. Same should be done for Python as well if we foresee any IDE plugin implemented in Python that will benefit from those optional callbacks.

**Comment by lorenzwalthert** [comment]
Ok, thanks for the explanation.

**Comment by javierluraschi** [comment]
Feature looks good to me, is mostly a developer event hook for package authors. Will comment in PR.

**Comment by lorenzwalthert** [comment]
@yitao-li I think this is closed with #3501? If you use the *closes* keyword in the description of the PR, the issue will close automatically on merge.
