### ISSUE TITLE
[FR] Should be able to create & manage nested runs in R

### ISSUE THREAD

**Issue by tnixon** [mlflow/mlflow#3537]
Thank you for submitting a feature request. **Before proceeding, please review MLflow's [Issue Policy for feature requests](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md#feature-requests) and the [MLflow Contributing Guide](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst)**.

**Please fill in this feature request template to ensure a timely and thorough response.**

## Willingness to contribute
The MLflow Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature (either as an MLflow Plugin or an enhancement to the MLflow code base)?

- [ ] Yes. I can contribute this feature independently.
- [X] Yes. I would be willing to contribute this feature with guidance from the MLflow community.
- [ ] No. I cannot contribute this feature at this time.

## Proposal Summary

The R API should allow for the creation & usage of nested runs similar to how it works in Python.

## Motivation
Nested runs are a crucial feature for organizing complex experimental runs (such as hyper-parameter tuning experiments) within the tracking service. Currently this is not possible in R because the R API does not expose these options as it does in Python.

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [X] `area/docs`: MLflow documentation pages
- [X] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [X] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

## Details

I have no specific thoughts on implementation at this point, except that it should bring the R API up to par with the Python API for creating and managing nested runs. I am happy to work on implementing this with any guidance from existing MLFlow contributors.

**Comment by dmatrix** [comment]
@tnixon Thanks for FR request and your desire to contribute. This could be a good contribution for nested runs. 

I'll let our R contributors comment and guide you.

cc: @lorenzwalthert @javierluraschi Please suggest as necessary for Tristan's contribution.

**Comment by yitao-li** [comment]
I haven't looked into the specifics of "nested run" yet (and would appreciate some pointers on what it actually entails).
I think in general it's a good idea to ensure the `mlflow` R package have feature parity with the Python client, so that people using mlflow won't find themselves missing some capabilities because they work with R instead of Python.

**Comment by lorenzwalthert** [comment]
@yitao-li I think it's as the word says, it's a run within a run. So you can make a run for hyper-parameter search and evaluate different hyper-parameters within that run. Right @tnixon? 
* A quick search in the repo for 'nested' yields a few examples where nested runs are showcased in Python: https://github.com/mlflow/mlflow/blob/d743a40426d5dedbde395a4e6bbdeebadbccd4dc/examples/hyperparam/search_random.py. Maybe it's worth running this example and check the GUI how it looks.
* The [Python API](https://mlflow.org/docs/latest/python_api/mlflow.html#mlflow.start_run) has just an additional parameter `nested`. If `False`, I assume it creates a new, separate run, if `True`, it creates a nested run under the current run.

**Comment by lorenzwalthert** [comment]
It looks like in Python, the only thing in [`mlflow.start_run()`](https://github.com/mlflow/mlflow/blob/fff240c6430a216849286052f88442c64180a3f6/mlflow/tracking/fluent.py#L161) does is a runtime check  if `nested = False`, there is no current run. Also, the REST API for [creating a run](https://mlflow.org/docs/latest/rest-api.html#create-run) does not expose a `nested` argument.

**Comment by tnixon** [comment]
Yes, @lorenzwalthert - that's the primary use I've seen for nested runs: so that you can organize hyper-parameter search experiments as trials of many sub-runs within a single parent-run.

I suppose that there are other possible use cases, but I haven't seen them yet.

**Comment by lorenzwalthert** [comment]
@tnixon did you get a chance to play around?

**Comment by yitao-li** [comment]
@tnixon So looks like the `nested` argument is purely for book-keeping and sanity-check on client side. Client cannot accidentally create a nested-run unless they explicitly set `nested` to true. The nested run then get stacked on top of the parent run (as in the child run becomes the active run, and the active run ID reverts back to parent once the child run completes). My PR ensures the MLflow R client performs the same type of client-side book-keeping the MLflow Python client does.

@dmatrix I think https://github.com/mlflow/mlflow/issues/3537 implements precisely what's described here. Could you please close this issue?

**Comment by tnixon** [comment]
@yitao-li - thanks for making these changes, this is great!
