### ISSUE TITLE
[BUG] keras 2.4.X autolog - AttributeError: module 'keras.callbacks' has no attribute 'callbacks'

### ISSUE THREAD

**Issue by sephib** [mlflow/mlflow#3571]
### Willingness to contribute
- [x] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:  no - just using the [tests/keras_autolog.py](https://github.com/mlflow/mlflow/blob/master/tests/keras_autolog/test_keras_autolog.py)
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux OpenSuSE 15.1
- **MLflow installed from (source or binary)**:  from dev with upgrade of `tensorflow` and `keras`
- **MLflow version (run ``mlflow --version``)**: 1.11.0
- **Python version**: 3.6.11 (also checked on 3.7)
- **Exact command to reproduce**:  
>pytest tests/keras_autolog --large --ignore-flavors --ignore=tests/examples

### Describe the problem
When running with:
>tensorflow 2.3.1
>keras 2.4.3   

the keras_autolog() fails with an error 
> AttributeError: module 'keras.callbacks' has no attribute 'callbacks'

### Code to reproduce issue
> pytest tests/keras_autolog --large --ignore-flavors --ignore=tests/examples

### Other info / logs

A work around can be done by [commenting out the if statement in keras.py](https://github.com/mlflow/mlflow/blob/master/mlflow/keras.py#L610:L613)  ,  this allows for most test to pass.

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [x] `area/artifacts`: Artifact stores and artifact logging
- [X] `area/projects`: MLproject format, project running backends
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

**Comment by harupy** [comment]
@sephib Thanks for reporthing this. Looks like we need to fix the if condition.

```
        if LooseVersion(keras.__version__) < LooseVersion("2.3.0") or LooseVersion(keras.__version__) >  LooseVersion("2.4.0"):
            es_callback = keras.callbacks.EarlyStopping
        else:
            es_callback = keras.callbacks.callbacks.EarlyStopping
```

**Comment by sephib** [comment]
Please let me know if you want me to submit a PR

**Comment by dbczumar** [comment]
@sephib That would be very helpful! Thank you!
