### ISSUE TITLE
[BUG] Unable to Register Custom Python Model Creme

### ISSUE THREAD

**Issue by r-maheshh** [mlflow/mlflow#3572]
### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [X] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
- **OS Platform and Distribution**: MacOS 10.15.5
- **MLflow installed from (source or binary)**: source
- **MLflow version (run ``mlflow --version``)**: version 1.11.0
- **Python version**: 3.7.4
- **npm version, if running the dev UI**:
- **Exact command to reproduce**:

mlflow.pyfunc.log_model("model", python_model= model)

### Describe the problem
I would like to train register a custom Python model. I have an incremental learning model from Python library Creme trained, but am unable to register this model with MLFlow.

### Code to reproduce issue

```
from creme import datasets, linear_model, metrics, optim, preprocessing, stream, compose, feature_extraction
from creme import compose, feature_extraction, model_selection, stats, ensemble, tree, compat
from creme.base import MultiClassifier
from creme import neighbors
from creme import compose
from creme import linear_model
from creme import metrics
from creme import multiclass
from creme import preprocessing
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn import datasets
import mlflow.sklearn
import mlflow
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

iris = datasets.load_iris()
X = pd.DataFrame(iris.data, columns=['C1', 'C2', 'C3', 'C4'])
X['Target'] = iris.target
y = X['Target']
del X['Target']

mlflow.end_run()
mlflow.set_tracking_uri("http://localhost:5000")
mlflow.set_experiment("path")


creme_data = X.to_dict(orient='records')
model = neighbors.KNeighborsClassifier(n_neighbors=3)
with mlflow.start_run():
    model_selection.progressive_val_score(
        X_y=zip(creme_data, y.values),
        model=model,
        metric=metrics.Accuracy(),
        print_every=1)
mlflow.pyfunc.log_model("model", python_model= model)
```

### Other info / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [X] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [X] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@r-maheshh Have you tried `mlflow.sklearn.log_model`?

**Comment by harupy** [comment]
@r-maheshh If you want to just log a model, you can use the sklearn flavor:

```python
import creme
from creme import (
    datasets,
    linear_model,
    metrics,
    optim,
    preprocessing,
    stream,
    compose,
    feature_extraction,
)
from creme import compose, feature_extraction, model_selection, stats, ensemble, tree, compat
from creme.base import MultiClassifier
from creme import neighbors
from creme import compose
from creme import linear_model
from creme import metrics
from creme import multiclass
from creme import preprocessing
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn import datasets
import mlflow.sklearn
import mlflow
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

iris = datasets.load_iris()
X = pd.DataFrame(iris.data, columns=["C1", "C2", "C3", "C4"])
X["Target"] = iris.target
y = X["Target"]
del X["Target"]


creme_data = X.to_dict(orient="records")
model = neighbors.KNeighborsClassifier(n_neighbors=3)
with mlflow.start_run():
    model_selection.progressive_val_score(
        X_y=zip(creme_data, y.values), model=model, metric=metrics.Accuracy(), print_every=1
    )
    
   ########## new lines ##########
    conda_env = mlflow.sklearn.get_default_conda_env()
    conda_env["creme"] = creme.__version__
    mlflow.sklearn.log_model(model, "model", conda_env=conda_env)
    model_uri = mlflow.get_artifact_uri("model")
    loaded_model = mlflow.sklearn.load_model(model_uri)
    p = loaded_model.predict_proba_one(X.iloc[0, :])
    print(p)

```

**Comment by r-maheshh** [comment]
Hello,

Thanks for getting back. I commented out "conda_env["creme"] = creme.__version__" and that seemed to do the trick. For some reason, the model is not showing up in the artifacts. I would like to register this model locally.

**Comment by harupy** [comment]
@r-maheshh Can you print out `model_uri` and see what it points to?

**Comment by dbczumar** [comment]
Closing this for now, as logging with the scikit-learn flavor appears to work. Additionally, there are instructions for saving arbitrary models in MLflow Model format here: https://mlflow.org/docs/latest/models.html#model-customization.
