### ISSUE TITLE
[BUG] mlflow.sklearn.autolog requires matplotlib

### ISSUE THREAD

**Issue by akshaya-a** [mlflow/mlflow#3702]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md) for additional information about bug reports. For help with debugging your code, please refer to [Stack Overflow](https://stackoverflow.com/questions/tagged/mlflow).

**Please fill in this bug report template to ensure a timely and thorough response.**

### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [x] Yes. I can contribute a fix for this bug independently.
- [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **MLflow installed from (source or binary)**: PyPI
- **MLflow version (run ``mlflow --version``)**: 1.12.0
- **Python version**: 3.6.12
- **npm version, if running the dev UI**:
- **Exact command to reproduce**:

### Describe the problem
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-5-5ead679a03fc> in <module>
      1 import mlflow.sklearn
----> 2 mlflow.sklearn.autolog()

/anaconda/envs/autosklearn/lib/python3.6/site-packages/mlflow/sklearn/__init__.py in autolog(log_input_examples, log_model_signatures)
    710 
    711     from mlflow.models import infer_signature
--> 712     from mlflow.sklearn.utils import (
    713         _MIN_SKLEARN_VERSION,
    714         _is_supported_version,

/anaconda/envs/autosklearn/lib/python3.6/site-packages/mlflow/sklearn/utils.py in <module>
      5 import logging
      6 from numbers import Number
----> 7 import matplotlib.pyplot as plt
      8 import numpy as np
      9 import time

ModuleNotFoundError: No module named 'matplotlib'

### Code to reproduce issue
execute sklearn autolog in a clean environment with only mlflow + sklearn

### Other info / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by akshaya-a** [comment]
@dbczumar @eedeleon   I assumed we could make this a caught exception to degrade the autologging to functionality present in the environment, but open to ideas

**Comment by dbczumar** [comment]
@akshaya-a I've filed https://github.com/mlflow/mlflow/pull/3703; this implements the caught exception approach you've suggested. In the context of a skinny client, we should identify a test plan for autologging / models integrations. It seems valuable to have the skinny client tests install the target ML library and run these suites, which will help to tease out dependency gaps like this.
