### ISSUE TITLE
[BUG] Yaml file '/Path/to/mymodel/meta.yaml' does not exist.

### ISSUE THREAD

**Issue by yodagast** [mlflow/mlflow#3755]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS
- **MLflow version (run ``mlflow --version``)**:  mlflow, version 1.9.1
- **Python version**: 3.9

### Describe the problem
I save my model and run MLflow UI like this
'''
    mlflow.set_tracking_uri("file:/models")
    mlflow.xgboost.autolog()
    mlflow.set_experiment("model")
    ……
    mlflow.xgboost.save_model(model,"./models/mymodel-%s" % run_name)
    mlflow.xgboost.log_model(model,artifact_path='1')
'''
then I get error

Traceback (most recent call last):
  File "/Users/anaconda3/lib/python3.7/site-packages/mlflow/store/tracking/file_store.py", line 197, in list_experiments
    experiment = self._get_experiment(exp_id, view_type)
  File "/Users/anaconda3/lib/python3.7/site-packages/mlflow/store/tracking/file_store.py", line 260, in _get_experiment
    meta = read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
  File "/Users/anaconda3/lib/python3.7/site-packages/mlflow/utils/file_utils.py", line 167, in read_yaml
    raise MissingConfigException("Yaml file '%s' does not exist." % file_path)
mlflow.exceptions.MissingConfigException: Yaml file '/Path/to/mymodel/meta.yaml' does not exist.
Malformed experiment 'mymodel'. Detailed error Yaml file 

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
Language 
- [ ] `language/python`: Proposals for new client languages

**Comment by ismael-marcos** [comment]
Did you find a solution to this? I am experiencing that too

**Comment by gloryVine** [comment]
Same problem, also on macOS. Super annoying and distracting.

**Comment by ricardoTegao** [comment]
Some solution?????

**Comment by ricardoTegao** [comment]
I had the same issue, and after many hours, I found this link and every thing works well.
https://stackoverflow.com/questions/63255631/mlflow-invalid-parameter-value-unsupported-uri-mlruns-for-model-registry-s

**Comment by irudayambics** [comment]
I faced the same issue and below solution worked for me. 

MLFLOW_TRACKING_URI environment variable was set and rerun the command. Everything worked fine.

**Comment by kolhesamiksha** [comment]
@irudayambics, Thanks it was super helpful.. By setting os.environ['MLFLOW_TRACKING_URI'] in the file where you're loading & setting your model.

**Comment by jaswanth333** [comment]
> I faced the same issue and below solution worked for me.
> 
> MLFLOW_TRACKING_URI environment variable was set and rerun the command. Everything worked fine.

Thanks, it worked.
