### ISSUE TITLE
[BUG] No index on foreign keys, in postgres store

### ISSUE THREAD

**Issue by ludaavics** [mlflow/mlflow#3785]
## MLflow Roadmap Item

This is an MLflow Roadmap item that has been prioritized by the MLflow maintainers. We're seeking help with the implementation of roadmap items tagged with the `help wanted` label.

For requirements clarifications and implementation questions, or to request a PR review, please tag @WeichenXu123 in your communications related to this issue.

### System information
- Linux Ubuntu 18.04
- MLflow installed from pip
- MLFlow version 1.11:
- Python version 3.8.3

### Describe the problem
This might not be true for other dialects, but Postgres doesn't automatically index on FKs. It makes something as simple as querying all run details extremely slow, as the number of experiments / runs (the UI only allows to fetch results 100 at  time).

### Code to reproduce issue
The following has about 10k rows but essentially times out.
```
SELECT * 
FROM runs
JOIN params on params.run_uuid = runs.run_uuid
JOIN metrics on metrics.run_uuid = params.run_uuid
WHERE runs.experiment_id = 30
```

### Other info / logs
Query to get all the missing FKs ([credit](https://www.cybertec-postgresql.com/en/index-your-foreign-key/))
```
SELECT c.conrelid::regclass AS "table",
       /* list of key column names in order */
       string_agg(a.attname, ',' ORDER BY x.n) AS columns,
       pg_catalog.pg_size_pretty(
          pg_catalog.pg_relation_size(c.conrelid)
       ) AS size,
       c.conname AS constraint,
       c.confrelid::regclass AS referenced_table
FROM pg_catalog.pg_constraint c
   /* enumerated key column numbers per foreign key */
   CROSS JOIN LATERAL
      unnest(c.conkey) WITH ORDINALITY AS x(attnum, n)
   /* name for each key column */
   JOIN pg_catalog.pg_attribute a
      ON a.attnum = x.attnum
         AND a.attrelid = c.conrelid
WHERE NOT EXISTS
        /* is there a matching index for the constraint? */
        (SELECT 1 FROM pg_catalog.pg_index i
         WHERE i.indrelid = c.conrelid
           /* the first index columns must be the same as the
              key columns, but order doesn't matter */
           AND (i.indkey::smallint[])[0:cardinality(c.conkey)-1]
               OPERATOR(pg_catalog.@>) c.conkey)
  AND c.contype = 'f'
GROUP BY c.conrelid, c.conname, c.confrelid
ORDER BY pg_catalog.pg_relation_size(c.conrelid) DESC;
```

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [ x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by ludaavics** [comment]
Looking at the db model a bit more closely, i realized metrics and runs are stored as key-value pairs; that, rather then missing indices, is probably the reason why my query blows up.

Still adding indices may still make sense -- let me know what you think.

**Comment by dmatrix** [comment]
@mparkhe Any comment on this issue regarding no indexing on foreign keys, in particular w.r.t Postgres?

**Comment by mberr** [comment]
@ludaavics maybe related: https://github.com/mlflow/mlflow/issues/3334 I had a similar performance issue with postgres backend and could improve it by manually adding an index.

It would be nice to have it automatically done by MLFlow though.

**Comment by huxuan** [comment]
Hi @WeichenXu123 , according to [1], it might be quite easy to fix the problem. But I wonder if there is anything else we should think of? For example, performance tests or whatever. 

[1] https://stackoverflow.com/questions/8890738/sqlalchemy-does-column-with-foreignkey-creates-index-automatically

**Comment by WeichenXu123** [comment]
@huxuan 

Thanks!
Yes, I think we need a performance test to confirm it address the issue, and need a db migration script to upgrade existing mlflow database

**Comment by WeichenXu123** [comment]
@huxuan 

The db migration scirpt can be generated by alembic tool, see https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst#database-schema-changes

**Comment by huxuan** [comment]
@WeichenXu123 Thanks for the reply. If possible, I may have a try on it.

BTW, is there any reference I can refer to for the performance test?

**Comment by dbczumar** [comment]
Hi @huxuan , apologies for the delay. I think the example discussed in the issue description will be helpful for performance testing:

```
SELECT * 
FROM runs
JOIN params on params.run_uuid = runs.run_uuid
JOIN metrics on metrics.run_uuid = params.run_uuid
WHERE runs.experiment_id = 30
```

We can try to create 10,000 runs with a few (e.g. 5) metrics & parameters each, then attempt to run the query above.

Thank you in advance for your contribution!

**Comment by NieuweNils** [comment]
Hi @ludaavics, @dbczumar , is this stil an open issue? I ould gladlylook into this if so!

**Comment by dbczumar** [comment]
Hi @NieuweNils ! Yes, this is till open. We'd really appreciate your help with it!

**Comment by huxuan** [comment]
Hi, @NieuweNils & @dbczumar, I can confirm I may not have sufficient load on this issue, so feel free to take it! Recently, I was busy working on integrating mlflow with the infrastructure of my team, writing various plugins for the training platform, evaluation platform, model management platform and so on mostly build by ourselves previously. I really appreciate the flexibility of mlflow that makes it possible to happen. I will absolutely come back after meeting the committed work.

**Comment by NieuweNils** [comment]
Great to hear I can help out! I'll start looking into it

**Comment by WeichenXu123** [comment]
Thanks @NieuweNils 's help! I will help review.

**Comment by harupy** [comment]
Query plan comparison:

### Without index:

```
| QUERY PLAN                                                                       |
| :------------------------------------------------------------------------------- |
| Nested Loop (cost=10.53..24.78 rows=8 width=4193)                                |
| -> Hash Join (cost=10.39..21.28 rows=2 width=3570)                               |
| Hash Cond: ((params.run_uuid)::text = (runs.run_uuid)::text)                     |
| -> Seq Scan on params (cost=0.00..10.70 rows=70 width=1114)                      |
| -> Hash (cost=10.38..10.38 rows=1 width=2456)                                    |
| -> Seq Scan on runs (cost=0.00..10.38 rows=1 width=2456)                         |
| Filter: (experiment_id = 0)                                                      |
| -> Index Only Scan using metric_pk on metrics (cost=0.14..1.74 rows=1 width=623) |
| Index Cond: (run_uuid = (params.run_uuid)::text)                                 |
```

### With index:

```
| QUERY PLAN                                                                               |
| :--------------------------------------------------------------------------------------- |
| Nested Loop (cost=0.29..20.26 rows=8 width=4193)                                         |
| -> Nested Loop (cost=0.14..18.54 rows=2 width=3570)                                      |
| -> Seq Scan on runs (cost=0.00..10.38 rows=1 width=2456)                                 |
| Filter: (experiment_id = 0)                                                              |
| -> Index Scan using params_run_uuid_index on params (cost=0.14..8.16 rows=1 width=1114)  |
| Index Cond: ((run_uuid)::text = (runs.run_uuid)::text)                                   |
| -> Index Scan using metrics_run_uuid_index on metrics (cost=0.14..0.85 rows=1 width=623) |
| Index Cond: ((run_uuid)::text = (params.run_uuid)::text)                                 |
```

**Comment by harupy** [comment]
Results of `EXPLAIN ANALYZE`:

```sql
SELECT * 
FROM runs
JOIN params on params.run_uuid = runs.run_uuid
JOIN metrics on metrics.run_uuid = params.run_uuid
WHERE runs.experiment_id = 0
```

### Without index

```
| QUERY PLAN                                                                                                                      |
|:--------------------------------------------------------------------------------------------------------------------------------|
| Hash Join  (cost=3349.49..293512.97 rows=25490308 width=243) (actual time=95.036..4505.088 rows=25000000 loops=1)               |
|   Hash Cond: ((params.run_uuid)::text = (runs.run_uuid)::text)                                                                  |
|   ->  Seq Scan on params  (cost=0.00..966.96 rows=49996 width=41) (actual time=0.009..3.200 rows=50000 loops=1)                 |
|   ->  Hash  (cost=1308.93..1308.93 rows=49965 width=202) (actual time=94.799..94.800 rows=50000 loops=1)                        |
|         Buckets: 32768  Batches: 4  Memory Usage: 3643kB                                                                        |
|         ->  Hash Join  (cost=5.45..1308.93 rows=49965 width=202) (actual time=56.861..73.589 rows=50000 loops=1)                |
|               Hash Cond: ((metrics.run_uuid)::text = (runs.run_uuid)::text)                                                     |
|               ->  Seq Scan on metrics  (cost=0.00..1166.65 rows=49965 width=63) (actual time=56.802..63.003 rows=50000 loops=1) |
|               ->  Hash  (cost=4.22..4.22 rows=98 width=139) (actual time=0.048..0.049 rows=100 loops=1)                         |
|                     Buckets: 1024  Batches: 1  Memory Usage: 26kB                                                               |
|                     ->  Seq Scan on runs  (cost=0.00..4.22 rows=98 width=139) (actual time=0.014..0.037 rows=100 loops=1)       |
|                           Filter: (experiment_id = 0)                                                                           |
| Planning Time: 0.873 ms                                                                                                         |
| JIT:                                                                                                                            |
|   Functions: 20                                                                                                                 |
|   Options: Inlining false, Optimization false, Expressions true, Deforming true                                                 |
|   Timing: Generation 1.459 ms, Inlining 0.000 ms, Optimization 8.401 ms, Emission 46.351 ms, Total 56.211 ms                    |
| Execution Time: 5160.198 ms                                                                                                     |
```

### With index

```
| QUERY PLAN                                                                                                                      |
|:--------------------------------------------------------------------------------------------------------------------------------|
| Hash Join  (cost=3349.62..293538.60 rows=25492858 width=243) (actual time=53.989..4580.449 rows=25000000 loops=1)               |
|   Hash Cond: ((params.run_uuid)::text = (runs.run_uuid)::text)                                                                  |
|   ->  Seq Scan on params  (cost=0.00..966.96 rows=49996 width=41) (actual time=0.007..3.243 rows=50000 loops=1)                 |
|   ->  Hash  (cost=1308.99..1308.99 rows=49970 width=202) (actual time=53.479..53.481 rows=50000 loops=1)                        |
|         Buckets: 32768  Batches: 4  Memory Usage: 3893kB                                                                        |
|         ->  Hash Join  (cost=5.45..1308.99 rows=49970 width=202) (actual time=13.144..31.013 rows=50000 loops=1)                |
|               Hash Cond: ((metrics.run_uuid)::text = (runs.run_uuid)::text)                                                     |
|               ->  Seq Scan on metrics  (cost=0.00..1166.70 rows=49970 width=63) (actual time=13.084..20.093 rows=50000 loops=1) |
|               ->  Hash  (cost=4.22..4.22 rows=98 width=139) (actual time=0.049..0.050 rows=100 loops=1)                         |
|                     Buckets: 1024  Batches: 1  Memory Usage: 26kB                                                               |
|                     ->  Seq Scan on runs  (cost=0.00..4.22 rows=98 width=139) (actual time=0.011..0.037 rows=100 loops=1)       |
|                           Filter: (experiment_id = 0)                                                                           |
| Planning Time: 0.802 ms                                                                                                         |
| JIT:                                                                                                                            |
|   Functions: 20                                                                                                                 |
|   Options: Inlining false, Optimization false, Expressions true, Deforming true                                                 |
|   Timing: Generation 1.492 ms, Inlining 0.000 ms, Optimization 0.630 ms, Emission 12.247 ms, Total 14.368 ms                    |
| Execution Time: 5166.073 ms                                                                                                     |
```

**Comment by harupy** [comment]
@mberr Thanks for the comment. I think I forgot to update the database schema. Here's the new result.

### Without index

```
| QUERY PLAN                                                                                                                 |
|:---------------------------------------------------------------------------------------------------------------------------|
| Hash Join  (cost=80.11..182.10 rows=348 width=4193) (actual time=1.750..4.820 rows=10000 loops=1)                          |
|   Hash Cond: ((metrics.run_uuid)::text = (params.run_uuid)::text)                                                          |
|   ->  Seq Scan on metrics  (cost=0.00..97.44 rows=1044 width=623) (actual time=0.013..0.880 rows=5000 loops=1)             |
|   ->  Hash  (cost=79.96..79.96 rows=12 width=3570) (actual time=1.726..1.728 rows=1000 loops=1)                            |
|         Buckets: 1024  Batches: 1  Memory Usage: 253kB                                                                     |
|         ->  Hash Join  (cost=12.46..79.96 rows=12 width=3570) (actual time=0.213..1.346 rows=1000 loops=1)                 |
|               Hash Cond: ((params.run_uuid)::text = (runs.run_uuid)::text)                                                 |
|               ->  Seq Scan on params  (cost=0.00..66.34 rows=434 width=1114) (actual time=0.004..0.493 rows=5000 loops=1)  |
|               ->  Hash  (cost=12.45..12.45 rows=1 width=2456) (actual time=0.198..0.199 rows=100 loops=1)                  |
|                     Buckets: 1024  Batches: 1  Memory Usage: 26kB                                                          |
|                     ->  Seq Scan on runs  (cost=0.00..12.45 rows=1 width=2456) (actual time=0.013..0.180 rows=100 loops=1) |
|                           Filter: (experiment_id = 0)                                                                      |
|                           Rows Removed by Filter: 400                                                                      |
| Planning Time: 0.564 ms                                                                                                    |
| Execution Time: 5.104 ms                                                                                                   |
```

### With index


```
| QUERY PLAN                                                                                                                                  |
|:--------------------------------------------------------------------------------------------------------------------------------------------|
| Nested Loop  (cost=4.57..39.63 rows=348 width=4193) (actual time=0.044..4.482 rows=10000 loops=1)                                           |
|   ->  Nested Loop  (cost=4.29..23.71 rows=12 width=3570) (actual time=0.032..0.696 rows=1000 loops=1)                                       |
|         ->  Seq Scan on runs  (cost=0.00..12.45 rows=1 width=2456) (actual time=0.015..0.132 rows=100 loops=1)                              |
|               Filter: (experiment_id = 0)                                                                                                   |
|               Rows Removed by Filter: 400                                                                                                   |
|         ->  Bitmap Heap Scan on params  (cost=4.29..11.24 rows=2 width=1114) (actual time=0.003..0.004 rows=10 loops=100)                   |
|               Recheck Cond: ((run_uuid)::text = (runs.run_uuid)::text)                                                                      |
|               Heap Blocks: exact=111                                                                                                        |
|               ->  Bitmap Index Scan on params_run_uuid_index  (cost=0.00..4.29 rows=2 width=0) (actual time=0.002..0.002 rows=10 loops=100) |
|                     Index Cond: ((run_uuid)::text = (runs.run_uuid)::text)                                                                  |
|   ->  Index Scan using metrics_run_uuid_index on metrics  (cost=0.28..1.28 rows=5 width=623) (actual time=0.001..0.003 rows=10 loops=1000)  |
|         Index Cond: ((run_uuid)::text = (params.run_uuid)::text)                                                                            |
| Planning Time: 0.615 ms                                                                                                                     |
| Execution Time: 4.736 ms                                                                                                                    |
```

**Comment by mberr** [comment]
I am dealing with a larger mlflow instance with around 30GiB of metrics.

```
                                     List of relations
 Schema |             Name              |   Type   |    Owner    |    Size    | Description 
--------+-------------------------------+----------+-------------+------------+-------------
 public | alembic_version               | table    | mlflow_user | 40 kB      | 
 public | experiment_tags               | table    | mlflow_user | 8192 bytes | 
 public | experiments                   | table    | mlflow_user | 48 kB      | 
 public | experiments_experiment_id_seq | sequence | mlflow_user | 8192 bytes | 
 public | latest_metrics                | table    | mlflow_user | 72 MB      | 
 public | metrics                       | table    | mlflow_user | 33 GB      | 
 public | model_version_tags            | table    | mlflow_user | 8192 bytes | 
 public | model_versions                | table    | mlflow_user | 8192 bytes | 
 public | params                        | table    | mlflow_user | 32 MB      | 
 public | registered_model_tags         | table    | mlflow_user | 8192 bytes | 
 public | registered_models             | table    | mlflow_user | 8192 bytes | 
 public | runs                          | table    | mlflow_user | 1984 kB    | 
 public | tags                          | table    | mlflow_user | 3576 kB    | 
```

I investigated two different index options, a default (B-tree) index on `metrics(run_uuid)` (called `metrics_run_uuid_idx`), as well as a hash index thereupon (called `metrics_run_uuid_idx1`). I benchmarked the same query as you did before, wrapped in the following snippet
```sql
begin;  -- wrap in begin; rollback to avoid actually deleting the indexes
drop index metrics_run_uuid_idx1;  -- comment out to keep
drop index metrics_run_uuid_idx;   -- comment out to keep
EXPLAIN ANALYZE

SELECT * 
FROM runs
JOIN params on params.run_uuid = runs.run_uuid
JOIN metrics on metrics.run_uuid = params.run_uuid
WHERE runs.experiment_id = 0;
rollback;
```

| b-tree index | hash index | execution time |
| -- | -- | --: |
| yes | yes | 1941.740 ms | 
| no | yes | 369.510 ms | 
| yes | no | 409.373 ms | 
| no | no | 296262.784 ms | 

_disclaimer: since I did not have these indexes in production, and did not often run the given query, the query optimizer might not have all statistics to make good decisions for the query execution plan._

<summary>Full Output</summary>
<details>

both indexes
```
                                                                         QUERY PLAN                                                                         
------------------------------------------------------------------------------------------------------------------------------------------------------------
 Hash Join  (cost=16594.42..584889.96 rows=2909817 width=316) (actual time=1906.860..1910.963 rows=0 loops=1)
   Hash Cond: ((runs.run_uuid)::text = (params.run_uuid)::text)
   ->  Gather Merge  (cost=1000.29..521121.30 rows=67670 width=250) (actual time=1906.859..1910.959 rows=0 loops=1)
         Workers Planned: 1
         Workers Launched: 1
         ->  Nested Loop  (cost=0.28..512508.41 rows=39806 width=250) (actual time=1873.318..1873.320 rows=0 loops=2)
               ->  Parallel Index Scan using run_pk on runs  (cost=0.28..27877.07 rows=1 width=163) (actual time=1710.378..1861.713 rows=2 loops=2)
                     Filter: (experiment_id = 0)
                     Rows Removed by Filter: 4204
               ->  Index Scan using metrics_run_uuid_idx1 on metrics  (cost=0.00..483401.77 rows=122958 width=87) (actual time=7.712..7.712 rows=0 loops=3)
                     Index Cond: ((run_uuid)::text = (runs.run_uuid)::text)
   ->  Hash  (cost=7437.61..7437.61 rows=336761 width=66) (never executed)
         ->  Seq Scan on params  (cost=0.00..7437.61 rows=336761 width=66) (never executed)
 Planning Time: 19.855 ms
 JIT:
   Functions: 25
   Options: Inlining true, Optimization true, Expressions true, Deforming true
   Timing: Generation 4.899 ms, Inlining 316.779 ms, Optimization 567.258 ms, Emission 432.088 ms, Total 1321.024 ms
 Execution Time: 1941.740 ms
(19 rows)
```

only hash index
```
                                                                         QUERY PLAN                                                                         
------------------------------------------------------------------------------------------------------------------------------------------------------------
 Hash Join  (cost=16594.42..584889.96 rows=2909817 width=316) (actual time=366.663..366.738 rows=0 loops=1)
   Hash Cond: ((runs.run_uuid)::text = (params.run_uuid)::text)
   ->  Gather Merge  (cost=1000.29..521121.30 rows=67670 width=250) (actual time=366.661..366.735 rows=0 loops=1)
         Workers Planned: 1
         Workers Launched: 1
         ->  Nested Loop  (cost=0.28..512508.41 rows=39806 width=250) (actual time=346.605..346.607 rows=0 loops=2)
               ->  Parallel Index Scan using run_pk on runs  (cost=0.28..27877.07 rows=1 width=163) (actual time=344.006..346.571 rows=2 loops=2)
                     Filter: (experiment_id = 0)
                     Rows Removed by Filter: 4204
               ->  Index Scan using metrics_run_uuid_idx1 on metrics  (cost=0.00..483401.77 rows=122958 width=87) (actual time=0.014..0.014 rows=0 loops=3)
                     Index Cond: ((run_uuid)::text = (runs.run_uuid)::text)
   ->  Hash  (cost=7437.61..7437.61 rows=336761 width=66) (never executed)
         ->  Seq Scan on params  (cost=0.00..7437.61 rows=336761 width=66) (never executed)
 Planning Time: 0.917 ms
 JIT:
   Functions: 25
   Options: Inlining true, Optimization true, Expressions true, Deforming true
   Timing: Generation 4.568 ms, Inlining 106.366 ms, Optimization 368.008 ms, Emission 211.456 ms, Total 690.399 ms
 Execution Time: 369.510 ms
(19 rows)
```

only default b-tree index
```
                                                                         QUERY PLAN                                                                          
-------------------------------------------------------------------------------------------------------------------------------------------------------------
 Hash Join  (cost=16595.11..585244.28 rows=2909817 width=316) (actual time=400.561..406.634 rows=0 loops=1)
   Hash Cond: ((runs.run_uuid)::text = (params.run_uuid)::text)
   ->  Gather Merge  (cost=1000.99..521475.62 rows=67670 width=250) (actual time=400.559..406.630 rows=0 loops=1)
         Workers Planned: 1
         Workers Launched: 1
         ->  Nested Loop  (cost=0.98..512862.74 rows=39806 width=250) (actual time=380.852..380.853 rows=0 loops=2)
               ->  Parallel Index Scan using run_pk on runs  (cost=0.28..27877.07 rows=1 width=163) (actual time=347.466..347.873 rows=2 loops=2)
                     Filter: (experiment_id = 0)
                     Rows Removed by Filter: 4204
               ->  Index Scan using metrics_run_uuid_idx on metrics  (cost=0.70..483756.09 rows=122958 width=87) (actual time=21.970..21.970 rows=0 loops=3)
                     Index Cond: ((run_uuid)::text = (runs.run_uuid)::text)
   ->  Hash  (cost=7437.61..7437.61 rows=336761 width=66) (never executed)
         ->  Seq Scan on params  (cost=0.00..7437.61 rows=336761 width=66) (never executed)
 Planning Time: 1.103 ms
 JIT:
   Functions: 25
   Options: Inlining true, Optimization true, Expressions true, Deforming true
   Timing: Generation 4.528 ms, Inlining 106.806 ms, Optimization 367.471 ms, Emission 213.897 ms, Total 692.702 ms
 Execution Time: 409.373 ms
(19 rows)
```

no index
```
---------------------------------------------------------------------------------------------------------------------------------------------------------
 Hash Join  (cost=16935.08..5825019.56 rows=2909817 width=316) (actual time=296253.922..296259.896 rows=0 loops=1)
   Hash Cond: ((runs.run_uuid)::text = (params.run_uuid)::text)
   ->  Gather  (cost=1340.96..5761250.90 rows=67670 width=250) (actual time=296253.921..296259.892 rows=0 loops=1)
         Workers Planned: 2
         Workers Launched: 2
         ->  Hash Join  (cost=340.96..5753483.90 rows=28196 width=250) (actual time=296235.854..296235.857 rows=0 loops=3)
               Hash Cond: ((metrics.run_uuid)::text = (runs.run_uuid)::text)
               ->  Parallel Seq Scan on metrics  (cost=0.00..5463035.33 rows=110457433 width=87) (actual time=385.887..280721.516 rows=88365946 loops=3)
               ->  Hash  (cost=340.94..340.94 rows=2 width=163) (actual time=1.768..1.769 rows=3 loops=3)
                     Buckets: 1024  Batches: 1  Memory Usage: 9kB
                     ->  Seq Scan on runs  (cost=0.00..340.94 rows=2 width=163) (actual time=0.036..1.759 rows=3 loops=3)
                           Filter: (experiment_id = 0)
                           Rows Removed by Filter: 8407
   ->  Hash  (cost=7437.61..7437.61 rows=336761 width=66) (never executed)
         ->  Seq Scan on params  (cost=0.00..7437.61 rows=336761 width=66) (never executed)
 Planning Time: 0.872 ms
 JIT:
   Functions: 40
   Options: Inlining true, Optimization true, Expressions true, Deforming true
   Timing: Generation 6.756 ms, Inlining 190.226 ms, Optimization 567.430 ms, Emission 328.273 ms, Total 1092.685 ms
 Execution Time: 296262.784 ms
(21 rows)
```
</details>

**Comment by harupy** [comment]
@mberr Thanks for benchmarking. This is awesome :)

**Comment by harupy** [comment]
@mberr Is it possible to benchmark this query in your environment?

```python
SELECT *
FROM metrics
WHERE metrics.run_uuid = <run id> AND metrics.key = <key>
```

**Comment by harupy** [comment]
cc @dbczumar @BenWilson2

**Comment by mberr** [comment]
> @mberr Is it possible to benchmark this query in your environment?
> 
> ```sql
> SELECT *
> FROM metrics
> WHERE metrics.run_uuid = <run id> AND metrics.key = <key>
> -- Please replace <run_id> and <key>
> ```
> 
> This is a query executed when the `get_metric_history` API is called.

There is not much difference here, since the primary key's index is used (cf. details below).

b-tree index | hash index | execution time
-- | -- | --:
yes | yes | 702.850 ms
no | yes | 702.080 ms
yes | no | 743.145 ms
no | no |  702.850 ms

<summary>Details</summary>
<details>


both
```
                                                              QUERY PLAN                                                               
---------------------------------------------------------------------------------------------------------------------------------------
 Index Only Scan using metric_pk on metrics  (cost=0.70..345344.60 rows=1165 width=87) (actual time=59.415..702.164 rows=2000 loops=1)
   Index Cond: ((key = 'eval.validation.left.num_rank'::text) AND (run_uuid = '8f9c932d81164360969ed9b724601eb1'::text))
   Heap Fetches: 0
 Planning Time: 31.427 ms
 JIT:
   Functions: 2
   Options: Inlining false, Optimization false, Expressions true, Deforming true
   Timing: Generation 0.394 ms, Inlining 0.000 ms, Optimization 0.146 ms, Emission 1.969 ms, Total 2.509 ms
 Execution Time: 702.850 ms
(9 rows)
```


btree
```
                                                              QUERY PLAN                                                               
---------------------------------------------------------------------------------------------------------------------------------------
 Index Only Scan using metric_pk on metrics  (cost=0.70..345344.60 rows=1165 width=87) (actual time=67.880..742.411 rows=2000 loops=1)
   Index Cond: ((key = 'eval.validation.left.num_rank'::text) AND (run_uuid = '8f9c932d81164360969ed9b724601eb1'::text))
   Heap Fetches: 0
 Planning Time: 3.881 ms
 JIT:
   Functions: 2
   Options: Inlining false, Optimization false, Expressions true, Deforming true
   Timing: Generation 0.436 ms, Inlining 0.000 ms, Optimization 0.172 ms, Emission 2.229 ms, Total 2.836 ms
 Execution Time: 743.145 ms
(9 rows)
```

hash tree
```
                                                              QUERY PLAN                                                               
---------------------------------------------------------------------------------------------------------------------------------------
 Index Only Scan using metric_pk on metrics  (cost=0.70..345344.60 rows=1165 width=87) (actual time=55.568..701.436 rows=2000 loops=1)
   Index Cond: ((key = 'eval.validation.left.num_rank'::text) AND (run_uuid = '8f9c932d81164360969ed9b724601eb1'::text))
   Heap Fetches: 0
 Planning Time: 0.501 ms
 JIT:
   Functions: 2
   Options: Inlining false, Optimization false, Expressions true, Deforming true
   Timing: Generation 0.363 ms, Inlining 0.000 ms, Optimization 0.145 ms, Emission 1.876 ms, Total 2.384 ms
 Execution Time: 702.080 ms
(9 rows)
```


none
```
                                                              QUERY PLAN                                                               
---------------------------------------------------------------------------------------------------------------------------------------
 Index Only Scan using metric_pk on metrics  (cost=0.70..345344.60 rows=1165 width=87) (actual time=59.415..702.164 rows=2000 loops=1)
   Index Cond: ((key = 'eval.validation.left.num_rank'::text) AND (run_uuid = '8f9c932d81164360969ed9b724601eb1'::text))
   Heap Fetches: 0
 Planning Time: 31.427 ms
 JIT:
   Functions: 2
   Options: Inlining false, Optimization false, Expressions true, Deforming true
   Timing: Generation 0.394 ms, Inlining 0.000 ms, Optimization 0.146 ms, Emission 1.969 ms, Total 2.509 ms
 Execution Time: 702.850 ms
(9 rows)
```

table schema
```
mlflow_db=# \d metrics
                         Table "public.metrics"
  Column   |          Type          | Collation | Nullable |   Default   
-----------+------------------------+-----------+----------+-------------
 key       | character varying(250) |           | not null | 
 value     | double precision       |           | not null | 
 timestamp | bigint                 |           | not null | 
 run_uuid  | character varying(32)  |           | not null | 
 step      | bigint                 |           | not null | '0'::bigint
 is_nan    | boolean                |           | not null | false
Indexes:
    "metric_pk" PRIMARY KEY, btree (key, "timestamp", step, run_uuid, value, is_nan)
    "metrics_run_uuid_idx" btree (run_uuid)
    "metrics_run_uuid_idx1" hash (run_uuid)
Foreign-key constraints:
    "metrics_run_uuid_fkey" FOREIGN KEY (run_uuid) REFERENCES runs(run_uuid)
```

</details>
