### ISSUE TITLE
[FR] avoid dependencies on MLflow Python CLI within MLflow R package

### ISSUE THREAD

**Issue by yitao-li** [mlflow/mlflow#3871]
## Willingness to contribute
The MLflow Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature (either as an MLflow Plugin or an enhancement to the MLflow code base)?

- [x] Yes. I can contribute this feature independently.
- [ ] Yes. I would be willing to contribute this feature with guidance from the MLflow community.
- [ ] No. I cannot contribute this feature at this time.

## Proposal Summary

There are basic MLflow functionalities such as downloading artifacts that can be performed entirely in R rather than being done through the MLflow Python CLI in a sub process.

## Motivation
- What is the use case for this feature?
- Why is this use case valuable to support for MLflow users in general?

Each time MLflow Python CLI is launched from R, there is a non-trivial overhead for starting up the Python sub process and in many cases running MLflow Python CLI can be avoided entirely.
Also, the fewer Python dependencies R users need to worry about, the better.

- Why is this use case valuable to support for your project(s) or organization?
- Why is it currently difficult to achieve this use case? (please be as specific as possible about why related MLflow features and components are insufficient)

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [x] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [x] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

## Details

Dependencies of MLflow R package on MLflow Python CLI should be reduced as much as possible.

**Comment by yitao-li** [comment]
We are unlikely to make changes proposed in this issue to `mlflow` R client. Having the R client relying on MLflow Python CLI for MLflow core functionalities guarantees reproducibility between Python and R clients, whereas re-implementing core functionalities in R could defeat such reproducibility and may be counterproductive. A secondary reason is re-writing those core functionalities in R would add too much maintenance workload to MLflow R client as well.
