### ISSUE TITLE
[BUG] TF2/Keras autologging failed to log model with default h5 save format

### ISSUE THREAD

**Issue by nemanja-m** [mlflow/mlflow#3910]
### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [x] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
MLflow Version: 1.13.0
TensorFlow version: 2.3.1
Python Version: 3.8.5
Operating System: Mac OS X 10.15.6 19G2021

### Describe the problem

Keras/TF2 models can be saved in the `SavedModel` format from the MLflow version 1.13.0 when `saved_format='tf'` is provided to `mlflow.keras.log_model`. When `mlflow.tensorflow.autolog(log_models=True)` is used, some trained models can't be saved on the train end callback in the default 'h5' format.

It seems that this happens because of https://github.com/mlflow/mlflow/blob/cbe0627428bc2692d851f4180a2ea59073040a63/mlflow/tensorflow.py#L779-L781 This callback calls `mlflow.keras.log_model` with default save format, which is `h5`.

One way to address this is to update `mlflow.tensorflow.autolog` with the `save_format: str = 'h5'` parameter, and propagate `save_format` option to callbacks.

### Code to reproduce issue

```python
import mlflow
import mlflow.tensorflow
import tensorflow as tf
from tensorflow.keras.layers.experimental.preprocessing import TextVectorization

VOCAB_SIZE = 10
SEQUENCE_LENGTH = 16
EMBEDDING_DIM = 32

train_samples = ["this is an example", "another example"]
train_labels = [0.43, 0.23]

mlflow.tensorflow.autolog()

with mlflow.start_run():
    vectorizer_layer = TextVectorization(
        input_shape=(1,),
        max_tokens=VOCAB_SIZE,
        output_mode="int",
        output_sequence_length=SEQUENCE_LENGTH,
    )
    vectorizer_layer.adapt(train_samples)

    model = tf.keras.Sequential(
        [
            vectorizer_layer,
            tf.keras.layers.Embedding(
                VOCAB_SIZE,
                EMBEDDING_DIM,
                name="embedding",
                mask_zero=True,
                input_shape=(1,),
            ),
            tf.keras.layers.GlobalAveragePooling1D(),
            tf.keras.layers.Dense(32, activation="relu"),
            tf.keras.layers.Dense(1, activation="tanh"),
        ]
    )
    model.compile(optimizer="adam", loss="mse", metrics="mae")
    model.fit(train_samples, train_labels, epochs=1)
```

### Other info / logs

```
2020/12/25 16:15:23 INFO mlflow.utils.autologging_utils: tensorflow autologging will track hyperparameters, performance metrics, model artifacts, and lineage information for the current tensorflow workflow to the MLflow run with ID '334a468262d64e7392594a859d2e7da5'
2020-12-25 16:15:23.657399: I tensorflow/core/profiler/lib/profiler_session.cc:164] Profiler session started.
1/1 [==============================] - 0s 31ms/step - loss: 0.1191 - mae: 0.3325
2020/12/25 16:15:24 WARNING mlflow.utils.autologging_utils: MLflow issued a warning during tensorflow autologging: "/Users/user/.pyenv/versions/example/lib/python3.8/site-packages/mlflow/tensorflow.py:786: UserWarning: Logging to MLflow failed: Save or restore weights that is not an instance of `tf.Variable` is not supported in h5, use `save_format='tf'` instead. Got a model or layer TextVectorization with weights [<tensorflow.python.keras.engine.base_layer_utils.TrackableWeightHandler object at 0x14f40a460>]"
```

### What component(s), interfaces, languages, and integrations does this bug affect?

- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

**Comment by MaisaDaoud** [comment]
has this issue  been fixed yet?

**Comment by nemanja-m** [comment]
Not yet. Here is a quick workaround:

```python
_original_keras_log_model = mlflow.keras.log_model

def _keras_log_model_patch(*args, **kwargs) -> None:
    kwargs["save_format"] = "tf"
    _original_keras_log_model(*args, **kwargs)

mlflow.keras.log_model = _keras_log_model_patch
```
