### ISSUE TITLE
[BUG] mlflow_list_experiments() bugs with tags

### ISSUE THREAD

**Issue by lorenzwalthert** [mlflow/mlflow#3941]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md) for additional information about bug reports. For help with debugging your code, please refer to [Stack Overflow](https://stackoverflow.com/questions/tagged/mlflow).

**Please fill in this bug report template to ensure a timely and thorough response.**

### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [x] Yes. I can contribute a fix for this bug independently.
- [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: Yes
- **OS Platform and Distribution)**: macOS
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**: 1.12.1
- **Python version**: 3.6
- **npm version, if running the dev UI**:
- **Exact command to reproduce**:

### Describe the problem

Listing experiments with `mlflow_list_experiments()` has two bugs that only show in certain cases:

``` r
one <- mlflow::mlflow_create_experiment('one')
mlflow::mlflow_list_experiments() # does not list tags. Consistent with REST API, so ok...
#> # A tibble: 2 x 4
#>   experiment_id name   artifact_location                         lifecycle_stage
#>   <chr>         <chr>  <chr>                                     <chr>          
#> 1 0             Defau… /private/var/folders/6g/bg5mcmsj7s51r33s… active         
#> 2 1             one    /private/var/folders/6g/bg5mcmsj7s51r33s… active
two <- mlflow::mlflow_create_experiment('two')
mlflow::mlflow_set_experiment_tag('key2', 'value2', two)

# still does not list tags because of a bug in purrr::transpose
# https://github.com/tidyverse/purrr/issues/397
mlflow::mlflow_list_experiments()
#> # A tibble: 3 x 4
#>   experiment_id name   artifact_location                         lifecycle_stage
#>   <chr>         <chr>  <chr>                                     <chr>          
#> 1 0             Defau… /private/var/folders/6g/bg5mcmsj7s51r33s… active         
#> 2 1             one    /private/var/folders/6g/bg5mcmsj7s51r33s… active         
#> 3 2             two    /private/var/folders/6g/bg5mcmsj7s51r33s… active


# make sure all existing have tags and there is more than one run
mlflow::mlflow_set_experiment_tag('key1', 'value1', one)
mlflow::mlflow_delete_experiment(experiment_id = 0)

# now errors because unlisting key value pairs returns 2x number of tags per
# experiment (one element for key, one for value)
mlflow::mlflow_list_experiments()
#> Error: Tibble columns must have compatible sizes.
#> * Size 2: Columns `experiment_id`, `name`, `artifact_location`, and `lifecycle_stage`.
#> * Size 4: Column `tags`.
#> ℹ Only values of size one are recycled.


# also, currently, if there is just one experiment, because of recycling rules,
# all but the tag rows are replicated for every key/value
mlflow::mlflow_delete_experiment(two)
mlflow::mlflow_set_experiment_tag('key', 'value', experiment_id = one)
mlflow::mlflow_list_experiments()
#> # A tibble: 4 x 5
#>   experiment_id name  artifact_location                    lifecycle_stage tags 
#>   <chr>         <chr> <chr>                                <chr>           <chr>
#> 1 1             one   /private/var/folders/6g/bg5mcmsj7s5… active          key  
#> 2 1             one   /private/var/folders/6g/bg5mcmsj7s5… active          value
#> 3 1             one   /private/var/folders/6g/bg5mcmsj7s5… active          key1 
#> 4 1             one   /private/var/folders/6g/bg5mcmsj7s5… active          valu…
```

<sup>Created on 2021-01-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

My Conclusion:
* tags column should always be returned if at least one run has tags.
* need to make sure tags is a list column with one element per experiment. This is a breaking API change (in return value) and can't be avoided, because there can be 0 or more tags with each experiment and the only way to return these type stable is with a list column.

This is implemented in #3942.

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [x] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations
