### ISSUE TITLE
[FR] Http Artifact Repository

### ISSUE THREAD

**Issue by joonjeong** [mlflow/mlflow#3956]
Thank you for submitting a feature request. **Before proceeding, please review MLflow's [Issue Policy for feature requests](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md#feature-requests) and the [MLflow Contributing Guide](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst)**.

**Please fill in this feature request template to ensure a timely and thorough response.**

## Willingness to contribute
The MLflow Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature (either as an MLflow Plugin or an enhancement to the MLflow code base)?

- [x] Yes. I can contribute this feature independently.
- [x] Yes. I would be willing to contribute this feature with guidance from the MLflow community.
- [ ] No. I cannot contribute this feature at this time.

## Proposal Summary

I think it would be great if mlflow supports http artifact repository.

```bash
$ mlflow server --default-artifact-root http://some-http-artifact-storage  
[2021-01-08 12:07:32 +0900] [86305] [INFO] Starting gunicorn 20.0.4
[2021-01-08 12:07:32 +0900] [86305] [INFO] Listening at: http://127.0.0.1:5000 (86305)

...

$ MLFLOW_TRACKING_URI=http://localhost:5000 python train.py
(it works!)
```

## Motivation
- What is the use case for this feature?
   MLflow Server as a sharable ML experiment dashboard
- Why is this use case valuable to support for MLflow users in general?
   This is for those who want to share ML experiment results in their team using Web Browser.
- Why is this use case valuable to support for your project(s) or organization?
   If this feature is available, it's possible to deploy MLflow Tracking Server as a standalone tracking dashboard and remote user can submit artifact remotely via http interface in CLI or their code.
- Why is it currently difficult to achieve this use case? (please be as specific as possible about why related MLflow features and components are insufficient)
   Only storage-like artifact repository is supported yet. this make hard to deploy MLflow Tracking Server as a standalone deployment

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [x] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

## Details

(Use this section to include any additional information about the feature. If you have a proposal for how to implement this feature, please include it here. For implementation guidelines, please refer to the [Contributing Guide](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst#contribution-guidelines).)

Actually, I make HttpArtifactRepository as a MLflow plugin private for just my private usages but it works like proxy of Google Storage yet. I know Http-based Artifact Repository requires another storage issues but I think it can be start with supporting local file storage like `filestore` and extending as a proxy to file transfer protocol or cloud storage.

**Comment by dbczumar** [comment]
Proxied artifact storage has been introduced to `mlflow server`. Documentation is available at https://mlflow.org/docs/latest/tracking.html#using-the-tracking-server-for-proxied-artifact-access. Thank you for using MLflow!
