### ISSUE TITLE
[FR] autolog support for xgboost.dask and lightgbm.dask

### ISSUE THREAD

**Issue by lostmygithubaccount** [mlflow/mlflow#3966]
## Willingness to contribute
The MLflow Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature (either as an MLflow Plugin or an enhancement to the MLflow code base)?

- [ ] Yes. I can contribute this feature independently.
- [ ] Yes. I would be willing to contribute this feature with guidance from the MLflow community.
- [x] No. I cannot contribute this feature at this time.

## Proposal Summary

Currently, ``xgboost.dask`` training does not work with ``mlflow.xgboost.autolog``. In ``lightgbm==3.2.0`` a similar ``lightgbm.dask`` module will be introduced.

As a user, I would expect the autologging to work for XGBoost and LightGBM training in the distributed submodules.

## Motivation
- What is the use case for this feature? **autologging/full compatibility with distributed training tracking**
- Why is this use case valuable to support for MLflow users in general? **logging with distributed training**
- Why is this use case valuable to support for your project(s) or organization? **adding distributed XGBoost and LightGBM tutorials to Azure Machine Learning examples https://github.com/Azure/azureml-examples/pull/324 and https://github.com/Azure/azureml-examples/pull/326**
- Why is it currently difficult to achieve this use case? **i do not know**

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

## Details

I think more discussion by people familiar with mlflow is needed on how to handle this and similar cases. 

CC: @akshaya-a

**Comment by akshaya-a** [comment]
@dbczumar @smurching  the reason this is interesting and I asked for an issue is the added dimension of distribution frameworks by logical flavor. considering LGBM, which is available bare, [on spark](https://github.com/Azure/mmlspark/blob/master/docs/lightgbm.md), and now dask (above) with (unfortunately) different namespacing, it seems like consumers would only care about the logical flavor, but there are likely going to be a set of shared functionality (utilities) that are centralized on a per-distribution-framework basis?
