### ISSUE TITLE
[BUG] mlflow.*.log_model returns None.

### ISSUE THREAD

**Issue by deokkyun** [mlflow/mlflow#3968]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md) for additional information about bug reports. For help with debugging your code, please refer to [Stack Overflow](https://stackoverflow.com/questions/tagged/mlflow).

**Please fill in this bug report template to ensure a timely and thorough response.**

### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [x] Yes. I can contribute a fix for this bug independently.
- [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: mac os catalina 10.15.7
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**: 1.13.1
- **Python version**: 3.7.3
- **npm version, if running the dev UI**:
- **Exact command to reproduce**: mlflow.sklearn.log_model

### Describe the problem
mlflow.*.log_model returns None.

In the document, Version information should be returned, but None.
The description of the above function in the [document](https://mlflow.org/docs/latest/model-registry.html#adding-an-mlflow-model-to-the-model-registry) is as follows.

>If a registered model with the name doesn’t exist, the method registers a new model, creates Version 1, and returns a ModelVersion MLflow object. If a registered model with the name exists already, the method creates a new model version and returns the version object.

expect: mlflow.sklearn.log_model returns VersionInfo.
actual: mlflow.sklearn.log_model returns None.

In addition to sklearn, version information is not returned from various model_flavors.

### Code to reproduce issue
```
mlflow.sklearn.log_model(
        sk_model=sk_learn_rfr,
        artifact_path="sklearn-model",
        registered_model_name="sk-learn-random-forest-reg-model"
    )
```

### Other info / logs

The return implementation of mlflow.sklearn.log_model is shown below.
![image](https://user-images.githubusercontent.com/19466114/104353790-a4c1bb00-554b-11eb-8597-807f957ae129.png)

but Model.log doesn't return anything.
![image](https://user-images.githubusercontent.com/19466114/104353939-d20e6900-554b-11eb-88af-7fbb885ceeb6.png)

I think we should add a return statement to Model.log and each model_flavor.
![image](https://user-images.githubusercontent.com/19466114/104354127-169a0480-554c-11eb-9118-1d56c12fdeff.png)

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [x] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dmatrix** [comment]
@deokkyun Thanks for filing this issue. 

> If a registered model with the name doesn’t exist, the method registers a new model, creates Version 1, and returns a ModelVersion MLflow object. If a registered model with the name exists already, the method creates a new model version and returns the version object.

This comment refers to the section below and for the code snippet for `mlflow.register_model()` rather than `mlflow.sklearn.log_mode()`, which can take registered_name as key word argument, the [signature](https://mlflow.org/docs/latest/python_api/mlflow.sklearn.html#mlflow.sklearn.log_model) does not return anything. It will
create a version when registering but it does not return it. Only the mlflow.register_model() returns a ModelVersion. 

The comment as is can be misleading to suggest the model version is returned from mlflow.sklearn.log_model() when it its not. I'll correct that.
