### ISSUE TITLE
[BUG] Metrics graph don't plot on Firefox v84.0.2

### ISSUE THREAD

**Issue by fatal69100** [mlflow/mlflow#3970]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md) for additional information about bug reports. For help with debugging your code, please refer to [Stack Overflow](https://stackoverflow.com/questions/tagged/mlflow).

**Please fill in this bug report template to ensure a timely and thorough response.**

### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [x] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**:  1.13.1
- **Python version**: 3.8.6
- **npm version, if running the dev UI**:
- **Exact command to reproduce**: mlflow server --backend-store-uri postgresql://postgres:mdp@127.0.0.1:5432/mlflow --host 127.0.0.1

### Describe the problem
Metrics are well plotted on Chrome but not on Firefox v84.0.2.

On Firefox, if I do several runs of the same experiment, curves metrics are plotted for the latest run but not for the older ones. 

First run (Firefox): 
![firefox_mlflow_first_success](https://user-images.githubusercontent.com/12247702/104356926-d4050780-550c-11eb-893c-1184d9262e8e.png)

Second run (Firefox): 
![firefox_plot_fail_mlflow](https://user-images.githubusercontent.com/12247702/104356934-d6fff800-550c-11eb-94d8-d1c32bfd2b5a.png)

Second run (Chrome): 
![chrome_plot_works](https://user-images.githubusercontent.com/12247702/104356944-db2c1580-550c-11eb-880f-8fbcf662163e.png)

And I am getting this issue for all runs except (sometimes) for the first one because sometimes even the latest run is not shown, but I don't understand why. I think the core issue is due to Firefox graph plot library but I hope that it is easy to reproduce.

### Code to reproduce issue
I could reproduce this bug using `examples/tensorflow/tf2/train_predict_2.py`.

### Other info / logs
N/a

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [x] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by fatal69100** [comment]
cannot reproduce. probably a caching issue
