### ISSUE TITLE
[BUG] R client does not respect run_id when starting a run anymore

### ISSUE THREAD

**Issue by lorenzwalthert** [mlflow/mlflow#3983]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md) for additional information about bug reports. For help with debugging your code, please refer to [Stack Overflow](https://stackoverflow.com/questions/tagged/mlflow).

**Please fill in this bug report template to ensure a timely and thorough response.**

### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [x] Yes. I can contribute a fix for this bug independently (https://github.com/mlflow/mlflow/pull/3816).
- [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS 10.15.7
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**: 1.13.1
- **Python version**: 3.6
- **npm version, if running the dev UI**:
- **Exact command to reproduce**:

### Describe the problem

You can't set the run id to a valid value with version 13.2 of R mlflow anymore.

### Code to reproduce issue

``` r
library(mlflow)
run_info <- mlflow::mlflow_start_run()
mlflow::mlflow_end_run()
#> # A tibble: 1 x 12
#>   run_uuid experiment_id user_id status start_time          end_time           
#>   <chr>    <chr>         <chr>   <chr>  <dttm>              <dttm>             
#> 1 fc99804… 0             lorenz  FINIS… 2021-01-14 23:27:03 2021-01-14 23:27:04
#> # … with 6 more variables: artifact_uri <chr>, lifecycle_stage <chr>,
#> #   run_id <chr>, metrics <lgl>, params <lgl>, tags <list>
# Sys.setenv("MLFLOW_RUN_ID" = run_info$run_id)
# mlflow::mlflow_start_run()
# or 
mlflow::mlflow_start_run(run_info$run_id)
#> Error: object of type 'closure' is not subsettable
```

<sup>Created on 2021-01-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [x] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by lorenzwalthert** [comment]
This is fixed with https://github.com/mlflow/mlflow/pull/3816.

**Comment by lorenzwalthert** [comment]
Closed with #3816.
