### ISSUE TITLE
[BUG] TypeError: cannot pickle 'weakref' object

### ISSUE THREAD

**Issue by rodalberta** [mlflow/mlflow#4005]
### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [x] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS 11.1
- **MLflow installed from (source or binary)**:
- **MLflow version (run ``mlflow --version``)**: 1.13.1
- **Python version**: 3.8
- **npm version, if running the dev UI**:
- **Exact command to reproduce**:

### Describe the problem
I've defined a basic Keras model and used the custom pyfunc flavor to create a model class and save this model to local file. I've tried several configurations but all lead to a "TypeError: cannot pickle 'weakref' object".

### Code to reproduce issue
```python
        model = keras.Sequential()
        model.add(Bidirectional(LSTM(128, input_shape=[10,100])))
        model.add(Dropout(rate=0.5))
        model.add(Dense(6, activation='softmax'))
        model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['acc'])
        history = model.fit(x_train, y_train, epochs=64, validation_split=0.2, shuffle=True)

        class NewModel(mlflow.pyfunc.PythonModel):
            def __init__(self, model):
                self.model = model
            def predict(self, context, x_input):
                return self.model.predict(x_input)
        
        mlflow.pyfunc.save_model(
            path = './_model/test_model',
            python_model = NewModel(model)
        )
```

### Other info / logs

```python
Traceback (most recent call last):
  File "/Users/roderickmacintosh/gDrive/MAIN/model_training/src/venv/lib/python3.8/site-packages/mlflow/pyfunc/model.py", line 138, in _save_model_with_class_artifacts_params
    cloudpickle.dump(python_model, out)
  File "/Users/roderickmacintosh/gDrive/MAIN/model_training/src/venv/lib/python3.8/site-packages/cloudpickle/cloudpickle_fast.py", line 55, in dump
    CloudPickler(
  File "/Users/roderickmacintosh/gDrive/MAIN/model_training/src/venv/lib/python3.8/site-packages/cloudpickle/cloudpickle_fast.py", line 563, in dump
    return Pickler.dump(self, obj)
TypeError: cannot pickle 'weakref' object
```

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [x] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
https://stackoverflow.com/questions/64665776/typeerror-cant-pickle-weakref-objects-for-deep-learning-model

**Comment by rodalberta** [comment]
thanks, did see this issue but I don't understand why the docs explicitly state Pyfunc models work with Keras. Why not use `mlflow.keras.log_model` or `mlflow.keras.log_model` > I've reduced the code slightly, but within NewModel class I will include several preprocessing functions/fitted scaler objects. Alternatively, I've tried `mlflow.keras.save_model` and included a `custom_objects` param with preprocess functions, however the objects aren't restored with `mlflow.keras.load_model()`

**Comment by ScarletMcLearn** [comment]
same here

**Comment by bobrasta** [comment]
pickle.dump(model,pickle_out)
TypeError: cannot pickle 'weakref' object

Sam here python3.9

**Comment by yemretat** [comment]
same here

**Comment by KevGomez** [comment]
same here

**Comment by sksvineeth** [comment]
Same issue

**Comment by SmFaraji** [comment]
Same issue

**Comment by tsuga** [comment]
Same issue

**Comment by nizarhabib** [comment]
Same TypeError: cannot pickle 'weakref' object

**Comment by bvarjavand** [comment]
I've also run into this issue.
It seems that increasing the scope of a keras model (including extra preprocessing steps, etc) and throwing everything into a PythonModel isn't supported.
I guess the only solution currently is to leave the model as purely a keras model, and move the methods for data preprocessing outside of the model.

**Comment by strangan** [comment]
I'm running into this issue as well. While it works great using mlflow.keras.log_model, I cant convert it to a pyfunc flavor. The reason why I'm even converting it to the a pyfunc flavor is because i want to override the PREDICT method and output something custom - instead of the probabilities, i want to output the class with the highest probability and serve it using MLFLOW model serving.

Pytorch doesn't seem to have this issue. But it also means that the code becomes more complicated to use Pytorch instead of the beautifully simple Keras APIs

**Comment by Fayzan-Bhatti** [comment]
Here I am using TensorFlow and Keras, I didn't test on PyTorch. Yet this
error is not resolved

**Comment by tangcc35** [comment]
same when using torch lightning

**Comment by strangan** [comment]
So i noticed there hasn't been any movement on this issue since Jan 21st, 2021 when it was first reported. And it doesn't seem to  have anyone assigned to it either. So what happens next? How does this actually get any attention from the mlflow authors/developers?

**Comment by jinzhang21** [comment]
Thanks for the raising the issue. We'll prioritize a discussion on possible solution to logging Keras models as Pyfunc type. In the meantime, you can use Keras native model logging to circumvent the issue: https://www.mlflow.org/docs/latest/python_api/mlflow.keras.html#mlflow.keras.log_model

**Comment by strangan** [comment]
@jinzhang21 : Thank you for your response.

I posted something similar on Stackoverflow.com as well to explain why having the ability to log a mlflow Keras model in a pyfunc flavor is important. You can read about it here:

https://stackoverflow.com/questions/70385171/mlflow-on-databricks-cannot-log-a-keras-model-as-a-mlflow-pyfunc-model-get-ty

Thanks

**Comment by jinzhang21** [comment]
Synced with team members. To log a Keras model (or any other flavor) in Pyfunc format, please follow the example below: https://www.mlflow.org/docs/latest/models.html#example-saving-an-xgboost-model-in-mlflow-format

I agree the approach is not self-evident and not very searchable. We'll fix the documentation in the near term, and think about how to better address the usability in long term.

**Comment by strangan** [comment]
Thanks @jinzhang21 

But i'm still having trouble. Maybe it's a silly error on my part. I followed the recipe you laid out from the XGBOOST example. However, it fails right at the end when I try to load the pyfunc model using ```mlflow.pyfunc.load_model``` The specific error is ```AttributeError: 'Model' object has no attribute 'load_model'``` which is strange because I'm calling the entire class mlflow.pyfunc.load_model. I've attached my code for you to review. If you could point me in the right direction, I would be very grateful. 

I suspect it has something to do with saving the Keras model ```keras_model.save```. I even tried saving it as an ```h5``` model but didn't have any success. Or maybe it's the definition of the KerasWrapper class itself. Either way, any help would be greatly appreciated. I'm sure others following this thread would benefit as well. All this is on a Databricks notebook by the way.

Thanks!

```
with mlflow.start_run(run_name=runName):

  mlflow.tensorflow.autolog()   

  #Build the model, compile and train on the training set
  #signature: build_model(vocab_size, steps, drop_embed, n_dim, encoder, modelType):
  keras_model = build_model((vocab_size + 1), timeSteps, drop_embed, embedding_dimensions, encoder, modelType)      

  # CREATE CALLBACKS        
  modelcheckpoint = ModelCheckpoint(filepath=output_dir+"/weights.{epoch:02d}.hdf5")

  keras_model.fit(X_train_encoded, y_train_encoded, epochs=epochs, verbose=1, batch_size=32, use_multiprocessing = True, 
                            validation_data=(X_test_encoded, y_test_encoded), callbacks=[modelcheckpoint])

  # Log the model parameters used for this run.  
  mlflow.log_param("numofActionsinWorkflow", numofActionsinWf)
  mlflow.log_param("timeSteps", timeSteps)

  # Create a model signature using the tensor input to store in the MLflow model registry
  signature = infer_signature(X_test_encoded, keras_model.predict(X_test_encoded))
  # Let's check out how it looks
  print(signature)

  # Create an input example to store in the MLflow model registry
  input_example = np.expand_dims(X_train[17], axis=0)
  
  #log the model to experiment
  mlflow.keras.log_model(keras_model, artifact_path = runName, signature=signature, input_example=input_example)

  #return the run ID for model registration
  run_id = mlflow.active_run().info.run_id
  
  mlflow.end_run()


class KerasWrapper(mlflow.pyfunc.PythonModel):
   
  def load_context(self, context):
    import tensorflow.keras as keras
    self.keras_model = keras.Model()
    self.keras_model.load_model(context.artifacts["keras_model"])
  
  def predict(self, context, input_data):
    scores = self.keras_model.predict(input_data)
    return(scores)

# Create a Conda environment for the new MLflow Model that contains all necessary dependencies.
conda_env = {
    'channels': ['defaults'],
    'dependencies': [
      'python={}'.format(PYTHON_VERSION),
      'pip',
      {
        'pip': [
          'mlflow',
          'tensorflow=={}'.format(tensorflow.__version__),
          'cloudpickle=={}'.format(cloudpickle.__version__),
        ],
      },
    ],
    'name': 'keras_env'
}

#save the model
keras_model_path = "keras_model_cnn.pth"
keras_model.save(keras_model_path, overwrite=True)

# Create an `artifacts` dictionary that assigns a unique name to the saved Keras model file.
# This dictionary will be passed to `mlflow.pyfunc.save_model`, which will copy the model file
# into the new MLflow Model's directory.

artifacts = {
    "keras_model": keras_model_path
}

# Save the MLflow Model
mlflow_pyfunc_model_path = "keras_mlflow_cnn"
mlflow.pyfunc.save_model(
        path=mlflow_pyfunc_model_path, python_model=KerasWrapper(), artifacts=artifacts,
        conda_env=conda_env)

# Load the model in `python_function` format
loaded_model = mlflow.pyfunc.load_model(mlflow_pyfunc_model_path)

#### GIVES ERROR OVER HERE -------- AttributeError: 'Model' object has no attribute 'load_model'
```

**Comment by dbczumar** [comment]
Hi @strangan , I think you need to replace the following:

```
    self.keras_model = keras.Model()
    self.keras_model.load_model(context.artifacts["keras_model"])
```

with

```
    self.keras_model = mlflow.keras.load_model(context.artifacts["keras_model"])
```

Let me know if this helps.

**Comment by strangan** [comment]
> 

Oh my god! What a silly mistake! I poured over the code line by line and nearly lost my mind. Thank you so much @dbczumar . This works now.

**Comment by cpinon-grd** [comment]
Hello! What if I want to have the model fit() logic inside my custom wrapper? Is it completely imposible?

**Comment by prabhatkgupta** [comment]
Getting a similar error in Keras model. Is passing artifact and using `load_context` the only way to log a Keras model in mlflow? @jinzhang21 @dbczumar
