### ISSUE TITLE
MLFlow Tracking - Auto-logging doesn't capture parameters by default on TF 1.15.0

### ISSUE THREAD

**Issue by mohammedayub44** [mlflow/mlflow#4053]
Description
  
  ### Willingness to contribute
  The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?
  
  - [ ] Yes. I can contribute a fix for this bug independently.
  - [x] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
  - [ ] No. I cannot contribute a bug fix at this time.
  
  ### System information
  - **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: `No`
  - **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: `Yes`
  - **MLflow installed from (source or binary)**: `binary`
  - **MLflow version (run ``mlflow --version``)**: `1.13.1`
  - **Python version**:  `3.7.6`
  - **npm version, if running the dev UI**:
  - **Exact command to reproduce**: `python examples/tensorflow/tf1/train_predict.py`
  
  ### Description:

Running the example does not capture parameters and also evaluation metrics. It also shows some warnings on export signatures. `expecting a Tensor of String but got Input of shape (None,13)`  Is this fine to ignore? (Attaching log file for reference)

Log File:  [train_predict_tf1_run_log.txt](https://github.com/mlflow/mlflow/files/5916072/train_predict_tf1_run_log.txt)

Snapshots: 
![image](https://user-images.githubusercontent.com/7122670/106697803-892b5c80-65ad-11eb-8d4d-f5fd59d01909.png)

    
  ### What component(s), interfaces, languages, and integrations does this bug affect?
  Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [x] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [x] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Let me know if I'm missing something. 
Thanks !
