### ISSUE TITLE
[BUG] infer_signature fails when dataframe contains ExtensionDtype

### ISSUE THREAD

**Issue by caleboverman** [mlflow/mlflow#4055]
### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [x] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS 11.1
- **MLflow installed from (source or binary)**: 
- **MLflow version (run ``mlflow --version``)**: 1.13.1
- **Python version**: 3.8.5
- **npm version, if running the dev UI**:
- **Exact command to reproduce**: 

### Describe the problem
Pandas supports `ExtensionDtypes` for extending types from numpy. These types allow additional functionality (like `NA` support for bools or ints). However, calling `infer_signature` on a dataframe with these types fails because the columns are not of type `numpy.ndarray`.

### Code to reproduce issue
```
import pandas as pd
from mlflow.models import infer_signature

df = pd.DataFrame(
    {
        "ints": [1, 2, 3],
        "bools": [True, False, True],
        "strings": ["a", "b", "c"]
    }
)

# doing any of the following will cause infer_signature to fail
df["ints"] = df["ints"].astype("Int64")
infer_signature(df)

df["bools"] = df["bools"].astype("boolean")
infer_signature(df)

df["strings"] = df["strings"].astype("string")
infer_signature(df)
```

### Other info / logs
```
TypeError                                 Traceback (most recent call last)
<ipython-input-122-64641ea9310a> in <module>
      1 df["strings"] = df["strings"].astype("string")
----> 2 infer_signature(df)

~/opt/anaconda3/envs/fts/lib/python3.8/site-packages/mlflow/models/signature.py in infer_signature(model_input, model_output)
    121     :return: ModelSignature
    122     """
--> 123     inputs = _infer_schema(model_input)
    124     outputs = _infer_schema(model_output) if model_output is not None else None
    125     return ModelSignature(inputs, outputs)

~/opt/anaconda3/envs/fts/lib/python3.8/site-packages/mlflow/types/utils.py in _infer_schema(data)
     62     elif isinstance(data, pd.DataFrame):
     63         schema = Schema(
---> 64             [ColSpec(type=_infer_numpy_array(data[col].values), name=col) for col in data.columns]
     65         )
     66     elif isinstance(data, np.ndarray):

~/opt/anaconda3/envs/fts/lib/python3.8/site-packages/mlflow/types/utils.py in <listcomp>(.0)
     62     elif isinstance(data, pd.DataFrame):
     63         schema = Schema(
---> 64             [ColSpec(type=_infer_numpy_array(data[col].values), name=col) for col in data.columns]
     65         )
     66     elif isinstance(data, np.ndarray):

~/opt/anaconda3/envs/fts/lib/python3.8/site-packages/mlflow/types/utils.py in _infer_numpy_array(col)
    138 def _infer_numpy_array(col: np.ndarray) -> DataType:
    139     if not isinstance(col, np.ndarray):
--> 140         raise TypeError("Expected numpy.ndarray, got '{}'.".format(type(col)))
    141     if len(col.shape) > 1:
    142         raise MlflowException("Expected 1d array, got array with shape {}".format(col.shape))

TypeError: Expected numpy.ndarray, got '<class 'pandas.core.arrays.string_.StringArray'>'
```

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [x] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dmatrix** [comment]
@caleboverman Thanks for filling this bug.

cc: @tomasatdatabricks is this true? Should we support extensions?

**Comment by tomasatdatabricks** [comment]
@dmatrix yes we should support it. I think we should fix it asap. If someone is willing to start working on this soon that I would say yes, it would be a good first issue.

**Comment by caleboverman** [comment]
I've got a basic fix in place utilizing internal pandas methods to check column types. I can try to get a PR ready in the next few days.

**Comment by dmatrix** [comment]
@caleboverman Since you want to contribute, yes, please get the PR going, and will review it and provide feedback.

**Comment by rafaelvp-db** [comment]
just wanted to know what's the status of this issue as it seems it's been a long time it's been open without changes. if it still hasn't been solved I would like to work on it.

**Comment by dbczumar** [comment]
This has been addressed via https://github.com/mlflow/mlflow/pull/4069. Thank you for your contribution!
