### ISSUE TITLE
[FR] Search by run_uuid ?

### ISSUE THREAD

**Issue by EKami** [mlflow/mlflow#4064]
## Willingness to contribute
Yes. I would be willing to contribute this feature with guidance from the MLflow community.

## Proposal Summary

In the Mlflow UI I am unable to search by `run_uuid`, I cannot do this for instance:
```
attribute.run_uuid='7ab1bd833f754d24a9cdc51f515df766'
```
I'm only able to do something like this to search my runs:
```
attribute.artifact_uri='s3://my_artifacts/0/7ab1bd833f754d24a9cdc51f515df766/artifacts'
```

It feels weird to search by `artifact_uri` to find a run in the UI...

## Motivation
- What is the use case for this feature?
Easily find a run

- Why is this use case valuable to support for MLflow users in general?
Easier to find a run that needs investigation

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [x] `area/server-infra`: MLflow server, JavaScript dev server
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [x] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dmatrix** [comment]
@EKami Thanks for filling this request. It seems like currently you can't use an `attribute.run_id` as part of the filter string,
but you can use something like `filter_string = f"attribute.artifact_uri ILIKE '%{run_id}%'". You don't need an entire artifact URI.
You can use the `ILIKE %string%`matching pattern.

See this[ code illustration](https://github.com/dmatrix/mlflow-tests/blob/master/py/mlflow/apis/fluent/search_runs.py).

**Comment by EKami** [comment]
Thanks @dmatrix . I will use that in the meantime but yeah, semantically it's not great and it's not something that is specified in the docs so I wasn't able to find what you shared by myself.

**Comment by dmatrix** [comment]
@EKami excellent. I shall update the docs with the example. If this servers the purpose, should we close this issue?

**Comment by EKami** [comment]
I guess we can close it yeah. Thanks for your help! @dmatrix :)
