### ISSUE TITLE
[FR] Provide an option to disable/enable autologging verbosity

### ISSUE THREAD

**Issue by flaviopereirap5** [mlflow/mlflow#4083]
Thank you for submitting a feature request. **Before proceeding, please review MLflow's [Issue Policy for feature requests](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md#feature-requests) and the [MLflow Contributing Guide](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst)**.

**Please fill in this feature request template to ensure a timely and thorough response.**

## Willingness to contribute
The MLflow Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature (either as an MLflow Plugin or an enhancement to the MLflow code base)?

- [ ] Yes. I can contribute this feature independently.
- [ ] Yes. I would be willing to contribute this feature with guidance from the MLflow community.
- [X] No. I cannot contribute this feature at this time.

## Proposal Summary
Provide an option to disable/enable autologging verbosity.
I'm using mlflow autologging along with sk-learn. The verbosity of this is inconceivable to work and consult other logs. I would really enjoy a way to disable it.

## Motivation
- What is the use case for this feature?
Using mlflow autologging along with sk-learn.
- Why is this use case valuable to support for MLflow users in general?
I cannot find the info I want to consult in the script logs. I need to put all my custom logs at the end of the script, so I can consult them without having to immensely scroll.
- Why is this use case valuable to support for your project(s) or organization?
I cannot find the info I want to consult in the script logs. I need to put all my custom logs at the end of the script, so I can consult them without having to immensely scroll.
- Why is it currently difficult to achieve this use case? (please be as specific as possible about why related MLflow features and components are insufficient)
There is currently no way to disable the autologging's (extensive) verbosity. 

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dmatrix** [comment]
@flaviopereirap5 Thanks for filling this feature enhancement. Can you provide an example code where the `mflow.autolog()` is verbose? My experience is that it logs a couple of INFO messages. Unless I missed something, for example, [this notebook](https://databricks-prod-cloudfront.cloud.databricks.com/public/4027ec902e239c93eaaa8714f173bcfc/8599738367597028/3936462234021824/3601578643761083/latest.html) only prints a couple of informative messages, not as much verbose. 

We would love to see an example where enabling `mlflow.autolog()` with sk-learn triggers verbose messages.

Thanks!
cc: @dbczumar are you aware of this verbosity?

**Comment by dbczumar** [comment]
@flaviopereirap5 we’ve identified and fixed an issue with verbose logs during sklearn autologging; the fix has already been applied to master and will be released in MLflow 1.14 next week. In the meantime, installing the latest MLflow nightly build or installing the latest GitHub master branch should help! Please feel free to reopen this if you have other concerns!
