### ISSUE TITLE
Development Setup - Incorrect Artifact location created during the run

### ISSUE THREAD

**Issue by mohammedayub44** [mlflow/mlflow#4105]
Hi,

### Problem Description
I have setup the dev version and trying to run some experiments using mysql database and file URI as the artifact location. 
I start the development UI using the below command - 
`mlflow ui --backend-store-uri 'mysql://username:passwd@localhost:3306/testing?unix_socket=/var/run/mysqld/mysqld.sock' --default-artifact-root file:///home/ubuntu/mlruns -h 0.0.0.0`
and then start the dev ui using `npm start` within the `js` dir.

It shows up correctly on the Dev UI and inside mysql database. However when I run any experiments, it does not fetch the current artifact URI and creates new artifact location like `./mlruns/1` and `./mlruns/2` so on and the artifacts don't show up on the Dev UI. Not sure where these directories are on my local as well as I did not find them in the current directory to home directory. The experiments don't throw any errors and finishes successfully.

Also, in my code I correctly set the tracking uri using `mlflow.set_tracking_uri()` and I did not find a way to set the artifact location explicitly.

This shows in mysql db:
![image](https://user-images.githubusercontent.com/7122670/108022694-082d8580-6fef-11eb-9777-167fc45f1e16.png)

### Willingness to contribute
- [x] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **MLflow installed from (source or binary)**: source
- **MLflow version (run ``mlflow --version``)**: 1.13.2.dev0
- **Python version**: 3.7.6
- **npm version, if running the dev UI**: 6.14.10
- **Exact command to reproduce**:  
`mlflow ui --backend-store-uri 'mysql://username:passwd@localhost:3306/testing?unix_socket=/var/run/mysqld/mysqld.sock' --default-artifact-root file:///home/ubuntu/mlruns -h 0.0.0.0`

# Code to reproduce
I'm using separate object detection repo to run the experiments, however I'm guessing this error is irrespective of any repo. Let me know if you need them I can provide the files

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [x] `area/artifacts`: Artifact stores and artifact logging
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Thanks !

**Comment by dmatrix** [comment]
@mohammedayub44 Thanks for filling this issue. In your client code, what are you setting the tracking URI to?

**Comment by mohammedayub44** [comment]
Hi @dmatrix 

I set it as follows: 
`mlflow.set_tracking_uri('file:///home/ubuntu/mlruns/')`

The order is as follows (if that matters) 

```python
# Turn Auto-logging On
mlflow.tensorflow.autolog()

# Set the DB URI
db_uri = 'mysql://username:$pwd@localhost:3306/testing2'

# Set Tracking URI
mlflow.set_tracking_uri('file:///home/ubuntu/mlruns/')

# Set Experiment ID
mlflow.set_experiment('MLFlow_TF2_Test_02162021')
...
```

**Comment by dmatrix** [comment]
Your tracking URI should be `mlflow.set_tracking_uri('http://127.0.0.1:5000')`

**Comment by mohammedayub44** [comment]
Great! That worked. My bad, I got confused following the docs [here](https://mlflow.org/docs/latest/python_api/mlflow.html#mlflow.set_tracking_uri) 
My assumption is even though you start it with `mlflow ui ...` if you give `--backend_store_uri` it requires a server URL instead of local path.
