### ISSUE TITLE
XGBoost support

### ISSUE THREAD

**Issue by mikaelmv** [mlflow/mlflow#4204]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md) for additional information about bug reports. For help with debugging your code, please refer to [Stack Overflow](https://stackoverflow.com/questions/tagged/mlflow).

**Please fill in this bug report template to ensure a timely and thorough response.**

### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [X] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: Custom
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **MLflow installed from (source or binary)**: source
- **MLflow version (run ``mlflow --version``)**: 1.14.1
- **Python version**: 3.7
- **npm version, if running the dev UI**:
- **Exact command to reproduce**: 

### Describe the problem
Hi,

I am using a Scikit-Learn wrapper for XGBoost (XGBRegressor).

Now when logging the model with mlflow (mlflow.xgboost.log_model), it crashes as anticipated by the official documentation:

https://www.mlflow.org/docs/latest/python_api/mlflow.xgboost.html

I noticed that if I use mlflow.sklearn.log_model instead, the artifact gets saved as expected.

1. What are the implications of using mlflow.sklearn.log_model with an XGBoost model? Not clear to me.
2. What alternatives do I have to log my XGBRegressor model correctly with mlflow?

Obviously if I instead use a RandomForest, then mlflow.sklearn.log_model works perfectly as expected, so again my issue is to log the XGBRegressor model.

### Code to reproduce issue
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

mlflow.xgboost.log_model(pipeline, "model") (where pipeline combines transformers and the XGBRegressor)

### Other info / logs

    151
    152     # Save an XGBoost model
--> 153     xgb_model.save_model(model_data_path)
    154
    155     conda_env_subpath = "conda.yaml"

AttributeError: 'Pipeline' object has no attribute 'save_model'

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [X] `area/artifacts`: Artifact stores and artifact logging
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry

**Comment by dmatrix** [comment]
@mikaelmv Thanks for filing this? Can you give me a small example, to reproduce this, that I can run and see? I know that for mlflow autologging we don't [support scikit-learn API](https://www.mlflow.org/docs/latest/python_api/mlflow.xgboost.html#mlflow.xgboost.autolog)

**Comment by chedikouki** [comment]
is there any solution 
mlflow.xgboost.save_model(pipeline,'Model')
AttributeError: 'Pipeline' object has no attribute 'save_model'

**Comment by harupy** [comment]
https://github.com/mlflow/mlflow/pull/4954/ fixed this issue.
