### ISSUE TITLE
Issue updating database with mlflow v1.15.0 [BUG]

### ISSUE THREAD

**Issue by murphycj** [mlflow/mlflow#4208]
### Willingness to contribute
- [ ] Yes. I can contribute a fix for this bug independently.
- [x] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac v11.2.2
- **MLflow installed from (source or binary)**: binary (via pip)
- **MLflow version (run ``mlflow --version``)**: 1.15.0
- **Python version**: 3.7.6
- **npm version, if running the dev UI**: 
- **Exact command to reproduce**: `mlflow db upgrade postgresql://postgres:xxxxxx@xxxxxxx.us-east-1.rds.amazonaws.com:5432/mlflow`

### Describe the problem
I was previously running on mlflow version 1.14.1. When I was upgrading the database to v1.15.0, I ran into a couple issues. When I first tried updating the database it gave me an error. I then tried upgrading again, but then the database connection froze; I was then unable to interact with my database for a while.

### Code to reproduce issue
`mlflow db upgrade postgresql://postgres:xxxxxx@xxxxxxx.us-east-1.rds.amazonaws.com:5432/mlflow`

### Other info / logs
Here is the error I get when trying to setup the ui:

`mlflow ui --backend-store-uri postgresql://postgres:xxxxxxx@xxxxxxxx.us-east-1.rds.amazonaws.com:5432/mlflow --default-artifact-root s3://mlflow-store`
```
2021/03/27 00:29:33 ERROR mlflow.cli: Error initializing backend store
2021/03/27 00:29:33 ERROR mlflow.cli: Detected out-of-date database schema (found version a8c4a736bde6, but expected 39d1c3be5f05). Take a backup of your database, then run 'mlflow db upgrade <database_uri>' to migrate your database to the lat
est schema. NOTE: schema migration may result in database downtime - please consult your database's documentation for more detail.
Traceback (most recent call last):
  File "/Users/charliemurphy/Envs/tf/lib/python3.7/site-packages/mlflow/cli.py", line 272, in ui
    initialize_backend_stores(backend_store_uri, default_artifact_root)
  File "/Users/charliemurphy/Envs/tf/lib/python3.7/site-packages/mlflow/server/handlers.py", line 145, in initialize_backend_stores
    _get_tracking_store(backend_store_uri, default_artifact_root)
  File "/Users/charliemurphy/Envs/tf/lib/python3.7/site-packages/mlflow/server/handlers.py", line 130, in _get_tracking_store
    _tracking_store = _tracking_store_registry.get_store(store_uri, artifact_root)
  File "/Users/charliemurphy/Envs/tf/lib/python3.7/site-packages/mlflow/tracking/_tracking_service/registry.py", line 38, in get_store
    return builder(store_uri=store_uri, artifact_uri=artifact_uri)
  File "/Users/charliemurphy/Envs/tf/lib/python3.7/site-packages/mlflow/server/handlers.py", line 101, in _get_sqlalchemy_store
    return SqlAlchemyStore(store_uri, artifact_uri)
  File "/Users/charliemurphy/Envs/tf/lib/python3.7/site-packages/mlflow/store/tracking/sqlalchemy_store.py", line 123, in __init__
    mlflow.store.db.utils._verify_schema(self.engine)
  File "/Users/charliemurphy/Envs/tf/lib/python3.7/site-packages/mlflow/store/db/utils.py", line 59, in _verify_schema
    "more detail." % (current_rev, head_revision)
mlflow.exceptions.MlflowException: Detected out-of-date database schema (found version a8c4a736bde6, but expected 39d1c3be5f05). Take a backup of your database, then run 'mlflow db upgrade <database_uri>' to migrate your database to the latest
 schema. NOTE: schema migration may result in database downtime - please consult your database's documentation for more detail.
```

I tried to update the database via this command:
`mlflow db upgrade postgresql://postgres:xxxxxxx@xxxxxxx.us-east-1.rds.amazonaws.com:5432/mlflow`
Here is the error that I get:

```
2021/03/27 00:29:46 INFO mlflow.store.db.utils: Updating database tables
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade a8c4a736bde6 -> 39d1c3be5f05, add_is_nan_constraint_for_metrics_tables_if_necessary
Traceback (most recent call last):
  File "/Users/charliemurphy/Envs/tf/bin/mlflow", line 8, in <module>
    sys.exit(cli())
  File "/Users/charliemurphy/Envs/tf/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/charliemurphy/Envs/tf/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/charliemurphy/Envs/tf/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/charliemurphy/Envs/tf/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/charliemurphy/Envs/tf/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/charliemurphy/Envs/tf/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/charliemurphy/Envs/tf/lib/python3.7/site-packages/mlflow/db.py", line 28, in upgrade
    mlflow.store.db.utils._upgrade_db(engine)
  File "/Users/charliemurphy/Envs/tf/lib/python3.7/site-packages/mlflow/store/db/utils.py", line 146, in _upgrade_db
    command.upgrade(config, "heads")
  File "/Users/charliemurphy/Envs/tf/lib/python3.7/site-packages/alembic/command.py", line 298, in upgrade
    script.run_env()
  File "/Users/charliemurphy/Envs/tf/lib/python3.7/site-packages/alembic/script/base.py", line 489, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/Users/charliemurphy/Envs/tf/lib/python3.7/site-packages/alembic/util/pyfiles.py", line 98, in load_python_file
    module = load_module_py(module_id, path)
  File "/Users/charliemurphy/Envs/tf/lib/python3.7/site-packages/alembic/util/compat.py", line 173, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/charliemurphy/Envs/tf/lib/python3.7/site-packages/mlflow/store/db_migrations/env.py", line 84, in <module>
    run_migrations_online()
  File "/Users/charliemurphy/Envs/tf/lib/python3.7/site-packages/mlflow/store/db_migrations/env.py", line 78, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/Users/charliemurphy/Envs/tf/lib/python3.7/site-packages/alembic/runtime/environment.py", line 846, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/Users/charliemurphy/Envs/tf/lib/python3.7/site-packages/alembic/runtime/migration.py", line 518, in run_migrations
    step.migration_fn(**kw)
  File "/Users/charliemurphy/Envs/tf/lib/python3.7/site-packages/mlflow/store/db_migrations/versions/39d1c3be5f05_add_is_nan_constraint_for_metrics_tables_if_necessary.py", line 29, in upgrade
    "is_nan", type_=sa.types.Boolean(create_constraint=True), nullable=False, default=False
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/Users/charliemurphy/Envs/tf/lib/python3.7/site-packages/alembic/operations/base.py", line 354, in batch_alter_table
    impl.flush()
  File "/Users/charliemurphy/Envs/tf/lib/python3.7/site-packages/alembic/operations/batch.py", line 83, in flush
    fn(*arg, **kw)
  File "/Users/charliemurphy/Envs/tf/lib/python3.7/site-packages/alembic/ddl/postgresql.py", line 144, in alter_column
    **kw
TypeError: alter_column() got an unexpected keyword argument 'default'
```

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [x] `area/server-infra`: MLflow server, JavaScript dev server
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [x] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by lrog** [comment]
Hi, having also the same issue even when trying to start MLflow server with an empty PostgreSQL database:
```
mlflow server --backend-store-uri postgresql://XXXX:YYYY@postgres:5432/mlflow --default-artifact-root ./artifacts --host 0.0.0.0
```
Seems the issue affects the latest version only, as what downgraded the mlflow to `1.14.1` all works fine.

**Comment by AndreaGiardini** [comment]
I can confirm this prevents using Mlflow version 1.15.0, even on an empty database

1.14.1 works just fine

**Comment by dolfinus** [comment]
Here is a fix: https://github.com/mlflow/mlflow/pull/4211

**Comment by dolfinus** [comment]
Fix was merged into master.
