### ISSUE TITLE
[FR] Add in the tracking API a decorator to log all function arguments as MLFlow params

### ISSUE THREAD

**Issue by corradomonti** [mlflow/mlflow#4210]
## Willingness to contribute
The MLflow Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature (either as an MLflow Plugin or an enhancement to the MLflow code base)?

- [ ] Yes. I can contribute this feature independently.
- [X] Yes. I would be willing to contribute this feature with guidance from the MLflow community.
- [ ] No. I cannot contribute this feature at this time.

## Proposal Summary

Introduce a Python decorator `log_arguments` in the tracking API, so that the decorated function will register all of its arguments as MLFlow parameters when called. Working example:

```
import mlflow

@mlflow.log_arguments
def my_experiment(learning_rate, n_estimators=10):
    pass
        
with mlflow.start_run():
    my_experiment(0.1) # This will log params learning_rate as 0.1 and n_estimators as 10.
```

## Motivation

- What is the use case for this feature?

This decorator would streamline using the arguments of functions as source for MLFlow parameters.

- Why is this use case valuable to support for your project(s) or organization?
- Why is it currently difficult to achieve this use case? (please be as specific as possible about why related MLflow features and components are insufficient)

Currently, my personal use case involves long sequences of `mlflow.log_param` at the beginning of some functions, basically repeating the function arguments. This is a burden to maintain and very error-prone. It could be easily done programmatically instead.

- Why is this use case valuable to support for MLflow users in general?

0. If other people use MLFlow tracking in a similar way, it would streamline their parameters logging.
1. it could make the integration of new frameworks easier and more compact.
2. it would make it easier for new users to integrate their custom functions into the MLFlow workflow, even if they are not using any supported machine learning framework.

Of course this comes at the expense of added complexity in MLFlow, one more Tracking API function to maintain, and inspection being introduced. I would perfectly understand if this forbids this feature to be added, and will continue to use it only in my personal projects. I am creating this issue just to check whether is there any interest from the community in merging this.

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

## Details

I have already implemented this function in a personal fork using Python [inspect.BoundArguments](https://docs.python.org/3/library/inspect.html#inspect.BoundArguments) object. The implementation seems to be easy and short (<10 lines). I will be glad to prepare a PR right away if there is interest.

**Comment by dmatrix** [comment]
@corradomonti I wonder how is this suggest is different from [MLflow autologging](https://mlflow.org/docs/latest/python_api/mlflow.html#mlflow.autolog) features for ML libraries? Any parameters supplied as part of the library are auto-logged for you?

cc @dbczumar

**Comment by corradomonti** [comment]
@dmatrix the idea is very similar in concept but works with user-supplied functions. I see that also the implementation from [autolog](https://github.com/mlflow/mlflow/blob/83b665a2fcbf2a1bd93331f9e2b58045c09e44f4/mlflow/tracking/fluent.py#L1373) is similar. However my use case is different: if I am designing a custom algorithm for research purposes I usually have a "run experiment" function (which e.g. will call a mix of tensorflow and custom functions). Therefore I'd like to do autologging for my own façade function in a simple way. Afaik this is not currently covered by autologging, but I'd be happy to learn that I'm wrong!
