### ISSUE TITLE
[BUG] Cant retrieve tracking uri from Azure ML - SSL Handshake error 

### ISSUE THREAD

**Issue by codingmercy1993** [mlflow/mlflow#4298]
### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [X ] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10 Enterprise
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**: 1.15.0
- **Python version**: 3.6.6.
- **Exact command to reproduce**:

      import mlflow
      from azureml.core import Workspace
      from azureml.core.authentication import ServicePrincipalAuthentication
   
      svc_pr=ServicePrincipalAuthentication(
                  tenant_id="my-tenant-id-here",
                  service_principal_id="my-principal-id-here",
                  service_principal_password="my-service-principal-pw-here")
      
      ws=Workspace(
                  subscription_id='my-subscription-id-here',
                  resource_group='my-rg',
                  workspace_name="defaultworkspace",
                  auth=svc_pr)
      
      workspace_uri=ws.get_mlflow_tracking_uri()

      mlflow.set_tracking_uri(workspace_uri)
      experiment_name='experiment_with_mlflow'
      mlflow.set_experiment(experiment_name)
      
      withmlflow.start_run():
      mlflow.log_metric('alpha',0.03)

### Describe the problem

 tried to execute an standard azure machine learning / ml flow example to log model params from my local machine into an experiment in my azure ML workspace. I created a service principal for authentication wich works without errors. Also the init of the workspace object works as expected. But when calling the get_mlflow_tracking_uri I get the error attached below.
I am behind a corporate proxy. Also monkey patching proxy settings in request lib didnt change the outcome.

I also have an ml flow instance on my maschine.
All the ml flow related parts work fine when I set the tracking uri to my local instance.

My problem is that I simply dont get the tracking uri with that get_mlflow_tracking_uri method.

If this problem cant be solved: Is there another way to get the tracking uri for a AML workspace?
Even with az cli/ azure web ui I couldnt find the uri.

### Other info / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "C:\develop\venv\venv_repo\all_venv\lib\site-packages\requests\adapters.py", line 449, in send
        timeout=timeout
      File "C:\develop\venv\venv_repo\all_venv\lib\site-packages\urllib3\connectionpool.py", line 756, in urlopen
        method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
      File "C:\develop\venv\venv_repo\all_venv\lib\site-packages\urllib3\util\retry.py", line 532, in increment
        raise six.reraise(type(error), error, _stacktrace)
      File "C:\develop\venv\venv_repo\all_venv\lib\site-packages\urllib3\packages\six.py", line 734, in reraise
        raise value.with_traceback(tb)
      File "C:\develop\venv\venv_repo\all_venv\lib\site-packages\urllib3\connectionpool.py", line 706, in urlopen
        chunked=chunked,
      File "C:\develop\venv\venv_repo\all_venv\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
        self._validate_conn(conn)
      File "C:\develop\venv\venv_repo\all_venv\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
        conn.connect()
      File "C:\develop\venv\venv_repo\all_venv\lib\site-packages\urllib3\connection.py", line 421, in connect
        tls_in_tls=tls_in_tls,
      File "C:\develop\venv\venv_repo\all_venv\lib\site-packages\urllib3\util\ssl_.py", line 429, in ssl_wrap_socket
        sock, context, tls_in_tls, server_hostname=server_hostname
      File "C:\develop\venv\venv_repo\all_venv\lib\site-packages\urllib3\util\ssl_.py", line 472, in _ssl_wrap_socket_impl
        return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
      File "C:\develop\Microsoft Visual Studio\Shared\Python36_64\lib\ssl.py", line 407, in wrap_socket
        _context=self, _session=session)
      File "C:\develop\Microsoft Visual Studio\Shared\Python36_64\lib\ssl.py", line 814, in __init__
        self.do_handshake()
      File "C:\develop\Microsoft Visual Studio\Shared\Python36_64\lib\ssl.py", line 1068, in do_handshake
        self._sslobj.do_handshake()
      File "C:\develop\Microsoft Visual Studio\Shared\Python36_64\lib\ssl.py", line 689, in do_handshake
        self._sslobj.do_handshake()
    urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054,
    “Connection forcibly closed by remote host”, None, 10054, None))
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "C:/develop/vssource/devops/Persoenlich_Deka/MlFlowPoC/az_AML.py", line 22, in <module>
        workspace_uri = ws.get_mlflow_tracking_uri()
      File "C:\develop\venv\venv_repo\all_venv\lib\site-packages\azureml\core\workspace.py", line 1072, in get_mlflow_tracking_uri
        return get_mlflow_tracking_uri(self)
      File "C:\develop\venv\venv_repo\all_venv\lib\site-packages\azureml\mlflow\__init__.py", line 59, in get_mlflow_tracking_uri
        parse.urlparse(workspace.service_context._get_run_history_url()).netloc)
      File "C:\develop\venv\venv_repo\all_venv\lib\site-packages\azureml\core\workspace.py", line 818, in service_context
        self._auth)
      File "C:\develop\venv\venv_repo\all_venv\lib\site-packages\azureml\_restclient\service_context.py", line 168, in __init__
        self._endpoints = self._fetch_endpoints()
      File "C:\develop\venv\venv_repo\all_venv\lib\site-packages\azureml\_restclient\service_context.py", line 295, in _fetch_endpoints
        service_name=discovery_key)
      File "C:\develop\venv\venv_repo\all_venv\lib\site-packages\azureml\_base_sdk_common\service_discovery.py", line 121, in get_service_url
        unique_id=workspace_id, discovery_url=workspace_discovery_url)
      File "C:\develop\venv\venv_repo\all_venv\lib\site-packages\azureml\_base_sdk_common\service_discovery.py", line 283, in get_cached_service_url
        discovery_url=discovery_url)[service_name]
      File "C:\develop\venv\venv_repo\all_venv\lib\site-packages\azureml\_base_sdk_common\service_discovery.py", line 182, in wrapper
        return test_function(self, *args, **kwargs)
      File "C:\develop\venv\venv_repo\all_venv\lib\site-packages\azureml\_base_sdk_common\service_discovery.py", line 257, in get_cached_services_uris
        cache[cache_key][DEFAULT_FLIGHT] = super(CachedServiceDiscovery, self).discover_services_uris_from_arm_scope(arm_scope, discovery_url)
      File "C:\develop\venv\venv_repo\all_venv\lib\site-packages\azureml\_base_sdk_common\service_discovery.py", line 138, in discover_services_uris_from_arm_scope
        return self.discover_services_uris(discovery_url)
      File "C:\develop\venv\venv_repo\all_venv\lib\site-packages\azureml\_base_sdk_common\service_discovery.py", line 141, in discover_services_uris
        status = ClientBase._execute_func(requests.get, discovery_url)
      File "C:\develop\venv\venv_repo\all_venv\lib\site-packages\azureml\_restclient\clientbase.py", line 375, in _execute_func
        DEFAULT_SHORT_BACKOFF, DEFAULT_RETRIES, module_logger, func, _noop_reset, *args, **kwargs)
      File "C:\develop\venv\venv_repo\all_venv\lib\site-packages\azureml\_restclient\clientbase.py", line 367, in _execute_func_internal
        left_retry = cls._handle_retry(back_off, left_retry, total_retry, error, logger, func)
      File "C:\develop\venv\venv_repo\all_venv\lib\site-packages\azureml\_restclient\clientbase.py", line 399, in _handle_retry
        raise error
      File "C:\develop\venv\venv_repo\all_venv\lib\site-packages\azureml\_restclient\clientbase.py", line 358, in _execute_func_internal
        response = func(*args, **kwargs)
      File "C:\develop\venv\venv_repo\all_venv\lib\site-packages\requests\api.py", line 76, in get
        return request('get', url, params=params, **kwargs)
      File "C:\develop\venv\venv_repo\all_venv\lib\site-packages\requests\api.py", line 61, in request
        return session.request(method=method, url=url, **kwargs)
      File "C:\develop\venv\venv_repo\all_venv\lib\site-packages\requests\sessions.py", line 542, in request
        resp = self.send(prep, **send_kwargs)
      File "C:\develop\venv\venv_repo\all_venv\lib\site-packages\requests\sessions.py", line 655, in send
        r = adapter.send(request, **kwargs)
      File "C:\develop\venv\venv_repo\all_venv\lib\site-packages\requests\adapters.py", line 498, in send
        raise ConnectionError(err, request=request)
    requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'Connection forcibly closed by remote host', None, 10054, None))
    
    

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

Language 
- [X ] `language/Python`: Python APIs and clients

Integrations
- [X] `integrations/azure`: Azure and Azure ML integrations

**Comment by codingmercy1993** [comment]
our proxy was down...resolved

FML
