### ISSUE TITLE
[FR] Adding a functionality to move runs to different experiments

### ISSUE THREAD

**Issue by edwardcqian** [mlflow/mlflow#4307]
## Willingness to contribute
The MLflow Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature (either as an MLflow Plugin or an enhancement to the MLflow code base)?

- [x] Yes. I can contribute this feature independently.
- [ ] Yes. I would be willing to contribute this feature with guidance from the MLflow community.
- [ ] No. I cannot contribute this feature at this time.

## Proposal Summary
Adding a functionality in both the UI and API to move a tracking run to a different experiment.

## Motivation
- What is the use case for this feature?
Often it's nice to be able to reorganize experiments. For example scope may change mid experiment, or by mistake a run is logged to the wrong place.
- Why is this use case valuable to support for MLflow users in general?
Currently there is no functionality to organize experiment. It's only create, log and delete.
- Why is this use case valuable to support for your project(s) or organization?
We currently move run folders manually, this is quite hacky and mistakes can happen, an formal solution.
- Why is it currently difficult to achieve this use case? (please be as specific as possible about why related MLflow features and components are insufficient)
There is currently no clean move functionality within MLflow (UI or API)

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [x] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

## Details
- Adding move button and API calls in UI
- Adding move endpoint in REST API
- Adding move functionality for local tracking and DB (python and java?)

**Comment by AveshCSingh** [comment]
Hi @edwardcqian. Thanks for filing this issue and drafting an implementation.

Per [CONTRIBUTING.rst](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst#write-designs-for-significant-changes):

`The MLflow REST API is implemented by a variety of open source and proprietary platforms. Changes to the REST API impact all of these platforms. Accordingly, we encourage developers to thoroughly explore alternatives before attempting to introduce REST API changes.`

Is moving runs between experiments is a common enough workflow to justify introducing a new API?

I think a good place to start is to write a design document. This should address the above question (eg in a Motivation section), then should discuss API changes, UI changes, client changes, testing, etc. We will need some community support, eg via 👍 's on this issue, as well as consensus on the API changes from various implementers of the MLflow API.

**Comment by jinzhang21** [comment]
Hi Edward, to address the need of moving runs, please consider using this project to export and import experiment and runs for MLflow: https://github.com/amesar/mlflow-export-import

Thanks a lot for contributing to MLflow. Closing the FR for now.
