### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by anjsam1402** [mlflow/mlflow#4355]
### System information
- **OS Platform and Distribution**: MLflow docker image based on 'python:3.9-slim-buster'. Deployed in k8s cluster.
- **MLflow installed from**: official pip \ pypi
- **MLflow version**: 1.16.0
- **MLflow backend store**: AWS RDS MySQL
- **MLflow artifact root**: AWS S3 bucket
- **Python version**: 3.9
- ** command** : `mlflow server --host 0.0.0.0  --port 5000 --default-artifact-root ${BUCKET}  --backend-store-uri mysql+pymysql://${USERNAME}:${PASSWORD}@${HOST}:${PORT}/${DATABASE}`

### Describe the problem
I wish to maintain high availability of MLFlow Tracking Server and Model Registry. 
How can I do that without facing write transactions issues or deadlocks?

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [X] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

**Comment by dmatrix** [comment]
@anjsam1402 Thanks for filing this. I would not consider this a bug. It's a feature that's absent in the OSS version of MLflow.  The managed offering on Databricks offers enterprises features that you would expect with a high number of transactions, queries, or 
interactions. 

Since the tracking server is stateless, you could load balance it so long as it writes to the same backend stores. This would be more or less best practices how you would deploy it in production.
