### ISSUE TITLE
[BUG] Git repository names containing the string _git have broken hyperlinks in MLflow UI

### ISSUE THREAD

**Issue by douglaswja** [mlflow/mlflow#4395]
### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [x] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: Yes, a python print statement and push this to git repository.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **MLflow installed from (source or binary)**: `pip install mlflow`
- **MLflow version (run ``mlflow --version``)**: 1.17.0
- **Python version**: 3.8.8

### Describe the problem
If the string `_git` occurs in any part of a git repository name, the first instance of it is omitted from hyperlinks in ML Flow UI that are intended to point to that repository.

For example, `https://github.com/douglaswja/_mlflow_git.git` becomes `https://github.com/douglaswja/_mlflow.git` in the ML Flow UI as shown in the screenshot below (Source name at top right, URL at bottom left).

I have attempted renaming my repository various combinations and can confirm that neither the length of the repository name  nor the number of underscores in the name seem to cause any problems, only the occurrence of `_git`.

The problem causes the hyperlink in MLFlow UI to not work and lead to a 404 page instead.

![image](https://user-images.githubusercontent.com/27340314/119678579-38988180-be72-11eb-92e3-d84c0dd0c56a.png)

### Code to reproduce issue
1. Initialise a local git repository
2. Create MLproject file with main entry point to some random .py file (i.e. a one-line file with `print("Hello world")`)
3. `git remote add origin ORIGIN_URL_HERE` a git repository with `_git` in its repository name
4. `mlflow run GIT_URL` i.e. run the project from its git url
5. `mlflow ui` open the mlflow UI
6. Navigate to that run and click on its source link.

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [x] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

**Comment by takabayashi** [comment]
The PR is here https://github.com/mlflow/mlflow/pull/4403

**Comment by AveshCSingh** [comment]
Closing this out since the issue has been resolved.
