### ISSUE TITLE
[BUG] Tracking: DB connection are not released when using log_param repeatedly

### ISSUE THREAD

**Issue by sebchr** [mlflow/mlflow#4489]
### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [x] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10 Version 10.0.19041 Build 19041
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**: mlflow, version 1.18.0
- **Python version**: Python 3.8.10
- **npm version, if running the dev UI**:
- **Exact command to reproduce**:

### Describe the problem
After logging ~80 parameters to the postgres tracking database, the number of available connections is exhausted, and I get the following error:
```
2021/06/21 14:21:00 WARNING mlflow.store.db.utils: SQLAlchemy engine could not be created. The following exception is caught.
(psycopg2.OperationalError) FATAL:  too many connections for role "zibvebrgldjyaa"

(Background on this error at: http://sqlalche.me/e/14/e3q8)
Operation will be retried in 0.1 seconds
```
Only 20 connections are available because I'm using a [Heroku Free-tier postgres database](https://elements.heroku.com/addons/heroku-postgresql). I'm the only one accessing the database and using `select * from pg_stat_activity where datname = 'dbname'` I can confirm that all connections are created by mlflow.

  I expected mlflow would use a constant and low number of connections. I did not see any improvement when setting `MLFLOW_SQLALCHEMYSTORE_POOL_SIZE` and `MLFLOW_SQLALCHEMYSTORE_MAX_OVERFLOW` environment variables.

The  version of the postgres database is: `PostgreSQL 13.3 (Ubuntu 13.3-1.pgdg20.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, 64-bit`

### Code to reproduce issue
Minimal example:
```python
import logging
import mlflow

logging.basicConfig(level=logging.INFO)

if __name__ == "__main__":
    with mlflow.start_run(run_name='test'):
        for i in range(100):
            mlflow.log_param(f"test_run_count {i}", i)
```
the same problem is encountered when logging across multiple runs.

Minimal example with connection counting:
```python
import logging
import os

import mlflow
import pandas as pd

logging.basicConfig(level=logging.INFO)


def count_connections():
    uri = os.getenv('MLFLOW_TRACKING_URI')
    dbname = uri.rsplit('/', 1)[-1]
    query = f"""select *
                from pg_stat_activity
                where datname = '{dbname}';"""
    df = pd.read_sql(query, uri)
    return len(df)


if __name__ == "__main__":
    with mlflow.start_run(run_name='test'):
        for i in range(100):
            mlflow.log_param(f"test_run_count {i}", i)
            logging.info(f'{count_connections()} connections')

```
The number of connections is slowly increasing toward the limit of 20. The increase is not monotonically increasing, after the first 10 parameters the number of active connections is: 6,8,6,8,9,10,7,9,10,11
### Other info / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [x] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [x] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by arpitjasa-db** [comment]
Fixed with https://github.com/mlflow/mlflow/pull/4663.
