### ISSUE TITLE
[BUG] Unable to log metrics, artifacts while using MLFlow Project in Docker environment

### ISSUE THREAD

**Issue by kusur** [mlflow/mlflow#4535]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md) for additional information about bug reports. For help with debugging your code, please refer to [Stack Overflow](https://stackoverflow.com/questions/tagged/mlflow).

**Please fill in this bug report template to ensure a timely and thorough response.**

### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [x] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Alpine
- **MLflow installed from (source or binary)**: pip
- **MLflow version (run ``mlflow --version``)**: 1.18.0
- **Python version**:3.8.10
- **npm version, if running the dev UI**: NA
- **Exact command to reproduce**: mlflow run .

### Describe the problem

I am trying to store metrics and artifacts on host after running MLProject in a docker environment.

Expected: artifacts, metrics folders in mlruns/ folder should have values and be shown on mlflow ui

Actual: The experiment completes successfully but artifacts, metrics folders in mlruns/ folder are empty. mlflow ui is also not reflecting the new experiment

### Code to reproduce issue

/home/mlflow_demo/mlflow-demo.py - 

import mlflow
from mlflow.tracking import MlflowClient
from random import random
import pickle

client = MlflowClient()
experiment_id = client.create_experiment(name='first experiment')
run = client.create_run(experiment_id=experiment_id)
for i in range(1000):
    client.log_metric(run.info.run_id,"foo",random(),step=i)
with open("test.txt","w") as f:
    f.write("This is an artifact file")
client.log_artifact(run.info.run_id,"test.txt")
client.set_terminated(run.info.run_id)

/home/mlflow_demo/mlflow-demo.py - 

name: test-project
docker_env: 
 image: kusur/apex-pytorch-image:latest
entry_points:
 main:
  command: "python mlflow-demo.py"

command (executed in /home/mlflow_demo): - mlflow run .

### Other info / logs

2021/07/06 12:22:28 INFO mlflow.projects.docker: === Building docker image test-project ===
2021/07/06 12:22:28 INFO mlflow.projects.utils: === Created directory /home/mlflow_demo/mlruns/tmpwa8ydc5j for downloading remote URIs passed to arguments of type 'path' ===
2021/07/06 12:22:28 INFO mlflow.projects.backend.local: === Running command 'docker run --rm -v /home/mlflow_demo/mlruns:/mlflow/tmp/mlruns -v /home/mlflow_demo/mlruns/0/0978fdd89ba44bf7b49975ab84838e82/artifacts:/home/mlflow_demo/mlruns/0/0978fdd89ba44bf7b49975ab84838e82/artifacts -e MLFLOW_RUN_ID=0978fdd89ba44bf7b49975ab84838e82 -e MLFLOW_TRACKING_URI=file:///mlflow/tmp/mlruns -e MLFLOW_EXPERIMENT_ID=0 test-project:latest python mlflow-demo.py' in run with ID '0978fdd89ba44bf7b49975ab84838e82' ===

...

2021/07/06 12:22:33 INFO mlflow.projects: === Run (ID '0978fdd89ba44bf7b49975ab84838e82') succeeded ===

Even after successful completion of the experiment, artifact, metrics folder in mlruns/0/0978fdd89ba44bf7b49975ab84838e82 are empty

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [x] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [x] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [x] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by jamaliki** [comment]
Do you have an mlruns folder show up at all? Could this be because you are not mounting a folder to the docker container so the data is getting lost?

**Comment by kusur** [comment]
Yes the mlruns folder does get created. In fact the meta.yml file also gets created and all the details in it are correct. Still no logging is happening

**Comment by jamaliki** [comment]
Can you try instead of `experiment_id = client.create_experiment(name='first experiment')`, doing `experiment_id = "0"`

**Comment by kusur** [comment]
Closing this issue as I solved it using docker-compose
