### ISSUE TITLE
[FR] adjustable width experiments sidebar in tracking server UI

### ISSUE THREAD

**Issue by addisonklinke** [mlflow/mlflow#4587]
## Willingness to contribute
The MLflow Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature (either as an MLflow Plugin or an enhancement to the MLflow code base)?

- [ ] Yes. I can contribute this feature independently.
- [ ] Yes. I would be willing to contribute this feature with guidance from the MLflow community.
- [x] No. I cannot contribute this feature at this time.

## Proposal Summary

Make the width of experiments list sidebar in the tracking server UI adjustable (via a handle which shows when you hover the mouse on the right border)

<img src="https://user-images.githubusercontent.com/39926682/126555363-a3cf45c3-ef30-48f7-9152-c71dd42fcf10.png" width="40%" height="40%">

## Motivation

- What is the use case for this feature?

This would make it possible to view the full experiment names

- Why is this use case valuable to support for MLflow users in general?

Currently, longer names get truncated and there's no way to view the full names simultaneously for all experiments in the list. If you hover a given name, there is a tool tip that shows the full name, but that doesn't allow you to look at multiple at once. Requiring the user to hover their mouse over each one in the list is tedious

- Why is this use case valuable to support for your project(s) or organization?

We plan to use a naming schema to organize large numbers of experiments and make them easier to query programmatically. For example, `modeling_task/architecture/[feature,release]/title`. As seen in the screenshot, most of these are too long to display at the current fixed width. I imagine a naming schema is common practice at many other organizations as well

- Why is it currently difficult to achieve this use case? (please be as specific as possible about why related MLflow features and components are insufficient)

There is no drag-able handle to adjust the sidebar width, and zooming out in the browser doesn't help either

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [x] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by zacfeng** [comment]
It will be very beneficial if the UI is adjustable.

**Comment by RicoSuaveGuapo** [comment]
I think anyone conducting numerous experiments would surely appreciate the introduction of this feature

**Comment by WilliamCCHuang** [comment]
Experiment names are usually too long to display completely in the sidebar. So if this feature is implemented, it would make mlflow more convenient.
