### ISSUE TITLE
[BUG] logging pytorch model hits tag size limit

### ISSUE THREAD

**Issue by pietermarsman** [mlflow/mlflow#4702]
### Willingness to contribute

I'm willing to contribute. I can fix the bug with some guidance on what the preferred solution would be. 

### System information
Ubuntu 20.04

- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.04
- **MLflow installed from (source or binary)**: With pip
- **MLflow version (run ``mlflow --version``)**: mlflow, version 1.18.0
- **Python version**: Python 3.8.10

### Describe the problem

This error raised when logging a pytorch artifact with [mlflow.pytorch.log_model](https://www.mlflow.org/docs/latest/python_api/mlflow.pytorch.html#mlflow.pytorch.log_model)

```
2021/08/14 09:27:55 ERROR mlflow.utils.rest_utils: API request to http://localhost:5000/api/2.0/mlflow/runs/log-model failed with code 500 != 200, retrying up to 2 more times. API response body: {"error_code": "INTERNAL_ERROR", "message": "Tag value '[{\"run_id\": \"e6d28c2c8c7a48808f63ab0a8766dc1c\", \"artifact_path\": \"models\", \"utc_time_created\": \
"2021-08-12 16:50:32.052540\", \"flavors\": {\"pytorch\": {\"model_data\": \"data\", \"pytorch_version\": \"1.7.1+cu110\"}, \"python_function\": {\"pickle_module_name\": \"m' had length 5348,
 which exceeded length limit of 5000"}
```

### Code to reproduce issue

I can't get a small reproducible example. I don't know why the data for this API request is so long. I litteraly use the following line to log the pytorch model, where fit.model is a pytorch `nn.Module`. 

```
        mlflow.pytorch.log_model(fit.model, self.model_dir)
```

I suspect our training code does somethign to the pytorch net which makes the log really long and therefore it can't be stored in a tag, which is what mlflow is using to store their model information. 

### Other info / logs
-

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [x] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [x] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by pietermarsman** [comment]
I missed the warning in the next line:
```
2021/08/16 10:40:28 WARNING mlflow.models.model: Logging model metadata to the tracking server has failed, possibly due older server version. The model artifacts have been logged successful
ly under mlflow/9/d6729c5f0f554316b388d4f63697d8c9/artifacts. In addition to exporting model artifacts, MLflow clients 1.7.0 and above attempt to record mod
el metadata to the  tracking store. If logging to a mlflow server via REST, consider  upgrading the server version to MLflow 1.7.0 or above. 
```

I know what to do now: update server version! :)
