### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by thomassantosh** [mlflow/mlflow#4792]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md) for additional information about bug reports. For help with debugging your code, please refer to [Stack Overflow](https://stackoverflow.com/questions/tagged/mlflow).

**Please fill in this bug report template to ensure a timely and thorough response.**

### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [X] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: Slight variation from a stock example in that it is using an R script, vs. the normal python ones
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 18.04.5 LTS (Bionic Beaver)
- **MLflow installed from (source or binary)**: Installed via ```conda install -c conda-forge r-mlflow```
- **MLflow version (run ``mlflow --version``)**: mlflow, version 1.20.2
- **Python version**: Python 3.8.11
- **npm version, if running the dev UI**: n/a
- **Exact command to reproduce**: n/a

### Describe the problem
- I'm not able to complete a successful ML Flow run, with AzureML, mlflow, and an R training script.
- I have two script files:
    - "main.py" (a Python script to leverage Azure ML & mlflow as the backend for experiments/runs)
    - "train.R" (an R script to build a model to predict wine quality).
- The dataset is taken from this source: https://github.com/mlflow/mlflow/blob/master/examples/r_wine/wine-quality.csv.
- There are two issues I'm getting depending upon how I configure the ```backend``` parameter in the ```mlflow.projects.run()```. 

If I configure it as ```backend='azureml'```, I get the following error:
```
Traceback (most recent call last):
  File "main.py", line 88, in <module>
    main()
  File "main.py", line 75, in main
    remote_mlflow_run = mlflow.projects.run(
  File "/anaconda/envs/mlflow/lib/python3.8/site-packages/mlflow/projects/__init__.py", line 293, in run
    submitted_run_obj = _run(
  File "/anaconda/envs/mlflow/lib/python3.8/site-packages/mlflow/projects/__init__.py", line 92, in _run
    submitted_run = backend.run(
  File "/anaconda/envs/mlflow/lib/python3.8/site-packages/azureml/mlflow/_internal/projects.py", line 194, in run
    registered_env = remote_environment.register(workspace=workspace)
AttributeError: 'NoneType' object has no attribute 'register'
```
If I configure it as ```backend='local'``` it processes further but errrors out right before the first mlflow log statement:
```
...2021/09/11 23:45:53 INFO mlflow.projects.utils: === Created directory /tmp/tmpndw2jjpm for downloading remote URIs passed to arguments of type 'path' ===
2021/09/11 23:45:53 INFO mlflow.projects.backend.local: === Running command 'Rscript -e "mlflow::mlflow_source('train.R')" --args' in run with ID '859a1942-811f-4903-bdf9-5794f9903c3e' === 
Registered S3 method overwritten by 'openssl':
  method      from
  print.bytes Rcpp
  [1] 4873 4196 4838 2518 4057 3642 4685 1204  723 2348 1128 1244 3298 4044  284
 [16] 1868 3025 2619 3891 3694 2477 2246 1031 3054 3923 4457 4674 2082   99 2221
 [31] 1507  217 2150 2084  191 1710 4265 2994  962 4691 2106 4211 3974 1669 3681
 [46] 4725 1575 2955 2733 3810 1319 4802 2683 3899 4246 1030  710  556 2498 2778
 [61] 4348  847  920 2062  563 1074 4694 2044 2849 1582 4418 4790 2078 4481 2588
 [76] 2706 3839 3024 1350  340 1749 3269 2264   87 4479 2519   31 4126  438  996
 [91] 3659 3598  685 1494 3004 2509 2561 4504 3438 3902 3241 3187 1242  218 4689
[106] 4452 4742 1035 4465 2590 2230 1129 3329 3524  437 4229 2829 2016 1714 3255
[121] 1955   95 3563 1070 1037 1784 2298 1638 2646  904 2878 3310 1510 4621 4512
[136] 3920 3305 1732 1417 4142 2907 4853 4056 3006 4063 1072 1533 3823 1064  641
[151] 1379 1386 4217 1709  461 3675 2060 4176 3391 2419 4681 2670 3897 2899 4539
[166]  818 3601 1419 1916  829 2328   20 4326 2067 3316 4646  361 2795 1198 4210
[181] 2700 1434 2864 4425 2198  711 2226 1188 2964 3504 4667 1086  425 2132  336
[196]  951  926 1599 3194  779 3184  308 2535 1752  211 4025  152 3718 4770  450
[211] 1248 2952  482 1195 1835 2681 1648 2344 1315 4710  627 3776 2239 2381   15
[226] 4460 1711 1489  314 1338 4534 1361 2583 3188 4830 2398 4172   89 3021 1259
[241] 3892 2210 3732 3715
[1] "before split of train/test"
Error in new_mlflow_client.default(tracking_uri): Unsupported scheme: 'azureml'

Error: There is no active run to end.
In addition: Warning message:
package ‘mlflow’ was built under R version 3.6.3 
Execution halted
Traceback (most recent call last):
  File "main.py", line 88, in <module>
    main()
  File "main.py", line 75, in main
    remote_mlflow_run = mlflow.projects.run(
  File "/anaconda/envs/mlflow/lib/python3.8/site-packages/mlflow/projects/__init__.py", line 307, in run
    _wait_for(submitted_run_obj)
  File "/anaconda/envs/mlflow/lib/python3.8/site-packages/mlflow/projects/__init__.py", line 324, in _wait_for
    raise ExecutionException("Run (ID '%s') failed" % run_id)
mlflow.exceptions.ExecutionException: Run (ID '859a1942-811f-4903-bdf9-5794f9903c3e') failed
```

### Code to reproduce issue
main.py
```python
## Authentication is through a service principal, and the 'workspace' object is brought in from a diff script
## The cluster mentioned below is a remote cluster
from authentication import ws
import mlflow
import mlflow.azureml
from azureml.core import Workspace, Dataset
from azureml.core.compute import ComputeTarget, ComputeInstance, AmlCompute
from azureml.core.compute_target import ComputeTargetException
from azureml.core.environment import Environment
from azureml.core import Experiment, ScriptRunConfig
from azureml.core import Dataset

def main():
    tracking_uri = ws.get_mlflow_tracking_uri()
    print(f'MLFLOW TRACKING URI: {tracking_uri}')
    mlflow.set_tracking_uri(tracking_uri)

    experiment_name = "matrix7"
    mlflow.set_experiment(experiment_name)
    backend_config = {"COMPUTE": "newcluster1", "USE_CONDA": True}

    remote_mlflow_run = mlflow.projects.run(
            uri='.',
            #entry_point='Rscript train.R',
            entry_point='train.R',
            backend = "local",
            #backend = "azureml",
            backend_config = backend_config,
            use_conda = False
            )

if __name__ == "__main__":
    main()
```

train.R
```R
#library(argparse)
library(mlflow)
library(glmnet)
library(carrier)
#mlflow::install_mlflow()
#set.seed(40)
#parser <- ArgumentParser(description='Input, and output filepaths')
#parser$add_argument('--input_file_path', help='The input file path')
#parser$add_argument('--output_file_path', help='The output file path')
#args <- parser$parse_args()

#data <- read.csv(file.path(args$input_file_path,"wine_quality.csv"))
data <- read.csv("wine_quality.csv")
sdata <- sample(1:nrow(data),0.05 * nrow(data))
print(sdata)

# Split the data into training and test sets. (0.75, 0.25) split.
sampled <- sample(1:nrow(data), 0.75 * nrow(data))
train <- data[sampled, ]
test <- data[-sampled, ]

# The predicted column is "quality" which is a scalar from [3, 9]
train_x <- as.matrix(train[, !(names(train) == "quality")])
test_x <- as.matrix(test[, !(names(train) == "quality")])
train_y <- train[, "quality"]
test_y <- test[, "quality"]

alpha <- mlflow_param("alpha", 0.5, "numeric")
lambda <- mlflow_param("lambda", 0.5, "numeric")

print("before split of train/test")
mlflow_log_param("alpha",alpha)
mlflow_log_param("lambda",lambda)
mlflow_log_metric("r2",1.00)

#with(mlflow_start_run(), {
#    model <- glmnet(train_x, train_y, alpha = alpha,lambda = lambda, family= "gaussian", standardize = FALSE)
#    predictor <- crate(~ glmnet::predict.glmnet(!!model, as.matrix(.x)), !!model)
#    predicted <- predictor(test_x)

#    rmse <- sqrt(mean((predicted - test_y) ^ 2))
#    mae <- mean(abs(predicted - test_y))
#    r2 <- as.numeric(cor(predicted, test_y) ^ 2)

#    message("Elasticnet model (alpha=", alpha, ", lambda=", lambda, "):")
#    message("  RMSE: ", rmse)
#    message("  MAE: ", mae)
#    message("  R2: ", r2)

#    mlflow_log_param("alpha", alpha)
#    mlflow_log_param("lambda", lambda)
#    mlflow_log_metric("rmse", rmse)
#    mlflow_log_metric("r2", r2)
#    mlflow_log_metric("mae", mae)
#    print("this far")
#    #mlflow_log_model(predictor, "model")
#}) 
```

### Other info / logs
Details of traceback shown above.

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [X] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [X] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by thomassantosh** [comment]
Also, in the case of the first issue, this seems very similar to this issue: https://github.com/criteo/mlflow-elasticsearchstore/issues/58

**Comment by AveshCSingh** [comment]
Hi @thomassantosh . It looks like you might be setting your tracking URI to "azureml". The supported tracking URIs can be found here: https://www.mlflow.org/docs/latest/python_api/mlflow.html#mlflow.set_tracking_uri
