### ISSUE TITLE
[DOC-FIX] MLflow tracking documentation for scenario 3 and 4 are confusing

### ISSUE THREAD

**Issue by Amr-devman** [mlflow/mlflow#4793]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md) for information on what types of issues we address.

**Please fill in this documentation issue template to ensure a timely and thorough response.**

### Willingness to contribute
The MLflow Community encourages documentation fix contributions. Would you or another member of your organization be willing to contribute a fix for this documentation issue to the MLflow code base?

- [ ] Yes. I can contribute a documentation fix independently.
- [x] Yes. I would be willing to contribute a document fix with guidance from the MLflow community.
- [ ] No. I cannot contribute a documentation fix at this time.

### URL(s) with the issue:

https://www.mlflow.org/docs/latest/tracking.html

### Description of proposal (what needs changing):

Scenario 4 has a syntax error that can cause many issues Artifact logging. 

![image](https://user-images.githubusercontent.com/27409084/133038582-2b66ca28-8d62-4387-934f-b3520971d0c7.png)

the `--default-artifact-root` value should start with `s3://...` instead of `S3:/...` . The documentation for scenario 3 and scenario 4 would heavily benefit from example commands that the user can modify rather than having the command written in the image.

An example that can be added to the doc would be:

```bash
 mlflow server \
--backend-store-uri mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql_db:3306/${MYSQL_DATABASE} \
--default-artifact-root s3://<bucket-name> \
--host 0.0.0.0
```
