### ISSUE TITLE
[BUG] R API not able to find the sqlite tracking server URI. failing with Unsupported scheme error

### ISSUE THREAD

**Issue by smothiki** [mlflow/mlflow#4815]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md) for additional information about bug reports. For help with debugging your code, please refer to [Stack Overflow](https://stackoverflow.com/questions/tagged/mlflow).

**Please fill in this bug report template to ensure a timely and thorough response.**

### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [X] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  Linux, Ubuntu 
- **MLflow installed from (source or binary)**: pip [python] and install.packages("mlflow") [R]
- **MLflow version (run ``mlflow --version``)**: mlflow, version 1.20.2
- **Python version**:  Python 3.6.13 , R 3.6
- **npm version, if running the dev UI**:
- **Exact command to reproduce**:

### Describe the problem
Using R API for mlflow with the above mentioned information. Not able to set tracking URI to sqlite. Getting the following error
 ```
Error in new_mlflow_client.default(tracking_uri) : 
  Unsupported scheme: 'sqlite'
```

### Code to reproduce issue
```
library(mlflow)
mlflow_client(tracking_uri="sqlite:///mlflow.db")
```

### Other info / logs
We have installed mlflow R API via `install.packages('mlflow')`. Not just sqlite but we also have a custom
tracking server plugin which was working with python but was never able to  get it working  with R.
Failing with the same error mentioned above `Unsupported scheme:`. 

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [X] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by smothiki** [comment]
Just wanted to know if there is any update on the issue

**Comment by AveshCSingh** [comment]
Tagging @lorenzwalthert or @yitao-li , who are more familiar with R.
