### ISSUE TITLE
[FR] Simplify model registration in autolog

### ISSUE THREAD

**Issue by mmaitre314** [mlflow/mlflow#4829]
## Willingness to contribute
The MLflow Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature (either as an MLflow Plugin or an enhancement to the MLflow code base)?

- [ ] Yes. I can contribute this feature independently.
- [X] Yes. I would be willing to contribute this feature with guidance from the MLflow community.
- [ ] No. I cannot contribute this feature at this time.

## Proposal Summary

`autolog()` makes tracking a lot simpler but it does not seem to provide an option to register models. That leads to code like this where the user needs to format a `runs:/` URL to be able to register the model, which is pretty user-unfriendly. Ideally, model registration would also not require special-casing `file:` during local runs.

```python
import mlflow
import mlflow.sklearn
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error

# Setup MLFlow tracking
mlflow.sklearn.autolog()

# Load data
X, y = load_diabetes(return_X_y = True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

with mlflow.start_run() as run:
    # Train model
    model = Ridge(alpha=0.03)
    model.fit(X_train, y_train)

    # Test model
    mse = mean_squared_error(model.predict(X_test), y_test)
    mlflow.log_metric("test_mse", mse)

    # Register model
    if not(mlflow.get_tracking_uri().startswith('file:')):
        mlflow.register_model(f"runs:/{run.info.run_id}/model", "my_model")
```

## Motivation
- What is the use case for this feature?

Simplify model registration.

- Why is this use case valuable to support for MLflow users in general?

This creates a barrier to entry for new users: I had to spend quite some time figuring out the right string-format incantation.

- Why is this use case valuable to support for your project(s) or organization?

I am trying to evangelize more rigorous MLOps processes and extra complexity reduces appeal.

- Why is it currently difficult to achieve this use case? (please be as specific as possible about why related MLflow features and components are insufficient)

String formatting is very low level and leads to typos difficult to debug.

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

## Details

Implementation-wise, one possibility would be for `mlflow.register_model()` to accept a `run` object as input, or for `autolog()` to give an option to register models.

Note sure how to deal with the `file:` special-case. Maybe log instead of failing (or implement model registration in `file:` but that's likely larger work).

**Comment by WeichenXu123** [comment]
If we add `registered_model_name` as autolog arugument, then every time autolog happen it will use the same model register name.  this is an issue.
@dbczumar we need consider how to auto-generate the registered name, (e.g.  {model_class}_{run_id} ) @mmaitre314 any thoughts on how to generate the name ? 

> mlflow.register_model() to accept a run object as input

@mmaitre314 This approach might be not a proper way, and we still face the issue of how to auto-generate the registered name

**Comment by WeichenXu123** [comment]
I propose a new API like:

mlflow.autolog(auto_register_model=True)

```
with mlflow.start_run(registered_model_name='abc'):
  model = sklearn.XXX().fit(...)   # then the model will be registered as name 'abc'
```

@dbczumar @mmaitre314 Thoughts ?

**Comment by jinzhang21** [comment]
How about just adding registered_model_name to autolog API? If it's not empty, register the model when it's being logged.
```
mlflow.autolog(registered_model_name='abc')

with mlflow.start_run():
  model = sklearn.XXX().fit(...)   # A model will be logged and registered as name 'abc'
```
A main concern is what happens if a model is trained twice. Presumably we can increment the version number here for each registered model if it's supported.

**Comment by dbczumar** [comment]
I agree with @jinzhang21 . It makes sense to write all models as new version of a consistent, user-specified `registered_model_name` without requiring the explicit use of `start_run()` .
