### ISSUE TITLE
[BUG] Deployment with AzureML issue.  No plugin found for managing model deployments to "file"

### ISSUE THREAD

**Issue by seankwon1014** [mlflow/mlflow#4849]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md) for additional information about bug reports. For help with debugging your code, please refer to [Stack Overflow](https://stackoverflow.com/questions/tagged/mlflow).

**Please fill in this bug report template to ensure a timely and thorough response.**

### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [x] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows
- **MLflow installed from (source or binary)**: source
- **MLflow version (run ``mlflow --version``)**:  1.20.2
- **Python version**: 3.8
- **npm version, if running the dev UI**:
- **Exact command to reproduce**:

### Describe the problem
Describe the problem clearly here. Include descriptions of the expected behavior and the actual behavior.

I tried to run my deployment.py file but got an error below:

**Traceback (most recent call last):
  File "deploy.py", line 6, in <module>
    client = get_deploy_client(mlflow.get_tracking_uri())
  File "C:\Users\Sihyun\anaconda3\lib\site-packages\mlflow\deployments\interface.py", line 42, in get_deploy_client
    plugin = plugin_store[target]
  File "C:\Users\Sihyun\anaconda3\lib\site-packages\mlflow\deployments\plugin_manager.py", line 82, in __getitem__
    raise MlflowException(msg, error_code=RESOURCE_DOES_NOT_EXIST)
mlflow.exceptions.MlflowException: No plugin found for managing model deployments to "file". In order to deploy models to "file", find and install an appropriate plugin from https://mlflow.org/docs/latest/plugins.html#community-plugins using your package manager (pip, conda etc).**

But I already installed azureml-mlflow. I don't know what plugin I should install.

### Code to reproduce issue
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
`from mlflow.deployments import get_deploy_client
import mlflow
import azureml.mlflow

client = get_deploy_client(mlflow.get_tracking_uri())
model_path = "model"
client.create_deployment(model_uri='runs:/{}/{}'.format(run.id, model_path), name="mlflow-test-aci")`

### Other info / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [x] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [x] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations
