### ISSUE TITLE
[DOC-FIX] spacy tracking using MLflow

### ISSUE THREAD

**Issue by farrandi** [mlflow/mlflow#4953]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md) for information on what types of issues we address.

**Please fill in this documentation issue template to ensure a timely and thorough response.**

### Willingness to contribute
The MLflow Community encourages documentation fix contributions. Would you or another member of your organization be willing to contribute a fix for this documentation issue to the MLflow code base?

- [ ] Yes. I can contribute a documentation fix independently.
- [ ] Yes. I would be willing to contribute a document fix with guidance from the MLflow community.
- [x] No. I cannot contribute a documentation fix at this time.

### URL(s) with the issue:

https://github.com/mlflow/mlflow/tree/master/examples/spacy

### Description of proposal (what needs changing):
The example code above is for the previous spacy version 2. Spacy did an update to version 3 and it changes most of its infrastructure and also how it trains. Spacy now trains its models in the CLW and I could not find any documentation to store metrics/parameters of a model trained in the CLW like how spacy does. 
It would be nice to have it written down as I am having this problem at the moment.
