### ISSUE TITLE
[BUG] mlflow ui can't find experiments

### ISSUE THREAD

**Issue by artuntun** [mlflow/mlflow#5021]
Hi there!

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: yes
- **OS Platform and Distribution: macOS Caralina
- **MLflow installed from**: pip
- **MLflow version**: 1.21.0
- **Python version**: 3.8.2
- **npm version**: 7.5.1
- **Exact command to reproduce**: mlflow ui

### Describe the problem
I am training a pytorch model in my local machine and logging experiments using mlflow with pytorch-lightning and that is working fine. The logs are saved at ./mlruns. However, `mlflow ui` can't really find any experiment.  I opened the ui on the default port 5000 but it shows 0 experiments. 

### Code to reproduce issue
This is how my Trainer and logger class looks
```python
mlf_logger = MLFlowLogger(experiment_name="default")
trainer = Trainer.from_argparse_args(args, gpus=AVAIL_GPUS, progress_bar_refresh_rate=20,
                                     callbacks=callbacks, log_every_n_steps=5, logger=mlf_logger)
```

### Other info / logs
A screenshoot of the mlruns folder
![image](https://user-images.githubusercontent.com/6185894/140717858-fe5e6c5b-c984-4c8d-bda6-e7e4654f103f.png)

A screenshoot of the ui
![image](https://user-images.githubusercontent.com/6185894/140718170-d7b48bd0-582e-4b26-8941-deb31daea3ba.png)

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [X] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Best
Arturo

**Comment by harupy** [comment]
@artuntun It looks like experiment 0 has no runs.

**Comment by harupy** [comment]
Does the same thing happen for experiment 1?

**Comment by artuntun** [comment]
there are two runs for experiment 1. The experiment 0 was created automatically but I don't really understand why

**Comment by harupy** [comment]
Can you see the two runs for experiment 1 on the UI?

**Comment by artuntun** [comment]
I understand now. There are two experiments on the left side both named 'default'. The second one is experiment 1 where I can see all the runs. 

Thanks for the help :)
