### ISSUE TITLE
[BUG] Timestamp created in R Log Model API is an invalid timestamp

### ISSUE THREAD

**Issue by singankit** [mlflow/mlflow#5054]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md) for additional information about bug reports. For help with debugging your code, please refer to [Stack Overflow](https://stackoverflow.com/questions/tagged/mlflow).

**Please fill in this bug report template to ensure a timely and thorough response.**

### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [x] Yes. I can contribute a fix for this bug independently.
- [x] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu18.04, Windows 10
- **MLflow installed from (source or binary)**: MLflow R SDK from https://cloud.r-project.org/
- **MLflow version (run ``mlflow --version``)**: 1.20.2
- **Python version**: NA
- **npm version, if running the dev UI**:
- **Exact command to reproduce**:

### Describe the problem
In R MLflow SDK as a part of mlflow_log_model api call [timestamp](https://github.com/mlflow/mlflow/blob/d6ae84164987e2881cdffdce07f7dcf0e3d94aaa/mlflow/R/mlflow/R/model.R#L57) generated to capture model creation time, is an invalid timestamp string.
 
A sample timestamp string generated is **21-11-11T21:49:25.25.46**. This string cannot be parsed by C# [DateTime.Parse](https://docs.microsoft.com/en-us/dotnet/api/system.datetime.parse?view=net-5.0#System_DateTime_Parse_System_String_) and throws following error **[System.FormatException: String was not recognized as a valid DateTime**

### Code to reproduce issue
1. Run following R code in R Studio to generate a timestamp as generated to [mlflow_log_model ](https://github.com/mlflow/mlflow/blob/d6ae84164987e2881cdffdce07f7dcf0e3d94aaa/mlflow/R/mlflow/R/model.R#L30)API
```R
mlflow_timestamp <- function() {
  withr::with_options(
    c(digits.secs = 2),
    format(
      as.POSIXlt(Sys.time(), tz = "GMT"),
      "%y-%m-%dT%H:%M:%S.%OS"
    )
  )
}

mlflow_timestamp ()
```
2. Copy the timestamp string generated in step 1 and run following C# code
```csharp
using System;
					
public class Program
{
	public static void Main()
	{
				//Corrected Date Format in string
		 		string test = "21-11-11T21:49:25.25.46";
				//Convert the string date value to datetime 
                DateTime DT = DateTime.Parse(test);
		
			 	Console.WriteLine("Value in datetime format : " + DT);
		
	}
}
```

It will result in following error: 
```csharp
Stack Trace:

[System.FormatException: String was not recognized as a valid DateTime.]
   at System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
   at System.DateTime.Parse(String s)
   at Program.Main() :line 10
```
### Other info / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [X] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by lorenzwalthert** [comment]
Hi @singankit ✋ 

Thanks fore reporting. Is the timestamp generated from R model logging API different from the Python API? I am not sure why the C# Parser is relevant here, but in any case, we should strive for consistency in the timestamp across all clients that log to `MLmodel`, so I think if you can provide a PR to align the R client with the Python client timestamp format, it would be more than welcome.

**Comment by singankit** [comment]
Hi @lorenzwalthert sharing the [PR](https://github.com/mlflow/mlflow/pull/5215) for the fix. It is not fully tested yet. I am running into following error (**Package required and available but unsuitable version: 'stringi'**) while setting up R SDK as per the instructions [here](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst#id18).

**Comment by singankit** [comment]
@lorenzwalthert  To answer your question yes there is a difference between timestamp between [python](https://github.com/mlflow/mlflow/blob/c0e0571d280ff19c7de8893e5953adb79a376705/mlflow/models/model.py#L53) and [R](https://github.com/mlflow/mlflow/blob/c0e0571d280ff19c7de8893e5953adb79a376705/mlflow/R/mlflow/R/model.R#L57) client right now.

Timestamp generation in python is equivalent to [d.isoformat(' ')](https://docs.python.org/3/library/datetime.html#datetime.datetime.__str__)  

where as 

R client adds an extra second section using %OS which causes timestamp to be different from what it is in python. A [link ](https://astrostatistics.psu.edu/su07/R/html/base/html/strptime.html)I found which explains %OS

**Comment by lorenzwalthert** [comment]
@singankit thanks. The {stringi} version is upper bounded because of an [older issue](https://github.com/mlflow/mlflow/pull/2288) which is probably resolved now and we should remove the upper bound. You probably had a higher version installed locally, which is why you got the warning. How about removing that maximal version requirement in`DESCRIPTION`in another PR?

**Comment by singankit** [comment]
This issue is fixed in the [PR](https://github.com/mlflow/mlflow/pull/5236). Hence closing it.
