### ISSUE TITLE
[FR] Enable >250 characters for `mlflow.log_params`

### ISSUE THREAD

**Issue by Eleven1Liu** [mlflow/mlflow#5076]
Thank you for submitting a feature request. **Before proceeding, please review MLflow's [Issue Policy for feature requests](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md#feature-requests) and the [MLflow Contributing Guide](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst)**.

**Please fill in this feature request template to ensure a timely and thorough response.**

## Willingness to contribute
The MLflow Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature (either as an MLflow Plugin or an enhancement to the MLflow code base)?

- [x] Yes. I can contribute this feature independently.
- [x] Yes. I would be willing to contribute this feature with guidance from the MLflow community.
- [ ] No. I cannot contribute this feature at this time.

## Proposal Summary
(In a few sentences, provide a clear, high-level description of the feature request)
Enable `mlflow.log_params` to log parameters with length over 250 characters.

## Motivation
- What is the use case for this feature?
We use `mlflow.log_params` to log parameters in the training pipeline.
The parameters could be hyperparameters or which text columns to used for the model. Some of the parameters have long names which may come from another platform like ETL which causes the following error:
```
mlflow.exceptions.MlflowException: Param value '[...' had length 376, which exceeded length limit of 250
```

- Why is this use case valuable to support for MLflow users in general?
    1. It would be easier for pytorch lightning users to log parameters with length over 250 characters. Please find the below issue and the PR accordingly.
    https://github.com/PyTorchLightning/pytorch-lightning/issues/5892
    https://github.com/PyTorchLightning/pytorch-lightning/pull/5893
    2. We also found the same feature requests in the past:
    https://github.com/mlflow/mlflow/issues/1976
    https://github.com/mlflow/mlflow/issues/3931

- Why is this use case valuable to support for your project(s) or organization?
If it is possible for `mlflow.log_params` to expand the length limit, it would be easier for us to manage logs across platforms.

- Why is it currently difficult to achieve this use case? (please be as specific as possible about why related MLflow features and components are insufficient)
To achieve this use case, we need to build another logger to maintain the logs.

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

## Details

(Use this section to include any additional information about the feature. If you have a proposal for how to implement this feature, please include it here. For implementation guidelines, please refer to the [Contributing Guide](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst#contribution-guidelines).)
https://github.com/mlflow/mlflow/blob/7b4ab0e4cac5d4c2d2cbfcd3d12aa55b2ee83efe/mlflow/utils/validation.py#L29

**Comment by sl0wc0der** [comment]
This change also needs change in the DB schema.. I've tried increasing the validation limits and it errors when actually adding data to the DB

**Comment by sl0wc0der** [comment]
Duplicate of https://github.com/mlflow/mlflow/issues/6183

**Comment by dbczumar** [comment]
https://github.com/mlflow/mlflow/issues/6183 has been addressed. The limit is now >= 500 bytes across all storage backends. Thank you for using MLflow!
