### ISSUE TITLE
[BUG] mlflow.pyfunc.load_model(model_uri=f"models:/{name}/{stage}") returns an HTTP 405 Method Not Allowed

### ISSUE THREAD

**Issue by jmckib** [mlflow/mlflow#5151]
### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [x] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux 67b050c0d2b8 5.10.47-linuxkit
- **MLflow installed from (source or binary)**: pip install
- **MLflow version (run ``mlflow --version``)**: 1.22.0
- **Python version**: 3.7.6
- **npm version, if running the dev UI**: 
- **Exact command to reproduce**: model = mlflow.pyfunc.load_model(model_uri=f"models:/KNN/staging")

### Describe the problem

When running `mlflow.pyfunc.load_model`, an HTTP 405 error is returned.

```
In [14]: model = mlflow.pyfunc.load_model(model_uri=f"models:/KNN/staging")
---------------------------------------------------------------------------
MlflowException                           Traceback (most recent call last)
<ipython-input-14-bd881dd521c6> in <module>
----> 1 model = mlflow.pyfunc.load_model(model_uri=f"models:/KNN/staging")

/opt/conda/lib/python3.7/site-packages/mlflow/pyfunc/__init__.py in load_model(model_uri, suppress_warnings, dst_path)
    652                      path will be created.
    653     """
--> 654     local_path = _download_artifact_from_uri(artifact_uri=model_uri, output_path=dst_path)
    655     model_meta = Model.load(os.path.join(local_path, MLMODEL_FILE_NAME))
    656

/opt/conda/lib/python3.7/site-packages/mlflow/tracking/artifact_utils.py in _download_artifact_from_uri(artifact_uri, output_path)
     93         root_uri = prefix + urllib.parse.urlunparse(parsed_uri)
     94
---> 95     return get_artifact_repository(artifact_uri=root_uri).download_artifacts(
     96         artifact_path=artifact_path, dst_path=output_path
     97     )

/opt/conda/lib/python3.7/site-packages/mlflow/store/artifact/artifact_repository_registry.py in get_artifact_repository(artifact_uri)
    105              requirements.
    106     """
--> 107     return _artifact_repository_registry.get_artifact_repository(artifact_uri)

/opt/conda/lib/python3.7/site-packages/mlflow/store/artifact/artifact_repository_registry.py in get_artifact_repository(self, artifact_uri)
     71                 )
     72             )
---> 73         return repository(artifact_uri)
     74
     75

/opt/conda/lib/python3.7/site-packages/mlflow/store/artifact/models_artifact_repo.py in __init__(self, artifact_uri)
     32             self.repo = DatabricksModelsArtifactRepository(artifact_uri)
     33         else:
---> 34             uri = ModelsArtifactRepository.get_underlying_uri(artifact_uri)
     33         else:
---> 34             uri = ModelsArtifactRepository.get_underlying_uri(artifact_uri)
     35             self.repo = get_artifact_repository(uri)
     36             # TODO: it may be nice to fall back to the source URI explicitly here if for some reason

/opt/conda/lib/python3.7/site-packages/mlflow/store/artifact/models_artifact_repo.py in get_underlying_uri(uri)
     51         )
     52         client = MlflowClient(registry_uri=databricks_profile_uri)
---> 53         (name, version) = get_model_name_and_version(client, uri)
     54         download_uri = client.get_model_version_download_uri(name, version)
     55         return add_databricks_profile_info_to_artifact_uri(download_uri, databricks_profile_uri)

/opt/conda/lib/python3.7/site-packages/mlflow/store/artifact/utils/models.py in get_model_name_and_version(client, models_uri)
     54     (model_name, model_version, model_stage) = _parse_model_uri(models_uri)
     55     if model_stage is not None:
---> 56         model_version = _get_model_version_from_stage(client, model_name, model_stage)
     57     return model_name, str(model_version)

/opt/conda/lib/python3.7/site-packages/mlflow/store/artifact/utils/models.py in _get_model_version_from_stage(client, name, stage)
     19
     20 def _get_model_version_from_stage(client, name, stage):
---> 21     latest = client.get_latest_versions(name, [stage])
     22     if len(latest) == 0:
     23         raise MlflowException(

/opt/conda/lib/python3.7/site-packages/mlflow/tracking/client.py in get_latest_versions(self, name, stages)
   2046             current_stage: None
   2047         """
-> 2048         return self._get_registry_client().get_latest_versions(name, stages)
   2049
   2050     def set_registered_model_tag(self, name, key, value) -> None:

/opt/conda/lib/python3.7/site-packages/mlflow/tracking/_model_registry/client.py in get_latest_versions(self, name, stages)
    147         :return: List of :py:class:`mlflow.entities.model_registry.ModelVersion` objects.
    148         """
--> 149         return self.store.get_latest_versions(name, stages)
    150
    151     def set_registered_model_tag(self, name, key, value):

/opt/conda/lib/python3.7/site-packages/mlflow/store/model_registry/rest_store.py in get_latest_versions(self, name, stages)
    195         """
    196         req_body = message_to_json(GetLatestVersions(name=name, stages=stages))
--> 197         response_proto = self._call_endpoint(GetLatestVersions, req_body, call_all_endpoints=True)
    198         return [
    199             ModelVersion.from_proto(model_version)

/opt/conda/lib/python3.7/site-packages/mlflow/store/model_registry/rest_store.py in _call_endpoint(self, api, json_body, call_all_endpoints)
     59         if call_all_endpoints:
     60             endpoints = _METHOD_TO_ALL_INFO[api]
---> 61             return call_endpoints(self.get_host_creds(), endpoints, json_body, response_proto)
     62         else:
     63             endpoint, method = _METHOD_TO_INFO[api]

/opt/conda/lib/python3.7/site-packages/mlflow/utils/rest_utils.py in call_endpoints(host_creds, endpoints, json_body, response_proto)
    238     for i, (endpoint, method) in enumerate(endpoints):
    239         try:
--> 240             return call_endpoint(host_creds, endpoint, method, json_body, response_proto)
    241         except RestException as e:
    242             if e.error_code != ErrorCode.Name(ENDPOINT_NOT_FOUND) or i == len(endpoints) - 1:

/opt/conda/lib/python3.7/site-packages/mlflow/utils/rest_utils.py in call_endpoint(host_creds, endpoint, method, json_body, response_proto)
    227             host_creds=host_creds, endpoint=endpoint, method=method, json=json_body
    228         )
--> 229     response = verify_rest_response(response, endpoint)
    230     js_dict = json.loads(response.text)
    231     parse_dict(js_dict=js_dict, message=response_proto)

/opt/conda/lib/python3.7/site-packages/mlflow/utils/rest_utils.py in verify_rest_response(response, endpoint)
    173                 response.status_code,
    174             )
--> 175             raise MlflowException("%s. Response body: '%s'" % (base_msg, response.text))
    176
    177     # Skip validation for endpoints (e.g. DBFS file-download API) which may return a non-JSON

MlflowException: API request to endpoint /api/2.0/mlflow/registered-models/get-latest-versions failed with error code 405 != 200. Response body: '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>405 Method Not Allowed</title>
<h1>Method Not Allowed</h1>
<p>The method is not allowed for the requested URL.</p>
```

It looks like the problem is that the `get-latest-versions` endpoint is receiving a POST request when it expects a GET. [The documentation says that it should be a POST](https://mlflow.org/docs/latest/rest-api.html#get-latest-modelversions), but I've confirmed that only a GET works.

```
In [13]: resp = requests.get(mlflow.get_tracking_uri() + "/api/2.0/mlflow/registered-models/get-latest-versions", params={"name": "KNN", "stages": ["No
    ...: ne"]}, headers={"Authorization": f"Bearer {os.environ['MLFLOW_TRACKING_TOKEN']}"})

In [14]: resp.status_code
Out[14]: 200

In [15]: resp=requests.post(mlflow.get_tracking_uri() + "/api/2.0/mlflow/registered-models/get-latest-versions", data={"name": "KNN", "stages": ["Stagi
    ...: ng"]}, headers={"Authorization": "Bearer 537f88d4b4bbff6827c6dd6241dfb3f6"})

In [16]: resp.status_code
Out[16]: 405
```

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [x] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages
- [x] `language/python`

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by alexsee** [comment]
Have you checked if your client library version is also updated to 1.22.0? There was a change in the API #4999.

**Comment by jmckib** [comment]
Oops, somehow I overlooked that the server version was still 1.17.0. My mistake, false alarm.
