### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'custom_transformer'

### ISSUE THREAD

**Issue by eXTure** [mlflow/mlflow#5178]
### Willingness to contribute
- [ ] Yes. I can contribute a fix for this bug independently.
- [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [x] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: -
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10 Home 21H2
- **MLflow installed from (source or binary)**: Source
- **MLflow version (run ``mlflow --version``)**: 1.22.0
- **Python version**: 3.9
- **npm version, if running the dev UI**: -

### Describe the problem
I use mlflow autologging for my sklearn pipeline and after exporting model to a different project, whenever I try to load the model, I get an error that modules are missing.

### Code to reproduce issue
I created an easily reproducible example.

Step 1: Create a module to import in train.py

    # custom_transformer.py

    from sklearn.base import BaseEstimator, TransformerMixin

    class ColumnSelector(BaseEstimator, TransformerMixin):

        def fit(self, X, y=None):
            return self

        def transform(self, X):
            return X

Step 2: Create and log sklearn model

    # train.py

    import mlflow.sklearn
    from sklearn.datasets import load_breast_cancer
    from sklearn.naive_bayes import GaussianNB
    from sklearn.pipeline import Pipeline, make_pipeline
    from custom_transformer import ColumnSelector

    mlflow.autolog()
    
    pipe = Pipeline([("selector", ColumnSelector())])

    data = load_breast_cancer()
    labels = data["target"]
    features = data["data"]

    model = make_pipeline(pipe, GaussianNB())
    model.fit(features, labels)

Step 3: Copy model folder to a different project and try to load

    # load.py

    import mlflow.sklearn

    mlflow.sklearn.load_model("model")

### Other info / logs
    Traceback (most recent call last):
      File "C:\Users\issue_test\load.py", line 6, in load
        mlflow.sklearn.load_model("model")
      File "C:\Users\issue_example\venv\lib\site-packages\mlflow\sklearn\__init__.py", line 549, in load_model
        return _load_model_from_local_file(
      File "C:\Users\issue_example\venv\lib\site-packages\mlflow\sklearn\__init__.py", line 417, in _load_model_from_local_file
        return cloudpickle.load(f)
    ModuleNotFoundError: No module named 'custom_transformer'

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [x] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [x] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [x] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [x] `area/windows`: Windows support

**Comment by aidiss** [comment]
Facing same issue.

Why could the import be missing? 

Maybe ml-flow supports only code that is not imported. In that case, if no user created Python modules would need to be imported loading would work just fine?

**Comment by AveshCSingh** [comment]
The problem here is that mlflow is unaware of the custom Python module `ColumnSelector`. Other mlflow flavors have handled this problem by adding a `code_path` parameter to `log_model` (see [mlflow.pyfunc.log_model](https://github.com/mlflow/mlflow/blob/852f567797dfcde34c8daffcceec95c64d2c641f/mlflow/pyfunc/__init__.py#L1107), [mlflow.pytorch.log_model](https://github.com/mlflow/mlflow/blob/master/mlflow/pytorch/__init__.py#L116)).

We should be able to do something similar here. **We would welcome community contributions to add a `code_path` parameter to `mlflow.sklearn.log_model`.**

Another challenge is to figure how autologging can determine the Python file dependencies. I am sure how we can solve this problem, but think ^ will get us pretty far. Users training models with file dependencies can call `log_model` directly rather than relying on autologging.

**Comment by ankit-db** [comment]
Closing because this was added in https://github.com/mlflow/mlflow/pull/5448
