### ISSUE TITLE
[BUG] MLFlow startup fails when DB URL is `postgres:<<foobar>>` instead of `postgresql:<<foobar>>`

### ISSUE THREAD

**Issue by mrkaye97** [mlflow/mlflow#5197]
### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [x] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### Describe the problem
MLFlow startup fails with the following error when using a DB URL that looks like: `postgres://...`

```
mlflow.tracking.registry.UnsupportedModelRegistryStoreURIException:  Model registry functionality is unavailable; got unsupported URI 'postgres://<<host and password and stuff>>' for model registry data storage. Supported URI schemes are: ['', 'file', 'postgresql', 'mysql', 'sqlite', 'mssql']. See https://www.mlflow.org/docs/latest/tracking.html#storage for how to run an MLflow server against one of the supported backend storage locations.
```

I'm not sure if this is a known issue or not. Admittedly, I'm also not sure if this is _actually_ an MLFlow issue, or if it's a SQLAlchemy issue. It seems like it should be easy enough to allow Postgres DBs to be specified with either `postgres` or `postgresql`? Is there a reason this isn't the case by default? It's annoying because some platforms (e.g. Heroku + Heroku Postgres) automatically add a `DATABASE_URL` environment variable to the app running MLFlow when the database is configured. But this `DATABASE_URL` uses `postgres` and not `postgresql`, which means that I essentially need to copy the URL but change `postgres` --> `postgresql` in order to get MLFlow to start. This seems like unnecessary overhead to me.

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [x] `area/server-infra`: MLflow Tracking server backend
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Thanks for any help on this!

**Comment by harupy** [comment]
@mrkaye97 Looks like this is a SQLAlchemy issue: https://stackoverflow.com/a/64698899/6943581

**Comment by mrkaye97** [comment]
Agh, brutal. Alright. Thanks for the pointer @harupy!
