### ISSUE TITLE
[BUG] Changing the Tracking's URI doesn't change the Artifact's URI

### ISSUE THREAD

**Issue by peguerosdc** [mlflow/mlflow#5204]
### Willingness to contribute
- [ ] Yes. I can contribute a fix for this bug independently.
- [x] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: docker `continuumio/miniconda3` on Azure's Compute Instance
- **MLflow installed from (source or binary)**: R's `install_mlflow()`
- **MLflow version (run ``mlflow --version``)**: 1.22.0
- **Python version**: 3.9

### Describe the problem
I am trying to use MLFlow on Azure's ML Compute Instances to track my experiments in R. The tracking URI set by the compute instance has the scheme `azureml://...` which is not supported by MLFlow. Azure has a [package](https://docs.microsoft.com/en-us/python/api/azureml-mlflow/?view=azure-ml-py) to enable support on Python, but as my code is in R, I found that I need to manually change the URI to `https://...` to make logging work.

Changing the Tracking URI works correctly (i.e. I can log params and metrics) when setting the `MLFLOW_ARTIFACT_URI` environment variable or when calling `mlflow_set_tracking_uri()`, but it doesn't seem to have any effect on the artifact URI (related to #3469) as it is still using the old scheme (the one starting with `azureml://`), so I am not able to log artifacts.

I see no method on [MLFlow's R API](https://www.mlflow.org/docs/latest/R-api.html#mlflow-server) to change the artifact's URI scheme (and #2577 seems to be related, but I created a different issue as I don't want to re-define the whole URI, but just the scheme) and workarounds are possible at least while Microsoft implements an R API (I hope it happens someday), but I was wondering if MLFlow has any suggestion on this or if a new feature that could help this use-case is in the plan.

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [x] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Language 
- [x] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [x] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by mrkaye97** [comment]
I'm not an author, but I've been working on a new API wrapper I'm calling [lightMLFlow](https://github.com/collegevine/lightMLFlow) that might help with your problem. One of the main ideas behind the package was that the R package that's making calls to the MLFlow API really has no reason to require `boto3` to save things to S3, so I replaced `boto3` with `aws.s3`. It'd be easy to extend that to also allow artifact URIs in Azure, which I assume could rely on a package like [AzureStore](https://cran.r-project.org/web/packages/AzureStor/vignettes/intro.html) for example. Let me know if you'd be interested in this functionality or maybe in contributing! `lightMLFlow` isn't stable enough for production yet, but it's not too far off.

**Comment by peguerosdc** [comment]
Hi! Thanks for sharing! After discussing the topic on a Microsoft forum, I was pointed to [an updated R example](https://github.com/Azure/azureml-examples/tree/aebe5100ffabbfbd4ec4bd06014be511acf48b24/cli/jobs/single-step/r) that implements a new MLFlow client (see `/accidents/src/azureml_utils.R`) which sort of solves my issue.

I don't consider it ready for production as sometimes the code halts unexpectedly without much explanation (and the example didn't run "as is"; that's why I said "sort of"), but I think working on top of it would be a more direct approach for this use case. I am not planning to do it as I am ok with my workarounds at the moment, but I leave it here in case someone finds it useful or if you find you can borrow some of it for your package.

(Still this issue should remain open as it is not fixed nor an explanation is given)

**Comment by mrkaye97** [comment]
Great, thanks for the pointer! That sounds like a solid solution 👍

**Comment by singankit** [comment]
@peguerosdc MLflow R uses mlflow cli for artifacts related tracking API which can be found [here](https://github.com/mlflow/mlflow/blob/3ab6fbf3757fc58b2600a10cd67f2104fdd1be23/mlflow/R/mlflow/R/tracking-runs.R#L481). Which then are handled by python package. For custom tracking store like Azure Machine Learning (AML) it requires `azureml-mlflow` package to be installed. This package will handle the artifacts related calls. Hence artifact uri should be of format `azureml://<>` if you are using AML default artifact store since azureml-mlflow plugin understand that tracking/artifact uri.
