### ISSUE TITLE
[FR] Support spark `transformers` tracking with mlflow

### ISSUE THREAD

**Issue by serena-ruan** [mlflow/mlflow#5216]
Thank you for submitting a feature request. **Before proceeding, please review MLflow's [Issue Policy for feature requests](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md#feature-requests) and the [MLflow Contributing Guide](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst)**.

**Please fill in this feature request template to ensure a timely and thorough response.**

## Willingness to contribute
The MLflow Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature (either as an MLflow Plugin or an enhancement to the MLflow code base)?

- [x] Yes. I can contribute this feature independently.
- [ ] Yes. I would be willing to contribute this feature with guidance from the MLflow community.
- [ ] No. I cannot contribute this feature at this time.

## Proposal Summary
Currently, MLFlow's spark flavor only support saving/logging classes that are `Models`, and it means even those popular `Transformers` like `Bucketizer` can't call save/log/predict. Could you support `Transformers` since both of them belong to `Pipeline` and it makes more sense if we can just call the same behavior for models and transformers.

## Motivation
- What is the use case for this feature?
Save, log and inference with spark transformers.
- Why is this use case valuable to support for MLflow users in general?
MLFlow spark already support `models`, and transformers are just like models that can be put into pipelines.
- Why is this use case valuable to support for your project(s) or organization?
It makes models and transformers behaviors consistent, and users can keep track of them using mlflow following the same pattern.
- Why is it currently difficult to achieve this use case? (please be as specific as possible about why related MLflow features and components are insufficient)
Mlflow spark currently has a strict check that only classes of type `pyspark.ml.model` can be passed to the following save_model function, so for transformers we must wrap it as pipeline model in order to save it, which makes the process more complicated. So if you could add transformers into the `_validate_model` function then it can directly be saved by mlflow.spark.save_model.

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [x] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

## Details

We want to support all pyspark ml Transformers with the ability to save, log and load with mlflow.spark. For example, VectorAssembler class is a typical type of Transformer that merges multiple columns into a vector column. And Transformers can be a stage of PipelineModel. So the suggested change is as follows:

For file mlflow/spark.py we change the _validate_model to support Transformer:

```
def _validate_model(spark_model):
    from pyspark.ml.util import MLReadable, MLWritable
    from pyspark.ml import Model as PySparkModel
    from pyspark.ml import Transformer as PySparkTransformer

    if (
        (
            not isinstance(spark_model, PySparkModel)
            and not isinstance(spark_model, PySparkTransformer)
        )
        or not isinstance(spark_model, MLReadable)
        or not isinstance(spark_model, MLWritable)
    ):
        raise MlflowException(
            "Cannot serialize this model. MLflow can only save descendants of pyspark.Model"
            "that implement MLWritable and MLReadable.",
            INVALID_PARAMETER_VALUE,
        )
```

As we can see in save_model function:
`if not isinstance(spark_model, PipelineModel):
        spark_model = PipelineModel([spark_model])`
And Transformers can also be put here so save_model will just work. log_model is the same.
For load_model it will finally load the PipelineModel back so the Transformers make no difference. We could still load PipelineModel back and call `transform` API on it.

The only difference would be that Transformers may not support `predict` function as that requires a column named `prediction`. Transformers are not designed as predictors so it's reasonable, and people can always specify the output column name as `prediction` if they insist on using this feature.

**Comment by mhamilton723** [comment]
Hey @harupy does the community have any thoughts on this proposal?

**Comment by serena-ruan** [comment]
Hi @harupy, we're actively chasing on this feature and hope to get some updates from your end ASAP so that I could contribute. Looking forward to hearing any comments!

**Comment by harupy** [comment]
@serena-ruan The proposal makes sense. Looking forward to a PR!
