### ISSUE TITLE
[BUG] Previous runs not shown after restart

### ISSUE THREAD

**Issue by JbIPS** [mlflow/mlflow#5246]
### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [X] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Fedora 35
- **MLflow installed from (source or binary)**: pip binary
- **MLflow version (run ``mlflow --version``)**: 1.22.0
- **Python version**: 3.9.9
- **Exact command to reproduce**: `mlfow run .`

### Describe the problem
On local backend, after a server restart, previous runs are not shown in the UI. `mlruns` folder is there, full of previous runs folder, but the UI shows a empty list of runs.

### Code to reproduce issue
* Start the UI
* Run
* Restart UI

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [X] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [X] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [X] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

**Comment by JbIPS** [comment]
Looks like I didn't see the filter "Last 24h".

Sorry for the false report and thank you for MLFlow!
