### ISSUE TITLE
[FR] Support Amazon Redshift as a backend-store-uri

### ISSUE THREAD

**Issue by nicholasarquette** [mlflow/mlflow#5252]
Thank you for submitting a feature request. **Before proceeding, please review MLflow's [Issue Policy for feature requests](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md#feature-requests) and the [MLflow Contributing Guide](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst)**.

**Please fill in this feature request template to ensure a timely and thorough response.**

## Willingness to contribute
The MLflow Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature (either as an MLflow Plugin or an enhancement to the MLflow code base)?

- [x ] Yes. I would be willing to contribute this feature with guidance from the MLflow community.

## Proposal Summary

I would like to log experiments and models in an Amazon Redshift database so that I can log to a single backend-store-uri from multiple machines.

(In a few sentences, provide a clear, high-level description of the feature request)

## Motivation
- What is the use case for this feature? Supporting tracking and model registry in another database.
- Why is this use case valuable to support for MLflow users in general? Support additional database backend stores.
- Why is this use case valuable to support for your project(s) or organization? Organizations using redshift will be able to use their redshift database to log runs and models.
- Why is it currently difficult to achieve this use case? (please be as specific as possible about why related MLflow features and components are insufficient) Right now it isn't an option, therefore you have to utilized other relational database systems to be able to log experiments and models.

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [x] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [x] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [x] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [x] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [x] `language/python`: 

# Details

(Use this section to include any additional information about the feature. If you have a proposal for how to implement this feature, please include it here. For implementation guidelines, please refer to the [Contributing Guide](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst#contribution-guidelines).)

**Comment by AveshCSingh** [comment]
Hi @nicholasarquette. Thanks for filing this feature request.

You can log to mlflow from multiple machines by standing up an MLflow server, or by connecting to the same database. Redshift is not necessary for this.

I am also skeptical of introducing Redshift as a supported backend, since Redshift is an OLAP and not an OLTP database. I will thus close this ticket for now, but please feel free to re-open if there are additional reasons to support Redshift.
