### ISSUE TITLE
[BUG] --serve-artifacts URIs on separate server

### ISSUE THREAD

**Issue by quantumtrope** [mlflow/mlflow#5297]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md) for additional information about bug reports. For help with debugging your code, please refer to [Stack Overflow](https://stackoverflow.com/questions/tagged/mlflow).

**Please fill in this bug report template to ensure a timely and thorough response.**

### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [x] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  Server running on Ubuntu 20.04, attempt to save model from Windows 10
- **MLflow installed from (source or binary)**: `pip install mlflow`
- **MLflow version (run ``mlflow --version``)**: 1.23
- **Python version**: 3.8.10
- **npm version, if running the dev UI**: N/A
- **Exact command to reproduce**: 
  - On server side: `mlflow server  --serve-artifacts --host 0.0.0.0 -p 5020    --artifacts-destination ./mlartifacts --gunicorn-opts "--log-level debug"
  - On client side, mlflow installed via `git clone` and `pip install -e ./`. Use the `mlflow_artifacts` example, so command is `python example.py`

### Describe the problem
I expect to be able to save artifacts from the `mlflow_artifacts` example to the server running on a separate machine. Instead I get errors relating to the URI. 

Only running the example code from the same machine works. 

### Code to reproduce issue
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

On an ubuntu machine, run the server command:
```bash
mlflow server  --serve-artifacts --host 0.0.0.0 -p 5020    --artifacts-destination ./mlartifacts     --gunicorn-opts "--log-level debug"
```
(Note that adding the option `--default-artifact-root http://<server-ip>:5020/api/2.0/mlflow-artifacts/artifacts/experiments` doesn't change a thing)

On a windows machine:
```powershell
$env:MLFLOW_TRACKING_URI="http://<ip-of-server>:5020/"
cd examples/mlflow_artifacts/
python example.py
```

The result is the following error:

```python
ConnectionError: HTTPConnectionPool(host='0.0.0.0', port=5020): Max retries exceeded with url: /api/2.0/mlflow-artifacts/artifacts/experiments/0/ef5c9d97f4504cc494413c4d5cf048f7/artifacts/a.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002464D5AC700>: Failed to establish a new connection: [WinError 10049] The requested address is not valid in its context'))
```

I think the hint is in the HTTPConnectionPool, which seems to be looking for a localhost (0.0.0.0) rather than the server name. Since this is being passed to the client on a different machine, which isn't running a server, the client can't save the artifact. 

### Other info / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

```bash
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
File ~\Miniconda3\envs\mlflow\lib\site-packages\urllib3\connection.py:174, in HTTPConnection._new_conn(self)
    173 try:
--> 174     conn = connection.create_connection(
    175         (self._dns_host, self.port), self.timeout, **extra_kw
    176     )
    178 except SocketTimeout:

File ~\Miniconda3\envs\mlflow\lib\site-packages\urllib3\util\connection.py:96, in create_connection(address, timeout, source_address, socket_options)
     95 if err is not None:
---> 96     raise err
     98 raise socket.error("getaddrinfo returns an empty list")

File ~\Miniconda3\envs\mlflow\lib\site-packages\urllib3\util\connection.py:86, in create_connection(address, timeout, source_address, socket_options)
     85     sock.bind(source_address)
---> 86 sock.connect(sa)
     87 return sock

OSError: [WinError 10049] The requested address is not valid in its context

During handling of the above exception, another exception occurred:

NewConnectionError                        Traceback (most recent call last)
File ~\Miniconda3\envs\mlflow\lib\site-packages\urllib3\connectionpool.py:699, in HTTPConnectionPool.urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    698 # Make the request on the httplib connection object.
--> 699 httplib_response = self._make_request(
    700     conn,
    701     method,
    702     url,
    703     timeout=timeout_obj,
    704     body=body,
    705     headers=headers,
    706     chunked=chunked,
    707 )
    709 # If we're going to release the connection in ``finally:``, then
    710 # the response doesn't need to know about the connection. Otherwise
    711 # it will also try to release it and we'll have a double-release
    712 # mess.

File ~\Miniconda3\envs\mlflow\lib\site-packages\urllib3\connectionpool.py:394, in HTTPConnectionPool._make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
    393     else:
--> 394         conn.request(method, url, **httplib_request_kw)
    396 # We are swallowing BrokenPipeError (errno.EPIPE) since the server is
    397 # legitimately able to close the connection after sending a valid response.
    398 # With this behaviour, the received response is still readable.

File ~\Miniconda3\envs\mlflow\lib\site-packages\urllib3\connection.py:239, in HTTPConnection.request(self, method, url, body, headers)
    238     headers["User-Agent"] = _get_default_user_agent()
--> 239 super(HTTPConnection, self).request(method, url, body=body, headers=headers)

File ~\Miniconda3\envs\mlflow\lib\http\client.py:1279, in HTTPConnection.request(self, method, url, body, headers, encode_chunked)
   1278 """Send a complete request to the server."""
-> 1279 self._send_request(method, url, body, headers, encode_chunked)

File ~\Miniconda3\envs\mlflow\lib\http\client.py:1325, in HTTPConnection._send_request(self, method, url, body, headers, encode_chunked)
   1324     body = _encode(body, 'body')
-> 1325 self.endheaders(body, encode_chunked=encode_chunked)

File ~\Miniconda3\envs\mlflow\lib\http\client.py:1274, in HTTPConnection.endheaders(self, message_body, encode_chunked)
   1273     raise CannotSendHeader()
-> 1274 self._send_output(message_body, encode_chunked=encode_chunked)

File ~\Miniconda3\envs\mlflow\lib\http\client.py:1034, in HTTPConnection._send_output(self, message_body, encode_chunked)
   1033 del self._buffer[:]
-> 1034 self.send(msg)
   1036 if message_body is not None:
   1037
   1038     # create a consistent interface to message_body

File ~\Miniconda3\envs\mlflow\lib\http\client.py:974, in HTTPConnection.send(self, data)
    973 if self.auto_open:
--> 974     self.connect()
    975 else:

File ~\Miniconda3\envs\mlflow\lib\site-packages\urllib3\connection.py:205, in HTTPConnection.connect(self)
    204 def connect(self):
--> 205     conn = self._new_conn()
    206     self._prepare_conn(conn)

File ~\Miniconda3\envs\mlflow\lib\site-packages\urllib3\connection.py:186, in HTTPConnection._new_conn(self)
    185 except SocketError as e:
--> 186     raise NewConnectionError(
    187         self, "Failed to establish a new connection: %s" % e
    188     )
    190 return conn

NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000002464D5AC700>: Failed to establish a new connection: [WinError 10049] The requested address is not valid in its context

During handling of the above exception, another exception occurred:

MaxRetryError                             Traceback (most recent call last)
File ~\Miniconda3\envs\mlflow\lib\site-packages\requests\adapters.py:439, in HTTPAdapter.send(self, request, stream, timeout, verify, cert, proxies)
    438 if not chunked:
--> 439     resp = conn.urlopen(
    440         method=request.method,
    441         url=url,
    442         body=request.body,
    443         headers=request.headers,
    444         redirect=False,
    445         assert_same_host=False,
    446         preload_content=False,
    447         decode_content=False,
    448         retries=self.max_retries,
    449         timeout=timeout
    450     )
    452 # Send the request.
    453 else:

File ~\Miniconda3\envs\mlflow\lib\site-packages\urllib3\connectionpool.py:755, in HTTPConnectionPool.urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    753     e = ProtocolError("Connection aborted.", e)
--> 755 retries = retries.increment(
    756     method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
    757 )
    758 retries.sleep()

File ~\Miniconda3\envs\mlflow\lib\site-packages\urllib3\util\retry.py:574, in Retry.increment(self, method, url, response, error, _pool, _stacktrace)
    573 if new_retry.is_exhausted():
--> 574     raise MaxRetryError(_pool, url, error or ResponseError(cause))
    576 log.debug("Incremented Retry for (url='%s'): %r", url, new_retry)

MaxRetryError: HTTPConnectionPool(host='0.0.0.0', port=5020): Max retries exceeded with url: /api/2.0/mlflow-artifacts/artifacts/experiments/0/ef5c9d97f4504cc494413c4d5cf048f7/artifacts/a.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002464D5AC700>: Failed to establish a new connection: [WinError 10049] The requested address is not valid in its context'))
```

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [x] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [x] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by bgt-cdedels** [comment]
I also have a similar issue on a linux machine.  In my case, the error is different, but I suspect that is because I am using a different configuration.

Steps to reproduce:

Artifacts server:
```
mlflow server --host 0.0.0.0 --port 80 --backend-store-uri postgresql+psycopg2://user:pass@host/database
      --artifacts-destination s3://model-artifacts-airflow-enhancements-20220226162046781400000001/ --serve-artifacts
```

Mlflow Client (I am using MlflowClient because of a separate issue with run not being ended when I call `mlflow.end_run()`):
```
MLFLOW_TRACKING_URI=http://hostname python example.py
```

The error at the client I get is below.  I expect this error because my client machine doesn't have permission to write to the S3 bucket, only the airflow artifacts server does.
```
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/boto3/s3/transfer.py", line 287, in upload_file
    future.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/s3transfer/futures.py", line 103, in result
    return self._coordinator.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/s3transfer/futures.py", line 266, in result
    raise self._exception
  File "/home/airflow/.local/lib/python3.7/site-packages/s3transfer/tasks.py", line 139, in __call__
    return self._execute_main(kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/s3transfer/tasks.py", line 162, in _execute_main
    return_value = self._main(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/s3transfer/upload.py", line 757, in _main
    client.put_object(Bucket=bucket, Key=key, Body=body, **extra_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 391, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 719, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "example.py", line 42, in <module>
    main()
  File "example.py", line 28, in main
    mlflow.log_artifact(tmp_path_a)
  File "/home/airflow/.local/lib/python3.7/site-packages/mlflow/tracking/fluent.py", line 621, in log_artifact
    MlflowClient().log_artifact(run_id, local_path, artifact_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/mlflow/tracking/client.py", line 955, in log_artifact
    self._tracking_client.log_artifact(run_id, local_path, artifact_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/mlflow/tracking/_tracking_service/client.py", line 355, in log_artifact
    artifact_repo.log_artifact(local_path, artifact_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/mlflow/store/artifact/s3_artifact_repo.py", line 125, in log_artifact
    s3_client=self._get_s3_client(), local_file=local_file, bucket=bucket, key=dest_path
  File "/home/airflow/.local/lib/python3.7/site-packages/mlflow/store/artifact/s3_artifact_repo.py", line 117, in _upload_file
    s3_client.upload_file(Filename=local_file, Bucket=bucket, Key=key, ExtraArgs=extra_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/boto3/s3/inject.py", line 133, in upload_file
    extra_args=ExtraArgs, callback=Callback)
  File "/home/airflow/.local/lib/python3.7/site-packages/boto3/s3/transfer.py", line 295, in upload_file
    filename, '/'.join([bucket, key]), e))
boto3.exceptions.S3UploadFailedError: Failed to upload /tmp/tmph80t01fq/a.txt to model-artifacts-airflow-enhancements-20220226162046781400000001/0/5336f31e7c854e1fa958f20af1c79d32/artifacts/a.txt: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied
```

**Comment by yudhiesh** [comment]
> I also have a similar issue on a linux machine. In my case, the error is different, but I suspect that is because I am using a different configuration.
> 
> Steps to reproduce:
> 
> Artifacts server:
> 
> ```
> mlflow server --host 0.0.0.0 --port 80 --backend-store-uri postgresql+psycopg2://user:pass@host/database
>       --artifacts-destination s3://model-artifacts-airflow-enhancements-20220226162046781400000001/ --serve-artifacts
> ```
> 
> Mlflow Client:
> 
> ```
> MLFLOW_TRACKING_URI=http://hostname python example.py
> ```
> 
> The error at the client I get is below. I expect this error because my client machine doesn't have permission to write to the S3 bucket, only the airflow artifacts server does.
> 
> ```
> Traceback (most recent call last):
>   File "/home/airflow/.local/lib/python3.7/site-packages/boto3/s3/transfer.py", line 287, in upload_file
>     future.result()
>   File "/home/airflow/.local/lib/python3.7/site-packages/s3transfer/futures.py", line 103, in result
>     return self._coordinator.result()
>   File "/home/airflow/.local/lib/python3.7/site-packages/s3transfer/futures.py", line 266, in result
>     raise self._exception
>   File "/home/airflow/.local/lib/python3.7/site-packages/s3transfer/tasks.py", line 139, in __call__
>     return self._execute_main(kwargs)
>   File "/home/airflow/.local/lib/python3.7/site-packages/s3transfer/tasks.py", line 162, in _execute_main
>     return_value = self._main(**kwargs)
>   File "/home/airflow/.local/lib/python3.7/site-packages/s3transfer/upload.py", line 757, in _main
>     client.put_object(Bucket=bucket, Key=key, Body=body, **extra_args)
>   File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 391, in _api_call
>     return self._make_api_call(operation_name, kwargs)
>   File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 719, in _make_api_call
>     raise error_class(parsed_response, operation_name)
> botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "example.py", line 42, in <module>
>     main()
>   File "example.py", line 28, in main
>     mlflow.log_artifact(tmp_path_a)
>   File "/home/airflow/.local/lib/python3.7/site-packages/mlflow/tracking/fluent.py", line 621, in log_artifact
>     MlflowClient().log_artifact(run_id, local_path, artifact_path)
>   File "/home/airflow/.local/lib/python3.7/site-packages/mlflow/tracking/client.py", line 955, in log_artifact
>     self._tracking_client.log_artifact(run_id, local_path, artifact_path)
>   File "/home/airflow/.local/lib/python3.7/site-packages/mlflow/tracking/_tracking_service/client.py", line 355, in log_artifact
>     artifact_repo.log_artifact(local_path, artifact_path)
>   File "/home/airflow/.local/lib/python3.7/site-packages/mlflow/store/artifact/s3_artifact_repo.py", line 125, in log_artifact
>     s3_client=self._get_s3_client(), local_file=local_file, bucket=bucket, key=dest_path
>   File "/home/airflow/.local/lib/python3.7/site-packages/mlflow/store/artifact/s3_artifact_repo.py", line 117, in _upload_file
>     s3_client.upload_file(Filename=local_file, Bucket=bucket, Key=key, ExtraArgs=extra_args)
>   File "/home/airflow/.local/lib/python3.7/site-packages/boto3/s3/inject.py", line 133, in upload_file
>     extra_args=ExtraArgs, callback=Callback)
>   File "/home/airflow/.local/lib/python3.7/site-packages/boto3/s3/transfer.py", line 295, in upload_file
>     filename, '/'.join([bucket, key]), e))
> boto3.exceptions.S3UploadFailedError: Failed to upload /tmp/tmph80t01fq/a.txt to model-artifacts-airflow-enhancements-20220226162046781400000001/0/5336f31e7c854e1fa958f20af1c79d32/artifacts/a.txt: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied
> ```

Hey I am facing the same issue, did you manage to fix ti?

**Comment by bgt-cdedels** [comment]
No.  I have moved to [scenario 4](https://mlflow.org/docs/latest/tracking.html#scenario-4-mlflow-with-remote-tracking-server-backend-and-artifact-stores).  [Scenario 5](https://mlflow.org/docs/latest/tracking.html#scenario-5-mlflow-tracking-server-enabled-with-proxied-artifact-storage-access) doesn't seem to work for me as documented.
