### ISSUE TITLE
[BUG] meta["lifecycle_stage"] = LifecycleStage.ACTIVE  TypeError: 'NoneType' object does not support item assignment

### ISSUE THREAD

**Issue by pkuong** [mlflow/mlflow#5336]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md) for additional information about bug reports. For help with debugging your code, please refer to [Stack Overflow](https://stackoverflow.com/questions/tagged/mlflow).

**Please fill in this bug report template to ensure a timely and thorough response.**

### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [x] Yes. I can contribute a fix for this bug independently.
- [x] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **MLflow installed from (source or binary)**:
- **MLflow version (run ``mlflow --version``)**:
- **Python version**:
- **npm version, if running the dev UI**:
- **Exact command to reproduce**:

### Describe the problem
 Getting the following error when trying to load the mlflow server UI

2022/02/01 18:00:43 ERROR mlflow.server: Exception on /ajax-api/2.0/preview/mlflow/experiments/list [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/mlflow/server/handlers.py", line 238, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/mlflow/server/handlers.py", line 298, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/mlflow/server/handlers.py", line 600, in _list_experiments
    experiment_entities = _get_tracking_store().list_experiments(**params)
  File "/usr/local/lib/python3.7/site-packages/mlflow/store/tracking/file_store.py", line 261, in list_experiments
    experiment = self._get_experiment(exp_id, view_type)
  File "/usr/local/lib/python3.7/site-packages/mlflow/store/tracking/file_store.py", line 348, in _get_experiment
    meta["lifecycle_stage"] = LifecycleStage.ACTIVE
TypeError: 'NoneType' object does not support item assignment

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [x] `area/server-infra`: MLflow Tracking server backend
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [x] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models

**Comment by pkuong** [comment]
Turns out that somehow there are runs folder in "mlflow/runtime/mlruns" with only meta.yaml file in it.. There was probably file writing issue on our side. So, nevermind!

**Comment by Nirmalnk05** [comment]
How did you fix this ? Can you explain in detail . Thanks in advance.
