### ISSUE TITLE
[Feature Request] show multiple plots in Tracking UI

### ISSUE THREAD

**Issue by pme0** [mlflow/mlflow#5397]
## Willingness to contribute
- [ ] Yes. I can contribute this feature independently.
- [ ] Yes. I would be willing to contribute this feature with guidance from the MLflow community.
- [x] No. I cannot contribute this feature at this time.

## Proposal Summary

User Interface (`mlflow ui`)  displaying multiple plots instead of just one.

## Motivation

Currently the Tracking UI seems to allow 1 plot only.
Multiple metrics can be plotted there, but in cases where metrics are on very different scales (e.g. different losses, learning rate, accuracy, etc.) the visualization is poor.

Switching being different metrics of interest, back-and-forth, manually, is not very user friendly.

Allowing multiple plots would improve the experiment tracking immensely.

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [x] `area/server-infra`: MLflow Tracking server backend
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [x] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server

**Comment by BenWilson2** [comment]
Thank you for the constructive feedback @pme0 . We're going to be discussing options for potentially implementing some UX changes that could simplify axis scaling issues with mixed range metric and parameter values. We appreciate your feedback!

**Comment by adamreeve** [comment]
Hi @BenWilson2. I'm also interested in this feature and willing to implement this if it fits in with your other plans. The way I'm thinking this could work is that a button for adding additional plots could be added to the existing metric view, and when multiple plots are visible, any one can be removed. I've had a go at implementing a proof of concept to show that this approach can work, but there would still be a fair amount of work to do to get this up to scratch for a PR. My proof of concept changes can be seen at https://github.com/adamreeve/mlflow/compare/master...multi_plot.

ps. there's also issue #1806 which this looks to be a duplicate of, or at least is closely related.
