### ISSUE TITLE
[BUG] --serve-artifacts seems not working

### ISSUE THREAD

**Issue by jlmeunier** [mlflow/mlflow#5407]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md) for additional information about bug reports. For help with debugging your code, please refer to [Stack Overflow](https://stackoverflow.com/questions/tagged/mlflow).

**Please fill in this bug report template to ensure a timely and thorough response.**

### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [ x ] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: CentOS Linux release 7.9.2009 (Core)
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**: 1.23.1
- **Python version**: 3.7.4
- **npm version, if running the dev UI**: N/A
- **Exact command to reproduce**: 
server started from $DIR, which is /home/meunier/MLFLOW, by command
`mlflow server --host 0.0.0.0 --port 3030 --backend-store-uri sqlite:///$DIR/data_NMT/server.db --serve-artifacts --artifacts-destination ./data_NMT --gunicorn-opts "--timeout 240"`
(I have also tried to give absolute path for --artifacts-destination)
client-side test:
`MLFLOW_TRACKING_URI=http://myhost:3030 python mlflow_artifacts/example.py
`
### Describe the problem
I'm getting an error:
`OSError: [Errno 45] Operation not supported: '/home/meunier'`
but this path refers to the server-side file system.
It seems like if the client still trie to copy the artifact to the server area, despite the --serve-artifacts

### Code to reproduce issue
run a server by:
`mlflow server --host 0.0.0.0 --port 3030 --backend-store-uri sqlite:///$DIR/data_NMT/server.db --serve-artifacts --artifacts-destination ./data_NMT --gunicorn-opts "--timeout 240"`
run the  `mlflow_artifacts/example.py`  example **from a machine which cannot access the server disks**.

### Other info / logs
MLFLOW_TRACKING_URI=http://my_server_host:3030 python mlflow_artifacts/example.py
```
Traceback (most recent call last):
  File "mlflow_artifacts/example.py", line 42, in <module>
    main()
  File "mlflow_artifacts/example.py", line 28, in main
    mlflow.log_artifact(tmp_path_a)
  File "/Users/meunier/opt/anaconda3/lib/python3.7/site-packages/mlflow/tracking/fluent.py", line 606, in log_artifact
    MlflowClient().log_artifact(run_id, local_path, artifact_path)
  File "/Users/meunier/opt/anaconda3/lib/python3.7/site-packages/mlflow/tracking/client.py", line 955, in log_artifact
    self._tracking_client.log_artifact(run_id, local_path, artifact_path)
  File "/Users/meunier/opt/anaconda3/lib/python3.7/site-packages/mlflow/tracking/_tracking_service/client.py", line 355, in log_artifact
    artifact_repo.log_artifact(local_path, artifact_path)
  File "/Users/meunier/opt/anaconda3/lib/python3.7/site-packages/mlflow/store/artifact/local_artifact_repo.py", line 37, in log_artifact
    mkdir(artifact_dir)
  File "/Users/meunier/opt/anaconda3/lib/python3.7/site-packages/mlflow/utils/file_utils.py", line 114, in mkdir
    raise e
  File "/Users/meunier/opt/anaconda3/lib/python3.7/site-packages/mlflow/utils/file_utils.py", line 111, in mkdir
    os.makedirs(target)
  File "/Users/meunier/opt/anaconda3/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/Users/meunier/opt/anaconda3/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/Users/meunier/opt/anaconda3/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  [Previous line repeated 2 more times]
  File "/Users/meunier/opt/anaconda3/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
OSError: [Errno 45] Operation not supported: '/home/meunier'
```

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ x] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [x ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dbczumar** [comment]
@jlmeunier Thank you for filing this. If you're referencing an experiment that already exists in `sqlite:///$DIR/data_NMT/server.db`, the MLflow client will continue to use the artifact location associated with that experiment, which refers directly to the inaccessible server. Creating a new experiment and using that should solve your issue because it will be configured with an `mlflow-artifacts:/` artifact location.

**Comment by jlmeunier** [comment]
@dbczumar you are absolutely right.

I added a line
mlflow.set_experiment("Corey")
just before the call to start_run and then the example is working perfectly well.

Maybe the example should be modified in this way?

thanks a lot! (I like when problems disappear so easily :) )
JL

**Comment by dbczumar** [comment]
@jlmeunier Fantastic! Glad this worked out! We'll absolutely work to update our examples & docs for this feature to avoid these kinds of pitfalls - great idea. I'll go ahead and close this out for now; feel free to reopen this or raise another issue if additional issues occur.

**Comment by jlmeunier** [comment]
Actually, no, there is a problem. :-/

The client code succeed, but when one goes on the experiment page, the artifacts do not appear. Instead there is a message:
```Loading Artifacts Failed
Unable to list artifacts stored under <code>{artifactUri}</code> for the current run. Please contact your tracking server administrator to notify them of this error, which can happen when the tracking server lacks permission to list artifacts under the current run's root artifact directory.```

if I add --default-artifact-root at launch time, my client tries to access a file system on server-side and fails.

Thanks
JL

**Comment by bartekkrol96** [comment]
@jlmeunier I hope you have already solved this problem but maybe someone will be looking for a solution like me. I had exactly the same situation as you - the artifacts were saved to the right place but I couldn't list the artifacts from the experiment page. In my case, the solution was

1. setting correct credentials to s3
(environment variables AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_DEFAULT_REGION, MLFLOW_S3_ENDPOINT_URL, MLFLOW_S3_IGNORE_TLS) 
2. installing `boto3` `awscli` `psycopg2-binary` in addition to mlflow itself on the server. 

I hope this helps someone :D
