### ISSUE TITLE
[BUG] Loading Artifacts Failed

### ISSUE THREAD

**Issue by jlmeunier** [mlflow/mlflow#5439]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md) for additional information about bug reports. For help with debugging your code, please refer to [Stack Overflow](https://stackoverflow.com/questions/tagged/mlflow).

**Please fill in this bug report template to ensure a timely and thorough response.**

### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [x ] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: name of experiment changed in stock example
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: CentOS Linux release 7.9.2009 (Core)
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**: 1.23.1
- **Python version**: 3.7.4
- **npm version, if running the dev UI**: N/A
- **Exact command to reproduce**:
- server started from `$DIR`, which is /home/meunier/MLFLOW, by command
`mlflow server --host 0.0.0.0 --port 3030 --backend-store-uri sqlite:///$DIR/data_NMT/server.db --serve-artifacts --artifacts-destination ./data_NMT --gunicorn-opts "--timeout 240"`
(I have also tried to give absolute path for --artifacts-destination)
- client-side test: **choose a new unseen name for the experiment** in the example code (**Line 20** of `examples/mlflow_artifacts/example.py`)
- - run **not on server machine, but on a machine which does not see the server file system** : `MLFLOW_TRACKING_URI=http://myhost:3030 python mlflow_artifacts/example.py`

### Describe the problem
When the client machine **cannot access the server file system***
- The client code runs without any error 
- when accessing the experiment in the web UI, there is an error message: 

> _Loading Artifacts Failed
> Unable to list artifacts stored under <code>{artifactUri}</code> for the current run. Please contact your tracking server administrator to notify them of this error, which can happen when the tracking server lacks permission to list artifacts under the current run's root artifact directory._

- in server storage, I see the artifacts:

> ```~/MLFLOW/data_NMT > ls -R 4/4dd56b47f2ae4aeeb642b4208a8c9f23/artifacts/
> 4/4dd56b47f2ae4aeeb642b4208a8c9f23/artifacts/:
> a.txt  dir/
> 
> 4/4dd56b47f2ae4aeeb642b4208a8c9f23/artifacts/dir:
> b.txt
> ```

### Code to reproduce issue
See above, use a client machine without access to the file system used by the server  (in --server-artifacts mode).
It seems it is a UI issue, because the artifacts seem properly stored in server-storage.

### Other info / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [x ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ x ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by jlmeunier** [comment]
@iavinas , yes, thanks, the UI now shows the artifacts. Thanks to you all!

**Comment by BenWilson2** [comment]
Thank you for the notification nonetheless. I'm happy that it is working for you now in the latest release!

**Comment by jspablo** [comment]
I am facing exactly the same problem with `mlflow==1.28.0` and a compatible S3 storage from Digital Ocean, I can save the artifacts and check them in S3 but getting the following error from the UI
```
Unable to list artifacts stored under <code>{artifactUri}</code> for the current run. Please contact your tracking server administrator to notify them of this error, which can happen when the tracking server lacks permission to list artifacts under the current run's root artifact directory.
```

**Comment by jspablo** [comment]
Here the solution I found in case it can be useful to someone else:
When using `mlflow server` you should use your bucket name as `s3://<bucket-name>/<mlflow-folder>` and point the `MLFLOW_S3_ENDPOINT_URL` variable to your cloud provider without the bucket name. For me this is the final command:
```
export MLFLOW_S3_ENDPOINT_URL=https://<region>.digitaloceanspaces.com
mlflow server --backend-store-uri sqlite:///<local_db>.db --default-artifact-root s3://<bucket-name>/<mlflow-folder> --serve-artifacts --host 0.0.0.0
```
