### ISSUE TITLE
[FR] Create Projects Directory to organize Experiments

### ISSUE THREAD

**Issue by zbloss** [mlflow/mlflow#5493]
## Willingness to contribute
The MLflow Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature (either as an MLflow Plugin or an enhancement to the MLflow code base)?

- [ ] Yes. I can contribute this feature independently.
- [x] Yes. I would be willing to contribute this feature with guidance from the MLflow community.
- [ ] No. I cannot contribute this feature at this time.

## Proposal Summary

It would be great if MLflow allowed the grouping of experiments into another hierarchy, maybe called `Projects`. As of now, we can nest runs, but it would be extremely handy if we could group experiments similarly.

## Motivation
- What is the use case for this feature? - Keeping track of multiple experiments is more difficult as the number of experiments increases. 
- Why is this use case valuable to support for MLflow users in general? This will provide another layer of organization making the UI cleaner and easier to use.
- Why is this use case valuable to support for your project(s) or organization? Being able to group similar or related projects together will improve the user experience.
- Why is it currently difficult to achieve this use case? (please be as specific as possible about why related MLflow features and components are insufficient) Currently there is no schema or structure for grouping experiments.

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [x] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [x] `area/docs`: MLflow documentation pages
- [x] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [x] `area/server-infra`: MLflow Tracking server backend
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [x] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [x] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

## Details

I am not entirely sure how this would be implemented. My hope is we could follow similar code that was created for `Experiments` to create `Projects`. Then maybe we will need to create a bridge table, and adjust artifact directories to follow filepath://<PROJECT_ID>/<EXPERIMENT_ID>/<RUN_ID>/artifacts/*

**Comment by dbczumar** [comment]
Hi @zbloss , thank you for raising this! We've had similar asks in the past for higher levels of content organization in MLflow. We're currently tracking these requests via https://github.com/mlflow/mlflow/issues/1464. For full transparency, we don't intend to implement an additional unit of organization in the near-term.

However, we are assessing potential improvements to the experiment search / discovery experience and will absolutely post updates on https://github.com/mlflow/mlflow/issues/1464 as our brainstorming progresses. 

Thank you for using MLflow!

**Comment by NSiddanth** [comment]
Hi, just curious to know if you are going to create a higher-level grouping of content which will be ability to group experiments under maybe a segregation called Projects?

**Comment by MeganBeckett** [comment]
Hi there, also very interested in this feature? It is the main reason so far why I can;t get our team to use MLFlow - because of the limitations in organisation of experiments and runs.
