### ISSUE TITLE
[FR] add a "name" parameter when creating runs from `client.create_run()`

### ISSUE THREAD

**Issue by Rusteam** [mlflow/mlflow#5523]
## Willingness to contribute
The MLflow Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature (either as an MLflow Plugin or an enhancement to the MLflow code base)?

- [x] Yes. I can contribute this feature independently.
- [ ] Yes. I would be willing to contribute this feature with guidance from the MLflow community.
- [ ] No. I cannot contribute this feature at this time.

## Proposal Summary

When creating a run using the mlflow client, it will be useful to provide a custom name.
```
client = MlflowClient()
experiment_id = "0"
run = client.create_run(experiment_id, tags=tags, name="My custom run name")
```

## Motivation
- What is the use case for this feature?

I run hyper-parameter search with **ray[tune]** package using their [MLflow Autologging](https://docs.ray.io/en/latest/tune/tutorials/tune-mlflow.html) and then when I analyze metric plots it's hard to tell runs apart (screenshot attached). Their code uses mlflow's `client.create_run()`

- Why is this use case valuable to support for MLflow users in general?

It will eliminate the need for manual clicking on each run to find out its details.

- Why is it currently difficult to achieve this use case? (please be as specific as possible about why related MLflow features and components are insufficient)

Currently there's no option of adding a custom run name, whilst the option is present in `mlflow.start_run()`.

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [x] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

![Screen Shot 2022-03-23 at 12 08 46](https://user-images.githubusercontent.com/22130831/159652788-dafc46d5-8388-4044-b676-27df07dc7686.png)

**Comment by dbczumar** [comment]
@Rusteam thank you for filing this, and, @tahesse, thank you for responding. We have merged https://github.com/mlflow/mlflow/pull/5187 to address this issue. Thank you for using MLflow!

**Comment by Rusteam** [comment]
@dbczumar that PR seems to address MLflow Projects.
Would it also allow to set a run name from `MLflowClient().create_run()` for other use cases?

**Comment by dbczumar** [comment]
@Rusteam My apologies. I misinterpreted. We're excited to review a PR for this, if you're still willing to contribute one.

**Comment by Rusteam** [comment]
Definitely. I can do this.

In a nutshell, what I have to do is to:
- add `run_name` parameter to `create_run()` in **sqlalchemy_store.py**
- add `run_name` parameter to `RunInfo()` in **run_info.py** in the call inside `create_run()` in `file_store.py`
- to set a `run_name` from `create_run()` in `tracking.MLflowClient()`, default is None or "".

anything else?

**Comment by Rusteam** [comment]
@dbczumar, 

stuck at this error:
```
    return _message.default_pool.FindFieldByName(full_name)
E   KeyError: "Couldn't find field mlflow.CreateRun.run_name"
```

added:
```
    _descriptor.FieldDescriptor(
      name='tags', full_name='mlflow.CreateExperiment.tags', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
``` 
 to **service_pb2.py**

and ` optional string run_name = 11;` to `CreateRun` in **service.proto**,
but without any luck.

If you can give me some directions how to fix this issue, would save me tons of time. Thanks

**Comment by dbczumar** [comment]
> @dbczumar,
> 
> stuck at this error:
> 
> ```
>     return _message.default_pool.FindFieldByName(full_name)
> E   KeyError: "Couldn't find field mlflow.CreateRun.run_name"
> ```
> 
> added:
> 
> ```
>     _descriptor.FieldDescriptor(
>       name='tags', full_name='mlflow.CreateExperiment.tags', index=2,
>       number=3, type=11, cpp_type=10, label=3,
>       has_default_value=False, default_value=[],
>       message_type=None, enum_type=None, containing_type=None,
>       is_extension=False, extension_scope=None,
>       serialized_options=None, file=DESCRIPTOR),
> ```
> 
> to **service_pb2.py**
> 
> and ` optional string run_name = 11;` to `CreateRun` in **service.proto**, but without any luck.
> 
> If you can give me some directions how to fix this issue, would save me tons of time. Thanks

Hi @Rusteam , apologies for the delay here. Instead of extending the REST API, can we add a `name=None` argument to `create_run()` and, if it's not `None`, add the corresponding run name tag to the dictionary of tags that are passed as part of the CreateRun request?

**Comment by Rusteam** [comment]
That's what I was gonna do. 
In that case it wouldn't be handled by FileStore and SQLAlchemyStore, would it?

**Comment by dbczumar** [comment]
> That's what I was gonna do. In that case it wouldn't be handled by FileStore and SQLAlchemyStore, would it?

Hi @Rusteam , apologies for the delay. `MlflowClient.create_run()` now accepts the `run_name` argument: https://github.com/mlflow/mlflow/blob/37f4bbe69e975a505a0b61bc7509bad3f784efdf/mlflow/tracking/client.py#L224. Thank you for using MLflow!
