### ISSUE TITLE
[FR] Be able to set the description of a run programmatically

### ISSUE THREAD

**Issue by dogeplusplus** [mlflow/mlflow#5526]
Thank you for submitting a feature request. **Before proceeding, please review MLflow's [Issue Policy for feature requests](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md#feature-requests) and the [MLflow Contributing Guide](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst)**.

**Please fill in this feature request template to ensure a timely and thorough response.**

## Willingness to contribute
The MLflow Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature (either as an MLflow Plugin or an enhancement to the MLflow code base)?

- [ ] Yes. I can contribute this feature independently.
- [ ] Yes. I would be willing to contribute this feature with guidance from the MLflow community.
- [x] No. I cannot contribute this feature at this time.

## Proposal Summary

Not sure if this is possible already, but it would be nice to have some functionality to set the description of a run programmatically. Checking through the documentation and issues I haven't found a way of doing this yet. This could manifest as one or more of:
- `mlflow.start_run` would have a parameter `description` that would be just an `Optional[str]`.
- A new function `mlflow.set_description` taking a single string `description`.
- As a possible extra `mlflow.get_description` would retrieve the current description.
- Probably would need to modify the `mlflow.entities` module as well.

## Motivation
- What is the use case for this feature?
Being able to provide some text description when submitting a job from the command line at the start of the run instead of going to the web UI after the job is triggered.

- Why is this use case valuable to support for MLflow users in general?
Users could start runs with a particular set of hyper-parameters and provide a some description of what its trying to achieve/test without starting the server.

- Why is this use case valuable to support for your project(s) or organization?
At the moment I am triggering runs using argument parsers in the command line. It would be nice to just set the description at the point of starting the run and not have to worry about it later.

- Why is it currently difficult to achieve this use case? (please be as specific as possible about why related MLflow features and components are insufficient)
It isn't that much effort for me to set the description in the web UI. But I felt that if it was possible to set tags programmatically, then being able to set descriptions also would make the logging more feature complete.

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

## Details
If this feature exists or has been raised already feel free to close the issue.

**Comment by BenWilson2** [comment]
Hi @dogeplusplus would the current functionality included in the context wrapper `mlflow.start_run()` that supports defining the arguments `run_name` and `tags`={"run_description": "This is what this model is for..."}` solve your use case? 
There isn't a specific construct for a 'run description' present in the signature for an MLflowObject (a run). Any UI-based description fields that are present are simply logged as tags and are rendered in a different manner from within the UI. 
Setting descriptions and any additional data are typically done through applying tags to the run. 
This is typically how users define ancillary information to be associated with a run in code rather than having to add information in the GUI. See: [the API docs](https://www.mlflow.org/docs/latest/python_api/mlflow.html#mlflow.start_run)  for the full signature.

**Comment by dogeplusplus** [comment]
Technically yes I could use the tags or the run name to do that. I just thought it would be nice to be able to inject like a paragraph since there is a description box right there. The box is also wider which makes it slightly more easier to read longer pieces than the tags section. However I know that my use case may be niche so feel free to close this issue if it's not worth implementing.

**Comment by BenWilson2** [comment]
Oh, not at all! Thank you for the reported idea. We'll discuss it internally and determine if it's something that we'd like to include. We appreciate your ideas and if you have any others, please feel free to share them!

**Comment by Jingnan-Jia** [comment]
This is a very necessary feature, I have been looking forward to it for a long time.

Nowthat the experiment/run's name, tags can be customed, why the `description` can not? 

In the following figure, we can see all titles (Parameters, Metrics, tags, Artifacts) could be assigned values by users except `description`.
![image](https://user-images.githubusercontent.com/34941987/160029182-c9910160-e5c0-4183-afe5-538baac1aed4.png)

**Comment by BenWilson2** [comment]
If anyone would like to contribute a PR for this, please feel free to add the `description` argument to the fluent API and have it set the appropriate tag key that populates this Description field in the UI. We'll be happy to review it!

**Comment by BenWilson2** [comment]
![Screen Shot 2022-03-24 at 9 11 02 PM](https://user-images.githubusercontent.com/39283302/160035325-0df8fdac-2117-4914-a3c5-953e06594cdd.png)

**Comment by dogeplusplus** [comment]
Now that it's the weekend I had some time to give this a go: #5534. Feel free to make changes directly on it or suggest ones that I can try to implement.
