### ISSUE TITLE
[BUG] Autologging error No encoder for object when adding regularization to pretrained model

### ISSUE THREAD

**Issue by mattpotma** [mlflow/mlflow#5530]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md) for additional information about bug reports. For help with debugging your code, please refer to [Stack Overflow](https://stackoverflow.com/questions/tagged/mlflow).

**Please fill in this bug report template to ensure a timely and thorough response.**

### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [x] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.04
- **MLflow installed from (source or binary)**: binary (poetry)
- **MLflow version (run ``mlflow --version``)**: 1.23.0, 1.24.0
- **Python version**: 3.9.7
- **npm version, if running the dev UI**: N/A
- **Exact command to reproduce**: Code provided below

### Describe the problem

Attempting to log a model which has regularization applied results in an error, `Encountered unexpected error during autologging: No encoder for object <keras.layers.convolutional.Conv2D object at 0x7f7a264e2610> of type <class 'keras.layers.convolutional.Conv2D'>.`.

If the regularization is added without setting the lambda default argument (`layer.add_loss(lambda: regularizer(layer.kernel))`), MLFlow can log the model, but certain architectures in TensorFlow, the regularization isn't applied to the correct layer. For example, the sample code provided below will fail with `AttributeError: 'Activation' object has no attribute 'kernel'` without the lambda default argument applied.

### Code to reproduce issue

```python
import mlflow
import numpy as np
import tensorflow as tf


mlflow.tensorflow.autolog()

model = tf.keras.applications.MobileNetV3Small(input_shape=(96, 96, 3))
regularizer = tf.keras.regularizers.L1(1e-3)

for layer in model.layers:
    if hasattr(layer, "kernel"):
        layer.add_loss(lambda l=layer: regularizer(l.kernel))

model.compile(loss="mse")
model.fit(
    np.random.randn(10, 96, 96, 3),
    np.random.randn(10, 1000),
)
```

### Other info / logs

No traceback, as no exception is raised. The following is all the relevant console output.

```
2022/03/25 09:18:19 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '0c7f1536b1504a50b426047ecd7964f8', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current tensorflow workflow
1/1 [==============================] - 5s 5s/step - loss: 173.9332
2022-03-25 09:18:28.022359: W tensorflow/python/util/util.cc:368] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
2022/03/25 09:18:34 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during autologging: No encoder for object <keras.layers.convolutional.Conv2D object at 0x7fe81ceeefd0> of type <class 'keras.layers.convolutional.Conv2D'>.
```

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [x] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [x] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by mattpotma** [comment]
This may just be an issue on TensorFlow's end. It's just raising an error from this line: https://github.com/mlflow/mlflow/blob/2e175e7fd65d86d12d204b648aa5ff73063a7dc9/mlflow/keras.py#L266

The model will save as `h5` format only, but sadly it appears MLFlow logging only supports the `SavedModel` format.
