### ISSUE TITLE
[FR] Make mlflow.tracking.artifact_utils._download_artifact_from_uri a public function

### ISSUE THREAD

**Issue by pogil** [mlflow/mlflow#5546]
Thank you for submitting a feature request. **Before proceeding, please review MLflow's [Issue Policy for feature requests](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md#feature-requests) and the [MLflow Contributing Guide](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst)**.

**Please fill in this feature request template to ensure a timely and thorough response.**

## Willingness to contribute
The MLflow Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature (either as an MLflow Plugin or an enhancement to the MLflow code base)?

- [ ] Yes. I can contribute this feature independently.
- [ ] Yes. I would be willing to contribute this feature with guidance from the MLflow community.
- [x] No. I cannot contribute this feature at this time.

## Proposal Summary

Make `mlflow.tracking.artifact_utils._download_artifact_from_uri` a public function.

## Motivation

Many workflows require download of models for easier orchestration. Right now this is available via the CLI or indirectly as a side effect of functions like `mlflow.pyfunc.load_model`. 

One example workflow would be deploying a model to Azure from a model registered in a non-AzureML workspace (e.g. Azure Databricks, a self managed instance of MLflow, ...). The workflow looks like 
(1) set the client URIs to the non-AzureML workspace
(2) download the model 
(3) change the client URIs to AzureML workspace
(4) deploy the model

Right now step (2) is a bit clunky, requiring users to use a private function, the CLI, or have the model downloaded as a side effect of some other function call. However, if we make `mlflow.tracking.artifact_utils._download_artifact_from_uri` a public function, we can provide a cleaner, more clearly supported path. 

Related: #5241

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [x] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

## Details

(Use this section to include any additional information about the feature. If you have a proposal for how to implement this feature, please include it here. For implementation guidelines, please refer to the [Contributing Guide](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst#contribution-guidelines).)

**Comment by dbczumar** [comment]
Addressed via https://github.com/mlflow/mlflow/pull/5585
