### ISSUE TITLE
[BUG] DB IntegrityError is not caught causing the server to hang for over 60 seconds

### ISSUE THREAD

**Issue by grybeck** [mlflow/mlflow#5704]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md) for additional information about bug reports. For help with debugging your code, please refer to [Stack Overflow](https://stackoverflow.com/questions/tagged/mlflow).

**Please fill in this bug report template to ensure a timely and thorough response.**

### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [x] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: CentOS Linux 7
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**: mlflow, version 1.23.1
- **Python version**: Python 3.9.5
- **npm version, if running the dev UI**: N/A
- **Exact command to reproduce**: 

```
# this gives an expected error RestException: RESOURCE_ALREADY_EXISTS
mlflow.create_experiment("Default")
# this gives an unexpected error and makes the server unresponsive for over 60 seconds
mlflow.create_experiment("Default", artifact_location="local")
```

### Describe the problem
Describe the problem clearly here. Include descriptions of the expected behavior and the actual behavior.

When I run `mlflow.create_experiment("HelloWorld", artifact_location="local")` where HelloWorld is an experiment that already exists, instead of getting the expected error `RestException: RESOURCE_ALREADY_EXISTS`, the request hangs for over 60 seconds effectively making the server go unresponsive, and finally returns the error: 
```
MlflowException: API request to http://localhost:5000/api/2.0/mlflow/experiments/create failed with exception HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/2.0/mlflow/experiments/create (Caused by ResponseError('too many 500 error responses'))
```

This does not happen without artifact_location argument. 

Server Error: 
```
Traceback (most recent call last):
  File "/pyenv/versions/mlplats-mlflow/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/pyenv/versions/mlplats-mlflow/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/pyenv/versions/mlplats-mlflow/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/pyenv/versions/mlplats-mlflow/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/pyenv/versions/mlplats-mlflow/lib/python3.9/site-packages/mlflow/server/handlers.py", line 241, in wrapper
    response.set_data(e.serialize_as_json())
  File "/pyenv/versions/mlplats-mlflow/lib/python3.9/site-packages/mlflow/exceptions.py", line 60, in serialize_as_json
    return json.dumps(exception_dict)
  File "/pyenv/versions/3.9.5/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/pyenv/versions/3.9.5/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/pyenv/versions/3.9.5/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/pyenv/versions/3.9.5/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type IntegrityError is not JSON serializable
```
### Tracking information

For bugs related to the tracking features (e.g. mlflow should log a run in my database but it doesn't), please insert the following code in your python script / notebook where you encountered the bug and run it:

```python
print("MLflow version:", mlflow.__version__)
print("Tracking URI:", mlflow.get_tracking_uri())
print("Artifact URI:", mlflow.get_artifact_uri())
```

Then, make sure the printed out information matches what you expect and paste it (with sensitive information masked) in the box below:

```
MLflow version: 1.25.1
Tracking URI: http://localhost:5000/
Artifact URI: local-artifacts/0/68e0c4bee1a14515b03884c56e221f9b/artifacts
```

If you know the command that was used to launch your tracking server (e.g. `mlflow server -h 0.0.0.0 -p 5000`), please provide it:

```
mlflow server --backend-store-uri sqlite:///mydb.sqlite --default-artifact-root=local-artifacts --host 0.0.0.0

```

### Code to reproduce issue
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
```
# this works
mlflow.create_experiment("HelloWorld", artifact_location="local")
# this breaks and makes the server unresponsive for over 60 seconds
mlflow.create_experiment("HelloWorld", artifact_location="local")
```

### Other info / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by WeichenXu123** [comment]
I found 2 issues related to this ticket:
1. The DB server worker raise mlflow exception with message set as an IntegrityError instance which cannot be dumped as JSON. 
2. The client keeps retries when requests failed. this is why it hangs for about 1 minute.

I create a fixing PR https://github.com/mlflow/mlflow/pull/5715
