### ISSUE TITLE
[FR] Customizable timeout and retry for rest_store api calls.

### ISSUE THREAD

**Issue by peterdhansen** [mlflow/mlflow#5744]
Thank you for submitting a feature request. **Before proceeding, please review MLflow's [Issue Policy for feature requests](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md#feature-requests) and the [MLflow Contributing Guide](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst)**.

**Please fill in this feature request template to ensure a timely and thorough response.**

## Willingness to contribute
The MLflow Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature (either as an MLflow Plugin or an enhancement to the MLflow code base)?

- [X] Yes. I can contribute this feature independently.
- [ ] Yes. I would be willing to contribute this feature with guidance from the MLflow community.
- [ ] No. I cannot contribute this feature at this time.

## Proposal Summary
Customize defaults for `http_request`.
 
## Motivation
- What is the use case for this feature? Allow users to customize timeout
- Why is this use case valuable to support for MLflow users in general? Currently the default timeout is 2 minutes with 5 retries and a backoff of 2x which goes over an hour before it fails. 
- Why is it currently difficult to achieve this use case? (please be as specific as possible about why related MLflow features and components are insufficient) There is no way to customize the timeout using the Pytho nAPI

### What component(s), interfaces, languages, and integrations does this feature affect?
Components
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

## Details
https://github.com/mlflow/mlflow/blob/master/mlflow/utils/rest_utils.py#L94
```python
def http_request(
    host_creds,
    endpoint,
    method,
    max_retries=5,
    backoff_factor=2,
    retry_codes=_TRANSIENT_FAILURE_RESPONSE_CODES,
    timeout=120,
    **kwargs,
):
```

could change to 
```python

_MAX_RETRIES=5
_DEFAULT_TIMEOUT=120
_BACKOFF_FACTOR=2
def http_request(
    host_creds,
    endpoint,
    method,
    max_retries=_MAX_RETRIES,
    backoff_factor=_BACKOFF_FACTOR,
    retry_codes=_TRANSIENT_FAILURE_RESPONSE_CODES,
    timeout=_DEFAULT_TIMEOUT,
    **kwargs,
):
```

**Comment by WeichenXu123** [comment]
Shall we add related configs for rest API service ?
