### ISSUE TITLE
[BUG] Problems with change run name in UI

### ISSUE THREAD

**Issue by adamwawrzynski** [mlflow/mlflow#5774]
### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [x] No. I cannot contribute a bug fix at this time.

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04
- **MLflow version**: 1.25.1:
- **Python version**: 3.8.0:

### Describe the problem
Problem with UI. When I enter experiment run and I select 3 dots on the right side and select "Rename" I got pop up with text field. I can copy and paste new name into but when I try to write in this text field I've got string clipped to the last character I typed. Tested on Firefox 99.0 and Chromium 99.0.4844.84.

### Other info / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

### What component(s), interfaces, languages, and integrations does this bug affect?
Components
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface
- [x] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@adamwawrzynski Could you take a screen recording and share it?

**Comment by harupy** [comment]
@adamwawrzynski gentle ping

**Comment by harupy** [comment]
@adamwawrzynski Thanks for the video, can you clarify the steps to reproduce the issue?

**Comment by adamwawrzynski** [comment]
@harupy I've installed latest `mlflow==1.25.1` in virtualenv with Python `3.8`. I've created bunch of experiments and runs to test this tool. When I enter any run and try to change it's name (as in video) text field is selecting all content after typing any character. So to pass desired run name I have to select right arrow after every typed character to unselect content of text field. It's annoying.

**Comment by adamwawrzynski** [comment]
@harupy It works just fine.

**Comment by harupy** [comment]
Can you open this page?

https://harupy-mlflow-7rwqxj6rcxg6j-3000.githubpreview.dev/#/experiments/0

**Comment by adamwawrzynski** [comment]
@harupy Yes and I can change run name without problems. That's weird.

**Comment by harupy** [comment]
I was able to reproduce the issue using `mlflow==1.25.1`.

**Comment by harupy** [comment]
It appears MLflow UI assets in mlflow versions >= 1.24.0 were created using `npm install && npm run build` but they should've been created using `yarn install && yarn build`. We'll fix this in the next release.

**Comment by harupy** [comment]
@adamwawrzynski We fixed our internal Jenkins job that publishes a new version. We're going to release MLflow 1.26.0 soon!
