### ISSUE TITLE
[FR] Freeze the first row (title row) of mlflow UI

### ISSUE THREAD

**Issue by Jingnan-Jia** [mlflow/mlflow#5789]
**Please fill in this feature request template to ensure a timely and thorough response.**

## Willingness to contribute
The MLflow Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature (either as an MLflow Plugin or an enhancement to the MLflow code base)?

- [ ] Yes. I can contribute this feature independently.
- [ ] Yes. I would be willing to contribute this feature with guidance from the MLflow community.
- [X] No. I cannot contribute this feature at this time.

## Proposal Summary

(In a few sentences, provide a clear, high-level description of the feature request)
The tracking UI needs to be able to fix the first row (title row) so that when we have a lot of runs, we can still clearly know the meaning of each column in the runs at the bottom of the page. At present, we I scroll down to the earlier runs, I do not know the meaning of each column. I have to scroll up several times to see the title of each column to confirm the meaning of each value.

The first screenshot shows that we can see the column titles when we scroll up.
![image](https://user-images.githubusercontent.com/34941987/165563399-32b35a67-f9ea-4949-8164-6b8c9771416d.png)

The second screenshot shows that I can not see the column title of the runs at the bottom of the screen when we have a lot of runs in the same experiment. So I hope we can have a feature to fix the title row so that we can always see the column titles even when we scroll down to the bottom. 

![image](https://user-images.githubusercontent.com/34941987/165563693-79e6124a-cdf5-4aa9-bbd7-31378e6e8ca7.png)

This feature would look like the "View -> Freeze Pans -> Freeze top row" in Excel.
![image](https://user-images.githubusercontent.com/34941987/165565317-4f7f28fb-150d-4758-b541-4bce05a0ca82.png)

## Motivation
- What is the use case for this feature?
When there are a lot of runs, it is necessary to see the column title for the runs at the bottom of the screen.

- Why is this use case valuable to support for MLflow users in general?
A lot of users would benefit from the feature.

- Why is it currently difficult to achieve this use case? (please be as specific as possible about why related MLflow features and components are insufficient)
At present there is no such feature at all to achieve it.

### What component(s), interfaces, languages, and integrations does this feature affect?
Components
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

**Comment by Jingnan-Jia** [comment]
split the two screenshots.

**Comment by dbczumar** [comment]
@Jingnan-Jia Thank you for raising this issue! I completely agree that this is necessary for a good user experience. I've added the `good first issue` and `help wanted` labels in hopes of soliciting a contribution.

**Comment by dbczumar** [comment]
@sunishsheth2009 Do you know how we can fix this?

**Comment by harupy** [comment]
Related SO post: https://stackoverflow.com/questions/40427888/ag-grid-keep-header-on-top-while-scrolling

**Comment by sunishsheth2009** [comment]
Hey @harupy and @dbczumar we already have a fix for this and will be merged soon by Hubert. Lets wait for his fix to be merged soon. :)

**Comment by Jingnan-Jia** [comment]
Another related feature should be: Make it possible to scroll right/left without the need to scroll down to the bottom.

In the following image, at present when I want to check more metrics (outsied the "screen") of the current runs, I have to scroll down to the bottom to get the horizontal bar, then press and hold the horizontal bar to the left/right to see more metrics.

![image](https://user-images.githubusercontent.com/34941987/166301674-a3415bfb-085c-462c-bb70-6d74a4491af8.png)

So I hope that there should be another set of seperate horizontal bar and vertical bar for the experiments/runs, so that we can see move the bars to see the column titles all the time and see more parameters/metrics easily.

**Comment by hubertzub-db** [comment]
@Jingnan-Jia @sunishsheth2009 
PR containing fixed header row is here
https://github.com/mlflow/mlflow/pull/5818
Example: 
![Apr-28-2022 17-48-45](https://user-images.githubusercontent.com/104438646/166874634-fe316780-97a8-4e7d-9c3d-746794cd31a6.gif)

Regarding https://github.com/mlflow/mlflow/issues/5789#issuecomment-1115211507 comment:
It is possible to scroll horizontally by using trackpad or shift+wheel (while hovering the scrollable area). The horizontal scroll position will be reflected correctly in the fixed header. We can try to find a way to display the horizontal scrollbar itself on the bottom of the viewport, it might be non-trivial through.

**Comment by hubertzub-db** [comment]
@Jingnan-Jia 
I'm not sure when the current code is going to be released in the `pip` registry, however since it's been merged you can clone the code and run it by yourself. You can refer to the following document:
https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst#developing-and-testing-mlflow

**Comment by harupy** [comment]
Addressed by #5856
