### ISSUE TITLE
[BUG] Artifacts not saved to local filesystem

### ISSUE THREAD

**Issue by ntakouris** [mlflow/mlflow#5835]
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### System information

- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: no 
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  Ubuntu 20.04 LTS
- **MLflow installed from (source or binary)**: yes
- **MLflow version (run ``mlflow --version``)**: 1.25.1
- **Python version**: 3.8.12

### Describe the problem

1. Configure a mlflow tracking server to run on a postgres instance and use the local filesystem as artifact root 
`mlflow server --backend-store-uri postgresql://mlflow:mlflow@localhost/mlflow --default-artifact-root /opt/mlflow/mlruns -h 0.0.0.0 -p 5000`
2. Instantiate a client and save some artifacts
```py 
client = MlflowClient(
            tracking_uri="http://localhost:5000",
        )
```
3. Create an experiment and register some artifact

```
experiment_id = client.create_experiment(name)

run = tracker.client.create_run(
    experiment_id,
)

run_id = run.info.run_id

client.log_artifact(
            run_id,
            local_path=artifact_file,
        )
```

3. Use 
```py
client.download_artifacts(
            run_id, os.path.join(artifact_scope, artifact_file)
        ) # ok
```
5. Open up `/opt/mlflow/mlruns`:
< directory is empty > !

6. Open up mlflow at `http://localhost:5000`. Artifacts are empty too! 

Where are those artifacts saved on disk? How do I make them appear at the ui?

### Code to reproduce issue

See problem description

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by browser-bug** [comment]
Just a shot in the dark but I don't think MLflow does (or can) support a local directory as artifact storage while using a remote backend store (e.g. an SQL-like database). Even if no errors are displayed on the CLI during launch, most probably the tracking server cannot find the artifact giving the local path, hence the unexpected behavior (you could verify this looking at the browser console logs while on the tracking server UI). 
Maybe using `file:/opt/mlflow/mlruns` instead of just `/opt/mlflow/mlruns` could tweak this but I doubt it will work anyway.

Maybe someone with more expertise can confirm this or give you some insight on your use case scenario nonetheless.

**Comment by harupy** [comment]
@ntakouris The following code saves artifacts in the `foo` directory. Am I missing something?

```
mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root foo -h 0.0.0.0 -p 5000
```

```python
import mlflow
import uuid

client = mlflow.tracking.MlflowClient(
    tracking_uri="http://localhost:5000",
)
name = uuid.uuid4().hex
eid = client.create_experiment(name)
print(client.get_experiment(eid))

run = client.create_run(eid)
run_id = run.info.run_id
client.log_artifact(run_id, local_path=__file__)
```

Output:

```
<Experiment: artifact_location='foo/9', experiment_id='9', lifecycle_stage='active', name='cd17250444dc4ac48667def6574409c7', tags={}>
```

**Comment by ntakouris** [comment]
@browser-bug So, if I set sftp to localhost it's going to work? That's a weird workaround.

@harupy I was using the sqlite variant before, and it did create a `mlruns.sqlite` and an `mlruns/` directory at the same directory when I did run the python (training) script command. But it was using that without the mlflow server.

Let's say I do `cd ~/testing && mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root foo -h 0.0.0.0 -p 5000`

I then save some artifact: the `~/testing/foo` directory is created, but nothing is inside:
```
ntak@sys76-ntakouris:~/testing$ ls foo/
ntak@sys76-ntakouris:~/testing$ ls
foo  mlflow.db
```

I also tried `file:///foo` and it works as expected: it tells me that I don't have permission. However, if I create the directory as I stated above: `/opt/mlflow/mlruns` and chmod 777 it (so there's no ownership problem), the same thing happens (no artifacts)!

**Comment by harupy** [comment]
@ntakouris Are you creating a new experiment? What does `print(mlflow.get_artifact_uri())` print out?

**Comment by ntakouris** [comment]
@harupy The `mlflow.tracking.MlflowClient` class does not contain a method `get_artifact_uri()`. I am passing in `tracking_uri="http://localhost:5000"` as expected, though.

**Comment by harupy** [comment]
If so, please run `print(run)`. The output should look like this:

```
<Run: data=<RunData: metrics={}, params={}, tags={}>, info=<RunInfo: artifact_uri='foo/9/bf13e18440aa46eeac3120684c65d137/artifacts', end_time=None, experiment_id='9', lifecycle_stage='active', run_id='bf13e18440aa46eeac3120684c65d137', run_uuid='bf13e18440aa46eeac3120684c65d137', start_time=1652169699156, status='RUNNING', user_id='unknown'>>
```

**Comment by ntakouris** [comment]
@harupy 

```
info=<RunInfo: artifact_uri='/opt/mlflow/mlruns/1/211770d1922f4d77934ddde7bac1126a/artifacts', end_time=None, experiment_id='1', lifecycle_stage='active', run_id='211770d1922f4d77934ddde7bac1126a', run_uuid='211770d1922f4d77934ddde7bac1126a', start_time=1652172411458, status='RUNNING', user_id='unknown'>>
```

... but the directory `/opt/mlflow/mlruns` is empty. 

I figured out the problem right now: it does not communicate with the server and instead tries to save this locally. 

So, instead of saving to the os `/opt/mlflow/mlruns`, it saves it inside the docker container where the training script is running. (So, the tracking server is not used to save the artifacts).

**Comment by harupy** [comment]
@ntakouris Got it, can you try running this command?

```
mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root mlflow-artifacts:/mlartifacts -h 0.0.0.0 -p 5000
```

doc: https://www.mlflow.org/docs/latest/tracking.html#artifact-stores

**Comment by ntakouris** [comment]
@harupy they are still being saved inside the container (wrong machine).

From the docs you linked: `mlflow-artifacts:/` is supposed to link to whatever existing artifact storage there is (ex. s3). I've not configured s3. I just want the artifacts to be stored on the local directory, of the machine/container that the tracking server runs.

**Comment by harupy** [comment]
@ntakouris Can you try running this command?

```
mlflow server \
  --backend-store-uri sqlite:///mlflow.db \
  --artifacts-destination ./mlruns \
  --default-artifact-root mlflow-artifacts:/mlartifacts \
  -h 0.0.0.0 -p 5000
```

and this code

```python
import mlflow
import uuid

mlflow.set_tracking_uri("http://localhost:5000")

mlflow.set_experiment(uuid.uuid4().hex)

with mlflow.start_run() as run:
    mlflow.log_artifact(__file__)

```

**Comment by ntakouris** [comment]
@harupy It gets stuck with log message: `INFO mlflow.tracking.fluent: Experiment with name '0395ab8d3a5b4c2d94885b713befacfa' does not exist. Creating a new experiment.`

Same thing happens if I use `--artifacts-destination /opt/mlflow/mlruns --default-artifact-root mlflow-artifacts:/artifacts`

**Comment by ntakouris** [comment]
If I `^C` it,

```
  File "training/test.py", line 10, in <module>
    mlflow.log_artifact(__file__)
  File "/opt/conda/lib/python3.8/site-packages/mlflow/tracking/fluent.py", line 693, in log_artifact
    MlflowClient().log_artifact(run_id, local_path, artifact_path)
  File "/opt/conda/lib/python3.8/site-packages/mlflow/tracking/client.py", line 955, in log_artifact
    self._tracking_client.log_artifact(run_id, local_path, artifact_path)
  File "/opt/conda/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py", line 337, in log_artifact
    artifact_repo.log_artifact(local_path, artifact_path)
  File "/opt/conda/lib/python3.8/site-packages/mlflow/store/artifact/http_artifact_repo.py", line 25, in log_artifact
    resp = http_request(self._host_creds, endpoint, "PUT", data=f, timeout=600)
  File "/opt/conda/lib/python3.8/site-packages/mlflow/utils/rest_utils.py", line 151, in http_request
    return _get_http_response_with_retries(
  File "/opt/conda/lib/python3.8/site-packages/mlflow/utils/rest_utils.py", line 91, in _get_http_response_with_retries
    return session.request(method, url, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/conda/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/opt/conda/lib/python3.8/site-packages/urllib3/connectionpool.py", line 846, in urlopen
    return self.urlopen(
  File "/opt/conda/lib/python3.8/site-packages/urllib3/connectionpool.py", line 846, in urlopen
    return self.urlopen(
  File "/opt/conda/lib/python3.8/site-packages/urllib3/connectionpool.py", line 846, in urlopen
    return self.urlopen(
  [Previous line repeated 1 more time]
  File "/opt/conda/lib/python3.8/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries.sleep(response)
  File "/opt/conda/lib/python3.8/site-packages/urllib3/util/retry.py", line 414, in sleep
    self._sleep_backoff()
  File "/opt/conda/lib/python3.8/site-packages/urllib3/util/retry.py", line 398, in _sleep_backoff
    time.sleep(backoff)
KeyboardInterrupt
```

**Comment by harupy** [comment]
Did you use `--serve-artifacts`?

**Comment by ntakouris** [comment]
@harupy Thank you for your help,

`mlflow server --backend-store-uri postgresql://mlflow:mlflow@localhost/mlflow --serve-artifacts --artifacts-destination /opt/mlflow/mlruns  -h 0.0.0.0 -p 5000` Solved the issue (no need to `--default-artifact-root mlflow-artifacts:/mlartifacts`, it's picked up automatically and placed under `/opt/mlflow/mlruns`.

Before I mark this issue as resolved, do you want to start up a PR to update docs with this command "preset"?

**Comment by harupy** [comment]
@ntakouris I think we already have a similar command example in https://www.mlflow.org/docs/latest/tracking.html#scenario-5-mlflow-tracking-server-enabled-with-proxied-artifact-storage-access.
