### ISSUE TITLE
[BUG] Uncaught 500 Error for python tracking api create_run with bad input on experiment_id, e.g. experiment_name, for Postgres backend

### ISSUE THREAD

**Issue by grybeck** [mlflow/mlflow#5847]
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### System information

- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac Big Sur
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**: 1.25.1
- **Python version**: 3.9.7
- **npm version, if running the dev UI**: N/A

### Describe the problem

When I mistakenly use experiment_name rather than experiment_id in the create_run method, the server throws a 500 error (uncaught error) rather than a RestException:
```
from mlflow.tracking import MlflowClient
client = MlflowClient()
client.create_run("example experiment name")
```
We would like that input validation caught and returned as a RestException to the client rather than a 500 error on the server, because many users accidentally set their experiment name as the parameter rather than experiment_id.

### Tracking information

MLflow version: 1.25.1
Tracking URI: http://localhost:5000

### Code to reproduce issue

```
from mlflow.tracking import MlflowClient
client = MlflowClient()
client.create_run("example experiment name")
```

### Other info / logs

Error (on client side):
```
MlflowException: API request to http://localhost:5000/api/2.0/mlflow/runs/create failed with exception HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/2.0/mlflow/runs/create (Caused by ResponseError('too many 500 error responses'))
```
Error (on server side):
```
raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DataError is not JSON serializable
[11/May/2022:15:48:13 -0400] "POST /api/2.0/mlflow/runs/create HTTP/1.1" 500 290 "-" "mlflow-python-client/1.25.1"
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [X] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by rafaelvp-db** [comment]
wasn't able to reproduce it, so looks like it was fixed at some point? @grybeck 

`client.create_run("example experiment name")`

`mlflow.exceptions.MlflowException: Invalid experiment ID: 'example experiment name'`

**Comment by Matesanz** [comment]
May it be that the `mlruns` folder was not created or MLFLOW has not access to it.

**Comment by xhensiladoda** [comment]
@Matesanz yeah might be related to similar issue https://github.com/mlflow/mlflow/issues/17812
Solution proposed at https://github.com/mlflow/mlflow/issues/17812#issuecomment-3328174158
