### ISSUE TITLE
[BUG] Obscure error when Docker not started

### ISSUE THREAD

**Issue by stobias123** [mlflow/mlflow#5851]
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### System information

- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: Nope - pretty standard
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: OSX
- **MLflow installed from (source or binary)**: pip
- **MLflow version (run ``mlflow --version``)**: mlflow, version 1.24.0
- **Python version**: Python 3.8.2
- **npm version, if running the dev UI**:

### Describe the problem

When docker daemon is not running on OSX, `mlflow run .` with docker env returns a cryptic "file not found error".

```
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
```

### Code to reproduce issue

```yaml
name: foo

docker_env:
  image: gcr.io/foo/bar-mlflow-base

entry_points:
  main:
    parameters:
      timesteps: { type: int, default: 100 }
      record_timesteps: { type: int, default: 1000 }
    command: "python pipeline.py --timesteps {timesteps} --record-timesteps {record_timesteps}"
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [X] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [X] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@stobias123 Please share the full stack trace.

**Comment by stobias123** [comment]
```
Traceback (most recent call last):
  File "/Users/user/.virtualenvs/user/bin/mlflow", line 8, in <module>
    sys.exit(cli())
  File "/Users/user/.virtualenvs/user/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/user/.virtualenvs/user/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/user/.virtualenvs/user/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/user/.virtualenvs/user/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/user/.virtualenvs/user/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/user/.virtualenvs/user/lib/python3.8/site-packages/mlflow/cli.py", line 168, in run
    projects.run(
  File "/Users/user/.virtualenvs/user/lib/python3.8/site-packages/mlflow/projects/__init__.py", line 293, in run
    submitted_run_obj = _run(
  File "/Users/user/.virtualenvs/user/lib/python3.8/site-packages/mlflow/projects/__init__.py", line 145, in _run
    image = build_docker_image(
  File "/Users/user/.virtualenvs/user/lib/python3.8/site-packages/mlflow/projects/docker.py", line 69, in build_docker_image
    client = docker.from_env()
  File "/Users/user/.virtualenvs/user/lib/python3.8/site-packages/docker/client.py", line 96, in from_env
    return cls(
  File "/Users/user/.virtualenvs/user/lib/python3.8/site-packages/docker/client.py", line 45, in __init__
    self.api = APIClient(*args, **kwargs)
  File "/Users/user/.virtualenvs/user/lib/python3.8/site-packages/docker/api/client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
  File "/Users/user/.virtualenvs/user/lib/python3.8/site-packages/docker/api/client.py", line 221, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
```

**Comment by harupy** [comment]
Are you sure docker is running on your system?

**Comment by harupy** [comment]
https://stackoverflow.com/questions/64952238/docker-errors-dockerexception-error-while-fetching-server-api-version seems related

**Comment by stobias123** [comment]
No that's what I said is the bug.
> When docker daemon is not running on OSX, mlflow run . with docker env returns a cryptic "file not found error".


I would expect this to be a simple pre-execution check. Instead I wait for quite some time, then get a cryptic error message as shown in stacktrace above. Took me a while to realize what was going on.

**Comment by harupy** [comment]
Sorry, I misunderstood. Filed #5853
