### ISSUE TITLE
[BUG] mlflow run: pip option "--index-url" not copied to the generated requirements.txt file

### ISSUE THREAD

**Issue by sebastien-genete** [mlflow/mlflow#5922]
### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### System information

- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 20.04
- **MLflow installed from (source or binary)**: pip install
- **MLflow version (run ``mlflow --version``)**: 1.26.0
- **Python version**: 3.7.12
- **yarn version, if running the dev UI**:

### Describe the problem

I run an exp with the command` mlflow run --env-manager virtualenv ...`
My conda.yaml:
```
name: my_engine
channels:
  - defaults
dependencies:
  - python>=3.7.12
  - pip
  - pip:
    - --index-url=https://private_repo:password@pypi.my_company.com
    - --trusted-host=https://pypi.my_company.com
    - mlflow>=1.26.0
    - -r requirements.txt    # with a private package my_private_package
```

The generated requirements.txt file doesn't contain the pip variable index-url

So the command 
`mlflow models build-docker -m "runs:/$(RUN_ID)/sklearn-model/" -n "my-image-name-venv" --env-manager virtualenv`
fails because the private package can be installed:

```
ERROR: Could not find a version that satisfies the requirement my_private_package==0.4.19 (from versions: none)
ERROR: No matching distribution found for my_private_package==0.4.19
WARNING: You are using pip version 22.0.4; however, version 22.1 is available.
You should consider upgrading via the '/root/.mlflow/envs/mlflow-85a9c7b0e8470d5d64c84665adeb824d36d7ac2d/bin/python -m pip install --upgrade pip' command.
2022/05/20 16:24:19 WARNING mlflow.utils.virtualenv: Encountered unexpected error while creating /root/.mlflow/envs/mlflow-85a9c7b0e8470d5d64c84665adeb824d36d7ac2d
2022/05/20 16:24:19 WARNING mlflow.utils.virtualenv: Attempting to remove /root/.mlflow/envs/mlflow-85a9c7b0e8470d5d64c84665adeb824d36d7ac2d
2022/05/20 16:24:19 WARNING mlflow.utils.virtualenv: Successfully removed /root/.mlflow/envs/mlflow-85a9c7b0e8470d5d64c84665adeb824d36d7ac2d
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/mlflow/models/container/__init__.py", line 120, in _install_pyfunc_deps
    env_activate_cmd = _get_or_create_virtualenv(model_path)
  File "/usr/local/lib/python3.7/dist-packages/mlflow/utils/virtualenv.py", line 291, in _get_or_create_virtualenv
    capture_output=capture_output,
  File "/usr/local/lib/python3.7/dist-packages/mlflow/utils/virtualenv.py", line 220, in _create_virtualenv
    _exec_cmd(cmd, capture_output=capture_output, cwd=local_model_path, extra_env=extra_env)
  File "/usr/local/lib/python3.7/dist-packages/mlflow/utils/process.py", line 94, in _exec_cmd
    raise ShellCommandException.from_completed_process(comp_process)
mlflow.utils.process.ShellCommandException: Non-zero exit code: 1
Command: ['bash', '-c', 'source /root/.mlflow/envs/mlflow-85a9c7b0e8470d5d64c84665adeb824d36d7ac2d/bin/activate && python -m pip install -r requirements.c96198dbd43d464db3766f241ec1a9b1.txt']
```

### Code to reproduce issue

see 

### Other info / logs

If I add the line `--index-url=https://private_repo:password@pypi.my_company.com` to the generated requirements.txt file (directly in the artifact folder),
the docker image is well built.

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [X] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by sebastien-genete** [comment]
@harupy Thank you ! It works now with conda_env=...

**Comment by harupy** [comment]
@sebastien-genete Thanks for the response, glad specifying `conda_env` solved the issue :)

**Comment by harupy** [comment]
> The recommended way is to define a k8s secret.

We currently don't support this.
