### ISSUE TITLE
[BUG] sqlite for backend store

### ISSUE THREAD

**Issue by sniafas** [mlflow/mlflow#5989]
### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

1.26

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 20.04
- **Python version**: 3.8
- **yarn version, if running the dev UI**:

### Describe the problem

Upgraded from 1.23, setting sqlite as backend store an sqlalchemy.future library error is produced.

A similar issue with this one
https://stackoverflow.com/questions/72341647/mlflow-modulenotfounderror-no-module-named-sqlalchemy-future/72432684#72432684

### Tracking information

mlflow server --backend-store-uri sqlite:///mlflow.sqlite  --default-artifact-root ./mlruns

### Code to reproduce issue

```
mlflow server --backend-store-uri sqlite:///mlflow.sqlite  --default-artifact-root ./mlruns
```

### Other info / logs

```
2022/05/30 13:18:36 ERROR mlflow.cli: Error initializing backend store
2022/05/30 13:18:36 ERROR mlflow.cli: No module named 'sqlalchemy.future'
Traceback (most recent call last):
lib/python3.8/site-packages/mlflow/store/tracking/sqlalchemy_store.py", line 11, in <module>
    from sqlalchemy.future import select
ModuleNotFoundError: No module named 'sqlalchemy.future'
```

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [X] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [X] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@sniafas What version of `sqlalchemy` are you using?

**Comment by harupy** [comment]
I was able to reproduce the same issue with this command:

```
docker run --rm python:3.7 bash -c "pip install 'sqlalchemy<1.4' && python -c 'from sqlalchemy.future import select'"
```

**Comment by sniafas** [comment]
Same 1.3.24. Do you think is a bug?

> @sniafas What version of `sqlalchemy` are you using?

**Comment by harupy** [comment]
@sniafas

> Do you think is a bug?

This looks like a bug to me. MLflow >= 1.24 uses `sqlalchemy.future.select` that sqlalchemy < 1.4 doesn't support.

**Comment by harupy** [comment]
https://github.com/mlflow/mlflow/pull/5382 added `from sqlalchemy.future import select`.

**Comment by harupy** [comment]
@sniafas One quick solution is to upgrade `sqlalchemy`.

**Comment by harupy** [comment]
Replaced `sqlalchemy.future.select` with `sqlalchemy.sql.expression` in #5990, but didn't work in `sqlalchemy<1.4.0`.

**Comment by harupy** [comment]
There are two options to resolve this issue:

1. Pin `sqlalchemy`.
2. Find a workaround.

**Comment by sniafas** [comment]
Tried with 1.4 and solved the issue? should I try i PR ?

**Comment by harupy** [comment]
The issue is [sqlalchemy 1.3.24](https://pypi.org/project/SQLAlchemy/1.3.24) is not that old (Released: Mar 31, 2021). We might need to keep mlflow compatible with it.

**Comment by harupy** [comment]
It'd be nice if we could find a workaround.

**Comment by harupy** [comment]
Hi @sniafas, we discussed this issue in the team and decided to drop SQLAlchemy 1.3. Would you be interested in filing a PR to pin a SQLAlchemy requirement in `setup.py`?

**Comment by sniafas** [comment]
Sure @harupy. Glad for asking! I ll give it a try, thanks!

**Comment by harupy** [comment]
@sniafas We can just make the following change:

```diff
diff --git a/setup.py b/setup.py
index adf20d1e6..8d73781b0 100644
--- a/setup.py
+++ b/setup.py
@@ -79,7 +79,7 @@ CORE_REQUIREMENTS = SKINNY_REQUIREMENTS + [
     # Pin sqlparse for: https://github.com/mlflow/mlflow/issues/3433
     "sqlparse>=0.3.1",
     # Required to run the MLflow server against SQL-backed storage
-    "sqlalchemy",
+    "sqlalchemy>=1.4.0",
     "waitress; platform_system == 'Windows'",
 ]
```
