### ISSUE TITLE
[FR] Search experiments and models by tags

### ISSUE THREAD

**Issue by MinuraPunchihewa** [mlflow/mlflow#6004]
### Willingness to contribute

Yes. I would be willing to contribute this feature with guidance from the MLflow community.

### Proposal Summary

I would like to be able to search experiments and models using the tags assigned to them. Through the Python API it is possible to use the `set_experiment_tag` and `set_registered_model_tag` respectively to assign tags to experiments and registered models respectively. Additionally, `set_model_version_tag` can be used to assign tags to specific versions of models. However, there is no means to search these experiments or models using the tags. The `search_model_versions`, `search_registered_models` and `get_experiment` functions do not support this yet. It would be great to have this functionality, similar to how runs can be searched using `search_runs`.

### Motivation

> #### What is the use case for this feature?
It is possible for a number of Data Scientists to be working on the same use case, but as separate experiments. I would like to be able to annotate these experiments and the resulting models using tags, and be able to search them later on. It will be useful to be able to say, find all of the experiments or models that related to a particular use case and make comparisons.

> #### Why is this use case valuable to support for MLflow users in general?
I believe that the scenario described above, of multiple Data Scientists working on the same use case individually, in an attempt to produce the best results, is pretty common among the community.

> #### Why is this use case valuable to support for your project(s) or organization?
As a Data Engineer, I have been tasked with developing an automated solution to search through the experiments and models, using tags, and make deployment to the various environments, again based on the tags assigned.

> #### Why is it currently difficult to achieve this use case?
The only workaround right now, to my knowledge, is to use listing functions like `list_experiments` or `list_registered_models`, loop through all of the elements until the matching tag(s) are found. It solves the problem, but is not very efficient.

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@MinuraPunchihewa 

> Search experiments by tags

We're going to add a capability to search experiments by tags soon.

> Search models by tags

Relates to #3296, but we don't have an immediate plan to update and merge this PR.

**Comment by MinuraPunchihewa** [comment]
@harupy Understood. Since these features are already planned for, I will proceed to close this issue.
