### ISSUE TITLE
[BUG] log_figure in plotly format without ".html" extension in artifact_file

### ISSUE THREAD

**Issue by drsantos89** [mlflow/mlflow#6039]
### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### MLflow version

1.25.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS
- **Python version**: 3.10

### Describe the problem

When logging a figure in plotly format, the file extension in the artifact_file needs to be ".html".
Otherwise, the file will be saved in HTML format anyway, but the file extension will be None or ".png" or other that the user specified in the path string. The file can't be opened on the MLFlow UI later.
The ".html" extension could be added to the end of the path if not there, or the method "write_image" could be used when the path finishes with PNG, JPEG, SVG or PDF.
Cheers,

### Code to reproduce issue

    import mlflow
    import plotly.express as px

    with mlflow.start_run():

        df = px.data.gapminder().query("country=='Canada'")
        fig = px.line(df, x="year", y="lifeExp", title='Life expectancy in Canada')
        mlflow.log_figure(fig, 'fig_test')

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [X] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by drsantos89** [comment]
@harupy 
Yes, that will work and maybe is more clear than just adding `.html`.
If we also want to support the `write_image` method (for png, jpeg, SVG, pdf).  We can have an if based on the artifact_file extensions and throw an error is not supported.

**Comment by harupy** [comment]
Would you be interested in creating a PR?

**Comment by drsantos89** [comment]
Yes, I will do it
