### ISSUE TITLE
[FR] [Roadmap] Add box plot with jittered points to run comparison UI

### ISSUE THREAD

**Issue by BenWilson2** [mlflow/mlflow#6074]
## MLflow Roadmap Item

This is an MLflow Roadmap item that has been prioritized by the MLflow maintainers. We’ve identified this feature as a highly requested addition to the MLflow package based on community feedback. 
We're seeking a community contribution for the implementation of this feature and will enthusiastically support the development and review of a submitted PR for this.

## Contribution Note

As with other roadmap items, there may be a desire for multiple contributors to work on an issue. While we don’t discourage collaboration, we strongly encourage that a primary contributor is assigned to roadmap issues to simplify the merging process. 
The items on the roadmap are of a high priority. Due to the wide-spread demand of roadmap features, we encourage potential contributors to only agree to take on the work of creating a PR, making changes, and ensuring that test coverage is adequately created for the feature if they are willing and able to see the implementation through to a merged state. 

## Feature scope

This roadmap feature’s complexity is classified as:

- [ ] `good-first-issue`: This feature is limited in complexity and effort required to implement.
- [ ] `simple`: This feature does not require a large amount of effort to implement and / or is clear enough to not need a design discussion with maintainers.
- [X] `involved`: This feature will require a substantial amount of development effort but does not require an agreed-upon design from the maintainers. The feedback given during the PR phase may be involved and necessitate multiple iterations before approval. (Please bear with us as we collaborate with you to make a great contribution)
- [ ] `design-recommended`: This is a substantial feature that should have a design document approved prior to working on an implementation (to save your time, not ours). After agreeing to work on this feature, a maintainer will be assigned to support you throughout the development process.

## Proposal Summary

Add a box plot with jittered points on the categorical group X-axis to the MLflow run comparison page.

For a visual reference, see this [FR](https://github.com/mlflow/mlflow/issues/6034), case #2. 

## Motivation
> #### What is the use case for this feature? 
  To more adequately visualize categorical comparisons between metrics and parameters. It is impossible to determine the distribution of points with the current visualization.
> #### Why is this use case valuable to support for MLflow users in general? 
  To aid in visually determining where the distribution locality is for points when points are overlapping.
> #### Why is this use case valuable to support for your project(s) or organization?
  This has been requested several times.
> #### Why is it currently difficult to achieve this use case? 
  It requires extracting the metrics and parameters from MLflow and plotting externally to visualize metric and parameter distributions.

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [X] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment]
For any questions, concerns, or clarification on implementing this issue, please ping @harupy

**Comment by harupy** [comment]
I think we should **add** a box plot instead of **replacing** the scatter plot (which I think is useful to plot continuous values).

**Comment by harupy** [comment]
Example implementation: https://github.com/harupy/mlflow/pull/44

**Comment by harupy** [comment]
Demo:

https://user-images.githubusercontent.com/17039389/177086575-60052db3-07c5-41d4-93f3-1858f1c9e283.mov

**Comment by harupy** [comment]
With jitter:

<img width="2377" alt="image" src="https://user-images.githubusercontent.com/17039389/177090518-1cb3a4d2-2f1f-4797-bc1f-593f8803f4b3.png">

**Comment by harupy** [comment]
cc @ahlag
