### ISSUE TITLE
[FR] [Roadmap] Support additional container build tool containerd

### ISSUE THREAD

**Issue by BenWilson2** [mlflow/mlflow#6076]
## MLflow Roadmap Item

This is an MLflow Roadmap item that has been prioritized by the MLflow maintainers. We’ve identified this feature as a highly requested addition to the MLflow package based on community feedback. 
We're seeking a community contribution for the implementation of this feature and will enthusiastically support the development and review of a submitted PR for this.

## Contribution Note

As with other roadmap items, there may be a desire for multiple contributors to work on an issue. While we don’t discourage collaboration, we strongly encourage that a primary contributor is assigned to roadmap issues to simplify the merging process. 
The items on the roadmap are of a high priority. Due to the wide-spread demand of roadmap features, we encourage potential contributors to only agree to take on the work of creating a PR, making changes, and ensuring that test coverage is adequately created for the feature if they are willing and able to see the implementation through to a merged state. 

## Feature scope

This roadmap feature’s complexity is classified as:

- [ ] `good-first-issue`: This feature is limited in complexity and effort required to implement.
- [X] `simple`: This feature does not require a large amount of effort to implement and / or is clear enough to not need a design discussion with maintainers.
- [ ] `involved`: This feature will require a substantial amount of development effort but does not require an agreed-upon design from the maintainers. The feedback given during the PR phase may be involved and necessitate multiple iterations before approval. (Please bear with us as we collaborate with you to make a great contribution)
- [ ] `design-recommended`: This is a substantial feature that should have a design document approved prior to working on an implementation (to save your time, not ours). After agreeing to work on this feature, a maintainer will be assigned to support you throughout the development process.

## Proposal Summary
Allow for a user-defined container build engine and tooling for model deployment. Currently, only Docker is supported to build a serving container. 
The addition of containerd, as linked in the FR issued below, is a good place to start to add additional container build support functionality for the scope of this FR.

See #5716 for context on original request.

## Motivation
> #### What is the use case for this feature? 
  Support building serving containers in containerd.
> #### Why is this use case valuable to support for MLflow users in general? 
  For organizations that choose not to use Docker Enterprise and prefer the OSS containerd approach.
> #### Why is it currently difficult to achieve this use case? 
  Building a serving container with a different containerization engine requires manual action and configuration.

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [X] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [X] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment]
For any questions, concerns, or clarification on implementing this issue, please ping @WeichenXu123

**Comment by anuarkaliyev23** [comment]
@BenWilson2 @WeichenXu123 
Hello, [PR 6591](https://github.com/mlflow/mlflow/pull/6591) have been recently merged into `master`
It allows to generate `dockerfile` as an additional option to building an image directly

From what I understand, `podman` and other alternatives can build images from `Dockerfile`, so it might be easier for users to use this feature for desired build? It will be easier to maintain, than to manually add different engines to the source code, in my opinion

Can this affect prioritization or approach selected for this FR?

**Comment by anuarkaliyev23** [comment]
Update: @dbczumar has recently closed issue #6084 since it is now possible to generate custom dockerfile
I think it is somewhat related to this issue, since it also regards build tools\docker
