### ISSUE TITLE
[FR] [Roadmap] Support NoSQL as tracking server backend

### ISSUE THREAD

**Issue by BenWilson2** [mlflow/mlflow#6077]
## MLflow Roadmap Item

This is an MLflow Roadmap item that has been prioritized by the MLflow maintainers. We’ve identified this feature as a highly requested addition to the MLflow package based on community feedback. 
We're seeking a community contribution for the implementation of this feature and will enthusiastically support the development and review of a submitted PR for this.

## Contribution Note

As with other roadmap items, there may be a desire for multiple contributors to work on an issue. While we don’t discourage collaboration, we strongly encourage that a primary contributor is assigned to roadmap issues to simplify the merging process. 
The items on the roadmap are of a high priority. Due to the wide-spread demand of roadmap features, we encourage potential contributors to only agree to take on the work of creating a PR, making changes, and ensuring that test coverage is adequately created for the feature if they are willing and able to see the implementation through to a merged state. 

## Feature scope

This roadmap feature’s complexity is classified as:

- [ ] `good-first-issue`: This feature is limited in complexity and effort required to implement.
- [ ] `simple`: This feature does not require a large amount of effort to implement and / or is clear enough to not need a design discussion with maintainers.
- [ ] `involved`: This feature will require a substantial amount of development effort but does not require an agreed-upon design from the maintainers. The feedback given during the PR phase may be involved and necessitate multiple iterations before approval. (Please bear with us as we collaborate with you to make a great contribution)
- [X] `design-recommended`: This is a substantial feature that should have a design document approved prior to working on an implementation (to save your time, not ours). After agreeing to work on this feature, a maintainer will be assigned to support you throughout the development process.

## Proposal Summary

In order to support larger scale deployments of MLflow, we would like to begin to design and implement support for using popular NoSQL engines as the tracking server backend.
This FR is a first step in a potentially larger design for the 2.0 release in which support for artifact co-location with tracking server data (metrics, tags, parameters) in a single NoSQL table entry *may be* considered. The first step in realizing this potential backend scalability improvement is building the interface to NoSQL engines. 

For this FR, support for using <either> CosmosDB or DynamoDB as the backing layer for the tracking server may be considered (supporting Azure or AWS), which will create a template for other NoSQL implementations. 

If possible, utilization of the existing SQLAlchemy ORM is highly preferred, but if incorporating that tooling into the NoSQL interface proves too complex, utilizing standard interface SDK libraries for the chosen engine is ok. 

Note: This implementation will likely be relatively involved and time-consuming to implement. As such, an RFC and a design review by maintainers is required for this implementation.

## Motivation
> #### What is the use case for this feature? 
  Scalability of the MLflow tracking server to support extremely large-scale usage patterns for users that are currently restricted on tracking server metrics, parameters, tags, and run counts.

> #### Why is this use case valuable to support for MLflow users in general? 
  Several users have brought this issue up and the required workarounds for not overwhelming the backing DB (writing bulk metrics and parameters as artifacts to avoid RDBMS limitations in table size).

> #### Why is it currently difficult to achieve this use case? ^

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [X] `area/docs`: MLflow documentation pages
- [X] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [X] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [X] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment]
For any questions, concerns, or clarification on implementing this issue, please ping either @dbczumar, @BenWilson2, @harupy, or @WeichenXu123

**Comment by gomrinal** [comment]
Hey! Can you add GCP into the examples as well like Big Table as a remote backend.
I think NoSQL as a backend would be highly important as it is scalable for massive number of request and most importantly where Data Scientist uses any algorithm which have varying hyperparameters so schema is changing based on algorithm selected. And using RDBMS restrict us in predicting the schema in advance.

**Comment by AdityaThakur1** [comment]
Hi,
I would like to contribute to the implementation of this road map. Is there anything that I could take up as my first  task.

**Comment by BenWilson2** [comment]
Hi @AdityaThakur1 the eventual end-goal for the over-arching theme with supporting NoSQL backends is a large one; for the purposes of this FR, we'd like to start small. The best place to get started is to pick (a) NoSQL backend that you're familiar with and draft up a design document that details your plans for implementation. Once created, please share with the maintainers (@dbczumar @harupy @WeichenXu123 @BenWilson2 ) and we will leave comments / questions on the design proposal. Once we get to a mutually agreed upon consensus, we'll work with you to define stages of implementation, change, and review. (This will likely be several PRs worth of work)
If you're up for it, please take a look at the implementation of the SQLAlchemy store implementation to get a feel for the scope of the work and to analyze what APIs will need to be implemented.

**Comment by cjtejasai** [comment]
hi @BenWilson2 , Even I wanted work on this feature . when you say document does MLFLOW as predefined template on how to create a design doc

**Comment by BenWilson2** [comment]
Hi @AdityaThakur1 and @cjtejasai Here is a link to our design template that you can use to get started: https://docs.google.com/document/d/1AQGgJk-hTkUo0lTkGqCGQOMelQmz05kQz_OA4bJWaJE/edit?usp=sharing 
Please create a copy of the template and post a link to your version of the doc when you're ready for us to take a look at it! 
Thanks again! :)

**Comment by kamalesh0406** [comment]
Hi @BenWilson2 is there any update on the status of this roadmap? I can start with the design doc if there are no takers yet.

**Comment by sayandigital** [comment]
@dbczumar, @BenWilson2, @harupy, or @WeichenXu123 I would like to contribute to the design.Please advise
