### ISSUE TITLE
[FR] [Roadmap] Generic MLflow model serving image

### ISSUE THREAD

**Issue by BenWilson2** [mlflow/mlflow#6078]
## MLflow Roadmap Item

This is an MLflow Roadmap item that has been prioritized by the MLflow maintainers. We’ve identified this feature as a highly requested addition to the MLflow package based on community feedback. 
We're seeking a community contribution for the implementation of this feature and will enthusiastically support the development and review of a submitted PR for this.

## Contribution Note

As with other roadmap items, there may be a desire for multiple contributors to work on an issue. While we don’t discourage collaboration, we strongly encourage that a primary contributor is assigned to roadmap issues to simplify the merging process. 
The items on the roadmap are of a high priority. Due to the wide-spread demand of roadmap features, we encourage potential contributors to only agree to take on the work of creating a PR, making changes, and ensuring that test coverage is adequately created for the feature if they are willing and able to see the implementation through to a merged state. 

## Feature scope

This roadmap feature’s complexity is classified as:

- [ ] `good-first-issue`: This feature is limited in complexity and effort required to implement.
- [X] `simple`: This feature does not require a large amount of effort to implement and / or is clear enough to not need a design discussion with maintainers.
- [ ] `involved`: This feature will require a substantial amount of development effort but does not require an agreed-upon design from the maintainers. The feedback given during the PR phase may be involved and necessitate multiple iterations before approval. (Please bear with us as we collaborate with you to make a great contribution)
- [ ] `design-recommended`: This is a substantial feature that should have a design document approved prior to working on an implementation (to save your time, not ours). After agreeing to work on this feature, a maintainer will be assigned to support you throughout the development process.

## Proposal Summary

Add the ability to generate an MLflow model serving image (i.e., `mlflow models build-image`) without the need to specify a `model_uri` in order to generate a generic serving image. 

## Motivation
> #### What is the use case for this feature? 
  To simplify and aid in supporting custom container definitions that can be used for both experimentation and production without requiring a specific model instance to be used to construct the container.
> #### Why is this use case valuable to support for MLflow users in general? 
  This helps to simplify the usage of containers for model serving by minimizing complexity in the dev loop.
> #### Why is it currently difficult to achieve this use case? 
  Currently a specific model artifact needs to be used to build a container which increases the complexity of development and testing.

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [X] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by subramaniam02** [comment]
@BenWilson2 @WeichenXu123 I am interested in FR. What will be the workflow look like after support of generic model serving.

mlflow user:
1. run `mlflow models build-image`
2. Create `dockerfile`
2.1 use image from above step
2.2 Copy model
3. `docker run`

I would like to add my opinion that https://github.com/mlflow/mlflow/issues/6084 will be efficient long term solution. But I agree this is good to have.

**Comment by dbczumar** [comment]
This has been addressed by @harupy via https://github.com/mlflow/mlflow/pull/6302. https://github.com/mlflow/mlflow/issues/6084 remains open for docker layer customization. Thanks @harupy !
