### ISSUE TITLE
[FR] [Roadmap] Alias client at top-level

### ISSUE THREAD

**Issue by BenWilson2** [mlflow/mlflow#6080]
## MLflow Roadmap Item

This is an MLflow Roadmap item that has been prioritized by the MLflow maintainers. We’ve identified this feature as a highly requested addition to the MLflow package based on community feedback. 
We're seeking a community contribution for the implementation of this feature and will enthusiastically support the development and review of a submitted PR for this.

## Contribution Note

As with other roadmap items, there may be a desire for multiple contributors to work on an issue. While we don’t discourage collaboration, we strongly encourage that a primary contributor is assigned to roadmap issues to simplify the merging process. 
The items on the roadmap are of a high priority. Due to the wide-spread demand of roadmap features, we encourage potential contributors to only agree to take on the work of creating a PR, making changes, and ensuring that test coverage is adequately created for the feature if they are willing and able to see the implementation through to a merged state. 

## Feature scope

This roadmap feature’s complexity is classified as:

- [X] `good-first-issue`: This feature is limited in complexity and effort required to implement.
- [ ] `simple`: This feature does not require a large amount of effort to implement and / or is clear enough to not need a design discussion with maintainers.
- [ ] `involved`: This feature will require a substantial amount of development effort but does not require an agreed-upon design from the maintainers. The feedback given during the PR phase may be involved and necessitate multiple iterations before approval. (Please bear with us as we collaborate with you to make a great contribution)
- [ ] `design-recommended`: This is a substantial feature that should have a design document approved prior to working on an implementation (to save your time, not ours). After agreeing to work on this feature, a maintainer will be assigned to support you throughout the development process.

## Proposal Summary

Create an alias at the top package level for `mlflow.tracking.MlflowClient()` to more accurately reflect its common usage and to simplify import and caller statements. 
The client constructor should be referable from: `mlflow.MlflowClient()`.

Note: this is simply adding an alias, not changing the package classpath to move the client constructor.

## Motivation
> #### What is the use case for this feature? 
  Simplify the user experience.
> #### Why is this use case valuable to support for MLflow users in general? 
  Everyone (*citation needed) appreciates typing less.
> #### Why is it currently difficult to achieve this use case? 
  N/A

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by subramaniam02** [comment]
@BenWilson2 I am willing to contribute.

**Comment by BenWilson2** [comment]
@subramaniam02 awesome! Thanks for taking this! 
Please perform a search within MLflow after creating the alias and replace all in-code references to the alias (including tests) and let me know if you have any questions while working on the PR!

**Comment by subramaniam02** [comment]
@BenWilson2 I am thinking of creating 2 PRs. One for code changes (tests, mlflow package), other for examples and docs. What do you think ? I am yet to run tests and verify. In next 1-2 days PR will be ready for review. Thanks

**Comment by BenWilson2** [comment]
Sounds great! Let me know if you get stuck with the docs portion. Sphinx can be a little finicky to interpret from the local cli command.
