### ISSUE TITLE
[FR] [Roadmap] Change log scale on UI charts to show official scientific notation

### ISSUE THREAD

**Issue by BenWilson2** [mlflow/mlflow#6081]
## MLflow Roadmap Item

This is an MLflow Roadmap item that has been prioritized by the MLflow maintainers. We’ve identified this feature as a highly requested addition to the MLflow package based on community feedback. 
We're seeking a community contribution for the implementation of this feature and will enthusiastically support the development and review of a submitted PR for this.

## Contribution Note

As with other roadmap items, there may be a desire for multiple contributors to work on an issue. While we don’t discourage collaboration, we strongly encourage that a primary contributor is assigned to roadmap issues to simplify the merging process. 
The items on the roadmap are of a high priority. Due to the wide-spread demand of roadmap features, we encourage potential contributors to only agree to take on the work of creating a PR, making changes, and ensuring that test coverage is adequately created for the feature if they are willing and able to see the implementation through to a merged state. 

## Feature scope

This roadmap feature’s complexity is classified as:

- [ ] `good-first-issue`: This feature is limited in complexity and effort required to implement.
- [X] `simple`: This feature does not require a large amount of effort to implement and / or is clear enough to not need a design discussion with maintainers.
- [ ] `involved`: This feature will require a substantial amount of development effort but does not require an agreed-upon design from the maintainers. The feedback given during the PR phase may be involved and necessitate multiple iterations before approval. (Please bear with us as we collaborate with you to make a great contribution)
- [ ] `design-recommended`: This is a substantial feature that should have a design document approved prior to working on an implementation (to save your time, not ours). After agreeing to work on this feature, a maintainer will be assigned to support you throughout the development process.

## Proposal Summary

The selection of log scale chart rendering in the run comparison page generates non-standard scientific notation to show the scale values along the y-axis. 
This FR proposes changing the display values to show in `standard scientific e-notation`. 
For example:
1.05e-5
1.5e4

## Motivation
> #### What is the use case for this feature? 
  Legibility and standardization. 
> #### Why is this use case valuable to support for MLflow users in general? 
  People are confused by what is there right now. This change is more in harmony with industry standards.
> #### Why is it currently difficult to achieve this use case? 
  N/A

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [X] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
Script to generate sample data

```python
import mlflow


with mlflow.start_run():
    for i in range(10):
        mlflow.log_metrics({"m": 10 ** (-i)}, step=i)
```

**Comment by harupy** [comment]
Hints:

```python
diff --git a/mlflow/server/js/src/experiment-tracking/components/MetricsPlotPanel.js b/mlflow/server/js/src/experiment-tracking/components/MetricsPlotPanel.js
index 5de9fcf90..8dccb3f15 100644
--- a/mlflow/server/js/src/experiment-tracking/components/MetricsPlotPanel.js
+++ b/mlflow/server/js/src/experiment-tracking/components/MetricsPlotPanel.js
@@ -283,7 +283,7 @@ export class MetricsPlotPanel extends React.Component {
     if (!yAxisLogScale && state.lastLinearYAxisRange && state.lastLinearYAxisRange.length > 0) {
       newLayout.yaxis = {
         type: 'linear',
-        range: state.lastLinearYAxisRange,
+        range: state.lastLinearYAaxisRange,
       };
       this.updateUrlState({ layout: newLayout, lastLinearYAxisRange: [] });
       return;
@@ -292,7 +292,7 @@ export class MetricsPlotPanel extends React.Component {
     // Otherwise, if plot previously had no y axis range configured, simply set the axis type to
     // log or linear scale appropriately
     if (!state.layout.yaxis || !state.layout.yaxis.range) {
-      newLayout.yaxis = { type: newAxisType, autorange: true };
+      newLayout.yaxis = { type: newAxisType, autorange: true, exponentformat: 'e' };
       this.updateUrlState({ layout: newLayout, lastLinearYAxisRange: [] });
       return;
     }
@@ -321,11 +321,13 @@ export class MetricsPlotPanel extends React.Component {
         newLayout.yaxis = {
           type: 'log',
           autorange: true,
+          exponentformat: 'e',
         };
       } else {
         newLayout.yaxis = {
           type: 'log',
           range: [Math.log(oldYRange[0]) / Math.log(10), Math.log(oldYRange[1]) / Math.log(10)],
+          exponentformat: 'e',
         };
       }
     } else {
```


Ref: https://plotly.com/python/reference/#carpet-baxis-exponentformat

**Comment by harupy** [comment]
<img width="1523" alt="image" src="https://user-images.githubusercontent.com/17039389/176652835-622fa572-5f03-4192-b740-0c391366583f.png">

**Comment by RajezMariner** [comment]
I am interested in taking up this roadmap and work on it.

**Comment by harupy** [comment]
@RajezMariner Thanks for the help! Looking forward to your PR :)
