### ISSUE TITLE
[FR] [Roadmap] Display tags in runs comparison table within the UI

### ISSUE THREAD

**Issue by BenWilson2** [mlflow/mlflow#6082]
## MLflow Roadmap Item

This is an MLflow Roadmap item that has been prioritized by the MLflow maintainers. We’ve identified this feature as a highly requested addition to the MLflow package based on community feedback. 
We're seeking a community contribution for the implementation of this feature and will enthusiastically support the development and review of a submitted PR for this.

## Contribution Note

As with other roadmap items, there may be a desire for multiple contributors to work on an issue. While we don’t discourage collaboration, we strongly encourage that a primary contributor is assigned to roadmap issues to simplify the merging process. 
The items on the roadmap are of a high priority. Due to the wide-spread demand of roadmap features, we encourage potential contributors to only agree to take on the work of creating a PR, making changes, and ensuring that test coverage is adequately created for the feature if they are willing and able to see the implementation through to a merged state. 

## Feature scope

This roadmap feature’s complexity is classified as:

- [ ] `good-first-issue`: This feature is limited in complexity and effort required to implement.
- [X] `simple`: This feature does not require a large amount of effort to implement and / or is clear enough to not need a design discussion with maintainers.
- [ ] `involved`: This feature will require a substantial amount of development effort but does not require an agreed-upon design from the maintainers. The feedback given during the PR phase may be involved and necessitate multiple iterations before approval. (Please bear with us as we collaborate with you to make a great contribution)
- [ ] `design-recommended`: This is a substantial feature that should have a design document approved prior to working on an implementation (to save your time, not ours). After agreeing to work on this feature, a maintainer will be assigned to support you throughout the development process.

## Proposal Summary

In the runs comparison table within the UI, display tags associated with runs.
The data for tags is already fetched from the query that retrieves parameters and metrics [here] (https://github.com/mlflow/mlflow/blob/ead653faf44eb7ee870a18d08bb8f864e37a2deb/mlflow/server/js/src/model-registry/components/CompareModelVersionsView.js#L655-L699). The tags stored in `const runTags` should be added to the table display.

Original request: #4807 

## Motivation
> #### What is the use case for this feature? 
  Allow the use case where users are storing critical data for comparison in tags associated with runs so that they do not have to perform additional actions in looking up tag values externally from the run comparison table.
> #### Why is this use case valuable to support for MLflow users in general? 
  To save on the number of actions that an end-user needs to take to evaluate models within the run comparison page.

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [X] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment]
For any questions, concerns, or clarification on implementing this issue, please ping @harupy

**Comment by CaioCavalcanti** [comment]
I would like to help with this.

**Comment by CaioCavalcanti** [comment]
@harupy can you give me a hand?

- Can I add the table at the end after metrics or should it be somewhere else?
- Should system tags be included?
- Including the existing `runTags` would look something like this, is this enough?
![image](https://user-images.githubusercontent.com/3620566/176320203-9733de37-509b-47e4-9bcd-fab8379987b0.png)

**Comment by jeremyjordan** [comment]
I can add some input from a user perspective (I also was the one who originally filed the feature request #4807)

> Can I add the table at the end after metrics or should it be somewhere else?

Yes, this seems like a reasonable place to add the table to me.

> Should system tags be included?

I would prefer a toggle, off by default, that allows you to show system tags. The reason for this is that I know some teams will take advantage of the fact that `mlflow.*` tags are hidden to keep track of some additional information without burdening the end user. It can be nice (but not critical) to have the option to be able to see that information.

**Comment by harupy** [comment]
@CaioCavalcanti Thanks for the help! 

> Can I add the table at the end after metrics or should it be somewhere else?

Yes, this sounds good to me.

@jeremyjordan 

> I would prefer a toggle, off by default, that allows you to show system tags. The reason for this is that I know some teams will take advantage of the fact that mlflow.* tags are hidden to keep track of some additional information without burdening the end user. It can be nice (but not critical) to have the option to be able to see that information.

Thanks for the input. Yeah, makes sense to me to add a toggle for MLflow system tags.
