### ISSUE TITLE
[FR] [Roadmap] Support color palette for MLflow plots to support users with color differentiation struggles

### ISSUE THREAD

**Issue by BenWilson2** [mlflow/mlflow#6087]
## MLflow Roadmap Item

This is an MLflow Roadmap item that has been prioritized by the MLflow maintainers. We’ve identified this feature as a highly requested addition to the MLflow package based on community feedback. 
We're seeking a community contribution for the implementation of this feature and will enthusiastically support the development and review of a submitted PR for this.

## Contribution Note

As with other roadmap items, there may be a desire for multiple contributors to work on an issue. While we don’t discourage collaboration, we strongly encourage that a primary contributor is assigned to roadmap issues to simplify the merging process. 
The items on the roadmap are of a high priority. Due to the wide-spread demand of roadmap features, we encourage potential contributors to only agree to take on the work of creating a PR, making changes, and ensuring that test coverage is adequately created for the feature if they are willing and able to see the implementation through to a merged state. 

## Feature scope

This roadmap feature’s complexity is classified as:

- [ ] `good-first-issue`: This feature is limited in complexity and effort required to implement.
- [X] `simple`: This feature does not require a large amount of effort to implement and / or is clear enough to not need a design discussion with maintainers.
- [ ] `involved`: This feature will require a substantial amount of development effort but does not require an agreed-upon design from the maintainers. The feedback given during the PR phase may be involved and necessitate multiple iterations before approval. (Please bear with us as we collaborate with you to make a great contribution)
- [ ] `design-recommended`: This is a substantial feature that should have a design document approved prior to working on an implementation (to save your time, not ours). After agreeing to work on this feature, a maintainer will be assigned to support you throughout the development process.

## Proposal Summary

As per #4186 set the color palette for in-UI generated plots such that the color space is universally visible. 
See references [here](https://jfly.uni-koeln.de/color/) for a candidate palette for grouped line, scatter, and contour plots.

## Motivation
> #### What is the use case for this feature? 
With the current color palette in MLflow generated charts, it is impossible for protanope, deteranope, and tritanope users to differentiate visual cues in differences in these plots. Switching to a universal color scheme palette will help them utilize Mlflow more effectively.

> #### Why is this use case valuable to support for MLflow users in general? ^

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [X] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment]
For any questions, concerns, or clarification on implementing this issue, please ping @harupy

**Comment by harupy** [comment]
Prototype:

https://user-images.githubusercontent.com/17039389/177224848-435d7e46-d135-47f7-9cd7-2a9760622286.mov

**Comment by harupy** [comment]
### Prototype 2

https://user-images.githubusercontent.com/17039389/177296758-a85c79ea-c75b-48ae-a3ad-ca76814ce813.mov

**Comment by harupy** [comment]
cc @pomelyu

**Comment by pomelyu** [comment]
> @pomelyu Any thoughts on this?

It looks great! I never thought of using the color palette. That's better than what I proposed. Thanks

**Comment by harupy** [comment]
@pomelyu Thanks for the reply! Would different symbols (e.g. circle, star, triangle, etc.) be also helpful?

<img width="956" alt="image" src="https://user-images.githubusercontent.com/17039389/177349967-a1c75756-9d2e-4dbb-af79-8f49e9c69b37.png">

**Comment by pomelyu** [comment]
> @pomelyu Thanks for the reply! Would different symbols (e.g. circle, star, triangle, etc.) be also helpful?
Sure

**Comment by bafonso** [comment]
Related to this, how does mlflow decide the current color scheme? I'm getting completely overlapping colors :( 

![image](https://github.com/mlflow/mlflow/assets/777910/ddb9f2fd-d2e6-451a-8ca3-00cf248b2007)
