### ISSUE TITLE
[FR] Can log_metrics log a pandas.DataFrame?

### ISSUE THREAD

**Issue by Jingnan-Jia** [mlflow/mlflow#6091]
### Willingness to contribute

No. I cannot contribute this feature at this time.

### Proposal Summary

Sometimes I have already got a table from 3rd package and I want to log the table to mlflow.

### Motivation

For instance, I can get a numpy arry or pandas.DataFrame to respresent the GPU or CPU usage every 2 seconds from a sub-threading during the model's training. And I do not want to use for loop to log the table because it is very slow. Is it possible to log a series of data into mlflow in one time?  

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [X] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment]
While there is no support for pandas_df directly, you can quite easily do one of two things:

1. Use the [client API](https://mlflow.org/docs/latest/python_api/mlflow.tracking.html#mlflow.tracking.MlflowClient.log_batch)
``` python
metrics_df = <pd.DataFrame>
client = mlflow.tracking.MlflowClient()
client.log_batch(run_id=<run_id>, metrics=metrics_df.to_dict(orient='dict'))
```
2.  Use the [fluent API](https://mlflow.org/docs/latest/python_api/mlflow.html#mlflow.log_metrics)
```python
with mlflow.start_run():

  metrics_df = <pd.DataFrame>
  mlflow.log_metrics(metrics_df.to_dict(orient='dict'), [optional]step=<int>)
```

**Comment by BenWilson2** [comment]
Closing this as the feature already exists.
