### ISSUE TITLE
[FR] [Roadmap] Add utility for signature validation of logged model to dataset

### ISSUE THREAD

**Issue by BenWilson2** [mlflow/mlflow#6092]
## MLflow Roadmap Item

This is an MLflow Roadmap item that has been prioritized by the MLflow maintainers. We’ve identified this feature as a highly requested addition to the MLflow package based on community feedback. 
We're seeking a community contribution for the implementation of this feature and will enthusiastically support the development and review of a submitted PR for this.

## Contribution Note

As with other roadmap items, there may be a desire for multiple contributors to work on an issue. While we don’t discourage collaboration, we strongly encourage that a primary contributor is assigned to roadmap issues to simplify the merging process. 
The items on the roadmap are of a high priority. Due to the wide-spread demand of roadmap features, we encourage potential contributors to only agree to take on the work of creating a PR, making changes, and ensuring that test coverage is adequately created for the feature if they are willing and able to see the implementation through to a merged state. 

## Feature scope

This roadmap feature’s complexity is classified as:

- [ ] `good-first-issue`: This feature is limited in complexity and effort required to implement.
- [ ] `simple`: This feature does not require a large amount of effort to implement and / or is clear enough to not need a design discussion with maintainers.
- [X] `involved`: This feature will require a substantial amount of development effort but does not require an agreed-upon design from the maintainers. The feedback given during the PR phase may be involved and necessitate multiple iterations before approval. (Please bear with us as we collaborate with you to make a great contribution)
- [ ] `design-recommended`: This is a substantial feature that should have a design document approved prior to working on an implementation (to save your time, not ours). After agreeing to work on this feature, a maintainer will be assigned to support you throughout the development process.

## Proposal Summary

This FR proposes the creation of a validation utility function that will:
- Validate a sample of a prediction dataset to ensure that its schema matches that (is a superset) of a logged model artifact's signature*
- Raise an MLflowException with a detailed human-readable message that explains the set difference between the supplied schema's required fields and that of the signature input schema*
- Perform a prediction of the provided sample data and ensure that the output schema matches the signature's outputs.
- Provide an [optional] expectation criterion to elicit a warning if any predicted values are beyond argument-provided thresholds
  - allow for passing a set of expected values for classification models
  - allow for a range passed as a tuple of (min, max) for regression models
  - return a namedtuple representation of the expectation validation check akin to (<full prediction>, <failed expectation rows>)

Original FR inspiration: #5144

## Motivation
> #### What is the use case for this feature? 
  To simplify pre-deployment validation tasks and aid in debugging of models in production. Expectation allows for validation steps to be performed during experimentation to provide a time-saving tool to validate a trained model meets business requirements.

> #### Why is this use case valuable to support for MLflow users in general? 
  It eliminates complexity in common tasks that currently require accessing internal APIs that are subject to change.

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment]
For any questions, concerns, or clarification on implementing this issue, please ping @dbczumar

**Comment by WeichenXu123** [comment]
@serena-ruan volunteers to do this task, assign it to her. :)

**Comment by dbczumar** [comment]
Thanks @serena-ruan, looking forward to your contribution!

**Comment by serena-ruan** [comment]
@dbczumar May I ask a few questions to clarify the problem a bit? 
From the initial issue and description, I feel like that we can directly wrap over mlflow.pyfunc's methods into the utility function to make validation of data schemas work for all flavors, and `predict` just comes for free. The only difference is that _enforce_schema has certain limits on the data type, and prediction results may fall out of that range. So I have this simple draft of outline:
<img width="876" alt="image" src="https://user-images.githubusercontent.com/82044803/184654295-4324c05f-4db2-4bcc-8b3f-3963fd109bc3.png">

Please feel free to correct me if I'm wrong :D

**Comment by dbczumar** [comment]
Hi @serena-ruan! Thank you for clarifying.

- I think that exposing an `mlflow.models.validate_schema()` method with the same arguments from your `SchemaUtils.validate_schema` method is a great idea.

- Right now, `mlflow.pyfunc.predict()` already performs schema validation, so `model.predict(data)` will already fail if `data` does not match the model's schema. Accordingly, I don't think we need `predict_and_validate_schema`.

- Finally, it would be nice to make it easier for users to fetch the signature of the model using the URI. For this, I think we can introduce an `mlflow.models.get_model_info()` method that returns a https://mlflow.org/docs/latest/python_api/mlflow.models.html#mlflow.models.model.ModelInfo object corresponding to the model.

Let me know if this helps, and apologies for the slight ambiguity in the issue description.

**Comment by serena-ruan** [comment]
Hi @dbczumar thanks for the clarification!
1. This sounds good, I'll add the method into mlflow/models/model.py, so that users can directly call mlflow.models.validate_schema().
2. I think `mlflow.pyfunc.predict` only does the input data schema check with `_enforce_schema`, it doesn't validate the output schema of predict. As for the third bullet in the above proposal `Perform a prediction of the provided sample data and ensure that the output schema matches the signature's outputs.` do we want to validate the output schema as well?
3. There's already a method of `get_model_info` https://github.com/mlflow/mlflow/blob/master/mlflow/models/model.py#:~:text=def%20get_model_info(self)%3A
When user uses `mlflow.xxx.log_model` it returns `Model.log(xxx)`, which internally calls this `get_model_info` method, so the return value of log_model is exactly the ModelInfo object. I'll check if there're any exceptions for different flavors. And if we want to expose another API that user can directly retrieve ModelInfo from url, then we canadd the API of `get_model_info(model_uri)` as well. We can discuss more in the follow-up PR :)

**Comment by dbczumar** [comment]
> Hi @dbczumar thanks for the clarification!
> 
> 1. This sounds good, I'll add the method into mlflow/models/model.py, so that users can directly call mlflow.models.validate_schema().
> 2. I think `mlflow.pyfunc.predict` only does the input data schema check with `_enforce_schema`, it doesn't validate the output schema of predict. As for the third bullet in the above proposal `Perform a prediction of the provided sample data and ensure that the output schema matches the signature's outputs.` do we want to validate the output schema as well?
> 3. There's already a method of `get_model_info` https://github.com/mlflow/mlflow/blob/master/mlflow/models/model.py#:~:text=def%20get_model_info(self)%3A
>    When user uses `mlflow.xxx.log_model` it returns `Model.log(xxx)`, which internally calls this `get_model_info` method, so the return value of log_model is exactly the ModelInfo object. I'll check if there're any exceptions for different flavors. And if we want to expose another API that user can directly retrieve ModelInfo from url, then we can add the API of `get_model_info(model_uri)` as well. We can discuss more in the follow-up PR :)

1. Awesome! :)

2. I don't think we want to validate the output schema of predictions produced by the model, since we can trust that the model produces outputs according to its schema. In contrast, we cannot trust that an arbitrary input complies with the model's schema, which is why a separate utility for validating a dataset against a schema is really helpful.

3. `Model.get_model_info()` requires the model to be loaded in the current Python environment. Users may not want to download and restore the model in order to read its signature, e.g. if the model has a lot of dependencies. I think that `mlflow.models.get_model_info()` will be helpful.
