### ISSUE TITLE
[FR] [Roadmap] Generate and publish official Docker image for MLflow model server

### ISSUE THREAD

**Issue by BenWilson2** [mlflow/mlflow#6094]
## MLflow Roadmap Item

This is an MLflow Roadmap item that has been prioritized by the MLflow maintainers. We’ve identified this feature as a highly requested addition to the MLflow package based on community feedback. 
We're seeking a community contribution for the implementation of this feature and will enthusiastically support the development and review of a submitted PR for this.

## Contribution Note

As with other roadmap items, there may be a desire for multiple contributors to work on an issue. While we don’t discourage collaboration, we strongly encourage that a primary contributor is assigned to roadmap issues to simplify the merging process. 
The items on the roadmap are of a high priority. Due to the wide-spread demand of roadmap features, we encourage potential contributors to only agree to take on the work of creating a PR, making changes, and ensuring that test coverage is adequately created for the feature if they are willing and able to see the implementation through to a merged state. 

## Feature scope

This roadmap feature’s complexity is classified as:

- [ ] `good-first-issue`: This feature is limited in complexity and effort required to implement.
- [ ] `simple`: This feature does not require a large amount of effort to implement and / or is clear enough to not need a design discussion with maintainers.
- [X] `involved`: This feature will require a substantial amount of development effort but does not require an agreed-upon design from the maintainers. The feedback given during the PR phase may be involved and necessitate multiple iterations before approval. (Please bear with us as we collaborate with you to make a great contribution)
- [ ] `design-recommended`: This is a substantial feature that should have a design document approved prior to working on an implementation (to save your time, not ours). After agreeing to work on this feature, a maintainer will be assigned to support you throughout the development process.

## Proposal Summary

Generate container images for MLflow's model server and configure for publishing during release.

Note: The CD portion of this will be done by MLflow maintainers.

## Motivation
> #### What is the use case for this feature? 
   Simplify the process of creating a model server.

> #### Why is this use case valuable to support for MLflow users in general? 
  It has been requested many times and it seems incredibly valuable to MLOps engineers.

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [X] `area/build`: Build and test infrastructure for MLflow
- [X] `area/docs`: MLflow documentation pages
- [X] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [X] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by rafaelvp-db** [comment]
@dbczumar happy to help with this one

**Comment by dbczumar** [comment]
Hey @rafaelvp-db , apologies for the delay here. Are you still interested in helping with this?

**Comment by jonnor** [comment]
Glad to see this one up there. I think it will be important to decide

1) Which storage backend configurations such should use. Both for the database and the artifacts store. Many permutations here
2) What authentication scheme(s) to support. 
3) How to run the HTTP server. Eg, should it have a frontend like nxginx/Apache/etc. This may interact with 2), if authentication is done there 

1) requires external services, either self-hosted or externally hosted / managed. If using managed, the options vary based on cloud provider. So that will influence quite a bit how easy it is to get things running on a given host, in practice.

Here is one option that supports Postgres/GoogleCloudStorage/Heroku. https://github.com/soundsensing/mlflow-easyauth 
And there are many other such smaller projects for different options, for example https://github.com/Toumash/mlflow-docker for MySQL/minio
