### ISSUE TITLE
[FR] [Roadmap] Add infrastructure examples

### ISSUE THREAD

**Issue by BenWilson2** [mlflow/mlflow#6097]
## MLflow Roadmap Item

This is an MLflow Roadmap item that has been prioritized by the MLflow maintainers. We’ve identified this feature as a highly requested addition to the MLflow package based on community feedback. 
We're seeking a community contribution for the implementation of this feature and will enthusiastically support the development and review of a submitted PR for this.

## Contribution Note

As with other roadmap items, there may be a desire for multiple contributors to work on an issue. While we don’t discourage collaboration, we strongly encourage that a primary contributor is assigned to roadmap issues to simplify the merging process. 
The items on the roadmap are of a high priority. Due to the wide-spread demand of roadmap features, we encourage potential contributors to only agree to take on the work of creating a PR, making changes, and ensuring that test coverage is adequately created for the feature if they are willing and able to see the implementation through to a merged state. 

## Feature scope

This roadmap feature’s complexity is classified as:

- [X] `good-first-issue`: This feature is limited in complexity and effort required to implement.
- [ ] `simple`: This feature does not require a large amount of effort to implement and / or is clear enough to not need a design discussion with maintainers.
- [ ] `involved`: This feature will require a substantial amount of development effort but does not require an agreed-upon design from the maintainers. The feedback given during the PR phase may be involved and necessitate multiple iterations before approval. (Please bear with us as we collaborate with you to make a great contribution)
- [ ] `design-recommended`: This is a substantial feature that should have a design document approved prior to working on an implementation (to save your time, not ours). After agreeing to work on this feature, a maintainer will be assigned to support you throughout the development process.

## Proposal Summary

This is a 'meta FR' that is intended to track several implementation PRs (one for each item). Please do not file a single PR with all of these changes. In order to work on one of these items, please request assignment to one (or several) and maintainers will assign it to you so that there isn't duplicated work by others.

Each element in here should have two contributions associated with a PR for it:
1. A documented script, with README, and any required files that illustrate and create a reproducible example concept in a folder within [examples](https://github.com/mlflow/mlflow/tree/master/examples) that is structured by example content type similar to `mlflow/examples/mlflow_artifacts/`
2. Accompanying updates to the official documentation with a linked page that provides a 'walkthrough guide' that explains how to accomplish the task with accompanying example code that shows modifications and usage of the provided example.

The infrastructure examples that need to be built are:
- End to end tracking server configuration for MLflow with SQLite [scenario 2](https://mlflow.org/docs/latest/tracking.html#scenario-2-mlflow-on-localhost-with-sqlite). 
- End to end tracking server configuration for MLflow on localhost with Tracking Server [scenario 3](https://mlflow.org/docs/latest/tracking.html#scenario-3-mlflow-on-localhost-with-tracking-server)
- End to end tracking server configuration for MLflow Tracking Server used exclusively as proxied access host for artifact storage access [scenario 6](https://mlflow.org/docs/latest/tracking.html#scenario-6-mlflow-tracking-server-used-exclusively-as-proxied-access-host-for-artifact-storage-access)
- A full example of using child runs to track a hyperparameter optimization run (logging to scenario 2 above) using either hyperopt or optuna (preferred)
- A full example of setting up a tracking server with nginx and basic http authentication with `.htaccess` (using env vars `MLFLOW_TRACKING_USERNAME` and `MLFLOW_TRACKING_PASSWORD`)

These examples should include 'real-world-like' usage patterns of creating multiple experiments, multiple runs per experiment, using nested child runs, setting tags (on experiments and runs), populating descriptions, logging artifacts (as well as metrics and parameters). Showing the use of autologging and the model `evaluate` API are highly encouraged.

## Motivation
> #### What is the use case for this feature? 
  To support new users and help to simplify the developer experience with well-documented guides on how to use MLflow.

> #### Why is this use case valuable to support for MLflow users in general? ^

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [X] `area/docs`: MLflow documentation pages
- [X] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment]
For any questions, concerns, or clarification on implementing this issue, please ping @BenWilson2

**Comment by dsgibbons** [comment]
> End to end tracking server configuration for MLflow with SQLite [scenario 2](https://mlflow.org/docs/latest/tracking.html#scenario-2-mlflow-on-localhost-with-sqlite).

Could I please work on this item?

**Comment by dsgibbons** [comment]
I've started working on scenario 2 @BenWilson2. I'll probably also work on scenario 6 too as there is a lot of overlap there.

**Comment by attilaszuts** [comment]
@BenWilson2 can you assign me to this issue? I'm going to start working on this task:

> End to end tracking server configuration for MLflow on localhost with Tracking Server [scenario 3](https://mlflow.org/docs/latest/tracking.html#scenario-3-mlflow-on-localhost-with-tracking-server)

**Comment by dsgibbons** [comment]
I can no longer work on this item. Please feel free to assign this to someone else @BenWilson2.

**Comment by Apurro12** [comment]
Hi @BenWilson2, could I work please in?

**End to end tracking server configuration for MLflow with SQLite [scenario 2](https://mlflow.org/docs/latest/tracking.html#scenario-2-mlflow-on-localhost-with-sqlite).**

**Comment by BenWilson2** [comment]
> Hi @BenWilson2, could I work please in?
> 
> **End to end tracking server configuration for MLflow with SQLite [scenario 2](https://mlflow.org/docs/latest/tracking.html#scenario-2-mlflow-on-localhost-with-sqlite).**

It's all yours!

**Comment by Rusteam** [comment]
@BenWilson2  I can help out with:
- [Scenario 3: MLflow on localhost with Tracking Server](https://mlflow.org/docs/latest/tracking.html#id34)

**Comment by BenWilson2** [comment]
@Rusteam Sure thing! Please ping me when you file your PR :) Thank you for volunteering!

**Comment by Rusteam** [comment]
> @Rusteam Sure thing! Please ping me when you file your PR :) Thank you for volunteering!

seems like @attilaszuts has already requested to cover that example. Are you still going to do it or should I?

**Comment by Ransaka** [comment]
Looking forward to contributing to this.

**Comment by JaynouOliver** [comment]
Hey @BenWilson2 can I work on this issue, as this is a good first issue, I feel I will be able to contribute here with my skills! 
Can you Please give me a chance?  I have no problem collaborating on this issue!

**Comment by dbczumar** [comment]
@BenWilson2 Can you provide some additional context on expectations here?

@JaynouOliver Of course! Thank you in advance for your contribution. Please let me know if you have any questions.

**Comment by BenWilson2** [comment]
@JaynouOliver The desired example here is something that shows a "soup to nuts" configuration of a full stack for a typical MLflow tracking server deployment. 

This means:
- Set up a SQL server that is supported by MLflow (MySQL is most widely used) in a Docker container 
- Start the Docker container and validate that the MySQL server running within it can accept queries
- Configure minio in another Docker container (with script) to serve as the artifact store
- Setup the Mlflow tracking server to use the MySQL instance as the tracking server 
- Setup an additional MLflow tracking server in --artifacts-only mode to handle passthrough to the minio instance for artifact storage
- A simple ML model script that will use the configured tracking server to log 2 experiments, each with 5-20 runs each (including nested child runs) and provide instructions on how to open up the UI to see the experiments. Then, load the experiments from the saved locations in the artifact store and perform inference in batch mode.

Hope that provides a bit more clarity on the ask here :)

**Comment by Rusteam** [comment]
@BenWilson2  how would the [Scenario 3: MLflow on localhost with Tracking Server](https://mlflow.org/docs/latest/tracking.html#id34) be different from an existing [example on artifact store](https://github.com/mlflow/mlflow/tree/master/examples/mlflow_artifacts). Seems to me they're pretty much the same.
