### ISSUE TITLE
[FR] [Roadmap] Create official helm charts for MLflow

### ISSUE THREAD

**Issue by BenWilson2** [mlflow/mlflow#6118]
## MLflow Roadmap Item

This is an MLflow Roadmap item that has been prioritized by the MLflow maintainers. We’ve identified this feature as a highly requested addition to the MLflow package based on community feedback. 
We're seeking a community contribution for the implementation of this feature and will enthusiastically support the development and review of a submitted PR for this.

## Contribution Note

As with other roadmap items, there may be a desire for multiple contributors to work on an issue. While we don’t discourage collaboration, we strongly encourage that a primary contributor is assigned to roadmap issues to simplify the merging process. 
The items on the roadmap are of a high priority. Due to the wide-spread demand of roadmap features, we encourage potential contributors to only agree to take on the work of creating a PR, making changes, and ensuring that test coverage is adequately created for the feature if they are willing and able to see the implementation through to a merged state. 

## Feature scope

This roadmap feature’s complexity is classified as:

- [ ] `good-first-issue`: This feature is limited in complexity and effort required to implement.
- [ ] `simple`: This feature does not require a large amount of effort to implement and / or is clear enough to not need a design discussion with maintainers.
- [X] `involved`: This feature will require a substantial amount of development effort but does not require an agreed-upon design from the maintainers. The feedback given during the PR phase may be involved and necessitate multiple iterations before approval. (Please bear with us as we collaborate with you to make a great contribution)
- [ ] `design-recommended`: This is a substantial feature that should have a design document approved prior to working on an implementation (to save your time, not ours). After agreeing to work on this feature, a maintainer will be assigned to support you throughout the development process.

## Proposal Summary

Many users deploy MLflow to kubernetes. In order to simplify and standardize this deployment, we need to have:
1. [Dependency on this FR: #6093] Official docker images for the MLflow Tracking Server (hosted [here](https://github.com/orgs/mlflow/packages)). 
2. Charts must permit standalone deployment to Kubernetes as well as being defined as a sub-chart within a more comprehensive helm chart for a deployment. 
3. Support for individual components (Tracking service, Serving) as well as the ability to install all services from a single `helm install` command.

These helm charts (versioned by release) should be published to the official helm repository [here](https://artifacthub.io/).  

## Motivation
> #### What is the use case for this feature? 
   Officially support kubernetes users of MLflow and consolidate community efforts to a collaborative single point of stable release.

> #### Why is this use case valuable to support for MLflow users in general? 
  This greatly simplifies (and adds support) for the many Kubernetes users who are leveraging MLflow.

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [X] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by rafaelvp-db** [comment]
@BenWilson2 also happy to contribute to this one

**Comment by BenGalewsky** [comment]
The National Center for Supercomputing Applications built a chart https://github.com/ncsa/charts/tree/main/charts/mlflow 
We'd be happy to contribute this

**Comment by skbly7** [comment]
Interested in contributing to this task. 👋

**Comment by ichbinjakes** [comment]
I have made some notes on things the helm chart might need to support 

Artifact storage configuration:
- S3 / Minio
- ABS (Azure)
- GCS
- FTP / SFTP
- NFS (volume mount: https://kubernetes.io/docs/concepts/storage/volumes/#nfs)
- HDFS

Tracking database:
- sqlite (local, mount Kubernetes volume for persistence)
- sqlalchemy uri (remote, mount uri from secret)

Mlflow server modes:
- tracking only
- proxy artifact 
- standard

#### Notes: 
- Credentials for artifact storage needs to be mounted to the pod with secrets. CA Certificates also need to be optionally mounted as volumes from secrets. The helm chart should support using existing secrets as well as having configurable values for creating secrets.
- Use a format like bitnami helm charts for documenting mlflow specific parameters in the values.yaml file

#### Questions:

> 1. [Dependency on this FR: [FR] [Roadmap] Publish official Docker image for MLflow Tracking server #6093] Official docker images for the MLflow Tracking Server (hosted here).

- The container image needs python libraries for each storage type. The current published container doesn't have boto3 needed for AWS S3 / Minio support (I haven't checked dependencies for other storage backends). We will need to add new images or modify the existing one.

> 2. Charts must permit standalone deployment to Kubernetes as well as being defined as a sub-chart within a more comprehensive helm chart for a deployment.

- Could someone expand on the comprehensive helm chart. Would this be a chart that sets up minio, postgres (or just local sqlite) and mlflow? Could we move that into another issue and get standalone done first?
- Where will the helm chart(s) go, `/charts`?

> 3. Support for individual components (Tracking service, Serving) as well as the ability to install all services from a single helm install command.

- Could someone expand on what the Serving component is? Is that just configuring mlflow as an artifact proxy?

> These helm charts (versioned by release) should be published to the official helm repository here.

- Need to add CI for pushing helm chart to the specified repository.


I am able to contribute or coordinate effort on this. I'd be able to get together a helm chart that supports cloud storage, remote db and standard serving mode but would need to leverage the expertise of others to implement HDFS, (S)FTP and NFS support (I dont have experience using these with mlflow).

**Comment by dbczumar** [comment]
Hi @ichbinjakes @BenGalewsky apologies for the delay here. The requirements outlined by @ichbinjakes look great, and I think that https://github.com/ncsa/charts/tree/main/charts/mlflow covers a lot of the groundwork. 

@ichbinjakes @BenGalewsky Would you still be interested in coordinating to extend the helm chart's capabilities and contribute it to MLflow, perhaps with help from @skbly7 if they're still interested as well?

**Comment by ichbinjakes** [comment]
@dbczumar I'm still available to coordinate and contribute to this. Happy for this issue to be assigned to me

**Comment by dbczumar** [comment]
Thanks @ichbinjakes ! Assigned :)

**Comment by Maelstro** [comment]
Hi, I'm also willing to contribute to this - I did some work on deploying MLFlow using Helm Charts, with cloud storage (S3/MinIO, GCP and Azure), I'm eager to help with this issue. 👋🏻

**Comment by dbczumar** [comment]
Hi @Maelstro , we would definitely welcome your contribution here. @ichbinjakes please let @Maelstro know how best to help :)

**Comment by ichbinjakes** [comment]
Hey @Maelstro, if you could help test on GCP and Azure that would be great :smiley:. First let me get the base charts together, just tidying them up, hopefully they will be done by next weekend.

If you or someone else want to make a helm chart for deploying models from a tracking server, feel free to have a go at that. (If you look at my fork there are instructions in `CONTRIBUTING.md` for setting up a local development cluster).

**Comment by dbczumar** [comment]
Hi @ichbinjakes, just checking in here. Have there been any updates?

**Comment by ichbinjakes** [comment]
Hey @dbczumar I have put in a draft merge request: https://github.com/mlflow/mlflow/pull/8056. @Maelstro If you are available to test the helm chart with azure and gcp storage, that would be great. I have only tested it with MinIO. It took me a while to figure out how best structure the helm chart to manage the complexity of different artifact storage providers. Happy to take feedback.

The helm chart only supports AWS/MinIO, Azure and GCP for artifact storage. If anyone wants to contribute  other providers let me know (or we could do it through separate MRs)

Some other loose ends, and whether they need to be solved in the PR is:
- Running the helm unit tests with CI
- Packaging helm chart and pushing them to a repo with CI
- Building the docker image with the artifact provider libraries and pushing it to a repo with CI

**Comment by snooyen** [comment]
Checking in here to see if I can help move this along as our organization has a vested interest in consuming an official MLFlow helm-chart.

**Comment by johncf** [comment]
Hello. I noticed that #8056 has been inactive for months. And after trying to use it in my company, I find that it is quite inflexible and impossible to use it as is for our setup. After going through its source, I realized that it can be simplified a lot, while making it a lot more flexible, by exposing ways to set up custom environment variables and volume mounts.

Is there motivation from the MLFlow team to add an official Helm chart _in the near-term_ through external contribution, and provide the necessary support? And if that’s the case, shall I make a new PR, with simplifications added on top of the changes from #8056 ?

**Comment by dhrp** [comment]
@johncf I second you. I've looked at using the [community-charts/mlflow](https://github.com/community-charts/helm-charts/tree/main/charts/mlflow) helm chart, but it has not been updated in months and cannot be run without modifications. 

It is, however, still better built than PR #8056, which is not DRY and doesn't seem flexible. If you're up for it I'm willing to collaborate with you to make a good Helm chart, and help maintain it here if necessary.

**Comment by BenGalewsky** [comment]
So @ichbinjakes if I made a PR to contribute the [NCSA MLFlow Helm Chart](https://github.com/ncsa/charts/tree/main/charts/mlflow) into the MLFlow repo it would be welcome?

I'd be happy to do that and have used the chart now for several deployments with different setups.

**Comment by johncf** [comment]
@dhrp I have pushed all the changes I made for internal use (at my company) [here](https://github.com/johncf/mlflow/tree/mlflow-helm-charts/charts/mlflow). The changes I made were on top of what's in #8056, and a diff can be viewed [here](https://github.com/johncf/mlflow/commit/60ba18a3011da3018a313b463c09ad7f29aab9d4)

Feel free to take it from there. I have talked with my manager, and this contribution can be considered to be of the original MLflow license, Apache version 2. 

I didn't update the tests since there was no response from the maintainers here yet.

**Comment by dhrp** [comment]
Ok, great. I like where we are going and I like the simplifications that @johncf made. @BenGalewsky version also looks mature (but lacks storage options, and is a bit biased). I will try to review and test these as well. 

If we can then get some attention from @harupy or @dbczumar for an "ok to work on it"

**Comment by BenWilson2** [comment]
@dhrp We'll definitely be interested in reviewing a non-opinionated and community-consensus validated implementation. For this helm chart, being firmly rooted in the k8s community of users, we'd like to get feedback from MLE's who are experts here to ensure that the solution works for the vast majority of use cases. 
Whomever ends up working on the PR, can we solicit feedback from everyone on this thread to provide reviews to the PR and ensure that your voice is heard?

**Comment by carrodher** [comment]
Dear MLflow Community,

I hope this message finds you well. We wanted to share some exciting news with you regarding Helm chart support for MLflow. At [Bitnami](https://bitnami.com/), we have developed our own Helm chart for MLflow, and we're thrilled to invite the MLflow community to collaborate, test, and provide feedback on this chart.

Our [Bitnami Helm chart for MLflow](https://github.com/bitnami/charts/tree/main/bitnami/mlflow) is designed to simplify the deployment and management of MLflow instances on Kubernetes, streamlining the process for users who prefer Helm as their package manager. We've put considerable effort into ensuring that it meets the highest standards for reliability, security, and ease of use.

We believe in the power of open-source collaboration, and we see an opportunity to align efforts with the upstream MLflow project. By collaborating and converging efforts around a single Helm chart, we can collectively ensure a more robust, well-maintained, and feature-rich solution for the entire MLflow community.

How you can get involved:
- **_Test the Bitnami Helm Chart_**: You can find our [Helm chart for MLflow](https://github.com/bitnami/charts/tree/main/bitnami/mlflow) and give it a spin. Your feedback and testing will be invaluable in improving the chart.
- **_Provide Feedback_**: We welcome your feedback on the Bitnami Helm chart. If you encounter any issues, have suggestions, or need assistance, please don't hesitate to share your thoughts by opening an Issue or PR in the [Bitnami charts GH repository](https://github.com/bitnami/charts).
- **_Collaborate_**: We are open to collaboration and contributions from the MLflow community. If you have ideas for improvements, or if you would like to participate in the development of the Helm chart, please let us know.

Our vision is to work together to make this Helm chart the official solution for deploying MLflow on Kubernetes. By pooling our resources and knowledge, we can create a Helm chart that caters to the diverse needs of the MLflow community.

Thank you for your time and consideration. We look forward to collaborating with you to enhance the MLflow Helm chart experience for everyone.

**Comment by ichbinjakes** [comment]
I won't be putting anymore effort into this as there does not seem to be interest from maintainers and bitnami has provided a chart. Anyone is welcome to continue this work.

**Comment by kjoth** [comment]
Hi, Are there any plans to integrate LLM features into the Helm chart, MLFlow Deployment server, and the Prompt Engineering UI for LLMs?

**Comment by aliabbasjaffri** [comment]
If anyone who has used the [bitnami mlflow chart](https://github.com/bitnami/charts/blob/main/bitnami/mlflow/values.yaml), they can understand the pain to actually be able to make it work. Its not just that, there is no documentation available to simply provide guidance for that chart's configuration or usage.
On the other hand, the [mlflow community helm chart](https://github.com/community-charts/helm-charts/tree/main/charts/mlflow) is somewhere closer to an ideal state but it isn't being actively maintained (last commit made over a year ago!)

I'm rather unsure why would a renouned and leading experiment tracking tool would be so far behind providing an offering for their kubernetes helm chart, especially when it is so highly in demand from the community and users?

**Comment by ChenYi015** [comment]
Hi @dbczumar , can I work on this? I had made some work [here](https://github.com/ChenYi015/mlflow/tree/helm-charts-dev)  and I am happy to contribute a helm chart for MLflow.

**Comment by riyanuddin17** [comment]
Did someone configured SSL with MLflow?? using env MLFLOW_TRACKING_CLIENT_CERT_PATH

**Comment by sorushsaghari** [comment]
i am also eager to do this. i want to contribute too

**Comment by paravatha** [comment]
Mlflow team, any updates on this?

**Comment by kimminw00** [comment]
Given that Bitnami is moving all production images and charts behind a subscription (referencing [bitnami/charts#35164](https://github.com/bitnami/charts/issues/35164)), it would be highly valuable to create an official Helm chart for MLflow.

**Comment by Jasper-Ben** [comment]
Regarding the mlflow helm chart provided by bitnami:

All versioned bitnami charts will soon be behind a paywall: https://github.com/bitnami/charts/issues/35164.

Not that I am surprised since bitnami is now part of Broadcom Inc. 😉

**Comment by B-Step62** [comment]
Thank you for the heads-up, @Jasper-Ben!

Coincidentally, we are going to support official tracking server docker image and quickstart docker-compose as a part of this year's roadmap, so I hope it will cover the gap for small scale self-hosting usage. For helm chart, we're interested in seeking community contribution, as well as a good collaboration model to maintain the chart up-to-date!

**Comment by paravatha** [comment]
🚀 Its finally being released https://github.com/mlflow/mlflow/releases/tag/v3.13.0rc0

**Comment by B-Step62** [comment]
☸️ An official Helm chart shipped in **MLflow 3.13.0**. You can now deploy the MLflow tracking server to any Kubernetes cluster with a maintained chart. Docs: https://mlflow.org/docs/latest/self-hosting/kubernetes-helm

@paravatha @Jasper-Ben @snooyen @aliabbasjaffri @johncf @dhrp, you all asked for this, please give it a try and share any feedback!

**Comment by yuiri-sedykh** [comment]
Hi, the issue description mentions that the Helm charts should be published to the official Helm repository on ArtifactHub, but I can't find any MLflow chart there. Is there still a plan to publish it, or has that been dropped? Would be great to have it available for easy discovery and install.
