### ISSUE TITLE
[BUG] `mlflow.spark.log_model` produces sparkml folder with only SUCCESS files with s3 as artifact store

### ISSUE THREAD

**Issue by mjstel** [mlflow/mlflow#6129]
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

1.26.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: apache/spark-py:3.2.1 Docker Image on K8s
- **Python version**: 3.9

### Describe the problem

Hello, we are trying to create a KMeans model using spark.ml. The spark job runs against our Kubernetes cluster in cluster-mode.

Saving the model directly via `model.save(...)` works as expected, but using `mlflow.spark.log_model` uploads the model to our tracking server, but when looking inside the sparkml folder, we only see a folder structure with some SUCCESS files.

![image](https://user-images.githubusercontent.com/23032465/175505852-2d75aee3-a4b7-4d5b-b8f8-a6535b1d3383.png)

When loading the model with `mlflow.spark.load_model` we're getting the following Error:
```
Traceback (most recent call last):
  File "/tmp/spark-36be34e7-5e43-4293-8542-3cf41f99ae18/main.py", line 140, in <module>
    model_info = mlflow.spark.load_model(model_uri=model_info.model_uri)
  File "/usr/local/lib/python3.9/dist-packages/mlflow/spark.py", line 711, in load_model
    return _load_model(model_uri=model_uri, dfs_tmpdir_base=dfs_tmpdir)
  File "/usr/local/lib/python3.9/dist-packages/mlflow/spark.py", line 660, in _load_model
    return PipelineModel.load(model_uri)
  File "/opt/spark/python/lib/pyspark.zip/pyspark/ml/util.py", line 332, in load
  File "/opt/spark/python/lib/pyspark.zip/pyspark/ml/pipeline.py", line 256, in load
  File "/opt/spark/python/lib/pyspark.zip/pyspark/ml/util.py", line 525, in loadMetadata
  File "/opt/spark/python/lib/pyspark.zip/pyspark/rdd.py", line 1591, in first
ValueError: RDD is empty
```

### Tracking information

MLflow version: 1.26.1
Tracking URI: http://mlflow.mlflow.svc.cluster.local:5000
Artifact URI: s3://<omitted>/0/6881283daca5440ba5c701ce6a5795e5/artifacts

### Code to reproduce issue

```python
import mlflow.spark
from pyspark.sql import SparkSession
from pyspark import SparkConf, SparkContext
from pyspark.ml.clustering import KMeans
from pyspark.sql import Row
from pyspark.ml.linalg import DenseVector

conf = SparkConf()
sc = SparkContext(conf=conf)
spark = SparkSession(sc)
mlflow.set_tracking_uri("http://mlflow.mlflow.svc.cluster.local:5000")

ml_input = spark.createDataFrame(
    [
        Row(features=DenseVector([38851.2266, 62739.2031, 23.0, 2.0, 8.0, 155.0, 0.0, 886.0, -863.0]), scaled_features=DenseVector([1.5453, 2.3341, 0.4422, 0.1807, 0.255, 1.0514, 0.0, 1.6196, -1.7345])),
        Row(features=DenseVector([485.0, 230.5168, 3.0, 0.0, 0.0, 0.0, 0.0, 1.0, 2.0]), scaled_features=DenseVector([0.0193, 0.0086, 0.0577, 0.0, 0.0, 0.0, 0.0, 0.0018, 0.004]))
    ]
)

model = KMeans(k=50, featuresCol="scaled_features").fit(ml_input)
model_info = mlflow.spark.log_model(spark_model=model, artifact_path="botspotter-kmeans", registered_model_name="kmeans")
loaded_model =  mlflow.spark.load_model(model_uri=model_info.model_uri)
```

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by ericbuzato** [comment]
Hello @mjstel , I'm facing the same problem. Could you share what the solution was please?

**Comment by hardymis** [comment]
Hello @mjstel and @mjstel , I have you get some solutions? I get the same error :(

**Comment by FelixGSE** [comment]
Hi sorry for the late reply. We haven't touched this in a while. We lately picked it up again and with the latest version of `mlflow` (`mlflow==2.1.1`) and `apache/spark-py:v3.3.1` as base image we don't experience this issue anymore. Here is the basic spark-submit command we use to submit our application:

```bash
S3_BASE_PATH=s3a://blabla/blbas

spark-submit \
  --master k8s://https://<MASTER_IP>:<MASTER_PORT> \
  --deploy-mode cluster \
  --name cool_application \
  --packages="org.apache.hadoop:hadoop-aws:3.3.4" \
  --conf spark.hadoop.fs.s3a.aws.credentials.provider=org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider \
  --conf spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem \
  --conf spark.hadoop.fs.s3.impl=org.apache.hadoop.fs.s3a.S3AFileSystem \
  --conf spark.executor.instances=4 \
  --conf spark.executor.processTreeMetrics.enabled=true \
  --conf spark.kubernetes.container.image=<IMAGE_NAME> \
  --conf spark.kubernetes.container.image.pullPolicy=Always \
  --conf spark.kubernetes.namespace=<NAMESPACE> \
  --conf spark.kubernetes.authenticate.driver.serviceAccountName=<SERVICE_ACCOUNT_NAME> \
  --conf spark.hadoop.fs.s3a.access.key=<ACCES_KEY> \
  --conf spark.hadoop.fs.s3a.secret.key=<SECRET_KEY> \
  --conf spark.kubernetes.driver.secretKeyRef.AWS_ACCESS_KEY_ID=<SECRET_NAME>:aws_access_key_id \
  --conf spark.kubernetes.executor.secretKeyRef.AWS_ACCESS_KEY_ID=<SECRET_NAME>:aws_access_key_id \
  --conf spark.kubernetes.driver.secretKeyRef.AWS_SECRET_ACCESS_KEY=<SECRET_NAME>:aws_secret_access_key \
  --conf spark.kubernetes.executor.secretKeyRef.AWS_SECRET_ACCESS_KEY=<SSECRET_NAME>:aws_secret_access_key \
  --conf spark.kubernetes.driver.secretKeyRef.AWS_DEFAULT_REGION=<SECRET_NAME>:aws_default_region \
  --conf spark.kubernetes.executor.secretKeyRef.AWS_DEFAULT_REGION=<SECRET_NAME>:aws_default_region \
  --conf spark.kubernetes.file.upload.path="$S3_BASE_PATH/spark" \
  --conf spark.hadoop.fs.s3a.fast.upload=true \
  --conf spark.executor.memory=8g \
  --conf spark.executor.cores=4 \
  --conf spark.kubernetes.container.image.pullSecrets=<PULL_SECRET_NAME> \
  --verbose \
  file:///<PATH_TO_SCRIPT>/foo.py
```

Also it helped as for debugging to set `mlflow` and `pyspark` loggers to debug. 

```python
logging.getLogger("mlflow").setLevel(logging.DEBUG)
logging.getLogger("pyspark").setLevel(logging.DEBUG)
```
Hope that helps

**Comment by JohnatanSantana** [comment]
Hi,

I was facing the same probleming. Our scenario was using spark operator on AKS, but in our case was a missing a config for hadoop. 
Have fixed it setting param **dst_path** when use ***mlflow.spark.load.model*** pointing to a mount that is shared between the driver and executors
   * :param dfs_tmpdir: Temporary directory path on Distributed (Hadoop) File System (DFS) or local
                       filesystem if running in local mode. The model is written in this
                       destination and then copied into the model's artifact directory. This is
                       necessary as Spark ML models read from and write to DFS if running on a
                       cluster. If this operation completes successfully, all temporary files
                       created on the DFS are removed. Defaults to ``/tmp/mlflow``.*
for example:

```mlflow.spark.load_model(model_uri, dst_path="/mnt/")```

So, when we use spark file will be downloaded in a shared mount point between executors, if use default it will be saved in driver.

hope this that can help.

**Comment by pamin2222** [comment]
Hello,

I was having this issue too. This is one workaround that works in my case.

Save model:

1. Create a PersistentVolumeClaim (PVC) & mount it to Spark drivers/executors
2. Use mlflow.spark.log_model() with 'dfs_tmpdir' parameter set to a shared PVC directory.

Load model:
Use spark.PipelineModel.load("s3 model path") to load model directly from S3


I still cannot load the model with mlflow.spark.load_model().
It will result in the following error even when using PVC 'dfs_tmpdir':
"file:/tmp/tmpxgdze85x/sparkml/metadata/part-00000 does not exist\n"
