### ISSUE TITLE
[FR] Rollback to Previous Model Version in Stage

### ISSUE THREAD

**Issue by MinuraPunchihewa** [mlflow/mlflow#6180]
### Willingness to contribute

Yes. I would be willing to contribute this feature with guidance from the MLflow community.

### Proposal Summary

It would be useful to be able to rollback to a previous model version in given stage, especially Production.

For example, say that I am working on a particular a model and after several iterations, I decide to move version 3 into Production. Now, after a few more rounds development and tuning, I have what I believe to be a better model in version 7 and I decide that I can move it into Production.

After a while, when scoring on the new model version, my analysts inform me that there is some kind of bug with the new version. In such a situation, I would like to be able to quickly move back to the previous version, which I know was working fine, so that no further predictions will be affected.

### Motivation

> #### What is the use case for this feature?
The use case is to be able to quickly rollback to a previous model version in a stage, particularly in Production, that was working fine, without having to remember or search through model versions.

> #### Why is this use case valuable to support for MLflow users in general?
The need to move back to a previous model version is a scenario that I believe anyone can come across.

> #### Why is this use case valuable to support for your project(s) or organization?
I have come across the need to rollback, as a result of bugs that exist in the newer model versions that are transitioned.

> #### Why is it currently difficult to achieve this use case?
At the moment, I am not sure if it is possible to achieve this, outside of searching through all of the models and deciding which one to bring back.

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by WeichenXu123** [comment]
Good feature proposal ! How do you want to implement the feature ? Unregister the last X models ?

**Comment by WeichenXu123** [comment]
On second thought, if you want to rollback "product" stage model, seemingly you can call `transition_model_version_stage` API to transition this model back to "staging" stage, does this satisfy your demand ?

**Comment by MinuraPunchihewa** [comment]
@WeichenXu123 This is actually not about transitioning the same model version between stages (e.g. moving model version 3 from Production to Staging), rather it is concerned with moving back to a previous model version _within a given stage_.
For instance, model version 3 was in Production previously and it was working fine. After a while, you decide to move model version 7 into production. However, you find out that there is a bug in this new version (version 7) and you want to move back to a version that you know was working properly (version 3). 
When you have a large number of versions registered, it is difficult to keep in mind which model version to go back to (if you are making direct transitions, say by using the `transition_model_version_stage` API). This is why I think this feature might be useful.
We could also maybe provide several options along with this, such as moving back to the first model version in a stage or rollback n times and so on.

**Comment by WeichenXu123** [comment]
@MinuraPunchihewa Got it.
What do you think of this solution:

Add a API like : `rollback_model_to_version(rollback_version, stage)`

it will do: for all models in the `stage` and version larger than `rollback_version`, transition their stage to be "archived".

**Comment by MinuraPunchihewa** [comment]
@WeichenXu123 We would need to specify which model version we are trying to rollback to here, yes? If we knew which model version we need to go back to, then we can simply use `transition_model_version_stage` like you mentioned previously.
The rollback operation, in my opinion, is useful when we don't know which version we want go back to, like I have mentioned in my example. With rollbacks, we are trying to move back to one of the previous versions that were in the stage.

A couple of notes,
- I think this is most useful when we want to maintain one version of a model in a given stage
- I am not completely aware if MLflow keeps a track of the various transitions that take place or all of the model versions that have been in a stage

**Comment by WeichenXu123** [comment]
@MinuraPunchihewa Understood.

> I think this is most useful when we want to maintain one version of a model in a given stage.

Why you need to only keep one model in a given stage ?

If you allow multiple model versions in a stage, and each time you add a new model into given stage, keep old models stage unchanged, then, e.g. in product stage, when you want to rollback to previous product model version, you can transition the latest produce model to "archived" stage, then you can call `get_latest_versions(stage='product')` then you get the previous version product model.

**Comment by MinuraPunchihewa** [comment]
@WeichenXu123 That's clear. But, in my organization, we prefer to maintain only a single model version in Production (in Staging as well, but that is not as important). The version in Production is the model that actually runs in the Production environment.

MLflow already facilitates this through the UI by transitioning model versions that already exist in a given stage to Archived,
![image](https://user-images.githubusercontent.com/49385643/177271101-1c673cbf-c2b7-4d61-8e9a-d5b85869cc9e.png)

This is also supported in the `transition_model_version_stage` API through the `archive_existing_versions ` flag.

What is your experience on how other organizations approach this? I was under the impression that most organizations would want only one version in certain stages, especially in Production (definitely not in None and Archived though).

**Comment by WeichenXu123** [comment]
Got it. CC @dbczumar What's the best practice for model stage setting ? (suppose we need to support rollback to previous version easily). If our best practice is only keep one model version in product stage, then it cannot easily support rollback to previous version (in this case we are hard to get the previous version)

**Comment by WeichenXu123** [comment]
We can add tag for history model in a stage, and then search by tag.

**Comment by MinuraPunchihewa** [comment]
@WeichenXu123 That's a great idea! Can this be incorporated into a MLflow API as well?

**Comment by WeichenXu123** [comment]
@MinuraPunchihewa Sure! We need to add API to query model by tags. Are you interested in contributing it ?

**Comment by dbczumar** [comment]
@WeichenXu123 @MinuraPunchihewa We are currently working on extending the `search_model_versions()` to support searching by. tags; however, for this use case, using `search_model_versions()` to filter based on the model name should be sufficient to fetch all model versions belonging to the model. After that, the tags of each model can be parsed according to @WeichenXu123's proposal. @MinuraPunchihewa at this time, we don't intend to incorporate this functionality into the MLflow API, but we can absolutely revisit it in the future; for now, we recommend using tags to solve the rollback problem. Thank you for using MLflow :)

API docs: https://mlflow.org/docs/latest/python_api/mlflow.tracking.html#mlflow.tracking.MlflowClient.search_model_versions.

**Comment by MinuraPunchihewa** [comment]
@dbczumar Understood. Thank you for your explanation. Should this issue be left open or shall I close it for now?

**Comment by dbczumar** [comment]
Of course! Hope it helped! I'm going to go ahead and close this for now, but we'll absolutely revisit rollbacks at some point in the future. Cheers! :)

**Comment by WeichenXu123** [comment]
@MinuraPunchihewa 
We have added tag based searching for model versions. See this PR: https://github.com/mlflow/mlflow/pull/6320

You use the feature in next mlflow release or you can install mlflow master version by `pip install git+https://github.com/mlflow/mlflow.git`

**Comment by MinuraPunchihewa** [comment]
@WeichenXu123 Thanks for the info. Much appreciated.
