### ISSUE TITLE
Tracking Server not working as a proxy for localhost

### ISSUE THREAD

**Issue by njanopoulos** [mlflow/mlflow#6181]
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

1.25.1

### System information

- localhost: GitBash
- Remote Host: Kubernetes POD
- Artifact Destination: AWS S3
- Python 3.7.2

### Describe the problem

I am having similar issue to what was posted here: https://github.com/mlflow/mlflow/issues/5659
Unfortunately, the solution provided hasn't worked for me.
When running a modeling script on the Remote Host, the artifacts get stored in S3 properly. When I run from localhost, I get:

botocore.exceptions.NoCredentialsError: Unable to locate credentials

I have determined that it expects to use local creds when running on localhost instead of the ones on the Tracking Server.
Hoping somebody has more suggestions of things to try or look for.

### Tracking information

Tracking & Artifact uri look as expected.  Not sharing for security reasons.

### Code to reproduce issue

```
mlflow.set_tracking_uri("masked")

mlflow.set_experiment("masked")
with mlflow.start_run():
.
.
.
    plt.savefig('plot.png')
    print(mlflow.get_tracking_uri())
    print(mlflow.get_artifact_uri())
    mlflow.log_artifact("plot.png")
```

### Other info / logs

botocore.exceptions.NoCredentialsError: Unable to locate credentials

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by WeichenXu123** [comment]
@harupy Would you like to provide some help for the user ? 
This is similar to the previous issue you replied https://github.com/mlflow/mlflow/issues/5659

**Comment by harupy** [comment]
@njanopoulos What does your tracking URI look like? Can you replace sensitive information with random strings and share it with us?

**Comment by harupy** [comment]
@njanopoulos Thanks for the comment.

> It all works from Tracking Server.

I think it's because the tracking server has credentials for S3, but your local machine doesn't.

**Comment by bkolb249** [comment]
I am having a similar issue as described here. Also running tracking server on kubernetes, with:

```
mlflow server \
    --host 0.0.0.0 \
    --port 5000 \
    --backend-store-uri postgresql://user:pw@endpoint \
    --artifacts-destination s3://folder/artifacts/ \
    --serve-artifacts \
    --default-artifact-root s3://folder/artifacts/ \
``` 

When I run `print(mlflow.get_artifact_uri())`, I get a similar output as @njanopoulos:

```
s3://folder/artifacts/4/49712sf7b542594f7ab312412asr4ae7c84/artifacts
```
however, according to [this comment](https://github.com/mlflow/mlflow/issues/5659#issuecomment-1096633208) in #5659 , it should probably be `mlflow-artifacts://...` instead of `s3://...`, which is also indicated in the [docs](https://www.mlflow.org/docs/latest/tracking.html#scenario-5-mlflow-tracking-server-enabled-with-proxied-artifact-storage-access):

![image](https://user-images.githubusercontent.com/23722371/177714047-6af0a2ba-690b-45d0-a719-e0b3f202c041.png)

Does this help to identify the issue?

**Comment by harupy** [comment]
@bkolb249 Did you create a new experiment?

**Comment by bkolb249** [comment]
yes, indicated in the logs by `2022/07/07 09:00:04 INFO mlflow.tracking.fluent: Experiment with name 'test5' does not exist. Creating a new experiment.`

**Comment by harupy** [comment]
@bkolb249 Can you check the experiment artifact URI?

**Comment by bkolb249** [comment]
Is the *experiment artifact URI* different from the *artifact URI*, i.e. the output I get from `print(mlflow.get_artifact_uri())`? The output of latter command is:
`s3://folder/artifacts/4/ace4fc93c9364afa9ee2b2b81ee91ef0/artifacts`

**Comment by harupy** [comment]
@bkolb249 Can you launch the server with this command:

```
mlflow server \
    --host 0.0.0.0 \
    --port 5000 \
    --backend-store-uri postgresql://user:pw@endpoint \
    --artifacts-destination s3://folder/artifacts/ \
    --serve-artifacts \
    👇👇👇 (remove this line)
    --default-artifact-root mlflow-artifacts:/
```

and create a new experiment, and then log artifacts?

**Comment by bkolb249** [comment]
```
mlflow server \
    --host 0.0.0.0 \
    --port 5000 \
    --backend-store-uri postgresql://user:pw@endpoint \
    --artifacts-destination s3://folder/artifacts/ \
    --serve-artifacts
```

**Comment by njanopoulos** [comment]
args:
        - '--host=0.0.0.0'
        - '--port=5000'
        - '--serve-artifacts'
        - >-
          --backend-store-uri=postgresql://user:pw@endpoint
        - >-
          --artifacts-destination=s3://bucket/folder/mlflow

Does the order of the args matter?
Wondering if --serve-artifacts needs to be after --artifacts-destination, not before it. Can try that.

**Comment by harupy** [comment]
@njanopoulos 

> Does the order of the args matter?

It doesn't.

Can you check the artifact URI of your experiment?
Can you create a new experiment, and then log artifacts?

**Comment by njanopoulos** [comment]
> @njanopoulos To confirm, you don't specify `--default-artifact-root`, right? and what does your artifact URI look like? Does it looks like `<tracking_uri>/api/2.0/mlflow-artifacts`?

Correct, default-artifact-root is not specified.

Artifact URI is set up as:
s3://bucket/folder/mlflow/

During the most-recent run, Artifact URI was resolved as:
s3://bucket/folder/mlflow/0e8c1fd6c26048b9abba66279b4f0f8c/artifacts

**Comment by harupy** [comment]
@njanopoulos Can you run this on your local machine?

```
import uuid

mlflow.set_tracking_uri("your traking URI")
mlflow.set_experiment(uuid.uuid4().hex)
with mlflow.start_run():
    print(mlflow.get_arttifact_uri())
```

**Comment by harupy** [comment]
@njanopoulos To confirm, the tracking server is NOT running on your local machine, right?

**Comment by harupy** [comment]
> Max retries exceeded with url: /api/2.0/mlflow-artifacts/artifacts/116/963aa747f26042fbafc7ec11c1bff0f7/artifacts/file.png (Caused by ResponseError('too many 500 error responses'))

Can you check the tracking server log?

**Comment by harupy** [comment]
> Max retries exceeded with url: /api/2.0/mlflow-artifacts/artifacts/116/963aa747f26042fbafc7ec11c1bff0f7/artifacts/file.png (Caused by ResponseError('too many 500 error responses'))

This means the client tried to upload the artifact using the tracking server as a proxy.

**Comment by njanopoulos** [comment]
botocore.exceptions.ClientError: An error occurred (InvalidToken) when calling the PutObject operation: The provided token is malformed or otherwise invalid.

boto3.exceptions.S3UploadFailedError: Failed to upload /tmp/tmp6b_9p7f0/file.png to bucket/folder/mlflow/117/38ca57eb511d48289ff41db184159a62/artifacts/file.png: An error occurred (InvalidToken) when calling the PutObject operation: The provided token is malformed or otherwise invalid.

**Comment by harupy** [comment]
Can you double-check?

**Comment by njanopoulos** [comment]
I continue to be successful when I run on tracking server with artifact_location in the format I mentioned.  Is there I way I can tell what creds I have when I'm running the other way, and from local host?

**Comment by harupy** [comment]
> when I run on tracking server 

Can you elaborate on this? Could you share the code you used?

**Comment by harupy** [comment]
@njanopoulos  Can you try running boto3 code ([example](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/s3-uploading-files.html)) instead of running `mlflow server`?

**Comment by njanopoulos** [comment]
It also works on the tracking server with boto3 code.

**Comment by harupy** [comment]
> It also works on the tracking server with boto3 code.


You saved the example in a file and ran `python /path/to/file.py` instead of running `mlflow server`?

**Comment by harupy** [comment]
How do you setup  AWS credentials? Using environment variables?

**Comment by harupy** [comment]
@njanopoulos I modified the mlflow source code to print out AWS credentailas. You can install it with the following command:

```
pip install git+https://github.com/harupy/mlflow.git@print-aws-credentials
```

Example:

```
> docker run --rm \
  -e AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY \
  -e AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE \
  python:3.7 \
  bash -c 'pip install git+https://github.com/harupy/mlflow.git@print-aws-credentials boto3 && python -c "from mlflow.store.artifact.s3_artifact_repo import S3ArtifactRepository;  S3ArtifactRepository(\"s3://my/bucket\")._get_s3_client()"'
...
==============================
ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
==============================
```

**Comment by harupy** [comment]
@njanopoulos Any updates here?

**Comment by njanopoulos** [comment]
We will be getting back to this issue next week. Sorry for the delay. Thank you for all of your help.

**Comment by rasika** [comment]
Are you trying this on an existing experiment? If that's the case; it will work as non-proxied if that experiment is created before moving to the proxied state. Note from the [docs](https://mlflow.org/docs/latest/tracking.html#scenario-6-mlflow-tracking-server-used-exclusively-as-proxied-access-host-for-artifact-storage-access);

```
When an experiment is created, the artifact storage location from the configuration of the tracking server is logged in the experiment’s metadata. When enabling proxied artifact storage, any existing experiments that were created while operating a tracking server in non-proxied mode will continue to use a non-proxied artifact location. In order to use proxied artifact logging, a new experiment must be created. If the intention of enabling a tracking server in -serve-artifacts mode is to eliminate the need for a client to have authentication to the underlying storage, new experiments should be created for use by clients so that the tracking server can handle authentication after this migration.
```

**Comment by jdonzallaz** [comment]
Hi @harupy,

We have the same problem here, when using the server as proxy.  
The artifact location of the experiment in the database is "s3://mlflow-artifacts/0". But I have the following error on the client side: `boto3.exceptions.S3UploadFailedError: Failed to upload {user-dir}\AppData\Local\Temp\tmpdot8hrp7\model\conda.yaml to mlflow-artifacts/0/69a7db5a7b9546dda7d80d9b71cca43c/artifacts/conda.yaml: An error occurred (InvalidAccessKeyId) when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.

I tried to run your code printing the AWS credentials on both the server and the client. They are correct on the server side, but not on the client side (it shows credentials from my `.aws/credentials` file.

It tries to use the s3_client code to upload the file on the client side, which I'm not sure is correct in proxy mode?

**Comment by jdonzallaz** [comment]
@harupy 

Yes, I deleted/recreated new experiments each time.  
The key is apparently to not use the `--default-artifact-root` argument as you stated in a previous comment (I didn't tried this before). This works for me.

**Comment by njanopoulos** [comment]
> @njanopoulos I created mlflow that prints out AWS credentials used when logging artifacts in S3. You can install it with the following command:
> 
> ```
> pip install git+https://github.com/harupy/mlflow.git@print-aws-credentials
> ```
> 
> This mlflow should print out AWS credentials like this:
> 
> ```shell
> # Test
> 
> > docker run --rm -e AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY -e AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE python:3.7 bash -c 'pip install git+https://github.com/harupy/mlflow.git@print-aws-credentials boto3 && python -c "from mlflow.store.artifact.s3_artifact_repo import S3ArtifactRepository;  S3ArtifactRepository(\"s3://my/bucket\")._get_s3_client()"'
> 
> ==============================
> ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
> SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
> ==============================
> ```
> 
> Can you install this and check the credentials used in the failed (the tracking server used as a proxy) and successful (directly log artifacts in the tracking server) cases?

The creds when logging artifacts successfully from tracking server are properly populated.
The creds when using tracking server as proxy are not populated and appear null.

AttributeError: 'NoneType' object has no attribute 'get_frozen_credentials'

**Comment by harupy** [comment]
@njanopoulos This indicates something is wrong with your credential setup. How do you provide AWS credentials?

**Comment by harupy** [comment]
Did you run `pip install git+https://github.com/harupy/mlflow.git@print-aws-credentials` before launching the tracking server?

```
pip install git+https://github.com/harupy/mlflow.git@print-aws-credentials
mlflow server ...
```

**Comment by njanopoulos** [comment]
> @njanopoulos Did you run `pip install git+https://github.com/harupy/mlflow.git@print-aws-credentials` before launching the tracking server?
> 
> ```
> pip install git+https://github.com/harupy/mlflow.git@print-aws-credentials
> mlflow server ...
> ```
> 
> > AttributeError: 'NoneType' object has no attribute 'get_frozen_credentials'
> 
> Did the tracking server throw this error? or the client did?

The client threw that. I'm not in a position to install things on the proxy server; I need to engage another team in the company for that, so in the meantime, I'm using similar code in the script that runs the model. Makes sense why it works from the proxy server (we see creds there), and not on the client (no creds).

**Comment by harupy** [comment]
@njanopoulos Did the tracking server throw `boto3.exceptions.S3UploadFailedError` in https://github.com/mlflow/mlflow/issues/6181#issuecomment-1177927640? If the tracking server did, that means the token used in the environment where `mlflow server` is running, is malformed or otherwise invalid.

**Comment by njanopoulos** [comment]
> @njanopoulos One more question. Did the tracking server throw `boto3.exceptions.S3UploadFailedError` in [#6181 (comment)](https://github.com/mlflow/mlflow/issues/6181#issuecomment-1177927640)? If the tracking server did, that means the token used in the environment where `mlflow server` is running, is malformed or otherwise invalid.

Yes, when running with a new experiment, I get messages on the tracking server that say malformed or otherwise invalid token.  Why would this be only when running from client?  When running from tracking server, it succeeds.

**Comment by harupy** [comment]
> The malformed token type errors occur when creating the experiment new during the run.

Do you have the stack trace?

**Comment by harupy** [comment]
> To be clear, the same script run from a client fails with an 'Unable to locate credentials error'.

This is expected because `s3://bucket/folder/folder` is a non-proxy URI so the client attempts to log artifacts using boto3.

**Comment by njanopoulos** [comment]
I think we've uncovered something that is key.

Non-proxied PUT to S3:
- Tracking Sever: works
- Client: fails (no creds)

Proxied PUT to S3:
- Tracking Server fails (malformed token)
- Client fails (malformed token)

I'm still working through the stack trace, but seems the Proxied connection to AWS has an authentication step that is failing, one that is different from how the Non-proxied connection approaches authentication.

**Comment by harupy** [comment]
@njanopoulos How do you set up AWS credentials? environment variables?

**Comment by harupy** [comment]
> Client fails (malformed token)

- Did the client send requests to log artifacts to the tracking server?
- Who threw the malformed token error?

**Comment by njanopoulos** [comment]
> @njanopoulos How do you set up AWS credentials? environment variables?

Yes - in the yaml file for the container, a file is specified, where the creds are located.

**Comment by njanopoulos** [comment]
> > Client fails (malformed token)
> 
> * Did the client send PUT requests to log artifacts to the tracking server?
> * Who threw the malformed token error?

mlflow.log_artifact(file.png)  is used
tracking server threw the malformed token error...on client it appears as timeout error

**Comment by harupy** [comment]
> tracking server threw the malformed token error

This indicates the environment where `mlflow server` is running has invalid credentials, right?

**Comment by harupy** [comment]
@njanopoulos Does the pod you entered have the same credentials as the pod where `mlflow server` is running?

**Comment by njanopoulos** [comment]
> @njanopoulos Does the pod you entered have the same AWS credentials as the pod where `mlflow server` is running?

Yes. The mlflow server is running on that very same pod.

**Comment by harupy** [comment]
@njanopoulos Have you checked the process where `mlflow server` is running have valid AWS credentials?

**Comment by njanopoulos** [comment]
> @njanopoulos Have you checked the process where `mlflow server` is running have valid AWS credentials? Can you print out the AWS environment variables before running `mlflow server` and check they are valid?

Great idea. For whatever reason, scripts that run on the pod get proper creds, but the mlflow server running on the same pod does not get the creds. Need to figure out why.

**Comment by harupy** [comment]
@njanopoulos Nice, please ping me once you figure it out.

**Comment by harupy** [comment]
@njanopoulos Feel free to reopen the issue if providing valid AWS credentials in the pod the mlflow server is running in, doesn't fix the issue.

**Comment by njanopoulos** [comment]
Thank you for all the help!

**Comment by nfarley-soaren** [comment]
I know this is a little different from the current issue but stumbled across it in my current search for answers and it seems to have some relevance so I figured I'd ask.   I'm using a similar set up with a remote AWS server as host.  I've tried specifying either and both `--artifacts-destination` and `--default-artifact-root` along with `--serve-artifacts` and got identical results.  Everything ends up in S3 but errors in the UI with `LOADING ARTIFACTS FAILED.`  After reading this thread, where it is recommended to exclude `--default-artifact-root`, I'm wondering why they can't just be set to the same location?  Also, excluding it completely didn't seem to matter in my case.
