### ISSUE TITLE
[BUG] Permissions issue when writing on /workspace

### ISSUE THREAD

**Issue by VC86** [mlflow/mlflow#6515]
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

1.27.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 22.04.1 LTS
- **Python version**: 3.9 (Mambaforge)
- **yarn version, if running the dev UI**: n/a

### Describe the problem

After terminating an unfinished run (while writing and debugging code), I see the following error in Python 3.9. Only solution I found so far is to remove the `mlruns/` directory as there is some permission issue with unfinished runs, it appears.
However I cannot always do it as, e.g., I have another training in progress while wanting to debug code that is not always running/completing successfully.

Is this a known issue with some known fix?

### Tracking information

MLflow version: 1.27.0
Tracking URI: file:///home/local/dev/mlruns
Artifact URI: file:///workspace/mlruns/0/5b986cb300594fe2b2730742acf6953a/artifacts

### Code to reproduce issue

Cannot disclose code.

### Stack trace

```python
  File "/home/local/mambaforge3/envs/tf_dev/lib/python3.9/site-packages/mlflow/tracking/fluent.py", line 846, in log_dict
    MlflowClient().log_dict(run_id, dictionary, artifact_file)
  File "/home/local/mambaforge3/envs/tf_dev/lib/python3.9/site-packages/mlflow/tracking/client.py", line 1094, in log_dict
    json.dump(dictionary, f, indent=2)
  File "/home/local/mambaforge3/envs/tf_dev/lib/python3.9/contextlib.py", line 126, in __exit__
    next(self.gen)
  File "/home/local/mambaforge3/envs/tf_dev/lib/python3.9/site-packages/mlflow/tracking/client.py", line 1020, in _log_artifact_helper
    self.log_artifact(run_id, tmp_path, artifact_dir)
  File "/home/local/mambaforge3/envs/tf_dev/lib/python3.9/site-packages/mlflow/tracking/client.py", line 955, in log_artifact
    self._tracking_client.log_artifact(run_id, local_path, artifact_path)
  File "/home/local/mambaforge3/envs/tf_dev/lib/python3.9/site-packages/mlflow/tracking/_tracking_service/client.py", line 365, in log_artifact
    artifact_repo.log_artifact(local_path, artifact_path)
  File "/home/local/mambaforge3/envs/tf_dev/lib/python3.9/site-packages/mlflow/store/artifact/local_artifact_repo.py", line 37, in log_artifact
    mkdir(artifact_dir)
  File "/home/local/mambaforge3/envs/tf_dev/lib/python3.9/site-packages/mlflow/utils/file_utils.py", line 119, in mkdir
    raise e
  File "/home/local/mambaforge3/envs/tf_dev/lib/python3.9/site-packages/mlflow/utils/file_utils.py", line 116, in mkdir
    os.makedirs(target)
  File "/home/local/mambaforge3/envs/tf_dev/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/local/mambaforge3/envs/tf_dev/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/local/mambaforge3/envs/tf_dev/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  [Previous line repeated 1 more time]
  File "/home/local/mambaforge3/envs/tf_dev/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/workspace'
python-BaseException

Process finished with exit code 130 (interrupted by signal 2: SIGINT)
```

### Other info / logs

I run MLflow locally on a Linux desktop machine for debugging experimental code in Tensorflow. The issue appears when terminating abruptly previous runs.

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
Do you have permission to create `/workspace`?

**Comment by VC86** [comment]
@harupy  I did not pick `/workspace` as default destination (presumably for artifacts since the Artifact URI is `file:///workspace/mlruns/0/5b986cb300594fe2b2730742acf6953a/artifacts`). Indeed, user has no permissions to write to `/workspace` or to create `/workspace`, but it is unclear why this error happens only when another run has started and was terminated before completing. So I would still consider it an issue with the defaults of MLflow, or at least (admitting that it is not a bug), a question -- how does one specify artifact URI destinations different than the default reported above?

**Comment by harupy** [comment]
> I did not pick /workspace as destination

Can you open `/home/local/dev/mlruns/0/meta.yaml` and what the value of `artifact_location` is?

> how does one specify artifact URI destinations different than the default reported above?

To use a different artifact URI, you need to create a new experiment with `mlflow.create_experiment` ([doc](https://www.mlflow.org/docs/latest/python_api/mlflow.html#mlflow.create_experiment)).

**Comment by VC86** [comment]
@harupy thanks for your prompt feedback.
Sure:
```yaml
artifact_location: file:///workspace/mlruns/0
experiment_id: '0'
lifecycle_stage: active
name: Default
```

However I normally run my code under a second experiment
```yaml
artifact_location: file:///workspace/mlruns/1
experiment_id: '1'
lifecycle_stage: active
name: CannotDisclose
```

Perhaps I am missing out on what the sense of having multiple runs on the same experiment is?

I set the experiment explicitly in my training script:
```python
    # MLFlow Logging
    mlflow.set_experiment("CannotDisclose")
    with mlflow.start_run(run_name=f"{model_type}-{tstamp}-{config_md5}"):
         # ...
```

**Comment by harupy** [comment]
@VC86 

```python
with mlflow.start_run():
    assert mlflow.get_artifact_ur().startswith("file:///workspace/mlruns")
    mlflow.log_artifact(__file__)
```

Does this code run successfully?

**Comment by VC86** [comment]
Nope, this:

```python
import mlflow

with mlflow.start_run():
    assert mlflow.get_artifact_uri().startswith("file:///workspace/mlruns")
    mlflow.log_artifact(__file__)
```

yields:

```python
/home/localuser/mambaforge3/envs/tf_dev/bin/python /home/localuser/pycharm-community-2022.1.3/plugins/python-ce/helpers/pydev/pydevd.py --multiprocess --qt-support=auto --client 127.0.0.1 --port 34405 --file /home/localuser/dev/rgbd_fusion_mltools/test.py
Connected to pydev debugger (build 221.5921.27)
Traceback (most recent call last):
  File "/home/localuser/dev/rgbd_fusion_mltools/test.py", line 5, in <module>
    mlflow.log_artifact(__file__)
  File "/home/localuser/mambaforge3/envs/tf_dev/lib/python3.9/site-packages/mlflow/tracking/fluent.py", line 752, in log_artifact
    MlflowClient().log_artifact(run_id, local_path, artifact_path)
  File "/home/localuser/mambaforge3/envs/tf_dev/lib/python3.9/site-packages/mlflow/tracking/client.py", line 955, in log_artifact
    self._tracking_client.log_artifact(run_id, local_path, artifact_path)
  File "/home/localuser/mambaforge3/envs/tf_dev/lib/python3.9/site-packages/mlflow/tracking/_tracking_service/client.py", line 365, in log_artifact
    artifact_repo.log_artifact(local_path, artifact_path)
  File "/home/localuser/mambaforge3/envs/tf_dev/lib/python3.9/site-packages/mlflow/store/artifact/local_artifact_repo.py", line 37, in log_artifact
    mkdir(artifact_dir)
  File "/home/localuser/mambaforge3/envs/tf_dev/lib/python3.9/site-packages/mlflow/utils/file_utils.py", line 119, in mkdir
    raise e
  File "/home/localuser/mambaforge3/envs/tf_dev/lib/python3.9/site-packages/mlflow/utils/file_utils.py", line 116, in mkdir
    os.makedirs(target)
  File "/home/localuser/mambaforge3/envs/tf_dev/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/localuser/mambaforge3/envs/tf_dev/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/localuser/mambaforge3/envs/tf_dev/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  [Previous line repeated 1 more time]
  File "/home/localuser/mambaforge3/envs/tf_dev/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/workspace'
python-BaseException
```

**Comment by harupy** [comment]
@VC86 Are you sure this issue occurs only when the last run didn't terminate properly?

**Comment by VC86** [comment]
@harupy 
1. Yes, I am sure. I reran the minimal example you provided and indeed, if the run terminates properly the assertion fails. This is because the artifact URI (when, e.g., deleting the `mlruns/` folder in the current directory and "starting from scratch") is then `file:///home/localuser/dev/mlruns/0/b59819c7deb14880b7168f91f857f224/artifacts` for example, instead of `file:///workspace/mlruns/0/ea5634b7b072420f89415601b091189d/artifacts` which happens when the previous run was not correctly terminated.

**Comment by harupy** [comment]
> This is because the artifact URI (when, e.g., deleting the mlruns/ folder in the current directory and "starting from scratch") is then file:///home/localuser/dev/mlruns/0/b59819c7deb14880b7168f91f857f224/artifacts for example, instead of file:///workspace/mlruns/0/ea5634b7b072420f89415601b091189d/artifacts which happens when the previous run was not correctly terminated.

This is strange. I have no clue why this happens. Can you create a script that can this behavior?

**Comment by thethiny** [comment]
I also faced the same issue with `/workspace`. For some reason this location just refuses to work. My setup involved docker. The solution for me was to use `/opt/workspace/` or literally any other workspace location. However it seems to me that your error is that `workspace` is not created by you, therefore can you print your `env` and show us the contents?

**Comment by VC86** [comment]
@thethiny thanks, can I ask you how do you set your `/workspace` to `/opt/workspace/`? This is not yet clear to me...

**Comment by VC86** [comment]
@harupy I will try, unfortunately the script is full of confidential information. I tried to create one minimal working example with your code snippet. It shows the error but only after the other script has failed to terminate properly (i.e., I halt execution in PyCharm).

**Comment by harupy** [comment]
@VC86 Can you check the value of the `MLFLOW_TRACKING_URI` environment variable when the script succeeds and doesn't?

**Comment by ridhwan-saal** [comment]
> @thethiny thanks, can I ask you how do you set your `/workspace` to `/opt/workspace/`? This is not yet clear to me...

As I said I'm running in docker therefore I Change dockerfile Workdir

**Comment by VC86** [comment]
Right, makes sense thanks.
I have the current issue on a system where I develop "interactively", i.e., including line-by-line debugging, eager execution in TF, etc.
Great to know docker has a workaround, do you have anything in mind to work around this without virtualization?

**Comment by VC86** [comment]
@harupy my environment as per `os.environ` is:
```console
('PATH', '/home/localuser/mambaforge3/envs/tf_dev/bin:/home/localuser/mambaforge3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin')
('LC_MEASUREMENT', 'nl_BE.UTF-8')
('XMODIFIERS', '@im=ibus')
('LC_TELEPHONE', 'nl_BE.UTF-8')
('XDG_DATA_DIRS', '/usr/share/gnome:/usr/local/share:/usr/share:/var/lib/snapd/desktop')
('LC_TIME', 'nl_BE.UTF-8')
('CONDA_DEFAULT_ENV', 'tf_dev')
('GTK_IM_MODULE', 'ibus')
('CONDA_PYTHON_EXE', '/home/localuser/mambaforge3/bin/python')
('DBUS_SESSION_BUS_ADDRESS', 'unix:path=/run/user/204606123/bus')
('CONDA_PREFIX', '/home/localuser/mambaforge3/envs/tf_dev')
('XDG_CURRENT_DESKTOP', 'GNOME')
('XRDP_SOCKET_PATH', '/run/xrdp/sockdir')
('SSH_AGENT_PID', '3667')
('KRB5CCNAME', 'FILE:/tmp/krb5cc_204606123_wCdhW7')
('XRDP_PULSE_SOURCE_SOCKET', 'xrdp_chansrv_audio_in_socket_10')
('COLORTERM', 'truecolor')
('LD_LIBRARY_PATH', '/home/localuser/mambaforge3/envs/tf_dev/lib')
('LC_PAPER', 'nl_BE.UTF-8')
('SESSION_MANAGER', 'local/AUTOMOTIV-DT2:@/tmp/.ICE-unix/3930,unix/AUTOMOTIV-DT2:/tmp/.ICE-unix/3930')
('LOGNAME', 'localuser')
('PWD', '/home/localuser/dev/')
('PYCHARM_HOSTED', '1')
('PYTHONPATH', '/home/localuser/dev/')
('SHELL', '/bin/bash')
('LESSOPEN', '| /usr/bin/lesspipe %s')
('LC_ADDRESS', 'nl_BE.UTF-8')
('GNOME_DESKTOP_SESSION_ID', 'this-is-deprecated')
('UID', '204606123')
('GNOME_TERMINAL_SCREEN', '/org/gnome/Terminal/screen/1744a9ce_8c30_4f65_a927_a9f01a6d20d4')
('GTK_MODULES', 'gail:atk-bridge')
('CLUTTER_IM_MODULE', 'ibus')
('CONDA_PROMPT_MODIFIER', '(tf_dev) ')
('SYSTEMD_EXEC_PID', '3962')
('LS_COLORS', 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:')
('SHLVL', '0')
('LC_IDENTIFICATION', 'nl_BE.UTF-8')
('LESSCLOSE', '/usr/bin/lesspipe %s %s')
('LC_MONETARY', 'nl_BE.UTF-8')
('QT_IM_MODULE', 'ibus')
('CONDA_EXE', '/home/localuser/mambaforge3/bin/conda')
('TERM', 'xterm-256color')
('GNOME_TERMINAL_SERVICE', ':1.95')
('LANG', 'en_US.UTF-8')
('XDG_SESSION_TYPE', 'x11')
('DISPLAY', ':10.0')
('_CE_M', '')
('PULSE_SCRIPT', '/etc/xrdp/pulse/default.pa')
('LC_NAME', 'nl_BE.UTF-8')
('CONDA_SHLVL', '2')
('XRDP_SESSION', '1')
('XDG_SESSION_CLASS', 'user')
('_', '/home/localuser/pycharm-community-2022.1.3/bin/pycharm.sh')
('PYTHONIOENCODING', 'UTF-8')
('GPG_AGENT_INFO', '/run/user/204606123/gnupg/S.gpg-agent:0:1')
('USER', 'localuser')
('XDG_MENU_PREFIX', 'gnome-')
('VTE_VERSION', '6800')
('QT_ACCESSIBILITY', '1')
('LC_NUMERIC', 'nl_BE.UTF-8')
('SSH_AUTH_SOCK', '/run/user/204606123/keyring/ssh')
('_CE_CONDA', '')
('PYTHONUNBUFFERED', '1')
('XRDP_PULSE_SINK_SOCKET', 'xrdp_chansrv_audio_out_socket_10')
('XDG_RUNTIME_DIR', '/run/user/204606123')
('HOME', '/home/localuser')
('TF2_BEHAVIOR', '1')
```

I actually don't see any environment variable being set there, and I've obtained this after `mlflow.start_run()` and right before `mlflow.log_dict()`, whose first call breaks execution as it is the first artifact being logged.
I will remark -- if I comment the `log_dict` call and wait for the epoch artifacts to be generated (I dump images at every end of epoch) then the execution stops when an artifact is logged (as we established, permission issues with creating this `/workspace` folder)

**Comment by thethiny** [comment]
```
MLflow version: 1.27.0
Tracking URI: file:///home/local/dev/mlruns
Artifact URI: file:///workspace/mlruns/0/5b986cb300594fe2b2730742acf6953a/artifacts
```

Can I understand why you are using Artifact URI to /workspace? Also try to use the Tracking URI as a path and not a URI, as in /home/local/dev/mlruns? Also can you share the command you're using to run?
`mlflow server` or `mlflow ui`? Finally, can you share your `mlflow run` command or `python file.py`? I would like to get as much information as I can to help you sustain the issue.

**Comment by harupy** [comment]
`mlflow server` or `mlflow ui` looks suspicious:

```
mlflow server --default-artifact-root file:///workspace/mlruns
```

generates `meta.yaml` that looks like:

```
artifact_location: file:///workspace/mlruns/0
experiment_id: '0'
lifecycle_stage: active
name: Default
```

which looks the same as the one in https://github.com/mlflow/mlflow/issues/6515#issuecomment-1220557434.

**Comment by thethiny** [comment]
> `mlflow server` or `mlflow ui` looks suspicious.
> 
> ```
> mlflow server --default-artifact-root file:///workspace/mlruns
> ```
> 
> generates `meta.yaml` that looks like:
> 
> ```
> artifact_location: file:///workspace/mlruns/0
> experiment_id: '0'
> lifecycle_stage: active
> name: Default
> ```
> 
> which looks the same as the one in [#6515 (comment)](https://github.com/mlflow/mlflow/issues/6515#issuecomment-1220557434).
> 
> If you create a new experiment on this tracking server (without specifying `artifact_uri`), that experiment would also have `file:///workspace/mlruns/0`. Here an example:
> 
> ```python
> mlflow.set_tracking_uri("http://localhost:5000")
> mlflow.set_experiment(uuid.uuid4().hex)  # create a new experiment and use it
> ```

What's the command you use to run this? If I run this using `mlflow run` I face an error that the experiment is not the same as the experiment ID, use CLI instead.

**Comment by harupy** [comment]
I don't use `mlflow run`. I just created a python script and ran it.

**Comment by thethiny** [comment]
> `python example.py` (updated the comment). I don't use `mlflow run`.

`mlflow run` is probably the worst thing that is provided by MLFlow. Everything else is fine. I vote to remove this feature completely.

**Comment by VC86** [comment]
@thethiny I'd like to point out that I am **not actively setting any URI**, I'm just using the default URIs of MLflow Tracking API. I never `set_tracking_uri()` anywhere, nor set the artifacts' URI to a non-default location. The `/workspace` write attempt appears in the event that the previous training didn't complete and was terminated (the process was killed, for example). 
I just run my training script, which is basically (editing out some relatively sensitive code parts):
```python
import argparse
import datetime
import hashlib
import json
import os
import time
import logging

import tensorflow as tf
import mlflow

logging.getLogger("mlflow").setLevel(logging.DEBUG)

def training():
    # Load dataset info, etc. ...
    # ...

    # MLFlow Logging
    mlflow.set_experiment("ML-based RGB-D Fusion Models")
    with mlflow.start_run(run_name=f"{model_type}-{tstamp}-{config_md5}"):
        # Setup training
        mlflow.log_param("epochs", max_epochs)
        mlflow.log_param("batch_size", batch_size)
        mlflow.log_param("initial_lr", default_lr)
        mlflow.log_param("train_dataset_size", train_dataset_size * batch_size)
        mlflow.log_param("valid_dataset_size", valid_dataset_size * batch_size)
        mlflow.log_dict(config, "config.json")  # this statement or any artifact logging statement breaks execution

        # Training
        # model.fit(...)

        # MLflow h5 weights
        mlflow.log_artifact(saved_weights_path, "model")

if __name__ == "__main__":
    training()
    exit(0)
```

I normally use `mlflow` through `mlflow ui` using the default address and port to monitor ongoing trainings that run indepedently via standard Python console.

@thethiny I can share relevant parts of the script, suitably anonymized and focusing on the `mlflow` commands -- but believe me it's not much more than what you see above...

**Comment by harupy** [comment]
@VC86 Can you try this?

1. Delete the `mlruns` directory in the current working directory?
2. Run the script
3. Open `mlruns/1/meta.yaml` and check the `artifact_location` value
4. Terminate the script
5. Open `mlruns/1/meta.yaml` and check the `artifact_location` value

?

**Comment by VC86** [comment]
Oups I should have edited out the name of the experiment -.- (sorry @harupy )

```yaml
artifact_location: file:///workspace/mlruns/1
experiment_id: '1'
lifecycle_stage: active
name: My Experiments
```

The artifact location reported in that `mlruns/1/meta.yaml` is indeed `file:///workspace/mlruns/1`. Terminating doesn't change it. However for the actual run there is also an own `meta.yaml` with content (for, e.g., run `d2b444572f22439e9403ddc41c40b570` in `mlruns/1/d2b444572f22439e9403ddc41c40b570`)
```yaml
artifact_uri: file:///home/localuser/dev/mlruns/1/d2b444572f22439e9403ddc41c40b570/artifacts
end_time: null
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: d2b444572f22439e9403ddc41c40b570
run_uuid: d2b444572f22439e9403ddc41c40b570
source_name: ''
source_type: 4
source_version: ''
start_time: 1661016888328
status: 1
tags: []
user_id: localuser
```

**Comment by harupy** [comment]
@VC86 Did you run the script in `/workspace`? Are you using `mlflow run?

**Comment by harupy** [comment]
I found the following command in https://github.com/mlflow/mlflow/issues/6515#issuecomment-1220735269:

```
pydevd.py --multiprocess --qt-support=auto --client 127.0.0.1 --port 34405 --file /home/localuser/dev/test.py
```

**Comment by VC86** [comment]
@harupy yes, I run the script via PyCharm as it is our IDE of choice. 
I will look into running the script off-IDE to see if it solves the issue.
Thanks!

**Comment by harupy** [comment]
@VC86 Any updates here?

**Comment by thethiny** [comment]
@VC86 try to reset your database or change your store location and run. I believe they when the db is reused the workspace gets corrupted. I tried it here and surely enough a 2nd run is weird.

**Comment by VC86** [comment]
I currently put a "patch" on the issue by `find -name "meta.yaml" -maxdepth 4 -print0 | xargs -0 sed -i 's/workspace/other_artifacts_location/g'>` so that I basically replace forcefully `/workspace` on all runs in the `mlruns/` folder. But this is not a permanent solution.

I haven't had the time to run the script off of PyCharm.

**Comment by harupy** [comment]
@VC86 Got it. Can you check where PyCharm runs your script by printing out `os.getcwd()`?

**Comment by harupy** [comment]
@VC86 Any updates?
