### ISSUE TITLE
[BUG] CLI Arguments do not match Python API environment and they have higher precedence  when they should not

### ISSUE THREAD

**Issue by ghost** [mlflow/mlflow#6519]
### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

1.28.0

### System information

- Ubuntu 20.04
- Python 3.9.0

### Describe the problem

NOTE: This BUG references #4830 due to the similar behavior.

There seems to be a bug in the CLI vs API configuration.
Scenario 1:
You have `main.py` that has `set_experiment` function call. Example:
`mlflow.set_experiment("my-experiment")`
Running the file using `python main.py` will correctly run and set the experiment.

Scenario 2:
You have `main.py` that has `set_tracking_uri`. Example:
`mlflow.set_tracking_uri("http://localhost:5000")`
Running the file using `python main.py` will correctly run and set the tracking url.

Scenario 3:
Using the same file in Scenario 1:
Running the file using `mlflow run /path/to/project` will give an error
```
Cannot start run with ID {} because active run ID does not match environment run ID. Make sure --experiment-name or --experiment-id matches experiment set with set_experiment(), or just use command-line
```
Running the file using `mlflow run /path/to/project --experiment-name my-experiment` works.
We note from this Scenario that there is an override happening here where the CLI's default experiment name `Default` is overriding the python API call to `set_experiment`. Usually CLI commands should override the code, but in this scenario the CLI command was NOT passed, therefore the API should override.

Scenario 4:
Using the same file as Scenario 2:
Running the file using `mlflow run /path/to/project/` will give an error
```
mlflow.exceptions.RestException: RESOURCE_DOES_NOT_EXIST: Run with id={} not found
```
There is no CLI argument to pass the tracking_uri therefore this scenario will NEVER work, thus creating a huge bug in the API. Current workaround envolves the use of environment variables, but this behavior completely eliminates the API `set_tracking_uri` as it simply cannot be used.

Potential fixes include either giving the API higher priority over the CLI (with a warning that CLI and API override) or to add a parameter `tracking-uri` to the `run` command to allow user to pass tracking URI.

I have added tracking uri to the cli as a proposed fix for Scenario 4 (but not 3 as that requires major changes to the API). The fix is found as PR #6518

### Code to reproduce issue

See above

### Stack trace

See above

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [X] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [X] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [x] `area/server-infra`: MLflow Tracking server backend
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations
