### ISSUE TITLE
[BUG] Cannot delete experiments with deleted runs

### ISSUE THREAD

**Issue by nsantavas** [mlflow/mlflow#6606]
### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

1.27.0

### System information

- **OS Platform and Distribution**: Ubuntu 20.04
- **Python version**: 3.8

### Describe the problem

I am trying to delete experiments, using both the UI and the client, but I am getting the following error ``` INVALID_PARAMETER_VALUE: The run 39a47c2a9df849b2b8a3b210da5478b4 must be in the 'active' state. Current state is deleted.```. This happens only with experiments that I have deleted individual runs, in fact even if I delete a single run, the experiment cannot be deleted later. What I've found is that if I restore the deleted runs, then I am able to remove the experiment.

### Code to reproduce issue

-

### Stack trace

```
INVALID_PARAMETER_VALUE: The run 39a47c2a9df849b2b8a3b210da5478b4 must be in the 'active' state. Current state is deleted.
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [X] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dbczumar** [comment]
@nsantavas Thank you for pointing this out. This is definitely a bug, and we are working on a fix.

**Comment by dbczumar** [comment]
Filed https://github.com/mlflow/mlflow/pull/6641 to address this issue. Once merged, it will be included in the MLflow 1.29.0 release in a couple of weeks :)

**Comment by jseia** [comment]
I'm facing this same issue, using last version of MLFlow. I have an experiment with no runs inside (they have been deleted from the user interface) and when I run the delete_experiment from my python script (with the right experiment ID, I can access the Experiment object correctly), it fails giving me the same error:

RestException: INVALID_PARAMETER_VALUE: The run 0887ce65a33c46a0839dad747f8c72ac must be in the 'active' state. Current state is deleted.

mlflow version: 2.9.2
python version: 3.9.18
