### ISSUE TITLE
[FR]

### ISSUE THREAD

**Issue by hemanth-marukala** [mlflow/mlflow#6609]
### Willingness to contribute

Yes. I would be willing to contribute this feature with guidance from the MLflow community.

### Proposal Summary

Use Vertica database as a MLFlow tracking server to store the experiment parameters, model versions and other metrics. 

Vertica has an sql alchemy dialect(https://pypi.org/project/sqlalchemy-vertica-python/) that we can use to connect to the database. Vertica has in-database machine learning capability and it also has Verticapy python library which has scikit like functionality to conduct data science projects on data stored in Vertica (Without moving the data out of Vertica). 

Ml flow can be used to track the performance and other parameters of the in-database ML models.  

### Motivation

> #### What is the use case for this feature?
To use Vertica DB as a tracking server for the ML models inside Vertica DB. 

> #### Why is this use case valuable to support for MLflow users in general?
Vertica can perform analytics very fast(MPP architecture). Having Vertica as a tracking server will help MLfow users to perform analytics on their experiment data and make better decision on choosing the ML model for production. 
> #### Why is this use case valuable to support for your project(s) or organization?
Vertica customer who are in the MLOps domain would like to store the experiment parameters metrics and versions when developing/ training ML models inside Vertica using verticapy python library.
> #### Why is it currently difficult to achieve this use case?
Currently Vertica is not supported as a tracking server. 

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [X] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by hemanth-marukala** [comment]
I have tried updating the code to include "vertica"/"vertica+vertica_python" to the db_types.py file but it creates a directory locally. 
**Here is the command i trying to execute:**

mlflow server --backend-store-uri vertica://dbadmin:password@x.x.x.x:5433/VMart --default-artifact-root sftp://dbadmin:password@x.x.x.x:~/mlflow/mlruns --host 0.0.0.0 -p 8000

**Here is the error log:**
mlflow/mlruns --host 0.0.0.0 -p 8000
2022/08/23 14:18:34 ERROR mlflow.cli: Error initializing backend store
2022/08/23 14:18:34 ERROR mlflow.cli: Can't load plugin: sqlalchemy.dialects:vertica
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/mlflow/cli.py", line 461, in server
    initialize_backend_stores(backend_store_uri, registry_store_uri, default_artifact_root)
  File "/usr/local/lib/python3.8/dist-packages/mlflow/server/handlers.py", line 267, in initialize_backend_stores
    _get_tracking_store(backend_store_uri, default_artifact_root)
  File "/usr/local/lib/python3.8/dist-packages/mlflow/server/handlers.py", line 246, in _get_tracking_store
    _tracking_store = _tracking_store_registry.get_store(store_uri, artifact_root)
  File "/usr/local/lib/python3.8/dist-packages/mlflow/tracking/_tracking_service/registry.py", line 39, in get_store
    return self._get_store_with_resolved_uri(resolved_store_uri, artifact_uri)
  File "/usr/local/lib/python3.8/dist-packages/mlflow/tracking/_tracking_service/registry.py", line 49, in _get_store_with_resolved_uri
    return builder(store_uri=resolved_store_uri, artifact_uri=artifact_uri)
  File "/usr/local/lib/python3.8/dist-packages/mlflow/server/handlers.py", line 114, in _get_sqlalchemy_store
    return SqlAlchemyStore(store_uri, artifact_uri)
  File "/usr/local/lib/python3.8/dist-packages/mlflow/store/tracking/sqlalchemy_store.py", line 125, in __init__
    ] = mlflow.store.db.utils.create_sqlalchemy_engine_with_retry(db_uri)
  File "/usr/local/lib/python3.8/dist-packages/mlflow/store/db/utils.py", line 166, in create_sqlalchemy_engine_with_retry
    engine = create_sqlalchemy_engine(db_uri)
  File "/usr/local/lib/python3.8/dist-packages/mlflow/store/db/utils.py", line 202, in create_sqlalchemy_engine
    return sqlalchemy.create_engine(db_uri, pool_pre_ping=True, **pool_kwargs)
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/deprecations.py", line 309, in warned
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/create.py", line 522, in create_engine
    entrypoint = u._get_entrypoint()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/url.py", line 655, in _get_entrypoint
    cls = registry.load(name)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/langhelpers.py", line 343, in load
    raise exc.NoSuchModuleError(
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:vertica

**Comment by dbczumar** [comment]
Hi @hemanth-marukala, can you try installing https://pypi.org/project/sqlalchemy-vertica/ and running your `mlflow server` command again?

**Comment by hemanth-marukala** [comment]
Hello dbczumar, 

I already have installed sqlalchemy-vertica and i have also tried copying the files under the dielect directory, modifies the __init__.py to add vertica

dbadmin@dbadmin-virtual-machine:/usr/local/lib/python3.8/dist-packages/sqlalchemy/dialects$ ls
firebird  **__init__.py**  mssql  mysql  oracle  postgresql  __pycache__  sqlite  sybase  **vertica**
dbadmin@dbadmin-virtual-machine:/usr/local/lib/python3.8/dist-packages/sqlalchemy/dialects$ cd vertica/
dbadmin@dbadmin-virtual-machine:/usr/local/lib/python3.8/dist-packages/sqlalchemy/dialects/vertica$ ls
base.py  dialect_pyodbc.py  dialect_vertica_python.py  __init__.py  __pycache__

Somehow i get the same No module error. Not sure if i am missing anything here.

**Comment by dbczumar** [comment]
Hmm...I'm unfortunately not quite sure what's going on here either, but it seems to be a Vertica + SQLAlchemy issue, rather than an MLflow issue. To confirm, did you try using `vertica+vertica_python://` as the scheme of your URI, rather than `vertica://`? If this still isn't working, I recommend filing an issue on the Vertica GitHub repository. Happy to reopen this if there's an identifiable MLflow-related issue / cause here. Thank you for using MLflow!
