### ISSUE TITLE
[FR] Log HTML representation of estimator in scikit-learn autologging

### ISSUE THREAD

**Issue by harupy** [mlflow/mlflow#6758]
### Willingness to contribute

No. I cannot contribute this feature at this time.

### Proposal Summary

Log an HTML representation of an estimator in scikit-learn autologging using [`sklearn.utils.estimator_html_repr`](https://scikit-learn.org/stable/modules/generated/sklearn.utils.estimator_html_repr.html#sklearn.utils.estimator_html_repr).

<img width="1166" alt="image" src="https://user-images.githubusercontent.com/17039389/189557559-d7c87334-d9a5-4b84-a05b-870c7bbb59fc.png">

### Motivation

> #### What is the use case for this feature?

To make it easier to understand the structure of a auto-logged estimator.

> #### Why is this use case valuable to support for MLflow users in general?

> #### Why is this use case valuable to support for your project(s) or organization?

> #### Why is it currently difficult to achieve this use case?

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@shraddhafalane Thanks! We can make a change like this:

```diff
diff --git a/mlflow/sklearn/utils.py b/mlflow/sklearn/utils.py
index 604407112..656faf092 100644
--- a/mlflow/sklearn/utils.py
+++ b/mlflow/sklearn/utils.py
@@ -553,6 +553,24 @@ def _log_specialized_estimator_content(
     return metrics
 
 
+def _log_estimator_html(run_id, estimator):
+    from sklearn.utils import estimator_html_repr
+
+    # Set charset to prevent the triangle toggle buttons from being garbled
+    estimator_html = f"""
+<!DOCTYPE html>
+<html lang="en">
+  <head>
+    <meta charset="UTF-8" />
+  </head>
+  <body>
+    {estimator_html_repr.estimator_html_repr(estimator)}
+  </body>
+</html>
+"""
+    MlflowClient().log_text(run_id, estimator_html, artifact_file="estimator.html")
+
+
 def _log_estimator_content(
     autologging_client,
     estimator,
@@ -614,6 +632,8 @@ def _log_estimator_content(
             autologging_client.log_metrics(run_id=run_id, metrics={score_key: score})
             metrics[score_key] = score
 
+    _log_estimator_html(run_id, estimator)
+
     return metrics
```

**Comment by harupy** [comment]
@RohanBha1 Is this issue something you'd be interested in working on?

**Comment by RohanBha1** [comment]
Sure that works for me, sorry on the late response, won't happen again

**Comment by harupy** [comment]
@RohanBha1 Assigned!

**Comment by harupy** [comment]
@RohanBha1 Any updates for this issue?

**Comment by RohanBha1** [comment]
Yes, I'll be done by tonight, sorry haven't updated in a while.

**Comment by RohanBha1** [comment]
Hey @harupy I had a few questions about what I'm supposed to do. Does this task involve making both the changes shown above, or just the lower one? In addition, what does "+    # Set charset to prevent the triangle toggle buttons from being garbled" mean, and what do I do about that?

**Comment by harupy** [comment]
@RohanBha1

> Does this task involve making both the changes shown above

Yes :)

**Comment by RohanBha1** [comment]
@harupy Thank you so much for the clarification, that makes much more sense. Is that what:


+<!DOCTYPE html>
+<html lang="en">
+  <head>
**+    <meta charset="UTF-8" />**
+  </head>
+  <body>
+    {estimator_html_repr.estimator_html_repr(estimator)}
+  </body>
+</html>

the bolded line above is doing, or would I need to add anything else to it?

**Comment by RohanBha1** [comment]
@harupy Thank you so much for the clarification, it makes much more sense now. Since this project is likely in UTF-8, would the line  "<meta charset="UTF-8" />  "    do the necessary specification, or would I need to add anything else besides that?

**Comment by RohanBha1** [comment]
@harupy Thank you so much for the clarification, it makes much more sense now. Since this project is likely in UTF-8, would the line 

`<meta charset="UTF-8" />  
`

do the necessary specification, or would I need to add anything else besides that?

**Comment by harupy** [comment]
Yes, it does.

**Comment by RohanBha1** [comment]
@harupy got it, thank you so much. So I looked through some of the other files and I think I have a good understanding of the actual changes made in the first part, please correct me if any of it seems incorrect: The first line defines the new function, then the estimator_html_repr function is imported from sklearn.utils. Then estimator_html is set to be an f-string and since """ is used every new line in the code will be a new line in the f-string, the contents of the f-string are the normal html headings, and the charset must be specified as UTF-8 so that the triangle buttons don't get garbled, then in the body since it is an f-string, the stuff in {} are found before the string itself so this calls the estimator_html_repr function and the body for the estimator is added to the body of the f-string. Then the f-string ends, and the estimator_html string is written in the autologger.

I do have a few questions though, such as how does autologging this html representation of the estimator benefit users? I might just be misunderstanding what autologging is. If you could elaborate on this topic a little that would be amazing.

Finally, could you tell me a little more about the testing in the second code snippet above. I get the first line is starting the autologger and the upcoming run is defined as run, but the next line completely loses me. Finally, using the run_id of the estimator from the first snippet, an array called artifact is called, and it is checked if the estimator is in that array. I feel like my understanding is pretty flawed, so if you could explain the testing that would be amazing.

Sorry for the longer question, I just want to make sure that I understand the contribution I am making. Thanks for all your help, its greatly appreciated.

**Comment by harupy** [comment]
@RohanBha1 

> how does autologging this html representation of the estimator benefit users?

The HTML representation allows users to understand what the estimator consists of quickly.

> could you tell me a little more about the testing in the second code snippet above

Sure!

```python
def test_estimator_html_is_logged():
    mlflow.sklearn.autolog()  # -> monkey patch sklearn.svm.SVC.fit
    with mlflow.start_run() as run:  # -> start a run
        sklearn.svm.SVC().fit(*get_iris())  # -> log params, metrics, and artifacts in the run
        artifacts = get_run_data(run.info.run_id)[3]  # -> Fetch the logged artifacts
        assert "estimator.html" in artifacts  # Ensure 'estimator.html' is logged as an artifact
```

**Comment by RohanBha1** [comment]
Hey @harupy sorry, I'm in Florida and we just got hit with a hurricane so my power is just coming back. I meant to ask the following a few days ago following our last conversation, but unfortunately given the hurricane I was unable.

Thank you so much for the continued explanation, I just had a few more questions about the estimator. I was looking through some of the scikit-learn documentation and found this:
<img width="992" alt="Screen Shot 2022-09-27 at 1 45 57 AM" src="https://user-images.githubusercontent.com/92875326/193399751-1285dfb4-e967-4875-a7e4-a822bf723bd6.png">

So from my understanding, the estimator is meant to be a model of some kind modeling the machine learning experiments that users perform using mlFlow. So is the thing labeled pipeline the estimator in the picture above? In addition, I read on the scikit-learn documentation that the HTML representation is automatically displayed, and I did not notice this being disabled anywhere. If the visualization is already displayed for the users to see, then how is copying the code for the visualization into the autologger beneficial for users? 

Again, I'm likely just misinterpreting something, I just want to fully wrap my head around the issue, and I really appreciate all your help in doing so.

As for the explanation of testing, thanks again for that it helped clarify everything.

**Comment by RohanBha1** [comment]
@harupy hey, I just made the according changes, should I make a PR for branch 2.0?

**Comment by harupy** [comment]
> the HTML representation is automatically displayed

If we log this HTML as a file, we can view in on MLflow UI.

**Comment by harupy** [comment]
You can file a PR against master.

**Comment by RohanBha1** [comment]
Let me know if I need to make any further changes
