### ISSUE TITLE
[BUG] mlflow.tensorflow.autolog cannot log custom object

### ISSUE THREAD

**Issue by anneadb** [mlflow/mlflow#6793]
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

1.28.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS 12.6
- **Python version**: 3.10
- **Tensorflow version**: 2.9.1

### Describe the problem

I'm trying to wrap the code used in this tensorflow tutorial https://www.tensorflow.org/tutorials/keras/text_classification into mlflow.

I am encountering the following issues:
- Metrics are logged correctly but no artifacts are logged.
- mlflow.pyfunc.load_model() is not aware of the custom objects I am using for my model.
    - In keras I can register these objects like this: 
    ```
    custom_objects = {"custom_standardization": custom_standardization}
    model: keras.Sequential = keras.models.load_model(
        os.path.join(MODEL_DIR, model_name),
        custom_objects=custom_objects,
    )
    ```
    but I do not see a similar option in the documentation for `autolog`
- `autolog` appears to have no write permissions for the folder it wants to write to. This seems strange because the run folder is created and metrics are written there.

### Tracking information

MLflow version: 1.28.0
Tracking URI: file:///Users/myusername/git/category-mapping/tutorials/mlflow/mlruns
Artifact URI: file://Users/myusername/git/category-mapping/tutorials/mlflow/mlruns/0/1b4fc9877e274c19ae04f7888582017a/artifacts

### Code to reproduce issue

```
import logging
import os

import mlflow

from tutorials.tf_basic_text_classification.tutorial import (
    create_model,
    create_vectorizer,
    custom_standardization,
    load_dataset,
    train_and_save_model,
)

logging.getLogger("mlflow").setLevel(logging.DEBUG)

SCRIPT_DIR = os.path.dirname(__file__)
mlflow.set_tracking_uri(f"file://{SCRIPT_DIR}/mlruns")
mlflow.set_experiment("tutorial")

ITERATION = 1
MODEL_NAME = f"model_{ITERATION}"
RUN_NAME = f"run_{ITERATION}"

mlflow.tensorflow.autolog(registered_model_name=MODEL_NAME)

if __name__ == "__main__":

    mlflow.start_run(run_name=RUN_NAME)

    raw_train_ds, raw_val_ds, raw_test_ds = load_dataset()
    vectorizer = create_vectorizer(raw_train_ds)
    model = create_model(vectorizer)
    history = train_and_save_model(MODEL_NAME, model, raw_train_ds, raw_val_ds)

    mlflow.end_run()
```

### Stack trace

```
2022/09/14 12:00:48 DEBUG mlflow.utils.autologging_utils: Called autolog() method for tensorflow autologging with args '()' and kwargs '{'every_n_iter': 1, 'log_models': True, 'disable': False, 'exclusive': False, 'disable_for_unsupported_versions': False, 'silent': False, 'registered_model_name': 'model_1', 'log_input_examples': False, 'log_model_signatures': False}'
Found 25000 files belonging to 2 classes.
Using 20000 files for training.
2022-09-14 12:00:50.512149: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Found 25000 files belonging to 2 classes.
Using 5000 files for validation.
Found 25000 files belonging to 2 classes.
Label 0 corresponds to neg
Label 1 corresponds to pos
Vocabulary sample: ['', '[UNK]', 'the', 'and', 'a', 'of', 'to', 'is', 'in', 'it', 'i', 'this', 'that', 'was', 'as', 'for', 'with', 'movie', 'but', 'film']
Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
=================================================================
 text_vectorization (TextVec  (None, 250)              0         
 torization)                                                     
                                                                 
 embedding (Embedding)       (None, 250, 16)           160016    
                                                                 
 dropout (Dropout)           (None, 250, 16)           0         
                                                                 
 global_average_pooling1d (G  (None, 16)               0         
 lobalAveragePooling1D)                                          
                                                                 
 dropout_1 (Dropout)         (None, 16)                0         
                                                                 
 dense (Dense)               (None, 1)                 17        
                                                                 
=================================================================
Total params: 160,033
Trainable params: 160,033
Non-trainable params: 0
_________________________________________________________________
None
2022/09/14 12:00:56 DEBUG mlflow.utils.autologging_utils: Invoked patched API '<class 'keras.engine.training.Model'>.fit' for tensorflow autologging with args '(<keras.engine.sequential.Sequential object at 0x123fccf40>, <BatchDataset element_spec=(TensorSpec(shape=(None,), dtype=tf.string, name=None), TensorSpec(shape=(None,), dtype=tf.int32, name=None))>)' and kwargs '{'validation_data': <BatchDataset element_spec=(TensorSpec(shape=(None,), dtype=tf.string, name=None), TensorSpec(shape=(None,), dtype=tf.int32, name=None))>, 'epochs': 2, 'callbacks': [<keras.callbacks.ModelCheckpoint object at 0x123fcfb50>]}'
2022/09/14 12:00:56 DEBUG mlflow.utils.autologging_utils: Original function invoked during execution of patched API '<class 'keras.engine.training.Model'>.fit' for tensorflow autologging. Original function was invoked with args '(<keras.engine.sequential.Sequential object at 0x123fccf40>, <BatchDataset element_spec=(TensorSpec(shape=(None,), dtype=tf.string, name=None), TensorSpec(shape=(None,), dtype=tf.int32, name=None))>)' and kwargs '{'validation_data': <BatchDataset element_spec=(TensorSpec(shape=(None,), dtype=tf.string, name=None), TensorSpec(shape=(None,), dtype=tf.int32, name=None))>, 'epochs': 2, 'callbacks': [<keras.callbacks.ModelCheckpoint object at 0x123fcfb50>, <mlflow.tensorflow._autolog._TensorBoard object at 0x123b32a70>, <mlflow.tensorflow._autolog.__MLflowTfKeras2Callback object at 0x123b33190>]}'
2022/09/14 12:00:56 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during autologging: [Errno 30] Read-only file system: '/myusername'
Epoch 1/2
621/625 [============================>.] - ETA: 0s - loss: 0.6653 - binary_accuracy: 0.6931  
Epoch 1: saving model to /Users/myusername/git/category-mapping/tutorials/tf_basic_text_classification/model/training_cp/cp.ckpt
625/625 [==============================] - 5s 7ms/step - loss: 0.6651 - binary_accuracy: 0.6938 - val_loss: 0.6166 - val_binary_accuracy: 0.7712
Epoch 2/2
621/625 [============================>.] - ETA: 0s - loss: 0.5503 - binary_accuracy: 0.7985  
Epoch 2: saving model to /Users/myusername/git/category-mapping/tutorials/tf_basic_text_classification/model/training_cp/cp.ckpt
625/625 [==============================] - 4s 7ms/step - loss: 0.5500 - binary_accuracy: 0.7986 - val_loss: 0.4994 - val_binary_accuracy: 0.8216
2022/09/14 12:01:06 DEBUG mlflow.utils.autologging_utils: Original function invocation completed successfully during execution of patched API call '<class 'keras.engine.training.Model'>.fit' for tensorflow autologging. Original function was invoked with with args '(<keras.engine.sequential.Sequential object at 0x123fccf40>, <BatchDataset element_spec=(TensorSpec(shape=(None,), dtype=tf.string, name=None), TensorSpec(shape=(None,), dtype=tf.int32, name=None))>)' and kwargs '{'validation_data': <BatchDataset element_spec=(TensorSpec(shape=(None,), dtype=tf.string, name=None), TensorSpec(shape=(None,), dtype=tf.int32, name=None))>, 'epochs': 2, 'callbacks': [<keras.callbacks.ModelCheckpoint object at 0x123fcfb50>, <mlflow.tensorflow._autolog._TensorBoard object at 0x123b32a70>, <mlflow.tensorflow._autolog.__MLflowTfKeras2Callback object at 0x123b33190>]}'
2022/09/14 12:01:15 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: /var/folders/3y/2phvw3b15d1c6h9p0723h_n00000gp/T/tmp5n91wuqv/model, flavor: keras), fall back to return ['tensorflow==2.9.1', 'keras==2.9.0']. Set logging level to DEBUG to see the full traceback.
2022/09/14 12:01:15 DEBUG mlflow.utils.environment: 
Traceback (most recent call last):
  File "/Users/myusername/git/category-mapping/.venv/lib/python3.10/site-packages/mlflow/utils/environment.py", line 378, in infer_pip_requirements
    return _infer_requirements(model_uri, flavor)
  File "/Users/myusername/git/category-mapping/.venv/lib/python3.10/site-packages/mlflow/utils/requirements_utils.py", line 345, in _infer_requirements
    modules = _capture_imported_modules(model_uri, flavor)
  File "/Users/myusername/git/category-mapping/.venv/lib/python3.10/site-packages/mlflow/utils/requirements_utils.py", line 266, in _capture_imported_modules
    _run_command(
  File "/Users/myusername/git/category-mapping/.venv/lib/python3.10/site-packages/mlflow/utils/requirements_utils.py", line 218, in _run_command
    raise MlflowException(msg)
mlflow.exceptions.MlflowException: Encountered an unexpected error while running ['/Users/myusername/git/category-mapping/.venv/bin/python', '/Users/myusername/git/category-mapping/.venv/lib/python3.10/site-packages/mlflow/utils/_capture_modules.py', '--model-path', '/var/folders/3y/2phvw3b15d1c6h9p0723h_n00000gp/T/tmp5n91wuqv/model', '--flavor', 'keras', '--output-file', '/var/folders/3y/2phvw3b15d1c6h9p0723h_n00000gp/T/tmp7ggbqvt3/imported_modules.txt', '--sys-path', '["/Users/myusername/git/category-mapping/tutorials/mlflow", "/Users/myusername/git/category-mapping/.venv/lib/python3.10/site-packages/git/ext/gitdb", "/Users/myusername/git/category-mapping", "/Users/myusername/.pyenv/versions/3.10.6/lib/python310.zip", "/Users/myusername/.pyenv/versions/3.10.6/lib/python3.10", "/Users/myusername/.pyenv/versions/3.10.6/lib/python3.10/lib-dynload", "/Users/myusername/git/category-mapping/.venv/lib/python3.10/site-packages", "/Users/myusername/git/category-mapping/.venv/lib/python3.10/site-packages/gitdb/ext/smmap"]']
exit status: 1
stdout: 
stderr: /Users/myusername/git/category-mapping/.venv/lib/python3.10/site-packages/mlflow/utils/_capture_modules.py:42: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
  return original(name, globals, locals, fromlist, level)
/Users/myusername/git/category-mapping/.venv/lib/python3.10/site-packages/keras/backend.py:450: UserWarning: `tf.keras.backend.set_learning_phase` is deprecated and will be removed after 2020-10-11. To update it, simply pass a True/False value to the `training` argument of the `__call__` method of your layer or model.
  warnings.warn('`tf.keras.backend.set_learning_phase` is deprecated and '
2022-09-14 12:01:15.058168: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "/Users/myusername/git/category-mapping/.venv/lib/python3.10/site-packages/mlflow/utils/_capture_modules.py", line 134, in <module>
    main()
  File "/Users/myusername/git/category-mapping/.venv/lib/python3.10/site-packages/mlflow/utils/_capture_modules.py", line 109, in main
    mlflow.pyfunc.load_model(model_path)
  File "/Users/myusername/git/category-mapping/.venv/lib/python3.10/site-packages/mlflow/pyfunc/__init__.py", line 756, in load_model
    model_impl = importlib.import_module(conf[MAIN])._load_pyfunc(data_path)
  File "/Users/myusername/git/category-mapping/.venv/lib/python3.10/site-packages/mlflow/utils/_capture_modules.py", line 106, in _load_pyfunc_patch
    return original(*args, **kwargs)
  File "/Users/myusername/git/category-mapping/.venv/lib/python3.10/site-packages/mlflow/keras.py", line 541, in _load_pyfunc
    m = _load_model(
  File "/Users/myusername/git/category-mapping/.venv/lib/python3.10/site-packages/mlflow/keras.py", line 486, in _load_model
    return keras_models.load_model(model_path, custom_objects=custom_objects, **kwargs)
  File "/Users/myusername/git/category-mapping/.venv/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/Users/myusername/git/category-mapping/.venv/lib/python3.10/site-packages/keras/utils/layer_utils.py", line 92, in validate_string_arg
    raise ValueError(
ValueError: Unkown value for `standardize` argument of layer TextVectorization. If restoring a model and `standardize` is a custom callable, please ensure the callable is registered as a custom object. See https://www.tensorflow.org/guide/keras/save_and_serialize#registering_the_custom_object for details. Allowed values are: `None`, a `Callable`, or one of the following values: ('lower_and_strip_punctuation', 'lower', 'strip_punctuation'). Received: custom_standardization

2022/09/14 12:01:15 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/Users/myusername/git/category-mapping/.venv/lib/python3.10/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils."
2022/09/14 12:01:15 DEBUG mlflow.utils.autologging_utils: Patched API call '<class 'keras.engine.training.Model'>.fit' for tensorflow autologging threw exception. Patched API was called with args '(<keras.engine.sequential.Sequential object at 0x123fccf40>, <BatchDataset element_spec=(TensorSpec(shape=(None,), dtype=tf.string, name=None), TensorSpec(shape=(None,), dtype=tf.int32, name=None))>)' and kwargs '{'validation_data': <BatchDataset element_spec=(TensorSpec(shape=(None,), dtype=tf.string, name=None), TensorSpec(shape=(None,), dtype=tf.int32, name=None))>, 'epochs': 2, 'callbacks': [<keras.callbacks.ModelCheckpoint object at 0x123fcfb50>]}'. Exception: [Errno 30] Read-only file system: '/myusername'
2022/09/14 12:01:15 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during tensorflow autologging: [Errno 30] Read-only file system: '/myusername'
```

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment]
Hi @anneadb the error that you're getting isn't an MLflow exception. It's an exception from Keras. 
Please see: https://github.com/tensorflow/tensorflow/issues/45231#issuecomment-799268188
and https://stackoverflow.com/questions/65050132/unable-to-restore-a-layer-of-class-textvectorization-text-classification
for guidance on correcting the issue.

**Comment by anneadb** [comment]
Hi @BenWilson2,
thanks for the helpful links but the solution displayed there is not working for my code with mlflow. As long as I do not integrate `mlflow.tensorflow.autolog` it runs fine, the source of the error appears to be `mlflow.pyfunc.load_model(model_path)`. After registering the custom function with the decorator the error message remains the same.

My error message is also slightly different than the given examples:
`ValueError: Unkown value for `standardize` argument of layer TextVectorization.` instead of `RuntimeError: Unable to restore a layer of class TextVectorization.`.

Since I am not that familiar with mlflow yet I'm having a really hard time debugging this. Do you have any other suggestions on what I could try?

**Comment by BenWilson2** [comment]
It looks like you're trying to implement a partial function approach for this model, right?
Is `standardize` a function that you're trying to pass in?
If the model you're building requires such an input then the standard flavor for TF in MLflow won't work since there are a limited set of types supported for input into the pyfunc implementation. 
How does this work without using autolog?

**Comment by anneadb** [comment]
The training code looks like this:

```
@keras.utils.register_keras_serializable()
def custom_standardization(input_data):
    lowercase = tf.strings.lower(input_data)
    stripped_html = tf.strings.regex_replace(lowercase, "<br />", " ")
    return tf.strings.regex_replace(stripped_html, "[%s]" % re.escape(string.punctuation), "")


def create_vectorizer(raw_train_ds) -> keras.layers.TextVectorization:
    sequence_length = 250

    vectorizer = keras.layers.TextVectorization(
        standardize=custom_standardization,
        max_tokens=MAX_FEATURES,
        output_mode="int",
        output_sequence_length=sequence_length,
    )

    # Make a text-only dataset (without labels), then call adapt
    # It's important to only use your training data when calling adapt (using the test set would leak information).
    train_text = raw_train_ds.map(lambda x, y: x)
    vectorizer.adapt(train_text)  # create the vocabulary
    print("Vocabulary sample: {}".format(vectorizer.get_vocabulary()[:20]))

    return vectorizer

def create_model(vectorizer: keras.layers.TextVectorization) -> keras.Sequential:
    embedding_dim = 16

    model = keras.Sequential(
        [
            keras.Input(shape=(1,), dtype=tf.string),
            vectorizer,
            keras.layers.Embedding(MAX_FEATURES + 1, embedding_dim),
            keras.layers.Dropout(0.2),
            keras.layers.GlobalAveragePooling1D(),
            keras.layers.Dropout(0.2),
            keras.layers.Dense(1),
        ]
    )

    print(model.summary())

    model.compile(
        loss=keras.losses.BinaryCrossentropy(from_logits=True),
        optimizer="adam",
        metrics=keras.metrics.BinaryAccuracy(threshold=0.0),
    )

    return model

def train_and_save_model(model_name, model: keras.Sequential, train_ds, val_ds) -> keras.callbacks.History:
    epochs = 10

    model.fit(
        train_ds,
        validation_data=val_ds,
        epochs=epochs,
    )
    model.save(os.path.join(MODEL_DIR, model_name), save_format="tf")

vectorizer = create_vectorizer(raw_train_ds)
model = create_model(vectorizer)
train_and_save_model(MODEL_NAME, model, raw_train_ds, raw_val_ds)
```

And then I can load it like this:

```
custom_objects = {"custom_standardization": custom_standardization}
model: keras.Sequential = keras.models.load_model(
    os.path.join(MODEL_DIR, MODEL_NAME),
    custom_objects=custom_objects,
)
# predict
examples = [
    "The movie was great!",
    "The movie was okay.",
    "The movie was terrible...",
    "The movie was amazing",
]
predictions = model.predict(examples)
```

So I need to tell the `load_model` function which `custom_objects` to integrate.

**Comment by BenWilson2** [comment]
Ah, I see. Pickling will fail here since the function reference is external to the generated object. Could you try refactoring to ensure that those functions become wrapped and encapsulated within the generated object and utilize the pyfunc flavor to ensure that all references are included?

**Comment by anneadb** [comment]
Hi Ben,
I'm sorry to say that I am not proficient enough with tensorflow and mlflow to follow your suggestion.

Regarding `functions become wrapped and encapsulated within the generated object`: Does this mean I would somehow have to add the custom function to my `create_model` function so that it is part of the model object? I thought it was already part of it because the vectorizer layer is a part of the model.

Regarding `utilize the pyfunc flavor`: Isn't the `autolog` function taking care of everything for mlflow? The following MLmodel is created:

```
artifact_path: model
flavors:
  keras:
    code: null
    data: data
    keras_module: tensorflow.keras
    keras_version: 2.9.0
    save_format: tf
  python_function:
    data: data
    env: conda.yaml
    loader_module: mlflow.keras
    python_version: 3.10.6
mlflow_version: 1.29.0
model_uuid: 21e33cde572648afad91abe1403b562b
run_id: 1ad0cc83a12042c0b6bf4151382dcd14
utc_time_created: '2022-09-27 10:32:27.314312'
```

**Comment by BenWilson2** [comment]
Autolog doesn't support the custom_objects that you'll need to supply to ensure that deserialization functions correctly. 
Could you try using mlflow.keras.log_model(<your model>, <your model name>, custom_objects={"custom_standardization": custom_standardization}) and see if that allows you to load the model correctly?
