### ISSUE TITLE
Getting URL of logged artifacts [FR]

### ISSUE THREAD

**Issue by leweex95** [mlflow/mlflow#6889]
### Willingness to contribute

No. I cannot contribute this feature at this time.

### Proposal Summary

I am running an ML pipeline, at the end of which I am logging certain information using mlflow. I was mostly going through Databricks' official mlflow tracking tutorial.

When running `mlflow.log_metric()` in a notebook, the below message shows:
```
(1) MLflow run
Logged 1 run to an experiment in MLflow. Learn more
```

And I can view the logged information by clicking on "1 run." 

However, I'd love to retrieve this link where the artifacts are stored, automatically. Currently, I can build this link in the following, quite cumbersome manner: 

`https://mycompany-{environment}.cloud.databricks.com/?o={workspace_id}#mlflow/experiments/{experiment_id}/runs/{run_id}`

Am I right that this should be implemented by mlflow? 

### Motivation

> #### What is the use case for this feature?
Automatically retrieving the url where artifacts of a ML model have been stored by Mlflow.
> #### Why is this use case valuable to support for MLflow users in general?
Currently, users can access it only by using the notebook UI and manually opening it, but AFAIK there's no in-built support for automatically retrieving this link.
> #### Why is this use case valuable to support for your project(s) or organization?
It would be useful to have this link to pass on to additional processes, such as email report or Slack notification.
> #### Why is it currently difficult to achieve this use case?
Currently, we need to manually build up the url piece-by-piece, by essentially hardcoding the url template to the code.  

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
Hi @leweex95, we can programmatically obtain an mlflow active run link using the following code on Databricks Notebook:

```python
def get_active_mlflow_run_link():
    host = dbutils.notebook.entry_point.getDbutils().notebook().getContext().browserHostName().get()
    run = mlflow.active_run()
    return f"https://{host}/#/mlflow/experiments/{run.info.experiment_id}/runs/{run.info.run_id}"

with mlflow.start_run():
    print(get_active_mlflow_run_link())
    # -> https://my.company.cloud.databricks.com/#/mlflow/experiments/1163310372195059/runs/218e79b0163a4817bdeb92ca2e62e18a
```

**Comment by BenWilson2** [comment]
@harupy that's how I would do it! LGTM

**Comment by harupy** [comment]
@leweex95 Feel free to reopen the issue if the code in https://github.com/mlflow/mlflow/issues/6889#issuecomment-1257877820 doesn't satisfy your needs.
