### ISSUE TITLE
[BUG]  autolog not working from pyspark because of _capture_modules.py stuck

### ISSUE THREAD

**Issue by seraus** [mlflow/mlflow#6905]
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

1.28/1.29

### System information

running on kubernetes v1.20.8
ubuntu 20.04, 
jupyterlab 3.4.3, 
python 3.8.13
spark 3.2.1 (pyspark)
minio quay.io/minio/minio:RELEASE.2022-02-18T01-50-10Z

### Describe the problem

Hi team,
I'm using mlflow to log a pysparkml model. 
I've got a mlflow tracking which is configured to use a local minio as storage.

Model logging is working from pure python (sklearn) while there seems to be a problem 

- when using mlflow.spark.log without specifying a conda_env, ie 

```
mlflow.spark.log_model(pipeline_model,"model",conda_env=conda_env)
```
- or when using sparkml autolog

In both cases it seems, after correctly logging the sparkml pipeline files to minio,  to call a piece of code "_capture_modules.py" to prepare the main file MLmodel:

jovyan    7228  0.5  0.4 583672 109928 ?       Sl   09:41   0:04 /home/jovyan/condaenv/edge/bin/python3.8 /home/jovyan/condaenv/edge/lib/python3.8/site-packages/mlflow/utils/_capture_modules.py --model-path /tmp/tmprxa5r8da --flavor spark --output-file /tmp/tmporxuqx4o/imported_modules.txt --sys-path ["/home/jovyan/notebook/working", "/home/jovyan/condaenv/edge/lib/python3.8/site-packages/git/ext/gitdb", "/tmp/spark-b0b87cac-185a-455a-a4f7-2541285e2836/userFiles-2989435d-54ac-48f2-92e7-86ae1cfb781a", "/usr/local/spark/python/lib/py4j-0.10.9.3-src.zip", "/usr/local/spark/python", "/home/jovyan/notebook/working", "/home/jovyan/condaenv/edge/lib/python38.zip", "/home/jovyan/condaenv/edge/lib/python3.8", "/home/jovyan/condaenv/edge/lib/python3.8/lib-dynload", "", "/home/jovyan/condaenv/edge/lib/python3.8/site-packages", "/home/jovyan/condaenv/edge/lib/python3.8/site-packages/gitdb/ext/smmap"]

and it starts a spark instance which seems  not properly configured:

jovyan    7237  2.6  1.5 6196088 368348 ?      Sl   09:41   0:19 /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -cp /usr/local/spark/conf/:/usr/local/spark/jars/* -Xmx1g -Dio.netty.tryReflectionSetAccessible=true org.apache.spark.deploy.SparkSubmit --conf spark.master=local[1] --conf spark.databricks.io.cache.enabled=False --conf spark.driver.bindAddress=127.0.0.1 --conf spark.python.worker.reuse=True --conf spark.executor.allowSparkContext=true pyspark-shell

and try to call s3 of amazon.com instead of local minio 

see stacktrace below

It usually end run in a 1.5 h after a timeout logging the remaining files (MLmodel file and "brothers")

Is there any chance to pass  spark and minio configuration to this process?

### Code to reproduce issue

from pyspark.ml.classification import LogisticRegression
from pyspark.ml.feature import VectorAssembler, StandardScaler
from pyspark.ml import Pipeline
from pyspark.sql import SparkSession
from sklearn.datasets import load_iris

import mlflow

mlflow.set_experiment("spark_pipeline_example")

mlflow.pyspark.ml.autolog()

df = load_iris(as_frame=True).frame.rename(columns={"target": "label"})
df = sc.createDataFrame(df)
train, test = df.randomSplit([0.8, 0.2])

assembler = VectorAssembler(inputCols=df.columns[:-1], outputCol="features")
scaler = StandardScaler(inputCol=assembler.getOutputCol(), outputCol="scaledFeatures")
lor = LogisticRegression(maxIter=5, featuresCol=scaler.getOutputCol())

# Non-neseted pipeline
pipeline = Pipeline(stages=[assembler, scaler, lor])
with mlflow.start_run():
    pipeline_model = pipeline.fit(train)

# predictions

columns = ["features", "prediction"]
pipeline_model.transform(test).select(columns).show()

### Stack trace

from pyspark.ml.classification import LogisticRegression
from pyspark.ml.feature import VectorAssembler, StandardScaler
from pyspark.ml import Pipeline
from pyspark.sql import SparkSession
from sklearn.datasets import load_iris

import mlflow

mlflow.set_experiment("spark_pipeline_example")

mlflow.pyspark.ml.autolog()

df = load_iris(as_frame=True).frame.rename(columns={"target": "label"})
df = sc.createDataFrame(df)
train, test = df.randomSplit([0.8, 0.2])

assembler = VectorAssembler(inputCols=df.columns[:-1], outputCol="features")
scaler = StandardScaler(inputCol=assembler.getOutputCol(), outputCol="scaledFeatures")
lor = LogisticRegression(maxIter=5, featuresCol=scaler.getOutputCol())

# Non-neseted pipeline
pipeline = Pipeline(stages=[assembler, scaler, lor])
with mlflow.start_run():
    pipeline_model = pipeline.fit(train)

# predictions

columns = ["features", "prediction"]
pipeline_model.transform(test).select(columns).show()

### Other info / logs

2022-09-27 09:53:14,412 +0000 [Thread-4] DEBUG (MainClientExec.java:234) - Opening connection {s}->https://miniosergio.s3.amazonaws.com:443
2022-09-27 09:53:14,413 +0000 [Thread-4] DEBUG (DefaultHttpClientConnectionOperator.java:139) - Connecting to miniosergio.s3.amazonaws.com/52.217.88.84:443
2022-09-27 09:53:14,413 +0000 [Thread-4] DEBUG (SSLConnectionSocketFactory.java:366) - Connecting socket to miniosergio.s3.amazonaws.com/52.217.88.84:443 with timeout 5000
2022-09-27 09:53:19,419 +0000 [Thread-4] DEBUG (ClientConnectionManagerFactory.java:82) - 
java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedMethodAccessor16.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76)
        at com.amazonaws.http.conn.$Proxy15.connect(Unknown Source)
        at com.amazonaws.thirdparty.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
        at com.amazonaws.thirdparty.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at com.amazonaws.thirdparty.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
        at com.amazonaws.thirdparty.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at com.amazonaws.thirdparty.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at com.amazonaws.thirdparty.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
        at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1333)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5227)
        at com.amazonaws.services.s3.AmazonS3Client.getBucketRegionViaHeadRequest(AmazonS3Client.java:6189)
        at com.amazonaws.services.s3.AmazonS3Client.fetchRegionFromCache(AmazonS3Client.java:6162)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5211)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5173)
        at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1360)
        at org.apache.hadoop.fs.s3a.S3AFileSystem.lambda$getObjectMetadata$6(S3AFileSystem.java:2066)
        at org.apache.hadoop.fs.s3a.Invoker.retryUntranslated(Invoker.java:412)
        at org.apache.hadoop.fs.s3a.Invoker.retryUntranslated(Invoker.java:375)
        at org.apache.hadoop.fs.s3a.S3AFileSystem.getObjectMetadata(S3AFileSystem.java:2056)
        at org.apache.hadoop.fs.s3a.S3AFileSystem.getObjectMetadata(S3AFileSystem.java:2032)
        at org.apache.hadoop.fs.s3a.S3AFileSystem.s3GetFileStatus(S3AFileSystem.java:3273)
        at org.apache.hadoop.fs.s3a.S3AFileSystem.innerGetFileStatus(S3AFileSystem.java:3185)
        at org.apache.hadoop.fs.s3a.S3AFileSystem.getFileStatus(S3AFileSystem.java:3053)
        at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1760)
        at org.apache.hadoop.fs.s3a.S3AFileSystem.exists(S3AFileSystem.java:4263)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
        at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
        at java.lang.Thread.run(Thread.java:750)
Caused by: com.amazonaws.thirdparty.apache.http.conn.ConnectTimeoutException: Connect to miniosergio.s3.amazonaws.com:443 [miniosergio.s3.amazonaws.com/52.217.88.84] failed: connect timed out
        at com.amazonaws.thirdparty.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:151)
        at com.amazonaws.thirdparty.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
        ... 49 more
Caused by: java.net.SocketTimeoutException: connect timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:607)
        at com.amazonaws.thirdparty.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:368)
        at com.amazonaws.thirdparty.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
        ... 50 more

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by seraus** [comment]
I'm setting them directly in jupyterlab with these:

**Comment by seraus** [comment]
I'm figuring out what is the problem:

the "_capture_modules.py" script create a new spark context by executing a command "java ....  pyspark-shell"
In my case I'm using a python module to set spark conf and to get a spark session:


def get_spark_session(mode="local", jars_path="/usr/local/spark/jars/"): 
  if mode == "kubernetes":
    return _get_client_mode_spark_session(jars_path)  (...)
  else:
    return SparkSession \
          .builder \
          .appName("spark app") \
          .config("spark.jars", ",".join(getJars(jars_path)))\
          .getOrCreate()

So I haven't got any 'spark-shell' command  configured.

But why create a new spark-context/spark-session in that script ? 
Couldn't you make it use an existing spark-context/spark-session, the same we use to log the pipeline?

**Comment by seraus** [comment]
and does it need to be isolated necessarily?

When doing log manually, If I use:

conda_env=mlflow.spark.get_default_conda_env()
mlflow.spark.log_model(pipeline_model,"model",conda_env=conda_env)

works perfectly and if I understand correctly, get_default_conda_env() is doing the same thing, ie collect dependencies

NB: if I omit "conda_env" parameter, there's the same problem.

Thanks for all the answer, BenWilson2. Very kind of you

**Comment by BenWilson2** [comment]
This does bring up a point about potentially using the current SparkSession. We'll discuss it internally and see if there's a potential change that we could make to this to support your use case (no promises on implementing it; only that we'll discuss it :) )

**Comment by WeichenXu123** [comment]
The issue is probably:
https://github.com/mlflow/mlflow/blob/3d6827f1775d91bffe401c4dfa57c262eeff7333/mlflow/utils/_capture_modules.py#L115

We should clean 'PYSPARK_GATEWAY_PORT' and 'PYSPARK_GATEWAY_SECRET'  in OSS spark case as well.
Otherwise the child process will try to connect to the spark driver process in parent process, which causes issues.

**Comment by BenWilson2** [comment]
@seraus Could I ask you to install MLflow on your system from the branch that we just pushed in #6912 to see if this fixes your original issue?
I think this might be a bit faster than trying to recreate the setup that you described that you're running on our end. If this works, we'll get it merged and it will be a part of the next release of MLflow so that you won't have to do any work arounds to get autologging to work in your setup.

**Comment by BenWilson2** [comment]
i.e.,
```sh
pip install git+https://github.com/mlflow/mlflow.git@clear-pyspark-gateway-for-module-capture
```

**Comment by seraus** [comment]
Thanks for the directions, I'm assuming is it enough to reinstall the clientapi (module in my conda env of jupyterhub), not the mlflow tracker server. It that so?

**Comment by seraus** [comment]
same problem, stuck on the launch of the second sparkSession:

`
jovyan    3897  1.5  0.4 584140 110480 ?       Sl   08:24   0:03 /home/jovyan/condaenv/edge/bin/python3.8 /home/jovyan/condaenv/edge/lib/python3.8/site-packages/mlflow/utils/_capture_modules.py --model-path /tmp/tmp67eg90nw --flavor spark --output-file /tmp/tmpnmikgcim/imported_modules.txt --sys-path ["/home/jovyan/notebook/working", "/home/jovyan/condaenv/edge/lib/python3.8/site-packages/git/ext/gitdb", "/tmp/spark-bc9b42e4-055a-475f-8473-e29e2fb226bb/userFiles-2e7fc0d5-d98e-457c-8fdf-7f6ee8f111eb", "/usr/local/spark/python/lib/py4j-0.10.9.3-src.zip", "/usr/local/spark/python", "/home/jovyan/notebook/working", "/home/jovyan/condaenv/edge/lib/python38.zip", "/home/jovyan/condaenv/edge/lib/python3.8", "/home/jovyan/condaenv/edge/lib/python3.8/lib-dynload", "", "/home/jovyan/condaenv/edge/lib/python3.8/site-packages", "/home/jovyan/condaenv/edge/lib/python3.8/site-packages/gitdb/ext/smmap"]
jovyan    3906  8.1  1.4 6196092 360928 ?      Sl   08:24   0:15 /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -cp /usr/local/spark/conf/:/usr/local/spark/jars/* -Xmx1g -Dio.netty.tryReflectionSetAccessible=true org.apache.spark.deploy.SparkSubmit --conf spark.master=local[1] --conf spark.databricks.io.cache.enabled=False --conf spark.driver.bindAddress=127.0.0.1 --conf spark.python.worker.reuse=True --conf spark.executor.allowSparkContext=true pyspark-shell
```

**Comment by seraus** [comment]
![cattura-mlflow](https://user-images.githubusercontent.com/41294954/192730000-89284bec-1333-4775-9803-0195ab2548f4.JPG)

**Comment by WeichenXu123** [comment]
@BenWilson2 Would you add log command and let user rerun again ?
https://github.com/mlflow/mlflow/pull/6912/files#r982133011

**Comment by seraus** [comment]
I logged in __init__

**Comment by WeichenXu123** [comment]
Could you also test running:

```
        spark = (
            pyspark.sql.SparkSession.builder.config("spark.python.worker.reuse", True)
            .config("spark.databricks.io.cache.enabled", False)
            # In Spark 3.1 and above, we need to set this conf explicitly to enable creating
            # a SparkSession on the workers
            .config("spark.executor.allowSparkContext", "true")
            # Binding "spark.driver.bindAddress" to 127.0.0.1 helps avoiding some local hostname
            # related issues (e.g. https://github.com/mlflow/mlflow/issues/5733).
            .config("spark.driver.bindAddress", "127.0.0.1")
            .master("local[1]")
            .getOrCreate()
        )
```

on your python environment (Pls start a clean python process to try.) :)

**Comment by seraus** [comment]
working perfectly....



![capture-mlflow2](https://user-images.githubusercontent.com/41294954/192795909-655d2900-8120-4d22-9ec1-dd985b272433.JPG)
[spark.log.zip](https://github.com/mlflow/mlflow/files/9665604/spark.log.zip)

**Comment by seraus** [comment]
But.. if you look at the exception I reported yesterday, problem doesn't seem to be starting a SparkSession from your code but having it properly configured (in this case it's calling amazon while I have a local minio)
thanks

Caused by: com.amazonaws.thirdparty.apache.http.conn.ConnectTimeoutException: Connect to miniosergio.s3.amazonaws.com:443 [miniosergio.s3.amazonaws.com/52.217.88.84] failed: connect timed out

**Comment by BenWilson2** [comment]
@seraus I just pushed a change to that branch from earlier that passes the current os.environ values to the subprocess. That PR also has the 'safe' SparkSession creation from within the subprocess for local session creation. Could you try your original code configuration with that branch (uninstall then reinstall MLflow from that branch) and see if it fixes the problem?

**Comment by seraus** [comment]
same problem with the new pull from git

Caused by: com.amazonaws.thirdparty.apache.http.conn.ConnectTimeoutException: Connect to miniosergio.s3.amazonaws.com:443 [miniosergio.s3.amazonaws.com/54.231.160.169] failed: connect timed out
        at com.amazonaws.thirdparty.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:151)
        at com.amazonaws.thirdparty.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
        ... 50 more

**Comment by WeichenXu123** [comment]
@BenWilson2 
Could you compare the environment varaibles DIFF between failed run case (in subprocess) and successful [case](https://github.com/mlflow/mlflow/issues/6905#issuecomment-1260945100)

**Comment by seraus** [comment]
Sure, I'll let you know shortly
Thanks

**Comment by seraus** [comment]
The two list of env variables are identical and now it's working!
I didn't notice in the last try, because autolog takes a bit longer than manual log:

Autolog 2,7 min
Manual log 33 sec

Do you think is it normal?

**Comment by seraus** [comment]
When do you think this new code will be released?

**Comment by BenWilson2** [comment]
Yeah, autolog does quite a few things 'under the hood' and can take a bit longer. Manually setting params / metrics / logging a model will always be faster. 
I'll try to clean up that branch (remove all the debug nonsense) and work on getting it merged to master in the next 4 days. It'll be part of the next release of MLflow :) 
Thanks for reporting this and being patient as we did remote troubleshooting!

**Comment by BenWilson2** [comment]
@seraus #6912 has been merged into master. The next release should have you all set!

**Comment by seraus** [comment]
Thanks BenWilson2!
