### ISSUE TITLE
[FR] Support for NoSQL Database for backend like GCP Big Table & Firestore

### ISSUE THREAD

**Issue by gomrinal** [mlflow/mlflow#6983]
### Willingness to contribute

Yes. I would be willing to contribute this feature with guidance from the MLflow community.

### Proposal Summary

MLflow need to have an option of logging data like hyperparameters on No-SQL databases because of scalability and mainly we don't know which model data scientists would use for their experimentation. Each algorithm usually have their own set of hyperparameters. 

Having RDBMS forces one to think ahead of time about the schema and fields one might use but that restricts the algorithms one can use because of this issue. Therefore, having a NO-SQL database as a backend might help in order to resolve this issue.

### Motivation

> #### What is the use case for this feature?
- Easily scaling writes for logging hyperparameters for algos where we can't predict the hyperparameters used by data scientists
> #### Why is this use case valuable to support for MLflow users in general?
- It will help everyone who want to use MLflow in production
> #### Why is this use case valuable to support for your project(s) or organization?
- It will help anyone who uses GCP for their work in ML engineering space.
> #### Why is it currently difficult to achieve this use case?
- Because MLFlow doesn't support no-sql database as backend as of now

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [X] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [X] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dbczumar** [comment]
Hi @gomrinal, thank you for raising this issue. We've included a comparable feature request in the MLflow roadmap: https://github.com/mlflow/mlflow/issues/6077 (I see that you've commented here: https://github.com/mlflow/mlflow/issues/6077#issuecomment-1269101126). If you'd like to work on designing this capability for a particular NoSQL platform, we'd love to discuss the topic with you and review any designs you have. I'm going to go ahead and close this particular issue as a duplicate.
