### ISSUE TITLE
[BUG] Registry image id not stored in tracking server

### ISSUE THREAD

**Issue by subramaniam20jan** [mlflow/mlflow#7005]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

1.29.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 20.04.5 LTS
- **Python version**: 3.10

### Describe the problem

When running mlflow on the kubernetes backend, mlflow pushes two image related tags to the tracking server, namely, mlflow.docker.image.id and mlflow.docker.image.uri.

While the mlflow.docker.image.uri is correct and corresponds the right image registry, it looks like the image.id tag corresponds to the local image digest and not the image digest corresponding to the remote docker registry which is actually what is deployed to the kubernetes.

It can be seen that this image_id is actually obtained and returned from the [mlflow.projects.kubernetes. push_image_to_registry](https://github.com/mlflow/mlflow/blob/master/mlflow/projects/kubernetes.py#L31). Then it is [used](https://github.com/mlflow/mlflow/blob/83295954a64d67ee46fccaf8cbbca66669dfcd0b/mlflow/projects/__init__.py#L165) to actually generate the kubernetes job definition, but isnt tagged to mlflow tracking server in any way.

### Code to reproduce issue

Any successful deployment with a kubernetes backend(including the [default example](https://github.com/mlflow/mlflow/tree/master/examples/docker) listed)  can be seen to reproduce this issue.

### Stack trace

No stacktrace since it is simply omitted metadata tag. Results in no error directly.

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [X] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [X] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dbczumar** [comment]
Hi @subramaniam20jan, thank you for raising this issue. I agree that the tag set on the MLflow Project Run is incorrect. Would you be able to file a pull request to address the problem? We'd be happy to review it and advise. Thank you in advance for your help!

**Comment by subramaniam20jan** [comment]
@dbczumar : is there a specific process for closing issues?
