### ISSUE TITLE
[BUG] Unexpected behaviour when authenticating to remote MLFlow server from Snakemake

### ISSUE THREAD

**Issue by JackyHess** [mlflow/mlflow#7009]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

1.29.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  MacOS BigSur 
- **Python version**:  3.9.13
- **yarn version, if running the dev UI**:

I have also tested this inside a Docker container running Debian 10.12

### Describe the problem

We use MLFlow for logging workflow parameters and artifacts from [Snakemake](https://snakemake.readthedocs.io/en/stable/) workflows. For this purpose I have set up  a remote MLFlow server on Google Kubernetes Engine protected behind an IAP (Identity Aware Proxy) and am connecting to it for logging runs using JWT tokens.

I can successfully authenticate to the server from a Notebook, however when I plug the identical code into Snakemake as a rule, authentication fails for POST methods (e.g. create run or create experiment), while I can still retrieve data from GET methods. 

Additionally, if I run the code below requesting the tracking URI and artifact URI, the version running as a Snakemake rule crashes without returning and artifact URI. 

The Notebook runs with the Snakemake conda environment so all packages are theoretically identical.

I am at a loss as to what could explain this behaviour - if anyone has any idea I'd be very grateful for some hints.

### Tracking information

Notebook printout

```
MLflow version: 1.28.0
Tracking URI: https://xxxxxxxx/
Artifact URI: gs://xxxxxxxxx/0/c1b08c4dc6474569b23f7a84c9660e90/artifacts
```

Snakemake rule printout
```
MLflow version: 1.28.0
Tracking URI: https://xxxxxxxx/
```

### Code to reproduce issue

```python
# Authentication function

def authenticate_mlflow():
    """
    Authenticate to mlflow cluster
    """

    if os.getenv("OAUTH_CLIENT_ID") != None:

        try:
            auth = subprocess.run("gcloud auth activate-service-account --key-file="+SERVICE_ACCOUNT_JSON, shell=True, check = True, capture_output=True)
            print("Authenticated service account")
        except subprocess.CalledProcessError:
            print("Authentication with service account " + SERVICE_ACCOUNT_JSON + " failed")
            sys.exit(1)
        try:
            stream = subprocess.run("gcloud auth print-identity-token --audiences={OAUTH_CLIENT_ID}".format(OAUTH_CLIENT_ID=os.getenv("OAUTH_CLIENT_ID")),shell=True, text = True, check = True, capture_output=True )
            # set token
            token = token = stream.stdout.rstrip()
            os.environ["MLFLOW_TRACKING_TOKEN"] = token
        except subprocess.CalledProcessError:
            print("Could not fetch token for OAuth client " + os.getenv("OAUTH_CLIENT_ID"))
            sys.exit(1)

        # set tracking uri
        mlflow.set_tracking_uri(TRACKING_URI)
        print("Authenticated MLFlow")

        # set experiment
        if not mlflow.get_experiment_by_name(config["mlflow_experiment"]):
            mlflow.create_experiment(config["mlflow_experiment"])
        exp = mlflow.get_experiment_by_name(config["mlflow_experiment"])

        return exp
    else:
        print("Missing OAuth client ID environmental variable \"OAUTH_CLIENT_ID\"to complete authentication")

# set constants
TRACKING_URI = "https://xxxxxxxxx"
SERVICE_ACCOUNT_JSON = "../config/service_account.json"
os.environ["OAUTH_CLIENT_ID"] = "xxxxxxxxxxx.apps.googleusercontent.com"
config = { "mlflow_experiment": "test-exp"}

# authenticate and run requests
exp = authenticate_mlflow()

token = os.getenv("MLFLOW_TRACKING_TOKEN")

# list experiments
url = TRACKING_URI + "/api/2.0/mlflow" + "/experiments/list"
r = requests.get(url, headers={"Authorization": f"Bearer {token}"})
print(r)
        
# create run
url = TRACKING_URI + "/api/2.0/mlflow" + "/runs/create"
payload = {
    "experiment_id": exp.experiment_id,
}
r = requests.post(url, json=payload, headers={"Authorization": f"Bearer {token}"})

print(r)
run_id = None
if r.status_code == 200:
    run_id = r.json()["run"]["info"]["run_uuid"]
print(run_id)
```

When executed from inside Snakemake, I provide the code as a rule like so:

```python
rule init_mlflow:
    output:
        "mlflow_run_id.txt"
    run:
        exp = authenticate_mlflow()
        token = os.getenv("MLFLOW_TRACKING_TOKEN")

        # list experiments
        url = TRACKING_URI + "/api/2.0/mlflow" + "/experiments/list"
        r = requests.get(url, headers={"Authorization": f"Bearer {token}"})
        print(r)
        #
        # create run
        url = TRACKING_URI + "/api/2.0/mlflow" + "/runs/create"
        payload = {
            "experiment_id": 2,
        }
        r = requests.post(url, json=payload, headers={"Authorization": f"Bearer {token}"})
        print(r)
        run_id = None
        if r.status_code == 200:
            run_id = r.json()["run"]["info"]["run_uuid"]
        print(run_id)
```

### Stack trace

Notebook output

```
Authenticated service account
Authenticated MLFlow
<Response [200]>
<Response [200]>
bc297eca3638422f8e8216406934eb3d
```

Snakemake output

```
Authenticated service account
Authenticated MLFlow
<Response [200]>
<Response [405]>
None
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dbczumar** [comment]
Hi @JackyHess, since MLflow appears to work with your IAP from a notebook, I don't think that there's a clear MLflow issue here. Would you be able to post this question on the discussions page (https://github.com/mlflow/mlflow/discussions) instead? Thank you for using MLflow!
