### ISSUE TITLE
[FR] Tracking Uncommitted Local Changes

### ISSUE THREAD

**Issue by boragokbakan** [mlflow/mlflow#7017]
### Willingness to contribute

Yes. I would be willing to contribute this feature with guidance from the MLflow community.

### Proposal Summary

MLflow readily tracks code versions for Git projects and includes the commit hash, put this does not capture any uncommitted changes (i.e., quick fixes, parameter changes) to the project. A git diff patch file could be added as an artifact to capture changes.

### Motivation

> #### What is the use case for this feature?
Sometimes, quick fixes or changes are done on workstations, which is not captured by the saved git hash. Saving a git diff patch would make it easier to reproduce experiments.

> #### Why is this use case valuable to support for MLflow users in general?
This would be a convenient utility for many in the MLflow community.

> #### Why is this use case valuable to support for your project(s) or organization?
I work in projects with multiple collaborators and servers, where people usually develop their code locally and run experiments in dedicated servers. It is difficult to reproduce experiments if someone forgets to commit their local changes.

> #### Why is it currently difficult to achieve this use case?
It is inconvenient to add this manually to every training script.

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dbczumar** [comment]
Hi @boragokbakan, this sounds like a great idea! Are you proposing to save the patch as an MLflow artifact? Let me know what your implementation ideas are here :D

**Comment by boragokbakan** [comment]
Hi @dbczumar, thanks for the reply.

Sorry for my late response. I think there are two ways of doing this, but I only mentioned one in the original issue:

1. **w/MLflow Artifacts:** Yes, we can save the patch as an MLflow artifact (to answer your question), if there is a difference to any tracked files in the working tree. So when someone wants to rerun an experiment, they would checkout the commit, then download & apply the patch file if there is any. Optionally, we could provide a CLI tool to automate this like: `mlflow checkout [RUNID]`
2.  **w/Automatic Commits:** We can alternatively create a commit if there are uncommitted changes, with a message like `MLflow Auto-commit Run ID: [RUNID]`. Then the HEAD would be reset to the original user commit to keep all the "uncommitted" changes in the working directory, but the index would be clean (i.e., users' Git flow would not be interrupted). The tracking server would register this commit as the source version, so it would be very easy to restore it.

I would love to hear your feedback on these two approaches.

**Comment by boragokbakan** [comment]
Any thoughts @dbczumar ?

**Comment by boragokbakan** [comment]
@dbczumar I can implement this on my own if we can agree on an approach. I use MLflow quite often, so I'd be more than happy to contribute.

**Comment by jot-hub** [comment]
isn't this related to: https://github.com/mlflow/mlflow/issues/271?
how do folks handle it currently? I would be surprised if the commit step is left to the developer/engineer to do manually.
