### ISSUE TITLE
[BUG] 1.30: mlflow.exceptions.RestException: BAD_REQUEST: (sqlite3.IntegrityError) UNIQUE constraint failed: tags.key, tags.run_uuid

### ISSUE THREAD

**Issue by alexanderkainsky** [mlflow/mlflow#7133]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

1.30

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: ubuntu 20.04
- **Python version**: 3.9.15
- **yarn version, if running the dev UI**:

### Describe the problem

After starting version 1.30 via:

mlflow server -h 0.0.0.0 -p 5050 \
  --backend-store-uri sqlite:////home/mlflow/mlflow.db \
  --serve-artifacts \
  --artifacts-destination file:/home/mlflow/mlartifacts

on a fresh install, I get:

mlflow.exceptions.RestException: BAD_REQUEST: (sqlite3.IntegrityError) UNIQUE constraint failed: tags.key, tags.run_uuid

### Tracking information

>>> import mlflow
>>> print("MLflow version:", mlflow.__version__)
MLflow version: 1.30.0
>>> print("Tracking URI:", mlflow.get_tracking_uri())
Tracking URI: file:///home/mlflow/mlruns
>>> print("Artifact URI:", mlflow.get_artifact_uri())
Artifact URI: file:///home/mlflow/mlruns/0/78c1349a05df4b7aada9a7f05bccd26e/artifacts

### Code to reproduce issue

with mlflow.start_run(**kwargs) as run:
  ...

### Stack trace

  File "/home/kaina/work/repo/core/scripts/tfx/mlflow_continuation_example.py", line 151, in do_run
    with mlflow.start_run(**kwargs) as run:
  File "/home/kaina/.pyenv/versions/core/lib/python3.9/site-packages/mlflow/tracking/fluent.py", line 318, in start_run
    active_run_obj = client.create_run(experiment_id=exp_id_for_run, tags=resolved_tags)
  File "/home/kaina/.pyenv/versions/core/lib/python3.9/site-packages/mlflow/tracking/client.py", line 265, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags)
  File "/home/kaina/.pyenv/versions/core/lib/python3.9/site-packages/mlflow/tracking/_tracking_service/client.py", line 99, in create_run
    return self.store.create_run(
  File "/home/kaina/.pyenv/versions/core/lib/python3.9/site-packages/mlflow/store/tracking/rest_store.py", line 170, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
  File "/home/kaina/.pyenv/versions/core/lib/python3.9/site-packages/mlflow/store/tracking/rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "/home/kaina/.pyenv/versions/core/lib/python3.9/site-packages/mlflow/utils/rest_utils.py", line 256, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "/home/kaina/.pyenv/versions/core/lib/python3.9/site-packages/mlflow/utils/rest_utils.py", line 185, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: BAD_REQUEST: (sqlite3.IntegrityError) UNIQUE constraint failed: tags.key, tags.run_uuid
[SQL: INSERT INTO tags ("key", value, run_uuid) VALUES (?, ?, ?)]

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@alexanderkainsky I ran:

```
docker run --rm -e MLFLOW_TRACKING_URI=sqlite:///mlflow.db python:3.8 bash -c "pip install mlflow && python -c 'import mlflow; mlflow.start_run()'"
```

but wasn't able to reproduce the issue.

**Comment by harupy** [comment]
Look like you pass `kwargs` to `mlflow.start_run`. Can you share the value of `kwargs`?

**Comment by harupy** [comment]
@alexanderkainsky I was able to reproduce the issue using this code:

```
import mlflow

mlflow.set_tracking_uri("sqlite:///mlflow.db")
mlflow.start_run(run_name="test", tags={"mlflow.runName": "test"})
```

#7183 fixes this issue.

As a workaround, you can make the following change:

```diff
mlflow.start_run(run_name="test")

```

**Comment by alexanderkainsky** [comment]
Very helpful, thank you!
