### ISSUE TITLE
[BUG] run_name not propagating 

### ISSUE THREAD

**Issue by dtpryce** [mlflow/mlflow#7195]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

1.30.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux
- **Python version**: 3.10
- **yarn version, if running the dev UI**: N/A

### Describe the problem

When attempting:

```
mlflow.start_run(run_name="test")
mlflow.sklearn.log_model(model, "test-model")
```

In the past we would get the artifact directory with the name "test-model" and then the run would be called "test" this has stopped working as can be seen in our server UI but also with this run above still active we run:

```
run = mlflow.active_run()
run.to_dictionary()
``` 

and get the output:
```
{'info': {'artifact_uri': 's3://REDACTED',
  'end_time': None,
  'experiment_id': '2',
  'lifecycle_stage': 'active',
  'run_id': '77cabe987a7b41c7911b25aa011c5116',
  'run_name': '',
  'run_uuid': '77cabe987a7b41c7911b25aa011c5116',
  'start_time': 1666976925457,
  'status': 'RUNNING',
  'user_id': 'root'},
 'data': {'metrics': {},
  'params': {},
  'tags': {'mlflow.user': 'root',
   'mlflow.source.name': '/shared-libs/python3.10/py-core/lib/python3.10/site-packages/ipykernel_launcher.py',
   'mlflow.source.type': 'LOCAL'}}}
```

And you can see that the run_id has been auto-generated but the explicit run_name ignored. I am sure we can find a workaround but thought you might like to know about this bug or lack of backward compatibility. 

### Tracking information

1.30.0

### Code to reproduce issue

```python
from sklearn.datasets load_iris
from sklearn.linear_model import LogisticRegression
import mlflow

X, y = load_iris(return_X_y=True)
model = LogisticRegression().fit(X, y)
with mlflow.start_run(run_name="test_name")
	mlflow.sklearn.log_model(model, "test_model")
```

### Stack trace

It doesn't raise an error since it's a lack of backward compatibility 

### Other info / logs

```python
run = mlflow.active_run()	
print(run.to_dictionary()['info']['run_name'])
```

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@dtpryce What is the mlflow version that's used to run the tracking server?

**Comment by harupy** [comment]
How to reproduce the issue:

```
docker run --rm -p 5000:5000 python:3.8 bash -c "pip install mlflow==1.29.0 && mlflow server --host 0.0.0.0"
```

```python
import mlflow

mlflow.set_tracking_uri("http://localhost:5000")

mlflow.start_run(run_name="a")
print(mlflow.active_run().to_dictionary())
```

```
{'info': {'artifact_uri': './mlruns/0/f462d4086e0a448da3235db0c26aab2a/artifacts', 'end_time': None, 'experiment_id': '0', 'lifecycle_stage': 'active', 'run_id': 'f462d4086e0a448da3235db0c26aab2a', 'run_name': '', 'run_uuid': 'f462d4086e0a448da3235db0c26aab2a', 'start_time': 1667177404918, 'status': 'RUNNING', 'user_id': 'haru'}, 'data': {'metrics': {}, 'params': {}, 'tags': {'mlflow.source.git.commit': '710c7e17dcfc54c130d3e9053fda82870919069c', 'mlflow.source.name': 'a.py', 'mlflow.runName': 'vaunted-zebra-455', 'mlflow.user': 'haru', 'mlflow.source.type': 'LOCAL'}}}
```

**Comment by harupy** [comment]
Tested MLflow 1.30.0 (tracking server version):

```
docker run --rm -p 5000:5000 python:3.8 bash -c "pip install mlflow==1.30.0 && mlflow server --host 0.0.0.0"
```

```python
import mlflow

mlflow.set_tracking_uri("http://localhost:5000")

mlflow.start_run(run_name="a")
print(mlflow.active_run().to_dictionary())
```

```
{'info': {'artifact_uri': './mlruns/0/26235b72406042639065652fb0d24dbf/artifacts', 'end_time': None, 'experiment_id': '0', 'lifecycle_stage': 'active', 'run_id': '26235b72406042639065652fb0d24dbf', 'run_name': 'a', 'run_uuid': '26235b72406042639065652fb0d24dbf', 'start_time': 1667179110134, 'status': 'RUNNING', 'user_id': 'haru'}, 'data': {'metrics': {}, 'params': {}, 'tags': {'mlflow.source.git.commit': '63bf1b4728f8cd1f71a0bb4b5155b4a4c0b057a4', 'mlflow.source.name': 'a.py', 'mlflow.runName': 'a', 'mlflow.user': 'haru', 'mlflow.source.type': 'LOCAL'}}}
```

**Comment by dtpryce** [comment]
Tested and confirmed all works again with versions matched :) thanks @harupy I would still prefer to see some sort of warning around this either in docs, changelog or code.
