### ISSUE TITLE
Is there any way to support automatic logging for the pytorch and tensorflow-1 version frameworks?[FR]

### ISSUE THREAD

**Issue by Trainbow** [mlflow/mlflow#7262]
### Willingness to contribute

No. I cannot contribute this feature at this time.

### Proposal Summary

MLflow is a great job, I used it to log and track my experiments.
However, it seems the `mlflow.autolog()` can not support the pytorch network with `nn.Module` and tensorflow 1.0~1.15.
Is there any way to support automatic logging for the pytorch and tensorflow-1 version frameworks?

### Motivation

> #### What is the use case for this feature?
Support more framework
> #### Why is this use case valuable to support for MLflow users in general?
Can be used in more experiments
> #### Why is this use case valuable to support for your project(s) or organization?
Support more framework
> #### Why is it currently difficult to achieve this use case?

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment]
TF1 is officially deprecated and it is in the process of being completely removed from support for MLflow. We have no plans to continue supporting it in any way as it is no longer supported by Google. Please have a read here: https://www.tensorflow.org/guide/migrate to work on migrating your existing TF1 code to the supported and actively maintained TF2.

**Comment by Trainbow** [comment]
已收到，谢谢！
