### ISSUE TITLE
set tracking URI path of a new experiment from code

### ISSUE THREAD

**Issue by rezakarbasi** [mlflow/mlflow#7292]
### Willingness to contribute

Yes. I would be willing to contribute this feature with guidance from the MLflow community.

### Proposal Summary

When I set  my experiment name in python code ( and it's a new name ), mlflow builds a new set of log folders in the <ins>`path`</ins> of python code. This means I couldn't track artifacts in UI, if `mlflow server` doesn't start from the <ins>`path`</ins>. This makes me confused !! 

In another word, we couldn't see artifacts when we run `mlflow server` from another places ( even if we set `backend-store-uri` and 

### Motivation

> #### Why is this use case valuable to support for MLflow users in general?
This is a small feature which make my use more comfortable. Also I believe it's make other's too.

> #### Why is it currently difficult to achieve this use case?
In latest versions, we should set the path of new experiment from other places at first ( ex. set it in UI ). But if this feature would be added, it could be set easily on the code.

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment]
Are you referring to the creation of the default experiment? (experiment_id '0')?

**Comment by harupy** [comment]
@rezakarbasi

> When I set my experiment name in python code ( and it's a new name )

Please share the code.

> In another word, we couldn't see artifacts when we run mlflow server from another places ( even if we set backend-store-uri and

Please share the command you ran.

**Comment by rezakarbasi** [comment]
> Are you referring to the creation of the default experiment? (experiment_id '0')?

@BenWilson2
No, I mean every new experiment

@harupy 
I use this command to run the server and watch the results on port 5004
```bash
mlflow server --backend-store-uri sqlite:////path/to/database.db --default-artifact-root /the/artifact/root -p 5004
```

also I run this piece of code to start mlflow logging in my code:
```python
mlflow.set_tracking_uri("sqlite:////path/to/database.db")
mlflow.set_experiment("a_new_experiment")
mlflow.autolog()
```

**Comment by rezakarbasi** [comment]
> @rezakarbasi
> 
> > When I set my experiment name in python code ( and it's a new name )
> 
> Can you share the code?
> 
> > In another word, we couldn't see artifacts when we run mlflow server from another places ( even if we set backend-store-uri and
> 
> Can you share the command you ran?


@harupy 
I use this command to run the server and watch the results on port 5004
```bash
mlflow server --backend-store-uri sqlite:////path/to/database.db --default-artifact-root /the/artifact/root -p 5004
```

also I run this piece of code to start mlflow logging in my code:
```python
mlflow.set_tracking_uri("sqlite:////path/to/database.db")
mlflow.set_experiment("a_new_experiment")
mlflow.autolog()
```

**Comment by B-Step62** [comment]
This is a configuration issue: with no tracking/artifact URI set, the artifact location is resolved relative to where the run is created. Pointing the client at the tracking server (`MLFLOW_TRACKING_URI`) and setting `--default-artifact-root` on the server resolves it. Closing as a usage issue, feel free to reopen with a reproducible setup.
