### ISSUE TITLE
[BUG] pymysql.err.IntegrityError on java client `startRun` (duplicate runName argument)

### ISSUE THREAD

**Issue by serkef** [mlflow/mlflow#7362]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

- Client: 1.30
- Tracking server: 1.30

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: GCP Dataproc (Spark) - not sure of the internals
- **Python version**: 3.7
- **yarn version, if running the dev UI**: -

### Describe the problem

when I run:
```java
mlFlowContext.startRun("2022-11-05")
```
throws the following error:
```
Exception in thread "main" org.mlflow.tracking.MlflowHttpException: statusCode=400 reasonPhrase=[Bad Request] bodyMessage=[{"error_code": "BAD_REQUEST", "message": "(pymysql.err.IntegrityError) (1062, \"Duplicate entry 'mlflow.runName-2796f91b90734e4ca05773f6e1ec5710' for key 'tags.PRIMARY'\")\n[SQL: INSERT INTO tags (`key`, value, run_uuid) VALUES (%(key)s, %(value)s, %(run_uuid)s)]\n[parameters: ({'key': 'mlflow.runName', 'value': '2022-11-05', 'run_uuid': '2796f91b90734e4ca05773f6e1ec5710'}, {'key': 'mlflow.source.type', 'value': 'LOCAL', 'run_uuid': '2796f91b90734e4ca05773f6e1ec5710'}, {'key': 'mlflow.user', 'value': 'spark', 'run_uuid': '2796f91b90734e4ca05773f6e1ec5710'}, {'key': 'mlflow.runName', 'value': 'marvelous-gnat-900', 'run_uuid': '2796f91b90734e4ca05773f6e1ec5710'})]\n(Background on this error at: https://sqlalche.me/e/14/gkpj)"}]
```
By reading it, there is an attempt to add both:
```json
{"key": "mlflow.runName", "value": "2022-11-05", "run_uuid": "2796f91b90734e4ca05773f6e1ec5710"}
```
and 
```json
{"key": "mlflow.runName", "value": "marvelous-gnat-900", "run_uuid": "2796f91b90734e4ca05773f6e1ec5710"}
```

This problem started occurring when we upgraded our server from v1.27 to v1.30

### Code to reproduce issue

Can't offer a reproduction step. Our code is in scala, using the java library, in a spark context.
It seems quite basic problem - someone must be injecting the randomly generated runName although runName is provided.

Maybe the `runName` should be set here? 
https://github.com/mlflow/mlflow/blob/dbee92072cb1a002fd19255042aad8367d5353b5/mlflow/java/client/src/main/java/org/mlflow/tracking/MlflowContext.java#L160-L163

### Stack trace

Exception in thread "main" org.mlflow.tracking.MlflowHttpException: statusCode=400 reasonPhrase=[Bad Request] bodyMessage=[{"error_code": "BAD_REQUEST", "message": "(pymysql.err.IntegrityError) (1062, \"Duplicate entry 'mlflow.runName-2796f91b90734e4ca05773f6e1ec5710' for key 'tags.PRIMARY'\")\n[SQL: INSERT INTO tags (`key`, value, run_uuid) VALUES (%(key)s, %(value)s, %(run_uuid)s)]\n[parameters: ({'key': 'mlflow.runName', 'value': '2022-11-05', 'run_uuid': '2796f91b90734e4ca05773f6e1ec5710'}, {'key': 'mlflow.source.type', 'value': 'LOCAL', 'run_uuid': '2796f91b90734e4ca05773f6e1ec5710'}, {'key': 'mlflow.user', 'value': 'spark', 'run_uuid': '2796f91b90734e4ca05773f6e1ec5710'}, {'key': 'mlflow.runName', 'value': 'marvelous-gnat-900', 'run_uuid': '2796f91b90734e4ca05773f6e1ec5710'})]\n(Background on this error at: https://sqlalche.me/e/14/gkpj)"}]
	at org.mlflow.tracking.MlflowHttpCaller.checkError(MlflowHttpCaller.java:193)
	at org.mlflow.tracking.MlflowHttpCaller.executeRequestWithRateLimitRetries(MlflowHttpCaller.java:104)
	at org.mlflow.tracking.MlflowHttpCaller.executeRequest(MlflowHttpCaller.java:114)
	at org.mlflow.tracking.MlflowHttpCaller.send(MlflowHttpCaller.java:178)
	at org.mlflow.tracking.MlflowHttpCaller.post(MlflowHttpCaller.java:164)
	at org.mlflow.tracking.MlflowClient.sendPost(MlflowClient.java:549)
	at org.mlflow.tracking.MlflowClient.createRun(MlflowClient.java:117)
	at org.mlflow.tracking.MlflowContext.startRun(MlflowContext.java:167)
	at org.mlflow.tracking.MlflowContext.startRun(MlflowContext.java:131)
	at \[...\](MLFlowLogger.scala:27)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [X] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [X] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by serkef** [comment]
As a workaround, I tried this and it works:

```java
val run = mlFlowContext.startRun()
run.setTag(MlflowTagConstants.RUN_NAME, runName)
```

**Comment by dbczumar** [comment]
Hi @serkef , this has been fixed in MLflow 2.0. Thank you for using MLflow!
