### ISSUE TITLE
Remove entry point parameters from run

### ISSUE THREAD

**Issue by VC86** [mlflow/mlflow#7400]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 1.29
- Tracking server: 1.29

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 22.04
- **Python version**: Python 3.9
- **yarn version, if running the dev UI**: n/a

### Describe the problem

When running an MLproject entry point through the Python API
```python
params = {"bar1": "hello", "bar2": "world"}
mlflow.projects.run("./", entry_point='main', parameters=params, experiment_name="big_foo")
```
assuming that in `MLproject` one has defined an entry point `"main"` accepting parameters `bar1, bar2`, it seems that the parameters in `params` are logged as part of the run.

Is there any way to avoid that behaviour and/or delete these entries (seems forbidden as it triggers an exception in v1.29)?

Example of issue:
![image](https://user-images.githubusercontent.com/26378999/203929367-94124144-d6a1-4081-8699-916a609b5580.png)

### Code to reproduce issue

`MLproject` file
```
name: test_issue
entry_points:
  main:
    parameters:
      bar1: {type: string, default: "a"}
      bar2: {type: string, default: "b"}
    command: "python main.py --bar1 {bar1} --bar2 {bar2}"
```

Generic main: `main.py`
```python
import argparse
import mlflow


def main(bar1, bar2):
    print(f"Got {bar1} {bar2}")
    mlflow.log_metrics({"MyMetric": 0.0}, step=0)
    return True


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="foo code"
    )

    parser.add_argument(
        "-b1",
        "--bar1",
        help="First parameter",
        default=None,
        required=True,
        type=str,
    )

    parser.add_argument(
        "-b2",
        "--bar2",
        help="Second parameter",
        default=None,
        required=True,
        type=str,
    )

    args = parser.parse_args()
    main(args.bar1, args.bar2)
```

Project runner script: `run.py`

```python
import mlflow
import datetime

def run():
    exp_name = "Default"
    run_name = "MyRun-" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
    params = {'bar1': 'hello', 'bar2': 'world'}
    mlflow.run('./', entry_point='main', env_manager='local', experiment_name=exp_name, run_name=run_name,
               parameters=params)
    return


if __name__ == "__main__":
    run()
    exit(0)
```

### Stack trace

n/a

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [X] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by WeichenXu123** [comment]
@VC86 

This should be by design, 
see https://github.com/mlflow/mlflow/blob/ff55883373f045a33a6abdfacc878ee0d190c6ff/mlflow/projects/utils.py#L309

it is not a bug.

**Comment by VC86** [comment]
Understood and thanks for the feedback @WeichenXu123 , is there a way to work around that, e.g., by overwriting or removing explicitly the unwanted parameters as per this other issue you are looking into https://github.com/mlflow/mlflow/issues/7402 ?

**Comment by WeichenXu123** [comment]
> but due to current design that triggers an exception

Could you describe what's the exception ? And then I can consider a good workaround for it.

**Comment by VC86** [comment]
I tried as workaround to go through the list of arguments that are passed to the entry point, and to set them to `None` by calling `log_params()`. 

For example, a naive attempt would be to set:
```python
def main(bar1, bar2):
    print(f"Got {bar1} {bar2}")
    mlflow.log_metrics({"MyMetric": 0.0}, step=0)
    [mlflow.log_param(k, None) for k in ["bar1", "bar2"]]
    return True
```
Which yields
```console
mlflow.exceptions.MlflowException: Changing param values is not allowed. Param with key='bar1' was already logged with value='hello' for run ID='3ec05b3c7ca74a14827ce7b94ea2a899'. Attempted logging new value 'None'.
```
as expected, "by design".

@WeichenXu123 the exception is then the same as the one reported in #7402 (trying to overwrite existing parameters).

**Comment by WeichenXu123** [comment]
@VC86 

MLflow does not allow removing or overwriting logged params.

I think you can add prefix for the param key like: `entry.param1`, `entry.param2`,
and in your application, when you want to read logged params, ignore params that key starting with `entry.`

What do you think of this workaround ?

**Comment by VC86** [comment]
I can indeed do that via UI, not super-elegant, but works.
