### ISSUE TITLE
[BUG] meta.yaml not being created when using SQlite as tracking URI

### ISSUE THREAD

**Issue by ArchanGhosh** [mlflow/mlflow#7455]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

mlflow, version 1.28.0

### System information

- **Windows 10 64 bit**:
- **3.9**:

### Describe the problem

The piece of code provided below is what I am using, and when running this the meta.yaml file is not being created at all. Because of which I am unable to use mlflow UI command or serve the model via mlflow serve. 

I can access the mlflow server and there I can register the models but thats it no way to serve the models.

### Code to reproduce issue

```python

import numpy as np 
import pandas as pd
import warnings

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression
from sklearn import metrics

import mlflow
import mlflow.sklearn

from preprocess import preprocess

import logging
mlflow.set_tracking_uri('sqlite:///mlflow.db')
logging.basicConfig(level=logging.WARN)
logger = logging.getLogger(__name__)

experiment = mlflow.set_experiment(experiment_name = "Logistic Regression") 
print("Experiment_id: {}".format(experiment.experiment_id))

X,y = preprocess() #Any classification data in features, labels format
if __name__ == "__main__":
	warnings.filterwarnings("ignore")
	np.random.seed(40)

	X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.25,random_state=3)
	with mlflow.start_run(run_name = "Train Run") as run:
		log_reg=LogisticRegression(random_state=3, penalty = 'elasticnet', solver='saga', l1_ratio= 0.5)
		log_reg.fit(X_train,y_train)
		y_pred=log_reg.predict(X_test)
		acc_log_clf = metrics.accuracy_score(y_test,y_pred)
		mlflow.log_metric("Accuracy", acc_log_clf)
		print('Accuracy score:', acc_log_clf)
		mlflow.sklearn.log_model(
		sk_model=log_reg,
		artifact_path="sklearn-model",
		registered_model_name="sk-learn-logistic-reg-model"
		)
		print("Model saved in run %s" % mlflow.active_run().info.run_uuid)


```

### Stack trace

mlflow ui
INFO:waitress:Serving on http://127.0.0.1:5000
WARNING:root:Malformed experiment '1'. Detailed error Yaml file '.\mlruns\1\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Python Scripts\mlops\env\lib\site-packages\mlflow\store\tracking\file_store.py", line 270, in list_experiments
    experiment = self._get_experiment(exp_id, view_type)
  File "C:\Python Scripts\mlops\env\lib\site-packages\mlflow\store\tracking\file_store.py", line 394, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
  File "C:\Python Scripts\mlops\env\lib\site-packages\mlflow\store\tracking\file_store.py", line 1049, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
  File "C:\Python Scripts\mlops\env\lib\site-packages\mlflow\store\tracking\file_store.py", line 1042, in _read_helper
    result = read_yaml(root, file_name)
  File "C:\Python Scripts\mlops\env\lib\site-packages\mlflow\utils\file_utils.py", line 181, in read_yaml
    raise MissingConfigException("Yaml file '%s' does not exist." % file_path)
mlflow.exceptions.MissingConfigException: Yaml file '.\mlruns\1\meta.yaml' does not exist.

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [X] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@ArchanGhosh I'm not sure `.\mlruns\1` was created but removing it should resolve the error.

**Comment by harupy** [comment]
@ArchanGhosh Never mind the comment above. When running `mlflow ui`, you need to specify the tracking URI using `--backend-store-uri` like:

```
mlflow ui --backend-store-uri sqlite:///mlflow.db
```

**Comment by ArchanGhosh** [comment]
> @ArchanGhosh Never mind the comment above. When running `mlflow ui`, you need to specify the tracking URI using `--backend-store-uri` like:
> 
> ```
> mlflow ui --backend-store-uri sqlite:///mlflow.db
> ```

This worked out thank you so much. In any case we can modify the mlflow serve command in a similar manner so that I can serve a particular model based on run ID

**Comment by ArchanGhosh** [comment]
@harupy when using this command
`>mlflow models serve --model-uri runs:/e2fc4c05beea4b9a89096037b58921cd/model`

I am getting the following error:

`Traceback (most recent call last):
  File "C:\Python\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python Scripts\mlops\env\Scripts\mlflow.exe\__main__.py", line 7, in <module>
  File "C:\Python Scripts\mlops\env\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python Scripts\mlops\env\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Python Scripts\mlops\env\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Python Scripts\mlops\env\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Python Scripts\mlops\env\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python Scripts\mlops\env\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Python Scripts\mlops\env\lib\site-packages\mlflow\models\cli.py", line 104, in serve
    return get_flavor_backend(
  File "C:\Python Scripts\mlops\env\lib\site-packages\mlflow\models\flavor_backend_registry.py", line 45, in get_flavor_backend
    local_path = _download_artifact_from_uri(
  File "C:\Python Scripts\mlops\env\lib\site-packages\mlflow\tracking\artifact_utils.py", line 100, in _download_artifact_from_uri
    return get_artifact_repository(artifact_uri=root_uri).download_artifacts(
  File "C:\Python Scripts\mlops\env\lib\site-packages\mlflow\store\artifact\artifact_repository_registry.py", line 107, in get_artifact_repository
    return _artifact_repository_registry.get_artifact_repository(artifact_uri)
  File "C:\Python Scripts\mlops\env\lib\site-packages\mlflow\store\artifact\artifact_repository_registry.py", line 73, in get_artifact_repository
    return repository(artifact_uri)
  File "C:\Python Scripts\mlops\env\lib\site-packages\mlflow\store\artifact\runs_artifact_repo.py", line 26, in __init__
    uri = RunsArtifactRepository.get_underlying_uri(artifact_uri)
  File "C:\Python Scripts\mlops\env\lib\site-packages\mlflow\store\artifact\runs_artifact_repo.py", line 39, in get_underlying_uri
    uri = get_artifact_uri(run_id, artifact_path, tracking_uri)
  File "C:\Python Scripts\mlops\env\lib\site-packages\mlflow\tracking\artifact_utils.py", line 47, in get_artifact_uri
    run = store.get_run(run_id)
  File "C:\Python Scripts\mlops\env\lib\site-packages\mlflow\store\tracking\file_store.py", line 623, in get_run
    run_info = self._get_run_info(run_id)
  File "C:\Python Scripts\mlops\env\lib\site-packages\mlflow\store\tracking\file_store.py", line 649, in _get_run_info
    run_info = self._get_run_info_from_dir(run_dir)
  File "C:\Python Scripts\mlops\env\lib\site-packages\mlflow\store\tracking\file_store.py", line 657, in _get_run_info_from_dir
    meta = FileStore._read_yaml(run_dir, FileStore.META_DATA_FILE_NAME)
  File "C:\Python Scripts\mlops\env\lib\site-packages\mlflow\store\tracking\file_store.py", line 1082, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
  File "C:\Python Scripts\mlops\env\lib\site-packages\mlflow\store\tracking\file_store.py", line 1075, in _read_helper
    result = read_yaml(root, file_name)
  File "C:\Python Scripts\mlops\env\lib\site-packages\mlflow\utils\file_utils.py", line 182, in read_yaml
    raise MissingConfigException("Yaml file '%s' does not exist." % file_path)
mlflow.exceptions.MissingConfigException: Yaml file 'C:\Python Scripts\mlops\heartstroke\mlruns\1\e2fc4c05beea4b9a89096037b58921cd\meta.yaml' does not exist.`

**Comment by harupy** [comment]
@ArchanGhosh Can you try running this command?

```
MLFLOW_TRACKING_URI=sqlite:///mlflow.db mlflow models serve --model-uri runs:/e2fc4c05beea4b9a89096037b58921cd/model
```

**Comment by ArchanGhosh** [comment]
> @ArchanGhosh Can you try running this command?
> 
> ```shell
> MLFLOW_TRACKING_URI=sqlite:///mlflow.db mlflow models serve --model-uri runs:/e2fc4c05beea4b9a89096037b58921cd/model
> ```

Not Working as MLFLOW_TRACKING_URI is not being recognized both in upper and lower case

**Comment by harupy** [comment]
This looks like an issue. `mlflow models serve` doesn't seem to provide a way to set the tracking URI.

**Comment by WeichenXu123** [comment]
In my test `MLFLOW_TRACKING_URI=sqlite:///mlflow.db mlflow models serve --model-uri runs:/...` works, and according to the code:  https://github.com/mlflow/mlflow/blob/c2cf7cfa3487e15cda112cb1823fe00ef4bf3f8d/mlflow/tracking/_tracking_service/utils.py#L135 it should work.

What's your error running that ? @ArchanGhosh

**Comment by ArchanGhosh** [comment]
``` python
>MLFLOW_TRACKING_URI=sqlite:///mlflow.db mlflow models serve --model-uri runs:/e2fc4c05beea4b9a89096037b58921cd/model
'MLFLOW_TRACKING_URI' is not recognized as an internal or external command,
operable program or batch file.

>mlflow_tracking_uri=sqlite:///mlflow.db mlflow models serve --model-uri runs:/
e2fc4c05beea4b9a89096037b58921cd/model
'mlflow_tracking_uri' is not recognized as an internal or external command,
operable program or batch file.
```

this is the error I am getting

**Comment by WeichenXu123** [comment]
ah... I got it. You are using Windows, in Windows we cannot set environment variable in this way.

**Comment by WeichenXu123** [comment]
@ArchanGhosh 

You can do:

```
set MLFLOW_TRACKING_URI=sqlite:///mlflow.db
mlflow models serve --model-uri runs:/e2fc4c05beea4b9a89096037b58921cd/model
```
it should work on windows. :)

**Comment by ArchanGhosh** [comment]
> @ArchanGhosh
> 
> You can do:
> 
> ```
> set MLFLOW_TRACKING_URI=sqlite:///mlflow.db
> mlflow models serve --model-uri runs:/e2fc4c05beea4b9a89096037b58921cd/model
> ```
> 
> it should work on windows. :)
'''python
>set MLFLOW_TRACKING_URI=sqlite:///mlflow.db

>mlflow models serve --model-uri runs:/e2fc4c05beea4b9a89096037b58921cd/sklearn-model
2022/12/07 11:38:19 INFO mlflow.models.flavor_backend_registry: Selected backend for flavor 'python_function'
Traceback (most recent call last):
  File "C:\Python\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python Scripts\mlops\env\Scripts\mlflow.exe\__main__.py", line 7, in <module>
  File "C:\Python Scripts\mlops\env\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python Scripts\mlops\env\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Python Scripts\mlops\env\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Python Scripts\mlops\env\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Python Scripts\mlops\env\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python Scripts\mlops\env\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Python Scripts\mlops\env\lib\site-packages\mlflow\models\cli.py", line 104, in serve
    return get_flavor_backend(
  File "C:\Python Scripts\mlops\env\lib\site-packages\mlflow\pyfunc\backend.py", line 226, in serve
    return self.prepare_env(local_path).execute(
  File "C:\Python Scripts\mlops\env\lib\site-packages\mlflow\pyfunc\backend.py", line 100, in prepare_env
    activate_cmd = _get_or_create_virtualenv(
  File "C:\Python Scripts\mlops\env\lib\site-packages\mlflow\utils\virtualenv.py", line 327, in _get_or_create_virtualenv
    _validate_pyenv_is_available()
  File "C:\Python Scripts\mlops\env\lib\site-packages\mlflow\utils\virtualenv.py", line 63, in _validate_pyenv_is_available
    raise MlflowException(
mlflow.exceptions.MlflowException: Could not find the pyenv binary. See https://github.com/pyenv-win/pyenv-win#installation for installation instructions.
'''

This is also being shown, not sure what is this if you can point it out

**Comment by harupy** [comment]
@ArchanGhosh Does `./mlruns/1/e2fc4c05beea4b9a89096037b58921cd/artifacts/model` exist?

**Comment by ArchanGhosh** [comment]
> @ArchanGhosh Does `./mlruns/1/e2fc4c05beea4b9a89096037b58921cd/artifacts/model` exist?

It does, and when I changed the adressing to sklearn-model, the name with which I have saved the artifact path it dropped a pyenv error. Not sure what that is.

**Comment by harupy** [comment]
That means you need to install pyenv. You can add `--env-manager local` to use the local environment.

```
mlflow models serve --env-manager local --model-uri runs:/e2fc4c05beea4b9a89096037b58921cd/model
```

**Comment by ArchanGhosh** [comment]
To amalgamate incase someone is having similar issues, on windows:
Use
```python
set MLFLOW_TRACKING_URI=sqlite:///mlflow.db 
```
Followed by

```python
mlflow models serve --env-manager local --model-uri runs:/%run-id%/%artifact-model-name-used-while-saving%
```
Also to access mlflow ui while having a SQlite storage reference:

```python

mlflow ui --backend-store-uri sqlite:///mlflow.db
```
