### ISSUE TITLE
[FR] Sequential Execution of Machine Learning pipeline for general use-case using MLflow's MLPROJECT file

### ISSUE THREAD

**Issue by ApoorveK** [mlflow/mlflow#7480]
### Willingness to contribute

Yes. I would be willing to contribute this feature with guidance from the MLflow community.

### Proposal Summary

Currently, In MLFow, the sequential execution for different components is missing. Even though there are multiple entry-points possible, but case of multiple components to be executed sequentially with single entry-point hasn't been observed here (in my personal knowledge of MLFlow till now, but i could be wrong though)

### Motivation

> #### What is the use case for this feature?
For use-case/s, where ML pipeline for any general ML application will get better support from inclusion of this feature.

> #### Why is this use case valuable to support for MLflow users in general?
It will give users better control over the pipeline, where the single MLproject can contain whole pipeline covering all the components, irrespective if it is for production or for just dev environment.

> #### Why is this use case valuable to support for your project(s) or organization?
Our organisation is currently looking for open-source alternatives for ML experiment tracking and monitoring, and found that although MLFlow can serve some of the purpose, yet the current form might not be helpful entirely for our use-case. So me as representative from my organisation, is ready to commit time to make this resource more robust and adaptable for our use-case.

> #### Why is it currently difficult to achieve this use case?
There are tools present in current MLOps environment which are either too use-specific or complex to use or are proprietary. We as startup although are looking to have more robust and future proof MLOps infrastructure, so that we don't need to focus ourself again and again on migration. Hence looking for some tools to incorporate in our MLOps ecosystem which are easy to adapt for our different use cases (our's is using different speech and text models for our product).

### Details

So, the whole idea of this proposal is to make MLproject file for MLflow sufficient enough to include whole ML-pipeline for different use-cases i.e. each component mentioned in MLproject file to be part of whole pipeline which are contributing to pipeline independently and yet executing sequence-wise. Adding this feature while help in controlling the flow over the whole MLproject as it will give user the power of early-stopping of the pipeline if certain criteria doesn't get fulfilled by working components while sequential execution.

I initially started exploring the MLflow with above motive, yet was not able to configure current tool to serve above mentioned case. So I am filing this proposal, just incase if this feature is really isn't part of current MLFlow.

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [X] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [X] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [X] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [X] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [X] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [X] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dbczumar** [comment]
Hi @ApoorveK , thank you for filing this feature request. Does the multi-step workflow example in https://github.com/mlflow/mlflow/tree/master/examples/multistep_workflow meet your requirements? If not, can you shared proposed interfaces for pipeline integration with MLflow Projects?

**Comment by ApoorveK** [comment]
Hello @dbczumar thanks for replying, actually our initial work which needed MLflow, has taken above example as reference. But the above example was not effective for pipeline execution.

Steps we did:
* Using MLProject file, we were trying to define a ML-pipeline (similar to above example, which involves different steps like data ingestion, training, model validation).
* But there were some specific cases where we need early automated termination of this MLproject file execution, which currently is not being handled by current working of MLProject file.

So we decided to fill-up for some feature request towards MLFlow community to see if someone else also would like to have this feature (i.e. more control over pipeline-like projects through MLProject file, like 'sequential execution of acyclic components' or 'execution with attached cyclic components' as well.)

Mostly this feature only require changes in following parts of MLFlow:
* Working of MLproject file: [ sub-Proposal-1: To include some type of threshold type variable which both can be logged and can be responsible for next component execution, based on this threshold behaviour. it could be initialised through MLproject file and can be used for other components. ] [ sub-Proposal-2: having sub-feature, which can help in defining behaviour of components, whether they will be part of acyclic (non-repeated execution through pipeline) or cyclic (repeated execution through pipeline) Executions.]
* Some Changes in dashboard as their will be multiple components in which some components might require logging and would need Dashboard.

Apart from it, these changes requires mostly no changes in UI/UX part, so it will not have dependencies on other maintainers. 

Also, have gone across MLFlow recipe (experimental part) but am not sure whether it will be good utility for our case so left it out in general.

**Comment by ApoorveK** [comment]
@BenWilson2 @dbczumar @harupy @WeichenXu123 please let me know the status, also please suggest a alternative for communication so that i can reach out to you all (either mail, or some slack channel or something else) as i have some other use-case specific queries which i believe needed to be catered.

**Comment by B-Step62** [comment]
Multi-step sequential pipelines are better expressed by orchestrating multiple `mlflow run` calls (see the multistep-workflow example) rather than a single MLproject, and MLflow Projects is in maintenance mode. Closing as not planned, feel free to reopen with a concrete proposal if needed.
