### ISSUE TITLE
[FR] Add REST API endpoint to retrieve all unique experiment tags

### ISSUE THREAD

**Issue by ddl-ebrown** [mlflow/mlflow#7514]
### Willingness to contribute

Yes. I would be willing to contribute this feature with guidance from the MLflow community.

### Proposal Summary

Getting a list of tags across all runs for an experiment is helpful when building tooling to add new tags to a given experiment / experiment run. When adding tags through a user interface, having an autocomplete type list of existing tags can help prevent the addition of misspelled or otherwise similar, but mismatched tags.

Furthermore, when providing tooling to search through experiment runs for runs with a specific tag, it's necessary to know the tag values in use.

An API to retrieve all new unique tag names is necessary to support either of these scenarios.

### Motivation

> #### What is the use case for this feature?

We're providing tooling on top of mlflow APIs and the current method for adding tags is error-prone without having a list of in-use tags. Similarly, auto-completing search criteria for tags is impractical over large sets of runs (that include many duplicates)

> #### Why is this use case valuable to support for MLflow users in general?

I suspect the MLflow UI has similar needs

> #### Why is this use case valuable to support for your project(s) or organization?

This would prevent tagging errors from the UI. This would also improve the latency / performance of building an autocomplete list for searching against existing tags.

> #### Why is it currently difficult to achieve this use case?

Currently the only way to build this list is to return all runs for an experiment to a client, merge all the tags together, then remove duplicates. This is quite expensive compared to returning a unique list directly from the database.

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [X] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [X] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by WeichenXu123** [comment]
My thoughts:

If adding the feature you suggested, to make the retrieving all unique experiment tags efficient, we need to maintain a separate table that stores the full tag key list across all runs / experiments, when adding a new tag , we updates the table. This still brings overhead and increase code complexity.

Another option is, you can implement tag autocomplete in upper layer software. In upper layer software, you can pre-define a tag key list that should be used, and generating autocomplete hint from the pre-defined tag key list. WDYT ?

**Comment by WeichenXu123** [comment]
@ddl-ebrown 

We discussed this in our team, our discussion conclusion is that it's too much overhead to implement compared to the amount of benefit.

But we're working on including hints for parameters, tags, and metrics in the search UI based on values loaded in the frontend. This should make it a bit easier for users to search from the UI.

**Comment by WeichenXu123** [comment]
@ddl-ebrown 

For your case, I think you can implement a patch for "log_XXX" as a workaround, in patching code, you can capture the tag / metric /param key and then store the key in your own storage system (used for autocompletion).
