### ISSUE TITLE
[BUG] Server with proxied artifact storage settings

### ISSUE THREAD

**Issue by jinserk** [mlflow/mlflow#7556]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

- Client: 2.0.1
- Tracking server: 2.0.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 20.04
- **Python version**: 3.10.8
- **yarn version, if running the dev UI**: NA

### Describe the problem

I'v tried the server configuration with proxied artifact storage (https://www.mlflow.org/docs/latest/tracking.html#scenario-5-mlflow-tracking-server-enabled-with-proxied-artifact-storage-access), however:
- the command doesn't have an option `--artifact-destination-root`
- when I use the command line
```
mlflow server --backend-store-uri postgresql://user:password@postgres:5432/mlflowdb --default-artifact-root gs//bucket_name --host 0.0.0.0 --serve-artifacts --artifacts-destination gs//bucket_name
```
  it looks like to work when I create an experiment from web ui, but the python code `mlflow.create_experiment(<exp-name>)` still make a local dir as `mlruns/<exp-id>`.

### Tracking information

System information: Linux #62~20.04.1-Ubuntu SMP Tue Nov 22 21:24:20 UTC 2022
Python version: 3.10.8
MLflow version: 2.0.1
MLflow module location: /usr/local/lib/python3.10/site-packages/mlflow/__init__.py
Tracking URI: postgresql://postgres:JoK92KI5DCkF54zA@10.204.208.3:5432/mlflow
Registry URI: postgresql://postgres:JoK92KI5DCkF54zA@10.204.208.3:5432/mlflow
MLflow environment variables: {
    "MLFLOW_TRACKING_URI": "postgresql://postgres:JoK92KI5DCkF54zA@10.204.208.3:5432/mlflow"
}
MLflow dependencies: {
    "click": "8.0.4",
    "cloudpickle": "2.2.0",
    "databricks-cli": "0.17.4",
    "entrypoints": "0.4",
    "gitpython": "3.1.29",
    "pyyaml": "5.4.1",
    "protobuf": "3.19.6",
    "pytz": "2022.7",
    "requests": "2.28.1",
    "packaging": "21.3",
    "importlib-metadata": "5.1.0",
    "sqlparse": "0.4.3",
    "alembic": "1.9.0",
    "docker": "6.0.1",
    "Flask": "2.2.2",
    "numpy": "1.23.4",
    "scipy": "1.9.3",
    "pandas": "1.5.2",
    "querystring-parser": "1.2.4",
    "sqlalchemy": "1.4.45",
    "scikit-learn": "1.1.3",
    "pyarrow": "10.0.1",
    "shap": "0.41.0",
    "markdown": "3.4.1",
    "matplotlib": "3.6.2",
    "gunicorn": "20.1.0",
    "Jinja2": "3.1.2"
}

### Code to reproduce issue

```python
import mlflow

mlflow.create_experiment("example-mlflow-3")
```

### Stack trace

Not available

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [X] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by jinserk** [comment]
When I check the `store` and its `artifact_root_uri`, it says:
```
from mlflow.tracking import _get_store, get_tracking_uri

store = _get_store()

print(store.db_uri)
print(store.artifact_root_uri)
```
```
postgresql://postgres:<pass>@<db-host>:5432/mlflow
postgresql://postgres:<pass>@<db-host>:5432/mlflow
./mlruns
```

**Comment by jinserk** [comment]
I found that I had to put the env var `MLFLOW_TRACKING_URI` to the server URI but I put the DB URI. After fixed, it works as expected.
