### ISSUE TITLE
[BUG] Exception: Run with UUID my_exp_number is already active. To start a new run, first end the current run with mlflow.end_run(). To start a nested run, call start_run with nested=True despite using set_tags

### ISSUE THREAD

**Issue by monajalal** [mlflow/mlflow#7680]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute
No.

### MLflow version
MLflow version: 1.30.0
- Client: 1.x.y
- Tracking server: 1.x.y

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Python version**:
- **yarn version, if running the dev UI**:

### Describe the problem

Could you please help why I keep getting this error? I even added set_tag as you see below and I still get the error. I am running this on an Azure Compute Cluster with 1 node.

```
ws = Workspace.get(name='mlops-test', subscription_id='number', resource_group='resource-group')

print('ws in train is: ', ws)


mlflow.set_tracking_uri(ws.get_mlflow_tracking_uri())

print("MLflow version:", mlflow.__version__)
print("Tracking URI:", mlflow.get_tracking_uri())
print("Artifact URI:", mlflow.get_artifact_uri())

tags = {"team": "team-name",
        "dataset": "dataset-name", 
        "model": "model-name"}
exp_name = "exp-name"
exp_id = mlflow.create_experiment(exp_name)
mlflow.set_experiment(experiment_name=exp_name)
mlflow.set_tags(tags)

run = mlflow.start_run()

```
```
Performing interactive authentication. Please follow the instructions on the terminal.
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code CODE to authenticate.
Interactive authentication successfully completed.
ws in train is:  Workspace.create(name='mlops-test', subscription_id='SUBSCRIPTION_ID', resource_group='RESOURCE-GROUP')

Cleaning up all outstanding Run operations, waiting 300.0 seconds
1 items cleaning up...
Cleanup took 0.06771636009216309 seconds
Traceback (most recent call last):
  File "train.py", line 127, in <module>
    run = mlflow.start_run()
  File "/azureml-envs/azureml_number/lib/python3.8/site-packages/mlflow/tracking/fluent.py", line 271, in start_run
    raise Exception(
Exception: Run with UUID my_exp_number is already active. To start a new run, first end the current run with mlflow.end_run(). To start a nested run, call start_run with nested=True


```

### Tracking information

```
MLflow version: 1.30.0
Tracking URI: azureml://eastus2.api.azureml.ms/mlflow/v1.0/subscriptions/numbers/resourceGroups/RESOURCE-GROUP/providers/Microsoft.MachineLearningServices/workspaces/mlops-test?
Artifact URI: azureml://experiments/my_exp/runs/my_exp_number/artifacts
```

### Code to reproduce issue

```
REPLACE_ME
```

### Stack trace

```
REPLACE_ME
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [X] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [X] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by monajalal** [comment]
I added the `mlflow.start_run()` inside a `try-catch` phrase and ran it again and here's some further logs:

```
print(platform.python_implementation())
print(platform.python_version())
print(platform.uname())
ws = Workspace.get(name='mlops-test', subscription_id='number', resource_group='resource-group')

print('ws in train is: ', ws)


mlflow.set_tracking_uri(ws.get_mlflow_tracking_uri())
print("MLflow version:", mlflow.__version__)
print("Tracking URI:", mlflow.get_tracking_uri())
print("Artifact URI:", mlflow.get_artifact_uri())

tags = {"team": "team-name",
        "dataset": "dataset-name", 
        "model": "model-name",
        "bs" : "16"}

exp_name = "experiment-name"
exp_id = mlflow.create_experiment(exp_name)
mlflow.set_experiment(experiment_name=exp_name)
mlflow.set_tags(tags)

try:
    run = mlflow.start_run()
except Exception as e:
    print(e)
    traceback.print_exc(file=sys.stdout)
    traceback.print_exc(*sys.exc_info())
```

Here's the output:
```
CPython
3.8.13
uname_result(system='Linux', node='number', release='5.0.0-1036-azure', version='#38-Ubuntu SMP Sun Mar 22 21:27:21 UTC 2020', machine='x86_64', processor='x86_64')
Performing interactive authentication. Please follow the instructions on the terminal.
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code CODE to authenticate.
Interactive authentication successfully completed.
ws in train is:  Workspace.create(name='mlops-test', subscription_id='number', resource_group='resource-group')
MLflow version: 1.30.0
Tracking URI: azureml://eastus2.api.azureml.ms/mlflow/v1.0/subscriptions/number/resourceGroups/resource-group/providers/Microsoft.MachineLearningServices/workspaces/mlops-test?
Artifact URI: azureml://experiments/my-exp/runs/my-exp_number/artifacts
Run with UUID my-exp_number is already active. To start a new run, first end the current run with mlflow.end_run(). To start a nested run, call start_run with nested=True
Traceback (most recent call last):
  File "train.py", line 133, in <module>
    run = mlflow.start_run()
  File "/azureml-envs/azureml_number/lib/python3.8/site-packages/mlflow/tracking/fluent.py", line 271, in start_run
    raise Exception(
Exception: Run with UUID my-exp_number is already active. To start a new run, first end the current run with mlflow.end_run(). To start a nested run, call start_run with nested=True
Cleaning up all outstanding Run operations, waiting 300.0 seconds
1 items cleaning up...
Cleanup took 0.048985958099365234 seconds
Traceback (most recent call last):
  File "train.py", line 133, in <module>
    run = mlflow.start_run()
  File "/azureml-envs/azureml_number/lib/python3.8/site-packages/mlflow/tracking/fluent.py", line 271, in start_run
    raise Exception(
Exception: Run with UUID my-exp_number is already active. To start a new run, first end the current run with mlflow.end_run(). To start a nested run, call start_run with nested=True

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 137, in <module>
    traceback.print_exc(*sys.exc_info())
  File "/azureml-envs/azureml_number/lib/python3.8/traceback.py", line 163, in print_exc
    print_exception(*sys.exc_info(), limit=limit, file=file, chain=chain)
  File "/azureml-envs/azureml_number/lib/python3.8/traceback.py", line 103, in print_exception
    for line in TracebackException(
  File "/azureml-envs/azureml_number/lib/python3.8/traceback.py", line 508, in __init__
    self.stack = StackSummary.extract(
  File "/azureml-envs/azureml_number/lib/python3.8/traceback.py", line 340, in extract
    if limit >= 0:
TypeError: '>=' not supported between instances of 'type' and 'int'
```

**Comment by monajalal** [comment]
using end before start resolved the problem but is there a better solution? 

```
ws = Workspace.get(name='mlops-test', subscription_id='9be1367a-bcc9-4275-8b3d-a0469f4119fa', resource_group='ard-ml')

print('ws in train is: ', ws)


mlflow.set_tracking_uri(ws.get_mlflow_tracking_uri())
# #mlflow.set_tracking_uri('azureml://eastus2.api.azureml.ms/mlflow/v1.0/subscriptions/9be1367a-bcc9-4275-8b3d-a0469f4119fa/resourceGroups/ard-ml/providers/Microsoft.MachineLearningServices/workspaces/mlops-test')
print("MLflow version:", mlflow.__version__)
print("Tracking URI:", mlflow.get_tracking_uri())
print("Artifact URI:", mlflow.get_artifact_uri())

tags = {"team": "ARD",
        "dataset": "mini PalLoc6D", 
        "model": "pose",
        "bs" : "16"}

exp_name = "dope6d"
exp_id = mlflow.create_experiment(exp_name)
mlflow.set_experiment(experiment_name=exp_name)
mlflow.set_tags(tags)

try:
    mlflow.end_run()
    run = mlflow.start_run()
except Exception as e:
    print(e)
    traceback.print_exc(file=sys.stdout)
    traceback.print_exc(*sys.exc_info())
```

**Comment by harupy** [comment]
@monajalal Let me break down what happens in your code:

```python
ws = Workspace.get(name='mlops-test', subscription_id='number', resource_group='resource-group')

print('ws in train is: ', ws)


mlflow.set_tracking_uri(ws.get_mlflow_tracking_uri())

print("MLflow version:", mlflow.__version__)
print("Tracking URI:", mlflow.get_tracking_uri())
print("Artifact URI:", mlflow.get_artifact_uri())

tags = {"team": "team-name",
        "dataset": "dataset-name", 
        "model": "model-name"}
exp_name = "exp-name"
exp_id = mlflow.create_experiment(exp_name)
mlflow.set_experiment(experiment_name=exp_name)
# ------ we can ignore the code above this line

mlflow.set_tags(tags)  # This creates an active run

run = mlflow.start_run()  # As an active run already exists, this line fails to start a run.
```

We can fix this

```
with mlflow.start_run():
    mlflow.set_tags(...)
```

**Comment by harupy** [comment]
I'd recommend always using `with mlflow.start_run()` when logging something.

**Comment by harupy** [comment]
Thanks for using MLflow!

**Comment by monajalal** [comment]
Thank you so much for your explanation, this is very helpful :)
