### ISSUE TITLE
[BUG] setting different artifact URI from tracking uri

### ISSUE THREAD

**Issue by HitHereX** [mlflow/mlflow#7749]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

- Client: 2.1.1
- Tracking server: 2.1.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.05
- **Python version**: Python 3.8.5
- **yarn version, if running the dev UI**:

### Describe the problem

Hello. Thank you for taking your time in my question.

I am trying to set up a mlflow remote tracking server for my team.
- command for server is like below:
```mlflow server --backend-store-uri postgresql://mlflow_user:mlflow@localhost/mlflow_db --default-artifact-root gs://<my_bucket_name>```

in this way, I intended to track metrics for log in my local db, and log the model in my GCP bucket.

however, when I run train to log metrics and model in my local(which I intend to have metrics logged in posgreSQL db, put model in GCP. I tested push/pulling files with GCP works)it keeps trying to its model by SFTP and it doesn't work.

I ran train by the command below:
```
mlflow.set_tracking_uri("http://127.0.0.1:5000")
mlflow.set_registry_uri("gs://<my_bucket_name>")
```
 below is the image of mlflow.doctor() 
![image](https://user-images.githubusercontent.com/112468961/215037622-f6d12890-0f99-4458-9ec4-a166d38e1bf5.png)

I thought `mlflow.set_registry_uri()` sets artifact root in client, but it doesn't seem so. 
It keeps trying to connect into SFTP and gives following error
It seems like I should assign artifact root individually in client, but I don't get how.
Can I get some info or help about this issue?

Since this is my first time using MLflow, there might be lack of info in my question. Feel free to let me know.
Thanks.

### Tracking information

```
mlflow server --backend-store-uri postgresql://mlflow_user:mlflow@localhost/mlflow_db --default-artifact-root gs://<my_bucket_name>
```

### Code to reproduce issue

```
import mlflow

mlflow.set_tracking_uri("http://127.0.0.1:5000")
mlflow.set_registry_uri("gs://<my_bucket_name>")

##train code##

mlflow.pytorch.log_model(self.model, 'model.pt')
```

### Stack trace
```
Traceback (most recent call last):
  File "train.py", line 34, in <module>
    main(config)
  File "train.py", line 25, in main
    trainer.train()
  File "/opt/ml/final-project-level3-nlp-06/classification/trainer/cnn_trainer.py", line 83, in train
    mlflow.pytorch.log_model(self.model, 'model.pt')
  File "/opt/conda/lib/python3.8/site-packages/mlflow/pytorch/__init__.py", line 310, in log_model
    return Model.log(
  File "/opt/conda/lib/python3.8/site-packages/mlflow/models/model.py", line 487, in log
    mlflow.tracking.fluent.log_artifacts(local_path, mlflow_model.artifact_path)
  File "/opt/conda/lib/python3.8/site-packages/mlflow/tracking/fluent.py", line 810, in log_artifacts
    MlflowClient().log_artifacts(run_id, local_dir, artifact_path)
  File "/opt/conda/lib/python3.8/site-packages/mlflow/tracking/client.py", line 1048, in log_artifacts
    self._tracking_client.log_artifacts(run_id, local_dir, artifact_path)
  File "/opt/conda/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py", line 448, in log_artifacts
    self._get_artifact_repo(run_id).log_artifacts(local_dir, artifact_path)
  File "/opt/conda/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py", line 416, in _get_artifact_repo
    artifact_repo = get_artifact_repository(artifact_uri)
  File "/opt/conda/lib/python3.8/site-packages/mlflow/store/artifact/artifact_repository_registry.py", line 106, in get_artifact_repository
    return _artifact_repository_registry.get_artifact_repository(artifact_uri)
  File "/opt/conda/lib/python3.8/site-packages/mlflow/store/artifact/artifact_repository_registry.py", line 72, in get_artifact_repository
    return repository(artifact_uri)
  File "/opt/conda/lib/python3.8/site-packages/mlflow/store/artifact/sftp_artifact_repo.py", line 82, in __init__
    connections = [pysftp.Connection(**self.config) for _ in range(self.max_workers)]
  File "/opt/conda/lib/python3.8/site-packages/mlflow/store/artifact/sftp_artifact_repo.py", line 82, in <listcomp>
    connections = [pysftp.Connection(**self.config) for _ in range(self.max_workers)]
  File "/opt/conda/lib/python3.8/site-packages/pysftp.py", line 150, in __init__
    self._transport = paramiko.Transport((host, port))
  File "/opt/conda/lib/python3.8/site-packages/paramiko/transport.py", line 441, in __init__
    raise SSHException(
paramiko.ssh_exception.SSHException: Unable to connect to 49.50.164.14: [Errno 110] Connection timed out
```

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by HitHereX** [comment]
got the solution during the weekends. 

I have typed ```export MLFLOW_TRACKING_URI="xxx.xxx.xxx.xxx:5000"``` in terminal before 
which was not an accessible port from outside.
I changed the ```export MLFLOW_TRACKING_URI = "xxx.xxx.xxx.xxx:remote_accessible_port"``` 
and ```mlflow.set_tracking_uri()``` as same one.


registry URI was somewhere else(i don't exactly know, but itk it's something different from artifact storage)
If anyone knows difference between registry URI and artifact_storage_URI, please let me know.
Thanks.
