### ISSUE TITLE
[BUG] MLFlow is using a lot of disk space

### ISSUE THREAD

**Issue by fzyzcjy** [mlflow/mlflow#7794]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### MLflow version

- Client: latest
- Tracking server: latest

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: ubuntu
- **Python version**: latest
- **yarn version, if running the dev UI**: n/a

### Describe the problem

Hi thanks for the helpful library! I realize MLflow tracking api is consuming a lot of disk space. For example, the sqlite.db itself alone is already 500MB with only lightly using it for (effectively) weeks. So you can imagine, it will grow to 10GB or 100GB as time goes by, and as the experiments parallelism is getting bigger (e.g. get more cards to do auto tune).

Thus, is it expected, or is it a bug? I am willing to contribute to fix it.

### Tracking information

```shell
N/A
```

### Code to reproduce issue

```
N/A
```

### Stack trace

```
N/A
```

### Other info / logs

```
N/A
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [X] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [X] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dbczumar** [comment]
Hi @fzyzcjy , we recommend deleting and cleaning up runs that you no longer need via the `mlflow gc` command (https://mlflow.org/docs/latest/cli.html#mlflow-gc). Additionally, you may see better scalability over time by using MySQL, Postgres, or SQLServer. Thank you for using MLflow!

**Comment by fzyzcjy** [comment]
Thank you!
