### ISSUE TITLE
[BUG] getting a URL rather than URI so that we can access the experiment tracking conveniently over the browser similar to W&B 

### ISSUE THREAD

**Issue by monajalal** [mlflow/mlflow#7806]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 1.x.y
- Tracking server: 1.x.y

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Python version**:
- **yarn version, if running the dev UI**:

### Describe the problem

I am using Azure Pipeline for job run and I am using mlflow in `train.py` for experiment tracking.

When the job started training, I got two URIs from mlflow but I do not know where in Azure I could access them or how to convert these URIs to URLs so I can access my experiments.

Here are the what I receive:

```
MLflow version: 1.30.0

Tracking URI: azureml://eastus2.api.azureml.ms/mlflow/v1.0/subscriptions/MY_SUBS_NUM/resourceGroups/MY_RESOURCE_GROUP/providers/Microsoft.MachineLearningServices/workspaces/MLops-Test?

Artifact URI: azureml://experiments/DOPE-pipeline/runs/MY_RUN_NUMBER/artifacts
```

I saw the following but still not sure how to access the browser version or Azure UI version of the MLflow experiment tracking.

https://github.com/mlflow/mlflow/issues/5722#issuecomment-1103325368

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```
REPLACE_ME
```

### Stack trace

```
REPLACE_ME
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [X] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dbczumar** [comment]
Hi @wamartin-aml can you provide guidance regarding how to view the Azure UI for an MLflow Experiment?

**Comment by wamartin-aml** [comment]
@monajalal, the general Azure guidance is to log into the [Azure Machine Learning studio](https://ml.azure.com/) and find your AzureML workspace, navigate to the Jobs tab, and find your experiment there. Do you have access to this workspace view?

Adding @santiagxf a) in case he has a better option b) so that he can track this ask in case we want to build a more direct solution
