### ISSUE TITLE
[BUG] Error:"Violation of PRIMARY KEY constraint 'latest_metric_pk' key error" when the same metric is logged twice with different capitalization

### ISSUE THREAD

**Issue by prestrepoh** [mlflow/mlflow#7857]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 2.1.1
- Tracking server: 2.1.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **Python version**: 3.9
- **yarn version, if running the dev UI**: n/a

### Describe the problem

When you try to log a metric that had already been logged for a run id (with a new value), the expected behavior is the following:

The new metric is inserted in the table 'metrics'
The old metric is replaced in the table  'latest_metrics' by the new one.

However, if you try to log the same metric twice with different capitalization (e.g 'my value' and then 'my Value') you will get the error:

`mlflow.exceptions.RestException: BAD_REQUEST: (pymssql._pymssql.IntegrityError) (2627, b"Violation of PRIMARY KEY constraint 'latest_metric_pk'. Cannot insert duplicate key in object 'latest_metrics'. The duplicate key value is (my Value, 5ddc2789ede647078de11caa48eb8198).DB-Lib error message 20018, severity 14:\nGeneral SQL Server error: Check messages from the SQL Server\n")
[SQL: INSERT INTO latest_metrics ([key], value, timestamp, step, is_nan, run_uuid) VALUES (%(key)s, %(value)s, %(timestamp)s, %(step)s, %(is_nan)s, %(run_uuid)s)]
[parameters: {'key': 'my Value', 'value': 0.5, 'timestamp': 1676622460911, 'step': 0, 'is_nan': 0, 'run_uuid': '5ddc2789ede647078de11caa48eb8198'}]`

The error happens when you log the metrics one by one, but also when you use mlflow.log_metrics() to log them in batch

### Tracking information

```shell
System information: Windows 10.0.17763
Python version: 3.9.7
MLflow version: 2.1.1
MLflow module location: XXXXXXXXXXXXXX
Tracking URI: XXXXXXXXXXXXXX
Registry URI: XXXXXXXXXXXXXX
MLflow environment variables: 
  MLFLOW_CLIENT_SECRET: XXXXXXXXXXXXXX
  MLFLOW_TRACKING_URI: XXXXXXXXXXXXXX
MLflow dependencies: 
  Flask: 2.0.3
  Jinja2: 3.1.2
  alembic: 1.9.3
  click: 8.1.3
  cloudpickle: 2.2.1
  databricks-cli: 0.17.4
  docker: 6.0.1
  entrypoints: 0.4
  gitpython: 3.1.30
  importlib-metadata: 3.10.1
  markdown: 3.3.4
  matplotlib: 3.4.3
  numpy: 1.22.4
  packaging: 22.0
  pandas: 1.3.5
  protobuf: 3.19.6
  pyarrow: 5.0.0
  pytz: 2022.7.1
  pyyaml: 5.4.1
  querystring-parser: 1.2.4
  requests: 2.28.2
  scikit-learn: 1.2.1
  scipy: 1.6.3
  shap: 0.41.0
  sqlalchemy: 1.4.46
  sqlparse: 0.4.3
  waitress: 2.1.2
```
command used to start tracking server:
mlflow server --backend-store-uri=mssql+pymssql:XXXXXXXXXXX --default-artifact-root=XXXXXXXXXX --host=0.0.0.0

### Code to reproduce issue

```
    tracking_uri = "http://localhost:5000"
    mlflow_client = mlflow.tracking.MlflowClient(tracking_uri=tracking_uri)

    experiment_id = mlflow_client.create_experiment('my experiment')
    run_id = mlflow_client.create_run(experiment_id=experiment_id).info.run_id

    mlflow_client.log_metric(run_id, 'my value', 0, step=0)
    mlflow_client.log_metric(run_id, 'my Value', 1, step=0)

```

### Stack trace

```
Traceback (most recent call last):
  File "XXXXXXXXXXXXXXX\my_mlflow_experiments2.py", line 16, in <module>
    main()
  File "XXXXXXXXXXXXXXX\my_mlflow_experiments2.py", line 13, in main
    mlflow_client.log_metric(run_id, 'my Value', 1, step=0)
  File "XXXXXXXXXXXXXXX\lib\site-packages\mlflow\tracking\client.py", line 687, in log_metric
    self._tracking_client.log_metric(run_id, key, value, timestamp, step)
  File "XXXXXXXXXXXXXXX\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 286, in log_metric
    self.store.log_metric(run_id, metric)
  File "XXXXXXXXXXXXXXX\lib\site-packages\mlflow\store\tracking\rest_store.py", line 196, in log_metric
    self._call_endpoint(LogMetric, req_body)
  File "XXXXXXXXXXXXXXX\lib\site-packages\mlflow\store\tracking\rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "XXXXXXXXXXXXXXX\lib\site-packages\mlflow\utils\rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "XXXXXXXXXXXXXXX\lib\site-packages\mlflow\utils\rest_utils.py", line 207, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: BAD_REQUEST: (pymssql._pymssql.IntegrityError) (2627, b"Violation of PRIMARY KEY constraint 'latest_metric_pk'. Cannot insert duplicate key in object 'dbo.latest_metrics'. The duplicate key value is (my Value, 56c20cc403164085b5dd2fe95f3533f7).DB-Lib error message 20018, severity 14:\nGeneral SQL Server error: Check messages from the SQL Server\n")
[SQL: INSERT INTO latest_metrics ([key], value, timestamp, step, is_nan, run_uuid) VALUES (%(key)s, %(value)s, %(timestamp)s, %(step)s, %(is_nan)s, %(run_uuid)s)]
[parameters: {'key': 'my Value', 'value': 1.0, 'timestamp': 1676628568844, 'step': 0, 'is_nan': 0, 'run_uuid': '56c20cc403164085b5dd2fe95f3533f7'}]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [X] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [X] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment]
Hi @prestrepoh thanks for reporting this. The root cause is the default collation properties on the primary key index for the metric history table. In MSSQL, collation is set by default as "CI" (case insensitive), while the proper primary key restriction we should be using for this DB is "CS" (case sensitive). We'll take a look at what this would require.

**Comment by BenWilson2** [comment]
After some discussion amongst the maintainers, we feel like the effort to fix this for MSSQL will involve a great deal of potentially backwards incompatible changes. While we know this is a bug, the effort and risk in correcting it is pretty substantial (extensive database migration for all users who utilize MSSQL). 
Is there any particular reason why you need to modify the casing on your metrics? Can renaming them function as a workaround for you?

**Comment by prestrepoh** [comment]
Hello @BenWilson2

Thanks for your answer. 

To be honest, it is not a big problem for us, since we can simply lowercase the metrics. I just wanted to report the bug, since it took me a while to find the root cause of the error in our code, and I think it would be interesting for you to know. :)

**Comment by BenWilson2** [comment]
Thank you for the report. We're likely going to address this the next time that we need to perform a database migration update in a future release. Thanks again!
