### ISSUE TITLE
[BUG] Registering transformers (huggingface) model with remote tracking (proxy server) with mlflow.pyfunc.log_model

### ISSUE THREAD

**Issue by michalisfrangos** [mlflow/mlflow#7897]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 2.1.1
- Tracking server: 2.1.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Python version**:
- Server: Linux Ubuntu, python version: 3.9.16
- Client: Linux Ubuntu, python version: 3.9.16

### Describe the problem

I have set up remote tracking [option 5](https://mlflow.org/docs/latest/tracking.html#id36) .  I believe things are setup up OK as I can add a model to registry using the documentation example [HERE](https://mlflow.org/docs/latest/model-registry.html#id7) and view all artifacts. My backend is PostgreSQL and my Artifact destination is a digital ocean SPACES bucket (equivalent to S3).  

The command I use to run the server in docker is 
```
mlflow server \
    --host 0.0.0.0 \
    --port 5000 \
    --backend-store-uri ${DATABASE_URL} \
    --artifacts-destination s3://${BUCKET} \
    --serve-artifacts
```
and the following environment variables are set on server: 
```
${AWS_SECRET_ACCESS_KEY} 
${AWS_ACCESS_KEY_ID}
${MLFLOW_S3_ENDPOINT_URL}
${BUCKET}
${DATABASE_URL}
```
However, the mlflow run terminates unexpectedly with the error message 'KILLED' or waits forever when I try to register a transformer model (huggingface model) with `mlflow.pyfunc.log_model() `.  I can see 2 artifacts for the run:  MLModel and conda.yml,  and status is set to 'failed'

### Tracking information

```
System information: Linux #44-Ubuntu SMP Wed Jun 22 14:20:53 UTC 2022
Python version: 3.9.16
MLflow version: 2.1.1
MLflow module location: /root/miniconda3/envs/myenv/lib/python3.9/site-packages/mlflow/__init__.py
Tracking URI: https://xxxxxx.ondigitalocean.app
Registry URI: https://xxxxxx.ondigitalocean.app
Active experiment ID: 10
Active run ID: 123456
Active run artifact URI: mlflow-artifacts:/10/123456/artifacts
MLflow dependencies: 
  Flask: 2.2.3
  Jinja2: 3.1.2
  alembic: 1.9.4
  click: 8.1.3
  cloudpickle: 2.2.1
  databricks-cli: 0.17.4
  docker: 6.0.1
  entrypoints: 0.4
  gitpython: 3.1.31
  gunicorn: 20.1.0
  importlib-metadata: 5.2.0
  markdown: 3.4.1
  matplotlib: 3.7.0
  numpy: 1.23.5
  packaging: 22.0
  pandas: 1.5.3
  protobuf: 4.22.0
  pyarrow: 10.0.1
  pytz: 2022.7.1
  pyyaml: 6.0
  querystring-parser: 1.2.4
  requests: 2.28.2
  scikit-learn: 1.2.1
  scipy: 1.10.1
  shap: 0.41.0
  sqlalchemy: 1.4.46
  sqlparse: 0.4.3
/root/miniconda3/envs/myenv/lib/python3.9/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
```

### Code to reproduce issue

test_model.py

```
import mlflow
from mlflow.models.signature import infer_signature
from mlflow.models import ModelSignature
import pandas as pd
import json
import os
from transformers import pipeline, AutoTokenizer, AutoModelForSequenceClassification

TRACKING_URL = "https://xxxxxx.ondigitalocean.app"

class Model(mlflow.pyfunc.PythonModel):
    def __init__(self):
        super().__init__()

        self.tokenizer = AutoTokenizer.from_pretrained("ProsusAI/finbert")
        self.model =  AutoModelForSequenceClassification.from_pretrained("ProsusAI/finbert")  # CRASHES IF UNCOMMENTED
        self.classifier = pipeline("sentiment-analysis", model=self.model, tokenizer=self.tokenizer) # CRASHES IF UNCOMMENTED

    def predict(self, context, model_input):
        return self.classifier(model_input.text.to_list())
    
if __name__ == "__main__":
    mlflow.set_tracking_uri(TRACKING_URL)
    mlflow.set_experiment("test0")
        
    model = Model()
    with mlflow.start_run() as run:
        model_input = json.dumps([{'name': 'text', 'type': 'string'}])
        model_output = json.dumps([{'name': 'label', 'type': 'string'}, {'name': 'score', 'type': 'double'}])
        signature = ModelSignature.from_dict({'inputs': model_input, 'outputs': model_output})
        mlflow.doctor()
        mlflow.pyfunc.log_model(artifact_path="model",
                                python_model=model,
                                registered_model_name="finbert-pretrained",
                                signature=signature)
```

### Stack trace

Waits for a long time and then it prints just
`KILLED` 

or prints:

```/root/miniconda3/envs/myenv/lib/python3.9/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils. warnings.warn("Setuptools is replacing distutils.")

Traceback (most recent call last):
  File "/root/miniconda3/envs/myenv/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/root/miniconda3/envs/myenv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 878, in urlopen
    return self.urlopen(
  File "/root/miniconda3/envs/myenv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 878, in urlopen
    return self.urlopen(
  File "/root/miniconda3/envs/myenv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 878, in urlopen
    return self.urlopen(
  [Previous line repeated 2 more times]
  File "/root/miniconda3/envs/myenv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 868, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/root/miniconda3/envs/myenv/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='xxxx.ondigitalocean.app', port=xx): Max retries exceeded with url: /api/2.0/mlflow-artifacts/artifacts/10/xxxxxxx/artifacts/model/python_model.pkl (Caused by ResponseError('too many 504 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/myenv/lib/python3.9/site-packages/mlflow/utils/rest_utils.py", line 167, in http_request
    return _get_http_response_with_retries(
  File "/root/miniconda3/envs/myenv/lib/python3.9/site-packages/mlflow/utils/rest_utils.py", line 98, in _get_http_response_with_retries
    return session.request(method, url, **kwargs)
  File "/root/miniconda3/envs/myenv/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/miniconda3/envs/myenv/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/root/miniconda3/envs/myenv/lib/python3.9/site-packages/requests/adapters.py", line 556, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='xxxxxx.ondigitalocean.app', port=xx) Max retries exceeded with url: /api/2.0/mlflow-artifacts/artifacts/10/xxxxxx/artifacts/model/python_model.pkl (Caused by ResponseError('too many 504 error responses'))

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/root/local/finbert.py", line 73, in <module>
    mlflow.pyfunc.log_model(artifact_path="model",
  File "/root/miniconda3/envs/myenv/lib/python3.9/site-packages/mlflow/pyfunc/__init__.py", line 1578, in log_model
    return Model.log(
  File "/root/miniconda3/envs/myenv/lib/python3.9/site-packages/mlflow/models/model.py", line 487, in log
    mlflow.tracking.fluent.log_artifacts(local_path, mlflow_model.artifact_path)
  File "/root/miniconda3/envs/myenv/lib/python3.9/site-packages/mlflow/tracking/fluent.py", line 810, in log_artifacts
    MlflowClient().log_artifacts(run_id, local_dir, artifact_path)
  File "/root/miniconda3/envs/myenv/lib/python3.9/site-packages/mlflow/tracking/client.py", line 1048, in log_artifacts
    self._tracking_client.log_artifacts(run_id, local_dir, artifact_path)
  File "/root/miniconda3/envs/myenv/lib/python3.9/site-packages/mlflow/tracking/_tracking_service/client.py", line 448, in log_artifacts
    self._get_artifact_repo(run_id).log_artifacts(local_dir, artifact_path)
  File "/root/miniconda3/envs/myenv/lib/python3.9/site-packages/mlflow/store/artifact/http_artifact_repo.py", line 40, in log_artifacts
    self.log_artifact(os.path.join(root, f), artifact_dir)
  File "/root/miniconda3/envs/myenv/lib/python3.9/site-packages/mlflow/store/artifact/http_artifact_repo.py", line 25, in log_artifact
    resp = http_request(self._host_creds, endpoint, "PUT", data=f)
  File "/root/miniconda3/envs/myenv/lib/python3.9/site-packages/mlflow/utils/rest_utils.py", line 185, in http_request
    raise MlflowException(f"API request to {url} failed with exception {e}")
mlflow.exceptions.MlflowException: API request to https://xxxxxx.ondigitalocean.app/api/2.0/mlflow-artifacts/artifacts/10/xxxxxxx/artifacts/model/python_model.pkl failed with exception HTTPSConnectionPool(host='xxxxxx.ondigitalocean.app', port=xx): Max retries exceeded with url: /api/2.0/mlflow-artifacts/artifacts/10/xxxxxxx/artifacts/model/python_model.pkl (Caused by ResponseError('too many 504 error responses'))
```

### Other info / logs

# Tracking server logs

```[mlflow] [2023-02-25 18:43:13] [2023-02-25 18:43:13 +0000] [18] [INFO] Starting gunicorn 20.1.0
[mlflow] [2023-02-25 18:43:13] [2023-02-25 18:43:13 +0000] [18] [INFO] Listening at: http://0.0.0.0:5000 (18)
[mlflow] [2023-02-25 18:43:13] [2023-02-25 18:43:13 +0000] [18] [INFO] Using worker: sync
[mlflow] [2023-02-25 18:43:13] [2023-02-25 18:43:13 +0000] [19] [INFO] Booting worker with pid: 19
[mlflow] [2023-02-25 18:43:13] [2023-02-25 18:43:13 +0000] [20] [INFO] Booting worker with pid: 20
[mlflow] [2023-02-25 18:43:13] [2023-02-25 18:43:13 +0000] [21] [INFO] Booting worker with pid: 21
[mlflow] [2023-02-25 18:43:13] [2023-02-25 18:43:13 +0000] [22] [INFO] Booting worker with pid: 22
[mlflow] [2023-02-25 18:43:17] OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
[mlflow] [2023-02-25 18:43:17] OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
[mlflow] [2023-02-25 18:43:17] OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
[mlflow] [2023-02-25 18:43:17] OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
[mlflow] [2023-02-25 18:43:20] OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
[mlflow] [2023-02-25 18:43:20] OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
[mlflow] [2023-02-25 18:43:21] OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
[mlflow] [2023-02-25 18:43:21] OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
[mlflow] [2023-02-25 19:35:14] [2023-02-25 19:35:14 +0000] [18] [CRITICAL] WORKER TIMEOUT (pid:22)
[mlflow] [2023-02-25 19:35:15] [2023-02-25 19:35:15 +0000] [22] [INFO] Worker exiting (pid: 22)
[mlflow] [2023-02-25 19:35:15] [2023-02-25 19:35:15 +0000] [250] [INFO] Booting worker with pid: 250
[mlflow] [2023-02-25 19:35:16] OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
[mlflow] [2023-02-25 19:35:17] OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
[mlflow] [2023-02-25 19:35:48] [2023-02-25 19:35:48 +0000] [18] [CRITICAL] WORKER TIMEOUT (pid:21)
[mlflow] [2023-02-25 19:35:48] [2023-02-25 19:35:48 +0000] [21] [INFO] Worker exiting (pid: 21)
[mlflow] [2023-02-25 19:35:49] [2023-02-25 19:35:49 +0000] [277] [INFO] Booting worker with pid: 277
[mlflow] [2023-02-25 19:35:50] OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
[mlflow] [2023-02-25 19:35:51] OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
[mlflow] [2023-02-25 19:36:27] [2023-02-25 19:36:27 +0000] [18] [CRITICAL] WORKER TIMEOUT (pid:20)
[mlflow] [2023-02-25 19:36:27] [2023-02-25 19:36:27 +0000] [20] [INFO] Worker exiting (pid: 20)
[mlflow] [2023-02-25 19:36:27] [2023-02-25 19:36:27 +0000] [304] [INFO] Booting worker with pid: 304
[mlflow] [2023-02-25 19:36:29] OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
[mlflow] [2023-02-25 19:36:30] OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
[mlflow] [2023-02-25 19:37:09] [2023-02-25 19:37:09 +0000] [18] [CRITICAL] WORKER TIMEOUT (pid:304)
[mlflow] [2023-02-25 19:37:09] [2023-02-25 19:37:09 +0000] [304] [INFO] Worker exiting (pid: 304)
[mlflow] [2023-02-25 19:37:09] [2023-02-25 19:37:09 +0000] [334] [INFO] Booting worker with pid: 334
[mlflow] [2023-02-25 19:37:10] OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
[mlflow] [2023-02-25 19:37:11] OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
[mlflow] [2023-02-25 19:37:58] [2023-02-25 19:37:58 +0000] [18] [CRITICAL] WORKER TIMEOUT (pid:19)
[mlflow] [2023-02-25 19:37:58] [2023-02-25 19:37:58 +0000] [19] [INFO] Worker exiting (pid: 19)
[mlflow] [2023-02-25 19:37:59] [2023-02-25 19:37:59 +0000] [361] [INFO] Booting worker with pid: 361
[mlflow] [2023-02-25 19:38:00] OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
[mlflow] [2023-02-25 19:38:01] OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
[mlflow] [2023-02-25 19:48:50] [2023-02-25 19:48:50 +0000] [18] [CRITICAL] WORKER TIMEOUT (pid:334)
[mlflow] [2023-02-25 19:48:50] [2023-02-25 19:48:50 +0000] [334] [INFO] Worker exiting (pid: 334)
[mlflow] [2023-02-25 19:48:51] [2023-02-25 19:48:51 +0000] [408] [INFO] Booting worker with pid: 408
[mlflow] [2023-02-25 19:48:52] OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
[mlflow] [2023-02-25 19:48:53] OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
[mlflow] [2023-02-25 19:49:25] [2023-02-25 19:49:25 +0000] [18] [CRITICAL] WORKER TIMEOUT (pid:408)
[mlflow] [2023-02-25 19:49:25] [2023-02-25 19:49:25 +0000] [408] [INFO] Worker exiting (pid: 408)
[mlflow] [2023-02-25 19:49:25] [2023-02-25 19:49:25 +0000] [440] [INFO] Booting worker with pid: 440
[mlflow] [2023-02-25 19:49:27] OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
[mlflow] [2023-02-25 19:49:28] OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
[mlflow] [2023-02-25 20:25:25] [2023-02-25 20:25:25 +0000] [18] [CRITICAL] WORKER TIMEOUT (pid:440)
[mlflow] [2023-02-25 20:25:25] [2023-02-25 20:25:25 +0000] [440] [INFO] Worker exiting (pid: 440)
[mlflow] [2023-02-25 20:25:25] [2023-02-25 20:25:25 +0000] [511] [INFO] Booting worker with pid: 511
[mlflow] [2023-02-25 20:25:26] OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
[mlflow] [2023-02-25 20:25:27] OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
[mlflow] [2023-02-25 20:25:58] [2023-02-25 20:25:58 +0000] [18] [CRITICAL] WORKER TIMEOUT (pid:511)
[mlflow] [2023-02-25 20:25:58] [2023-02-25 20:25:58 +0000] [511] [INFO] Worker exiting (pid: 511)
[mlflow] [2023-02-25 20:25:59] [2023-02-25 20:25:59 +0000] [538] [INFO] Booting worker with pid: 538
[mlflow] [2023-02-25 20:26:00] OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
[mlflow] [2023-02-25 20:26:01] OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
[mlflow] [2023-02-25 20:36:26] [2023-02-25 20:36:26 +0000] [18] [CRITICAL] WORKER TIMEOUT (pid:538)
[mlflow] [2023-02-25 20:36:26] [2023-02-25 20:36:26 +0000] [538] [INFO] Worker exiting (pid: 538)
[mlflow] [2023-02-25 20:36:27] [2023-02-25 20:36:27 +0000] [574] [INFO] Booting worker with pid: 574
[mlflow] [2023-02-25 20:36:28] OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
[mlflow] [2023-02-25 20:36:29] OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
[mlflow] [2023-02-25 20:37:00] [2023-02-25 20:37:00 +0000] [18] [CRITICAL] WORKER TIMEOUT (pid:361)
[mlflow] [2023-02-25 20:37:00] [2023-02-25 20:37:00 +0000] [361] [INFO] Worker exiting (pid: 361)
[mlflow] [2023-02-25 20:37:01] [2023-02-25 20:37:01 +0000] [18] [WARNING] Worker with pid 361 was terminated due to signal 9
[mlflow] [2023-02-25 20:37:01] [2023-02-25 20:37:01 +0000] [601] [INFO] Booting worker with pid: 601
[mlflow] [2023-02-25 20:37:02] OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
[mlflow] [2023-02-25 20:37:04] OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
[mlflow] [2023-02-25 21:05:04] [2023-02-25 21:05:04 +0000] [18] [CRITICAL] WORKER TIMEOUT (pid:574)
[mlflow] [2023-02-25 21:05:04] [2023-02-25 21:05:04 +0000] [574] [INFO] Worker exiting (pid: 574)
[mlflow] [2023-02-25 21:05:04] [2023-02-25 21:05:04 +0000] [654] [INFO] Booting worker with pid: 654
[mlflow] [2023-02-25 21:05:05] OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
[mlflow] [2023-02-25 21:05:07] OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
[mlflow] [2023-02-25 21:05:38] [2023-02-25 21:05:38 +0000] [18] [CRITICAL] WORKER TIMEOUT (pid:250)
[mlflow] [2023-02-25 21:05:39] [2023-02-25 21:05:39 +0000] [250] [INFO] Worker exiting (pid: 250)
[mlflow] [2023-02-25 21:05:39] [2023-02-25 21:05:39 +0000] [681] [INFO] Booting worker with pid: 681
[mlflow] [2023-02-25 21:05:40] OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
[mlflow] [2023-02-25 21:05:41] OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
[mlflow] [2023-02-25 21:41:31] [2023-02-25 21:41:31 +0000] [18] [CRITICAL] WORKER TIMEOUT (pid:601)
[mlflow] [2023-02-25 21:41:31] [2023-02-25 21:41:31 +0000] [601] [INFO] Worker exiting (pid: 601)
[mlflow] [2023-02-25 21:41:32] [2023-02-25 21:41:32 +0000] [715] [INFO] Booting worker with pid: 715
[mlflow] [2023-02-25 21:41:33] OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
[mlflow] [2023-02-25 21:41:34] OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
[mlflow] [2023-02-25 21:42:05] [2023-02-25 21:42:05 +0000] [18] [CRITICAL] WORKER TIMEOUT (pid:277)
[mlflow] [2023-02-25 21:42:05] [2023-02-25 21:42:05 +0000] [277] [INFO] Worker exiting (pid: 277)
[mlflow] [2023-02-25 21:42:05] [2023-02-25 21:42:05 +0000] [742] [INFO] Booting worker with pid: 742
[mlflow] [2023-02-25 21:42:07] OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
[mlflow] [2023-02-25 21:42:08] OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
[mlflow] [2023-02-25 21:42:43] [2023-02-25 21:42:43 +0000] [18] [CRITICAL] WORKER TIMEOUT (pid:742)
[mlflow] [2023-02-25 21:42:43] [2023-02-25 21:42:43 +0000] [742] [INFO] Worker exiting (pid: 742)
[mlflow] [2023-02-25 21:42:43] [2023-02-25 21:42:43 +0000] [769] [INFO] Booting worker with pid: 769
[mlflow] [2023-02-25 21:42:44] OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
[mlflow] [2023-02-25 21:42:45] OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
[mlflow] [2023-02-25 21:43:24] [2023-02-25 21:43:24 +0000] [18] [CRITICAL] WORKER TIMEOUT (pid:769)
[mlflow] [2023-02-25 21:43:24] [2023-02-25 21:43:24 +0000] [769] [INFO] Worker exiting (pid: 769)
[mlflow] [2023-02-25 21:43:25] [2023-02-25 21:43:25 +0000] [796] [INFO] Booting worker with pid: 796
[mlflow] [2023-02-25 21:43:26] OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
[mlflow] [2023-02-25 21:43:27] OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
[mlflow] [2023-02-25 21:44:14] [2023-02-25 21:44:14 +0000] [18] [CRITICAL] WORKER TIMEOUT (pid:654)
[mlflow] [2023-02-25 21:44:14] [2023-02-25 21:44:14 +0000] [654] [INFO] Worker exiting (pid: 654)
[mlflow] [2023-02-25 21:44:14] [2023-02-25 21:44:14 +0000] [823] [INFO] Booting worker with pid: 823
[mlflow] [2023-02-25 21:44:15] OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
[mlflow] [2023-02-25 21:44:17] OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
[mlflow] [2023-02-25 21:45:20] [2023-02-25 21:45:20 +0000] [18] [CRITICAL] WORKER TIMEOUT (pid:823)
[mlflow] [2023-02-25 21:45:20] [2023-02-25 21:45:20 +0000] [823] [INFO] Worker exiting (pid: 823)
[mlflow] [2023-02-25 21:45:20] [2023-02-25 21:45:20 +0000] [850] [INFO] Booting worker with pid: 850
[mlflow] [2023-02-25 21:45:21] OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
[mlflow] [2023-02-25 21:45:22] OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
[mlflow] [2023-02-25 21:52:14] [2023-02-25 21:52:14 +0000] [18] [CRITICAL] WORKER TIMEOUT (pid:715)
[mlflow] [2023-02-25 21:52:14] [2023-02-25 21:52:14 +0000] [715] [INFO] Worker exiting (pid: 715)
[mlflow] [2023-02-25 21:52:15] [2023-02-25 21:52:15 +0000] [18] [WARNING] Worker with pid 715 was terminated due to signal 9
[mlflow] [2023-02-25 21:52:15] [2023-02-25 21:52:15 +0000] [893] [INFO] Booting worker with pid: 893
[mlflow] [2023-02-25 21:52:20] OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
[mlflow] [2023-02-25 21:52:23] OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
[mlflow] [2023-02-25 21:52:49] [2023-02-25 21:52:49 +0000] [18] [CRITICAL] WORKER TIMEOUT (pid:681)
[mlflow] [2023-02-25 21:52:49] [2023-02-25 21:52:49 +0000] [681] [INFO] Worker exiting (pid: 681)
[mlflow] [2023-02-25 21:52:50] [2023-02-25 21:52:50 +0000] [924] [INFO] Booting worker with pid: 924
[mlflow] [2023-02-25 21:52:51] OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
[mlflow] [2023-02-25 21:52:52] OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
[mlflow] [2023-02-25 21:53:23] [2023-02-25 21:53:23 +0000] [18] [CRITICAL] WORKER TIMEOUT (pid:796)
[mlflow] [2023-02-25 21:53:23] [2023-02-25 21:53:23 +0000] [796] [INFO] Worker exiting (pid: 796)
[mlflow] [2023-02-25 21:53:23] [2023-02-25 21:53:23 +0000] [951] [INFO] Booting worker with pid: 951
[mlflow] [2023-02-25 21:53:24] OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
[mlflow] [2023-02-25 21:53:26] OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
[mlflow] [2023-02-25 21:54:00] [2023-02-25 21:54:00 +0000] [18] [CRITICAL] WORKER TIMEOUT (pid:924)
[mlflow] [2023-02-25 21:54:00] [2023-02-25 21:54:00 +0000] [924] [INFO] Worker exiting (pid: 924)
[mlflow] [2023-02-25 21:54:01] [2023-02-25 21:54:01 +0000] [978] [INFO] Booting worker with pid: 978
[mlflow] [2023-02-25 21:54:02] OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
[mlflow] [2023-02-25 21:54:03] OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
[mlflow] [2023-02-25 21:54:42] [2023-02-25 21:54:42 +0000] [18] [CRITICAL] WORKER TIMEOUT (pid:978)
[mlflow] [2023-02-25 21:54:42] [2023-02-25 21:54:42 +0000] [978] [INFO] Worker exiting (pid: 978)
[mlflow] [2023-02-25 21:54:42] [2023-02-25 21:54:42 +0000] [1005] [INFO] Booting worker with pid: 1005
[mlflow] [2023-02-25 21:54:44] OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
[mlflow] [2023-02-25 21:54:45] OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
[mlflow] [2023-02-25 21:55:32] [2023-02-25 21:55:32 +0000] [18] [CRITICAL] WORKER TIMEOUT (pid:1005)
[mlflow] [2023-02-25 21:55:32] [2023-02-25 21:55:32 +0000] [1005] [INFO] Worker exiting (pid: 1005)
[mlflow] [2023-02-25 21:55:32] [2023-02-25 21:55:32 +0000] [1032] [INFO] Booting worker with pid: 1032
[mlflow] [2023-02-25 21:55:33] OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
[mlflow] [2023-02-25 21:55:34] OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
[mlflow] [2023-02-25 21:56:37] [2023-02-25 21:56:37 +0000] [18] [CRITICAL] WORKER TIMEOUT (pid:893)
[mlflow] [2023-02-25 21:56:37] [2023-02-25 21:56:37 +0000] [893] [INFO] Worker exiting (pid: 893)
[mlflow] [2023-02-25 21:56:38] [2023-02-25 21:56:38 +0000] [1065] [INFO] Booting worker with pid: 1065
[mlflow] [2023-02-25 21:56:39] OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
[mlflow] [2023-02-25 21:56:40] OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
```

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations
