### ISSUE TITLE
[BUG] Tracking server says "ConnectionRefusedError" when listing artifacts in UI using FTP artifact store

### ISSUE THREAD

**Issue by davideCremona** [mlflow/mlflow#8006]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 1.25.1
- Tracking server: 1.20.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20
- **Python version**: 3.8.10
- **yarn version, if running the dev UI**:

### Describe the problem

I have this setup described in a docker-compose file:

```text
version: "3.3"
services:
    db:
        image: mysql/mysql-server:latest
        container_name: mlflow_db
        environment:
            MYSQL_ROOT_PASSWORD: <root_psw_mysql>
            MYSQL_USER: <mlflow_mysql_user>
            MYSQL_PASSWORD: <mlflow_mysql_psw>
            MYSQL_DATABASE: mlflow_db
        expose:
          - "3306"
        ports:
          - "3306:3306"
        volumes:
          - /home/DATI/mlflow/mysql:/var/lib/mysql
        networks:
          - backend
        restart: always

    web:
        build: /home/drb/docker_images/mlflow-tracking
        image: mlflow-tracking:latest
        container_name: mlflow_server
        expose:
          - "5000"
        ports:
          - "8088:5000"
        networks:
          - backend
        depends_on:
          - "db"
          - "ftp"
        links:
          - "ftp"
        restart: always
        command: bash -c "mlflow db upgrade ${BACKEND_STORE_URI} || true && mlflow server --backend-store-uri ${BACKEND_STORE_URI} --default-artifact-root ${ARTIFACT_STORE_URI} --host 0.0.0.0"

    ftp:
        image: delfer/alpine-ftp-server
        container_name: mlflow_ftp
        environment:
            USERS: <mlflow_ftp_user>|<mlflow_ftp_psw>
        ports:
          - "21:21"
        volumes:
          - /home/DATI/mlflow/artifact_store:/home/mlflow/
        networks:
          - backend
        restart: always

networks:
    backend:
        driver: bridge
```

And this is the .env file:
```
# MLFLOW
BACKEND_STORE_URI=mysql+pymysql://<mlflow_mysql_user>:<mlflow_mysql_psw>@db:3306/mlflow_db
ARTIFACT_STORE_URI=ftp://<mlflow_ftp_user>:<mlflow_ftp_psw>@10.11.12.2/home/mlflow
```

`10.11.12.2` is the IP of the machine that is running the services.

I can correctly ping mlflow_server from mlflow_ftp and vice versa

I can correctly connect to ftp server using `ftp ftp` command inside the mlflow_server

When I execute a python script from my local machine, it crashes showing me this error:
script:
```python
import mlflow

def setup_mlflow(config_mlflow):
    mlflow_tracking_uri = config_mlflow['tracking_uri']
    mlflow.set_tracking_uri(mlflow_tracking_uri)

    exp_name = config_mlflow['experiment_name']
    experiment = mlflow.get_experiment_by_name(exp_name)
    if experiment is None:
        experiment_id = mlflow.create_experiment(name=exp_name)
    else:
        experiment_id = experiment.experiment_id

    return experiment_id


config_mlflow = {
  "tracking_uri": "http://10.11.12.2:8088",
  "experiment_name": "TEST_mlflow",
  "run_name": "time_upload_artifact"
}


experiment_id = setup_mlflow(config_mlflow)

mlflow_run_name = config_mlflow['run_name']

with mlflow.start_run(experiment_id=experiment_id, run_name=mlflow_run_name):

    mlflow.log_param('test_type', "artifacts")

    # single file
    print("logging single file")
    mlflow.log_artifact("/home/drb/Desktop/tests/test_mlflow/file.txt")
    
    # directory
    print("logging directory")
    mlflow.log_artifacts("snapshots_best")
```

error:
```text
Traceback (most recent call last):
  File "test_artifacts.py", line 35, in <module>
    mlflow.log_artifact("/home/drb/Desktop/tests/test_mlflow/file.txt")
  File "/usr/local/lib/python3.8/dist-packages/mlflow/tracking/fluent.py", line 693, in log_artifact
    MlflowClient().log_artifact(run_id, local_path, artifact_path)
  File "/usr/local/lib/python3.8/dist-packages/mlflow/tracking/client.py", line 955, in log_artifact
    self._tracking_client.log_artifact(run_id, local_path, artifact_path)
  File "/usr/local/lib/python3.8/dist-packages/mlflow/tracking/_tracking_service/client.py", line 337, in log_artifact
    artifact_repo.log_artifact(local_path, artifact_path)
  File "/usr/local/lib/python3.8/dist-packages/mlflow/store/artifact/ftp_artifact_repo.py", line 73, in log_artifact
    ftp.storbinary("STOR " + os.path.basename(local_file), f)
  File "/usr/lib/python3.8/ftplib.py", line 494, in storbinary
    with self.transfercmd(cmd, rest) as conn:
  File "/usr/lib/python3.8/ftplib.py", line 389, in transfercmd
    return self.ntransfercmd(cmd, rest)[0]
  File "/usr/lib/python3.8/ftplib.py", line 350, in ntransfercmd
    conn = socket.create_connection((host, port), self.timeout,
  File "/usr/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```

but the run is correctly created.

When I try to view the run page in the UI I see this error in the docker-compose logs:

```text
mlflow_ftp | 2023-03-10T18:03:35.323453730Z Fri Mar 10 18:03:35 2023 [pid 38] CONNECT: Client "172.23.0.1"
mlflow_ftp | 2023-03-10T18:03:35.348564531Z Fri Mar 10 18:03:35 2023 [pid 37] [mlflow] OK LOGIN: Client "172.23.0.1"
mlflow_server | 2023-03-10T18:03:35.350971380Z 2023/03/10 18:03:35 ERROR mlflow.server: Exception on /ajax-api/2.0/preview/mlflow/artifacts/list [GET]
mlflow_server | 2023-03-10T18:03:35.351018938Z Traceback (most recent call last):
mlflow_server | 2023-03-10T18:03:35.351032049Z   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
mlflow_server | 2023-03-10T18:03:35.351041969Z     response = self.full_dispatch_request()
mlflow_server | 2023-03-10T18:03:35.351050276Z   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
mlflow_server | 2023-03-10T18:03:35.351059073Z     rv = self.handle_user_exception(e)
mlflow_server | 2023-03-10T18:03:35.351068596Z   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
mlflow_server | 2023-03-10T18:03:35.351083612Z     rv = self.dispatch_request()
mlflow_server | 2023-03-10T18:03:35.351097766Z   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
mlflow_server | 2023-03-10T18:03:35.351122159Z     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
mlflow_server | 2023-03-10T18:03:35.351136104Z   File "/usr/local/lib/python3.8/site-packages/mlflow/server/handlers.py", line 214, in wrapper
mlflow_server | 2023-03-10T18:03:35.351150190Z     return func(*args, **kwargs)
mlflow_server | 2023-03-10T18:03:35.351164264Z   File "/usr/local/lib/python3.8/site-packages/mlflow/server/handlers.py", line 487, in _list_artifacts
mlflow_server | 2023-03-10T18:03:35.351180076Z     artifact_entities = _get_artifact_repo(run).list_artifacts(path)
mlflow_server | 2023-03-10T18:03:35.351194153Z   File "/usr/local/lib/python3.8/site-packages/mlflow/store/artifact/ftp_artifact_repo.py", line 104, in list_artifacts
mlflow_server | 2023-03-10T18:03:35.351209750Z     artifact_files = ftp.nlst(list_dir)
mlflow_server | 2023-03-10T18:03:35.351223167Z   File "/usr/local/lib/python3.8/ftplib.py", line 549, in nlst
mlflow_server | 2023-03-10T18:03:35.351237716Z     self.retrlines(cmd, files.append)
mlflow_server | 2023-03-10T18:03:35.351252000Z   File "/usr/local/lib/python3.8/ftplib.py", line 458, in retrlines
mlflow_server | 2023-03-10T18:03:35.351266776Z     with self.transfercmd(cmd) as conn, \
mlflow_server | 2023-03-10T18:03:35.351281988Z   File "/usr/local/lib/python3.8/ftplib.py", line 389, in transfercmd
mlflow_server | 2023-03-10T18:03:35.351321847Z     return self.ntransfercmd(cmd, rest)[0]
mlflow_server | 2023-03-10T18:03:35.351337616Z   File "/usr/local/lib/python3.8/ftplib.py", line 350, in ntransfercmd
mlflow_server | 2023-03-10T18:03:35.351351730Z     conn = socket.create_connection((host, port), self.timeout,
mlflow_server | 2023-03-10T18:03:35.351366354Z   File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
mlflow_server | 2023-03-10T18:03:35.351380933Z     raise err
mlflow_server | 2023-03-10T18:03:35.351394385Z   File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
mlflow_server | 2023-03-10T18:03:35.351408797Z     sock.connect(sa)
mlflow_server | 2023-03-10T18:03:35.351423108Z ConnectionRefusedError: [Errno 111] Connection refused
```

Is there anyone that can help me with this issue? Thank you!

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```
REPLACE_ME
```

### Stack trace

```
REPLACE_ME
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [X] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [X] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [X] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dbczumar** [comment]
Hi @davideCremona , thank you for filing this issue. To isolate the problem, can you check whether the following script runs successfully?:

```
from ftplib import FTP

import posixpath
import urllib.parse

from urllib.parse import unquote

```
artifact_uri = "ftp://<mlflow_ftp_user>:<mlflow_ftp_psw>@10.11.12.2/home/mlflow"
parsed = urllib.parse.urlparse(artifact_uri)
config = {
            "host": parsed.hostname,
            "port": 21 if parsed.port is None else parsed.port,
            "username": parsed.username,
            "password": parsed.password,
}
ftp = FTP()
ftp.connect(self.config["host"], self.config["port"])
ftp.login(self.config["username"], self.config["password"])
ftp.cwd("/home/mlflow")
```

**Comment by davideCremona** [comment]
Unfortunately I switched to S3 instead of FTP using MINIO.

Anyway, thank you for your support and work on mlflow.

**Comment by twmht** [comment]
@dbczumar 

I also hit this issue with sftp server,

```
mlflow server --host 1.1.1.1 --backend-store-uri mysql://acer:test@1.1.1.1:3306/mlflow_artifacts  --default-artifact-root sftp://acer:test@11.1.1.1:2222/home/acer/upload
```

I can access the ftp server with filezilla, so  i think the sftp server setup is okay.

Here are my test script to reprodcue the problem

```
  import os
  from random import random, randint

  import mlflow
  from mlflow import log_metric, log_param, log_artifacts

  if __name__ == "__main__":
      print("Running mlflow_tracking.py")

      mlflow.set_tracking_uri("http://10.36.172.141:5000")
      mlflow.set_experiment("my-experiment")


      log_param("param1", randint(0, 100))

      log_metric("foo", random())
      log_metric("foo", random() + 1)
      log_metric("foo", random() + 2)

      if not os.path.exists("outputs"):
          os.makedirs("outputs")
      with open("outputs/test.txt", "w") as f:
          f.write("hello world!")

      log_artifacts("outputs")
```

Here are the error messges

```
  File "/home/shared/mlflow/examples/quickstart/mlflow_tracking.py", line 25, in <module>
    log_artifacts("outputs")
  File "/home/acer/.pyenv/versions/training_env/lib/python3.9/site-packages/mlflow/tracking/fluent.py", line 818, in log_artifacts
    MlflowClient().log_artifacts(run_id, local_dir, artifact_path)
  File "/home/acer/.pyenv/versions/training_env/lib/python3.9/site-packages/mlflow/tracking/client.py", line 1074, in log_artifacts
    self._tracking_client.log_artifacts(run_id, local_dir, artifact_path)
  File "/home/acer/.pyenv/versions/training_env/lib/python3.9/site-packages/mlflow/tracking/_tracking_service/client.py", line 448, in log_artifacts
    self._get_artifact_repo(run_id).log_artifacts(local_dir, artifact_path)
  File "/home/acer/.pyenv/versions/training_env/lib/python3.9/site-packages/mlflow/store/artifact/ftp_artifact_repo.py", line 95, in log_artifacts
    self.log_artifact(os.path.join(root, f), upload_path)
  File "/home/acer/.pyenv/versions/training_env/lib/python3.9/site-packages/mlflow/store/artifact/ftp_artifact_repo.py", line 78, in log_artifact
    ftp.storbinary("STOR " + os.path.basename(local_file), f)
  File "/home/acer/.pyenv/versions/3.9.16/lib/python3.9/ftplib.py", line 498, in storbinary
    with self.transfercmd(cmd, rest) as conn:
  File "/home/acer/.pyenv/versions/3.9.16/lib/python3.9/ftplib.py", line 393, in transfercmd
    return self.ntransfercmd(cmd, rest)[0]
  File "/home/acer/.pyenv/versions/3.9.16/lib/python3.9/ftplib.py", line 354, in ntransfercmd
    conn = socket.create_connection((host, port), self.timeout,
  File "/home/acer/.pyenv/versions/3.9.16/lib/python3.9/socket.py", line 844, in create_connection
    raise err
  File "/home/acer/.pyenv/versions/3.9.16/lib/python3.9/socket.py", line 832, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

```

**Comment by twmht** [comment]
I managed to get this working, but i got 

```
Failed to load HostKeys from
/home/acer/.ssh/known_hosts.  You will need to explicitly load HostKeys (cnopts.hostkeys.load(filename)) or disableHostKey checking (
cnopts.hostkeys = None).
  warnings.warn(wmsg, UserWarning)
Traceback (most recent call last):
  File "/home/shared/mlflow/examples/quickstart/mlflow_tracking.py", line 27, in <module>
    log_artifacts("outputs")
  File "/home/acer/.pyenv/versions/training_env/lib/python3.9/site-packages/mlflow/tracking/fluent.py", line 818, in log_artifacts
    MlflowClient().log_artifacts(run_id, local_dir, artifact_path)
  File "/home/acer/.pyenv/versions/training_env/lib/python3.9/site-packages/mlflow/tracking/client.py", line 1074, in log_artifacts
    self._tracking_client.log_artifacts(run_id, local_dir, artifact_path)
  File "/home/acer/.pyenv/versions/training_env/lib/python3.9/site-packages/mlflow/tracking/_tracking_service/client.py", line 448, i
n log_artifacts
    self._get_artifact_repo(run_id).log_artifacts(local_dir, artifact_path)
  File "/home/acer/.pyenv/versions/training_env/lib/python3.9/site-packages/mlflow/tracking/_tracking_service/client.py", line 416, i
n _get_artifact_repo
    artifact_repo = get_artifact_repository(artifact_uri)
  File "/home/acer/.pyenv/versions/training_env/lib/python3.9/site-packages/mlflow/store/artifact/artifact_repository_registry.py", l
ine 106, in get_artifact_repository
    return _artifact_repository_registry.get_artifact_repository(artifact_uri)
  File "/home/acer/.pyenv/versions/training_env/lib/python3.9/site-packages/mlflow/store/artifact/artifact_repository_registry.py", l
ine 72, in get_artifact_repository
    return repository(artifact_uri)
  File "/home/acer/.pyenv/versions/training_env/lib/python3.9/site-packages/mlflow/store/artifact/sftp_artifact_repo.py", line 82, in
 __init__
    connections = [pysftp.Connection(**self.config) for _ in range(self.max_workers)]
  File "/home/acer/.pyenv/versions/training_env/lib/python3.9/site-packages/mlflow/store/artifact/sftp_artifact_repo.py", line 82, in
 <listcomp>
    connections = [pysftp.Connection(**self.config) for _ in range(self.max_workers)]
  File "/home/acer/.pyenv/versions/training_env/lib/python3.9/site-packages/pysftp/__init__.py", line 132, in __init__
    self._tconnect['hostkey'] = self._cnopts.get_hostkey(host)
  File "/home/acer/.pyenv/versions/training_env/lib/python3.9/site-packages/pysftp/__init__.py", line 71, in get_hostkey
    raise SSHException("No hostkey for host %s found." % host)

```
