### ISSUE TITLE
[BUG] `HTTPConnectionPool(host='mlflow.mlflow.svc.cluster.local', port=5000): Read timed out. (read timeout=10)`

### ISSUE THREAD

**Issue by anirbankonar123** [mlflow/mlflow#8044]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 1.23.1
- Tracking server: 1.23.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **Python version**: Python 3.7
- **yarn version, if running the dev UI**:

### Describe the problem

We are getting this strange error in MLFlow logs : [2023-03-16 05:26:34 +0000] [14] [DEBUG] Ignoring EPIPE 

This happens when the RUN_ID is not created for certain projects only (for other projects its working fine with same code). 

### Tracking information

```shell

remote_server_uri = os.environ.get("MLFLOW_TRACKING_URI", "https://mlflow-dev.loopr.ai:443")

mlflow.set_tracking_uri(remote_server_uri)
mlflow.set_experiment(EXPT_NAME)

    with mlflow.start_run(nested = True) as run:
        mlflow.log_params(parameters)
        mlflow_runid = mlflow.active_run().info.run_id
```

### Code to reproduce issue

```
"HTTPConnectionPool(host='mlflow.mlflow.svc.cluster.local', port=5000): Read timed out. (read timeout=10)"
```

### Stack trace

```
"HTTPConnectionPool(host='mlflow.mlflow.svc.cluster.local', port=5000): Read timed out. (read timeout=10)"
```

### Other info / logs

```
[2023-03-16 05:24:20 +0000] [12] [INFO] Starting gunicorn 20.1.0
[2023-03-16 05:24:20 +0000] [12] [DEBUG] Arbiter booted
[2023-03-16 05:24:20 +0000] [12] [INFO] Listening at: http://0.0.0.0:5000 (12)
[2023-03-16 05:24:20 +0000] [12] [INFO] Using worker: sync
[2023-03-16 05:24:20 +0000] [14] [INFO] Booting worker with pid: 14
[2023-03-16 05:24:20 +0000] [15] [INFO] Booting worker with pid: 15
[2023-03-16 05:24:20 +0000] [16] [INFO] Booting worker with pid: 16
[2023-03-16 05:24:20 +0000] [12] [DEBUG] 4 workers
[2023-03-16 05:24:20 +0000] [17] [INFO] Booting worker with pid: 17
[2023-03-16 05:25:51 +0000] [16] [DEBUG] GET /api/2.0/mlflow/runs/get
[2023-03-16 05:25:52 +0000] [17] [DEBUG] GET /api/2.0/mlflow/runs/get
[2023-03-16 05:26:20 +0000] [15] [DEBUG] GET /api/2.0/mlflow/experiments/get-by-name
[2023-03-16 05:26:21 +0000] [15] [DEBUG] GET /api/2.0/mlflow/experiments/get-by-name
[2023-03-16 05:26:21 +0000] [15] [DEBUG] GET /api/2.0/mlflow/runs/get
[2023-03-16 05:26:21 +0000] [15] [DEBUG] GET /api/2.0/mlflow-artifacts/artifacts
[2023-03-16 05:26:21 +0000] [14] [DEBUG] GET /api/2.0/mlflow-artifacts/artifacts
[2023-03-16 05:26:21 +0000] [14] [DEBUG] GET /api/2.0/mlflow-artifacts/artifacts/133/93143830d0304237b3e73ecc1bf7a228/artifacts/model/ConcreteCrackDetection-14-Mar-2023-16:12:22.json
[2023-03-16 05:26:21 +0000] [14] [DEBUG] GET /api/2.0/mlflow-artifacts/artifacts/133/93143830d0304237b3e73ecc1bf7a228/artifacts/model/coco_instances_results.json
[2023-03-16 05:26:21 +0000] [16] [DEBUG] GET /api/2.0/mlflow-artifacts/artifacts/133/93143830d0304237b3e73ecc1bf7a228/artifacts/model/events.out.tfevents.1678790659.custom-model-train2hn2h-4184424361.7.0
[2023-03-16 05:26:21 +0000] [16] [DEBUG] GET /api/2.0/mlflow-artifacts/artifacts/133/93143830d0304237b3e73ecc1bf7a228/artifacts/model/instances_predictions.pth
[2023-03-16 05:26:21 +0000] [16] [DEBUG] GET /api/2.0/mlflow-artifacts/artifacts/133/93143830d0304237b3e73ecc1bf7a228/artifacts/model/last_checkpoint
[2023-03-16 05:26:22 +0000] [17] [DEBUG] GET /api/2.0/mlflow-artifacts/artifacts/133/93143830d0304237b3e73ecc1bf7a228/artifacts/model/metrics.json
[2023-03-16 05:26:22 +0000] [14] [DEBUG] GET /api/2.0/mlflow-artifacts/artifacts/133/93143830d0304237b3e73ecc1bf7a228/artifacts/model/model_final.pth
[2023-03-16 05:26:34 +0000] [14] [DEBUG] Ignoring EPIPE

```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [X] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@anirbankonar123 The same issue is reported in https://stackoverflow.com/questions/55768090/gunicorn-nginx-ignoring-epipe. Are you using nginx?

**Comment by anirbankonar123** [comment]
Yes, we are using nginx, checking this.

Thanks for the information.

**Comment by harupy** [comment]
Do you have the stacktrace?

**Comment by anirbankonar123** [comment]
We see this exception : "HTTPConnectionPool(host='mlflow.mlflow.svc.cluster.local', port=5000): Read timed out. (read timeout=10)"

In MLFlow server logs we only see : [2023-03-16 05:26:34 +0000] [14] [DEBUG] Ignoring EPIPE

**Comment by harupy** [comment]
Strange. If something goes wrong, stacktrace should be printed out. Have you tried the solution in https://stackoverflow.com/a/66874741?

**Comment by harupy** [comment]
@anirbankonar123 Can you create `docker-compose.yml` that can reproduce the issue?

**Comment by harupy** [comment]
@anirbankonar123 I'm also curious how large your model is.

**Comment by anirbankonar123** [comment]
Its 450 MB.

**Comment by harupy** [comment]
@anirbankonar123 Did increasing the timeout help?

**Comment by anirbankonar123** [comment]
Rt now, we have switched to using Azure Blob client to download the model.
You can close this tkt. Will re-open if needed.

Thanks,
Anirban

**Comment by harupy** [comment]
@anirbankonar123 Got it, thanks for the reply!

**Comment by 111Kaushal** [comment]
Posting this here if it helps anyone...

In my case there was a problem in the log_params function and not with the http connection. The strack trace disappeared probably because the code for logging was somewhere deep inside multiple methods and classes.

I was logging using log_params() in one run multiple times (was using a for loop) and so there was a conflict with the paramater naming convention  but the stack trace did not throw an error and rather the http read time out error showed up. In simple terms if my parameter was logged as 'A'  and the value was 1 then in the same run  in the next for loop iteration it would have to log 'A' again with new value say 2. So now we have 2 values to log with the same name which is a conflict in mlflow. I got around this by simply changing the parameter names.
