### ISSUE TITLE
[FR] Combined Local and Remote Model Tracking

### ISSUE THREAD

**Issue by cgeller** [mlflow/mlflow#8132]
### Willingness to contribute

Yes. I would be willing to contribute this feature with guidance from the MLflow community.

### Proposal Summary

We are already using mlflow during development of new models to track parameters and metrics for every training run. The mlflow UI gives a really nice overview of all experiments conducted. So far, the experiment tracking happens only locally on every developers workstation. And this is good for experiment tracking, because we don't want to track all experiments on a remote tracking server with all developers experiments combined. 

However, we think about a "verified", global, remote model registry, where every developer can register a local experiment to the global model registry. 

As far as i know, tracking and registry (so the both tabs in the mlflow UI) always live on the same machine, because the registered models are only a soft link to one of the experiment runs. 

Is there any way to combine a local tracking of experiments, with a global/remote verified model registry? Maybe we just missed an already existing way.

### Motivation

> #### What is the use case for this feature?
Combine a local tracking of experiments, with a global/remote verified model registry.

> #### Why is this use case valuable to support for MLflow users in general?
Local models are not always important for the whole developer team, only some (verified, registered models, are)

> #### Why is it currently difficult to achieve this use case?
If we understood the documentation correctly, a registered model is only a soft link to a specific experiment.

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [X] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by WeichenXu123** [comment]
@cgeller 

I think you can specify `--registry-store-uri` option for tracking server, acceptable URIs are SQLAlchemy-compatible database connection strings (e.g. 'sqlite:///path/to/file.db'), if `--registry-store-uri`  is not specified, it will use `--backend-store-uri` . :)

**Comment by cgeller** [comment]
Thanks a lot for your answer, @WeichenXu123. For my understanding, the sqlite database is hosted locally and "only" refers to objects from the backend store-uri? Is this correct? 

Or are all artifacts of experiments also included in the sqlite database when registering a model? So the database can also work `standalone`. Then one can maybe find a way to host a sqlite database on a remote server. Does anybody have already some experiments with that?

**Comment by WeichenXu123** [comment]
@cgeller 
> the sqlite database is hosted locally and "only"

No. You can setup a remote database

> Or are all artifacts of experiments also included in the sqlite database when registering a model?

No. They are still stored in `backend-store-uri` server (i.e. local server in your case). `registry-store-uri` is for server that only stores registered model artifacts.

**Comment by cgeller** [comment]
Thanks, again! Yes .. but then, in the registry sqlite database only a reference to a source run/experiment is stored. The actual artifacts from the source run/experiment are not included in the database (and therefore on my remote machine), which are required to download and distribute the model. That's my actual problem ..

**Comment by cgeller** [comment]
Okay, I guess our usecase can not be reached with the current mlflow implementation.

**Comment by WeichenXu123** [comment]
I think for this use case, we need to add a new option like "--registry-model-artifact-destination" for Mlflow server CLI.

**Comment by cgeller** [comment]
I think such a function and storing the whole model artifacts when registering a model would be a great feature for all of us. I`m not familiar with the current mlflow implementation, so it's hard to evaluate the feasibility.

**Comment by WeichenXu123** [comment]
@cgeller 

I think your use case again, we have a simpler solution for this case:

1. launch a central MLflow server that is accessible by all developer workstation. Supposing the tracking URI for this server is: `http://central-server-ip:5000`
2. For each user, by default, they will create experiment and log artifacts locally, but, if a developer needs to register a model to the central MLflow server, he can write code like:

```
from mlflow.tracking._tracking_service.utils import _use_tracking_uri

with _use_tracking_uri('http://central-server-ip:5000'):
  with mlflow.start_run() as run:
    run_id = run.info.run_id
    mlflow.sklearn.log_model(sklearn_model, artifact_path)  # log model to the central server
    mlflow.register_model(f"runs:/{run_id}/{artifact_path}", registered_model_name)  # register the just logged model to central server using the 
```

But note the `_use_tracking_uri` is a developer API. @dbczumar Can we make it to be a public API so that it makes user easier in this case ?

Another option is you can use MLflow client API. Like:

```
from mlflow.tracking.client import MlflowClient
client = MlflowClient(tracking_uri='http://central-server-ip:5000')
client.log_artifacts(...) # log model artifacts
client.create_registered_model(...)
client.client.create_model_version(...)
```
But this way we cannot use the API of `mlflow.<flavor>.log_model` to log model, which makes the solution inconvenient.

**Comment by cgeller** [comment]
Thanks again for your very comprehensive explanation. 

I tried your solution. Using the `register_model` method requires a mlflow `run_id` which has to exist on the mlflow server (in this case the `central-server`). This means that a user has to log the model again when deciding to upload a "verified, final" experiment. I think a user wants to "upload" an already existing model to the registry, if somehow possible, without logging/training the model again.

Instead, the developer could upload the desired experiment run to the `central-server` and then call the `register_model` method.  However, using the mlflow UI for the "uploading" task would be more user-friendly. 

I'm thinking of a solution where the `Experiments` tab manages all local experiment runs, and the `Models` tab manages all remote, registered models. This would include an artefact upload during the registering process, instead "just" linking to an already existing experiment run.

Maybe there is another solution for this really common problem?

**Comment by WeichenXu123** [comment]
Got it. 

> Instead, the developer could upload the desired experiment run to the central-server

I think I can provide a utility method to do this. Let me discuss it with my teammates .

**Comment by cgeller** [comment]
Thanks a lot, this would be amazing.

Do you see a way to automatically call a custom method when registering a method via the UI?

**Comment by WeichenXu123** [comment]
> Do you see a way to automatically call a custom method when registering a method via the UI?

I prefer to add an UI button like: "Sync one experiment run (including all of its metrics/artifacts/params/tags) to another MLflow server", this way makes the functionality more clear. Then in another MLflow server you can register the model via UI.

**Comment by WeichenXu123** [comment]
@cgeller 

> "Sync one experiment run (including all of its metrics/artifacts/params/tags) to another MLflow server"

For this solution we hit an issue: Current rest API cannot support create experiment run with specified `run_id`, (and supporting this is not agreed by mlflow core team members), so if we want to exactly sync one run to remote server, we have to directly insert data into remote server database (which is hacky and risky)

So for now, the best solution should be:

Using Mlflow client API, construct MlflowClient with the remote server tracking URI,
then create a new run with `client.create_run()`, then within the run call `client.log_artifacts()` to upload locally logged model artifacts to remote server, and then call client.register_model() (or you can register the model on remote server web UI)

**Comment by WeichenXu123** [comment]
@cgeller I will close this ticket because I think for now https://github.com/mlflow/mlflow/issues/8132#issuecomment-1495745670 is the best solution and it works. If you have any better idea feel free to reopen the ticket. :)
