### ISSUE TITLE
[BUG] extra ghost runs due to failed  connection retries

### ISSUE THREAD

**Issue by maciejskorski** [mlflow/mlflow#8238]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### MLflow version

- Client: 2.2.2
- Tracking server: ngrok

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Unbuntu 20
- **Python version**: 3.7
- **yarn version, if running the dev UI**:

### Describe the problem

When tracking experiments with MLFlow and ngrok as the web interface, I often get _extra ghost runs_ related to failed url retries that _remain unfinished_. By "extra" I mean that all the jobs get done, but the process spawns an incomplete run too.
Can't provide a minimal working example, but believe this may be known to experienced developers. How to avoid this situation, as in monitoring I ideally want a clean situation? 

### Tracking information

```shell
WARNING:urllib3.connectionpool:Retrying (Retry(total=4, connect=5, read=5, redirect=5, status=5)) after connection broken by 'SSLError(SSLError(1, '[SSL: SSLV3_ALERT_BAD_RECORD_MAC] sslv3 alert bad record mac (_ssl.c:2633)'))': /api/2.0/mlflow/runs/create
WARNING:urllib3.connectionpool:Retrying (Retry(total=4, connect=5, read=4, redirect=5, status=5)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /api/2.0/mlflow/runs/create
WARNING:urllib3.connectionpool:Retrying (Retry(total=4, connect=5, read=5, redirect=5, status=5)) after connection broken by 'SSLError(SSLError(1, '[SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2633)'))': /api/2.0/mlflow/runs/create
```

### Code to reproduce issue

```
# Run mlflow server
get_ipython().system_raw("mlflow ui --port 5000 &")

# Terminate open tunnels if exist
ngrok.kill()

# Setting the authtoken (optional)
# Get your authtoken from https://dashboard.ngrok.com/auth
NGROK_AUTH_TOKEN = getpass('Enter the ngrok authtoken: ')  
ngrok.set_auth_token(NGROK_AUTH_TOKEN)

# Open an HTTPS tunnel on port 5000 for http://localhost:5000
ngrok_tunnel = ngrok.connect(addr="5000", proto="http", bind_tls=True)

# visit the tracking address to enable it
mlflow.set_tracking_uri(ngrok_tunnel.public_url)
logger.info(f"MLflow Tracking UI:{ngrok_tunnel.public_url}")

# plus standard mlflow logging code
```

### Stack trace

```
appears as a warning, no stack trace
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [X] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@maciejskorski Are you saying that the code like beflow results in creating multiple unfinished runs?

```
with mlflow.start_run():
    ...
```

**Comment by maciejskorski** [comment]
> @maciejskorski Are you saying that the code like beflow results in creating multiple unfinished runs due to connection retries?
> 
> ```python
> with mlflow.start_run():
>     ...
> ```

Yup that's what I am saying. 

The usage is pretty standard as you said, except that I am tunnelling and multiprocessing. 
```
experiment_id = mlflow.create_experiment(experiment_name)

def do_job(cfg):
    with mlflow.start_run(experiment_id=experiment_id):
      mlflow.log_param('file',cfg.inputfile)
      # ... do stuff

with mp.Pool(4) as p:
  p.map(do_job, all_cfgs)
```
I typically end up with one ghost round more than the length of the task list.

If nothing comes to mind right away, I can try a bit harder and make a fully reproducible example in Google Colab

**Comment by harupy** [comment]
@maciejskorski We encountered the same issue in https://github.com/mlflow/mlflow/pull/8116 and found reusing a cached `requests.Session` was the cause.

**Comment by harupy** [comment]
Relevant code:

https://github.com/mlflow/mlflow/blob/24e7c0701ca31bc0925a6647c97dffdee9ef938b/mlflow/utils/rest_utils.py#L42-L44

**Comment by maciejskorski** [comment]
@harupy many thanks for root-causing it! Indeed, without multiprocessing, my use-case is stable. yet, one thing that still puzzles me is that the issue seems to occur somewhat randomly

**Comment by harupy** [comment]
@maciejskorski 

> one thing that still puzzles me is that the issue seems to occur somewhat randomly

We observed the same thing. It was flaky :)

**Comment by harupy** [comment]
@maciejskorski I filed https://github.com/mlflow/mlflow/issues/8238 to fix this issue. Would you mind testing this PR?

```
pip install git+https://github.com/mlflow/mlflow.git@refs/pull/8238/merge
```

**Comment by monajalal** [comment]
@harupy  I do not have this problem when I have one node, multi-GPU , however, I do have the problem if I have multi-node, multi-gpu in each node. Could you please suggest a fix?

Here's my `requirements.txt`:
```
 # for local testing (cpu)
torchvision==0.12.0
torch==1.11.0
transformers==4.18.0

# for metrics reporting/plotting
mlflow==1.25.1
azureml-mlflow==1.41.0
matplotlib==3.5.2
tqdm==4.64.0
psutil==5.9.0

# for unit testing
pytest==7.1.2

```

and here's my `Dockerfile`:
```
# check release notes https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/index.html
FROM nvcr.io/nvidia/pytorch:22.04-py3

##############################################################################
# NCCL TESTS
##############################################################################
ENV NCCL_TESTS_TAG=v2.11.0

# NOTE: adding gencodes to support K80, M60, V100, A100
RUN mkdir /tmp/nccltests && \
    cd /tmp/nccltests && \
    git clone -b ${NCCL_TESTS_TAG} https://github.com/NVIDIA/nccl-tests.git && \
    cd nccl-tests && \
    make \
    MPI=1 MPI_HOME=/opt/hpcx/ompi \
    NVCC_GENCODE="-gencode=arch=compute_35,code=sm_35 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_61,code=sm_61 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_80,code=sm_80" \
    CUDA_HOME=/usr/local/cuda && \
    cp ./build/* /usr/local/bin && \
    rm -rf /tmp/nccltests

# Install dependencies missing in this container
# NOTE: container already has matplotlib==3.5.1 tqdm==4.62.0
COPY requirements.txt ./
RUN pip install -r requirements.txt


# add ndv4-topo.xml
RUN mkdir /opt/microsoft/
ADD ./ndv4-topo.xml /opt/microsoft

# to use on A100, enable env var below in your job
# ENV NCCL_TOPO_FILE="/opt/microsoft/ndv4-topo.xml"

# adjusts the level of info from NCCL tests
ENV NCCL_DEBUG="INFO"
ENV NCCL_DEBUG_SUBSYS="GRAPH,INIT,ENV"

# Relaxed Ordering can greatly help the performance of Infiniband networks in virtualized environments.
ENV NCCL_IB_PCI_RELAXED_ORDERING="1"
ENV CUDA_DEVICE_ORDER="PCI_BUS_ID"
ENV NCCL_SOCKET_IFNAME="eth0"
# ENV NCCL_SOCKET_IFNAME='lo'
ENV NCCL_IB_DISABLE="1"

```

Here's the non-problematic situation:

```
fec33820a43e42eaa326fabda0a0a7b3000001:37:37 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to eth0
fec33820a43e42eaa326fabda0a0a7b3000001:37:37 [0] NCCL INFO Bootstrap : Using eth0:10.0.0.5<0>
fec33820a43e42eaa326fabda0a0a7b3000001:37:37 [0] NCCL INFO Plugin Path : /opt/hpcx/nccl_rdma_sharp_plugin/lib/libnccl-net.so
fec33820a43e42eaa326fabda0a0a7b3000001:37:37 [0] NCCL INFO P2P plugin IBext
fec33820a43e42eaa326fabda0a0a7b3000001:37:37 [0] NCCL INFO NCCL_IB_PCI_RELAXED_ORDERING set by environment to 1.
fec33820a43e42eaa326fabda0a0a7b3000001:37:37 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to eth0
fec33820a43e42eaa326fabda0a0a7b3000001:37:37 [0] NCCL INFO NET/IB : No device found.
fec33820a43e42eaa326fabda0a0a7b3000001:37:37 [0] NCCL INFO NCCL_IB_DISABLE set by environment to 1.
fec33820a43e42eaa326fabda0a0a7b3000001:37:37 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to eth0
fec33820a43e42eaa326fabda0a0a7b3000001:37:37 [0] NCCL INFO NET/Socket : Using [0]eth0:10.0.0.5<0>
fec33820a43e42eaa326fabda0a0a7b3000001:37:37 [0] NCCL INFO Using network Socket
NCCL version 2.10.3+cuda10.2
fec33820a43e42eaa326fabda0a0a7b3000001:37:208 [0] NCCL INFO Topology detection : could not read /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/47505500-0001-0000-3130-444531303244/pci0001:00/0001:00:00.0/../max_link_speed, ignoring
fec33820a43e42eaa326fabda0a0a7b3000001:37:208 [0] NCCL INFO Topology detection : could not read /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/47505500-0001-0000-3130-444531303244/pci0001:00/0001:00:00.0/../max_link_width, ignoring
fec33820a43e42eaa326fabda0a0a7b3000001:37:208 [0] NCCL INFO Topology detection : could not read /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/47505500-0002-0000-3130-444531303244/pci0002:00/0002:00:00.0/../max_link_speed, ignoring
fec33820a43e42eaa326fabda0a0a7b3000001:37:208 [0] NCCL INFO Topology detection : could not read /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/47505500-0002-0000-3130-444531303244/pci0002:00/0002:00:00.0/../max_link_width, ignoring
fec33820a43e42eaa326fabda0a0a7b3000001:37:208 [0] NCCL INFO Topology detection : could not read /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/47505500-0003-0000-3130-444531303244/pci0003:00/0003:00:00.0/../max_link_speed, ignoring
fec33820a43e42eaa326fabda0a0a7b3000001:37:208 [0] NCCL INFO Topology detection : could not read /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/47505500-0003-0000-3130-444531303244/pci0003:00/0003:00:00.0/../max_link_width, ignoring
fec33820a43e42eaa326fabda0a0a7b3000001:37:208 [0] NCCL INFO Topology detection : could not read /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/47505500-0004-0000-3130-444531303244/pci0004:00/0004:00:00.0/../max_link_speed, ignoring
fec33820a43e42eaa326fabda0a0a7b3000001:37:208 [0] NCCL INFO Topology detection : could not read /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/47505500-0004-0000-3130-444531303244/pci0004:00/0004:00:00.0/../max_link_width, ignoring
fec33820a43e42eaa326fabda0a0a7b3000001:37:208 [0] NCCL INFO Topology detection: network path /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/6045bdbd-f1de-6045-bdbd-f1de6045bdbd is not a PCI device (vmbus). Attaching to first CPU
fec33820a43e42eaa326fabda0a0a7b3000001:37:208 [0] NCCL INFO KV Convert to int : could not find value of '' in dictionary, falling back to 60
fec33820a43e42eaa326fabda0a0a7b3000001:37:208 [0] NCCL INFO KV Convert to int : could not find value of '' in dictionary, falling back to 60
fec33820a43e42eaa326fabda0a0a7b3000001:37:208 [0] NCCL INFO KV Convert to int : could not find value of '' in dictionary, falling back to 60
fec33820a43e42eaa326fabda0a0a7b3000001:37:208 [0] NCCL INFO KV Convert to int : could not find value of '' in dictionary, falling back to 60
fec33820a43e42eaa326fabda0a0a7b3000001:37:208 [0] NCCL INFO Attribute coll of node net not found
fec33820a43e42eaa326fabda0a0a7b3000001:37:208 [0] NCCL INFO === System : maxWidth 12.0 totalWidth 12.0 ===
fec33820a43e42eaa326fabda0a0a7b3000001:37:208 [0] NCCL INFO CPU/0 (1/1/1)
fec33820a43e42eaa326fabda0a0a7b3000001:37:208 [0] NCCL INFO + PCI[5000.0] - NIC/0
fec33820a43e42eaa326fabda0a0a7b3000001:37:208 [0] NCCL INFO + PCI[12.0] - GPU/100000 (0)
fec33820a43e42eaa326fabda0a0a7b3000001:37:208 [0] NCCL INFO + PCI[12.0] - GPU/200000 (1)
fec33820a43e42eaa326fabda0a0a7b3000001:37:208 [0] NCCL INFO + PCI[12.0] - GPU/300000 (2)
fec33820a43e42eaa326fabda0a0a7b3000001:37:208 [0] NCCL INFO + PCI[12.0] - GPU/400000 (3)
fec33820a43e42eaa326fabda0a0a7b3000001:37:208 [0] NCCL INFO ==========================================
fec33820a43e42eaa326fabda0a0a7b3000001:37:208 [0] NCCL INFO GPU/100000 :GPU/100000 (0/5000.000000/LOC) GPU/200000 (2/12.000000/PHB) GPU/300000 (2/12.000000/PHB) GPU/400000 (2/12.000000/PHB) CPU/0 (1/12.000000/PHB) 
fec33820a43e42eaa326fabda0a0a7b3000001:37:208 [0] NCCL INFO GPU/200000 :GPU/100000 (2/12.000000/PHB) GPU/200000 (0/5000.000000/LOC) GPU/300000 (2/12.000000/PHB) GPU/400000 (2/12.000000/PHB) CPU/0 (1/12.000000/PHB) 
fec33820a43e42eaa326fabda0a0a7b3000001:37:208 [0] NCCL INFO GPU/300000 :GPU/100000 (2/12.000000/PHB) GPU/200000 (2/12.000000/PHB) GPU/300000 (0/5000.000000/LOC) GPU/400000 (2/12.000000/PHB) CPU/0 (1/12.000000/PHB) 
fec33820a43e42eaa326fabda0a0a7b3000001:37:208 [0] NCCL INFO GPU/400000 :GPU/100000 (2/12.000000/PHB) GPU/200000 (2/12.000000/PHB) GPU/300000 (2/12.000000/PHB) GPU/400000 (0/5000.000000/LOC) CPU/0 (1/12.000000/PHB) 
fec33820a43e42eaa326fabda0a0a7b3000001:37:208 [0] NCCL INFO Pattern 4, crossNic 0, nChannels 1, speed 10.000000/10.000000, type PHB/PIX, sameChannels 1
fec33820a43e42eaa326fabda0a0a7b3000001:37:208 [0] NCCL INFO  0 : GPU/0 GPU/1 GPU/2 GPU/3
fec33820a43e42eaa326fabda0a0a7b3000001:37:208 [0] NCCL INFO Pattern 1, crossNic 0, nChannels 1, speed 10.000000/10.000000, type PHB/PIX, sameChannels 1
fec33820a43e42eaa326fabda0a0a7b3000001:37:208 [0] NCCL INFO  0 : GPU/0 GPU/1 GPU/2 GPU/3
fec33820a43e42eaa326fabda0a0a7b3000001:37:208 [0] NCCL INFO Pattern 3, crossNic 0, nChannels 1, speed 10.000000/10.000000, type PHB/PIX, sameChannels 1
fec33820a43e42eaa326fabda0a0a7b3000001:37:208 [0] NCCL INFO  0 : GPU/0 GPU/1 GPU/2 GPU/3
fec33820a43e42eaa326fabda0a0a7b3000001:37:208 [0] NCCL INFO Tree 0 : -1 -> 0 -> 1/-1/-1
fec33820a43e42eaa326fabda0a0a7b3000001:37:208 [0] NCCL INFO Tree 1 : -1 -> 0 -> 1/-1/-1
fec33820a43e42eaa326fabda0a0a7b3000001:37:208 [0] NCCL INFO Channel 00/02 :    0   1   2   3
fec33820a43e42eaa326fabda0a0a7b3000001:37:208 [0] NCCL INFO Channel 01/02 :    0   1   2   3
fec33820a43e42eaa326fabda0a0a7b3000001:37:208 [0] NCCL INFO Ring 00 : 3 -> 0 -> 1
fec33820a43e42eaa326fabda0a0a7b3000001:37:208 [0] NCCL INFO Ring 01 : 3 -> 0 -> 1
fec33820a43e42eaa326fabda0a0a7b3000001:37:208 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1 [1] 1/-1/-1->0->-1
fec33820a43e42eaa326fabda0a0a7b3000001:37:208 [0] NCCL INFO Setting affinity for GPU 0 to 0fff
fec33820a43e42eaa326fabda0a0a7b3000001:37:208 [0] NCCL INFO Channel 00 : 0[100000] -> 1[200000] via direct shared memory
fec33820a43e42eaa326fabda0a0a7b3000001:37:208 [0] NCCL INFO Channel 01 : 0[100000] -> 1[200000] via direct shared memory
fec33820a43e42eaa326fabda0a0a7b3000001:37:208 [0] NCCL INFO Connected all rings
fec33820a43e42eaa326fabda0a0a7b3000001:37:208 [0] NCCL INFO Connected all trees
fec33820a43e42eaa326fabda0a0a7b3000001:37:208 [0] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 8/8/512
fec33820a43e42eaa326fabda0a0a7b3000001:37:208 [0] NCCL INFO 2 coll channels, 2 p2p channels, 2 p2p channels per peer
fec33820a43e42eaa326fabda0a0a7b3000001:37:208 [0] NCCL INFO comm 0x153eb0001240 rank 0 nranks 4 cudaDev 0 busId 100000 - Init COMPLETE
fec33820a43e42eaa326fabda0a0a7b3000001:37:37 [0] NCCL INFO Launch mode Parallel
MLflow version: 1.25.1
Tracking URI: azureml:URI
Artifact URI: azureml:URI
World size: 4
local rank is 0 and world rank is 0
Downloading https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz to ./data_0/cifar-10-python.tar.gz

  0%|          | 0/170498071 [00:00<?, ?it/s]
  0%|          | 544768/170498071 [00:00<00:31, 5369680.61it/s]
  2%|▏         | 2880512/170498071 [00:00<00:10, 15844914.53it/s]
  3%|▎         | 5056512/170498071 [00:00<00:09, 17856230.77it/s]
  4%|▍         | 7335936/170498071 [00:00<00:08, 19729892.43it/s]
  6%|▌         | 9648128/170498071 [00:00<00:07, 20931046.37it/s]
  7%|▋         | 11968512/170498071 [00:00<00:07, 21630963.81it/s]
  8%|▊         | 14247936/170498071 [00:00<00:07, 22005088.89it/s]
 10%|▉         | 16520192/170498071 [00:00<00:06, 22113817.44it/s]
 11%|█         | 18784256/170498071 [00:00<00:06, 22276545.60it/s]
 12%|█▏        | 21054464/170498071 [00:01<00:06, 22407118.86it/s]
 14%|█▎        | 23296000/170498071 [00:01<00:06, 22188998.50it/s]
 15%|█▍        | 25516032/170498071 [00:01<00:06, 21661435.98it/s]
 16%|█▌        | 27685888/170498071 [00:01<00:06, 21140440.07it/s]
 17%|█▋        | 29804544/170498071 [00:01<00:06, 20593556.49it/s]
 19%|█▊        | 31868928/170498071 [00:01<00:06, 20156557.50it/s]
 20%|█▉        | 33888256/170498071 [00:01<00:06, 19745679.59it/s]
 21%|██        | 35865600/170498071 [00:01<00:06, 19687404.90it/s]
 22%|██▏       | 37836800/170498071 [00:01<00:06, 19460052.10it/s]
 23%|██▎       | 39784448/170498071 [00:01<00:06, 19222178.56it/s]
 24%|██▍       | 41707520/170498071 [00:02<00:06, 19104469.22it/s]
 26%|██▌       | 43624448/170498071 [00:02<00:06, 19072615.77it/s]
 27%|██▋       | 45544448/170498071 [00:02<00:06, 19046030.11it/s]
 28%|██▊       | 47472640/170498071 [00:02<00:06, 18993926.03it/s]
 29%|██▉       | 49392640/170498071 [00:02<00:06, 18941301.65it/s]
 30%|███       | 51333120/170498071 [00:02<00:06, 19078166.70it/s]
 31%|███       | 53265408/170498071 [00:02<00:06, 19150688.08it/s]
 32%|███▏      | 55181312/170498071 [00:02<00:06, 19015663.83it/s]
 33%|███▎      | 57083904/170498071 [00:02<00:05, 18921455.92it/s]
 35%|███▍      | 59008000/170498071 [00:02<00:05, 18876725.57it/s]
 36%|███▌      | 60896256/170498071 [00:03<00:05, 18868879.10it/s]
 37%|███▋      | 62840832/170498071 [00:03<00:05, 19039215.17it/s]
 38%|███▊      | 64745472/170498071 [00:03<00:05, 18795086.88it/s]
 39%|███▉      | 66632704/170498071 [00:03<00:05, 18810168.86it/s]
 40%|████      | 68552704/170498071 [00:03<00:05, 18886629.32it/s]
 41%|████▏     | 70480896/170498071 [00:03<00:05, 18926663.49it/s]
 42%|████▏     | 72408064/170498071 [00:03<00:05, 19017268.26it/s]
 44%|████▎     | 74384384/170498071 [00:03<00:05, 19154625.24it/s]
 45%|████▍     | 76312576/170498071 [00:03<00:04, 19185430.64it/s]
 46%|████▌     | 78232576/170498071 [00:03<00:04, 19044355.19it/s]
 47%|████▋     | 80138240/170498071 [00:04<00:04, 19032394.16it/s]
 48%|████▊     | 82072576/170498071 [00:04<00:04, 19032762.39it/s]
 49%|████▉     | 84000768/170498071 [00:04<00:04, 18993284.35it/s]
 50%|█████     | 85984256/170498071 [00:04<00:04, 19194041.36it/s]
 52%|█████▏    | 87968768/170498071 [00:04<00:04, 19295312.99it/s]
 53%|█████▎    | 89960448/170498071 [00:04<00:04, 19394267.99it/s]
 54%|█████▍    | 91943936/170498071 [00:04<00:04, 19474106.16it/s]
 55%|█████▌    | 94000128/170498071 [00:04<00:03, 19731032.65it/s]
 56%|█████▋    | 96304128/170498071 [00:04<00:03, 20653426.52it/s]
 58%|█████▊    | 98657280/170498071 [00:05<00:03, 21509811.57it/s]
 59%|█████▉    | 100984832/170498071 [00:05<00:03, 21949022.30it/s]
 61%|██████    | 103304192/170498071 [00:05<00:03, 22318196.75it/s]
 62%|██████▏   | 105656320/170498071 [00:05<00:02, 22563801.79it/s]
 63%|██████▎   | 107984896/170498071 [00:05<00:02, 22772587.92it/s]
 65%|██████▍   | 110336000/170498071 [00:05<00:02, 22893636.05it/s]
 66%|██████▋   | 113224704/170498071 [00:05<00:02, 24611655.12it/s]
 68%|██████▊   | 116120576/170498071 [00:05<00:02, 25873352.76it/s]
 70%|██████▉   | 118992896/170498071 [00:05<00:01, 26672004.11it/s]
 71%|███████▏  | 121872384/170498071 [00:05<00:01, 27269632.47it/s]
 73%|███████▎  | 124768256/170498071 [00:06<00:01, 27738624.97it/s]
 75%|███████▍  | 127640576/170498071 [00:06<00:01, 27994351.27it/s]
 77%|███████▋  | 130528256/170498071 [00:06<00:01, 28237881.13it/s]
 78%|███████▊  | 133408768/170498071 [00:06<00:01, 28395251.23it/s]
 80%|███████▉  | 136296448/170498071 [00:06<00:01, 28490006.83it/s]
 82%|████████▏ | 139175936/170498071 [00:06<00:01, 28557051.70it/s]
 83%|████████▎ | 142064640/170498071 [00:06<00:00, 28576616.43it/s]
 85%|████████▌ | 144948224/170498071 [00:06<00:00, 28653993.24it/s]
 87%|████████▋ | 147896320/170498071 [00:06<00:00, 28869425.59it/s]
 88%|████████▊ | 150784000/170498071 [00:06<00:00, 28754943.51it/s]
 91%|█████████ | 155528192/170498071 [00:07<00:00, 34291822.22it/s]
 95%|█████████▍| 161680384/170498071 [00:07<00:00, 42359886.52it/s]
 98%|█████████▊| 167552000/170498071 [00:07<00:00, 47246998.05it/s]
170499072it [00:07, 23447255.93it/s]                               Extracting ./data_0/cifar-10-python.tar.gz to ./data_0
Files already downloaded and verified

[Epoch 1] loss: 469.946
[Epoch 2] loss: 331.277
[Epoch 3] loss: 288.598
[Epoch 4] loss: 271.003
[Epoch 5] loss: 253.672
[Epoch 6] loss: 238.890
[Epoch 7] loss: 228.931
[Epoch 8] loss: 218.206
[Epoch 9] loss: 220.511
[Epoch 10] loss: 199.832
[Epoch 11] loss: 186.101
[Epoch 12] loss: 188.461
[Epoch 13] loss: 179.636
```

Here's the full log of my problem when I switch to multi-node multi-GPU (here, 4 nodes each with 4 GPUs, 16 GPUs total):
https://github.com/microsoft/MLOpsPython/issues/416
https://github.com/mlflow/mlflow/issues/8444
