### ISSUE TITLE
[BUG] Duplicate key value violates unique constraint "tag_pk"

### ISSUE THREAD

**Issue by LukasBa1** [mlflow/mlflow#8442]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- 1.30.1 and still occurs for version 2.3.2

### System information

- **OS Platform and Distribution**: Win10
- **Python version**: 3.8.16

### Describe the problem

When specifying a run name in `with mlflow.start_run(run_name=run_name)`, the key containing `mlflow.runName` and `run_uuid` is created twice, leading to the following exception:
`mlflow.exceptions.RestException: BAD_REQUEST: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "tag_pk"
DETAIL:  Key (key, run_uuid)=(mlflow.runName, 64e68fdf8d6a489b920dc875094e1d0b) already exists.`

Please see the stack trace for more details. This occurs for version 1.30.1 and still occurs for 2.3.2 (current latest version) while for version 1.30.0 the run is tracked as expected.

### Code to reproduce issue

```python
import shutil
from pathlib import Path
import mlflow
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression

artifact_dir = ".models"
model_path = Path("model_test")

run_name = "test-run"
experiment_name = "test-experiment"

if model_path.exists():
    shutil.rmtree(model_path)
model_path.mkdir(exist_ok=False, parents=True)

X, y = load_iris(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

mlflow.set_experiment(experiment_name)

with mlflow.start_run(run_name=run_name):
    model = LogisticRegression().fit(X_train, y_train)
    y_pred = model.predict(X_test)
    accuracy= accuracy_score(y_test, y_pred)

    mlflow.sklearn.save_model(model, model_path)
    mlflow.log_params(model.get_params())
    mlflow.log_metric("accuracy", accuracy)
```

### Stack trace

```bash
Traceback (most recent call last):
  File "test.py", line 32, in <module>       
    with mlflow.start_run(run_name=run_name):
  File "C:\Users\user\Anaconda3\envs\env\lib\site-packages\mlflow\tracking\fluent.py", line 353, in start_run
    active_run_obj = client.create_run(
  File "C:\Users\user\Anaconda3\envs\env\lib\site-packages\mlflow\tracking\client.py", line 270, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
  File "C:\Users\user\Anaconda3\envs\env\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 108, in create_run
    return self.store.create_run(
  File "C:\Users\user\Anaconda3\envs\env\lib\site-packages\mlflow\store\tracking\rest_store.py", line 204, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
  File "C:\Users\user\Anaconda3\envs\env\lib\site-packages\mlflow\store\tracking\rest_store.py", line 57, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "C:\Users\user\Anaconda3\envs\env\lib\site-packages\mlflow\utils\rest_utils.py", line 280, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "C:\Users\user\Anaconda3\envs\env\lib\site-packages\mlflow\utils\rest_utils.py", line 206, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: BAD_REQUEST: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "tag_pk"
DETAIL:  Key (key, run_uuid)=(mlflow.runName, 88e1494d57794c43a26a4ff2ad5dcdc8) already exists.

[SQL: INSERT INTO tags (key, value, run_uuid) VALUES (%(key)s, %(value)s, %(run_uuid)s)]
[parameters: ({'key': 'mlflow.user', 'value': 'n3LxuOEmZScHgF6O4cgnhGVTTZu5ydjO3fahGKDbJOE', 'run_uuid': '88e1494d57794c43a26a4ff2ad5dcdc8'}, {'key': 'mlflow.source.name', 'value': 'test.py', 'run_uuid': '88e1494d57794c43a26a4ff2ad5dcdc8'}, {'key': 'mlflow.source.type', 'value': 'LOCAL', 'run_uuid': '88e1494d57794c43a26a4ff2ad5dcdc8'}, {'key': 'mlflow.source.git.commit', 'value': 'b6ad14ce59e246d42dd4c12ae276c973b0876b5e', 'run_uuid': '88e1494d57794c43a26a4ff2ad5dcdc8'}, {'key': 'mlflow.runName', 'value': 'test-run', 'run_uuid': '88e1494d57794c43a26a4ff2ad5dcdc8'}, {'key': 'mlflow.runName', 'value': 'test-run', 'run_uuid': '88e1494d57794c43a26a4ff2ad5dcdc8'})]
```

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [X] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by WeichenXu123** [comment]
@LukasBa1 

I cannot reproduce your reported bug,

I tested your code on Windows with mlflow 1.30.1 and mlflow 2.3.2, they both work fine.

For each version mlflow, I tested your code with MLflow sql-store backend and filestore backend. They all work fine.

**Comment by awskhd** [comment]
@mlflow-automation  this issue is not fixed yet, i am still getting the same error, this could be avoided by using 1.30.0 version, but this is not the optimal due to the Vulnerabilities with 1.30.0

**Comment by SiJonesDLG** [comment]
@WeichenXu123 This was closed as complete, but I am unclear on whether it was fixed or found to be caused by something else and which version the fix does or will appear in, if any. Can you explain a little?

**Comment by SiJonesDLG** [comment]
@WeichenXu123 @awskhd I believe I get the same error with a different build, also fixed by rolling back to mlflow==1.30.0

**Comment by nadworny** [comment]
@BenWilson2 @dbczumar @harupy @WeichenXu123 can we please re-open this one?

**Comment by makwanji** [comment]
I am getting same issue with version `2.15.0`

**Comment by stevecj** [comment]
I am seeing this in version 3.11.1
