### ISSUE TITLE
[FR]: Setting run_name for MLFlow-Recipes

### ISSUE THREAD

**Issue by e-taghizadeh** [mlflow/mlflow#8474]
### Willingness to contribute

Yes. I would be willing to contribute this feature with guidance from the MLflow community.

### Proposal Summary

It's possible to set the run_name when starting an MLFlow run. However this feature is not available in MLFlow Rcipes. It would be nice to set the run_name or run_id, when starting an MLFlow Recipe run. 

### Motivation

> #### What is the use case for this feature?
When running multiple recipes on a remote server, e.g. doing a comparison between different input parameters, it is not easy to compare the runs easily in the table view of MLFlow Tracking, based on random run names. This would be even more difficult to retrieve the information on the results of these runs via code. If the run_name of a specific run in an experiment could be set, or at least the run_id was returned after Recipe.run(), could make summarizing the results easier in a code.

> #### Why is this use case valuable to support for MLflow users in general?

> #### Why is this use case valuable to support for your project(s) or organization?
I would like to automate hyperparameter tuning or summarizing the results of k-fold cross validation using MLFlow recipes.
 
> #### Why is it currently difficult to achieve this use case?
The jobs are submitted to run on a remote server. After a successful run of the job, the results can be seen on MLFlow tracking, however it is difficult to retrieve information related to a specific run, when the name of the run or run_id are set, randomly.

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [X] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by WeichenXu123** [comment]
The feature make sense ? Shall we add the name in recipe profile config file or add it as an argument of `class Recipe` constructor ?

**Comment by e-taghizadeh** [comment]
In my opinion, it could be passed in as an argument of the class Recipe, and can be set in the recipe config file (recipe.yaml). This way, one could easily define a template for the run_name, based on input parameters, that are set via profile config. e.g. estimator name and primary metric names are defined in the profile as {ESTIMATOR_NAME} and {PRIMARY_METRIC} variables. Then, the run_name could be set in the recipe config as: {{ESTIMATOR_NAME}}_{{PRIMARY_METRIC}}.

**Comment by WeichenXu123** [comment]
I discussed with Mlflow dev team members, we recommand to use "run_name_prefix" in your case:
See https://github.com/mlflow/mlflow/pull/7763/files

i.e., adds an "experiment" section in recipe profile yaml file, and inside "experiment" section, adds a "run_name_prefix" config.

**Comment by e-taghizadeh** [comment]
Thanks for your reply. I could make it work with run_name_prefix. Then I will close this FR.
