### ISSUE TITLE
[BUG] Run id does not exist  if the user is not adminstrator when tracking experiment with basic auth

### ISSUE THREAD

**Issue by ruanysheng** [mlflow/mlflow#8509]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

- Client: 2.3.2
- Tracking server: 2.3.2

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 20.04)**:
- **Python version**:
- **yarn version, if running the dev UI**:

### Describe the problem

I use the basic auth in the Scenario 4.  I created a new user from ```https://<host>/signup```,   exported necessary environments from client, and  ran my python code as below:

```shell
import mlflow 
mlflow.set_tracking_uri("MY_MLFLOW_TRACKING_URI")
exp = mlflow.get_experiment_by_name(name=exp_name)
if exp:
    exp_id = exp.experiment_id
else:
    exp_id = mlflow.create_experiment(name=exp_name)

mlflow.start_run(experiment_id=exp_id)
mlflow.log_metric('a', 123)
mlflow.log_metric('b', 456)

mlflow.end_run()
```

It raised an error:

```shell
  File "/home/thinhnn/miniconda3/envs/mlflow/lib/python3.8/site-packages/mlflow/tracking/fluent.py", line 394, in end_run
    MlflowClient().set_terminated(run.info.run_id, status)
  File "/home/thinhnn/miniconda3/envs/mlflow/lib/python3.8/site-packages/mlflow/tracking/client.py", line 1543, in set_terminated
    self._tracking_client.set_terminated(run_id, status, end_time)
  File "/home/thinhnn/miniconda3/envs/mlflow/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py", line 485, in set_terminated
    self.store.update_run_info(
  File "/home/thinhnn/miniconda3/envs/mlflow/lib/python3.8/site-packages/mlflow/store/tracking/rest_store.py", line 148, in update_run_info
    response_proto = self._call_endpoint(UpdateRun, req_body)
  File "/home/thinhnn/miniconda3/envs/mlflow/lib/python3.8/site-packages/mlflow/store/tracking/rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "/home/thinhnn/miniconda3/envs/mlflow/lib/python3.8/site-packages/mlflow/utils/rest_utils.py", line 303, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "/home/thinhnn/miniconda3/envs/mlflow/lib/python3.8/site-packages/mlflow/utils/rest_utils.py", line 227, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: RESOURCE_DOES_NOT_EXIST: Run '28de43bb03084e0abe2f2f0dd1b1843f' not found
```

and MLlfow UI did not show the experiment  

![Screenshot from 2023-05-23 22-15-11](https://github.com/mlflow/mlflow/assets/110561667/67b7ee01-a194-4f39-8c48-6cb40b002fa5)

 I changed the experiment of the user to 'MANAGE' but it still raise an error as above. However, if I change the user to administrator, it will run exactly what I want. And if i switch all user to admin, authorization is not true in my case. 

I tried to experiment with Scenario 3, and it does not has any problem with my steps. How should I fix this issue ?

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```
REPLACE_ME
```

### Stack trace

```
REPLACE_ME
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [X] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by ka1mar** [comment]
Had the same, setting MLFLOW_TRACKING_URI environmental variable on server side (in my case MLFLOW_TRACKING_URI=mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}) solved the problem.

**Comment by ruanysheng** [comment]
> Had the same, setting MLFLOW_TRACKING_URI environmental variable on server side (in my case MLFLOW_TRACKING_URI=mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}) solved the problem.

Thanks @ka1mar, it is solved.

**Comment by B-Step62** [comment]
The basic-auth permission model has since been reworked (including default-permission handling). Closing due to inactivity, feel free to reopen if you still hit "Run id does not exist" for a non-admin user on a current MLflow version.
