### ISSUE TITLE
[FR] Support Johnsnowlabs 20K + SOTA NLP models  for over 200 languages

### ISSUE THREAD

**Issue by C-K-Loan** [mlflow/mlflow#8552]
### Willingness to contribute

Yes. I can contribute this feature independently.
See this PR  https://github.com/mlflow/mlflow/pull/8556

### Proposal Summary

Support every of the  20k+  model state-of-the-art models for 200+ languages from [johnsnowlabs](https://www.johnsnowlabs.com/) as MLFlow model, via easy `pyfunc` creation and `johnsnowlabs`  flavor
For a overview see [the modelshub](https://nlp.johnsnowlabs.com/models?q=cancer) 

### Motivation

> #### What is the use case for this feature?
Dozens of uses

> #### Why is this use case valuable to support for MLflow users in general?
20K+ Enterprise NLP models, easily usable in the mlflow ecosystem
Acces to LLM's, fine-tuned models for Entity Named Recongition, Summarization, Question answering,  Translation, Various Text classifiers, Audio To Speech, Image Classification, Spell Checking, Various Zero-Shot classifiers, Embeddings and much more! All in 1 line of code using the underlying nlu engine.
> #### Why is this use case valuable to support for your project(s) or organization?
We are Databricks partners and help the world put AI to good use in a scalable fashion with Databricks&Spark
> #### Why is it currently difficult to achieve this use case?
There is no direct support to use the johnsnowlabs models in mlflow

### Details

usage : 

## via Python
```python
from johnsnowlabs import nlp
import mlflow
import os

# Define environment variables, pprovided to you by johnsnowlabs
license_keys = { 
    "AWS_ACCESS_KEY_ID": "MY_AWS_ACCESS_KEY_ID"
    "AWS_SECRET_ACCESS_KEY": "MY_AWS_SECRET_ACCESS_KEY"
    "SPARK_NLP_LICENSE": "MY_SPARK_NLP_LICENSE"
    "SECRET": "MY_SECRET"
os.environ.update(license_keys)


# Download & Install Jars/Wheels if missing and Start a spark Session
nlp.start()

# load a model
model = nlp.load('tokenize')

# log model to mlflow server 
mlflow.johnsnowlabs.log_model(model, 'logged_model')

# Save model as pyfunc and johnsnowlabs format
mlflow.johnsnowlabs.save_model(model, 'saved_model')
model = mlflow.johnsnowlabs.load_model('saved_model')

# Save model as mleap
# todo 



```

## Via `mlflow models build-docker`
```shell
mlflow models build-docker --model-uri "MY_MODEL" --name "mlflow-pyfunc"
```

deploy local container (pyfunc format)
```shell
docker run -p 5001:8080 \
 -e AWS_ACCESS_KEY_ID=MY_AWS_ACCESS_KEY_ID\
 -e AWS_SECRET_ACCESS_KEY=MY_AWS_SECRET_ACCESS_KEY\
 -e SPARK_NLP_LICENSE=MY_SPARK_NLP_LICENSE\
 -e SECRET=MY_SECRET\
 "mlflow-pyfunc"
```

Query server
```shell
curl http://127.0.0.1:5001/invocations -H 'Content-Type: application/json' -d '{
  "dataframe_split": {                 
      "columns": ["text"],
      "data": [ [ "I hate covid"], ["I love covid"]]
  }
}'
```

## via `mlflow models serve` 

```shell
export AWS_ACCESS_KEY_ID=MY_AWS_ACCESS_KEY_ID
export AWS_SECRET_ACCESS_KEY=MY_AWS_SECRET_ACCESS_KEY
export SPARK_NLP_LICENSE=MY_SPARK_NLP_LICENSE
export SECRET=MY_SECRET
mlflow models serve -m /MY_MODEL
```

then send data to server

```shell 
curl http://127.0.0.1:5000/invocations -H 'Content-Type: application/json' -d '{
  "dataframe_split": {                 
      "columns": ["text"],
      "data": [ [ "I hate covid"], ["I love covid"]]
  }
}'
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [X] `area/examples`: Example code
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by C-K-Loan** [comment]
Resolved in https://github.com/mlflow/mlflow/pull/8556
