### ISSUE TITLE
[BUG] 'delete' button does not display after I selected runs

### ISSUE THREAD

**Issue by Jingnan-Jia** [mlflow/mlflow#8757]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 2.2.2
- Tracking server: 2.2.2

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: CentOS 7/8
- **Python version**: 3.8
- **yarn version, if running the dev UI**:

### Describe the problem

Normally, if I selected some runs in an experiment from  UI, a button 'delete' should appeared and once we click this button, the selected runs would be deleted (go to the trash), as shown bellow.

![1686838304485](https://github.com/mlflow/mlflow/assets/34941987/2cee5dc2-997e-4619-a268-48668c46e0ec)

The bug is: **sometimes, the button of 'delete' does not display so that I cannot delete the run from UI.** as shown below.

![image](https://github.com/mlflow/mlflow/assets/34941987/9d11f1cb-65ff-4b62-ae3d-72ab9a6225e3)

I used SQLite as the database backbone.

I guess the reason **may be** that I have too many runs (over 3000) under one experiment. It's funny because it's because I have so many runs that I'm going to delete some

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```
REPLACE_ME
```

### Stack trace

```
REPLACE_ME
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [X] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment]
Are you able to verify if the same behavior exists with the UI version of 2.4.1?

**Comment by Jingnan-Jia** [comment]
@BenWilson2 I just run "pip install mlflow --upgrade" to upgrade my mlflow. But the UI shows: "
Unable to display MLflow UI - landing page (index.html) not found.

You are very likely running the MLflow server using a source installation of the Python MLflow
package.

If you are a developer making MLflow source code changes and intentionally running a source
installation of MLflow, you can view the UI by running the Javascript dev server:
https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.md#running-the-javascript-dev-server

Otherwise, uninstall MLflow via 'pip uninstall mlflow', reinstall an official MLflow release
from PyPI via 'pip install mlflow', and rerun the MLflow server.
"

Is this because I upgraded mlflow during the training of my model? I thought mlflow could be upgraded even during the training.

**Comment by Jingnan-Jia** [comment]
yes, solved by upgrading mlflow to 2.4.1
