### ISSUE TITLE
[FR] Database schema migration support for basic auth schema

### ISSUE THREAD

**Issue by barrywhart** [mlflow/mlflow#8863]
### Willingness to contribute

No. I cannot contribute this feature at this time.

### Proposal Summary

The new basic auth support in MLflow works well, but it does not provide an the same support for potential future schema migrations as core MLflow (see the `mlflow db upgrade` [command](https://mlflow.org/docs/latest/cli.html#mlflow-db-upgrade)). It would be great to provide this capability.

### Motivation

> #### What is the use case for this feature?
Upgrading existing MLflow deployments that use basic auth, if/when the auth database schema changes in a future MLflow release.

> #### Why is this use case valuable to support for MLflow users in general?
Without support for this use case, early adopters of the basic auth feature will not have a smooth path forward if the schema changes in the future. This will likely prevent some potential users from adopting it.

> #### Why is this use case valuable to support for your project(s) or organization?
We are building an integration with Google App Engine and Cloud Run, using JWT. Our implementation mostly defers to the basic auth feature. For various reasons, including the lack of schema migration capability, we are constructing a private, local SQLite authorization database as each server instance (e.g. Docker container) starts up. If schema migration support were available, we would consider storing the authorization database in a shared database (e.g. Postgres or MySQL), the one we already use for the MLflow tracking store.

> #### Why is it currently difficult to achieve this use case?
The current implementation of basic auth uses a simple `create_all()` command to create the auth tables. There is no consideration for handling the case where a potential earlier version of the table schema has already been installed (and has existing records).

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [X] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@barrywhart Thanks for raising this, 100% agree, I'll work on this :)

**Comment by barrywhart** [comment]
Wonderful, thanks!

If you or anyone is interested, I'd be happy at some point to walk through how we are using (and extending) basic auth. It may give you other ideas for the future of MLflow authorization beyond the specific feature requests I created yesterday. One specific example -- we're configuring authorization at the group level rather than the individual level.

**Comment by barrywhart** [comment]
Thanks, @harupy! I hope we can adopt this soon after it is released.

**Comment by hoangelos** [comment]
So, I tried this and opened a bug on it.  @harupy  I'm running against Postgres. The error looks like it might be caused by confusion on which alembic.ini files it's grabbing.  It keeps trying to apply migrations from the store... One details is the I'm trying to store this in the same Schema as the tracking info and model registry store etc.

**Comment by hoangelos** [comment]
https://github.com/mlflow/mlflow/issues/10052

**Comment by barrywhart** [comment]
I think you have to create a different database. IIUC, Alembic doesn't support multiple schemas in one database.
