### ISSUE TITLE
[BUG] MLFlow crashes on Databricks - Run <run-id> not found

### ISSUE THREAD

**Issue by zimonitrome** [mlflow/mlflow#8877]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

- Client: 2.3.1
- Tracking server: No idea how to check this on Databricks but I think it's also 2.3.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.04.5 LTS
- **Python version**: 3.8

### Describe the problem

Running script with tracking_uri set to Databricks crashes the script and the run is not found.

I am specifically using the MMLabs/MMEngine integration of MLFlow.

### Tracking information

```shell
System information: Linux #41~20.04.1-Ubuntu SMP Mon May 22 18:18:00 UTC 2023
Python version: 3.8.16
MLflow version: 2.3.0
MLflow module location: /databricks/conda/envs/mlflow-3a1ac60e5aa02cd433353e1f872e0fdab605fb69/lib/python3.8/site-packages/mlflow/__init__.py
Tracking URI: databricks
Registry URI: databricks
MLflow environment variables: 
  MLFLOW_CONDA_HOME: /databricks/conda
  MLFLOW_EXPERIMENT_ID: 2124797230890366
  MLFLOW_PYTHON_EXECUTABLE: /databricks/spark/scripts/mlflow_python.sh
  MLFLOW_RUN_ID: f259d9b8fb954920a0a58f4e436570d1
  MLFLOW_TRACKING_URI: databricks
MLflow dependencies: 
  Flask: 2.3.2
  Jinja2: 3.1.2
  alembic: 1.11.1
  click: 8.1.3
  cloudpickle: 2.2.1
  databricks-cli: 0.17.7
  docker: 6.1.3
  entrypoints: 0.4
  gitpython: 3.1.31
  gunicorn: 20.1.0
  importlib-metadata: 6.7.0
  markdown: 3.4.3
  matplotlib: 3.7.1
  numpy: 1.24.3
  packaging: 23.1
  pandas: 2.0.2
  protobuf: 4.23.3
  pyarrow: 11.0.0
  pytz: 2023.3
  pyyaml: 6.0
  querystring-parser: 1.2.4
  requests: 2.29.0
  scikit-learn: 1.2.2
  scipy: 1.10.1
  sqlalchemy: 2.0.17
  sqlparse: 0.4.4
```

### Code to reproduce issue

I tried making a minimal example since running in Databricks is required for me.

https://github.com/zimonitrome/mmlabs_error_demo

### Stack trace

```
2023/06/27 15:05:49 INFO mlflow.utils.conda: === Creating conda environment mlflow-3a1ac60e5aa02cd433353e1f872e0fdab605fb69 ===
2023/06/27 15:11:59 INFO mlflow.projects.utils: === Created directory /tmp/tmp758h6q02 for downloading remote URIs passed to arguments of type 'path' ===
2023/06/27 15:11:59 INFO mlflow.utils.databricks_utils: No workspace ID specified; if your Databricks workspaces share the same host URL, you may want to specify the workspace ID (along with the host information in the secret manager) for run lineage tracking. For more details on how to specify this information in the secret manager, please refer to the Databricks MLflow documentation.
2023/06/27 15:11:59 INFO mlflow.projects.backend.local: === Running command 'source /databricks/conda/bin/../etc/profile.d/conda.sh && conda activate mlflow-3a1ac60e5aa02cd433353e1f872e0fdab605fb69 1>&2 && python mmsegmentation/tools/train.py stdc1_4xb12-80k_cityscapes-512x1024_custom.py' in run with ID '09a9ed543f3945558b787ad0dcf124e7' === 
/databricks/conda/envs/mlflow-3a1ac60e5aa02cd433353e1f872e0fdab605fb69/lib/python3.8/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: /databricks/conda/envs/mlflow-3a1ac60e5aa02cd433353e1f872e0fdab605fb69/lib/python3.8/site-packages/torchvision/image.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
  warn(f"Failed to load image Python extension: {e}")
Traceback (most recent call last):
  File "mmsegmentation/tools/train.py", line 104, in <module>
    main()
  File "mmsegmentation/tools/train.py", line 93, in main
    runner = Runner.from_cfg(cfg)
  File "/databricks/conda/envs/mlflow-3a1ac60e5aa02cd433353e1f872e0fdab605fb69/lib/python3.8/site-packages/mmengine/runner/runner.py", line 439, in from_cfg
    runner = cls(
  File "/databricks/conda/envs/mlflow-3a1ac60e5aa02cd433353e1f872e0fdab605fb69/lib/python3.8/site-packages/mmengine/runner/runner.py", line 395, in __init__
    self.visualizer.add_config(self.cfg)
  File "/databricks/conda/envs/mlflow-3a1ac60e5aa02cd433353e1f872e0fdab605fb69/lib/python3.8/site-packages/mmengine/dist/utils.py", line 366, in wrapper
    return func(*args, **kwargs)
  File "/databricks/conda/envs/mlflow-3a1ac60e5aa02cd433353e1f872e0fdab605fb69/lib/python3.8/site-packages/mmengine/visualization/visualizer.py", line 1068, in add_config
    vis_backend.add_config(config, **kwargs)
  File "/databricks/conda/envs/mlflow-3a1ac60e5aa02cd433353e1f872e0fdab605fb69/lib/python3.8/site-packages/mmengine/visualization/vis_backend.py", line 59, in wrapper
    return old_func(obj, *args, **kwargs)
  File "/databricks/conda/envs/mlflow-3a1ac60e5aa02cd433353e1f872e0fdab605fb69/lib/python3.8/site-packages/mmengine/visualization/vis_backend.py", line 751, in add_config
    self._mlflow.log_params(self._flatten(self.cfg))
  File "/databricks/conda/envs/mlflow-3a1ac60e5aa02cd433353e1f872e0fdab605fb69/lib/python3.8/site-packages/mlflow/tracking/fluent.py", line 700, in log_params
    run_id = _get_or_start_run().info.run_id
  File "/databricks/conda/envs/mlflow-3a1ac60e5aa02cd433353e1f872e0fdab605fb69/lib/python3.8/site-packages/mlflow/tracking/fluent.py", line 1552, in _get_or_start_run
    return start_run()
  File "/databricks/conda/envs/mlflow-3a1ac60e5aa02cd433353e1f872e0fdab605fb69/lib/python3.8/site-packages/mlflow/tracking/fluent.py", line 288, in start_run
    active_run_obj = client.get_run(existing_run_id)
  File "/databricks/conda/envs/mlflow-3a1ac60e5aa02cd433353e1f872e0fdab605fb69/lib/python3.8/site-packages/mlflow/tracking/client.py", line 158, in get_run
    return self._tracking_client.get_run(run_id)
  File "/databricks/conda/envs/mlflow-3a1ac60e5aa02cd433353e1f872e0fdab605fb69/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py", line 72, in get_run
    return self.store.get_run(run_id)
  File "/databricks/conda/envs/mlflow-3a1ac60e5aa02cd433353e1f872e0fdab605fb69/lib/python3.8/site-packages/mlflow/store/tracking/file_store.py", line 647, in get_run
    run_info = self._get_run_info(run_id)
  File "/databricks/conda/envs/mlflow-3a1ac60e5aa02cd433353e1f872e0fdab605fb69/lib/python3.8/site-packages/mlflow/store/tracking/file_store.py", line 670, in _get_run_info
    raise MlflowException(
mlflow.exceptions.MlflowException: Run '09a9ed543f3945558b787ad0dcf124e7' not found
2023/06/27 15:12:04 ERROR mlflow.cli: === Run (ID '09a9ed543f3945558b787ad0dcf124e7') failed ===
```

### Other info / logs

It seems to me like `_get_or_start_run()` is supposed to create a run if it does not exist but this just doesn't happen.

This bug is seemingly the same as #4176. I have also written about it in the MMEngine repo: https://github.com/open-mmlab/mmengine/issues/1217 but it seems to be an MLFlow problem (?).

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [X] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [X] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [X] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [X] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [X] `integrations/databricks`: Databricks integrations

**Comment by WeichenXu123** [comment]
Hi @zimonitrome In your linked example code, I don't find `mmsegmentation/tools/train.py` file, could you provide it ?

**Comment by WeichenXu123** [comment]
According to the error stack, I think `MLFLOW_RUN_ID` environment variable must be set to `09a9ed543f3945558b787ad0dcf124e7` so it skipped create run, see related code https://github.com/mlflow/mlflow/blob/152063e0b6fbadfbb2baecaf7d0ac7ca1b304b31/mlflow/tracking/fluent.py#L296C7-L296C7

Could you help check `mmengine` code set whether `MLFLOW_RUN_ID` environment variable somewhere ?

**Comment by zimonitrome** [comment]
Hell @WeichenXu123 thanks for your response. `mmsegmentation` is a git submodule in the repository I linked and can be found here: https://github.com/open-mmlab/mmsegmentation/blob/main/tools/train.py
You might need to do a `git submodule update --init --recursive` to get it manually when cloning the repo. I updated the readme to list this.

The MMLabs config file is read and imported by `train.py` as a python file and is the easiest file to modify to run code on Databricks. So I modified that file to read all environment variables by adding these lines:
```
import os
print(os.environ)
```
Do you think this sufficient to debug?

The MLFlow experiment I ran got assigned the Run ID ea5558c01d794f4698cd6777fbe8d932 in the UI:
![image](https://github.com/mlflow/mlflow/assets/17656709/517cc758-f2da-4b57-9182-6d406a26485b)
And the code printed that same ID: 
```
environ({
    'SHELL': '/bin/bash', 
    'PIP_NO_INPUT': '1', 
    'SUDO_GID': '0', 
    'CONDA_EXE': '/databricks/conda/bin/conda', 
    ...
    'SUDO_USER': 'root', 
    'MLFLOW_RUN_ID': 'ea5558c01d794f4698cd6777fbe8d932',
    ...
})
```

So I'm pretty sure the `MLFLOW_RUN_ID` is set correctly. I even tried this a few days ago with a larger script (not the minimum example I provided) where I modified the `train.py` and could also see the `MLFLOW_RUN_ID` environment variable set correctly.

> It looks like mmengine code does not use mlflow correctly

Yes this is what I have been thinking too. But it seems like `_get_or_start_run()` should work in this instance and I also see people having similar problems in #4176.

**Comment by WeichenXu123** [comment]
Could you help check which tracking URI does the `train.py` uses ?

It might have a different tracking URI with the tracking URI that you use to view the UI portal. So that you can find the run ID in UI portal but you got non-existed run ID in `train.py`

**Comment by zimonitrome** [comment]
How do I check my Databricks tracking URI? Is it this one?
![image](https://github.com/mlflow/mlflow/assets/17656709/71d9827f-aa8d-4182-a810-ef8f34ff45be)

I'm a little bit unsure of how to check the tracking URI in `train.py` too. On my local PC I set it to `databricks` to make it automatically run on my Databricks server. When using the previously mentioned method of adding
```
import os
print(os.environ)
```
in my `config.py` (which is loaded by `train.py`) I also see `'MLFLOW_TRACKING_URI': 'databricks'`. But this is also the case with an older script (not MMLabs) where running on Databricks works.

Is there a better way to check `tracking_URI`? Should I modify a file deeper down the stack trace?

**Comment by WeichenXu123** [comment]
thank you.

could you add one line `print(mlflow.mlflow.get_tracking_uri())` to get the actual tracking URI ? (add the line before the line that raises the exception), if it print "databricks", then tracking URI is correct.

**Comment by WeichenXu123** [comment]
No response. I will close it. We can reopen it once there is new response
