### ISSUE TITLE
[FR] Authorization module should support other methods for determining the user's identity

### ISSUE THREAD

**Issue by barrywhart** [mlflow/mlflow#9066]
### Willingness to contribute

Yes. I would be willing to contribute this feature with guidance from the MLflow community.

### Proposal Summary

In our MLflow deployment, we use MLflow's "basic auth" module as a starting point for _authorization_, but we don't use it for _authentication_. Our deployment authenticates using JWT. It would be great if MLflow either supported JWT directly or provided a way to do this through configuration + a bit of custom code. Currently, we have to monkeypatch MLflow to do this.

### Motivation

> #### What is the use case for this feature?
Authorization is a really valuable feature, especially for medium-sized and larger companies that use MLflow. The current basic auth module has a lot of useful functionality, but not everyone uses basic auth for authentication. 

JWT, or JSON Web Token, is a compact method of securely transmitting claims or information between two parties in the form of a JSON object. These claims are encoded and can be digitally signed or integrity protected, making them trustworthy. JWTs are prevalent in many sectors due to their versatility and ease of use, particularly in microservices architectures and single sign-on environments where user identity verification is crucial.

> #### Why is this use case valuable to support for MLflow users in general?

JWTs are widely used in the industry due to their simplicity and versatility. They are commonly used for authentication and secure information exchange, and are particularly prevalent in microservices architectures, where services need a lightweight and standard way to verify the identity of callers.

JWTs are used to create access tokens for user identity verification in applications, especially in the context of single sign-on (SSO) environments. They are a self-contained way for securely transmitting information between parties as a JSON object, and this information can be verified and trusted because it is digitally signed.

The three major cloud providers all support JWT:
* Google Cloud Platform uses JWTs for many of its services, like Google App Engine and Google Cloud Run. They also use JWTs for server-to-server authentication.
* Amazon Web Services uses JWTs in a few different ways. For example, Amazon Cognito uses JWTs to handle user authentication and authorization. In addition, AWS App Runner, similar to Google Cloud Run, can also use JWTs for passing the user's identity.
* Microsoft Azure: Azure uses JWTs in Azure Active Directory for user authentication and authorization. JWTs are used as bearer tokens in Azure to authenticate the calls to your web APIs.

> #### Why is this use case valuable to support for your project(s) or organization?
Our organization uses Google Cloud, specifically Google App Engine and Google Cloud Run. These two environments have direct support for JWT. If authentication is enabled, they automatically pass the user's identity in the `email` field of the following headers:
* `Authorization`: Cloud Run
* `x-goog-iap-jwt-assertion`: App Engine

> #### Why is it currently difficult to achieve this use case?

Currently, only basic authentication (user name / password) is supported. To support JWT, we have to monkeypatch MLflow. This works but is not very "clean", as it relies in internal implementation details of the basic auth module and of MLflow (e.g. its use of the Werkzeug web framework.)

### Details

For now, we use monkeypatching to force MLflow to call our function:
```
from werkzeug.wrappers import Request

def get_auth_info_from_request(request) -> Optional[Authorization]:
    """Given request, build & return Authorization object based on JWT token."""
    ...

# Override field access so basic auth will call our function instead.
Request.authorization = property(lambda self: get_auth_info_from_request(self))
```

It would be cool if we could do this without monkeypatching. A couple of possible approaches:
* Define a new [plugin type](https://mlflow.org/docs/latest/plugins.html#defining-a-plugin), `mlflow.identity_provider`. If there's a package installed which provides this entry point, authorization uses it automatically.
* Add support for a new, optional setting, e.g. `identity_provider`, in the auth config file (`basic_auth.ini`). It specifies a module and function name that returns the user's identity.

Our use case only requires authorization, not authentication, although if it seems useful, the same function could do both (e.g. throw an exception or return `None` if the user is not authenticated).

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/gateway`: AI Gateway service, Gateway client APIs, third-party Gateway integrations
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [X] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@barrywhart Thanks for the FR! This sounds reasonable to me.

> Add support for a new, optional setting, e.g. identity_provider, in the auth config file (basic_auth.ini). It specifies a module and function name that returns the user's identity.

The second option (adding an optional field in the config) sounds more appealing to me because you don't need to create a package.

> Our use case only requires authorization, not authentication, although if it seems useful, the same function could do both (e.g. throw an exception or return None if the user is not authenticated).

Can you elaborate on this?

**Comment by barrywhart** [comment]
Sure!

Our MLflow deployment runs on App Engine and Cloud Run, where Google Cloud _itself_ authenticates each request prior to forwarding it to the MLflow server instance.

Thus, for our deployment, we provide a function that examines a JWT token in the header, extracts the user's email address (i.e. user name) and returns it. It does not need to authenticate (i.e. validating a token or checking a password). Then the "basic auth" provider performs authorization based on the identity returned.

My point is that, if this FR is implemented, some users of the feature _may_ want to authenticate, even though we don't.

Does this make sense? If not, I can provide some pseudocode which may be clearer.

**Comment by harupy** [comment]
@barrywhart Thanks for the reply!

> I can provide some pseudocode which may be clearer.

Code always helps. Can you provide pseudocode?

**Comment by barrywhart** [comment]
In MLflow 2.3.2, we see this code:

```
@catch_mlflow_exception
def _before_request():
    if is_unprotected_route(request.path):
        return

    _user = request.authorization.username if request.authorization else None
    _logger.debug(f"before_request: {request.method} {request.path} (user: {_user})")
```

A number of functions also directly access `request.authorization.username`, e.g.
```
def _get_permission_from_experiment_id() -> Permission:
    experiment_id = _get_request_param("experiment_id")
    username = request.authorization.username
    return _get_permission_from_store_or_default(
        lambda: store.get_experiment_permission(experiment_id, username).permission
    )
```

I propose adding a level of indirection, i.e. rather than accessing `request.authorization` directly, instead something like (probably with appropriate caching of the function lookup):

```
import importlib

from werkzeug.datastructures import Authorization

def get_request_authorization(request) -> Optional[Authorization]:
    module_name, func_name = auth_config.authorization_function.rsplit('.', 1)
    module = importlib.import_module(module_name)
    auth_func = getattr(module, func_name)
    return auth_func(request)
```

This is the actual function we use for JWT in Google Cloud. If this feature were implemented, we would configure MLflow to call this function. Currently, though, we use monkeypatching.

```
import base64
import logging

from google.auth import jwt

BEARER_PREFIX = "bearer "

_logger = logging.getLogger(__name__)


def get_jwt_authorization_info(request) -> Optional[Authorization]:
    """Given request, build & return Authorization object based on JWT token."""
    _logger.debug("Getting token")
    # In Cloud Run, we receive the token in the "Authorization" header.
    # In App Engine, we receive it in the "x-goog-iap-jwt-assertion" header.
    # https://cloud.google.com/iap/docs/signed-headers-howto#securing_iap_headers
    # In the former case, the token is prefixed with "Bearer ", but in the latter
    # case it is not.
    token = request.headers.get(
        "Authorization", request.headers.get("x-goog-iap-jwt-assertion")
    )
    if token:
        _logger.debug(f"Verifying token")
        if token.lower().startswith("basic "):
            # "basic" means HTTP basic authentication, which is used for local
            # testing. The token is base64-encoded, so we need to decode it.
            # This will never happen in production because Google authenticates
            # the user before the request reaches the service.
            token = base64.b64decode(token.split(" ")[1]).decode(
                "utf-8"
            )  # Remove "basic " prefix
            # Split the string into email and password. We discard the password,
            # because this behavior is only for local testing, and this function
            # is not responsible for authenticating the user, only for extracting
            # the username for _authorization_.
            email, _ = token.split(":")
            email = _apply_impersonation(request, email)
            return Authorization(
                auth_type="jwt", data=dict(username=email, password="")
            )
        elif token.lower().startswith(BEARER_PREFIX):
            token = token[len(BEARER_PREFIX) :]  # Remove prefix

        # Note: Rather than google.oauth2.id_token.verify_oauth2_token(), we use
        # jwt.decode() with verification disabled. That's because within the
        # Cloud Run service, Google has already verified the token (thus we
        # don't NEED to verify it) and removed the signature (thus we CAN'T
        # verify it).
        # https://cloud.google.com/run/docs/authenticating/service-to-service#authenticating_end-users
        token_info = jwt.decode(token, verify=False)
        if not token_info:  # pragma: no cover
            _logger.warning("No token_info returned")
            return None

        email = token_info["email"]
        return Authorization(auth_type="jwt", data=dict(username=email, password=""))
    else:  # pragma: no cover
        _logger.warning("Missing or invalid authorization token")
        return None
```

**Comment by harupy** [comment]
@barrywhart Thanks for the code! It looks like `password` is always discarded?

**Comment by harupy** [comment]
I'm wondering what `_before_request` would look like with your proposal:

https://github.com/mlflow/mlflow/blob/00c9b423e2fa33ead427f90b5c731a29b5bd7737/mlflow/server/auth/__init__.py#L417-L442

**Comment by barrywhart** [comment]
> I'm wondering what `_before_request` would look like with your proposal:

Good question! My proposal focuses on authorization rather than authentication because of the way it is deployed in our environment (because Google Cloud handles authentication). But the proposal definitely needs to co-exist with authentication, especially the existing support for basic authentication.

I propose modifying the signature of the proposed `get_request_authorization` function to:

```
def get_request_authorization(request) -> Union[Authorization, Response]
```

By allowing this function to return either `Authorization` or `Response`, it can handle both:
* Successful authentication: Returns an `Authorization` object
* Unsuccessful authentication: Returns a `Response` object, appropriately populated based on the authentication scheme.

With that change, the default (basic auth) implementation of `get_request_authorization` will be:
```
def get_request_authorization(request)  -> Union[Authorization, Response]:
    if request.authorization is None:
        return make_basic_auth_response()

    username = request.authorization.username
    password = request.authorization.password
    if store.authenticate_user(username, password):
        return request.authorization
    else:
        # let user attempt login again
        return make_basic_auth_response()
```

 And `_before_request` becomes:

```

@catch_mlflow_exception
def _before_request():
    if is_unprotected_route(request.path):
        return

    authorization = get_request_authorization(request)
    if isinstance(authorization, Response):
        return authorization
    elif not isinstance(authorization, Authorization):
        raise MlflowException(
            f"Unsupported result type from get_request_authorization: '{type(authorization).__name__}'",
            INTERNAL_ERROR,
        )     

    username = request.authorization.username

    # ... From here to the end of the function, no changes ...

    # admins don't need to be authorized
    if sender_is_admin():
        _logger.debug(f"Admin (username={username}) authorization not required")
        return

    # authorization
    if validator := BEFORE_REQUEST_VALIDATORS.get((request.path, request.method)):
        _logger.debug(f"Calling validator: {validator.__name__}")
        if not validator():
            return make_forbidden_response()
    else:
        _logger.debug(f"No validator found for {(request.path, request.method)}")

```

With JWT, `handle_unauthorized_request` might be implemented as:

```
def get_request_authorization() -> Union[Authorization, Response]:
    _logger.debug("Getting token")
    # In Cloud Run, we receive the token in the "Authorization" header.
    # In App Engine, we receive it in the "x-goog-iap-jwt-assertion" header.
    # https://cloud.google.com/iap/docs/signed-headers-howto#securing_iap_headers
    # In the former case, the token is prefixed with "Bearer ", but in the latter
    # case it is not.
    token = request.headers.get(
        "Authorization", request.headers.get("x-goog-iap-jwt-assertion")
    )
    if token:
        _logger.debug(f"Verifying token")
        if token.lower().startswith("basic "):
            # "basic" means HTTP basic authentication, which is used for local
            # testing. The token is base64-encoded, so we need to decode it.
            # This will never happen in production because Google authenticates
            # the user before the request reaches the service.
            token = base64.b64decode(token.split(" ")[1]).decode(
                "utf-8"
            )  # Remove "basic " prefix
            # Split the string into email and password. We discard the password,
            # because this behavior is only for local testing, and this function
            # is not responsible for authenticating the user, only for extracting
            # the username for _authorization_.
            email, _ = token.split(":")
            email = _apply_impersonation(request, email)
            return Authorization(
                auth_type="jwt", data=dict(username=email, password="")
            )
        elif token.lower().startswith(BEARER_PREFIX):
            token = token[len(BEARER_PREFIX) :]  # Remove prefix

        error_response =     make_response()
        error_response.status_code = 401
        error_response.set_data(
            "You are not authenticated. Please provide a valid JWT Bearer token with the request."
        )
        error_response.headers["WWW-Authenticate"] = 'Bearer error="invalid_token"'

        # Note: Rather than google.oauth2.id_token.verify_oauth2_token(), we use
        # jwt.decode() with verification disabled. That's because within the
        # Cloud Run service, Google has already verified the token (thus we
        # don't NEED to verify it) and removed the signature (thus we CAN'T
        # verify it).
        # https://cloud.google.com/run/docs/authenticating/service-to-service#authenticating_end-users
        token_info = jwt.decode(token, verify=False)
        if not token_info:  # pragma: no cover
            _logger.warning("No token_info returned")
            return error_response

        email = token_info["email"]
        return Authorization(auth_type="jwt", data=dict(username=email, password=""))
    else:  # pragma: no cover
        _logger.warning("Missing or invalid authorization token")
        return error_response
```

Below are some resources regarding the format of the `Bearer error` response. 
* https://datatracker.ietf.org/doc/html/rfc6750#section-3
* https://stackoverflow.com/questions/57343599/auth0-api-returning-401-www-authenticate-bearer-error-invalid-token-in-net-c
* https://stackoverflow.com/questions/55781040/401-unauthorized-www-authenticate-bearer

Since

**Comment by barrywhart** [comment]
I'm beginning work on a PR for this.

**Comment by barrywhart** [comment]
PR: #9191
