### ISSUE TITLE
[FR] Allow Poetry MathJax Specification

### ISSUE THREAD

**Issue by stroblme** [mlflow/mlflow#9149]
### Willingness to contribute

Yes. I can contribute this feature independently.

### Proposal Summary

While logging a Plotly figure with MlFlow using the `mlflow.log_figure(...)` method works well in principle, it is not possible to specify further arguments available by the `.write_html(...)` method (see [documentation](https://plotly.com/python/interactive-html-export/#full-parameter-documentation) in Plotly.
This however is necessary if the figure includes Latex/MathJax formulas as those are not being rendered correctly in the resulting html artifact (see [this Stackoverflow question](https://stackoverflow.com/questions/71735053/save-plotly-figure-interactively-html-whilst-preserving-latex-font)).
Therefore I propose to add either `**kwargs` or the more specific `include_mathjax` argument to `mlflow.log_figure(...)` that then can be passed to the underlying `.write_html(...)` method.

### Motivation

> #### What is the use case for this feature?
Logging interactive (html) Plotly figures that include Latex/MathJax formulas.

> #### Why is this use case valuable to support for MLflow users in general?
Otherwise, formulas in interactive figures are not being rendered correctly.

> #### Why is this use case valuable to support for your project(s) or organization?
See above.

> #### Why is it currently difficult to achieve this use case?
To my best knowledge, the only possible workaround is:
- writing a json based plotly figure
- loading this figure in a separate python script
- injecting the above mentioned `include_mathjax` argument
- saving the figure using the Plotly API directly
This is way more difficult compared to directly specifying the required argument in `mlflow.log_figure(...)

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/gateway`: AI Gateway service, Gateway client APIs, third-party Gateway integrations
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [X] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@stroblme Thanks for the proposal! It seems reasonable to me :) Adding `**kwargs` sounds more appealing because `log_figure` also supports matplotlib.
