### ISSUE TITLE
[BUG] mlflow version compatibility issues for deployment and tracking

### ISSUE THREAD

**Issue by nfarley-soaren** [mlflow/mlflow#9368]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 1.29.0 and 2.5.0
- Tracking server: 1.27.0 and 2.4.1

### System information

- **OS: Amazon Linux 2**:
- **Python version: 3.10.4**:

### Describe the problem

I'm running into a few problems that are related.  I recently upgraded to using mlflow 2.4+ for both development and tracking but ran into errors during deployment to Sagemaker.  When using v1.29 or 1.30 I ran into an issue similar to the [following](https://github.com/mlflow/mlflow/issues/9259#issuecomment-1681426136) when deploying to a t2.medium instance and had to scale up to a large instance when including certain packages in the environment.  Since the upgrade to v2, the larger instance has also started to fail and the same environment now requires an xlarge instance.  This cost inflation isn't really feasible for my use cases so I tried downgrading the version being used in development back to v1 for new models.  When I did this, I received and error similar to the one seen in this [issue](https://github.com/mlflow/mlflow/issues/5171) when trying to log the new model to the upgraded tracking server.  I then tried to downgrade the tracking server to what I was using before the upgrade (back to 1.27 from 2.4.1) to allow me to register models built with v1 but received a 502 error.   I believe this is due to the fact that I have already developed and registered models using mlflow v2 though I'm still looking into it.  I'm concerned about the compatibility issues between mlflow versions.  I can't use a newer version of mlflow for deployment due to the cost inflation of having to use a larger instance.  I can't register a model built with an earlier version to the tracking server and I can't downgrade due to what I believe are the same compatibility issues.  I don't know how hard it would be to make different versions of mlflow compatible but I'm hoping this will be addressed.  Or if there's something I'm missing, please let me know.  I'm still working on troubleshooting on my end.  

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

It is version specific, not a normal code error.

### Stack trace

Error when trying to register a model built using 1.29.0 to the tracking server running 2.4.1
```
Traceback (most recent call last):
  File "/tmp/tmpjqmh7z_q/conversion/conversion.py", line 386, in <module>
    results = build_models(
  File "/tmp/tmpjqmh7z_q/modeling_tools/modeling.py", line 628, in build_models
    results = build_final(train_test_model_args)
  File "/tmp/tmpjqmh7z_q/modeling_tools/modeling.py", line 1656, in build_final
    return train_test_model(train_test_model_args, save_model=True)
  File "/tmp/tmpjqmh7z_q/modeling_tools/modeling.py", line 1241, in train_test_model
    mlflow.pyfunc.log_model(
  File "/home/mgrimmett/miniconda3/envs/mlflow-a2320038b5072a8680f191687d88b0be5f0a29c0/lib/python3.10/site-packages/mlflow/pyfunc/__init__.py", line 1335, in log_model
    return Model.log(
  File "/home/mgrimmett/miniconda3/envs/mlflow-a2320038b5072a8680f191687d88b0be5f0a29c0/lib/python3.10/site-packages/mlflow/models/model.py", line 382, in log
    mlflow.register_model(
  File "/home/mgrimmett/miniconda3/envs/mlflow-a2320038b5072a8680f191687d88b0be5f0a29c0/lib/python3.10/site-packages/mlflow/tracking/_model_registry/fluent.py", line 74, in register_model
    raise e
  File "/home/mgrimmett/miniconda3/envs/mlflow-a2320038b5072a8680f191687d88b0be5f0a29c0/lib/python3.10/site-packages/mlflow/tracking/_model_registry/fluent.py", line 65, in register_model
    create_model_response = client.create_registered_model(name)
  File "/home/mgrimmett/miniconda3/envs/mlflow-a2320038b5072a8680f191687d88b0be5f0a29c0/lib/python3.10/site-packages/mlflow/tracking/client.py", line 1782, in create_registered_model
    return self._get_registry_client().create_registered_model(name, tags, description)
  File "/home/mgrimmett/miniconda3/envs/mlflow-a2320038b5072a8680f191687d88b0be5f0a29c0/lib/python3.10/site-packages/mlflow/tracking/_model_registry/client.py", line 59, in create_registered_model
    return self.store.create_registered_model(name, tags, description)
  File "/home/mgrimmett/miniconda3/envs/mlflow-a2320038b5072a8680f191687d88b0be5f0a29c0/lib/python3.10/site-packages/mlflow/store/model_registry/rest_store.py", line 83, in create_registered_model
    response_proto = self._call_endpoint(CreateRegisteredModel, req_body)
  File "/home/mgrimmett/miniconda3/envs/mlflow-a2320038b5072a8680f191687d88b0be5f0a29c0/lib/python3.10/site-packages/mlflow/store/model_registry/rest_store.py", line 64, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "/home/mgrimmett/miniconda3/envs/mlflow-a2320038b5072a8680f191687d88b0be5f0a29c0/lib/python3.10/site-packages/mlflow/utils/rest_utils.py", line 274, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "/home/mgrimmett/miniconda3/envs/mlflow-a2320038b5072a8680f191687d88b0be5f0a29c0/lib/python3.10/site-packages/mlflow/utils/rest_utils.py", line 206, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/preview/mlflow/registered-models/create failed with error code 404 != 200. Response body: '<!doctype html>
<html lang=en>
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>
'
```

### Other info / logs

One of the errors seen when deploying model built with 2.5.0 to Sagemaker - from AWS Cloudwatch
```
Writing to /root/.config/pip/pip.conf
2023/04/17 18:00:34 INFO mlflow.models.container: creating and activating custom environment
CondaValueError: prefix already exists: /miniconda/envs/custom_env
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/miniconda/lib/python3.9/site-packages/mlflow/models/container/__init__.py", line 57, in _init
    _serve(env_manager)
  File "/miniconda/lib/python3.9/site-packages/mlflow/models/container/__init__.py", line 84, in _serve
    _serve_pyfunc(m, env_manager)
  File "/miniconda/lib/python3.9/site-packages/mlflow/models/container/__init__.py", line 156, in _serve_pyfunc
    _install_pyfunc_deps(
  File "/miniconda/lib/python3.9/site-packages/mlflow/models/container/__init__.py", line 117, in _install_pyfunc_deps
    raise Exception("Failed to create model environment.")
Exception: Failed to create model environment.
```
Different error seen when deploying a different model to Sagemaker
```
Writing to /root/.config/pip/pip.conf
2023/08/10 19:20:30 INFO mlflow.models.container: creating and activating custom environment
ERROR conda.auxlib.logz:stringify(171): 
Traceback (most recent call last):
  File "/miniconda/lib/python3.10/site-packages/conda/auxlib/logz.py", line 165, in stringify
    requests_models_Response_builder(builder, obj)
  File "/miniconda/lib/python3.10/site-packages/conda/auxlib/logz.py", line 143, in requests_models_Response_builder
    content = dumps(resp, indent=2)
  File "/miniconda/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/miniconda/lib/python3.10/json/encoder.py", line 202, in encode
    return ''.join(chunks)
MemoryError
Collecting package metadata (repodata.json): ...working... done
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/gateway`: AI Gateway service, Gateway client APIs, third-party Gateway integrations
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [X] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [X] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [X] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [X] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment]
Hi @nfarley-soaren would you happen to have the diff of libraries being installed between the two container versions? Are there libraries being included in the containers that are definitely not required in order to serve your model type?

**Comment by nfarley-soaren** [comment]
@BenWilson2 The only difference between the libraries installed between the two containers is the version of mlflow.  It was tested with only that difference.  But I know that a number of additional libraries get installed automatically in the container environment.
