### ISSUE TITLE
[FR] Allow more special characters in metric and parameter names

### ISSUE THREAD

**Issue by TomSteenbergen** [mlflow/mlflow#9425]
### Willingness to contribute

Yes. I would be willing to contribute this feature with guidance from the MLflow community.

### Proposal Summary

At the moment, it is not possible to log metrics or parameters with special characters in their names, e.g. `MAP@k` (a common ranking metric) or `huber_loss[delta=1.3]`, which is oftentimes desirable when you have metrics that can be configured with certain parameters. 

Looking in [mlflow/utils/validation.py](https://github.com/mlflow/mlflow/blob/master/mlflow/utils/validation.py) the only characters allowed are:

```python
# Regex for valid param and metric names: may only contain slashes, alphanumerics,
# underscores, periods, dashes, and spaces.
_VALID_PARAM_AND_METRIC_NAMES = re.compile(r"^[/\w.\- ]*$")
```

It would be great if we could extend the regex to allow characters such as `@ = , [ ]`, giving users more freedom and flexibility in creating human readable metric and parameter names.

### Motivation

> #### What is the use case for this feature?

Enable more freedom in naming metrics and parameters.

> #### Why is this use case valuable to support for MLflow users in general?

It improves user experience.

> #### Why is this use case valuable to support for your project(s) or organization?

Makes it easier to read more complex metric names.

> #### Why is it currently difficult to achieve this use case?

We need work around this by using other characters, oftentimes resulting in less human-readable names.

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/gateway`: AI Gateway service, Gateway client APIs, third-party Gateway integrations
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [X] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment]
Unfortunately, these reserved characters are intentionally disallowed in order to provide a consistent, secure, and displayable metric or parameter key within the SDKs, tracking databases, and in the UI. We particularly do not wish to allow special characters that have reserved meanings with URL encodings (``[]()&?@*``)
Sorry for the inconvenience here!

**Comment by juanmirocks** [comment]
@BenWilson2 @harupy 

Any chance to revise this decision?

Similar as the OP, I'd like to name my metric `R@P` (i.e. Recall at Precision) and thus I'd like to have at least the `@` character allowed. It's a common naming pattern.
