### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by matthias-roussel-soyhuce** [mlflow/mlflow#9553]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 2.6.0
- Tracking server: 2.6.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 22.04
- **Java version**: 17
- **yarn version, if running the dev UI**: N/A

### Describe the problem

I'm using the Java tracking API and attempting to log a substantial number of metrics in a single call using `MlflowClient.logBatch`. 

Expected behavior: This code is expected to create a new run and log a single metric to it.

Actual behavior: However the server doesn't accept the list of metrics, despite working fine for params (if the `metrics` argument is `null` and the `params` argument provided). The run is created but no metric is logged.

I can't run the doctor as it is not included in the Java API.

### Tracking information

```shell
(Doctor not available in Java API.)
```

### Code to reproduce issue

```
package org.acme.mlflow;

import org.mlflow.api.proto.Service;
import org.mlflow.tracking.MlflowClient;

import java.util.ArrayList;
import java.util.List;

public class Main {

    public static void main(String[] args) {
        MlflowClient client = new MlflowClient();
        List<Service.Metric> metrics = new ArrayList<>();
        Service.Metric.Builder metricBuilder = Service.Metric.newBuilder();
        metricBuilder.setKey("metric");
        metricBuilder.setValue(0.0);
        Service.Metric metric = metricBuilder.build();
        metrics.add(metric);

        Service.RunInfo run = client.createRun();
        client.logBatch(run.getRunId(), metrics, null, null);
    }
}

```

### Stack trace

```
2023-09-07 18:11:43,120 [main] WARN  Request returned with status code 400 (Rate limit exceeded). Retrying up to 2 more times. Response body: {"error_code": "INVALID_PARAMETER_VALUE", "message": "Invalid value [{'key': 'metric', 'value': 0.0}] for parameter 'metrics' supplied. Hint: Value was of type 'list'. See the API docs for more information about request parameters."}
2023-09-07 18:11:43,247 [main] WARN  Request returned with status code 400 (Rate limit exceeded). Retrying up to 1 more times. Response body: {"error_code": "INVALID_PARAMETER_VALUE", "message": "Invalid value [{'key': 'metric', 'value': 0.0}] for parameter 'metrics' supplied. Hint: Value was of type 'list'. See the API docs for more information about request parameters."}
Exception in thread "main" org.mlflow.tracking.MlflowHttpException: statusCode=400 reasonPhrase=[Bad Request] bodyMessage=[{"error_code": "INVALID_PARAMETER_VALUE", "message": "Invalid value [{'key': 'metric', 'value': 0.0}] for parameter 'metrics' supplied. Hint: Value was of type 'list'. See the API docs for more information about request parameters."}]
	at org.mlflow.tracking.MlflowHttpCaller.checkError(MlflowHttpCaller.java:193)
	at org.mlflow.tracking.MlflowHttpCaller.executeRequestWithRateLimitRetries(MlflowHttpCaller.java:104)
	at org.mlflow.tracking.MlflowHttpCaller.executeRequest(MlflowHttpCaller.java:114)
	at org.mlflow.tracking.MlflowHttpCaller.send(MlflowHttpCaller.java:178)
	at org.mlflow.tracking.MlflowHttpCaller.post(MlflowHttpCaller.java:164)
	at org.mlflow.tracking.MlflowClient.sendPost(MlflowClient.java:562)
	at org.mlflow.tracking.MlflowClient.logBatch(MlflowClient.java:529)
	at fr.soyhuce.algorh.plaf.Main.main(Main.java:23)

Process finished with exit code 1
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/gateway`: AI Gateway service, Gateway client APIs, third-party Gateway integrations
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [X] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment]
Can you try setting the required timestamp value as part of the metric builder constructor? This field is required. 

Here is what happens from the server side from the python client API when omitting (or explicitly setting `None` as a value in Python when constructing a ``Metric`` instance) the proto interpreter will raise the exception for this issue much more clearly from the Python APIs than from the JavaAPIs (due to the Java API being a wrapper around REST requests instead of a native Java implementation):

```python

from mlflow.entities import Metric, Param, RunTag

run = client.create_run(experiment_id=0)

metrics = [Metric("metric", 1, None, 1), Metric("metric2", 2, None, 1), Metric("metric3", 3, None, 1)]

params = [Param("param", "a"), Param("param2", "b")]

client.log_batch(run_id=run.info.run_id, metrics=metrics, params=params)
```

Stack trace result:
```bash
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/miniconda3/envs/mlflow-dev-env/lib/python3.8/site-packages/google/protobuf/internal/python_message.py in field_setter(self, new_value)
    701     try:
--> 702       new_value = type_checker.CheckValue(new_value)
    703     except TypeError as e:

~/miniconda3/envs/mlflow-dev-env/lib/python3.8/site-packages/google/protobuf/internal/type_checkers.py in CheckValue(self, proposed_value)
    166                  (proposed_value, type(proposed_value), (int,)))
--> 167       raise TypeError(message)
    168 

TypeError: None has type <class 'NoneType'>, but expected one of: (<class 'int'>,)

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
/var/folders/cd/n8n0rm2x53l_s0xv_j_xklb00000gp/T/ipykernel_67654/2526191017.py in <cell line: 9>()
      7 params = [Param("param", "a"), Param("param2", "b")]
      8 
----> 9 client.log_batch(run_id=run.info.run_id, metrics=metrics, params=params)

~/repos/mlflow-fork/mlflow/mlflow/tracking/client.py in log_batch(self, run_id, metrics, params, tags)
   1036             status: FINISHED
   1037         """
-> 1038         self._tracking_client.log_batch(run_id, metrics, params, tags)
   1039 
   1040     @experimental

~/repos/mlflow-fork/mlflow/mlflow/tracking/_tracking_service/client.py in log_batch(self, run_id, metrics, params, tags)
    387             metrics = metrics[metrics_batch_size:]
    388 
--> 389             self.store.log_batch(
    390                 run_id=run_id, metrics=metrics_batch, params=params_batch, tags=tags_batch
    391             )

~/repos/mlflow-fork/mlflow/mlflow/store/tracking/rest_store.py in log_batch(self, run_id, metrics, params, tags)
    316 
    317     def log_batch(self, run_id, metrics, params, tags):
--> 318         metric_protos = [metric.to_proto() for metric in metrics]
    319         param_protos = [param.to_proto() for param in params]
    320         tag_protos = [tag.to_proto() for tag in tags]

~/repos/mlflow-fork/mlflow/mlflow/store/tracking/rest_store.py in <listcomp>(.0)
    316 
    317     def log_batch(self, run_id, metrics, params, tags):
--> 318         metric_protos = [metric.to_proto() for metric in metrics]
    319         param_protos = [param.to_proto() for param in params]
    320         tag_protos = [tag.to_proto() for tag in tags]

~/repos/mlflow-fork/mlflow/mlflow/entities/metric.py in to_proto(self)
     38         metric.key = self.key
     39         metric.value = self.value
---> 40         metric.timestamp = self.timestamp
     41         metric.step = self.step
     42         return metric

~/miniconda3/envs/mlflow-dev-env/lib/python3.8/site-packages/google/protobuf/internal/python_message.py in field_setter(self, new_value)
    702       new_value = type_checker.CheckValue(new_value)
    703     except TypeError as e:
--> 704       raise TypeError(
    705           'Cannot set %s to %.1024r: %s' % (field.full_name, new_value, e))
    706     if clear_when_set_to_default and not new_value:

TypeError: Cannot set mlflow.Metric.timestamp to None: None has type <class 'NoneType'>, but expected one of: (<class 'int'>,)
```

**Comment by matthias-roussel-soyhuce** [comment]
That was it. Thanks a lot for the solution.
